/* Teksty modułu ue — język: cs.
   Te same klucze co w napisy/pl.js (wersja źródłowa); wstawki {p0}, {p1}…
   pozostają bez zmian. Klucze ue.cyt.* to wzorce składania odesłań
   do przepisów w tym języku — patrz kraje/ue/cytaty.js. */
KRAJE.napisy('ue', 'cs', {
    "app.10": "Zkontrolujte seznam rolí níže — o statusu rozhoduje skutečně vykonávaná činnost (článek 3 směrnice (EU) 2022/2555), nikoli zápis v rejstříku.",
    "app.14": "Předchozí rok: {p0} EUR",
    "app.15": "Obrat za vykazované období: {p0} EUR",
    "app.19": "Dotazuji rejstříky podle čísla {p0}…",
    "app.34": " mld. EUR",
    "app.35": " mil. EUR",
    "app.36": " tis. EUR",
    "app.37": "",
    "app.4": "Automatické načítání údajů z rejstříku není pro tento stát dostupné — vyplňte profil ručně.",
    "app.59": "Posouzení souladu se směrnicí NIS 2 (JSON)",
    "app.68": "Pro tento stát neexistuje rejstřík, z něhož by nástroj mohl načíst údaje — profil se vyplňuje ručně.",
    "app.69": "Pro tento stát neexistuje rejstřík, z něhož by nástroj mohl načíst údaje. Kliknutím zapnete režim offline.",
    "app.73": " · výkaz zisku a ztráty ve variantě ",
    "app.74": "<div class=\"mt-2 tekst-uwaga\">Z údajů rejstříku nevyplývá žádná role v odvětví digitální infrastruktury. Role vyberte ručně níže.</div>",
    "app.8": "Potvrzen zápis v rejstříku poskytovatelů elektronických komunikací",
    "app.progDostawcy": "",
    "app.przyklad.adres": "Vzorová 1, 110 00 Praha",
    "app.przyklad.forma": "Společnost s ručením omezeným",
    "app.przyklad.nazwa": "Vzorový operátor s.r.o.",
    "app.statusVat": " · stav DPH: ",
    "dashboard.1": "Na základě deklarovaných rolí a velikosti není subjekt základním ani důležitým subjektem ve smyslu článku 3 směrnice (EU) 2022/2555. Zkontrolujte profil, pokud výsledek neodpovídá očekávání.",
    "dashboard.113": "Časté otázky",
    "dashboard.12": "— {p0}; lhůta pro provedení do národního práva uplynula {p2}",
    "dashboard.123": "Směrnice NIS 2",
    "dashboard.30": "Seznam základních a důležitých subjektů",
    "dashboard.4": "— přímo použitelné od {p0} ve všech členských státech, bez provedení",
    "dashboard.42": "Částková varianta: {p0}",
    "dashboard.45": "Kritéria z čl. 32 odst. 7 směrnice:",
    "dashboard.46": "Celkem",
    "dashboard.49": "Subjekt vykonává činnost v oblasti elektronických komunikací — odpovědnost vedoucí osoby stanoví národní právo",
    "dashboard.50": "",
    "dashboard.51": "",
    "dashboard.53": "Penále za prodlení s výkonem rozhodnutí: od {p0} EUR do {p1} EUR za každý den ({p2})",
    "dashboard.54": "Kvalifikovaný případ: do {p0} EUR ({p1})",
    "dashboard.57": "({p0}). Od kdy může národní orgán ukládat pokuty, stanoví zákon provádějící směrnici — tento modul jej nezná. Povinnosti zavedení vyplývají z národního práva ode dne jeho účinnosti.",
    "dashboard.65": "({p0}). Od kdy může národní orgán ukládat pokuty, stanoví zákon provádějící směrnici — tento modul jej nezná. Finanční riziko zde proto není datováno, povinnosti zavedení však vyplývají z národního práva ode dne jeho účinnosti.",
    "dashboard.83": "Činnost v oblasti elektronických komunikací — prahové hodnoty stanoví národní právo.",
    "dashboard.84": "Nařízení (EU) 2024/2690 se nevztahuje na poskytovatele veřejných sítí a služeb elektronických komunikací. Prahové hodnoty významného incidentu pro ně stanoví národní právo (čl. 23 odst. 11 směrnice) — tento modul je nezná, a proto neuvádí číselné hodnoty.",
    "dashboard.terminRejestracji": "Lhůtu pro předložení registračních údajů stanoví národní právo (čl. 3 odst. 4 směrnice). Poskytovatelé podle čl. 27 odst. 1 — služeb DNS, registry TLD, cloudových služeb, datových center, sítí pro doručování obsahu, řízených služeb a řízených bezpečnostních služeb — předávají údaje do registru ENISA: původně do 17. ledna 2025, každou změnu bez zbytečného odkladu.",
    "html.1": "ITORO — Posouzení souladu se směrnicí NIS 2 (EU) 2022/2555",
    "html.10": "Posouzení souladu se směrnicí NIS 2 — společný modul",
    "html.100": "Načtení účetní závěrky funguje jen pro státy s modulem národního práva. Pro tento stát zadáváte <strong>obrat</strong> za účetní období ručně — na něm závisí výše pokuty.",
    "html.102": "Automatické načítání údajů z rejstříků funguje jen pro státy s modulem národního práva. Role a velikost podniku uvádíte ručně.",
    "html.11": "Směrnice (EU) 2022/2555 (NIS 2) vyžaduje provedení do národního práva. Posouzení zahrnuje povinnosti vyplývající přímo ze směrnice a přímo použitelné prováděcí nařízení Komise (EU) 2024/2690 — v rozsahu, v jakém se subjektu týkají.",
    "html.23": "obrat a velikost zadáváte ručně — společný modul nedotazuje národní rejstříky",
    "html.33": "směrnice Evropského parlamentu a Rady (EU) 2022/2555 ze dne 14. prosince 2022 (NIS 2)",
    "html.33a": "{p0} — vnitrostátní předpis provádějící směrnici; jeho požadavky tento modul zatím nehodnotí",
    "html.33b": "stát dosud nepřijal prováděcí předpis — hodnocení vychází z práva Unie",
    "html.35": "povinnosti řídícího orgánu — článek 20 směrnice",
    "html.36": "Nástroj slouží k sebehodnocení. Není auditem ani právním stanoviskem.",
    "html.40": "společný modul neprovádí žádná odchozí spojení — nedotazuje rejstříky",
    "html.59": "Účetní závěrky",
    "html.60": "Načtení účetní závěrky je dostupné jen pro státy s modulem národního práva. Pro tento stát zadáváte obrat a počet zaměstnanců ručně.",
    "html.62": "Vyhledání v rejstříku",
    "html.63": "obchodní rejstříky jsou národní — společný modul je nezná",
    "html.64": "role a velikost podniku uvádíte ručně",
    "html.66": "Identifikační číslo subjektu",
    "html.68": "Automatické načítání údajů z rejstříků funguje jen pro státy s modulem národního práva.",
    "html.76": "Roční obrat (EUR)",
    "html.78": "Obrat z činnosti v oblasti elektronických komunikací (EUR)",
    "html.79": "Pole se týká poskytovatelů veřejných sítí nebo služeb elektronických komunikací. Národní prahové hodnoty stanoví právo členského státu.",
    "html.80": "Měsíční odměna vedoucího (EUR)",
    "html.82": "Směnný kurz",
    "html.83": "Stropy pokut ve směrnici jsou vyjádřeny v eurech. Přepočet na národní měnu a kurz stanoví národní právo — zde jsou částky uvedeny v eurech bez přepočtu.",
    "html.84": "Status vyplývá výhradně ze sčítání údajů propojených podniků a informační systém subjektu je nezávislý (bod odůvodnění 16 směrnice — o použití rozhoduje národní právo)",
    "html.85": "Subjekt působí v oblasti národní bezpečnosti, veřejné bezpečnosti, obrany nebo vymáhání práva (čl. 2 odst. 7 směrnice)",
    "html.91": "Posouzení souladu se směrnicí Evropského parlamentu a Rady (EU) 2022/2555 (NIS 2) a s prováděcím nařízením Komise (EU) 2024/2690 — společný modul pro státy, jejichž modul národního práva ještě není hotov.",
    "html.94": "zda je subjekt <strong>základní</strong>, <strong>důležitý</strong>, nebo mimo působnost směrnice",
    "html.daneZeSprawozdania": "název, identifikační číslo, adresa sídla",
    "html.rejestrMozliwy": "Rejstřík {p0} je veřejný a bezplatný — jeho čtení lze do nástroje doplnit; přijímáme pull requesty (viz README).",
    "html.tytulNaglowka": "Posouzení souladu se směrnicí NIS 2",
    "html.zrodlaRecznie": "Tento modul nezná rejstříky vaší země — vyplňte profil ručně. Roční obrat určuje horní hranici pokuty, zadejte jej proto přesně.",
    "klasyfikacja.10": "čl. 3 odst. 1 písm. c) směrnice (EU) 2022/2555 (poskytovatel veřejných sítí elektronických komunikací nebo veřejně dostupných služeb elektronických komunikací, který je alespoň středním podnikem)",
    "klasyfikacja.11": "čl. 3 odst. 2 ve spojení s čl. 2 odst. 2 písm. a) bodem i) směrnice (EU) 2022/2555 (poskytovatel veřejných sítí nebo služeb elektronických komunikací, který je mikropodnikem nebo malým podnikem)",
    "klasyfikacja.12": "čl. 3 odst. 1 písm. a) směrnice (EU) 2022/2555 (poskytovatel řízených bezpečnostních služeb překračující stropy pro střední podnik)",
    "klasyfikacja.13": "Mikropodniky a malé podniky nejsou z titulu této role směrnicí dotčeny (čl. 2 odst. 1 a contrario).",
    "klasyfikacja.15": "čl. 3 odst. 1 písm. b) směrnice (EU) 2022/2555 (kvalifikovaný poskytovatel služeb vytvářejících důvěru) — bez ohledu na velikost podniku",
    "klasyfikacja.16": "čl. 3 odst. 2 ve spojení s čl. 2 odst. 2 písm. a) bodem ii) směrnice (EU) 2022/2555 (nekvalifikovaný poskytovatel služeb vytvářejících důvěru, který je mikropodnikem, malým nebo středním podnikem)",
    "klasyfikacja.18": "čl. 3 odst. 2 směrnice (EU) 2022/2555 (subjekt veřejné správy na regionální úrovni, pokud tak členský stát stanoví — čl. 2 odst. 2 písm. f) bod ii))",
    "klasyfikacja.19": "čl. 3 odst. 1 písm. f) směrnice (EU) 2022/2555 (subjekt veřejné správy na ústřední úrovni — čl. 2 odst. 2 písm. f) bod i))",
    "klasyfikacja.2": "Dohled ex ante a ex post (článek 32 směrnice (EU) 2022/2555).",
    "klasyfikacja.20": "čl. 3 odst. 2 směrnice (EU) 2022/2555 (subjekt veřejné správy na regionální úrovni — čl. 2 odst. 2 písm. f) bod ii))",
    "klasyfikacja.21": "Rozsah povinností subjektů veřejné správy na místní úrovni stanoví národní právo (čl. 2 odst. 5 písm. a) směrnice).",
    "klasyfikacja.22": "Členský stát může vyjmout subjekty působící v oblasti národní bezpečnosti, veřejné bezpečnosti, obrany nebo vymáhání práva (čl. 2 odst. 7 směrnice). Výjimka nepůsobí sama od sebe — výsledek posouzení ověřte podle národního práva.",
    "klasyfikacja.23": "Subjekt splňuje kritéria základního i důležitého subjektu. Je základním subjektem (čl. 3 odst. 1 směrnice) a přísnější požadavky se vztahují na veškerou činnost, na kterou se směrnice vztahuje.",
    "klasyfikacja.25": "Subjekt je základní, proto se na něj vztahuje úplný katalog opatření podle čl. 21 odst. 2 směrnice a dohled ex ante i ex post — posouzení zahrnuje úplnou sadu otázek.",
    "klasyfikacja.26": "Jako důležitý subjekt podléháte stejnému katalogu opatření podle čl. 21 odst. 2, ale pouze dohledu ex post (článek 33). Strop pokuty je nižší: 7 mil. EUR nebo 1,4 % obratu (čl. 34 odst. 5). Úlevy pro veřejné subjekty může zavést národní právo — tento modul je nezná.",
    "klasyfikacja.28": "Povinnosti subjektů veřejné správy vyplývají z čl. 2 odst. 2 písm. f) směrnice; jejich přesný rozsah, včetně místní úrovně a vzdělávacích zařízení, stanoví národní právo (čl. 2 odst. 5).",
    "klasyfikacja.29": "Bylo deklarováno, že status subjektu vyplývá výhradně ze sčítání údajů propojených nebo partnerských podniků a že informační systém subjektu je nezávislý. Směrnice takové vyloučení připouští (bod odůvodnění 16), rozhoduje o něm však národní právo — modul vyloučení přijímá a je třeba je ověřit podle práva členského státu a zdokumentovat.",
    "klasyfikacja.4": "Pouze dohled ex post — při důkazech, náznacích nebo informacích o porušení (článek 33 směrnice (EU) 2022/2555).",
    "klasyfikacja.5": "Mimo působnost směrnice",
    "klasyfikacja.6": "Pro uvedenou roli nevyplývají ze směrnice (EU) 2022/2555 žádné povinnosti.",
    "klasyfikacja.7": "čl. 3 odst. 1 písm. a) směrnice (EU) 2022/2555 (subjekt druhu uvedeného v příloze I překračující stropy pro střední podnik)",
    "klasyfikacja.8": "čl. 3 odst. 2 směrnice (EU) 2022/2555 (subjekt druhu uvedeného v příloze I splňující kritéria středního podniku)",
    "klasyfikacja.9": "Mikropodniky a malé podniky nejsou z titulu této role směrnicí dotčeny (čl. 2 odst. 1 a contrario).",
    "kreator.10": "Obrat za předchozí rok zadejte ručně.",
    "kreator.35": "<span class=\"text-secondary\">Načtení účetních závěrek není pro tento stát dostupné.</span>",
    "kreator.37": "Načtení účetních závěrek není pro tento stát dostupné — zadejte obrat ručně.",
    "kreator.56": "Ano — nařízení EU se použije přímo od 7. listopadu 2024 ve všech členských státech a nemá přechodné období. Základem je",
    "kreator.57": ", který zmocnil Komisi ke stanovení technických a metodických požadavků pro poskytovatele uvedené v čl. 3 odst. 1 nařízení. Lhůta pro provedení směrnice uplynula",
    "kreator.58": ", a od kdy může národní orgán ukládat pokuty, stanoví národní právo. Technické požadavky přílohy (oddíly 6 a 9–13) jsou závazné v současném znění — nečekají na upřesnění. Odchýlit se lze pouze od požadavků s doložkou „v příslušných případech“, a to výhradně se zdokumentovaným odůvodněním.",
    "kreator.9": "Účetní závěrky →",
    "kreator.przepisReg2690": "čl. 21 odst. 5 směrnice (EU) 2022/2555",
    "kreator.terminReg2690": "17. října 2024",
    "punktacja.10": "Veřejné subjekty",
    "punktacja.4": "Směrnice NIS 2 — článek 21",
    "punktacja.5": "Směrnice NIS 2 — formální povinnosti",
    "punktacja.8": "Elektronické komunikace",
    "punktacja.9": "Směrnice NIS 2 — veřejné subjekty",
    "punktacja.skrotKsc": "NIS 2",
    "punktacja.skrotPke": "telekom",
    "ue.cyt.akapit": "pododstavec {p0}",
    "ue.cyt.art": "čl. {p0}",
    "ue.cyt.drugi": "2",
    "ue.cyt.dyr": "{p0} směrnice (EU) 2022/2555",
    "ue.cyt.i": "a",
    "ue.cyt.laczenie": " ",
    "ue.cyt.lit": "písm. {p0})",
    "ue.cyt.litery": "",
    "ue.cyt.pkt": "bod {p0}",
    "ue.cyt.rozdzielacz": "; ",
    "ue.cyt.rozp": "{p0} nařízení (EU) 2024/2690",
    "ue.cyt.ust": "odst. {p0}",
    "ue.katalog.1": "Koncepce analýzy rizik a bezpečnosti informačních systémů",
    "ue.katalog.10": "Řešení incidentů",
    "ue.katalog.11": "Řešení incidentů zahrnuje veškerá opatření a postupy zaměřené na předcházení incidentům, jejich odhalování, analýzu a omezení, reakci na ně a obnovu po nich (čl. 6 bod 8).",
    "ue.katalog.12": "Existuje zdokumentovaný postup řešení incidentů zahrnující odhalení, analýzu, omezení, reakci a obnovu?",
    "ue.katalog.13": "ISO/IEC 27001 A.5.24–A.5.26",
    "ue.katalog.14": "Umožňuje postup dodržet lhůty pro hlášení významného incidentu: včasné varování do 24 hodin, hlášení do 72 hodin, závěrečná zpráva do jednoho měsíce?",
    "ue.katalog.15": "ISO/IEC 27001 A.5.24",
    "ue.katalog.16": "Má subjekt kritéria pro uznání incidentu za významný v souladu s čl. 23 odst. 3: závažné narušení provozu nebo finanční ztráty, anebo značná újma jiným osobám?",
    "ue.katalog.17": "ISO/IEC 27001 A.5.25",
    "ue.katalog.18": "Jsou incidenty evidovány a poznatky z jejich řešení využívány ke zlepšování opatření?",
    "ue.katalog.19": "ISO/IEC 27001 A.5.27",
    "ue.katalog.2": "Opatření vycházejí z přístupu zohledňujícího všechna rizika (čl. 21 odst. 2). Jejich přiměřenost se posuzuje s ohledem na míru vystavení riziku, velikost subjektu, pravděpodobnost incidentů a jejich závažnost (čl. 21 odst. 1 druhý pododstavec).",
    "ue.katalog.20": "Kontinuita činností a krizové řízení",
    "ue.katalog.21": "Kontinuita činností, jako je správa záloh a obnova po havárii, a krizové řízení.",
    "ue.katalog.22": "Existuje plán kontinuity činností zahrnující obnovu po havárii?",
    "ue.katalog.23": "ISO/IEC 27001 A.5.29–A.5.30",
    "ue.katalog.24": "Jsou zálohy vytvářeny, chráněny a testovány z hlediska obnovitelnosti?",
    "ue.katalog.25": "ISO/IEC 27001 A.8.13",
    "ue.katalog.26": "Má subjekt postupy krizového řízení s vymezenými rolemi a komunikačními kanály?",
    "ue.katalog.27": "ISO/IEC 27001 A.5.29",
    "ue.katalog.28": "Jsou plány kontinuity a obnovy pravidelně testovány a výsledky dokumentovány?",
    "ue.katalog.29": "ISO/IEC 27001 A.5.30",
    "ue.katalog.3": "Má subjekt zdokumentovanou koncepci analýzy rizik a bezpečnosti informačních systémů schválenou řídícím orgánem?",
    "ue.katalog.30": "Bezpečnost dodavatelského řetězce",
    "ue.katalog.31": "Bezpečnost dodavatelského řetězce včetně bezpečnostních aspektů vztahů mezi subjektem a jeho přímými dodavateli nebo poskytovateli služeb. Subjekt zohledňuje zranitelnosti specifické pro každého dodavatele a celkovou kvalitu jeho produktů a postupů v oblasti kybernetické bezpečnosti (čl. 21 odst. 3).",
    "ue.katalog.32": "Vede subjekt seznam přímých dodavatelů a poskytovatelů služeb s hodnocením jejich významu pro bezpečnost sítí a systémů?",
    "ue.katalog.33": "ISO/IEC 27001 A.5.19",
    "ue.katalog.34": "Zohledňuje se při výběru opatření vůči dodavatelům zranitelnost specifická pro každého z nich a kvalita jejich postupů kybernetické bezpečnosti a bezpečného vývoje?",
    "ue.katalog.35": "ISO/IEC 27001 A.5.19, A.5.21",
    "ue.katalog.36": "Obsahují smlouvy s dodavateli bezpečnostní požadavky a povinnost informovat o incidentech a zranitelnostech?",
    "ue.katalog.37": "ISO/IEC 27001 A.5.20",
    "ue.katalog.38": "Zohledňuje subjekt výsledky koordinovaných posouzení bezpečnostních rizik kritických dodavatelských řetězců podle článku 22?",
    "ue.katalog.39": "ISO/IEC 27001 A.5.21",
    "ue.katalog.4": "ISO/IEC 27001 body 5.2, 6.1.2",
    "ue.katalog.40": "Bezpečnost při pořizování, vývoji a údržbě systémů",
    "ue.katalog.41": "Bezpečnost pořizování, vývoje a údržby sítí a informačních systémů, včetně řešení a zveřejňování zranitelností.",
    "ue.katalog.42": "Jsou bezpečnostní požadavky stanoveny před pořízením nebo zahájením vývoje systému a ověřeny před nasazením?",
    "ue.katalog.43": "ISO/IEC 27001 A.8.25–A.8.29",
    "ue.katalog.44": "Existuje proces řešení zranitelností: identifikace, posouzení, odstranění ve stanovené lhůtě?",
    "ue.katalog.45": "ISO/IEC 27001 A.8.8",
    "ue.katalog.46": "Má subjekt postup pro zveřejňování zranitelností včetně kanálu pro přijímání hlášení od třetích stran?",
    "ue.katalog.47": "Procházejí změny systémů řízeným procesem řízení změn s posouzením dopadu na bezpečnost?",
    "ue.katalog.48": "ISO/IEC 27001 A.8.32",
    "ue.katalog.49": "Posuzování účinnosti opatření",
    "ue.katalog.5": "Zahrnuje analýza rizik všechna rizika pro sítě a informační systémy a jejich fyzické prostředí, nejen kybernetické hrozby?",
    "ue.katalog.50": "Koncepce a postupy pro posuzování účinnosti opatření k řízení kybernetických bezpečnostních rizik.",
    "ue.katalog.51": "Existuje zdokumentovaná koncepce posuzování účinnosti opatření vymezující rozsah, četnost a metody?",
    "ue.katalog.52": "ISO/IEC 27001 bod 9.1",
    "ue.katalog.53": "Provádějí se posouzení účinnosti pravidelně a jsou jejich výsledky předávány řídícímu orgánu?",
    "ue.katalog.54": "ISO/IEC 27001 body 9.2–9.3",
    "ue.katalog.55": "Vedou zjištěné slabiny ke zdokumentovaným nápravným opatřením s vlastníkem a lhůtou?",
    "ue.katalog.56": "ISO/IEC 27001 bod 10.1",
    "ue.katalog.57": "Kybernetická hygiena a školení",
    "ue.katalog.58": "Základní postupy kybernetické hygieny a školení v oblasti kybernetické bezpečnosti. Členové řídícího orgánu se pravidelně účastní školení (čl. 20 odst. 2).",
    "ue.katalog.59": "Uplatňuje subjekt základní postupy kybernetické hygieny: aktualizace, správu hesel, omezení oprávnění, ochranu před škodlivým softwarem?",
    "ue.katalog.6": "ISO/IEC 27001 bod 6.1.2",
    "ue.katalog.60": "ISO/IEC 27001 A.8.7, A.8.8",
    "ue.katalog.61": "Absolvují zaměstnanci školení kybernetické bezpečnosti přizpůsobené jejich roli a je účast dokumentována?",
    "ue.katalog.62": "ISO/IEC 27001 A.6.3",
    "ue.katalog.63": "Účastní se členové řídícího orgánu pravidelně školení umožňujících rozpoznat rizika a posoudit postupy řízení rizik?",
    "ue.katalog.64": "ISO/IEC 27001 bod 7.2",
    "ue.katalog.65": "Kryptografie a šifrování",
    "ue.katalog.66": "Koncepce a postupy používání kryptografie a v příslušných případech šifrování.",
    "ue.katalog.67": "Existuje koncepce používání kryptografie vymezující, které údaje a kanály se šifrují a jakými algoritmy?",
    "ue.katalog.68": "ISO/IEC 27001 A.8.24",
    "ue.katalog.69": "Jsou kryptografické klíče spravovány v celém životním cyklu: generování, distribuce, uložení, rotace, vyřazení?",
    "ue.katalog.7": "Zohledňuje výběr opatření nejnovější stav techniky, příslušné evropské a mezinárodní normy a náklady na zavedení?",
    "ue.katalog.70": "Lidské zdroje, řízení přístupu a správa aktiv",
    "ue.katalog.71": "Bezpečnost lidských zdrojů, koncepce řízení přístupu a správa aktiv.",
    "ue.katalog.72": "Vede subjekt aktuální seznam aktiv s přiřazenými vlastníky a klasifikací?",
    "ue.katalog.73": "ISO/IEC 27001 A.5.9, A.5.12",
    "ue.katalog.74": "Existuje koncepce řízení přístupu založená na zásadě nejnižších oprávnění s pravidelným přezkumem oprávnění?",
    "ue.katalog.75": "ISO/IEC 27001 A.5.15, A.5.18",
    "ue.katalog.76": "Uplatňují se při nástupu, změně pozice a odchodu zaměstnance bezpečnostní postupy včetně odebrání oprávnění a vrácení aktiv?",
    "ue.katalog.77": "ISO/IEC 27001 A.6.1–A.6.5",
    "ue.katalog.78": "Je privilegovaný přístup omezen, zaznamenáván a přezkoumáván?",
    "ue.katalog.79": "ISO/IEC 27001 A.8.2",
    "ue.katalog.8": "ISO/IEC 27001 bod 6.1.3",
    "ue.katalog.80": "Vícefaktorové ověřování a zabezpečená komunikace",
    "ue.katalog.81": "V příslušných případech — vícefaktorové nebo průběžné ověřování, zabezpečená hlasová, obrazová a textová komunikace a zabezpečené systémy nouzové komunikace uvnitř subjektu.",
    "ue.katalog.82": "Používá se vícefaktorové nebo průběžné ověřování tam, kde to analýza rizik odůvodňuje, zejména pro vzdálený přístup a privilegované účty?",
    "ue.katalog.83": "ISO/IEC 27001 A.8.5",
    "ue.katalog.84": "Je hlasová, obrazová a textová komunikace používaná pro služební účely zabezpečena?",
    "ue.katalog.85": "ISO/IEC 27001 A.8.20",
    "ue.katalog.86": "Má subjekt zabezpečený systém interní nouzové komunikace nezávislý na hlavní infrastruktuře?",
    "ue.katalog.9": "Je úroveň bezpečnosti zdokumentována jako přiměřená existujícímu riziku, s odůvodněním zohledňujícím velikost subjektu a společenské a hospodářské dopady incidentů?",
    "ue.kierownictwo.1": "Řídící orgán základního nebo důležitého subjektu — v kapitálové společnosti představenstvo či jednatelé. Směrnice tento pojem nedefinuje; jeho rozsah v daném státě vyplývá z národního práva.",
    "ue.kierownictwo.10": "Určit status subjektu a zajistit registraci",
    "ue.kierownictwo.11": "Určení, zda je subjekt základní nebo důležitý, a předložení registračních údajů příslušnému orgánu. Postup a lhůtu stanoví národní právo.",
    "ue.kierownictwo.12": "Zavést analýzu rizik a bezpečnostní koncepci",
    "ue.kierownictwo.13": "Opatření vycházející z přístupu zohledňujícího všechna rizika, přiměřená vystavení riziku, velikosti subjektu a závažnosti incidentů.",
    "ue.kierownictwo.14": "Spustit řešení a hlášení incidentů",
    "ue.kierownictwo.15": "Postup řešení incidentů a schopnost dodržet lhůty 24 hodin, 72 hodin a jednoho měsíce.",
    "ue.kierownictwo.16": "24 h / 72 h / měsíc od zjištění",
    "ue.kierownictwo.17": "Zajistit kontinuitu činností",
    "ue.kierownictwo.18": "Plán kontinuity, zálohy, obnova po havárii, krizové řízení.",
    "ue.kierownictwo.19": "Uspořádat dodavatelský řetězec",
    "ue.kierownictwo.2": "Odpovědností řídícího orgánu nejsou dotčeny národní předpisy o odpovědnosti veřejných institucí a úředníků (čl. 20 odst. 1 druhý pododstavec).",
    "ue.kierownictwo.20": "Seznam dodavatelů, hodnocení jejich zranitelností a postupů, bezpečnostní požadavky ve smlouvách.",
    "ue.kierownictwo.21": "Zavést řízení přístupu a správu aktiv",
    "ue.kierownictwo.22": "Seznam aktiv, zásada nejnižších oprávnění, přezkumy oprávnění, vícefaktorové ověřování tam, kde to riziko odůvodňuje.",
    "ue.kierownictwo.23": "Měřit účinnost opatření",
    "ue.kierownictwo.24": "Koncepce a postupy posuzování účinnosti, pravidelné přezkumy, nápravná opatření.",
    "ue.kierownictwo.25": "Schvalovat",
    "ue.kierownictwo.26": "opatření k řízení kybernetických bezpečnostních rizik (čl. 20 odst. 1)",
    "ue.kierownictwo.27": "koncepci analýzy rizik a bezpečnosti systémů",
    "ue.kierownictwo.28": "rozpočet a role při zavádění",
    "ue.kierownictwo.29": "Dohlížet",
    "ue.kierownictwo.3": "Zda svěření povinností jiné osobě vylučuje odpovědnost, rozhoduje národní právo. V Polsku nevylučuje (čl. 8c odst. 3 zákona o národním systému kybernetické bezpečnosti).",
    "ue.kierownictwo.30": "na provádění schválených opatření (čl. 20 odst. 1)",
    "ue.kierownictwo.31": "na výsledky posouzení účinnosti (čl. 21 odst. 2 písm. f))",
    "ue.kierownictwo.32": "na dodržování lhůt pro hlášení incidentů (článek 23)",
    "ue.kierownictwo.33": "Dokumentovat",
    "ue.kierownictwo.34": "schvalovací rozhodnutí a přezkumy",
    "ue.kierownictwo.35": "účast na školeních (čl. 20 odst. 2)",
    "ue.kierownictwo.36": "Člen řídícího orgánu",
    "ue.kierownictwo.37": "schvalování opatření, dohled, rozhodnutí, rozpočet",
    "ue.kierownictwo.38": "Vedoucí projektu",
    "ue.kierownictwo.39": "koordinace zavádění, harmonogram, stav a důkazy",
    "ue.kierownictwo.4": "Schválit opatření k řízení kybernetických bezpečnostních rizik",
    "ue.kierownictwo.40": "IT / kybernetická bezpečnost",
    "ue.kierownictwo.41": "analýza rizik, technická opatření, řešení incidentů",
    "ue.kierownictwo.42": "Právní oddělení / compliance",
    "ue.kierownictwo.5": "Řídící orgán schvaluje opatření přijatá k zajištění souladu s článkem 21. Je to rozhodnutí orgánu, nikoli IT oddělení — bez něj opatření nemají oporu.",
    "ue.kierownictwo.6": "Dohlížet na provádění opatření",
    "ue.kierownictwo.7": "Dohled nad prováděním je povinností řídícího orgánu. Provedení lze svěřit, dohled nikoli.",
    "ue.kierownictwo.8": "Pravidelně se účastnit školení",
    "ue.kierownictwo.9": "Členové řídícího orgánu se pravidelně účastní školení, aby získali dostatečné znalosti k rozpoznání rizik a posouzení postupů řízení rizik a jejich dopadu na služby subjektu.",
    "ue.kierownictwo.daneRejestracyjne": "registrační údaje a jejich aktualizace (čl. 3 odst. 4–5)",
    "ue.meta.1": "Převažuje procentní varianta: {p0} % obratu je více než {p1} mil. EUR.",
    "ue.meta.10": "Směrnice neukládá povinnosti podnikům přímo — činí tak národní zákon, který měl členský stát přijmout do 17. října 2024. Tento modul zobrazuje požadavky ve znění směrnice, protože modul národního práva pro vybraný stát ještě není hotov nebo stát směrnici neprovedl.",
    "ue.meta.11": "Povinnosti ze směrnice",
    "ue.meta.12": "Seznam subjektů — do 17. dubna 2025",
    "ue.meta.13": "Členské státy měly do 17. dubna 2025 vytvořit seznam základních a důležitých subjektů a vyžadovat od subjektů předložení registračních údajů.",
    "ue.meta.14": "Nařízení (EU) 2024/2690",
    "ue.meta.15": "Přímo použitelné od 7. listopadu 2024",
    "ue.meta.16": "Prováděcí nařízení se použije přímo ve všech členských státech bez ohledu na stav provedení směrnice. Týká se subjektů uvedených v jeho článku 1: DNS, TLD, cloudu, datových center, sítí pro doručování obsahu, řízených služeb a služeb vytvářejících důvěru.",
    "ue.meta.17": "článek 16 nařízení (EU) 2024/2690",
    "ue.meta.18": "Nejméně 10 000 000 EUR nebo nejméně 2 % celkového celosvětového ročního obratu podniku v předchozím účetním období — použije se vyšší částka. Jde o minimální strop: národní právo jej může zvýšit.",
    "ue.meta.19": "Nejméně 7 000 000 EUR nebo 1,4 % celkového celosvětového ročního obratu — použije se vyšší částka. Minimální strop.",
    "ue.meta.2": "Převažuje pevná částka: {p0} mil. EUR je více než {p1} % obratu.",
    "ue.meta.20": "Směrnice nestanoví samostatnou pokutu za kvalifikované porušení — jde o konstrukci národního práva některých států.",
    "ue.meta.21": "Členské státy mohou stanovit penále k vynucení ukončení porušování. Výši stanoví národní právo.",
    "ue.meta.22": "Řídící orgán schvaluje opatření k řízení rizik, dohlíží na jejich provádění a může nést odpovědnost za porušení článku 21. Zásady a rozsah této odpovědnosti stanoví národní právo.",
    "ue.meta.23": "Řídící orgán schvaluje opatření k řízení kybernetických bezpečnostních rizik (čl. 20 odst. 1).",
    "ue.meta.24": "Řídící orgán dohlíží na provádění těchto opatření (čl. 20 odst. 1).",
    "ue.meta.25": "Členové řídícího orgánu se pravidelně účastní školení (čl. 20 odst. 2).",
    "ue.meta.26": "Vůči základnímu subjektu může orgán požádat o dočasný zákaz výkonu řídících funkcí (čl. 32 odst. 5 písm. b)).",
    "ue.meta.27": "Minimální strop stanoví směrnice",
    "ue.meta.28": "Porovnávají se dvě hodnoty: pevná částka v eurech a procento celkového celosvětového ročního obratu podniku v předchozím účetním období. Vyšší z nich je horní hranice, kterou členský stát musí přinejmenším stanovit. Národní právo ji může zvýšit.",
    "ue.meta.29": "Částku v rámci stropu stanoví národní orgán",
    "ue.meta.3": "Strop ze směrnice převyšuje roční obrat subjektu {p0}krát. Čl. 34 odst. 1 vyžaduje, aby pokuta byla přiměřená okolnostem jednotlivého případu — jde o horní hranici, nikoli o očekávanou pokutu.",
    "ue.meta.30": "Pokuta má být účinná, přiměřená a odrazující s ohledem na okolnosti jednotlivého případu. Orgán zohledňuje alespoň kritéria z čl. 32 odst. 7: závažnost a dobu trvání porušení, dřívější porušení, škody, úmysl, nápravná opatření a spolupráci.",
    "ue.meta.31": "Strop může mnohonásobně převyšovat roční obrat — jde o horní hranici, nikoli o očekávanou částku. Národní minima, penále a způsob vyměření stanoví zákon členského státu.",
    "ue.meta.32": "Při rozhodování o uložení správní pokuty a o její výši se v každém jednotlivém případě náležitě zohlední alespoň prvky uvedené v čl. 32 odst. 7.",
    "ue.meta.33": "závažnost porušení a význam porušených ustanovení — za závažné se v každém případě považují: opakovaná porušení, nenahlášení nebo nenapravení významných incidentů, nenapravení nedostatků v rozporu se závaznými příkazy, maření auditů nebo sledování, poskytnutí nepravdivých nebo hrubě nepřesných informací",
    "ue.meta.34": "relevantní dřívější porušení ze strany subjektu",
    "ue.meta.35": "způsobené majetkové a nemajetkové škody, včetně finančních ztrát, dopadu na jiné služby a počtu dotčených uživatelů",
    "ue.meta.36": "úmyslná nebo nedbalostní povaha jednání",
    "ue.meta.37": "opatření přijatá k zabránění škodám nebo jejich zmírnění",
    "ue.meta.38": "dodržování schválených kodexů chování nebo mechanismů certifikace",
    "ue.meta.39": "míra spolupráce s příslušnými orgány",
    "ue.meta.4": "Směrnice Evropského parlamentu a Rady (EU) 2022/2555 (NIS 2)",
    "ue.meta.40": "Směrnice výslovně nestanoví upuštění od pokuty — zda a kdy je možné, rozhoduje národní právo.",
    "ue.meta.41": "Od tohoto data mají členské státy uplatňovat národní předpisy provádějící směrnici. Konkrétní datum, od kterého může orgán uložit pokutu, vyplývá z národního práva.",
    "ue.meta.42": "Vstup směrnice NIS 2 v platnost",
    "ue.meta.43": "Dvacátým dnem po vyhlášení v Úředním věstníku.",
    "ue.meta.44": "Lhůta pro provedení směrnice",
    "ue.meta.45": "Do tohoto data měly členské státy přijmout a zveřejnit národní předpisy.",
    "ue.meta.46": "Použití národních předpisů a zrušení NIS 1",
    "ue.meta.47": "Od tohoto data státy uplatňují prováděcí předpisy; směrnice (EU) 2016/1148 se zrušuje.",
    "ue.meta.48": "Použití nařízení (EU) 2024/2690",
    "ue.meta.49": "Prováděcí nařízení se použije přímo od dvacátého dne po vyhlášení.",
    "ue.meta.5": "Úř. věst. EU L 333, 27.12.2022",
    "ue.meta.50": "Seznam základních a důležitých subjektů",
    "ue.meta.51": "Do tohoto data členské státy vytvoří seznam; subjekty předloží orgánům registrační údaje.",
    "ue.meta.52": "První přezkum směrnice Komisí",
    "ue.meta.53": "Komise přezkoumá fungování směrnice a předloží zprávu.",
    "ue.meta.54": "Včasné varování o významném incidentu",
    "ue.meta.55": "24 hodin od okamžiku, kdy se subjekt dozví",
    "ue.meta.56": "Hlášení významného incidentu",
    "ue.meta.57": "72 hodin od okamžiku, kdy se subjekt dozví",
    "ue.meta.58": "Závěrečná zpráva",
    "ue.meta.59": "měsíc od hlášení incidentu",
    "ue.meta.6": "Prováděcí nařízení Komise (EU) 2024/2690",
    "ue.meta.60": "Hlášení incidentu poskytovatelem služeb vytvářejících důvěru",
    "ue.meta.61": "čl. 21 odst. 5 směrnice (EU) 2022/2555; články 1 a 2 nařízení (EU) 2024/2690",
    "ue.meta.62": "Bez údajů o obratu je stropem pevná částka ze směrnice.",
    "ue.meta.63": "Stropy podle čl. 34 odst. 4 a 5 jsou minimální („nejméně“) — národní právo může stanovit vyšší. Částky v eurech, bez přepočtu na národní měnu.",
    "ue.meta.64": "Příslušný orgán členského státu",
    "ue.meta.65": "Řídící orgán může nést odpovědnost za porušení článku 21. Rozsah a postup stanoví národní právo — tento modul je nezná.",
    "ue.meta.66": "Rozsah osobní odpovědnosti vedení vyplývá z národního zákona. Pro Polsko je to až 300 % odměny (čl. 73a odst. 4 zákona o národním systému kybernetické bezpečnosti); jiné státy to řeší jinak.",
    "ue.meta.7": "Úř. věst. EU L, 2024/2690",
    "ue.meta.8": "Směrnice (EU) 2022/2555",
    "ue.meta.9": "Lhůta pro provedení uplynula 17. října 2024",
    "ue.moduly.1": "přibližně {p0} min",
    "ue.moduly.10": "Deset oblastí z čl. 21 odst. 2 písm. a) až j): od koncepce rizik po vícefaktorové ověřování. Porušení je sankcionováno pokutou podle článku 34. Hodnocení na škále vyspělosti.",
    "ue.moduly.11": "Nařízení 2024/2690 — řízení a procesy",
    "ue.moduly.12": "Oddíly 1–5 a 7–8 přílohy: koncepce, řízení rizik, řešení incidentů, kontinuita činností, dodavatelský řetězec, posuzování účinnosti, kybernetická hygiena. Přímo použitelné od 7. listopadu 2024.",
    "ue.moduly.13": "Nařízení 2024/2690 — technické požadavky",
    "ue.moduly.14": "Oddíly 6 a 9–13 přílohy: pořizování a vývoj systémů, kryptografie, bezpečnost lidských zdrojů, řízení přístupu, správa aktiv, fyzická bezpečnost a bezpečnost prostředí.",
    "ue.moduly.2": "přibližně {p0} h {p1} min",
    "ue.moduly.3": "přibližně {p0} h",
    "ue.moduly.4": "méně než minuta",
    "ue.moduly.5": "Rychlé posouzení rizik",
    "ue.moduly.6": "Nadřazené otázky ze všech oblastí směrnice. Každá rozhoduje o celé skupině témat. Umožňuje odhadnout rozsah restů bez průchodu celým dotazníkem.",
    "ue.moduly.7": "Povinnosti ze směrnice",
    "ue.moduly.8": "Registrační údaje, hlášení incidentů do 24 a 72 hodin, povinnosti řídícího orgánu, připravenost na dohled. Ověřitelné z dokumentů, bez technické analýzy.",
    "ue.moduly.9": "Opatření k řízení rizik — čl. 21 odst. 2",
    "ue.obowiazki.1": "Registrační údaje pro seznam subjektů",
    "ue.obowiazki.10": "Hlášení významných incidentů",
    "ue.obowiazki.11": "Subjekt hlásí významné incidenty týmu CSIRT nebo příslušnému orgánu ve třech krocích: včasné varování, hlášení, závěrečná zpráva. Lhůty běží od okamžiku, kdy se subjekt o incidentu dozví.",
    "ue.obowiazki.12": "Je subjekt schopen předat včasné varování do 24 hodin od okamžiku, kdy se o významném incidentu dozví, s uvedením, zda je incident pravděpodobně způsoben protiprávním jednáním a zda může mít přeshraniční dopad?",
    "ue.obowiazki.13": "24 hodin od okamžiku, kdy se subjekt dozví",
    "ue.obowiazki.14": "Je subjekt schopen předat hlášení incidentu do 72 hodin s prvotním posouzením závažnosti a dopadu a s indikátory kompromitace?",
    "ue.obowiazki.15": "72 hodin od okamžiku, kdy se subjekt dozví",
    "ue.obowiazki.16": "Předává subjekt závěrečnou zprávu nejpozději měsíc po hlášení, s popisem incidentu, druhem hrozby, nápravnými opatřeními a přeshraničním dopadem?",
    "ue.obowiazki.17": "měsíc od hlášení",
    "ue.obowiazki.18": "Informuje subjekt příjemce svých služeb o významných incidentech, které mohou nepříznivě ovlivnit poskytování těchto služeb?",
    "ue.obowiazki.19": "Informuje subjekt příjemce služeb o významné kybernetické hrozbě a o nápravných opatřeních, která mohou příjemci přijmout?",
    "ue.obowiazki.2": "Členské státy vytvoří seznam základních a důležitých subjektů a vyžadují od subjektů předložení registračních údajů. Postup, lhůtu a portál stanoví národní právo.",
    "ue.obowiazki.20": "Je-li subjekt poskytovatelem služeb vytvářejících důvěru — hlásí významné incidenty do 24 hodin od okamžiku, kdy se o nich dozví?",
    "ue.obowiazki.21": "týká se poskytovatelů služeb vytvářejících důvěru",
    "ue.obowiazki.22": "Řídící orgán",
    "ue.obowiazki.23": "Řídící orgán schvaluje opatření k řízení rizik, dohlíží na jejich provádění a může nést odpovědnost. Členové orgánu se pravidelně účastní školení.",
    "ue.obowiazki.24": "Schválil řídící orgán formálně opatření k řízení kybernetických bezpečnostních rizik přijatá k zajištění souladu s článkem 21?",
    "ue.obowiazki.25": "Dohlíží řídící orgán na provádění těchto opatření zdokumentovaným způsobem — například pravidelnými zprávami a přezkumy?",
    "ue.obowiazki.26": "Účastní se členové řídícího orgánu pravidelně školení umožňujících rozpoznat rizika a posoudit postupy řízení rizik, a je účast zdokumentována?",
    "ue.obowiazki.27": "Připravenost na dohledové úkony",
    "ue.obowiazki.28": "Základní subjekt podléhá dohledu ex ante i ex post, důležitý subjekt pouze ex post. Orgán může požadovat informace, důkazy o zavedení koncepcí a výsledky auditů.",
    "ue.obowiazki.29": "Je subjekt schopen na žádost orgánu předložit důkazy o zavedení koncepcí kybernetické bezpečnosti, včetně výsledků bezpečnostních auditů?",
    "ue.obowiazki.3": "Určil subjekt, zda je základním nebo důležitým subjektem, na základě odvětví z přílohy I nebo II a velikosti podniku?",
    "ue.obowiazki.30": "Je subjekt schopen na žádost orgánu zpřístupnit údaje, dokumenty a informace nezbytné k výkonu dohledových úkolů?",
    "ue.obowiazki.31": "Je základní subjekt připraven na bezpečnostní audit prováděný orgánem nebo nezávislým subjektem na vlastní náklady?",
    "ue.obowiazki.4": "Předložil subjekt příslušnému orgánu registrační údaje: název, adresu a kontaktní údaje, odvětví a pododvětví, seznam členských států, v nichž poskytuje služby?",
    "ue.obowiazki.5": "Kontaktní údaje zahrnují e-mailové adresy, rozsahy IP adres a telefonní čísla. Národní lhůtu a registrační portál stanoví právo členského státu.",
    "ue.obowiazki.6": "Existuje proces aktualizace registračních údajů bez zbytečného odkladu po jejich změně?",
    "ue.obowiazki.7": "Směrnice vyžaduje aktualizaci bez zbytečného odkladu; konkrétní lhůta — například 14 dnů v Polsku — vyplývá z národního práva.",
    "ue.obowiazki.8": "Je-li subjekt poskytovatelem DNS, registrem TLD, poskytovatelem cloudu, datového centra, CDN, řízených služeb, online tržištěm, vyhledávačem nebo sociální sítí — předložil dodatečné údaje podle článku 27 včetně adresy hlavní provozovny v Unii?",
    "ue.obowiazki.9": "týká se subjektů podle čl. 26 odst. 1",
    "ue.role.1": "Příslušný orgán členského státu",
    "ue.role.10": "Služby datového centra: kolokace, hosting infrastruktury a související služby.",
    "ue.role.11": "Datová centra",
    "ue.role.12": "Základní subjekt nad prahem středního podniku (čl. 3 odst. 1 písm. a)), důležitý při střední velikosti (čl. 3 odst. 2). Pod střední velikostí — mimo působnost, pokud členský stát subjekt neurčí podle čl. 2 odst. 2 písm. b) až e). Dotčen nařízením 2024/2690.",
    "ue.role.13": "Poskytovatel výměnného uzlu internetu",
    "ue.role.14": "Infrastruktura umožňující výměnu provozu mezi nezávislými sítěmi.",
    "ue.role.15": "Výměnné uzly internetu",
    "ue.role.16": "Klasifikace podle velikosti (čl. 3 odst. 1 písm. a) a odst. 2). Nařízení 2024/2690 se na výměnné uzly internetu nevztahuje — článek 1 nařízení obsahuje uzavřený výčet adresátů.",
    "ue.role.17": "Poskytovatel služeb DNS",
    "ue.role.18": "Služby překladu doménových jmen, s výjimkou provozovatelů kořenových jmenných serverů.",
    "ue.role.19": "Systém doménových jmen",
    "ue.role.2": "příslušný orgán",
    "ue.role.20": "Základní subjekt bez ohledu na velikost (čl. 3 odst. 1 písm. b)). Dotčen nařízením 2024/2690.",
    "ue.role.21": "Registr TLD",
    "ue.role.22": "Vedení registru domény nejvyšší úrovně.",
    "ue.role.23": "Základní subjekt bez ohledu na velikost (čl. 3 odst. 1 písm. b)). Navíc povinnosti týkající se registračních údajů podle článku 28. Dotčen nařízením 2024/2690.",
    "ue.role.24": "Poskytovatel služeb cloud computingu",
    "ue.role.25": "Služby cloud computingu: infrastruktura, platforma, software jako služba.",
    "ue.role.26": "Služby cloud computingu",
    "ue.role.27": "Klasifikace podle velikosti (čl. 3 odst. 1 písm. a) a odst. 2). Dotčen nařízením 2024/2690.",
    "ue.role.28": "Poskytovatel sítě pro doručování obsahu",
    "ue.role.29": "Síť distribuovaných serverů doručujících obsah a služby koncovým uživatelům.",
    "ue.role.3": "určený národním právem; do zavedení národního modulu nástroj neuvádí konkrétní instituci",
    "ue.role.30": "Sítě pro doručování obsahu",
    "ue.role.31": "Poskytovatel služeb vytvářejících důvěru",
    "ue.role.32": "Služby vytvářející důvěru ve smyslu nařízení (EU) č. 910/2014: podpisy, pečetě, časová razítka, certifikáty.",
    "ue.role.33": "Služby vytvářející důvěru",
    "ue.role.34": "Směrnicí dotčen bez ohledu na velikost (čl. 2 odst. 2 písm. a) bod ii)). Kvalifikovaný poskytovatel je základním subjektem bez ohledu na velikost (čl. 3 odst. 1 písm. b)); nekvalifikovaný je základním nad prahem středního podniku, jinak důležitým. Dotčen nařízením 2024/2690.",
    "ue.role.35": "Poskytovatel řízených služeb",
    "ue.role.36": "Správa infrastruktury IKT zákazníka: instalace, údržba, podpora, správa systémů.",
    "ue.role.37": "Řízení služeb IKT (B2B)",
    "ue.role.38": "Řízené služby",
    "ue.role.39": "Poskytovatel řízených bezpečnostních služeb",
    "ue.role.4": "Poskytovatel veřejných sítí elektronických komunikací nebo veřejně dostupných služeb elektronických komunikací",
    "ue.role.40": "Řízené služby v oblasti kybernetické bezpečnosti: monitorování, reakce na incidenty, testy, poradenství.",
    "ue.role.41": "Řízené bezpečnostní služby",
    "ue.role.42": "Směrnice klasifikuje podle velikosti (čl. 3 odst. 1 písm. a) a odst. 2). Členské státy mohou práh zpřísnit — Polsko považuje MSSP za základní subjekt již od malého podniku; tento modul uplatňuje výhradně pravidlo směrnice. Dotčen nařízením 2024/2690.",
    "ue.role.5": "Zajišťování veřejných sítí elektronických komunikací nebo poskytování veřejně dostupných služeb elektronických komunikací, včetně přístupu k internetu.",
    "ue.role.6": "Digitální infrastruktura",
    "ue.role.7": "Elektronické komunikace",
    "ue.role.8": "Směrnicí dotčen bez ohledu na velikost (čl. 2 odst. 2 písm. a) bod i)). Střední nebo větší podnik je základním subjektem (čl. 3 odst. 1 písm. c)), mikropodnik a malý podnik důležitým (čl. 3 odst. 2). Národní zákon o elektronických komunikacích může ukládat další povinnosti — tento modul je neobsahuje.",
    "ue.role.9": "Poskytovatel služeb datového centra",
    "ue.role.podstawaArt3b": "čl. 3 odst. 1 písm. b) směrnice (EU) 2022/2555",
    "ue.zaslepki.1": "Směrnice Evropského parlamentu a Rady (EU) 2022/2555 (NIS 2)",
    "ue.zaslepki.10": "Zda je část subjektů zapisována z moci úřední, rozhoduje národní právo.",
    "ue.zaslepki.11": "Zjistěte, zda podléháte směrnici",
    "ue.zaslepki.12": "Odvětví z přílohy I nebo II a velikost podniku. Tuto část provádí profil subjektu v tomto nástroji.",
    "ue.zaslepki.13": "Zjistěte příslušný orgán ve svém státě",
    "ue.zaslepki.14": "Každý stát určí příslušný orgán (čl. 8 odst. 1). Aktuální seznam vede ENISA a Komise.",
    "ue.zaslepki.15": "Předložte registrační údaje",
    "ue.zaslepki.16": "Název, adresa a kontaktní údaje, odvětví a pododvětví, státy poskytování služeb (čl. 3 odst. 4). Postup podle národního práva.",
    "ue.zaslepki.17": "Aktualizujte údaje bez zbytečného odkladu",
    "ue.zaslepki.18": "Každá změna registračních údajů vyžaduje aktualizaci (čl. 3 odst. 5).",
    "ue.zaslepki.19": "adresa a aktuální kontaktní údaje: e-mailové adresy, rozsahy IP adres, telefonní čísla",
    "ue.zaslepki.2": "Úř. věst. EU L 333, 27.12.2022, s. 80",
    "ue.zaslepki.20": "odvětví a pododvětví z přílohy I nebo II",
    "ue.zaslepki.21": "seznam členských států, v nichž subjekt poskytuje služby",
    "ue.zaslepki.22": "Stanoví národní právo.",
    "ue.zaslepki.23": "Směrnice (EU) 2022/2555 — článek 3",
    "ue.zaslepki.24": "ENISA — příslušné orgány členských států",
    "ue.zaslepki.25": "Směrnice (EU) 2022/2555",
    "ue.zaslepki.26": "Unijní modul neobsahuje pokyny národního orgánu — ty přijdou s modulem národního práva.",
    "ue.zaslepki.27": "Automatické načítání údajů z rejstříku funguje jen pro státy s modulem národního práva. Vyplňte profil ručně.",
    "ue.zaslepki.28": "Načtení účetní závěrky funguje jen pro státy s modulem národního práva. Zadejte obrat a počet zaměstnanců ručně.",
    "ue.zaslepki.3": "Prováděcí nařízení Komise (EU) 2024/2690",
    "ue.zaslepki.4": "Úř. věst. EU L, 2024/2690, 18.11.2024",
    "ue.zaslepki.5": "Směrnice NIS 2 neobsahuje samostatnou vrstvu elektronických komunikací. Národní právo elektronických komunikací může ukládat další povinnosti — tento modul je nezná.",
    "ue.zaslepki.6": "Seznam základních a důležitých subjektů",
    "ue.zaslepki.7": "Příslušný orgán členského státu.",
    "ue.zaslepki.8": "Směrnice ukládá členským státům vést seznam základních a důležitých subjektů a vyžadovat od subjektů předložení registračních údajů. Portál, postup a lhůtu stanoví národní právo — tento modul je nezná, protože modul národního práva pro vybraný stát ještě není hotov.",
    "ue.zaslepki.9": "Všechny základní a důležité subjekty. Lhůtu stanoví národní právo.",
    "ue.zaslepki.skrotDyrektywy": "směrnice NIS 2",
    "ue.zaslepki.skrotReg2690": "nař. 2024/2690",
    "xlsx.1": "{p0} – {p1} EUR",
    "xlsx.25": "Směnný kurz",
    "xlsx.4": "ZPRÁVA O SOULADU SE SMĚRNICÍ NIS 2 (EU) 2022/2555",
    "xlsx.58": "Činnost v oblasti elektronických komunikací: nařízení (EU) 2024/2690 se nepoužije. Prahové hodnoty stanoví národní právo (čl. 23 odst. 11 směrnice) — společný modul je nezná.",
    "xlsx.68": "Nástroj slouží k sebehodnocení. Není auditem ani právním stanoviskem.",
    "xlsx.69": "Pro subjekty, na které se nevztahuje nařízení (EU) 2024/2690, stanoví prahové hodnoty významného incidentu národní právo (čl. 23 odst. 11 směrnice).",
    "xlsx.70": "Role uvedené v profilu jsou prohlášením. O statusu rozhoduje skutečně vykonávaná činnost (článek 3 směrnice (EU) 2022/2555).",
    "xlsx.etykietaKrs": "Rejstříkové číslo",
    "xlsx.etykietaNip": "Identifikační číslo",
    "xlsx.etykietaRegon": "Statistické číslo"
});
