/* Teksty modułu ue — język: en.
   Te same klucze co w napisy/pl.js (wersja źródłowa); wstawki {p0}, {p1}…
   pozostają bez zmian. Klucze ue.cyt.* to wzorce składania odesłań
   do przepisów w tym języku — patrz kraje/ue/cytaty.js. */
KRAJE.napisy('ue', 'en', {
    "app.10": "Check the list of roles below — status is determined by the activity actually carried out (Article 3 of Directive (EU) 2022/2555), not by a register entry.",
    "app.14": "Previous year: EUR {p0}",
    "app.15": "Revenue for the reporting period: EUR {p0}",
    "app.19": "Querying registers by number {p0}…",
    "app.34": " bn EUR",
    "app.35": " m EUR",
    "app.36": " k EUR",
    "app.37": "",
    "app.4": "Automatic retrieval of register data is not available for this country — fill in the profile manually.",
    "app.59": "NIS 2 Directive compliance assessment (JSON)",
    "app.68": "For this country there is no register from which the tool could retrieve data — the profile is filled in manually.",
    "app.69": "For this country there is no register from which the tool could retrieve data. Click to switch offline mode on.",
    "app.73": " · profit and loss account in the ",
    "app.74": "<div class=\"mt-2 tekst-uwaga\">The register data do not indicate any role in the digital infrastructure sector. Select the roles manually below.</div>",
    "app.8": "Entry in the register of electronic communications providers confirmed",
    "app.progDostawcy": "",
    "app.przyklad.adres": "1 Example Street, Example Town",
    "app.przyklad.forma": "Private company limited by shares",
    "app.przyklad.nazwa": "Example Operator Ltd",
    "app.statusVat": " · VAT status: ",
    "dashboard.1": "Based on the declared roles and size, the entity is neither an essential nor an important entity within the meaning of Article 3 of Directive (EU) 2022/2555. Check the profile if the result differs from what you expected.",
    "dashboard.113": "Frequently asked questions",
    "dashboard.12": "— {p0}; the deadline for transposition into national law expired on {p2}",
    "dashboard.123": "NIS 2 Directive",
    "dashboard.30": "List of essential and important entities",
    "dashboard.4": "— directly applicable from {p0} in all Member States, without transposition",
    "dashboard.42": "Fixed-amount variant: {p0}",
    "dashboard.45": "Criteria from Article 32(7) of the Directive:",
    "dashboard.46": "Total",
    "dashboard.49": "The entity carries out electronic communications activity — the liability of the managing person is determined by national law",
    "dashboard.50": "",
    "dashboard.51": "",
    "dashboard.53": "Periodic penalty for delay in complying with a decision: from EUR {p0} to EUR {p1} per day ({p2})",
    "dashboard.54": "Qualified case: up to EUR {p0} ({p1})",
    "dashboard.57": "({p0}). From when the national authority may impose fines is determined by the act transposing the Directive — this module does not know it. Implementation obligations follow from national law from the day it enters into force.",
    "dashboard.65": "({p0}). From when the national authority may impose fines is determined by the act transposing the Directive — this module does not know it. Financial risk is therefore not dated here, while implementation obligations follow from national law from the day it enters into force.",
    "dashboard.83": "Electronic communications activity — thresholds are set by national law.",
    "dashboard.84": "Regulation (EU) 2024/2690 does not apply to providers of public electronic communications networks and services. For them, the thresholds for a significant incident are set by national law (Article 23(11) of the Directive) — this module does not know them, so it gives no figures.",
    "dashboard.terminRejestracji": "The deadline for submitting registration data is set by national law (Article 3(4) of the Directive). Providers under Article 27(1) — DNS service providers, TLD name registries, cloud computing, data centre, content delivery network, managed service and managed security service providers — submit their data to the ENISA registry: originally by 17 January 2025, and every change without undue delay.",
    "html.1": "ITORO — NIS 2 Directive (EU) 2022/2555 compliance assessment",
    "html.10": "NIS 2 Directive compliance assessment — common module",
    "html.100": "Reading a financial statement works only for countries with a national law module. For this country you enter the <strong>revenue</strong> for the financial year manually — the level of the fine depends on it.",
    "html.102": "Automatic retrieval of register data works only for countries with a national law module. You indicate the roles and the enterprise size manually.",
    "html.11": "Directive (EU) 2022/2555 (NIS 2) requires transposition into national law. The assessment covers the obligations that follow directly from the Directive and Commission Implementing Regulation (EU) 2024/2690, which applies directly — to the extent they concern the entity.",
    "html.23": "you enter revenue and size manually — the common module does not query national registers",
    "html.33": "Directive (EU) 2022/2555 of the European Parliament and of the Council of 14 December 2022 (NIS 2)",
    "html.33a": "{p0} — the national act transposing the Directive; this module does not yet assess its requirements",
    "html.33b": "the country has not yet adopted a transposing act — the assessment follows EU law",
    "html.35": "obligations of the management body — Article 20 of the Directive",
    "html.36": "The tool serves self-assessment. It is neither an audit nor legal advice.",
    "html.40": "the common module makes no outgoing connections at all — it does not query registers",
    "html.59": "Financial statements",
    "html.60": "Reading a financial statement is available only for countries with a national law module. For this country you enter revenue and headcount manually.",
    "html.62": "Register search",
    "html.63": "business registers are national — the common module does not know them",
    "html.64": "you indicate the roles and the enterprise size manually",
    "html.66": "Entity identification number",
    "html.68": "Automatic retrieval of register data works only for countries with a national law module.",
    "html.76": "Annual revenue (EUR)",
    "html.78": "Revenue from electronic communications activity (EUR)",
    "html.79": "This field concerns providers of public electronic communications networks or services. National thresholds are set by the law of the Member State.",
    "html.80": "Monthly remuneration of the head of the entity (EUR)",
    "html.82": "Exchange rate",
    "html.83": "The fine ceilings in the Directive are expressed in euro. Conversion into the national currency and the exchange rate are determined by national law — here the amounts are given in euro without conversion.",
    "html.84": "The status results solely from aggregating the data of linked enterprises, and the entity's information system is independent (recital 16 of the Directive — whether this applies is decided by national law)",
    "html.85": "The entity carries out activities in the areas of national security, public security, defence or law enforcement (Article 2(7) of the Directive)",
    "html.91": "Compliance assessment against Directive (EU) 2022/2555 of the European Parliament and of the Council (NIS 2) and Commission Implementing Regulation (EU) 2024/2690 — common module for countries whose national law module is not yet ready.",
    "html.94": "whether the entity is <strong>essential</strong>, <strong>important</strong> or outside the scope of the Directive",
    "html.daneZeSprawozdania": "name, identification number, registered office address",
    "html.rejestrMozliwy": "The {p0} register is public and free of charge — reading it can be added to the tool; we welcome pull requests (see README).",
    "html.tytulNaglowka": "NIS 2 Directive compliance assessment",
    "html.zrodlaRecznie": "This module does not know your country’s registers — fill in the profile by hand. The annual turnover determines the maximum fine, so enter it accurately.",
    "klasyfikacja.10": "Article 3(1)(c) of Directive (EU) 2022/2555 (provider of public electronic communications networks or of publicly available electronic communications services that qualifies at least as a medium-sized enterprise)",
    "klasyfikacja.11": "Article 3(2) in conjunction with Article 2(2)(a)(i) of Directive (EU) 2022/2555 (provider of public electronic communications networks or services that is a micro or small enterprise)",
    "klasyfikacja.12": "Article 3(1)(a) of Directive (EU) 2022/2555 (managed security service provider exceeding the ceilings for a medium-sized enterprise)",
    "klasyfikacja.13": "Micro and small enterprises are not covered by the Directive on account of this role (Article 2(1) a contrario).",
    "klasyfikacja.15": "Article 3(1)(b) of Directive (EU) 2022/2555 (qualified trust service provider) — regardless of enterprise size",
    "klasyfikacja.16": "Article 3(2) in conjunction with Article 2(2)(a)(ii) of Directive (EU) 2022/2555 (non-qualified trust service provider that is a micro, small or medium-sized enterprise)",
    "klasyfikacja.18": "Article 3(2) of Directive (EU) 2022/2555 (public administration entity at regional level, where the Member State so provides — Article 2(2)(f)(ii))",
    "klasyfikacja.19": "Article 3(1)(f) of Directive (EU) 2022/2555 (public administration entity at central government level — Article 2(2)(f)(i))",
    "klasyfikacja.2": "Ex ante and ex post supervision (Article 32 of Directive (EU) 2022/2555).",
    "klasyfikacja.20": "Article 3(2) of Directive (EU) 2022/2555 (public administration entity at regional level — Article 2(2)(f)(ii))",
    "klasyfikacja.21": "The scope of obligations of public administration entities at local level is determined by national law (Article 2(5)(a) of the Directive).",
    "klasyfikacja.22": "A Member State may exempt entities carrying out activities in the areas of national security, public security, defence or law enforcement (Article 2(7) of the Directive). The exemption does not operate by itself — verify the result of the assessment against national law.",
    "klasyfikacja.23": "The entity meets the criteria of both an essential and an important entity. It is an essential entity (Article 3(1) of the Directive), and the higher requirements apply to all activity covered by the Directive.",
    "klasyfikacja.25": "The entity is essential, so the full catalogue of measures under Article 21(2) of the Directive and ex ante and ex post supervision apply — the assessment covers the full set of questions.",
    "klasyfikacja.26": "As an important entity you are subject to the same catalogue of measures under Article 21(2), but to ex post supervision only (Article 33). The fine ceiling is lower: EUR 7 million or 1.4 % of turnover (Article 34(5)). Reliefs for public entities may be introduced by national law — this module does not know them.",
    "klasyfikacja.28": "The obligations of public administration entities follow from Article 2(2)(f) of the Directive; their exact scope, including for local level and educational institutions, is determined by national law (Article 2(5)).",
    "klasyfikacja.29": "It has been declared that the entity's status results solely from aggregating the data of linked or partner enterprises, and that the entity's information system is independent. The Directive allows such an exclusion (recital 16), but national law decides on it — the module assumes the exclusion, which must be verified against the law of the Member State and documented.",
    "klasyfikacja.4": "Ex post supervision only — where there is evidence, indication or information of an infringement (Article 33 of Directive (EU) 2022/2555).",
    "klasyfikacja.5": "Outside the scope of the Directive",
    "klasyfikacja.6": "No obligations under Directive (EU) 2022/2555 for the indicated role.",
    "klasyfikacja.7": "Article 3(1)(a) of Directive (EU) 2022/2555 (entity of a type listed in Annex I exceeding the ceilings for a medium-sized enterprise)",
    "klasyfikacja.8": "Article 3(2) of Directive (EU) 2022/2555 (entity of a type listed in Annex I meeting the criteria for a medium-sized enterprise)",
    "klasyfikacja.9": "Micro and small enterprises are not covered by the Directive on account of this role (Article 2(1) a contrario).",
    "kreator.10": "Enter the previous year's revenue manually.",
    "kreator.35": "<span class=\"text-secondary\">Reading financial statements is not available for this country.</span>",
    "kreator.37": "Reading financial statements is not available for this country — enter the revenue manually.",
    "kreator.56": "Yes — the EU Regulation applies directly from 7 November 2024 in all Member States and has no transitional period. Its basis is",
    "kreator.57": ", which empowered the Commission to lay down the technical and methodological requirements for the providers listed in Article 3(1) of the Regulation. The deadline for transposing the Directive expired on",
    "kreator.58": ", and from when the national authority may impose fines is determined by national law. The technical requirements of the Annex (sections 6 and 9–13) are binding as they stand — they do not wait for further clarification. Only requirements qualified by the phrase “where appropriate” may be departed from, and only with a documented justification.",
    "kreator.9": "Financial statements →",
    "kreator.przepisReg2690": "Article 21(5) of Directive (EU) 2022/2555",
    "kreator.terminReg2690": "17 October 2024",
    "punktacja.10": "Public entities",
    "punktacja.4": "NIS 2 Directive — Article 21",
    "punktacja.5": "NIS 2 Directive — formal obligations",
    "punktacja.8": "Electronic communications",
    "punktacja.9": "NIS 2 Directive — public entities",
    "punktacja.skrotKsc": "NIS 2",
    "punktacja.skrotPke": "telecom",
    "ue.cyt.akapit": ", {p0} subparagraph",
    "ue.cyt.art": "Article {p0}",
    "ue.cyt.drugi": "second",
    "ue.cyt.dyr": "{p0} of Directive (EU) 2022/2555",
    "ue.cyt.i": "and",
    "ue.cyt.laczenie": "",
    "ue.cyt.lit": "({p0})",
    "ue.cyt.litery": "",
    "ue.cyt.pkt": ", point ({p0})",
    "ue.cyt.rozdzielacz": "; ",
    "ue.cyt.rozp": "{p0} of Regulation (EU) 2024/2690",
    "ue.cyt.ust": "({p0})",
    "ue.katalog.1": "Policies on risk analysis and information system security",
    "ue.katalog.10": "Incident handling",
    "ue.katalog.11": "Incident handling means any actions and procedures aiming to prevent, detect, analyse and contain or to respond to and recover from an incident (Article 6, point (8)).",
    "ue.katalog.12": "Is there a documented incident handling procedure covering detection, analysis, containment, response and recovery?",
    "ue.katalog.13": "ISO/IEC 27001 A.5.24–A.5.26",
    "ue.katalog.14": "Does the procedure make it possible to meet the deadlines for reporting a significant incident: early warning within 24 hours, incident notification within 72 hours, final report within one month?",
    "ue.katalog.15": "ISO/IEC 27001 A.5.24",
    "ue.katalog.16": "Does the entity have criteria for considering an incident significant, consistent with Article 23(3): severe operational disruption or financial loss, or considerable damage to other persons?",
    "ue.katalog.17": "ISO/IEC 27001 A.5.25",
    "ue.katalog.18": "Are incidents recorded and are lessons learned from handling them used to improve the measures?",
    "ue.katalog.19": "ISO/IEC 27001 A.5.27",
    "ue.katalog.2": "The measures are based on an all-hazards approach (Article 21(2)). Their proportionality is assessed taking into account the degree of exposure, the entity's size, the likelihood of incidents and their severity (Article 21(1), second subparagraph).",
    "ue.katalog.20": "Business continuity and crisis management",
    "ue.katalog.21": "Business continuity, such as backup management and disaster recovery, and crisis management.",
    "ue.katalog.22": "Is there a business continuity plan that covers recovery after a disaster?",
    "ue.katalog.23": "ISO/IEC 27001 A.5.29–A.5.30",
    "ue.katalog.24": "Are backups made, protected and tested for restorability?",
    "ue.katalog.25": "ISO/IEC 27001 A.8.13",
    "ue.katalog.26": "Does the entity have crisis management procedures with defined roles and communication channels?",
    "ue.katalog.27": "ISO/IEC 27001 A.5.29",
    "ue.katalog.28": "Are continuity and recovery plans tested periodically, with the results documented?",
    "ue.katalog.29": "ISO/IEC 27001 A.5.30",
    "ue.katalog.3": "Does the entity have a documented policy on risk analysis and information system security, approved by the management body?",
    "ue.katalog.30": "Supply chain security",
    "ue.katalog.31": "Supply chain security, including security-related aspects concerning the relationships between the entity and its direct suppliers or service providers. The entity takes into account the vulnerabilities specific to each supplier and the overall quality of its products and cybersecurity practices (Article 21(3)).",
    "ue.katalog.32": "Does the entity keep a list of direct suppliers and service providers together with an assessment of their significance for the security of networks and systems?",
    "ue.katalog.33": "ISO/IEC 27001 A.5.19",
    "ue.katalog.34": "When selecting measures for suppliers, are the vulnerabilities specific to each of them and the quality of their cybersecurity and secure development practices taken into account?",
    "ue.katalog.35": "ISO/IEC 27001 A.5.19, A.5.21",
    "ue.katalog.36": "Do contracts with suppliers contain security requirements and an obligation to report incidents and vulnerabilities?",
    "ue.katalog.37": "ISO/IEC 27001 A.5.20",
    "ue.katalog.38": "Does the entity take into account the results of the coordinated security risk assessments of critical supply chains referred to in Article 22?",
    "ue.katalog.39": "ISO/IEC 27001 A.5.21",
    "ue.katalog.4": "ISO/IEC 27001 clauses 5.2, 6.1.2",
    "ue.katalog.40": "Security in acquisition, development and maintenance of systems",
    "ue.katalog.41": "Security in network and information systems acquisition, development and maintenance, including vulnerability handling and disclosure.",
    "ue.katalog.42": "Are security requirements defined before a system is acquired or its development begins, and verified before deployment?",
    "ue.katalog.43": "ISO/IEC 27001 A.8.25–A.8.29",
    "ue.katalog.44": "Is there a vulnerability handling process: identification, assessment, remediation within a defined time?",
    "ue.katalog.45": "ISO/IEC 27001 A.8.8",
    "ue.katalog.46": "Does the entity have a vulnerability disclosure procedure, including a channel for receiving reports from third parties?",
    "ue.katalog.47": "Do changes to systems go through a controlled change management process with an assessment of the impact on security?",
    "ue.katalog.48": "ISO/IEC 27001 A.8.32",
    "ue.katalog.49": "Assessing the effectiveness of measures",
    "ue.katalog.5": "Does the risk analysis cover all hazards to network and information systems and their physical environment, not only cyber threats?",
    "ue.katalog.50": "Policies and procedures to assess the effectiveness of cybersecurity risk-management measures.",
    "ue.katalog.51": "Is there a documented policy for assessing the effectiveness of measures that defines the scope, frequency and methods?",
    "ue.katalog.52": "ISO/IEC 27001 clause 9.1",
    "ue.katalog.53": "Are effectiveness assessments carried out periodically and their results reported to the management body?",
    "ue.katalog.54": "ISO/IEC 27001 clauses 9.2–9.3",
    "ue.katalog.55": "Do identified weaknesses lead to documented corrective actions with an owner and a deadline?",
    "ue.katalog.56": "ISO/IEC 27001 clause 10.1",
    "ue.katalog.57": "Cyber hygiene and training",
    "ue.katalog.58": "Basic cyber hygiene practices and cybersecurity training. Members of the management body follow regular training (Article 20(2)).",
    "ue.katalog.59": "Does the entity apply basic cyber hygiene practices: updates, password management, restriction of privileges, protection against malware?",
    "ue.katalog.6": "ISO/IEC 27001 clause 6.1.2",
    "ue.katalog.60": "ISO/IEC 27001 A.8.7, A.8.8",
    "ue.katalog.61": "Do employees receive cybersecurity training tailored to their role, with participation documented?",
    "ue.katalog.62": "ISO/IEC 27001 A.6.3",
    "ue.katalog.63": "Do members of the management body follow regular training enabling them to identify risks and assess risk-management practices?",
    "ue.katalog.64": "ISO/IEC 27001 clause 7.2",
    "ue.katalog.65": "Cryptography and encryption",
    "ue.katalog.66": "Policies and procedures regarding the use of cryptography and, where appropriate, encryption.",
    "ue.katalog.67": "Is there a cryptography policy that defines which data and channels are subject to encryption and with which algorithms?",
    "ue.katalog.68": "ISO/IEC 27001 A.8.24",
    "ue.katalog.69": "Are cryptographic keys managed across their full lifecycle: generation, distribution, storage, rotation, retirement?",
    "ue.katalog.7": "Does the choice of measures take into account the state of the art, relevant European and international standards and the cost of implementation?",
    "ue.katalog.70": "Human resources, access control and asset management",
    "ue.katalog.71": "Human resources security, access control policies and asset management.",
    "ue.katalog.72": "Does the entity keep an up-to-date asset inventory with assigned owners and classification?",
    "ue.katalog.73": "ISO/IEC 27001 A.5.9, A.5.12",
    "ue.katalog.74": "Is there an access control policy based on the least-privilege principle, with periodic review of privileges?",
    "ue.katalog.75": "ISO/IEC 27001 A.5.15, A.5.18",
    "ue.katalog.76": "Are security procedures applied on hiring, change of position and departure of an employee, including revocation of privileges and return of assets?",
    "ue.katalog.77": "ISO/IEC 27001 A.6.1–A.6.5",
    "ue.katalog.78": "Is privileged access restricted, logged and reviewed?",
    "ue.katalog.79": "ISO/IEC 27001 A.8.2",
    "ue.katalog.8": "ISO/IEC 27001 clause 6.1.3",
    "ue.katalog.80": "Multi-factor authentication and secured communications",
    "ue.katalog.81": "Where appropriate — multi-factor or continuous authentication, secured voice, video and text communications and secured emergency communication systems within the entity.",
    "ue.katalog.82": "Is multi-factor or continuous authentication used where the risk analysis justifies it, in particular for remote access and privileged accounts?",
    "ue.katalog.83": "ISO/IEC 27001 A.8.5",
    "ue.katalog.84": "Are the voice, video and text communications used for business purposes secured?",
    "ue.katalog.85": "ISO/IEC 27001 A.8.20",
    "ue.katalog.86": "Does the entity have a secured internal emergency communication system, independent of the primary infrastructure?",
    "ue.katalog.9": "Is the level of security documented as appropriate to the risks posed, with a justification that takes into account the entity's size and the societal and economic impact of incidents?",
    "ue.kierownictwo.1": "The management body of an essential or important entity — in a company, the board of directors. The Directive does not define the term; its scope in a given country follows from national law.",
    "ue.kierownictwo.10": "Determine the entity's status and ensure registration",
    "ue.kierownictwo.11": "Determining whether the entity is essential or important and submitting registration data to the competent authority. The procedure and deadline are set by national law.",
    "ue.kierownictwo.12": "Implement risk analysis and a security policy",
    "ue.kierownictwo.13": "Measures based on an all-hazards approach, proportionate to exposure, the entity's size and the severity of incidents.",
    "ue.kierownictwo.14": "Set up incident handling and reporting",
    "ue.kierownictwo.15": "An incident handling procedure and the ability to meet the 24-hour, 72-hour and one-month deadlines.",
    "ue.kierownictwo.16": "24 h / 72 h / one month from detection",
    "ue.kierownictwo.17": "Ensure business continuity",
    "ue.kierownictwo.18": "Continuity plan, backups, disaster recovery, crisis management.",
    "ue.kierownictwo.19": "Put the supply chain in order",
    "ue.kierownictwo.2": "The liability of the management body is without prejudice to national rules on the liability of public institutions and officials (Article 20(1), second subparagraph).",
    "ue.kierownictwo.20": "List of suppliers, assessment of their vulnerabilities and practices, security requirements in contracts.",
    "ue.kierownictwo.21": "Implement access control and asset management",
    "ue.kierownictwo.22": "Asset inventory, least-privilege principle, privilege reviews, multi-factor authentication where the risk justifies it.",
    "ue.kierownictwo.23": "Measure the effectiveness of measures",
    "ue.kierownictwo.24": "Effectiveness assessment policy and procedures, periodic reviews, corrective actions.",
    "ue.kierownictwo.25": "Approve",
    "ue.kierownictwo.26": "the cybersecurity risk-management measures (Article 20(1))",
    "ue.kierownictwo.27": "the policy on risk analysis and system security",
    "ue.kierownictwo.28": "the budget and roles in the implementation",
    "ue.kierownictwo.29": "Oversee",
    "ue.kierownictwo.3": "Whether entrusting duties to another person removes liability is decided by national law. In Poland it does not (Article 8c(3) of the Act on the National Cybersecurity System).",
    "ue.kierownictwo.30": "implementation of the approved measures (Article 20(1))",
    "ue.kierownictwo.31": "the results of the effectiveness assessment (Article 21(2)(f))",
    "ue.kierownictwo.32": "compliance with incident reporting deadlines (Article 23)",
    "ue.kierownictwo.33": "Document",
    "ue.kierownictwo.34": "approval decisions and reviews",
    "ue.kierownictwo.35": "participation in training (Article 20(2))",
    "ue.kierownictwo.36": "Member of the management body",
    "ue.kierownictwo.37": "approval of measures, oversight, decisions, budget",
    "ue.kierownictwo.38": "Project manager",
    "ue.kierownictwo.39": "coordination of implementation, schedule, status and evidence",
    "ue.kierownictwo.4": "Approve the cybersecurity risk-management measures",
    "ue.kierownictwo.40": "IT / cybersecurity",
    "ue.kierownictwo.41": "risk analysis, technical measures, incident handling",
    "ue.kierownictwo.42": "Legal / compliance",
    "ue.kierownictwo.5": "The management body approves the measures taken to comply with Article 21. This is a decision of the body, not of the IT department — without it the measures have no mandate.",
    "ue.kierownictwo.6": "Oversee the implementation of the measures",
    "ue.kierownictwo.7": "Oversight of implementation is an obligation of the management body. Execution can be delegated; oversight cannot.",
    "ue.kierownictwo.8": "Follow regular training",
    "ue.kierownictwo.9": "Members of the management body follow regular training to gain sufficient knowledge to identify risks and assess risk-management practices and their impact on the entity's services.",
    "ue.kierownictwo.daneRejestracyjne": "registration data and their updates (Article 3(4)–(5))",
    "ue.meta.1": "The percentage variant prevails: {p0} % of turnover is higher than EUR {p1} million.",
    "ue.meta.10": "The Directive does not impose obligations on undertakings directly — the national act does, which the Member State was to adopt by 17 October 2024. This module shows the requirements as worded in the Directive, because the national law module for the selected country is not yet ready or the country has not transposed the Directive.",
    "ue.meta.11": "Obligations under the Directive",
    "ue.meta.12": "List of entities — by 17 April 2025",
    "ue.meta.13": "Member States were to establish a list of essential and important entities by 17 April 2025 and require entities to submit registration data.",
    "ue.meta.14": "Regulation (EU) 2024/2690",
    "ue.meta.15": "Directly applicable from 7 November 2024",
    "ue.meta.16": "The Implementing Regulation applies directly in all Member States, regardless of the state of transposition of the Directive. It concerns the entities listed in its Article 1: DNS, TLD, cloud, data centre, content delivery network, managed service and trust service providers.",
    "ue.meta.17": "Article 16 of Regulation (EU) 2024/2690",
    "ue.meta.18": "At least EUR 10 000 000 or at least 2 % of the total worldwide annual turnover of the undertaking in the preceding financial year — whichever is higher. This is a minimum ceiling: national law may raise it.",
    "ue.meta.19": "At least EUR 7 000 000 or 1.4 % of the total worldwide annual turnover — whichever is higher. Minimum ceiling.",
    "ue.meta.2": "The fixed amount prevails: EUR {p0} million is higher than {p1} % of turnover.",
    "ue.meta.20": "The Directive provides no separate fine for a qualified infringement — that is a construct of the national law of some Member States.",
    "ue.meta.21": "Member States may provide for periodic penalty payments to compel an entity to cease an infringement. The amount is set by national law.",
    "ue.meta.22": "The management body approves the risk-management measures, oversees their implementation and can be held liable for infringements of Article 21. The rules and extent of that liability are determined by national law.",
    "ue.meta.23": "The management body approves the cybersecurity risk-management measures (Article 20(1)).",
    "ue.meta.24": "The management body oversees the implementation of those measures (Article 20(1)).",
    "ue.meta.25": "Members of the management body follow regular training (Article 20(2)).",
    "ue.meta.26": "In respect of an essential entity the authority may request a temporary prohibition on exercising managerial functions (Article 32(5)(b)).",
    "ue.meta.27": "The minimum ceiling is set by the Directive",
    "ue.meta.28": "Two values are compared: a fixed amount in euro and a percentage of the undertaking's total worldwide annual turnover in the preceding financial year. The higher of the two is the upper limit that the Member State must provide for at a minimum. National law may raise it.",
    "ue.meta.29": "The amount within the ceiling is set by the national authority",
    "ue.meta.3": "The ceiling from the Directive exceeds the entity's annual turnover {p0}-fold. Article 34(1) requires the fine to be proportionate to the circumstances of the individual case — this is an upper limit, not an expected fine.",
    "ue.meta.30": "The fine must be effective, proportionate and dissuasive according to the circumstances of the individual case. The authority takes into account at least the criteria of Article 32(7): the gravity and duration of the infringement, previous infringements, damage caused, intent, remedial measures and cooperation.",
    "ue.meta.31": "The ceiling may exceed annual turnover many times over — it is an upper limit, not an expected amount. National minimums, periodic penalties and the procedure for setting fines are determined by the law of the Member State.",
    "ue.meta.32": "When deciding whether to impose an administrative fine and its amount, due regard is given in each individual case to at least the elements listed in Article 32(7).",
    "ue.meta.33": "the gravity of the infringement and the importance of the provisions breached — the following are in any event considered serious: repeated infringements, failure to notify or remedy significant incidents, failure to remedy deficiencies contrary to binding instructions, obstruction of audits or monitoring, provision of false or grossly inaccurate information",
    "ue.meta.34": "any relevant previous infringements by the entity",
    "ue.meta.35": "any material or non-material damage caused, including financial loss, effects on other services and the number of users affected",
    "ue.meta.36": "the intentional or negligent character of the infringement",
    "ue.meta.37": "measures taken to prevent or mitigate the damage",
    "ue.meta.38": "adherence to approved codes of conduct or certification mechanisms",
    "ue.meta.39": "the degree of cooperation with the competent authorities",
    "ue.meta.4": "Directive (EU) 2022/2555 of the European Parliament and of the Council (NIS 2)",
    "ue.meta.40": "The Directive does not expressly provide for waiving a fine — whether and when this is possible is decided by national law.",
    "ue.meta.41": "From this date Member States are to apply the national provisions implementing the Directive. The specific date from which the authority may impose a fine follows from national law.",
    "ue.meta.42": "Entry into force of the NIS 2 Directive",
    "ue.meta.43": "On the twentieth day following publication in the Official Journal.",
    "ue.meta.44": "Deadline for transposing the Directive",
    "ue.meta.45": "By this date Member States were to adopt and publish national provisions.",
    "ue.meta.46": "Application of national provisions and repeal of NIS 1",
    "ue.meta.47": "From this date Member States apply the implementing provisions; Directive (EU) 2016/1148 is repealed.",
    "ue.meta.48": "Application of Regulation (EU) 2024/2690",
    "ue.meta.49": "The Implementing Regulation applies directly from the twentieth day following publication.",
    "ue.meta.5": "OJ EU L 333, 27.12.2022",
    "ue.meta.50": "List of essential and important entities",
    "ue.meta.51": "By this date Member States establish the list; entities submit registration data to the authorities.",
    "ue.meta.52": "First review of the Directive by the Commission",
    "ue.meta.53": "The Commission reviews the functioning of the Directive and submits a report.",
    "ue.meta.54": "Early warning of a significant incident",
    "ue.meta.55": "24 hours after becoming aware",
    "ue.meta.56": "Notification of a significant incident",
    "ue.meta.57": "72 hours after becoming aware",
    "ue.meta.58": "Final report",
    "ue.meta.59": "one month after the incident notification",
    "ue.meta.6": "Commission Implementing Regulation (EU) 2024/2690",
    "ue.meta.60": "Incident notification by a trust service provider",
    "ue.meta.61": "Article 21(5) of Directive (EU) 2022/2555; Articles 1 and 2 of Regulation (EU) 2024/2690",
    "ue.meta.62": "Without turnover data the ceiling is the fixed amount from the Directive.",
    "ue.meta.63": "The ceilings in Article 34(4) and (5) are minimums (“at least”) — national law may provide for higher ones. Amounts in euro, without conversion into the national currency.",
    "ue.meta.64": "Competent authority of the Member State",
    "ue.meta.65": "The management body can be held liable for infringements of Article 21. The extent and procedure are determined by national law — this module does not know them.",
    "ue.meta.66": "The extent of the personal liability of management follows from the national act. For Poland it is up to 300 % of remuneration (Article 73a(4) of the Act on the National Cybersecurity System); other Member States decide differently.",
    "ue.meta.7": "OJ EU L, 2024/2690",
    "ue.meta.8": "Directive (EU) 2022/2555",
    "ue.meta.9": "The transposition deadline expired on 17 October 2024",
    "ue.moduly.1": "about {p0} min",
    "ue.moduly.10": "Ten areas from Article 21(2)(a)–(j): from the risk policy to multi-factor authentication. Infringement is subject to a fine under Article 34. Assessed on the maturity scale.",
    "ue.moduly.11": "Regulation 2024/2690 — governance and processes",
    "ue.moduly.12": "Sections 1–5 and 7–8 of the Annex: policies, risk management, incident handling, business continuity, supply chain, effectiveness assessment, cyber hygiene. Directly applicable from 7 November 2024.",
    "ue.moduly.13": "Regulation 2024/2690 — technical requirements",
    "ue.moduly.14": "Sections 6 and 9–13 of the Annex: acquisition and development of systems, cryptography, human resources security, access control, asset management, physical and environmental security.",
    "ue.moduly.2": "about {p0} h {p1} min",
    "ue.moduly.3": "about {p0} h",
    "ue.moduly.4": "under a minute",
    "ue.moduly.5": "Quick risk assessment",
    "ue.moduly.6": "Overarching questions from all areas of the Directive. Each one decides a whole group of issues. It lets you estimate the scale of the backlog without going through the full questionnaire.",
    "ue.moduly.7": "Obligations under the Directive",
    "ue.moduly.8": "Registration data, incident reporting within 24 and 72 hours, obligations of the management body, readiness for supervision. Verifiable from documents, without technical analysis.",
    "ue.moduly.9": "Risk-management measures — Article 21(2)",
    "ue.obowiazki.1": "Registration data for the list of entities",
    "ue.obowiazki.10": "Reporting significant incidents",
    "ue.obowiazki.11": "The entity reports significant incidents to the CSIRT or the competent authority in three steps: early warning, incident notification, final report. The deadlines run from becoming aware of the incident.",
    "ue.obowiazki.12": "Is the entity able to submit an early warning within 24 hours of becoming aware of a significant incident, indicating whether the incident is suspected of being caused by unlawful acts and whether it could have a cross-border impact?",
    "ue.obowiazki.13": "24 hours after becoming aware",
    "ue.obowiazki.14": "Is the entity able to submit an incident notification within 72 hours, with an initial assessment of severity and impact and indicators of compromise?",
    "ue.obowiazki.15": "72 hours after becoming aware",
    "ue.obowiazki.16": "Does the entity submit a final report no later than one month after the notification, with a description of the incident, the type of threat, the mitigation measures and the cross-border impact?",
    "ue.obowiazki.17": "one month after the notification",
    "ue.obowiazki.18": "Does the entity notify the recipients of its services of significant incidents that are likely to adversely affect the provision of those services?",
    "ue.obowiazki.19": "Does the entity notify the recipients of its services of a significant cyber threat and of the remedies they can take?",
    "ue.obowiazki.2": "Member States establish a list of essential and important entities and require entities to submit registration data. The procedure, deadline and portal are set by national law.",
    "ue.obowiazki.20": "If the entity is a trust service provider — does it report significant incidents within 24 hours of becoming aware?",
    "ue.obowiazki.21": "applies to trust service providers",
    "ue.obowiazki.22": "Management body",
    "ue.obowiazki.23": "The management body approves the risk-management measures, oversees their implementation and can be held liable. Members of the body follow regular training.",
    "ue.obowiazki.24": "Has the management body formally approved the cybersecurity risk-management measures taken to comply with Article 21?",
    "ue.obowiazki.25": "Does the management body oversee the implementation of those measures in a documented way — for example through periodic reports and reviews?",
    "ue.obowiazki.26": "Do members of the management body follow regular training enabling them to identify risks and assess risk-management practices, with participation documented?",
    "ue.obowiazki.27": "Readiness for supervisory measures",
    "ue.obowiazki.28": "An essential entity is subject to ex ante and ex post supervision, an important entity to ex post supervision only. The authority may request information, evidence of implementation of policies and audit results.",
    "ue.obowiazki.29": "Is the entity able, at the authority's request, to provide evidence of implementation of cybersecurity policies, including the results of security audits?",
    "ue.obowiazki.3": "Has the entity determined whether it is an essential or an important entity, based on the sector in Annex I or II and the enterprise size?",
    "ue.obowiazki.30": "Is the entity able, at the authority's request, to provide the data, documents and information necessary to carry out supervisory tasks?",
    "ue.obowiazki.31": "Is the essential entity prepared for a security audit carried out by the authority or an independent body, at its own cost?",
    "ue.obowiazki.4": "Has the entity submitted registration data to the competent authority: name, address and contact details, sector and subsector, list of the Member States in which it provides services?",
    "ue.obowiazki.5": "Contact details include e-mail addresses, IP ranges and telephone numbers. The national deadline and registration portal are set by the law of the Member State.",
    "ue.obowiazki.6": "Is there a process for updating registration data without undue delay after they change?",
    "ue.obowiazki.7": "The Directive requires updates without undue delay; a specific deadline — for example 14 days in Poland — follows from national law.",
    "ue.obowiazki.8": "If the entity is a DNS service provider, TLD name registry, cloud, data centre, CDN or managed service provider, online marketplace, search engine or social networking platform — has it submitted the additional data under Article 27, including the address of its main establishment in the Union?",
    "ue.obowiazki.9": "applies to entities under Article 26(1)",
    "ue.role.1": "Competent authority of the Member State",
    "ue.role.10": "Data centre services: colocation, infrastructure hosting and related services.",
    "ue.role.11": "Data centres",
    "ue.role.12": "Essential entity above the medium-sized enterprise threshold (Article 3(1)(a)), important entity when medium-sized (Article 3(2)). Below medium-sized — outside the scope, unless the Member State identifies the entity under Article 2(2)(b)–(e). Covered by Regulation 2024/2690.",
    "ue.role.13": "Internet exchange point provider",
    "ue.role.14": "Infrastructure enabling the exchange of traffic between independent networks.",
    "ue.role.15": "Internet exchange points",
    "ue.role.16": "Size-based classification (Article 3(1)(a) and (2)). Regulation 2024/2690 does not cover internet exchange points — Article 1 of the Regulation contains a closed list of addressees.",
    "ue.role.17": "DNS service provider",
    "ue.role.18": "Domain name resolution services, excluding root name server operators.",
    "ue.role.19": "Domain name system",
    "ue.role.2": "competent authority",
    "ue.role.20": "Essential entity regardless of size (Article 3(1)(b)). Covered by Regulation 2024/2690.",
    "ue.role.21": "Top-level domain name registry",
    "ue.role.22": "Operation of a top-level domain registry.",
    "ue.role.23": "Essential entity regardless of size (Article 3(1)(b)). Additionally subject to the registration data obligations of Article 28. Covered by Regulation 2024/2690.",
    "ue.role.24": "Cloud computing service provider",
    "ue.role.25": "Cloud computing services: infrastructure, platform, software as a service.",
    "ue.role.26": "Cloud computing services",
    "ue.role.27": "Size-based classification (Article 3(1)(a) and (2)). Covered by Regulation 2024/2690.",
    "ue.role.28": "Content delivery network provider",
    "ue.role.29": "A network of distributed servers delivering content and services to end users.",
    "ue.role.3": "designated by national law; until the national module is implemented the tool does not name a specific institution",
    "ue.role.30": "Content delivery networks",
    "ue.role.31": "Trust service provider",
    "ue.role.32": "Trust services within the meaning of Regulation (EU) No 910/2014: signatures, seals, time stamps, certificates.",
    "ue.role.33": "Trust services",
    "ue.role.34": "Covered by the Directive regardless of size (Article 2(2)(a)(ii)). A qualified provider is an essential entity regardless of size (Article 3(1)(b)); a non-qualified one is essential above the medium-sized threshold and important otherwise. Covered by Regulation 2024/2690.",
    "ue.role.35": "Managed service provider",
    "ue.role.36": "Management of the customer's ICT infrastructure: installation, maintenance, support, system administration.",
    "ue.role.37": "ICT service management (B2B)",
    "ue.role.38": "Managed services",
    "ue.role.39": "Managed security service provider",
    "ue.role.4": "Provider of public electronic communications networks or of publicly available electronic communications services",
    "ue.role.40": "Managed services in the field of cybersecurity: monitoring, incident response, testing, consultancy.",
    "ue.role.41": "Managed security services",
    "ue.role.42": "The Directive classifies by size (Article 3(1)(a) and (2)). Member States may tighten the threshold — Poland treats an MSSP as an essential entity from small enterprise size upwards; this module applies the Directive's rule only. Covered by Regulation 2024/2690.",
    "ue.role.5": "Provision of public electronic communications networks or of publicly available electronic communications services, including internet access.",
    "ue.role.6": "Digital infrastructure",
    "ue.role.7": "Electronic communications",
    "ue.role.8": "Covered by the Directive regardless of size (Article 2(2)(a)(i)). A medium-sized or larger enterprise is an essential entity (Article 3(1)(c)), a micro or small one an important entity (Article 3(2)). National electronic communications law may impose additional obligations — this module does not contain them.",
    "ue.role.9": "Data centre service provider",
    "ue.role.podstawaArt3b": "Article 3(1)(b) of Directive (EU) 2022/2555",
    "ue.zaslepki.1": "Directive (EU) 2022/2555 of the European Parliament and of the Council (NIS 2)",
    "ue.zaslepki.10": "Whether some entities are entered ex officio is decided by national law.",
    "ue.zaslepki.11": "Determine whether you fall under the Directive",
    "ue.zaslepki.12": "Sector from Annex I or II and enterprise size. This part is done by the entity profile in this tool.",
    "ue.zaslepki.13": "Identify the competent authority in your country",
    "ue.zaslepki.14": "Each Member State designates a competent authority (Article 8(1)). ENISA and the Commission keep the current list.",
    "ue.zaslepki.15": "Submit registration data",
    "ue.zaslepki.16": "Name, address and contact details, sector and subsector, Member States in which services are provided (Article 3(4)). Procedure according to national law.",
    "ue.zaslepki.17": "Update the data without undue delay",
    "ue.zaslepki.18": "Any change to the registration data requires an update (Article 3(5)).",
    "ue.zaslepki.19": "address and up-to-date contact details: e-mail addresses, IP ranges, telephone numbers",
    "ue.zaslepki.2": "OJ EU L 333, 27.12.2022, p. 80",
    "ue.zaslepki.20": "sector and subsector from Annex I or II",
    "ue.zaslepki.21": "list of the Member States in which the entity provides services",
    "ue.zaslepki.22": "Determined by national law.",
    "ue.zaslepki.23": "Directive (EU) 2022/2555 — Article 3",
    "ue.zaslepki.24": "ENISA — competent authorities of the Member States",
    "ue.zaslepki.25": "Directive (EU) 2022/2555",
    "ue.zaslepki.26": "The EU module contains no guidance from a national authority — that will come with the national law module.",
    "ue.zaslepki.27": "Automatic retrieval of register data works only for countries with a national law module. Fill in the profile manually.",
    "ue.zaslepki.28": "Reading a financial statement works only for countries with a national law module. Enter revenue and headcount manually.",
    "ue.zaslepki.3": "Commission Implementing Regulation (EU) 2024/2690",
    "ue.zaslepki.4": "OJ EU L, 2024/2690, 18.11.2024",
    "ue.zaslepki.5": "The NIS 2 Directive contains no separate electronic communications layer. National electronic communications law may impose additional obligations — this module does not know them.",
    "ue.zaslepki.6": "List of essential and important entities",
    "ue.zaslepki.7": "Competent authority of the Member State.",
    "ue.zaslepki.8": "The Directive requires Member States to keep a list of essential and important entities and to require entities to submit registration data. The portal, procedure and deadline are set by national law — this module does not know them, because the national law module for the selected country is not yet ready.",
    "ue.zaslepki.9": "All essential and important entities. The deadline is set by national law.",
    "ue.zaslepki.skrotDyrektywy": "NIS 2 Directive",
    "ue.zaslepki.skrotReg2690": "Reg. 2024/2690",
    "xlsx.1": "EUR {p0} – {p1}",
    "xlsx.25": "Exchange rate",
    "xlsx.4": "NIS 2 DIRECTIVE (EU) 2022/2555 COMPLIANCE REPORT",
    "xlsx.58": "Electronic communications activity: Regulation (EU) 2024/2690 does not apply. Thresholds are set by national law (Article 23(11) of the Directive) — the common module does not know them.",
    "xlsx.68": "The tool serves self-assessment. It is neither an audit nor legal advice.",
    "xlsx.69": "For entities not covered by Regulation (EU) 2024/2690, the thresholds for a significant incident are set by national law (Article 23(11) of the Directive).",
    "xlsx.70": "The roles indicated in the profile are a declaration. Status is determined by the activity actually carried out (Article 3 of Directive (EU) 2022/2555).",
    "xlsx.etykietaKrs": "Register number",
    "xlsx.etykietaNip": "Identification number",
    "xlsx.etykietaRegon": "Statistical number"
});
