/* Teksty modułu ue — język: es.
   Te same klucze co w napisy/pl.js (wersja źródłowa); wstawki {p0}, {p1}…
   pozostają bez zmian. Klucze ue.cyt.* to wzorce składania odesłań
   do przepisów w tym języku — patrz kraje/ue/cytaty.js. */
KRAJE.napisy('ue', 'es', {
    "app.10": "Revise la lista de funciones más abajo: el estatus lo determina la actividad realmente ejercida (artículo 3 de la Directiva (UE) 2022/2555), no una inscripción registral.",
    "app.14": "Año anterior: {p0} EUR",
    "app.15": "Ingresos del periodo de referencia: {p0} EUR",
    "app.19": "Consultando registros con el número {p0}…",
    "app.34": " mil millones EUR",
    "app.35": " millones EUR",
    "app.36": " mil EUR",
    "app.37": "",
    "app.4": "La obtención automática de datos registrales no está disponible para este país: rellene el perfil manualmente.",
    "app.59": "Evaluación de cumplimiento de la Directiva NIS 2 (JSON)",
    "app.68": "Para este país no existe ningún registro del que la herramienta pueda obtener datos: el perfil se rellena manualmente.",
    "app.69": "Para este país no existe ningún registro del que la herramienta pueda obtener datos. Pulse para activar el modo sin conexión.",
    "app.73": " · cuenta de pérdidas y ganancias en la variante ",
    "app.74": "<div class=\"mt-2 tekst-uwaga\">De los datos registrales no se deduce ninguna función del sector de infraestructuras digitales. Indique las funciones manualmente más abajo.</div>",
    "app.8": "Inscripción en el registro de proveedores de comunicaciones electrónicas confirmada",
    "app.progDostawcy": "",
    "app.przyklad.adres": "Calle Ejemplo 1, 28000 Ciudad",
    "app.przyklad.forma": "Sociedad de responsabilidad limitada",
    "app.przyklad.nazwa": "Operador de Ejemplo, S.L.",
    "app.statusVat": " · estado IVA: ",
    "dashboard.1": "Según las funciones y el tamaño declarados, la entidad no es ni esencial ni importante en el sentido del artículo 3 de la Directiva (UE) 2022/2555. Revise el perfil si el resultado no coincide con lo esperado.",
    "dashboard.113": "Preguntas frecuentes",
    "dashboard.12": "— {p0}; el plazo de transposición al derecho nacional venció el {p2}",
    "dashboard.123": "Directiva NIS 2",
    "dashboard.30": "Lista de entidades esenciales e importantes",
    "dashboard.4": "— de aplicación directa desde el {p0} en todos los Estados miembros, sin transposición",
    "dashboard.42": "Variante de cuantía fija: {p0}",
    "dashboard.45": "Criterios del artículo 32, apartado 7, de la Directiva:",
    "dashboard.46": "Total",
    "dashboard.49": "La entidad ejerce una actividad de comunicaciones electrónicas: la responsabilidad del directivo la determina el derecho nacional",
    "dashboard.50": "",
    "dashboard.51": "",
    "dashboard.53": "Multa coercitiva por retraso en el cumplimiento de una decisión: de {p0} EUR a {p1} EUR por día ({p2})",
    "dashboard.54": "Caso cualificado: hasta {p0} EUR ({p1})",
    "dashboard.57": "({p0}). Desde cuándo puede la autoridad nacional imponer multas lo determina la ley de transposición; este módulo no la conoce. Las obligaciones de implantación se derivan del derecho nacional desde su entrada en vigor.",
    "dashboard.65": "({p0}). Desde cuándo puede la autoridad nacional imponer multas lo determina la ley de transposición; este módulo no la conoce. Por eso el riesgo financiero no lleva fecha aquí, mientras que las obligaciones de implantación se derivan del derecho nacional desde su entrada en vigor.",
    "dashboard.83": "Actividad de comunicaciones electrónicas: los umbrales los fija el derecho nacional.",
    "dashboard.84": "El Reglamento (UE) 2024/2690 no se aplica a los proveedores de redes públicas y servicios de comunicaciones electrónicas. Para ellos, los umbrales del incidente significativo los fija el derecho nacional (artículo 23, apartado 11, de la Directiva); este módulo no los conoce, por lo que no indica cifras.",
    "dashboard.terminRejestracji": "El plazo para presentar los datos de registro lo fija el derecho nacional (artículo 3, apartado 4, de la Directiva). Los proveedores del artículo 27, apartado 1 —servicios de DNS, registros de nombres de dominio de primer nivel, servicios en nube, centros de datos, redes de distribución de contenidos, servicios gestionados y servicios de seguridad gestionados— presentan sus datos al registro de la ENISA: inicialmente antes del 17 de enero de 2025, y cada cambio sin demora indebida.",
    "html.1": "ITORO — Evaluación de cumplimiento de la Directiva NIS 2 (UE) 2022/2555",
    "html.10": "Evaluación de cumplimiento de la Directiva NIS 2 — módulo común",
    "html.100": "La lectura de estados financieros solo funciona en países con módulo de derecho nacional. Para este país, los <strong>ingresos</strong> del ejercicio los introduce usted manualmente; de ellos depende el importe de la multa.",
    "html.102": "La obtención automática de datos registrales solo funciona en países con módulo de derecho nacional. Las funciones y el tamaño de la empresa los indica usted manualmente.",
    "html.11": "La Directiva (UE) 2022/2555 (NIS 2) requiere transposición al derecho nacional. La evaluación abarca las obligaciones que se derivan directamente de la Directiva y el Reglamento de Ejecución (UE) 2024/2690 de la Comisión, de aplicación directa, en la medida en que afecten a la entidad.",
    "html.23": "los ingresos y el tamaño los introduce usted manualmente; el módulo común no consulta registros nacionales",
    "html.33": "Directiva (UE) 2022/2555 del Parlamento Europeo y del Consejo, de 14 de diciembre de 2022 (NIS 2)",
    "html.33a": "{p0} — acto nacional de transposición de la Directiva; este módulo todavía no evalúa sus requisitos",
    "html.33b": "el Estado aún no ha adoptado un acto de transposición — la evaluación sigue el Derecho de la Unión",
    "html.35": "obligaciones del órgano de dirección — artículo 20 de la Directiva",
    "html.36": "La herramienta sirve para la autoevaluación. No es una auditoría ni asesoramiento jurídico.",
    "html.40": "el módulo común no realiza ninguna conexión saliente: no consulta registros",
    "html.59": "Estados financieros",
    "html.60": "La lectura de estados financieros solo está disponible en países con módulo de derecho nacional. Para este país, los ingresos y la plantilla los introduce usted manualmente.",
    "html.62": "Búsqueda en registro",
    "html.63": "los registros mercantiles son nacionales; el módulo común no los conoce",
    "html.64": "las funciones y el tamaño de la empresa los indica usted manualmente",
    "html.66": "Número de identificación de la entidad",
    "html.68": "La obtención automática de datos registrales solo funciona en países con módulo de derecho nacional.",
    "html.76": "Ingresos anuales (EUR)",
    "html.78": "Ingresos de la actividad de comunicaciones electrónicas (EUR)",
    "html.79": "Este campo afecta a los proveedores de redes públicas o servicios de comunicaciones electrónicas. Los umbrales nacionales los fija el derecho del Estado miembro.",
    "html.80": "Retribución mensual del directivo (EUR)",
    "html.82": "Tipo de cambio",
    "html.83": "Los límites de las multas de la Directiva se expresan en euros. La conversión a la moneda nacional y el tipo los determina el derecho nacional; aquí los importes se indican en euros sin conversión.",
    "html.84": "El estatus resulta exclusivamente de la agregación de datos de empresas vinculadas, y el sistema de información de la entidad es independiente (considerando 16 de la Directiva; su aplicación la decide el derecho nacional)",
    "html.85": "La entidad ejerce actividades en los ámbitos de la seguridad nacional, la seguridad pública, la defensa o la aplicación de la ley (artículo 2, apartado 7, de la Directiva)",
    "html.91": "Evaluación de cumplimiento de la Directiva (UE) 2022/2555 del Parlamento Europeo y del Consejo (NIS 2) y del Reglamento de Ejecución (UE) 2024/2690 de la Comisión — módulo común para los países cuyo módulo de derecho nacional aún no está listo.",
    "html.94": "si la entidad es <strong>esencial</strong>, <strong>importante</strong> o queda fuera del ámbito de la Directiva",
    "html.daneZeSprawozdania": "nombre, número de identificación, domicilio social",
    "html.rejestrMozliwy": "El registro {p0} es público y gratuito: su lectura puede añadirse a la herramienta; aceptamos pull requests (véase el README).",
    "html.tytulNaglowka": "Evaluación de cumplimiento de la Directiva NIS 2",
    "html.zrodlaRecznie": "Este módulo no conoce los registros de su país: complete el perfil manualmente. El volumen de negocios anual determina la multa máxima, así que indíquelo con precisión.",
    "klasyfikacja.10": "artículo 3, apartado 1, letra c), de la Directiva (UE) 2022/2555 (proveedor de redes públicas de comunicaciones electrónicas o de servicios de comunicaciones electrónicas disponibles al público que sea al menos mediana empresa)",
    "klasyfikacja.11": "artículo 3, apartado 2, en relación con el artículo 2, apartado 2, letra a), inciso i), de la Directiva (UE) 2022/2555 (proveedor de redes públicas o servicios de comunicaciones electrónicas que sea microempresa o pequeña empresa)",
    "klasyfikacja.12": "artículo 3, apartado 1, letra a), de la Directiva (UE) 2022/2555 (proveedor de servicios de seguridad gestionados que supera los límites de la mediana empresa)",
    "klasyfikacja.13": "Las microempresas y pequeñas empresas no están comprendidas en la Directiva por esta función (artículo 2, apartado 1, a contrario).",
    "klasyfikacja.15": "artículo 3, apartado 1, letra b), de la Directiva (UE) 2022/2555 (prestador cualificado de servicios de confianza) — con independencia del tamaño de la empresa",
    "klasyfikacja.16": "artículo 3, apartado 2, en relación con el artículo 2, apartado 2, letra a), inciso ii), de la Directiva (UE) 2022/2555 (prestador no cualificado de servicios de confianza que sea microempresa, pequeña o mediana empresa)",
    "klasyfikacja.18": "artículo 3, apartado 2, de la Directiva (UE) 2022/2555 (entidad de la Administración pública a nivel regional, si así lo dispone el Estado miembro — artículo 2, apartado 2, letra f), inciso ii))",
    "klasyfikacja.19": "artículo 3, apartado 1, letra f), de la Directiva (UE) 2022/2555 (entidad de la Administración pública a nivel central — artículo 2, apartado 2, letra f), inciso i))",
    "klasyfikacja.2": "Supervisión ex ante y ex post (artículo 32 de la Directiva (UE) 2022/2555).",
    "klasyfikacja.20": "artículo 3, apartado 2, de la Directiva (UE) 2022/2555 (entidad de la Administración pública a nivel regional — artículo 2, apartado 2, letra f), inciso ii))",
    "klasyfikacja.21": "El alcance de las obligaciones de las entidades de la Administración pública a nivel local lo determina el derecho nacional (artículo 2, apartado 5, letra a), de la Directiva).",
    "klasyfikacja.22": "Un Estado miembro puede eximir a las entidades que ejercen actividades en los ámbitos de la seguridad nacional, la seguridad pública, la defensa o la aplicación de la ley (artículo 2, apartado 7, de la Directiva). La exención no opera por sí sola: verifique el resultado de la evaluación con el derecho nacional.",
    "klasyfikacja.23": "La entidad cumple los criterios tanto de entidad esencial como de entidad importante. Es una entidad esencial (artículo 3, apartado 1, de la Directiva), y los requisitos más exigentes se aplican a toda la actividad comprendida en la Directiva.",
    "klasyfikacja.25": "La entidad es esencial, por lo que le es aplicable el catálogo completo de medidas del artículo 21, apartado 2, de la Directiva y la supervisión ex ante y ex post; la evaluación abarca el conjunto completo de preguntas.",
    "klasyfikacja.26": "Como entidad importante, está sujeta al mismo catálogo de medidas del artículo 21, apartado 2, pero solo a supervisión ex post (artículo 33). El límite de la multa es menor: 7 millones EUR o el 1,4 % del volumen de negocios (artículo 34, apartado 5). El derecho nacional puede prever alivios para las entidades públicas; este módulo no los conoce.",
    "klasyfikacja.28": "Las obligaciones de las entidades de la Administración pública se derivan del artículo 2, apartado 2, letra f), de la Directiva; su alcance exacto, incluido el nivel local y los centros educativos, lo determina el derecho nacional (artículo 2, apartado 5).",
    "klasyfikacja.29": "Se ha declarado que el estatus de la entidad resulta exclusivamente de la agregación de datos de empresas vinculadas o asociadas y que el sistema de información de la entidad es independiente. La Directiva admite tal exclusión (considerando 16), pero la decide el derecho nacional; el módulo asume la exclusión, que debe verificarse con el derecho del Estado miembro y documentarse.",
    "klasyfikacja.4": "Supervisión únicamente ex post, cuando existan pruebas, indicios o información de una infracción (artículo 33 de la Directiva (UE) 2022/2555).",
    "klasyfikacja.5": "Fuera del ámbito de la Directiva",
    "klasyfikacja.6": "No hay obligaciones derivadas de la Directiva (UE) 2022/2555 para la función indicada.",
    "klasyfikacja.7": "artículo 3, apartado 1, letra a), de la Directiva (UE) 2022/2555 (entidad de un tipo del anexo I que supera los límites de la mediana empresa)",
    "klasyfikacja.8": "artículo 3, apartado 2, de la Directiva (UE) 2022/2555 (entidad de un tipo del anexo I que cumple los criterios de mediana empresa)",
    "klasyfikacja.9": "Las microempresas y pequeñas empresas no están comprendidas en la Directiva por esta función (artículo 2, apartado 1, a contrario).",
    "kreator.10": "Introduzca manualmente los ingresos del año anterior.",
    "kreator.35": "<span class=\"text-secondary\">La lectura de estados financieros no está disponible para este país.</span>",
    "kreator.37": "La lectura de estados financieros no está disponible para este país: introduzca los ingresos manualmente.",
    "kreator.56": "Sí: el Reglamento de la UE se aplica directamente desde el 7 de noviembre de 2024 en todos los Estados miembros y no tiene periodo transitorio. Su base es",
    "kreator.57": ", que facultó a la Comisión para establecer los requisitos técnicos y metodológicos para los proveedores del artículo 3, apartado 1, del Reglamento. El plazo de transposición de la Directiva venció el",
    "kreator.58": ", y desde cuándo puede la autoridad nacional imponer multas lo determina el derecho nacional. Los requisitos técnicos del anexo (secciones 6 y 9 a 13) son vinculantes en su redacción actual; no esperan a ninguna concreción. Solo puede apartarse de los requisitos con la fórmula «cuando proceda», y únicamente documentando la justificación.",
    "kreator.9": "Estados financieros →",
    "kreator.przepisReg2690": "el artículo 21, apartado 5, de la Directiva (UE) 2022/2555",
    "kreator.terminReg2690": "17 de octubre de 2024",
    "punktacja.10": "Entidades públicas",
    "punktacja.4": "Directiva NIS 2 — artículo 21",
    "punktacja.5": "Directiva NIS 2 — obligaciones formales",
    "punktacja.8": "Comunicaciones electrónicas",
    "punktacja.9": "Directiva NIS 2 — entidades públicas",
    "punktacja.skrotKsc": "NIS 2",
    "punktacja.skrotPke": "telecom",
    "ue.cyt.akapit": ", párrafo {p0}",
    "ue.cyt.art": "artículo {p0}",
    "ue.cyt.drugi": "segundo",
    "ue.cyt.dyr": "{p0}, de la Directiva (UE) 2022/2555",
    "ue.cyt.i": "y",
    "ue.cyt.laczenie": "",
    "ue.cyt.lit": ", letra {p0})",
    "ue.cyt.litery": "",
    "ue.cyt.pkt": ", punto {p0}",
    "ue.cyt.rozdzielacz": "; ",
    "ue.cyt.rozp": "{p0}, del Reglamento (UE) 2024/2690",
    "ue.cyt.ust": ", apartado {p0}",
    "ue.katalog.1": "Políticas de análisis de riesgos y seguridad de los sistemas de información",
    "ue.katalog.10": "Gestión de incidentes",
    "ue.katalog.11": "La gestión de incidentes comprende las acciones y procedimientos destinados a prevenir, detectar, analizar y contener un incidente, responder a él y recuperarse (artículo 6, punto 8).",
    "ue.katalog.12": "¿Existe un procedimiento documentado de gestión de incidentes que cubra la detección, el análisis, la contención, la respuesta y la recuperación?",
    "ue.katalog.13": "ISO/IEC 27001 A.5.24–A.5.26",
    "ue.katalog.14": "¿Permite el procedimiento cumplir los plazos de notificación de un incidente significativo: alerta temprana en 24 horas, notificación en 72 horas, informe final en un mes?",
    "ue.katalog.15": "ISO/IEC 27001 A.5.24",
    "ue.katalog.16": "¿Tiene la entidad criterios para considerar significativo un incidente, conformes con el artículo 23, apartado 3: perturbación operativa grave o pérdidas financieras, o daños considerables a otras personas?",
    "ue.katalog.17": "ISO/IEC 27001 A.5.25",
    "ue.katalog.18": "¿Se registran los incidentes y se utilizan las lecciones de su gestión para mejorar las medidas?",
    "ue.katalog.19": "ISO/IEC 27001 A.5.27",
    "ue.katalog.2": "Las medidas se basan en un planteamiento que tiene en cuenta todos los peligros (artículo 21, apartado 2). Su proporcionalidad se evalúa teniendo en cuenta el grado de exposición, el tamaño de la entidad, la probabilidad de incidentes y su gravedad (artículo 21, apartado 1, párrafo segundo).",
    "ue.katalog.20": "Continuidad de las actividades y gestión de crisis",
    "ue.katalog.21": "Continuidad de las actividades, como la gestión de copias de seguridad y la recuperación en caso de catástrofe, y gestión de crisis.",
    "ue.katalog.22": "¿Existe un plan de continuidad de las actividades que cubra la recuperación tras una catástrofe?",
    "ue.katalog.23": "ISO/IEC 27001 A.5.29–A.5.30",
    "ue.katalog.24": "¿Se realizan, protegen y prueban las copias de seguridad en cuanto a su capacidad de restauración?",
    "ue.katalog.25": "ISO/IEC 27001 A.8.13",
    "ue.katalog.26": "¿Dispone la entidad de procedimientos de gestión de crisis con funciones y canales de comunicación definidos?",
    "ue.katalog.27": "ISO/IEC 27001 A.5.29",
    "ue.katalog.28": "¿Se prueban periódicamente los planes de continuidad y recuperación y se documentan los resultados?",
    "ue.katalog.29": "ISO/IEC 27001 A.5.30",
    "ue.katalog.3": "¿Dispone la entidad de una política documentada de análisis de riesgos y seguridad de los sistemas de información, aprobada por el órgano de dirección?",
    "ue.katalog.30": "Seguridad de la cadena de suministro",
    "ue.katalog.31": "Seguridad de la cadena de suministro, incluidos los aspectos de seguridad de las relaciones entre la entidad y sus proveedores o prestadores de servicios directos. La entidad tiene en cuenta las vulnerabilidades específicas de cada proveedor y la calidad general de sus productos y prácticas de ciberseguridad (artículo 21, apartado 3).",
    "ue.katalog.32": "¿Mantiene la entidad una lista de proveedores y prestadores de servicios directos con una evaluación de su relevancia para la seguridad de las redes y sistemas?",
    "ue.katalog.33": "ISO/IEC 27001 A.5.19",
    "ue.katalog.34": "Al seleccionar medidas respecto a los proveedores, ¿se tienen en cuenta las vulnerabilidades específicas de cada uno y la calidad de sus prácticas de ciberseguridad y desarrollo seguro?",
    "ue.katalog.35": "ISO/IEC 27001 A.5.19, A.5.21",
    "ue.katalog.36": "¿Contienen los contratos con proveedores requisitos de seguridad y la obligación de informar de incidentes y vulnerabilidades?",
    "ue.katalog.37": "ISO/IEC 27001 A.5.20",
    "ue.katalog.38": "¿Tiene en cuenta la entidad los resultados de las evaluaciones coordinadas de riesgos de seguridad de las cadenas de suministro críticas a que se refiere el artículo 22?",
    "ue.katalog.39": "ISO/IEC 27001 A.5.21",
    "ue.katalog.4": "ISO/IEC 27001 puntos 5.2, 6.1.2",
    "ue.katalog.40": "Seguridad en la adquisición, el desarrollo y el mantenimiento de sistemas",
    "ue.katalog.41": "Seguridad en la adquisición, el desarrollo y el mantenimiento de redes y sistemas de información, incluidas la gestión y la divulgación de vulnerabilidades.",
    "ue.katalog.42": "¿Se definen los requisitos de seguridad antes de adquirir o empezar a desarrollar un sistema y se verifican antes de su puesta en producción?",
    "ue.katalog.43": "ISO/IEC 27001 A.8.25–A.8.29",
    "ue.katalog.44": "¿Existe un proceso de gestión de vulnerabilidades: identificación, evaluación, corrección en un plazo definido?",
    "ue.katalog.45": "ISO/IEC 27001 A.8.8",
    "ue.katalog.46": "¿Dispone la entidad de un procedimiento de divulgación de vulnerabilidades, incluido un canal para recibir avisos de terceros?",
    "ue.katalog.47": "¿Pasan los cambios en los sistemas por un proceso controlado de gestión de cambios con evaluación del impacto en la seguridad?",
    "ue.katalog.48": "ISO/IEC 27001 A.8.32",
    "ue.katalog.49": "Evaluación de la eficacia de las medidas",
    "ue.katalog.5": "¿Abarca el análisis de riesgos todos los peligros para las redes y sistemas de información y su entorno físico, y no solo las ciberamenazas?",
    "ue.katalog.50": "Políticas y procedimientos para evaluar la eficacia de las medidas de gestión de riesgos de ciberseguridad.",
    "ue.katalog.51": "¿Existe una política documentada de evaluación de la eficacia de las medidas que defina el alcance, la frecuencia y los métodos?",
    "ue.katalog.52": "ISO/IEC 27001 punto 9.1",
    "ue.katalog.53": "¿Se realizan las evaluaciones de eficacia periódicamente y se comunican sus resultados al órgano de dirección?",
    "ue.katalog.54": "ISO/IEC 27001 puntos 9.2–9.3",
    "ue.katalog.55": "¿Dan lugar las debilidades detectadas a acciones correctivas documentadas con responsable y plazo?",
    "ue.katalog.56": "ISO/IEC 27001 punto 10.1",
    "ue.katalog.57": "Ciberhigiene y formación",
    "ue.katalog.58": "Prácticas básicas de ciberhigiene y formación en ciberseguridad. Los miembros del órgano de dirección reciben formación periódica (artículo 20, apartado 2).",
    "ue.katalog.59": "¿Aplica la entidad prácticas básicas de ciberhigiene: actualizaciones, gestión de contraseñas, limitación de privilegios, protección contra programas maliciosos?",
    "ue.katalog.6": "ISO/IEC 27001 punto 6.1.2",
    "ue.katalog.60": "ISO/IEC 27001 A.8.7, A.8.8",
    "ue.katalog.61": "¿Recibe el personal formación en ciberseguridad adaptada a su función, con participación documentada?",
    "ue.katalog.62": "ISO/IEC 27001 A.6.3",
    "ue.katalog.63": "¿Reciben los miembros del órgano de dirección formación periódica que les permita identificar riesgos y evaluar las prácticas de gestión de riesgos?",
    "ue.katalog.64": "ISO/IEC 27001 punto 7.2",
    "ue.katalog.65": "Criptografía y cifrado",
    "ue.katalog.66": "Políticas y procedimientos relativos a la utilización de criptografía y, cuando proceda, cifrado.",
    "ue.katalog.67": "¿Existe una política de criptografía que defina qué datos y canales se cifran y con qué algoritmos?",
    "ue.katalog.68": "ISO/IEC 27001 A.8.24",
    "ue.katalog.69": "¿Se gestionan las claves criptográficas en todo su ciclo de vida: generación, distribución, almacenamiento, rotación, retirada?",
    "ue.katalog.7": "¿Tiene en cuenta la selección de medidas el estado de la técnica, las normas europeas e internacionales pertinentes y el coste de implantación?",
    "ue.katalog.70": "Recursos humanos, control de acceso y gestión de activos",
    "ue.katalog.71": "Seguridad de los recursos humanos, políticas de control de acceso y gestión de activos.",
    "ue.katalog.72": "¿Mantiene la entidad un inventario actualizado de activos con propietarios asignados y clasificación?",
    "ue.katalog.73": "ISO/IEC 27001 A.5.9, A.5.12",
    "ue.katalog.74": "¿Existe una política de control de acceso basada en el principio de mínimo privilegio, con revisión periódica de los permisos?",
    "ue.katalog.75": "ISO/IEC 27001 A.5.15, A.5.18",
    "ue.katalog.76": "¿Se aplican procedimientos de seguridad en la contratación, el cambio de puesto y la salida del personal, incluidas la retirada de permisos y la devolución de activos?",
    "ue.katalog.77": "ISO/IEC 27001 A.6.1–A.6.5",
    "ue.katalog.78": "¿Está el acceso privilegiado limitado, registrado y revisado?",
    "ue.katalog.79": "ISO/IEC 27001 A.8.2",
    "ue.katalog.8": "ISO/IEC 27001 punto 6.1.3",
    "ue.katalog.80": "Autenticación multifactor y comunicaciones seguras",
    "ue.katalog.81": "Cuando proceda: autenticación multifactor o continua, comunicaciones de voz, vídeo y texto seguras y sistemas seguros de comunicación de emergencia dentro de la entidad.",
    "ue.katalog.82": "¿Se utiliza autenticación multifactor o continua donde el análisis de riesgos lo justifica, en particular para el acceso remoto y las cuentas privilegiadas?",
    "ue.katalog.83": "ISO/IEC 27001 A.8.5",
    "ue.katalog.84": "¿Están protegidas las comunicaciones de voz, vídeo y texto utilizadas con fines profesionales?",
    "ue.katalog.85": "ISO/IEC 27001 A.8.20",
    "ue.katalog.86": "¿Dispone la entidad de un sistema seguro de comunicación interna de emergencia, independiente de la infraestructura principal?",
    "ue.katalog.9": "¿Está documentado que el nivel de seguridad es adecuado al riesgo existente, con una justificación que tenga en cuenta el tamaño de la entidad y el impacto social y económico de los incidentes?",
    "ue.kierownictwo.1": "El órgano de dirección de una entidad esencial o importante; en una sociedad de capital, el consejo de administración. La Directiva no define el concepto; su alcance en cada país resulta del derecho nacional.",
    "ue.kierownictwo.10": "Determinar el estatus de la entidad y velar por el registro",
    "ue.kierownictwo.11": "Determinar si la entidad es esencial o importante y presentar los datos de registro a la autoridad competente. El procedimiento y el plazo los fija el derecho nacional.",
    "ue.kierownictwo.12": "Implantar el análisis de riesgos y la política de seguridad",
    "ue.kierownictwo.13": "Medidas basadas en un planteamiento que tiene en cuenta todos los peligros, proporcionadas a la exposición, al tamaño de la entidad y a la gravedad de los incidentes.",
    "ue.kierownictwo.14": "Poner en marcha la gestión y notificación de incidentes",
    "ue.kierownictwo.15": "Procedimiento de gestión de incidentes y capacidad para cumplir los plazos de 24 horas, 72 horas y un mes.",
    "ue.kierownictwo.16": "24 h / 72 h / un mes desde la detección",
    "ue.kierownictwo.17": "Garantizar la continuidad de las actividades",
    "ue.kierownictwo.18": "Plan de continuidad, copias de seguridad, recuperación tras catástrofe, gestión de crisis.",
    "ue.kierownictwo.19": "Poner en orden la cadena de suministro",
    "ue.kierownictwo.2": "La responsabilidad del órgano de dirección se entiende sin perjuicio de las normas nacionales sobre la responsabilidad de las instituciones públicas y los funcionarios (artículo 20, apartado 1, párrafo segundo).",
    "ue.kierownictwo.20": "Lista de proveedores, evaluación de sus vulnerabilidades y prácticas, requisitos de seguridad en los contratos.",
    "ue.kierownictwo.21": "Implantar el control de acceso y la gestión de activos",
    "ue.kierownictwo.22": "Inventario de activos, principio de mínimo privilegio, revisiones de permisos, autenticación multifactor donde el riesgo lo justifique.",
    "ue.kierownictwo.23": "Medir la eficacia de las medidas",
    "ue.kierownictwo.24": "Política y procedimientos de evaluación de la eficacia, revisiones periódicas, acciones correctivas.",
    "ue.kierownictwo.25": "Aprobar",
    "ue.kierownictwo.26": "las medidas de gestión de riesgos de ciberseguridad (artículo 20, apartado 1)",
    "ue.kierownictwo.27": "la política de análisis de riesgos y seguridad de los sistemas",
    "ue.kierownictwo.28": "el presupuesto y las funciones en la implantación",
    "ue.kierownictwo.29": "Supervisar",
    "ue.kierownictwo.3": "Si encomendar las obligaciones a otra persona excluye la responsabilidad lo decide el derecho nacional. En Polonia no la excluye (artículo 8c, apartado 3, de la Ley del sistema nacional de ciberseguridad).",
    "ue.kierownictwo.30": "la implantación de las medidas aprobadas (artículo 20, apartado 1)",
    "ue.kierownictwo.31": "los resultados de la evaluación de la eficacia (artículo 21, apartado 2, letra f))",
    "ue.kierownictwo.32": "el cumplimiento de los plazos de notificación de incidentes (artículo 23)",
    "ue.kierownictwo.33": "Documentar",
    "ue.kierownictwo.34": "las decisiones de aprobación y las revisiones",
    "ue.kierownictwo.35": "la participación en la formación (artículo 20, apartado 2)",
    "ue.kierownictwo.36": "Miembro del órgano de dirección",
    "ue.kierownictwo.37": "aprobación de medidas, supervisión, decisiones, presupuesto",
    "ue.kierownictwo.38": "Jefe de proyecto",
    "ue.kierownictwo.39": "coordinación de la implantación, calendario, estado y evidencias",
    "ue.kierownictwo.4": "Aprobar las medidas de gestión de riesgos de ciberseguridad",
    "ue.kierownictwo.40": "TI / ciberseguridad",
    "ue.kierownictwo.41": "análisis de riesgos, medidas técnicas, gestión de incidentes",
    "ue.kierownictwo.42": "Departamento jurídico / cumplimiento",
    "ue.kierownictwo.5": "El órgano de dirección aprueba las medidas adoptadas para cumplir el artículo 21. Es una decisión del órgano, no del departamento de TI; sin ella, las medidas carecen de respaldo.",
    "ue.kierownictwo.6": "Supervisar la implantación de las medidas",
    "ue.kierownictwo.7": "La supervisión de la implantación es obligación del órgano de dirección. La ejecución puede encomendarse; la supervisión, no.",
    "ue.kierownictwo.8": "Recibir formación periódica",
    "ue.kierownictwo.9": "Los miembros del órgano de dirección reciben formación periódica para adquirir conocimientos que les permitan identificar riesgos y evaluar las prácticas de gestión de riesgos y su repercusión en los servicios de la entidad.",
    "ue.kierownictwo.daneRejestracyjne": "los datos de registro y sus actualizaciones (artículo 3, apartados 4 y 5)",
    "ue.meta.1": "Prevalece la variante porcentual: el {p0} % del volumen de negocios es mayor que {p1} millones EUR.",
    "ue.meta.10": "La Directiva no impone obligaciones directamente a las empresas: lo hace la ley nacional, que el Estado miembro debía aprobar antes del 17 de octubre de 2024. Este módulo muestra los requisitos en los términos de la Directiva, porque el módulo de derecho nacional del país seleccionado aún no está listo o el país no ha transpuesto la Directiva.",
    "ue.meta.11": "Obligaciones derivadas de la Directiva",
    "ue.meta.12": "Lista de entidades — antes del 17 de abril de 2025",
    "ue.meta.13": "Los Estados miembros debían establecer una lista de entidades esenciales e importantes antes del 17 de abril de 2025 y exigir a las entidades que presentaran sus datos de registro.",
    "ue.meta.14": "Reglamento (UE) 2024/2690",
    "ue.meta.15": "De aplicación directa desde el 7 de noviembre de 2024",
    "ue.meta.16": "El Reglamento de Ejecución se aplica directamente en todos los Estados miembros, con independencia del estado de transposición de la Directiva. Afecta a las entidades enumeradas en su artículo 1: DNS, TLD, nube, centros de datos, redes de distribución de contenidos, servicios gestionados y servicios de confianza.",
    "ue.meta.17": "artículo 16 del Reglamento (UE) 2024/2690",
    "ue.meta.18": "Al menos 10 000 000 EUR o al menos el 2 % del volumen de negocios anual total a escala mundial de la empresa en el ejercicio anterior, la cifra que sea mayor. Es un límite mínimo: el derecho nacional puede elevarlo.",
    "ue.meta.19": "Al menos 7 000 000 EUR o el 1,4 % del volumen de negocios anual total a escala mundial, la cifra que sea mayor. Límite mínimo.",
    "ue.meta.2": "Prevalece la cuantía fija: {p0} millones EUR es mayor que el {p1} % del volumen de negocios.",
    "ue.meta.20": "La Directiva no prevé una multa distinta por infracción cualificada; es una construcción del derecho nacional de algunos países.",
    "ue.meta.21": "Los Estados miembros pueden prever multas coercitivas para obligar a poner fin a una infracción. El importe lo fija el derecho nacional.",
    "ue.meta.22": "El órgano de dirección aprueba las medidas de gestión de riesgos, supervisa su implantación y puede ser considerado responsable de las infracciones del artículo 21. Las normas y el alcance de esa responsabilidad los determina el derecho nacional.",
    "ue.meta.23": "El órgano de dirección aprueba las medidas de gestión de riesgos de ciberseguridad (artículo 20, apartado 1).",
    "ue.meta.24": "El órgano de dirección supervisa la implantación de esas medidas (artículo 20, apartado 1).",
    "ue.meta.25": "Los miembros del órgano de dirección reciben formación periódica (artículo 20, apartado 2).",
    "ue.meta.26": "Respecto de una entidad esencial, la autoridad puede solicitar la prohibición temporal de ejercer funciones directivas (artículo 32, apartado 5, letra b)).",
    "ue.meta.27": "El límite mínimo lo fija la Directiva",
    "ue.meta.28": "Se comparan dos valores: una cuantía fija en euros y un porcentaje del volumen de negocios anual total a escala mundial de la empresa en el ejercicio anterior. El mayor es el límite superior que el Estado miembro debe prever como mínimo. El derecho nacional puede elevarlo.",
    "ue.meta.29": "El importe dentro del límite lo fija la autoridad nacional",
    "ue.meta.3": "El límite de la Directiva supera {p0} veces el volumen de negocios anual de la entidad. El artículo 34, apartado 1, exige que la multa sea proporcionada a las circunstancias de cada caso: es un límite superior, no una multa esperada.",
    "ue.meta.30": "La multa debe ser efectiva, proporcionada y disuasoria según las circunstancias de cada caso. La autoridad tiene en cuenta al menos los criterios del artículo 32, apartado 7: gravedad y duración de la infracción, infracciones anteriores, daños, intencionalidad, medidas correctoras y cooperación.",
    "ue.meta.31": "El límite puede superar varias veces el volumen de negocios anual: es un límite superior, no un importe esperado. Los mínimos nacionales, las multas coercitivas y el procedimiento de graduación los determina la ley del Estado miembro.",
    "ue.meta.32": "Al decidir si se impone una multa administrativa y su importe, se tienen debidamente en cuenta en cada caso, como mínimo, los elementos enumerados en el artículo 32, apartado 7.",
    "ue.meta.33": "la gravedad de la infracción y la importancia de las disposiciones infringidas; se consideran graves en todo caso: las infracciones reiteradas, la falta de notificación o corrección de incidentes significativos, la falta de subsanación de deficiencias contra instrucciones vinculantes, la obstrucción de auditorías o del seguimiento, y el suministro de información falsa o manifiestamente inexacta",
    "ue.meta.34": "cualquier infracción anterior pertinente cometida por la entidad",
    "ue.meta.35": "los daños materiales o inmateriales causados, incluidas las pérdidas financieras, la repercusión en otros servicios y el número de usuarios afectados",
    "ue.meta.36": "el carácter intencionado o negligente de la infracción",
    "ue.meta.37": "las medidas adoptadas para prevenir o mitigar los daños",
    "ue.meta.38": "la adhesión a códigos de conducta aprobados o a mecanismos de certificación",
    "ue.meta.39": "el grado de cooperación con las autoridades competentes",
    "ue.meta.4": "Directiva (UE) 2022/2555 del Parlamento Europeo y del Consejo (NIS 2)",
    "ue.meta.40": "La Directiva no prevé expresamente la renuncia a la multa; si es posible y cuándo lo decide el derecho nacional.",
    "ue.meta.41": "Desde esta fecha los Estados miembros deben aplicar las disposiciones nacionales de transposición de la Directiva. La fecha concreta desde la que la autoridad puede imponer una multa resulta del derecho nacional.",
    "ue.meta.42": "Entrada en vigor de la Directiva NIS 2",
    "ue.meta.43": "A los veinte días de su publicación en el Diario Oficial.",
    "ue.meta.44": "Plazo de transposición de la Directiva",
    "ue.meta.45": "Antes de esta fecha los Estados miembros debían adoptar y publicar las disposiciones nacionales.",
    "ue.meta.46": "Aplicación de las disposiciones nacionales y derogación de NIS 1",
    "ue.meta.47": "Desde esta fecha los Estados aplican las disposiciones de transposición; la Directiva (UE) 2016/1148 queda derogada.",
    "ue.meta.48": "Aplicación del Reglamento (UE) 2024/2690",
    "ue.meta.49": "El Reglamento de Ejecución se aplica directamente a partir de los veinte días de su publicación.",
    "ue.meta.5": "DO UE L 333 de 27.12.2022",
    "ue.meta.50": "Lista de entidades esenciales e importantes",
    "ue.meta.51": "Antes de esta fecha los Estados miembros establecen la lista; las entidades presentan sus datos de registro a las autoridades.",
    "ue.meta.52": "Primera revisión de la Directiva por la Comisión",
    "ue.meta.53": "La Comisión revisa el funcionamiento de la Directiva y presenta un informe.",
    "ue.meta.54": "Alerta temprana de un incidente significativo",
    "ue.meta.55": "24 horas desde que se tiene conocimiento",
    "ue.meta.56": "Notificación de un incidente significativo",
    "ue.meta.57": "72 horas desde que se tiene conocimiento",
    "ue.meta.58": "Informe final",
    "ue.meta.59": "un mes desde la notificación del incidente",
    "ue.meta.6": "Reglamento de Ejecución (UE) 2024/2690 de la Comisión",
    "ue.meta.60": "Notificación de incidente por un prestador de servicios de confianza",
    "ue.meta.61": "artículo 21, apartado 5, de la Directiva (UE) 2022/2555; artículos 1 y 2 del Reglamento (UE) 2024/2690",
    "ue.meta.62": "Sin datos de volumen de negocios, el límite es la cuantía fija de la Directiva.",
    "ue.meta.63": "Los límites del artículo 34, apartados 4 y 5, son mínimos («al menos»): el derecho nacional puede prever otros mayores. Importes en euros, sin conversión a la moneda nacional.",
    "ue.meta.64": "Autoridad competente del Estado miembro",
    "ue.meta.65": "El órgano de dirección puede ser considerado responsable de las infracciones del artículo 21. El alcance y el procedimiento los determina el derecho nacional; este módulo no los conoce.",
    "ue.meta.66": "El alcance de la responsabilidad personal de la dirección resulta de la ley nacional. En Polonia llega hasta el 300 % de la retribución (artículo 73a, apartado 4, de la Ley del sistema nacional de ciberseguridad); otros países lo regulan de otro modo.",
    "ue.meta.7": "DO UE L, 2024/2690",
    "ue.meta.8": "Directiva (UE) 2022/2555",
    "ue.meta.9": "El plazo de transposición venció el 17 de octubre de 2024",
    "ue.moduly.1": "unos {p0} min",
    "ue.moduly.10": "Diez áreas del artículo 21, apartado 2, letras a) a j): desde la política de riesgos hasta la autenticación multifactor. La infracción está sancionada con multa conforme al artículo 34. Evaluación en la escala de madurez.",
    "ue.moduly.11": "Reglamento 2024/2690 — gobernanza y procesos",
    "ue.moduly.12": "Secciones 1 a 5 y 7 a 8 del anexo: políticas, gestión de riesgos, gestión de incidentes, continuidad de las actividades, cadena de suministro, evaluación de la eficacia, ciberhigiene. De aplicación directa desde el 7 de noviembre de 2024.",
    "ue.moduly.13": "Reglamento 2024/2690 — requisitos técnicos",
    "ue.moduly.14": "Secciones 6 y 9 a 13 del anexo: adquisición y desarrollo de sistemas, criptografía, seguridad de los recursos humanos, control de acceso, gestión de activos, seguridad física y del entorno.",
    "ue.moduly.2": "unas {p0} h {p1} min",
    "ue.moduly.3": "unas {p0} h",
    "ue.moduly.4": "menos de un minuto",
    "ue.moduly.5": "Evaluación rápida de riesgos",
    "ue.moduly.6": "Preguntas transversales de todas las áreas de la Directiva. Cada una resuelve un grupo completo de cuestiones. Permite estimar la magnitud del retraso sin recorrer todo el cuestionario.",
    "ue.moduly.7": "Obligaciones derivadas de la Directiva",
    "ue.moduly.8": "Datos de registro, notificación de incidentes en 24 y 72 horas, obligaciones del órgano de dirección, preparación para la supervisión. Comprobable con documentos, sin análisis técnico.",
    "ue.moduly.9": "Medidas de gestión de riesgos — artículo 21, apartado 2",
    "ue.obowiazki.1": "Datos de registro para la lista de entidades",
    "ue.obowiazki.10": "Notificación de incidentes significativos",
    "ue.obowiazki.11": "La entidad notifica los incidentes significativos al CSIRT o a la autoridad competente en tres pasos: alerta temprana, notificación, informe final. Los plazos corren desde que se tiene conocimiento del incidente.",
    "ue.obowiazki.12": "¿Es capaz la entidad de presentar una alerta temprana en las 24 horas siguientes a tener conocimiento de un incidente significativo, indicando si se sospecha que el incidente se debe a actos ilícitos y si puede tener repercusión transfronteriza?",
    "ue.obowiazki.13": "24 horas desde que se tiene conocimiento",
    "ue.obowiazki.14": "¿Es capaz la entidad de presentar una notificación del incidente en 72 horas, con una evaluación inicial de la gravedad y el impacto e indicadores de compromiso?",
    "ue.obowiazki.15": "72 horas desde que se tiene conocimiento",
    "ue.obowiazki.16": "¿Presenta la entidad un informe final a más tardar un mes después de la notificación, con descripción del incidente, tipo de amenaza, medidas de mitigación y repercusión transfronteriza?",
    "ue.obowiazki.17": "un mes desde la notificación",
    "ue.obowiazki.18": "¿Informa la entidad a los destinatarios de sus servicios de los incidentes significativos que puedan afectar negativamente a la prestación de esos servicios?",
    "ue.obowiazki.19": "¿Informa la entidad a los destinatarios de sus servicios de una ciberamenaza significativa y de las medidas que pueden adoptar?",
    "ue.obowiazki.2": "Los Estados miembros establecen una lista de entidades esenciales e importantes y exigen a las entidades que presenten sus datos de registro. El procedimiento, el plazo y el portal los fija el derecho nacional.",
    "ue.obowiazki.20": "Si la entidad es prestador de servicios de confianza, ¿notifica los incidentes significativos en las 24 horas siguientes a tener conocimiento?",
    "ue.obowiazki.21": "afecta a los prestadores de servicios de confianza",
    "ue.obowiazki.22": "Órgano de dirección",
    "ue.obowiazki.23": "El órgano de dirección aprueba las medidas de gestión de riesgos, supervisa su implantación y puede ser considerado responsable. Los miembros del órgano reciben formación periódica.",
    "ue.obowiazki.24": "¿Ha aprobado formalmente el órgano de dirección las medidas de gestión de riesgos de ciberseguridad adoptadas para cumplir el artículo 21?",
    "ue.obowiazki.25": "¿Supervisa el órgano de dirección la implantación de esas medidas de forma documentada, por ejemplo mediante informes y revisiones periódicos?",
    "ue.obowiazki.26": "¿Reciben los miembros del órgano de dirección formación periódica que les permita identificar riesgos y evaluar las prácticas de gestión de riesgos, con participación documentada?",
    "ue.obowiazki.27": "Preparación para las actuaciones de supervisión",
    "ue.obowiazki.28": "Una entidad esencial está sujeta a supervisión ex ante y ex post; una entidad importante, solo ex post. La autoridad puede requerir información, pruebas de la implantación de las políticas y resultados de auditorías.",
    "ue.obowiazki.29": "¿Es capaz la entidad, a requerimiento de la autoridad, de presentar pruebas de la implantación de sus políticas de ciberseguridad, incluidos los resultados de auditorías de seguridad?",
    "ue.obowiazki.3": "¿Ha determinado la entidad si es esencial o importante, según el sector del anexo I o II y el tamaño de la empresa?",
    "ue.obowiazki.30": "¿Es capaz la entidad, a requerimiento de la autoridad, de facilitar los datos, documentos e información necesarios para el ejercicio de las funciones de supervisión?",
    "ue.obowiazki.31": "¿Está la entidad esencial preparada para una auditoría de seguridad realizada por la autoridad o por un organismo independiente, a su propia costa?",
    "ue.obowiazki.4": "¿Ha presentado la entidad a la autoridad competente sus datos de registro: nombre, dirección y datos de contacto, sector y subsector, lista de los Estados miembros en los que presta servicios?",
    "ue.obowiazki.5": "Los datos de contacto incluyen direcciones de correo electrónico, rangos de direcciones IP y números de teléfono. El plazo nacional y el portal de registro los fija el derecho del Estado miembro.",
    "ue.obowiazki.6": "¿Existe un proceso para actualizar los datos de registro sin demora indebida tras su modificación?",
    "ue.obowiazki.7": "La Directiva exige la actualización sin demora indebida; un plazo concreto —por ejemplo, 14 días en Polonia— resulta del derecho nacional.",
    "ue.obowiazki.8": "Si la entidad es proveedor de servicios de DNS, registro de TLD, proveedor de nube, centro de datos, CDN, servicios gestionados, mercado en línea, motor de búsqueda o red social, ¿ha presentado los datos adicionales del artículo 27, incluida la dirección de su establecimiento principal en la Unión?",
    "ue.obowiazki.9": "afecta a las entidades del artículo 26, apartado 1",
    "ue.role.1": "Autoridad competente del Estado miembro",
    "ue.role.10": "Servicios de centro de datos: colocación, alojamiento de infraestructura y servicios asociados.",
    "ue.role.11": "Centros de datos",
    "ue.role.12": "Entidad esencial por encima del umbral de mediana empresa (artículo 3, apartado 1, letra a)); importante si es mediana (artículo 3, apartado 2). Por debajo de mediana, fuera del ámbito, salvo que el Estado miembro designe a la entidad conforme al artículo 2, apartado 2, letras b) a e). Comprendido en el Reglamento 2024/2690.",
    "ue.role.13": "Proveedor de punto de intercambio de internet",
    "ue.role.14": "Infraestructura que permite el intercambio de tráfico entre redes independientes.",
    "ue.role.15": "Puntos de intercambio de internet",
    "ue.role.16": "Clasificación por tamaño (artículo 3, apartado 1, letra a), y apartado 2). El Reglamento 2024/2690 no comprende los puntos de intercambio de internet: el artículo 1 del Reglamento contiene una lista cerrada de destinatarios.",
    "ue.role.17": "Proveedor de servicios de DNS",
    "ue.role.18": "Servicios de resolución de nombres de dominio, excluidos los operadores de servidores raíz.",
    "ue.role.19": "Sistema de nombres de dominio",
    "ue.role.2": "autoridad competente",
    "ue.role.20": "Entidad esencial con independencia del tamaño (artículo 3, apartado 1, letra b)). Comprendido en el Reglamento 2024/2690.",
    "ue.role.21": "Registro de nombres de dominio de primer nivel",
    "ue.role.22": "Gestión de un registro de dominio de primer nivel.",
    "ue.role.23": "Entidad esencial con independencia del tamaño (artículo 3, apartado 1, letra b)). Además, obligaciones sobre datos de registro del artículo 28. Comprendido en el Reglamento 2024/2690.",
    "ue.role.24": "Proveedor de servicios de computación en nube",
    "ue.role.25": "Servicios de computación en nube: infraestructura, plataforma, software como servicio.",
    "ue.role.26": "Servicios de computación en nube",
    "ue.role.27": "Clasificación por tamaño (artículo 3, apartado 1, letra a), y apartado 2). Comprendido en el Reglamento 2024/2690.",
    "ue.role.28": "Proveedor de red de distribución de contenidos",
    "ue.role.29": "Red de servidores distribuidos que entrega contenidos y servicios a los usuarios finales.",
    "ue.role.3": "designada por el derecho nacional; hasta que se implante el módulo nacional, la herramienta no indica ninguna institución concreta",
    "ue.role.30": "Redes de distribución de contenidos",
    "ue.role.31": "Prestador de servicios de confianza",
    "ue.role.32": "Servicios de confianza en el sentido del Reglamento (UE) n.º 910/2014: firmas, sellos, sellos de tiempo, certificados.",
    "ue.role.33": "Servicios de confianza",
    "ue.role.34": "Comprendido en la Directiva con independencia del tamaño (artículo 2, apartado 2, letra a), inciso ii)). El prestador cualificado es entidad esencial con independencia del tamaño (artículo 3, apartado 1, letra b)); el no cualificado es esencial por encima del umbral de mediana empresa e importante en los demás casos. Comprendido en el Reglamento 2024/2690.",
    "ue.role.35": "Proveedor de servicios gestionados",
    "ue.role.36": "Gestión de la infraestructura TIC del cliente: instalación, mantenimiento, soporte, administración de sistemas.",
    "ue.role.37": "Gestión de servicios TIC (B2B)",
    "ue.role.38": "Servicios gestionados",
    "ue.role.39": "Proveedor de servicios de seguridad gestionados",
    "ue.role.4": "Proveedor de redes públicas de comunicaciones electrónicas o de servicios de comunicaciones electrónicas disponibles al público",
    "ue.role.40": "Servicios gestionados en el ámbito de la ciberseguridad: monitorización, respuesta a incidentes, pruebas, consultoría.",
    "ue.role.41": "Servicios de seguridad gestionados",
    "ue.role.42": "La Directiva clasifica por tamaño (artículo 3, apartado 1, letra a), y apartado 2). Los Estados miembros pueden endurecer el umbral: Polonia considera al MSSP entidad esencial ya desde pequeña empresa; este módulo aplica solo la regla de la Directiva. Comprendido en el Reglamento 2024/2690.",
    "ue.role.5": "Suministro de redes públicas de comunicaciones electrónicas o prestación de servicios de comunicaciones electrónicas disponibles al público, incluido el acceso a internet.",
    "ue.role.6": "Infraestructura digital",
    "ue.role.7": "Comunicaciones electrónicas",
    "ue.role.8": "Comprendido en la Directiva con independencia del tamaño (artículo 2, apartado 2, letra a), inciso i)). La mediana empresa o mayor es entidad esencial (artículo 3, apartado 1, letra c)); la microempresa o pequeña, importante (artículo 3, apartado 2). La ley nacional de telecomunicaciones puede imponer obligaciones adicionales; este módulo no las contiene.",
    "ue.role.9": "Proveedor de servicios de centro de datos",
    "ue.role.podstawaArt3b": "artículo 3, apartado 1, letra b), de la Directiva (UE) 2022/2555",
    "ue.zaslepki.1": "Directiva (UE) 2022/2555 del Parlamento Europeo y del Consejo (NIS 2)",
    "ue.zaslepki.10": "Si algunas entidades se inscriben de oficio lo decide el derecho nacional.",
    "ue.zaslepki.11": "Determine si está comprendido en la Directiva",
    "ue.zaslepki.12": "Sector del anexo I o II y tamaño de la empresa. Esta parte la realiza el perfil de la entidad en esta herramienta.",
    "ue.zaslepki.13": "Identifique la autoridad competente de su país",
    "ue.zaslepki.14": "Cada Estado designa una autoridad competente (artículo 8, apartado 1). La ENISA y la Comisión mantienen la lista actualizada.",
    "ue.zaslepki.15": "Presente los datos de registro",
    "ue.zaslepki.16": "Nombre, dirección y datos de contacto, sector y subsector, Estados en los que presta servicios (artículo 3, apartado 4). Procedimiento según el derecho nacional.",
    "ue.zaslepki.17": "Actualice los datos sin demora indebida",
    "ue.zaslepki.18": "Cualquier cambio en los datos de registro exige una actualización (artículo 3, apartado 5).",
    "ue.zaslepki.19": "dirección y datos de contacto actualizados: direcciones de correo electrónico, rangos de direcciones IP, números de teléfono",
    "ue.zaslepki.2": "DO UE L 333 de 27.12.2022, p. 80",
    "ue.zaslepki.20": "sector y subsector del anexo I o II",
    "ue.zaslepki.21": "lista de los Estados miembros en los que la entidad presta servicios",
    "ue.zaslepki.22": "Lo determina el derecho nacional.",
    "ue.zaslepki.23": "Directiva (UE) 2022/2555 — artículo 3",
    "ue.zaslepki.24": "ENISA — autoridades competentes de los Estados miembros",
    "ue.zaslepki.25": "Directiva (UE) 2022/2555",
    "ue.zaslepki.26": "El módulo de la UE no contiene directrices de una autoridad nacional; llegarán con el módulo de derecho nacional.",
    "ue.zaslepki.27": "La obtención automática de datos registrales solo funciona en países con módulo de derecho nacional. Rellene el perfil manualmente.",
    "ue.zaslepki.28": "La lectura de estados financieros solo funciona en países con módulo de derecho nacional. Introduzca los ingresos y la plantilla manualmente.",
    "ue.zaslepki.3": "Reglamento de Ejecución (UE) 2024/2690 de la Comisión",
    "ue.zaslepki.4": "DO UE L, 2024/2690, 18.11.2024",
    "ue.zaslepki.5": "La Directiva NIS 2 no contiene una capa separada de comunicaciones electrónicas. El derecho nacional de comunicaciones electrónicas puede imponer obligaciones adicionales; este módulo no las conoce.",
    "ue.zaslepki.6": "Lista de entidades esenciales e importantes",
    "ue.zaslepki.7": "Autoridad competente del Estado miembro.",
    "ue.zaslepki.8": "La Directiva obliga a los Estados miembros a llevar una lista de entidades esenciales e importantes y a exigir a las entidades que presenten sus datos de registro. El portal, el procedimiento y el plazo los fija el derecho nacional; este módulo no los conoce, porque el módulo de derecho nacional del país seleccionado aún no está listo.",
    "ue.zaslepki.9": "Todas las entidades esenciales e importantes. El plazo lo fija el derecho nacional.",
    "ue.zaslepki.skrotDyrektywy": "Directiva NIS 2",
    "ue.zaslepki.skrotReg2690": "Regl. 2024/2690",
    "xlsx.1": "{p0} – {p1} EUR",
    "xlsx.25": "Tipo de cambio",
    "xlsx.4": "INFORME DE CUMPLIMIENTO DE LA DIRECTIVA NIS 2 (UE) 2022/2555",
    "xlsx.58": "Actividad de comunicaciones electrónicas: el Reglamento (UE) 2024/2690 no se aplica. Los umbrales los fija el derecho nacional (artículo 23, apartado 11, de la Directiva); el módulo común no los conoce.",
    "xlsx.68": "La herramienta sirve para la autoevaluación. No es una auditoría ni asesoramiento jurídico.",
    "xlsx.69": "Para las entidades no comprendidas en el Reglamento (UE) 2024/2690, los umbrales del incidente significativo los fija el derecho nacional (artículo 23, apartado 11, de la Directiva).",
    "xlsx.70": "Las funciones indicadas en el perfil son una declaración. El estatus lo determina la actividad realmente ejercida (artículo 3 de la Directiva (UE) 2022/2555).",
    "xlsx.etykietaKrs": "Número registral",
    "xlsx.etykietaNip": "Número de identificación",
    "xlsx.etykietaRegon": "Número estadístico"
});
