/* Teksty modułu ue — język: et.
   Te same klucze co w napisy/pl.js (wersja źródłowa); wstawki {p0}, {p1}…
   pozostają bez zmian. Klucze ue.cyt.* to wzorce składania odesłań
   do przepisów w tym języku — patrz kraje/ue/cytaty.js. */
KRAJE.napisy('ue', 'et', {
    "app.10": "Kontrollige allolevat rollide loetelu — staatuse määrab tegelikult teostatav tegevus (direktiivi (EL) 2022/2555 artikkel 3), mitte registrikanne.",
    "app.14": "Eelmine aasta: {p0} EUR",
    "app.15": "Aruandeperioodi tulu: {p0} EUR",
    "app.19": "Päring registritesse numbri {p0} järgi…",
    "app.34": " mld EUR",
    "app.35": " mln EUR",
    "app.36": " tuh EUR",
    "app.37": "",
    "app.4": "Registriandmete automaatne hankimine pole selle riigi puhul saadaval — täitke profiil käsitsi.",
    "app.59": "NIS 2 direktiivile vastavuse hindamine (JSON)",
    "app.68": "Selle riigi puhul pole registrit, kust tööriist saaks andmeid hankida — profiil täidetakse käsitsi.",
    "app.69": "Selle riigi puhul pole registrit, kust tööriist saaks andmeid hankida. Klõpsake võrguühenduseta režiimi sisselülitamiseks.",
    "app.73": " · kasumiaruanne skeemis ",
    "app.74": "<div class=\"mt-2 tekst-uwaga\">Registriandmed ei näita ühtegi digitaristu sektori rolli. Valige rollid allpool käsitsi.</div>",
    "app.8": "Kanne elektroonilise side teenuse osutajate registris kinnitatud",
    "app.progDostawcy": "",
    "app.przyklad.adres": "Näidise tn 1, 10000 Linn",
    "app.przyklad.forma": "Osaühing",
    "app.przyklad.nazwa": "Näidisoperaator OÜ",
    "app.statusVat": " · KMKR staatus: ",
    "dashboard.1": "Deklareeritud rollide ja suuruse põhjal ei ole üksus ei elutähtis ega oluline üksus direktiivi (EL) 2022/2555 artikli 3 tähenduses. Kontrollige profiili, kui tulemus erineb oodatust.",
    "dashboard.113": "Korduma kippuvad küsimused",
    "dashboard.12": "— {p0}; riigisisesesse õigusesse ülevõtmise tähtaeg möödus {p2}",
    "dashboard.123": "NIS 2 direktiiv",
    "dashboard.30": "Elutähtsate ja oluliste üksuste loetelu",
    "dashboard.4": "— otsekohalduv alates {p0} kõigis liikmesriikides, ilma ülevõtmiseta",
    "dashboard.42": "Kindlasummaline variant: {p0}",
    "dashboard.45": "Direktiivi artikli 32 lõike 7 kriteeriumid:",
    "dashboard.46": "Kokku",
    "dashboard.49": "Üksus tegeleb elektroonilise sidega — juhtiva isiku vastutuse määrab riigisisene õigus",
    "dashboard.50": "",
    "dashboard.51": "",
    "dashboard.53": "Perioodiline trahv otsuse täitmisega viivitamise eest: {p0} EUR kuni {p1} EUR päevas ({p2})",
    "dashboard.54": "Kvalifitseeritud juhtum: kuni {p0} EUR ({p1})",
    "dashboard.57": "({p0}). Millest alates riigi asutus võib trahve määrata, määrab direktiivi ülevõttev seadus — see moodul seda ei tea. Rakendamiskohustused tulenevad riigisisesest õigusest alates selle jõustumise päevast.",
    "dashboard.65": "({p0}). Millest alates riigi asutus võib trahve määrata, määrab direktiivi ülevõttev seadus — see moodul seda ei tea. Rahaline risk pole seetõttu siin dateeritud, rakendamiskohustused aga tulenevad riigisisesest õigusest alates selle jõustumise päevast.",
    "dashboard.83": "Elektroonilise side tegevus — künnised määrab riigisisene õigus.",
    "dashboard.84": "Määrust (EL) 2024/2690 ei kohaldata üldkasutatavate elektroonilise side võrkude ja teenuste pakkujatele. Nende puhul määrab olulise intsidendi künnised riigisisene õigus (direktiivi artikli 23 lõige 11) — see moodul neid ei tea ja seetõttu arve ei esita.",
    "dashboard.terminRejestracji": "Registreerimisandmete esitamise tähtaja määrab riigisisene õigus (direktiivi artikli 3 lõige 4). Artikli 27 lõikes 1 nimetatud osutajad — DNS-teenuse osutajad, tippdomeeninimede registrid, pilvandmetöötlus-, andmekeskus-, sisuedastusvõrgu-, hallatud teenuse ja hallatud turbeteenuse osutajad — esitavad andmed ENISA registrisse: algselt 17. jaanuariks 2025 ja iga muudatuse põhjendamatu viivituseta.",
    "html.1": "ITORO — NIS 2 direktiivile (EL) 2022/2555 vastavuse hindamine",
    "html.10": "NIS 2 direktiivile vastavuse hindamine — ühine moodul",
    "html.100": "Majandusaasta aruande lugemine töötab ainult riigisisese õiguse mooduliga riikide puhul. Selle riigi puhul sisestate majandusaasta <strong>tulu</strong> käsitsi — sellest sõltub trahvi suurus.",
    "html.102": "Registriandmete automaatne hankimine töötab ainult riigisisese õiguse mooduliga riikide puhul. Rollid ja ettevõtte suuruse märgite käsitsi.",
    "html.11": "Direktiiv (EL) 2022/2555 (NIS 2) nõuab ülevõtmist riigisisesesse õigusesse. Hindamine hõlmab otse direktiivist tulenevaid kohustusi ja otsekohalduvat komisjoni rakendusmäärust (EL) 2024/2690 — ulatuses, milles need üksust puudutavad.",
    "html.23": "tulu ja suuruse sisestate käsitsi — ühine moodul ei tee riiklikesse registritesse päringuid",
    "html.33": "Euroopa Parlamendi ja nõukogu 14. detsembri 2022. aasta direktiiv (EL) 2022/2555 (NIS 2)",
    "html.33a": "{p0} — direktiivi üle võttev riigisisene akt; selle nõudeid see moodul veel ei hinda",
    "html.33b": "riik ei ole veel ülevõtmisakti vastu võtnud — hindamine lähtub liidu õigusest",
    "html.35": "juhtorgani kohustused — direktiivi artikkel 20",
    "html.36": "Tööriist on mõeldud enesehindamiseks. See ei ole audit ega õigusnõustamine.",
    "html.40": "ühine moodul ei loo ühtegi väljuvat ühendust — ei tee registritesse päringuid",
    "html.59": "Majandusaasta aruanded",
    "html.60": "Majandusaasta aruande lugemine on saadaval ainult riigisisese õiguse mooduliga riikide puhul. Selle riigi puhul sisestate tulu ja töötajate arvu käsitsi.",
    "html.62": "Otsing registrist",
    "html.63": "äriregistrid on riiklikud — ühine moodul neid ei tea",
    "html.64": "rollid ja ettevõtte suuruse märgite käsitsi",
    "html.66": "Üksuse identifitseerimisnumber",
    "html.68": "Registriandmete automaatne hankimine töötab ainult riigisisese õiguse mooduliga riikide puhul.",
    "html.76": "Aastatulu (EUR)",
    "html.78": "Tulu elektroonilise side tegevusest (EUR)",
    "html.79": "Väli puudutab üldkasutatavate elektroonilise side võrkude või teenuste pakkujaid. Riigisisesed künnised määrab liikmesriigi õigus.",
    "html.80": "Juhi kuutasu (EUR)",
    "html.82": "Vahetuskurss",
    "html.83": "Direktiivi trahvide ülempiirid on väljendatud eurodes. Ümberarvestuse omavääringusse ja kursi määrab riigisisene õigus — siin on summad eurodes ilma ümberarvestuseta.",
    "html.84": "Staatus tuleneb üksnes seotud ettevõtete andmete liitmisest ja üksuse infosüsteem on sõltumatu (direktiivi põhjendus 16 — kohaldamise üle otsustab riigisisene õigus)",
    "html.85": "Üksus tegutseb riikliku julgeoleku, avaliku julgeoleku, riigikaitse või õiguskaitse valdkonnas (direktiivi artikli 2 lõige 7)",
    "html.91": "Euroopa Parlamendi ja nõukogu direktiivile (EL) 2022/2555 (NIS 2) ning komisjoni rakendusmäärusele (EL) 2024/2690 vastavuse hindamine — ühine moodul riikidele, mille riigisisese õiguse moodul pole veel valmis.",
    "html.94": "kas üksus on <strong>elutähtis</strong>, <strong>oluline</strong> või jääb direktiivi kohaldamisalast välja",
    "html.daneZeSprawozdania": "nimi, identifitseerimisnumber, registrijärgne aadress",
    "html.rejestrMozliwy": "Register {p0} on avalik ja tasuta — selle lugemise saab tööriista lisada; ootame pull request’e (vt README).",
    "html.tytulNaglowka": "NIS 2 direktiivile vastavuse hindamine",
    "html.zrodlaRecznie": "See moodul ei tunne teie riigi registreid — täitke profiil käsitsi. Aastakäive määrab trahvi ülempiiri, seega sisestage see täpselt.",
    "klasyfikacja.10": "direktiivi (EL) 2022/2555 artikli 3 lõike 1 punkt c (üldkasutatavate elektroonilise side võrkude või üldkasutatavate elektroonilise side teenuste pakkuja, kes on vähemalt keskmise suurusega ettevõte)",
    "klasyfikacja.11": "direktiivi (EL) 2022/2555 artikli 3 lõige 2 koostoimes artikli 2 lõike 2 punkti a alapunktiga i (üldkasutatavate elektroonilise side võrkude või teenuste pakkuja, kes on mikro- või väikeettevõte)",
    "klasyfikacja.12": "direktiivi (EL) 2022/2555 artikli 3 lõike 1 punkt a (hallatud turbeteenuse osutaja, kes ületab keskmise suurusega ettevõtte piirmäärad)",
    "klasyfikacja.13": "Mikro- ja väikeettevõtted ei kuulu selle rolli alusel direktiivi kohaldamisalasse (artikli 2 lõige 1 a contrario).",
    "klasyfikacja.15": "direktiivi (EL) 2022/2555 artikli 3 lõike 1 punkt b (kvalifitseeritud usaldusteenuse osutaja) — sõltumata ettevõtte suurusest",
    "klasyfikacja.16": "direktiivi (EL) 2022/2555 artikli 3 lõige 2 koostoimes artikli 2 lõike 2 punkti a alapunktiga ii (kvalifitseerimata usaldusteenuse osutaja, kes on mikro-, väike- või keskmise suurusega ettevõte)",
    "klasyfikacja.18": "direktiivi (EL) 2022/2555 artikli 3 lõige 2 (piirkondliku tasandi avaliku halduse üksus, kui liikmesriik nii sätestab — artikli 2 lõike 2 punkti f alapunkt ii)",
    "klasyfikacja.19": "direktiivi (EL) 2022/2555 artikli 3 lõike 1 punkt f (keskvalitsuse tasandi avaliku halduse üksus — artikli 2 lõike 2 punkti f alapunkt i)",
    "klasyfikacja.2": "Eel- ja järeljärelevalve (direktiivi (EL) 2022/2555 artikkel 32).",
    "klasyfikacja.20": "direktiivi (EL) 2022/2555 artikli 3 lõige 2 (piirkondliku tasandi avaliku halduse üksus — artikli 2 lõike 2 punkti f alapunkt ii)",
    "klasyfikacja.21": "Kohaliku tasandi avaliku halduse üksuste kohustuste ulatuse määrab riigisisene õigus (direktiivi artikli 2 lõike 5 punkt a).",
    "klasyfikacja.22": "Liikmesriik võib vabastada üksused, mis tegutsevad riikliku julgeoleku, avaliku julgeoleku, riigikaitse või õiguskaitse valdkonnas (direktiivi artikli 2 lõige 7). Vabastus ei toimi iseenesest — kontrollige hindamise tulemust riigisisese õiguse alusel.",
    "klasyfikacja.23": "Üksus vastab nii elutähtsa kui ka olulise üksuse kriteeriumidele. Ta on elutähtis üksus (direktiivi artikli 3 lõige 1) ja rangemad nõuded kohalduvad kogu direktiiviga hõlmatud tegevusele.",
    "klasyfikacja.25": "Üksus on elutähtis, seega kohaldub talle direktiivi artikli 21 lõike 2 meetmete täielik kataloog ning eel- ja järeljärelevalve — hindamine hõlmab täielikku küsimuste kogumit.",
    "klasyfikacja.26": "Olulise üksusena kohaldub teile sama artikli 21 lõike 2 meetmete kataloog, kuid ainult järeljärelevalve (artikkel 33). Trahvi ülempiir on madalam: 7 mln EUR või 1,4 % käibest (artikli 34 lõige 5). Avaliku sektori üksuste leevendusi võib kehtestada riigisisene õigus — see moodul neid ei tea.",
    "klasyfikacja.28": "Avaliku halduse üksuste kohustused tulenevad direktiivi artikli 2 lõike 2 punktist f; nende täpse ulatuse, sealhulgas kohaliku tasandi ja haridusasutuste puhul, määrab riigisisene õigus (artikli 2 lõige 5).",
    "klasyfikacja.29": "Deklareeritud on, et üksuse staatus tuleneb üksnes seotud või partnerettevõtete andmete liitmisest ja et üksuse infosüsteem on sõltumatu. Direktiiv lubab sellist väljajätmist (põhjendus 16), kuid selle üle otsustab riigisisene õigus — moodul aktsepteerib väljajätmist, kuid seda tuleb liikmesriigi õiguse alusel kontrollida ja dokumenteerida.",
    "klasyfikacja.4": "Ainult järeljärelevalve — tõendite, viidete või teabe korral rikkumise kohta (direktiivi (EL) 2022/2555 artikkel 33).",
    "klasyfikacja.5": "Direktiivi kohaldamisalast väljas",
    "klasyfikacja.6": "Märgitud rolli puhul direktiivist (EL) 2022/2555 kohustusi ei tulene.",
    "klasyfikacja.7": "direktiivi (EL) 2022/2555 artikli 3 lõike 1 punkt a (I lisas loetletud liiki üksus, kes ületab keskmise suurusega ettevõtte piirmäärad)",
    "klasyfikacja.8": "direktiivi (EL) 2022/2555 artikli 3 lõige 2 (I lisas loetletud liiki üksus, kes vastab keskmise suurusega ettevõtte kriteeriumidele)",
    "klasyfikacja.9": "Mikro- ja väikeettevõtted ei kuulu selle rolli alusel direktiivi kohaldamisalasse (artikli 2 lõige 1 a contrario).",
    "kreator.10": "Sisestage eelmise aasta tulu käsitsi.",
    "kreator.35": "<span class=\"text-secondary\">Majandusaasta aruannete lugemine pole selle riigi puhul saadaval.</span>",
    "kreator.37": "Majandusaasta aruannete lugemine pole selle riigi puhul saadaval — sisestage tulu käsitsi.",
    "kreator.56": "Jah — ELi määrus on otsekohalduv alates 7. novembrist 2024 kõigis liikmesriikides ja sellel pole üleminekuperioodi. Selle alus on",
    "kreator.57": ", mis volitas komisjoni kehtestama tehnilised ja metoodilised nõuded määruse artikli 3 lõikes 1 nimetatud osutajatele. Direktiivi ülevõtmise tähtaeg möödus",
    "kreator.58": ", ja millest alates riigi asutus võib trahve määrata, määrab riigisisene õigus. Lisa tehnilised nõuded (6. ning 9.–13. jagu) on siduvad praegusel kujul — need ei oota täpsustamist. Kõrvale kalduda saab ainult nõuetest klausliga „kui see on asjakohane“ ja üksnes dokumenteeritud põhjendusega.",
    "kreator.9": "Majandusaasta aruanded →",
    "kreator.przepisReg2690": "direktiivi (EL) 2022/2555 artikli 21 lõige 5",
    "kreator.terminReg2690": "17. oktoobril 2024",
    "punktacja.10": "Avaliku sektori üksused",
    "punktacja.4": "NIS 2 direktiiv — artikkel 21",
    "punktacja.5": "NIS 2 direktiiv — vormilised kohustused",
    "punktacja.8": "Elektrooniline side",
    "punktacja.9": "NIS 2 direktiiv — avaliku sektori üksused",
    "punktacja.skrotKsc": "NIS 2",
    "punktacja.skrotPke": "telekom",
    "ue.cyt.akapit": "{p0} lõik",
    "ue.cyt.art": "artikli {p0}",
    "ue.cyt.drugi": "teine",
    "ue.cyt.dyr": "direktiivi (EL) 2022/2555 {p0}",
    "ue.cyt.i": "ja",
    "ue.cyt.laczenie": " ",
    "ue.cyt.lit": "punkt {p0}",
    "ue.cyt.litery": "",
    "ue.cyt.pkt": "punkt {p0}",
    "ue.cyt.rozdzielacz": "; ",
    "ue.cyt.rozp": "määruse (EL) 2024/2690 {p0}",
    "ue.cyt.ust": "lõige {p0}",
    "ue.katalog.1": "Riskianalüüsi ja infosüsteemide turvalisuse põhimõtted",
    "ue.katalog.10": "Intsidentide käsitlemine",
    "ue.katalog.11": "Intsidentide käsitlemine hõlmab tegevusi ja menetlusi intsidendi ennetamiseks, avastamiseks, analüüsimiseks ja ohjeldamiseks või sellele reageerimiseks ja sellest taastumiseks (artikli 6 punkt 8).",
    "ue.katalog.12": "Kas on dokumenteeritud intsidentide käsitlemise kord, mis hõlmab avastamist, analüüsi, ohjeldamist, reageerimist ja taastumist?",
    "ue.katalog.13": "ISO/IEC 27001 A.5.24–A.5.26",
    "ue.katalog.14": "Kas kord võimaldab järgida olulisest intsidendist teatamise tähtaegu: varajane hoiatus 24 tunni jooksul, intsidenditeade 72 tunni jooksul, lõpparuanne ühe kuu jooksul?",
    "ue.katalog.15": "ISO/IEC 27001 A.5.24",
    "ue.katalog.16": "Kas üksusel on kriteeriumid intsidendi oluliseks tunnistamiseks kooskõlas artikli 23 lõikega 3: tõsine tegevushäire või rahaline kahju või märkimisväärne kahju teistele isikutele?",
    "ue.katalog.17": "ISO/IEC 27001 A.5.25",
    "ue.katalog.18": "Kas intsidendid registreeritakse ja kas nende käsitlemise õppetunde kasutatakse meetmete parandamiseks?",
    "ue.katalog.19": "ISO/IEC 27001 A.5.27",
    "ue.katalog.2": "Meetmed põhinevad kõiki ohte arvestaval lähenemisviisil (artikli 21 lõige 2). Nende proportsionaalsust hinnatakse, võttes arvesse riskidele avatuse astet, üksuse suurust, intsidentide tõenäosust ja raskust (artikli 21 lõike 1 teine lõik).",
    "ue.katalog.20": "Talitluspidevus ja kriisiohje",
    "ue.katalog.21": "Talitluspidevus, näiteks varukoopiate haldus ja avariitaaste, ning kriisiohje.",
    "ue.katalog.22": "Kas on talitluspidevuse plaan, mis hõlmab taastumist pärast katastroofi?",
    "ue.katalog.23": "ISO/IEC 27001 A.5.29–A.5.30",
    "ue.katalog.24": "Kas varukoopiaid tehakse, kaitstakse ja testitakse taastatavuse suhtes?",
    "ue.katalog.25": "ISO/IEC 27001 A.8.13",
    "ue.katalog.26": "Kas üksusel on kriisiohje menetlused määratletud rollide ja sidekanalitega?",
    "ue.katalog.27": "ISO/IEC 27001 A.5.29",
    "ue.katalog.28": "Kas talitluspidevuse ja taastamise plaane testitakse perioodiliselt ja tulemused dokumenteeritakse?",
    "ue.katalog.29": "ISO/IEC 27001 A.5.30",
    "ue.katalog.3": "Kas üksusel on dokumenteeritud riskianalüüsi ja infosüsteemide turvalisuse põhimõtted, mille on kinnitanud juhtorgan?",
    "ue.katalog.30": "Tarneahela turvalisus",
    "ue.katalog.31": "Tarneahela turvalisus, sealhulgas üksuse ja tema otseste tarnijate või teenuseosutajate vaheliste suhete turvaaspektid. Üksus võtab arvesse iga tarnija spetsiifilisi nõrkusi ning tema toodete ja küberturvalisuse tavade üldist kvaliteeti (artikli 21 lõige 3).",
    "ue.katalog.32": "Kas üksus peab otseste tarnijate ja teenuseosutajate loetelu koos hinnanguga nende tähtsusele võrkude ja süsteemide turvalisuse seisukohast?",
    "ue.katalog.33": "ISO/IEC 27001 A.5.19",
    "ue.katalog.34": "Kas tarnijate suhtes meetmete valikul võetakse arvesse igaühe spetsiifilisi nõrkusi ning nende küberturvalisuse ja turvalise arenduse tavade kvaliteeti?",
    "ue.katalog.35": "ISO/IEC 27001 A.5.19, A.5.21",
    "ue.katalog.36": "Kas lepingud tarnijatega sisaldavad turvanõudeid ning kohustust teatada intsidentidest ja nõrkustest?",
    "ue.katalog.37": "ISO/IEC 27001 A.5.20",
    "ue.katalog.38": "Kas üksus võtab arvesse artiklis 22 nimetatud kriitiliste tarneahelate koordineeritud turvariskide hindamise tulemusi?",
    "ue.katalog.39": "ISO/IEC 27001 A.5.21",
    "ue.katalog.4": "ISO/IEC 27001 punktid 5.2, 6.1.2",
    "ue.katalog.40": "Turvalisus süsteemide hankimisel, arendamisel ja hooldamisel",
    "ue.katalog.41": "Turvalisus võrgu- ja infosüsteemide hankimisel, arendamisel ja hooldamisel, sealhulgas nõrkuste käsitlemine ja avalikustamine.",
    "ue.katalog.42": "Kas turvanõuded määratletakse enne süsteemi hankimist või arenduse alustamist ja kontrollitakse enne kasutuselevõttu?",
    "ue.katalog.43": "ISO/IEC 27001 A.8.25–A.8.29",
    "ue.katalog.44": "Kas on nõrkuste käsitlemise protsess: tuvastamine, hindamine, kõrvaldamine määratud aja jooksul?",
    "ue.katalog.45": "ISO/IEC 27001 A.8.8",
    "ue.katalog.46": "Kas üksusel on nõrkuste avalikustamise kord, sealhulgas kanal kolmandate isikute teadete vastuvõtmiseks?",
    "ue.katalog.47": "Kas süsteemide muudatused läbivad kontrollitud muudatuste halduse protsessi koos turvamõju hindamisega?",
    "ue.katalog.48": "ISO/IEC 27001 A.8.32",
    "ue.katalog.49": "Meetmete tõhususe hindamine",
    "ue.katalog.5": "Kas riskianalüüs hõlmab kõiki ohte võrgu- ja infosüsteemidele ning nende füüsilisele keskkonnale, mitte ainult küberohte?",
    "ue.katalog.50": "Põhimõtted ja menetlused küberturvalisuse riskijuhtimismeetmete tõhususe hindamiseks.",
    "ue.katalog.51": "Kas on dokumenteeritud meetmete tõhususe hindamise põhimõtted, mis määravad ulatuse, sageduse ja meetodid?",
    "ue.katalog.52": "ISO/IEC 27001 punkt 9.1",
    "ue.katalog.53": "Kas tõhususe hindamisi tehakse perioodiliselt ja kas nende tulemused esitatakse juhtorganile?",
    "ue.katalog.54": "ISO/IEC 27001 punktid 9.2–9.3",
    "ue.katalog.55": "Kas tuvastatud puudused viivad dokumenteeritud parandusmeetmeteni koos vastutaja ja tähtajaga?",
    "ue.katalog.56": "ISO/IEC 27001 punkt 10.1",
    "ue.katalog.57": "Küberhügieen ja koolitus",
    "ue.katalog.58": "Küberhügieeni põhitavad ja küberturvalisuse koolitus. Juhtorgani liikmed läbivad regulaarselt koolitusi (artikli 20 lõige 2).",
    "ue.katalog.59": "Kas üksus rakendab küberhügieeni põhitavasid: uuendused, paroolihaldus, õiguste piiramine, kaitse pahavara eest?",
    "ue.katalog.6": "ISO/IEC 27001 punkt 6.1.2",
    "ue.katalog.60": "ISO/IEC 27001 A.8.7, A.8.8",
    "ue.katalog.61": "Kas töötajad saavad oma rollile kohandatud küberturvalisuse koolitust ja kas osalemine dokumenteeritakse?",
    "ue.katalog.62": "ISO/IEC 27001 A.6.3",
    "ue.katalog.63": "Kas juhtorgani liikmed läbivad regulaarselt koolitusi, mis võimaldavad tuvastada riske ja hinnata riskijuhtimistavasid?",
    "ue.katalog.64": "ISO/IEC 27001 punkt 7.2",
    "ue.katalog.65": "Krüptograafia ja krüpteerimine",
    "ue.katalog.66": "Põhimõtted ja menetlused krüptograafia ning vajaduse korral krüpteerimise kasutamiseks.",
    "ue.katalog.67": "Kas on krüptograafia põhimõtted, mis määravad, milliseid andmeid ja kanaleid krüpteeritakse ja milliste algoritmidega?",
    "ue.katalog.68": "ISO/IEC 27001 A.8.24",
    "ue.katalog.69": "Kas krüptovõtmeid hallatakse kogu elutsükli vältel: genereerimine, jaotamine, säilitamine, vahetamine, kasutuselt kõrvaldamine?",
    "ue.katalog.7": "Kas meetmete valikul võetakse arvesse tehnika taset, asjakohaseid Euroopa ja rahvusvahelisi standardeid ning rakendamise kulusid?",
    "ue.katalog.70": "Personal, juurdepääsu kontroll ja varahaldus",
    "ue.katalog.71": "Personaliturve, juurdepääsu kontrolli põhimõtted ja varahaldus.",
    "ue.katalog.72": "Kas üksus peab ajakohast varade loetelu koos määratud omanike ja klassifikatsiooniga?",
    "ue.katalog.73": "ISO/IEC 27001 A.5.9, A.5.12",
    "ue.katalog.74": "Kas on juurdepääsu kontrolli põhimõtted, mis põhinevad vähimate õiguste põhimõttel, koos õiguste perioodilise ülevaatamisega?",
    "ue.katalog.75": "ISO/IEC 27001 A.5.15, A.5.18",
    "ue.katalog.76": "Kas töölevõtmisel, ametikoha muutumisel ja töötaja lahkumisel rakendatakse turvamenetlusi, sealhulgas õiguste tühistamist ja varade tagastamist?",
    "ue.katalog.77": "ISO/IEC 27001 A.6.1–A.6.5",
    "ue.katalog.78": "Kas privilegeeritud juurdepääs on piiratud, logitud ja üle vaadatud?",
    "ue.katalog.79": "ISO/IEC 27001 A.8.2",
    "ue.katalog.8": "ISO/IEC 27001 punkt 6.1.3",
    "ue.katalog.80": "Mitmeastmeline autentimine ja turvatud side",
    "ue.katalog.81": "Kui see on asjakohane — mitmeastmeline või pidev autentimine, turvatud kõne-, video- ja tekstside ning turvatud hädaolukorra sidesüsteemid üksuse sees.",
    "ue.katalog.82": "Kas mitmeastmelist või pidevat autentimist kasutatakse seal, kus riskianalüüs seda õigustab, eelkõige kaugjuurdepääsu ja privilegeeritud kontode puhul?",
    "ue.katalog.83": "ISO/IEC 27001 A.8.5",
    "ue.katalog.84": "Kas tööotstarbel kasutatav kõne-, video- ja tekstside on turvatud?",
    "ue.katalog.85": "ISO/IEC 27001 A.8.20",
    "ue.katalog.86": "Kas üksusel on turvatud sisemine hädaolukorra sidesüsteem, mis on põhitaristust sõltumatu?",
    "ue.katalog.9": "Kas turvatase on dokumenteeritud kui riskile vastav, põhjendusega, mis võtab arvesse üksuse suurust ning intsidentide ühiskondlikku ja majanduslikku mõju?",
    "ue.kierownictwo.1": "Elutähtsa või olulise üksuse juhtorgan — äriühingus juhatus. Direktiiv seda mõistet ei määratle; selle ulatus konkreetses riigis tuleneb riigisisesest õigusest.",
    "ue.kierownictwo.10": "Määrata üksuse staatus ja tagada registreerimine",
    "ue.kierownictwo.11": "Kindlakstegemine, kas üksus on elutähtis või oluline, ja registreerimisandmete esitamine pädevale asutusele. Korra ja tähtaja määrab riigisisene õigus.",
    "ue.kierownictwo.12": "Rakendada riskianalüüs ja turvapoliitika",
    "ue.kierownictwo.13": "Kõiki ohte arvestaval lähenemisviisil põhinevad meetmed, mis on proportsionaalsed riskidele avatuse, üksuse suuruse ja intsidentide raskusega.",
    "ue.kierownictwo.14": "Seada sisse intsidentide käsitlemine ja teatamine",
    "ue.kierownictwo.15": "Intsidentide käsitlemise kord ning võime järgida 24 tunni, 72 tunni ja ühe kuu tähtaegu.",
    "ue.kierownictwo.16": "24 h / 72 h / kuu alates avastamisest",
    "ue.kierownictwo.17": "Tagada talitluspidevus",
    "ue.kierownictwo.18": "Talitluspidevuse plaan, varukoopiad, avariitaaste, kriisiohje.",
    "ue.kierownictwo.19": "Korrastada tarneahel",
    "ue.kierownictwo.2": "Juhtorgani vastutus ei mõjuta riigisiseseid norme avalike asutuste ja ametnike vastutuse kohta (artikli 20 lõike 1 teine lõik).",
    "ue.kierownictwo.20": "Tarnijate loetelu, nende nõrkuste ja tavade hindamine, turvanõuded lepingutes.",
    "ue.kierownictwo.21": "Rakendada juurdepääsu kontroll ja varahaldus",
    "ue.kierownictwo.22": "Varade loetelu, vähimate õiguste põhimõte, õiguste ülevaatused, mitmeastmeline autentimine seal, kus risk seda õigustab.",
    "ue.kierownictwo.23": "Mõõta meetmete tõhusust",
    "ue.kierownictwo.24": "Tõhususe hindamise põhimõtted ja menetlused, perioodilised ülevaatused, parandusmeetmed.",
    "ue.kierownictwo.25": "Kinnitada",
    "ue.kierownictwo.26": "küberturvalisuse riskijuhtimismeetmed (artikli 20 lõige 1)",
    "ue.kierownictwo.27": "riskianalüüsi ja süsteemide turvalisuse põhimõtted",
    "ue.kierownictwo.28": "rakendamise eelarve ja rollid",
    "ue.kierownictwo.29": "Jälgida",
    "ue.kierownictwo.3": "Kas kohustuste usaldamine teisele isikule välistab vastutuse, otsustab riigisisene õigus. Poolas ei välista (riikliku küberturvalisuse süsteemi seaduse artikli 8c lõige 3).",
    "ue.kierownictwo.30": "kinnitatud meetmete rakendamist (artikli 20 lõige 1)",
    "ue.kierownictwo.31": "tõhususe hindamise tulemusi (artikli 21 lõike 2 punkt f)",
    "ue.kierownictwo.32": "intsidentidest teatamise tähtaegade järgimist (artikkel 23)",
    "ue.kierownictwo.33": "Dokumenteerida",
    "ue.kierownictwo.34": "kinnitamisotsused ja ülevaatused",
    "ue.kierownictwo.35": "koolitustel osalemine (artikli 20 lõige 2)",
    "ue.kierownictwo.36": "Juhtorgani liige",
    "ue.kierownictwo.37": "meetmete kinnitamine, järelevalve, otsused, eelarve",
    "ue.kierownictwo.38": "Projektijuht",
    "ue.kierownictwo.39": "rakendamise koordineerimine, ajakava, seis ja tõendid",
    "ue.kierownictwo.4": "Kinnitada küberturvalisuse riskijuhtimismeetmed",
    "ue.kierownictwo.40": "IT / küberturvalisus",
    "ue.kierownictwo.41": "riskianalüüs, tehnilised meetmed, intsidentide käsitlemine",
    "ue.kierownictwo.42": "Õigusosakond / vastavus",
    "ue.kierownictwo.5": "Juhtorgan kinnitab meetmed, mis on võetud artikli 21 järgimiseks. See on organi, mitte IT-osakonna otsus — ilma selleta puudub meetmetel alus.",
    "ue.kierownictwo.6": "Jälgida meetmete rakendamist",
    "ue.kierownictwo.7": "Rakendamise järelevalve on juhtorgani kohustus. Täitmist saab delegeerida, järelevalvet mitte.",
    "ue.kierownictwo.8": "Läbida regulaarselt koolitusi",
    "ue.kierownictwo.9": "Juhtorgani liikmed läbivad regulaarselt koolitusi, et omandada piisavad teadmised riskide tuvastamiseks ning riskijuhtimistavade ja nende mõju hindamiseks üksuse teenustele.",
    "ue.kierownictwo.daneRejestracyjne": "registreerimisandmed ja nende ajakohastamine (artikli 3 lõiked 4 ja 5)",
    "ue.meta.1": "Ülekaalus on protsendivariant: {p0} % käibest on rohkem kui {p1} mln EUR.",
    "ue.meta.10": "Direktiiv ei pane ettevõtjatele kohustusi otse — seda teeb riigisisene seadus, mille liikmesriik pidi vastu võtma 17. oktoobriks 2024. See moodul näitab nõudeid direktiivi sõnastuses, sest valitud riigi riigisisese õiguse moodul pole veel valmis või riik pole direktiivi üle võtnud.",
    "ue.meta.11": "Direktiivist tulenevad kohustused",
    "ue.meta.12": "Üksuste loetelu — 17. aprilliks 2025",
    "ue.meta.13": "Liikmesriigid pidid 17. aprilliks 2025 koostama elutähtsate ja oluliste üksuste loetelu ning nõudma üksustelt registreerimisandmete esitamist.",
    "ue.meta.14": "Määrus (EL) 2024/2690",
    "ue.meta.15": "Otsekohalduv alates 7. novembrist 2024",
    "ue.meta.16": "Rakendusmäärus on otsekohalduv kõigis liikmesriikides, sõltumata direktiivi ülevõtmise seisust. See puudutab selle artiklis 1 loetletud üksusi: DNS-, tippdomeeni-, pilve-, andmekeskus-, sisuedastusvõrgu-, hallatud teenuse ja usaldusteenuse osutajaid.",
    "ue.meta.17": "määruse (EL) 2024/2690 artikkel 16",
    "ue.meta.18": "Vähemalt 10 000 000 eurot või vähemalt 2 % ettevõtja eelmise majandusaasta ülemaailmsest aastasest kogukäibest — kohaldatakse suuremat summat. See on minimaalne ülempiir: riigisisene õigus võib seda tõsta.",
    "ue.meta.19": "Vähemalt 7 000 000 eurot või 1,4 % ülemaailmsest aastasest kogukäibest — kohaldatakse suuremat summat. Minimaalne ülempiir.",
    "ue.meta.2": "Ülekaalus on kindel summa: {p0} mln EUR on rohkem kui {p1} % käibest.",
    "ue.meta.20": "Direktiiv ei näe ette eraldi trahvi kvalifitseeritud rikkumise eest — see on mõne liikmesriigi riigisisese õiguse konstruktsioon.",
    "ue.meta.21": "Liikmesriigid võivad ette näha perioodilisi trahve rikkumise lõpetamisele sundimiseks. Suuruse määrab riigisisene õigus.",
    "ue.meta.22": "Juhtorgan kinnitab riskijuhtimismeetmed, jälgib nende rakendamist ja võib artikli 21 rikkumise eest vastutada. Selle vastutuse reeglid ja ulatuse määrab riigisisene õigus.",
    "ue.meta.23": "Juhtorgan kinnitab küberturvalisuse riskijuhtimismeetmed (artikli 20 lõige 1).",
    "ue.meta.24": "Juhtorgan jälgib nende meetmete rakendamist (artikli 20 lõige 1).",
    "ue.meta.25": "Juhtorgani liikmed läbivad regulaarselt koolitusi (artikli 20 lõige 2).",
    "ue.meta.26": "Elutähtsa üksuse puhul võib asutus taotleda juhtimisülesannete täitmise ajutist keeldu (artikli 32 lõike 5 punkt b).",
    "ue.meta.27": "Minimaalse ülempiiri määrab direktiiv",
    "ue.meta.28": "Võrreldakse kahte väärtust: kindlat summat eurodes ja protsenti ettevõtja eelmise majandusaasta ülemaailmsest aastasest kogukäibest. Suurem neist on ülemine piir, mille liikmesriik peab vähemalt ette nägema. Riigisisene õigus võib seda tõsta.",
    "ue.meta.29": "Summa ülempiiri raames määrab riigi asutus",
    "ue.meta.3": "Direktiivi ülempiir ületab üksuse aastakäivet {p0} korda. Artikli 34 lõige 1 nõuab, et trahv oleks proportsionaalne konkreetse juhtumi asjaoludega — see on ülemine piir, mitte eeldatav trahv.",
    "ue.meta.30": "Trahv peab olema tõhus, proportsionaalne ja hoiatav vastavalt konkreetse juhtumi asjaoludele. Asutus võtab arvesse vähemalt artikli 32 lõike 7 kriteeriume: rikkumise raskust ja kestust, varasemaid rikkumisi, tekitatud kahju, tahtlust, parandusmeetmeid ja koostööd.",
    "ue.meta.31": "Ülempiir võib aastakäivet mitmekordselt ületada — see on ülemine piir, mitte eeldatav summa. Riigisisesed miinimumid, perioodilised trahvid ja trahvide määramise korra määrab liikmesriigi seadus.",
    "ue.meta.32": "Haldustrahvi määramise ja selle suuruse üle otsustamisel võetakse igal üksikjuhul nõuetekohaselt arvesse vähemalt artikli 32 lõikes 7 loetletud asjaolusid.",
    "ue.meta.33": "rikkumise raskus ja rikutud sätete tähtsus — raskeks loetakse igal juhul: korduvad rikkumised, olulistest intsidentidest teatamata jätmine või nende kõrvaldamata jätmine, puuduste kõrvaldamata jätmine vastuolus siduvate juhistega, auditite või seire takistamine, vale või jämedalt ebatäpse teabe esitamine",
    "ue.meta.34": "üksuse asjakohased varasemad rikkumised",
    "ue.meta.35": "tekitatud varaline või mittevaraline kahju, sealhulgas rahaline kahju, mõju teistele teenustele ja mõjutatud kasutajate arv",
    "ue.meta.36": "rikkumise tahtlik või hooletusest tingitud iseloom",
    "ue.meta.37": "kahju ärahoidmiseks või leevendamiseks võetud meetmed",
    "ue.meta.38": "heakskiidetud toimimisjuhendite või sertifitseerimismehhanismide järgimine",
    "ue.meta.39": "pädevate asutustega koostöö ulatus",
    "ue.meta.4": "Euroopa Parlamendi ja nõukogu direktiiv (EL) 2022/2555 (NIS 2)",
    "ue.meta.40": "Direktiiv ei näe sõnaselgelt ette trahvist loobumist — kas ja millal see on võimalik, otsustab riigisisene õigus.",
    "ue.meta.41": "Alates sellest kuupäevast peavad liikmesriigid kohaldama direktiivi ülevõtvaid riigisiseseid sätteid. Konkreetne kuupäev, millest alates asutus võib trahvi määrata, tuleneb riigisisesest õigusest.",
    "ue.meta.42": "NIS 2 direktiivi jõustumine",
    "ue.meta.43": "Kahekümnendal päeval pärast avaldamist Euroopa Liidu Teatajas.",
    "ue.meta.44": "Direktiivi ülevõtmise tähtaeg",
    "ue.meta.45": "Selleks kuupäevaks pidid liikmesriigid riigisisesed sätted vastu võtma ja avaldama.",
    "ue.meta.46": "Riigisiseste sätete kohaldamine ja NIS 1 kehtetuks tunnistamine",
    "ue.meta.47": "Alates sellest kuupäevast kohaldavad liikmesriigid ülevõtvaid sätteid; direktiiv (EL) 2016/1148 tunnistatakse kehtetuks.",
    "ue.meta.48": "Määruse (EL) 2024/2690 kohaldamine",
    "ue.meta.49": "Rakendusmäärus on otsekohalduv alates kahekümnendast päevast pärast avaldamist.",
    "ue.meta.5": "ELT L 333, 27.12.2022",
    "ue.meta.50": "Elutähtsate ja oluliste üksuste loetelu",
    "ue.meta.51": "Selleks kuupäevaks koostavad liikmesriigid loetelu; üksused esitavad asutustele registreerimisandmed.",
    "ue.meta.52": "Direktiivi esimene läbivaatamine komisjoni poolt",
    "ue.meta.53": "Komisjon vaatab direktiivi toimimise läbi ja esitab aruande.",
    "ue.meta.54": "Varajane hoiatus olulisest intsidendist",
    "ue.meta.55": "24 tundi alates teadasaamisest",
    "ue.meta.56": "Olulisest intsidendist teatamine",
    "ue.meta.57": "72 tundi alates teadasaamisest",
    "ue.meta.58": "Lõpparuanne",
    "ue.meta.59": "kuu alates intsidenditeatest",
    "ue.meta.6": "Komisjoni rakendusmäärus (EL) 2024/2690",
    "ue.meta.60": "Usaldusteenuse osutaja intsidenditeade",
    "ue.meta.61": "direktiivi (EL) 2022/2555 artikli 21 lõige 5; määruse (EL) 2024/2690 artiklid 1 ja 2",
    "ue.meta.62": "Käibeandmete puudumisel on ülempiiriks direktiivi kindel summa.",
    "ue.meta.63": "Artikli 34 lõigete 4 ja 5 ülempiirid on miinimumid („vähemalt“) — riigisisene õigus võib ette näha kõrgemaid. Summad eurodes, ilma omavääringusse ümberarvestamata.",
    "ue.meta.64": "Liikmesriigi pädev asutus",
    "ue.meta.65": "Juhtorgan võib artikli 21 rikkumise eest vastutada. Ulatuse ja korra määrab riigisisene õigus — see moodul neid ei tea.",
    "ue.meta.66": "Juhtkonna isikliku vastutuse ulatus tuleneb riigisisesest seadusest. Poola puhul on see kuni 300 % tasust (riikliku küberturvalisuse süsteemi seaduse artikli 73a lõige 4); teised liikmesriigid reguleerivad seda erinevalt.",
    "ue.meta.7": "ELT L, 2024/2690",
    "ue.meta.8": "Direktiiv (EL) 2022/2555",
    "ue.meta.9": "Ülevõtmise tähtaeg möödus 17. oktoobril 2024",
    "ue.moduly.1": "u {p0} min",
    "ue.moduly.10": "Kümme valdkonda artikli 21 lõike 2 punktidest a–j: riskipoliitikast mitmeastmelise autentimiseni. Rikkumine on karistatav trahviga artikli 34 alusel. Hindamine küpsusskaalal.",
    "ue.moduly.11": "Määrus 2024/2690 — juhtimine ja protsessid",
    "ue.moduly.12": "Lisa 1.–5. ja 7.–8. jagu: põhimõtted, riskijuhtimine, intsidentide käsitlemine, talitluspidevus, tarneahel, tõhususe hindamine, küberhügieen. Otsekohalduv alates 7. novembrist 2024.",
    "ue.moduly.13": "Määrus 2024/2690 — tehnilised nõuded",
    "ue.moduly.14": "Lisa 6. ja 9.–13. jagu: süsteemide hankimine ja arendamine, krüptograafia, personaliturve, juurdepääsu kontroll, varahaldus, füüsiline ja keskkonnaturve.",
    "ue.moduly.2": "u {p0} h {p1} min",
    "ue.moduly.3": "u {p0} h",
    "ue.moduly.4": "alla minuti",
    "ue.moduly.5": "Kiire riskihinnang",
    "ue.moduly.6": "Üldküsimused direktiivi kõigist valdkondadest. Igaüks otsustab terve teemarühma üle. Võimaldab hinnata mahajäämuse ulatust kogu küsimustikku läbimata.",
    "ue.moduly.7": "Direktiivist tulenevad kohustused",
    "ue.moduly.8": "Registreerimisandmed, intsidentidest teatamine 24 ja 72 tunni jooksul, juhtorgani kohustused, valmisolek järelevalveks. Kontrollitav dokumentide põhjal, ilma tehnilise analüüsita.",
    "ue.moduly.9": "Riskijuhtimismeetmed — artikli 21 lõige 2",
    "ue.obowiazki.1": "Registreerimisandmed üksuste loetelu jaoks",
    "ue.obowiazki.10": "Olulistest intsidentidest teatamine",
    "ue.obowiazki.11": "Üksus teatab olulistest intsidentidest CSIRT-ile või pädevale asutusele kolmes etapis: varajane hoiatus, intsidenditeade, lõpparuanne. Tähtajad kulgevad alates intsidendist teadasaamisest.",
    "ue.obowiazki.12": "Kas üksus suudab 24 tunni jooksul alates olulisest intsidendist teadasaamisest esitada varajase hoiatuse, märkides, kas intsidendi põhjustas eeldatavasti õigusvastane tegevus ja kas sellel võib olla piiriülene mõju?",
    "ue.obowiazki.13": "24 tundi alates teadasaamisest",
    "ue.obowiazki.14": "Kas üksus suudab 72 tunni jooksul esitada intsidenditeate koos raskuse ja mõju esialgse hinnangu ning ohuindikaatoritega?",
    "ue.obowiazki.15": "72 tundi alates teadasaamisest",
    "ue.obowiazki.16": "Kas üksus esitab hiljemalt kuu aja jooksul pärast teadet lõpparuande intsidendi kirjelduse, ohu liigi, leevendusmeetmete ja piiriülese mõjuga?",
    "ue.obowiazki.17": "kuu alates teatest",
    "ue.obowiazki.18": "Kas üksus teavitab oma teenuste saajaid olulistest intsidentidest, mis võivad nende teenuste osutamist negatiivselt mõjutada?",
    "ue.obowiazki.19": "Kas üksus teavitab teenuste saajaid olulisest küberohust ja meetmetest, mida saajad võivad võtta?",
    "ue.obowiazki.2": "Liikmesriigid koostavad elutähtsate ja oluliste üksuste loetelu ja nõuavad üksustelt registreerimisandmete esitamist. Korra, tähtaja ja portaali määrab riigisisene õigus.",
    "ue.obowiazki.20": "Kui üksus on usaldusteenuse osutaja — kas ta teatab olulistest intsidentidest 24 tunni jooksul alates teadasaamisest?",
    "ue.obowiazki.21": "puudutab usaldusteenuse osutajaid",
    "ue.obowiazki.22": "Juhtorgan",
    "ue.obowiazki.23": "Juhtorgan kinnitab riskijuhtimismeetmed, jälgib nende rakendamist ja võib vastutada. Organi liikmed läbivad regulaarselt koolitusi.",
    "ue.obowiazki.24": "Kas juhtorgan on ametlikult kinnitanud artikli 21 järgimiseks võetud küberturvalisuse riskijuhtimismeetmed?",
    "ue.obowiazki.25": "Kas juhtorgan jälgib nende meetmete rakendamist dokumenteeritult — näiteks perioodiliste aruannete ja ülevaatuste kaudu?",
    "ue.obowiazki.26": "Kas juhtorgani liikmed läbivad regulaarselt koolitusi, mis võimaldavad tuvastada riske ja hinnata riskijuhtimistavasid, ja kas osalemine dokumenteeritakse?",
    "ue.obowiazki.27": "Valmisolek järelevalvemeetmeteks",
    "ue.obowiazki.28": "Elutähtsale üksusele kohaldub eel- ja järeljärelevalve, olulisele üksusele — ainult järeljärelevalve. Asutus võib nõuda teavet, põhimõtete rakendamise tõendeid ja audititulemusi.",
    "ue.obowiazki.29": "Kas üksus suudab asutuse nõudmisel esitada küberturvalisuse põhimõtete rakendamise tõendid, sealhulgas turvaauditite tulemused?",
    "ue.obowiazki.3": "Kas üksus on I või II lisa sektori ja ettevõtte suuruse põhjal kindlaks teinud, kas ta on elutähtis või oluline üksus?",
    "ue.obowiazki.30": "Kas üksus suudab asutuse nõudmisel teha kättesaadavaks järelevalveülesannete täitmiseks vajalikud andmed, dokumendid ja teabe?",
    "ue.obowiazki.31": "Kas elutähtis üksus on valmis asutuse või sõltumatu üksuse tehtavaks turvaauditiks omal kulul?",
    "ue.obowiazki.4": "Kas üksus on esitanud pädevale asutusele registreerimisandmed: nime, aadressi ja kontaktandmed, sektori ja allsektori, nende liikmesriikide loetelu, kus ta teenuseid osutab?",
    "ue.obowiazki.5": "Kontaktandmed hõlmavad e-posti aadresse, IP-aadresside vahemikke ja telefoninumbreid. Riigisisese registreerimistähtaja ja portaali määrab liikmesriigi õigus.",
    "ue.obowiazki.6": "Kas on kord registreerimisandmete ajakohastamiseks põhjendamatu viivituseta pärast nende muutumist?",
    "ue.obowiazki.7": "Direktiiv nõuab ajakohastamist põhjendamatu viivituseta; konkreetne tähtaeg — näiteks 14 päeva Poolas — tuleneb riigisisesest õigusest.",
    "ue.obowiazki.8": "Kui üksus on DNS-teenuse osutaja, tippdomeeninimede register, pilve-, andmekeskus-, CDN- või hallatud teenuse osutaja, internetipõhine kauplemiskoht, otsingumootor või sotsiaalvõrgustik — kas ta on esitanud artikli 27 täiendavad andmed, sealhulgas peamise tegevuskoha aadressi liidus?",
    "ue.obowiazki.9": "puudutab artikli 26 lõikes 1 nimetatud üksusi",
    "ue.role.1": "Liikmesriigi pädev asutus",
    "ue.role.10": "Andmekeskusteenused: kolokatsioon, taristu majutus ja seotud teenused.",
    "ue.role.11": "Andmekeskused",
    "ue.role.12": "Elutähtis üksus üle keskmise suurusega ettevõtte piirmäära (artikli 3 lõike 1 punkt a), oluline — keskmise suuruse korral (artikli 3 lõige 2). Alla keskmise suuruse — kohaldamisalast väljas, välja arvatud juhul, kui liikmesriik määrab üksuse artikli 2 lõike 2 punktide b–e alusel. Hõlmatud määrusega 2024/2690.",
    "ue.role.13": "Interneti vahetuspunkti pakkuja",
    "ue.role.14": "Taristu, mis võimaldab liiklusvahetust sõltumatute võrkude vahel.",
    "ue.role.15": "Interneti vahetuspunktid",
    "ue.role.16": "Klassifikatsioon suuruse järgi (artikli 3 lõike 1 punkt a ja lõige 2). Määrus 2024/2690 interneti vahetuspunkte ei hõlma — määruse artiklis 1 on adressaatide suletud loetelu.",
    "ue.role.17": "DNS-teenuse osutaja",
    "ue.role.18": "Domeeninimede lahendamise teenused, välja arvatud juurnimeserverite käitajad.",
    "ue.role.19": "Domeeninimede süsteem",
    "ue.role.2": "pädev asutus",
    "ue.role.20": "Elutähtis üksus sõltumata suurusest (artikli 3 lõike 1 punkt b). Hõlmatud määrusega 2024/2690.",
    "ue.role.21": "Tippdomeeninimede register",
    "ue.role.22": "Tippdomeeni registri pidamine.",
    "ue.role.23": "Elutähtis üksus sõltumata suurusest (artikli 3 lõike 1 punkt b). Lisaks artikli 28 kohustused registreerimisandmete osas. Hõlmatud määrusega 2024/2690.",
    "ue.role.24": "Pilvandmetöötlusteenuse osutaja",
    "ue.role.25": "Pilvandmetöötlusteenused: taristu, platvorm, tarkvara teenusena.",
    "ue.role.26": "Pilvandmetöötlusteenused",
    "ue.role.27": "Klassifikatsioon suuruse järgi (artikli 3 lõike 1 punkt a ja lõige 2). Hõlmatud määrusega 2024/2690.",
    "ue.role.28": "Sisuedastusvõrgu pakkuja",
    "ue.role.29": "Hajutatud serverite võrk, mis edastab sisu ja teenuseid lõppkasutajatele.",
    "ue.role.3": "määratud riigisisese õigusega; kuni riigisisese mooduli rakendamiseni tööriist konkreetset asutust ei nimeta",
    "ue.role.30": "Sisuedastusvõrgud",
    "ue.role.31": "Usaldusteenuse osutaja",
    "ue.role.32": "Usaldusteenused määruse (EL) nr 910/2014 tähenduses: allkirjad, templid, ajatemplid, sertifikaadid.",
    "ue.role.33": "Usaldusteenused",
    "ue.role.34": "Direktiiv kohaldub sõltumata suurusest (artikli 2 lõike 2 punkti a alapunkt ii). Kvalifitseeritud osutaja on elutähtis üksus sõltumata suurusest (artikli 3 lõike 1 punkt b); kvalifitseerimata osutaja on elutähtis üle keskmise suurusega ettevõtte piirmäära, muul juhul oluline. Hõlmatud määrusega 2024/2690.",
    "ue.role.35": "Hallatud teenuse osutaja",
    "ue.role.36": "Kliendi IKT-taristu haldamine: paigaldus, hooldus, tugi, süsteemide administreerimine.",
    "ue.role.37": "IKT-teenuste haldamine (B2B)",
    "ue.role.38": "Hallatud teenused",
    "ue.role.39": "Hallatud turbeteenuse osutaja",
    "ue.role.4": "Üldkasutatavate elektroonilise side võrkude või üldkasutatavate elektroonilise side teenuste pakkuja",
    "ue.role.40": "Hallatud küberturvalisuse teenused: seire, intsidentidele reageerimine, testimine, nõustamine.",
    "ue.role.41": "Hallatud turbeteenused",
    "ue.role.42": "Direktiiv klassifitseerib suuruse järgi (artikli 3 lõike 1 punkt a ja lõige 2). Liikmesriigid võivad künnist karmistada — Poola loeb MSSP elutähtsaks üksuseks juba alates väikeettevõttest; see moodul kohaldab ainult direktiivi reeglit. Hõlmatud määrusega 2024/2690.",
    "ue.role.5": "Üldkasutatavate elektroonilise side võrkude pakkumine või üldkasutatavate elektroonilise side teenuste, sealhulgas internetiühenduse osutamine.",
    "ue.role.6": "Digitaristu",
    "ue.role.7": "Elektrooniline side",
    "ue.role.8": "Direktiiv kohaldub sõltumata suurusest (artikli 2 lõike 2 punkti a alapunkt i). Keskmise suurusega või suurem ettevõte on elutähtis üksus (artikli 3 lõike 1 punkt c), mikro- ja väikeettevõte — oluline (artikli 3 lõige 2). Riigisisene elektroonilise side seadus võib panna lisakohustusi — see moodul neid ei sisalda.",
    "ue.role.9": "Andmekeskusteenuse osutaja",
    "ue.role.podstawaArt3b": "direktiivi (EL) 2022/2555 artikli 3 lõike 1 punkt b",
    "ue.zaslepki.1": "Euroopa Parlamendi ja nõukogu direktiiv (EL) 2022/2555 (NIS 2)",
    "ue.zaslepki.10": "Kas osa üksusi kantakse loetellu ametiülesande korras, otsustab riigisisene õigus.",
    "ue.zaslepki.11": "Tehke kindlaks, kas direktiiv teid hõlmab",
    "ue.zaslepki.12": "I või II lisa sektor ja ettevõtte suurus. Selle osa teeb selles tööriistas üksuse profiil.",
    "ue.zaslepki.13": "Tehke kindlaks oma riigi pädev asutus",
    "ue.zaslepki.14": "Iga riik määrab pädeva asutuse (artikli 8 lõige 1). Ajakohast loetelu peavad ENISA ja komisjon.",
    "ue.zaslepki.15": "Esitage registreerimisandmed",
    "ue.zaslepki.16": "Nimi, aadress ja kontaktandmed, sektor ja allsektor, teenuste osutamise riigid (artikli 3 lõige 4). Kord riigisisese õiguse järgi.",
    "ue.zaslepki.17": "Ajakohastage andmeid põhjendamatu viivituseta",
    "ue.zaslepki.18": "Iga registreerimisandmete muudatus nõuab ajakohastamist (artikli 3 lõige 5).",
    "ue.zaslepki.19": "aadress ja ajakohased kontaktandmed: e-posti aadressid, IP-aadresside vahemikud, telefoninumbrid",
    "ue.zaslepki.2": "ELT L 333, 27.12.2022, lk 80",
    "ue.zaslepki.20": "I või II lisa sektor ja allsektor",
    "ue.zaslepki.21": "nende liikmesriikide loetelu, kus üksus teenuseid osutab",
    "ue.zaslepki.22": "Määrab riigisisene õigus.",
    "ue.zaslepki.23": "Direktiiv (EL) 2022/2555 — artikkel 3",
    "ue.zaslepki.24": "ENISA — liikmesriikide pädevad asutused",
    "ue.zaslepki.25": "Direktiiv (EL) 2022/2555",
    "ue.zaslepki.26": "ELi moodul ei sisalda riigi asutuse juhiseid — need tulevad koos riigisisese õiguse mooduliga.",
    "ue.zaslepki.27": "Registriandmete automaatne hankimine töötab ainult riigisisese õiguse mooduliga riikide puhul. Täitke profiil käsitsi.",
    "ue.zaslepki.28": "Majandusaasta aruande lugemine töötab ainult riigisisese õiguse mooduliga riikide puhul. Sisestage tulu ja töötajate arv käsitsi.",
    "ue.zaslepki.3": "Komisjoni rakendusmäärus (EL) 2024/2690",
    "ue.zaslepki.4": "ELT L, 2024/2690, 18.11.2024",
    "ue.zaslepki.5": "NIS 2 direktiivis pole eraldi elektroonilise side kihti. Riigisisene elektroonilise side õigus võib panna lisakohustusi — see moodul neid ei tea.",
    "ue.zaslepki.6": "Elutähtsate ja oluliste üksuste loetelu",
    "ue.zaslepki.7": "Liikmesriigi pädev asutus.",
    "ue.zaslepki.8": "Direktiiv kohustab liikmesriike pidama elutähtsate ja oluliste üksuste loetelu ja nõudma üksustelt registreerimisandmete esitamist. Portaali, korra ja tähtaja määrab riigisisene õigus — see moodul neid ei tea, sest valitud riigi riigisisese õiguse moodul pole veel valmis.",
    "ue.zaslepki.9": "Kõik elutähtsad ja olulised üksused. Tähtaja määrab riigisisene õigus.",
    "ue.zaslepki.skrotDyrektywy": "NIS 2 direktiiv",
    "ue.zaslepki.skrotReg2690": "Määrus 2024/2690",
    "xlsx.1": "{p0} – {p1} EUR",
    "xlsx.25": "Vahetuskurss",
    "xlsx.4": "NIS 2 DIREKTIIVILE (EL) 2022/2555 VASTAVUSE ARUANNE",
    "xlsx.58": "Elektroonilise side tegevus: määrust (EL) 2024/2690 ei kohaldata. Künnised määrab riigisisene õigus (direktiivi artikli 23 lõige 11) — ühine moodul neid ei tea.",
    "xlsx.68": "Tööriist on mõeldud enesehindamiseks. See ei ole audit ega õigusnõustamine.",
    "xlsx.69": "Üksuste puhul, mida määrus (EL) 2024/2690 ei hõlma, määrab olulise intsidendi künnised riigisisene õigus (direktiivi artikli 23 lõige 11).",
    "xlsx.70": "Profiilis märgitud rollid on deklaratsioon. Staatuse määrab tegelikult teostatav tegevus (direktiivi (EL) 2022/2555 artikkel 3).",
    "xlsx.etykietaKrs": "Registrinumber",
    "xlsx.etykietaNip": "Identifitseerimisnumber",
    "xlsx.etykietaRegon": "Statistikanumber"
});
