/* Teksty modułu ue — język: fi.
   Te same klucze co w napisy/pl.js (wersja źródłowa); wstawki {p0}, {p1}…
   pozostają bez zmian. Klucze ue.cyt.* to wzorce składania odesłań
   do przepisów w tym języku — patrz kraje/ue/cytaty.js. */
KRAJE.napisy('ue', 'fi', {
    "app.10": "Tarkista alla oleva roolien luettelo — aseman ratkaisee tosiasiallisesti harjoitettu toiminta (direktiivin (EU) 2022/2555 3 artikla), ei rekisterimerkintä.",
    "app.14": "Edellinen vuosi: {p0} €",
    "app.15": "Raportointikauden liikevaihto: {p0} €",
    "app.19": "Haetaan rekistereistä numerolla {p0}…",
    "app.34": " mrd. €",
    "app.35": " milj. €",
    "app.36": " tuhatta €",
    "app.37": "",
    "app.4": "Rekisteritietojen automaattinen haku ei ole käytettävissä tälle maalle — täytä profiili käsin.",
    "app.59": "NIS 2 -direktiivin vaatimustenmukaisuuden arviointi (JSON)",
    "app.68": "Tälle maalle ei ole rekisteriä, josta työkalu voisi hakea tietoja — profiili täytetään käsin.",
    "app.69": "Tälle maalle ei ole rekisteriä, josta työkalu voisi hakea tietoja. Napsauta kytkeäksesi offline-tilan päälle.",
    "app.73": " · tuloslaskelma kaavan mukaan ",
    "app.74": "<div class=\"mt-2 tekst-uwaga\">Rekisteritiedot eivät osoita mitään digitaalisen infrastruktuurin toimialan roolia. Valitse roolit käsin alta.</div>",
    "app.8": "Merkintä sähköisen viestinnän palveluntarjoajien rekisterissä vahvistettu",
    "app.progDostawcy": "",
    "app.przyklad.adres": "Esimerkkikatu 1, 00100 Kaupunki",
    "app.przyklad.forma": "Osakeyhtiö",
    "app.przyklad.nazwa": "Esimerkkioperaattori Oy",
    "app.statusVat": " · ALV-asema: ",
    "dashboard.1": "Ilmoitettujen roolien ja koon perusteella toimija ei ole keskeinen eikä tärkeä toimija direktiivin (EU) 2022/2555 3 artiklassa tarkoitetulla tavalla. Tarkista profiili, jos tulos poikkeaa odotetusta.",
    "dashboard.113": "Usein kysytyt kysymykset",
    "dashboard.12": "— {p0}; määräaika saattaa osaksi kansallista lainsäädäntöä umpeutui {p2}",
    "dashboard.123": "NIS 2 -direktiivi",
    "dashboard.30": "Keskeisten ja tärkeiden toimijoiden luettelo",
    "dashboard.4": "— suoraan sovellettava {p0} alkaen kaikissa jäsenvaltioissa ilman täytäntöönpanoa",
    "dashboard.42": "Kiinteän määrän vaihtoehto: {p0}",
    "dashboard.45": "Direktiivin 32 artiklan 7 kohdan kriteerit:",
    "dashboard.46": "Yhteensä",
    "dashboard.49": "Toimija harjoittaa sähköisen viestinnän toimintaa — johtavan henkilön vastuun määrää kansallinen laki",
    "dashboard.50": "",
    "dashboard.51": "",
    "dashboard.53": "Uhkasakko päätöksen täytäntöönpanon viivästymisestä: {p0}–{p1} € päivässä ({p2})",
    "dashboard.54": "Törkeä tapaus: enintään {p0} € ({p1})",
    "dashboard.57": "({p0}). Mistä alkaen kansallinen viranomainen voi määrätä sakkoja, määrää direktiivin täytäntöönpanolaki — tämä moduuli ei tunne sitä. Toteutusvelvoitteet seuraavat kansallisesta laista sen voimaantulopäivästä.",
    "dashboard.65": "({p0}). Mistä alkaen kansallinen viranomainen voi määrätä sakkoja, määrää direktiivin täytäntöönpanolaki — tämä moduuli ei tunne sitä. Taloudellista riskiä ei siksi ole tässä päivätty, mutta toteutusvelvoitteet seuraavat kansallisesta laista sen voimaantulopäivästä.",
    "dashboard.83": "Sähköisen viestinnän toiminta — kynnysarvot määrää kansallinen laki.",
    "dashboard.84": "Asetusta (EU) 2024/2690 ei sovelleta yleisten sähköisten viestintäverkkojen ja -palvelujen tarjoajiin. Niiden osalta merkittävän poikkeaman kynnysarvot määrää kansallinen laki (direktiivin 23 artiklan 11 kohta) — tämä moduuli ei tunne niitä, joten se ei ilmoita lukuja.",
    "dashboard.terminRejestracji": "Rekisteröintitietojen toimittamisen määräajan määrää kansallinen laki (direktiivin 3 artiklan 4 kohta). 27 artiklan 1 kohdan mukaiset tarjoajat — DNS-palveluntarjoajat, aluetunnusrekisterit, pilvipalvelujen, datakeskuspalvelujen, sisällönjakeluverkkojen, hallinnoitujen palvelujen ja hallinnoitujen tietoturvapalvelujen tarjoajat — toimittavat tietonsa ENISAn rekisteriin: alun perin 17.1.2025 mennessä ja jokaisen muutoksen ilman aiheetonta viivytystä.",
    "html.1": "ITORO — NIS 2 -direktiivin (EU) 2022/2555 vaatimustenmukaisuuden arviointi",
    "html.10": "NIS 2 -direktiivin vaatimustenmukaisuuden arviointi — yhteinen moduuli",
    "html.100": "Tilinpäätöksen lukeminen toimii vain maille, joilla on kansallisen lain moduuli. Tälle maalle syötät tilikauden <strong>liikevaihdon</strong> käsin — sakon suuruus riippuu siitä.",
    "html.102": "Rekisteritietojen automaattinen haku toimii vain maille, joilla on kansallisen lain moduuli. Roolit ja yrityksen koon ilmoitat käsin.",
    "html.11": "Direktiivi (EU) 2022/2555 (NIS 2) edellyttää saattamista osaksi kansallista lainsäädäntöä. Arviointi kattaa suoraan direktiivistä seuraavat velvoitteet ja suoraan sovellettavan komission täytäntöönpanoasetuksen (EU) 2024/2690 — siltä osin kuin ne koskevat toimijaa.",
    "html.23": "liikevaihdon ja koon syötät käsin — yhteinen moduuli ei tee hakuja kansallisiin rekistereihin",
    "html.33": "Euroopan parlamentin ja neuvoston direktiivi (EU) 2022/2555, annettu 14. joulukuuta 2022 (NIS 2)",
    "html.33a": "{p0} — direktiivin täytäntöönpaneva kansallinen säädös; sen vaatimuksia tämä moduuli ei vielä arvioi",
    "html.33b": "maa ei ole vielä säätänyt täytäntöönpanevaa säädöstä — arviointi perustuu unionin oikeuteen",
    "html.35": "hallintoelimen velvoitteet — direktiivin 20 artikla",
    "html.36": "Työkalu on tarkoitettu itsearviointiin. Se ei ole tarkastus eikä oikeudellista neuvontaa.",
    "html.40": "yhteinen moduuli ei muodosta lainkaan lähteviä yhteyksiä — se ei tee hakuja rekistereihin",
    "html.59": "Tilinpäätökset",
    "html.60": "Tilinpäätöksen lukeminen on käytettävissä vain maille, joilla on kansallisen lain moduuli. Tälle maalle syötät liikevaihdon ja henkilöstömäärän käsin.",
    "html.62": "Haku rekisteristä",
    "html.63": "yritysrekisterit ovat kansallisia — yhteinen moduuli ei tunne niitä",
    "html.64": "roolit ja yrityksen koon ilmoitat käsin",
    "html.66": "Toimijan tunnistenumero",
    "html.68": "Rekisteritietojen automaattinen haku toimii vain maille, joilla on kansallisen lain moduuli.",
    "html.76": "Vuotuinen liikevaihto (€)",
    "html.78": "Sähköisen viestinnän toiminnan liikevaihto (€)",
    "html.79": "Kenttä koskee yleisten sähköisten viestintäverkkojen tai -palvelujen tarjoajia. Kansalliset kynnysarvot määrää jäsenvaltion laki.",
    "html.80": "Johtajan kuukausipalkkio (€)",
    "html.82": "Valuuttakurssi",
    "html.83": "Direktiivin sakkojen enimmäismäärät on ilmaistu euroina. Muuntamisen kansalliseen valuuttaan ja kurssin määrää kansallinen laki — tässä määrät on esitetty euroina ilman muuntamista.",
    "html.84": "Asema johtuu yksinomaan sidosyritysten tietojen yhdistämisestä, ja toimijan tietojärjestelmä on riippumaton (direktiivin johdanto-osan 16 kappale — soveltamisesta päättää kansallinen laki)",
    "html.85": "Toimija toimii kansallisen turvallisuuden, yleisen turvallisuuden, puolustuksen tai lainvalvonnan alalla (direktiivin 2 artiklan 7 kohta)",
    "html.91": "Euroopan parlamentin ja neuvoston direktiivin (EU) 2022/2555 (NIS 2) ja komission täytäntöönpanoasetuksen (EU) 2024/2690 vaatimustenmukaisuuden arviointi — yhteinen moduuli maille, joiden kansallisen lain moduuli ei ole vielä valmis.",
    "html.94": "onko toimija <strong>keskeinen</strong>, <strong>tärkeä</strong> vai direktiivin soveltamisalan ulkopuolella",
    "html.daneZeSprawozdania": "nimi, tunnistenumero, kotipaikan osoite",
    "html.rejestrMozliwy": "Rekisteri {p0} on julkinen ja maksuton — sen lukeminen voidaan lisätä työkaluun; otamme vastaan pull requesteja (ks. README).",
    "html.tytulNaglowka": "NIS 2 -direktiivin vaatimustenmukaisuuden arviointi",
    "html.zrodlaRecznie": "Tämä moduuli ei tunne maanne rekistereitä — täyttäkää profiili käsin. Vuotuinen liikevaihto määrää sakon enimmäismäärän, joten merkitkää se tarkasti.",
    "klasyfikacja.10": "direktiivin (EU) 2022/2555 3 artiklan 1 kohdan c alakohta (yleisten sähköisten viestintäverkkojen tai yleisesti saatavilla olevien sähköisten viestintäpalvelujen tarjoaja, joka on vähintään keskisuuri yritys)",
    "klasyfikacja.11": "direktiivin (EU) 2022/2555 3 artiklan 2 kohta yhdessä 2 artiklan 2 kohdan a alakohdan i alakohdan kanssa (yleisten sähköisten viestintäverkkojen tai -palvelujen tarjoaja, joka on mikro- tai pieni yritys)",
    "klasyfikacja.12": "direktiivin (EU) 2022/2555 3 artiklan 1 kohdan a alakohta (hallinnoitujen tietoturvapalvelujen tarjoaja, joka ylittää keskisuuren yrityksen enimmäisrajat)",
    "klasyfikacja.13": "Mikro- ja pienet yritykset eivät kuulu direktiivin soveltamisalaan tämän roolin perusteella (2 artiklan 1 kohta a contrario).",
    "klasyfikacja.15": "direktiivin (EU) 2022/2555 3 artiklan 1 kohdan b alakohta (hyväksytty luottamuspalvelun tarjoaja) — yrityksen koosta riippumatta",
    "klasyfikacja.16": "direktiivin (EU) 2022/2555 3 artiklan 2 kohta yhdessä 2 artiklan 2 kohdan a alakohdan ii alakohdan kanssa (muu kuin hyväksytty luottamuspalvelun tarjoaja, joka on mikro-, pieni tai keskisuuri yritys)",
    "klasyfikacja.18": "direktiivin (EU) 2022/2555 3 artiklan 2 kohta (aluetason julkishallinnon toimija, jos jäsenvaltio niin säätää — 2 artiklan 2 kohdan f alakohdan ii alakohta)",
    "klasyfikacja.19": "direktiivin (EU) 2022/2555 3 artiklan 1 kohdan f alakohta (keskushallinnon tason julkishallinnon toimija — 2 artiklan 2 kohdan f alakohdan i alakohta)",
    "klasyfikacja.2": "Ennakko- ja jälkivalvonta (direktiivin (EU) 2022/2555 32 artikla).",
    "klasyfikacja.20": "direktiivin (EU) 2022/2555 3 artiklan 2 kohta (aluetason julkishallinnon toimija — 2 artiklan 2 kohdan f alakohdan ii alakohta)",
    "klasyfikacja.21": "Paikallistason julkishallinnon toimijoiden velvoitteiden laajuuden määrää kansallinen laki (direktiivin 2 artiklan 5 kohdan a alakohta).",
    "klasyfikacja.22": "Jäsenvaltio voi vapauttaa toimijat, jotka toimivat kansallisen turvallisuuden, yleisen turvallisuuden, puolustuksen tai lainvalvonnan alalla (direktiivin 2 artiklan 7 kohta). Vapautus ei toimi itsestään — tarkista arvioinnin tulos kansallisen lain perusteella.",
    "klasyfikacja.23": "Toimija täyttää sekä keskeisen että tärkeän toimijan kriteerit. Se on keskeinen toimija (direktiivin 3 artiklan 1 kohta), ja tiukemmat vaatimukset koskevat kaikkea direktiivin soveltamisalaan kuuluvaa toimintaa.",
    "klasyfikacja.25": "Toimija on keskeinen, joten siihen sovelletaan direktiivin 21 artiklan 2 kohdan mukaista toimenpiteiden täyttä luetteloa sekä ennakko- ja jälkivalvontaa — arviointi kattaa koko kysymyssarjan.",
    "klasyfikacja.26": "Tärkeänä toimijana teihin sovelletaan samaa 21 artiklan 2 kohdan mukaista toimenpideluetteloa, mutta vain jälkivalvontaa (33 artikla). Sakon enimmäismäärä on alempi: 7 milj. € tai 1,4 % liikevaihdosta (34 artiklan 5 kohta). Julkisten toimijoiden helpotuksia voi säätää kansallinen laki — tämä moduuli ei tunne niitä.",
    "klasyfikacja.28": "Julkishallinnon toimijoiden velvoitteet seuraavat direktiivin 2 artiklan 2 kohdan f alakohdasta; niiden tarkan laajuuden, myös paikallistason ja oppilaitosten osalta, määrää kansallinen laki (2 artiklan 5 kohta).",
    "klasyfikacja.29": "On ilmoitettu, että toimijan asema johtuu yksinomaan sidos- tai omistusyhteysyritysten tietojen yhdistämisestä ja että toimijan tietojärjestelmä on riippumaton. Direktiivi sallii tällaisen poissulkemisen (johdanto-osan 16 kappale), mutta siitä päättää kansallinen laki — moduuli hyväksyy poissulkemisen, joka on kuitenkin tarkistettava jäsenvaltion lain perusteella ja dokumentoitava.",
    "klasyfikacja.4": "Vain jälkivalvonta — kun on näyttöä, viitteitä tai tietoa rikkomuksesta (direktiivin (EU) 2022/2555 33 artikla).",
    "klasyfikacja.5": "Direktiivin soveltamisalan ulkopuolella",
    "klasyfikacja.6": "Ilmoitetun roolin perusteella direktiivistä (EU) 2022/2555 ei seuraa velvoitteita.",
    "klasyfikacja.7": "direktiivin (EU) 2022/2555 3 artiklan 1 kohdan a alakohta (liitteessä I tarkoitetun tyyppinen toimija, joka ylittää keskisuuren yrityksen enimmäisrajat)",
    "klasyfikacja.8": "direktiivin (EU) 2022/2555 3 artiklan 2 kohta (liitteessä I tarkoitetun tyyppinen toimija, joka täyttää keskisuuren yrityksen kriteerit)",
    "klasyfikacja.9": "Mikro- ja pienet yritykset eivät kuulu direktiivin soveltamisalaan tämän roolin perusteella (2 artiklan 1 kohta a contrario).",
    "kreator.10": "Syötä edellisen vuoden liikevaihto käsin.",
    "kreator.35": "<span class=\"text-secondary\">Tilinpäätösten lukeminen ei ole käytettävissä tälle maalle.</span>",
    "kreator.37": "Tilinpäätösten lukeminen ei ole käytettävissä tälle maalle — syötä liikevaihto käsin.",
    "kreator.56": "Kyllä — EU-asetusta sovelletaan suoraan 7.11.2024 alkaen kaikissa jäsenvaltioissa, eikä sillä ole siirtymäaikaa. Sen perustana on",
    "kreator.57": ", jolla komissio valtuutettiin vahvistamaan tekniset ja menetelmälliset vaatimukset asetuksen 3 artiklan 1 kohdassa tarkoitetuille tarjoajille. Direktiivin täytäntöönpanon määräaika umpeutui",
    "kreator.58": ", ja mistä alkaen kansallinen viranomainen voi määrätä sakkoja, määrää kansallinen laki. Liitteen tekniset vaatimukset (jaksot 6 ja 9–13) ovat sitovia nykyisessä muodossaan — ne eivät odota täsmennystä. Vain vaatimuksista, joissa on lauseke ”tarvittaessa”, voi poiketa, ja vain dokumentoidulla perustelulla.",
    "kreator.9": "Tilinpäätökset →",
    "kreator.przepisReg2690": "direktiivin (EU) 2022/2555 21 artiklan 5 kohta",
    "kreator.terminReg2690": "17.10.2024",
    "punktacja.10": "Julkiset toimijat",
    "punktacja.4": "NIS 2 -direktiivi — 21 artikla",
    "punktacja.5": "NIS 2 -direktiivi — muodolliset velvoitteet",
    "punktacja.8": "Sähköinen viestintä",
    "punktacja.9": "NIS 2 -direktiivi — julkiset toimijat",
    "punktacja.skrotKsc": "NIS 2",
    "punktacja.skrotPke": "televiestintä",
    "ue.cyt.akapit": "{p0} alakohta",
    "ue.cyt.art": "{p0} artiklan",
    "ue.cyt.drugi": "toinen",
    "ue.cyt.dyr": "direktiivin (EU) 2022/2555 {p0}",
    "ue.cyt.i": "ja",
    "ue.cyt.laczenie": " ",
    "ue.cyt.lit": "{p0} alakohta",
    "ue.cyt.litery": "",
    "ue.cyt.pkt": "{p0} kohta",
    "ue.cyt.rozdzielacz": "; ",
    "ue.cyt.rozp": "asetuksen (EU) 2024/2690 {p0}",
    "ue.cyt.ust": "{p0} kohta",
    "ue.katalog.1": "Riskianalyysiä ja tietojärjestelmien turvallisuutta koskevat toimintaperiaatteet",
    "ue.katalog.10": "Poikkeamien käsittely",
    "ue.katalog.11": "Poikkeamien käsittelyllä tarkoitetaan toimia ja menettelyjä, joilla pyritään estämään, havaitsemaan, analysoimaan ja rajaamaan poikkeama tai reagoimaan siihen ja palautumaan siitä (6 artiklan 8 alakohta).",
    "ue.katalog.12": "Onko olemassa dokumentoitu poikkeamien käsittelymenettely, joka kattaa havaitsemisen, analysoinnin, rajaamisen, reagoinnin ja palautumisen?",
    "ue.katalog.13": "ISO/IEC 27001 A.5.24–A.5.26",
    "ue.katalog.14": "Mahdollistaako menettely merkittävän poikkeaman ilmoittamisen määräaikojen noudattamisen: ennakkovaroitus 24 tunnissa, poikkeamailmoitus 72 tunnissa, loppuraportti kuukaudessa?",
    "ue.katalog.15": "ISO/IEC 27001 A.5.24",
    "ue.katalog.16": "Onko toimijalla 23 artiklan 3 kohdan mukaiset kriteerit poikkeaman merkittäväksi katsomiselle: vakava toimintahäiriö tai taloudellinen tappio taikka huomattava haitta muille henkilöille?",
    "ue.katalog.17": "ISO/IEC 27001 A.5.25",
    "ue.katalog.18": "Kirjataanko poikkeamat, ja hyödynnetäänkö niiden käsittelystä saatuja oppeja toimenpiteiden parantamiseen?",
    "ue.katalog.19": "ISO/IEC 27001 A.5.27",
    "ue.katalog.2": "Toimenpiteet perustuvat kaikki vaaratekijät huomioivaan lähestymistapaan (21 artiklan 2 kohta). Niiden oikeasuhteisuutta arvioidaan ottaen huomioon riskialttiuden aste, toimijan koko sekä poikkeamien todennäköisyys ja vakavuus (21 artiklan 1 kohdan toinen alakohta).",
    "ue.katalog.20": "Toiminnan jatkuvuus ja kriisinhallinta",
    "ue.katalog.21": "Toiminnan jatkuvuus, kuten varmuuskopioiden hallinta ja palautuminen katastrofista, sekä kriisinhallinta.",
    "ue.katalog.22": "Onko olemassa toiminnan jatkuvuussuunnitelma, joka kattaa katastrofista palautumisen?",
    "ue.katalog.23": "ISO/IEC 27001 A.5.29–A.5.30",
    "ue.katalog.24": "Tehdäänkö varmuuskopiot, suojataanko ne ja testataanko niiden palautettavuus?",
    "ue.katalog.25": "ISO/IEC 27001 A.8.13",
    "ue.katalog.26": "Onko toimijalla kriisinhallintamenettelyt, joissa on määritellyt roolit ja viestintäkanavat?",
    "ue.katalog.27": "ISO/IEC 27001 A.5.29",
    "ue.katalog.28": "Testataanko jatkuvuus- ja palautumissuunnitelmat säännöllisesti ja dokumentoidaanko tulokset?",
    "ue.katalog.29": "ISO/IEC 27001 A.5.30",
    "ue.katalog.3": "Onko toimijalla dokumentoidut, hallintoelimen hyväksymät riskianalyysiä ja tietojärjestelmien turvallisuutta koskevat toimintaperiaatteet?",
    "ue.katalog.30": "Toimitusketjun turvallisuus",
    "ue.katalog.31": "Toimitusketjun turvallisuus, mukaan lukien toimijan ja sen suorien toimittajien tai palveluntarjoajien välisten suhteiden turvallisuusnäkökohdat. Toimija ottaa huomioon kunkin toimittajan erityiset haavoittuvuudet sekä sen tuotteiden ja kyberturvallisuuskäytäntöjen yleisen laadun (21 artiklan 3 kohta).",
    "ue.katalog.32": "Pitääkö toimija luetteloa suorista toimittajista ja palveluntarjoajista sekä arviota niiden merkityksestä verkkojen ja järjestelmien turvallisuudelle?",
    "ue.katalog.33": "ISO/IEC 27001 A.5.19",
    "ue.katalog.34": "Otetaanko toimittajia koskevia toimenpiteitä valittaessa huomioon kunkin erityiset haavoittuvuudet sekä niiden kyberturvallisuus- ja turvallisen kehityksen käytäntöjen laatu?",
    "ue.katalog.35": "ISO/IEC 27001 A.5.19, A.5.21",
    "ue.katalog.36": "Sisältävätkö toimittajasopimukset turvallisuusvaatimuksia ja velvoitteen ilmoittaa poikkeamista ja haavoittuvuuksista?",
    "ue.katalog.37": "ISO/IEC 27001 A.5.20",
    "ue.katalog.38": "Ottaako toimija huomioon 22 artiklassa tarkoitettujen kriittisten toimitusketjujen koordinoitujen turvallisuusriskinarviointien tulokset?",
    "ue.katalog.39": "ISO/IEC 27001 A.5.21",
    "ue.katalog.4": "ISO/IEC 27001 kohdat 5.2, 6.1.2",
    "ue.katalog.40": "Turvallisuus järjestelmien hankinnassa, kehittämisessä ja ylläpidossa",
    "ue.katalog.41": "Turvallisuus verkko- ja tietojärjestelmien hankinnassa, kehittämisessä ja ylläpidossa, mukaan lukien haavoittuvuuksien käsittely ja julkistaminen.",
    "ue.katalog.42": "Määritelläänkö turvallisuusvaatimukset ennen järjestelmän hankintaa tai kehittämisen aloittamista ja tarkistetaanko ne ennen käyttöönottoa?",
    "ue.katalog.43": "ISO/IEC 27001 A.8.25–A.8.29",
    "ue.katalog.44": "Onko olemassa haavoittuvuuksien käsittelyprosessi: tunnistaminen, arviointi, korjaaminen määräajassa?",
    "ue.katalog.45": "ISO/IEC 27001 A.8.8",
    "ue.katalog.46": "Onko toimijalla haavoittuvuuksien julkistamismenettely, mukaan lukien kanava kolmansien osapuolten ilmoitusten vastaanottamiseen?",
    "ue.katalog.47": "Käsitelläänkö järjestelmämuutokset hallitussa muutoksenhallintaprosessissa, johon sisältyy turvallisuusvaikutusten arviointi?",
    "ue.katalog.48": "ISO/IEC 27001 A.8.32",
    "ue.katalog.49": "Toimenpiteiden vaikuttavuuden arviointi",
    "ue.katalog.5": "Kattaako riskianalyysi kaikki verkko- ja tietojärjestelmiin ja niiden fyysiseen ympäristöön kohdistuvat vaaratekijät, ei vain kyberuhkia?",
    "ue.katalog.50": "Toimintaperiaatteet ja menettelyt kyberturvallisuusriskien hallintatoimenpiteiden vaikuttavuuden arvioimiseksi.",
    "ue.katalog.51": "Onko olemassa dokumentoitu toimenpiteiden vaikuttavuuden arviointiperiaate, jossa määritellään laajuus, tiheys ja menetelmät?",
    "ue.katalog.52": "ISO/IEC 27001 kohta 9.1",
    "ue.katalog.53": "Tehdäänkö vaikuttavuusarvioinnit säännöllisesti ja raportoidaanko niiden tulokset hallintoelimelle?",
    "ue.katalog.54": "ISO/IEC 27001 kohdat 9.2–9.3",
    "ue.katalog.55": "Johtavatko havaitut puutteet dokumentoituihin korjaaviin toimenpiteisiin, joilla on vastuuhenkilö ja määräaika?",
    "ue.katalog.56": "ISO/IEC 27001 kohta 10.1",
    "ue.katalog.57": "Kyberhygienia ja koulutus",
    "ue.katalog.58": "Kyberhygienian peruskäytännöt ja kyberturvallisuuskoulutus. Hallintoelimen jäsenet osallistuvat säännöllisesti koulutukseen (20 artiklan 2 kohta).",
    "ue.katalog.59": "Soveltaako toimija kyberhygienian peruskäytäntöjä: päivitykset, salasanojen hallinta, oikeuksien rajoittaminen, suojaus haittaohjelmilta?",
    "ue.katalog.6": "ISO/IEC 27001 kohta 6.1.2",
    "ue.katalog.60": "ISO/IEC 27001 A.8.7, A.8.8",
    "ue.katalog.61": "Saavatko työntekijät rooliinsa räätälöityä kyberturvallisuuskoulutusta ja dokumentoidaanko osallistuminen?",
    "ue.katalog.62": "ISO/IEC 27001 A.6.3",
    "ue.katalog.63": "Osallistuvatko hallintoelimen jäsenet säännöllisesti koulutukseen, jonka avulla he voivat tunnistaa riskejä ja arvioida riskienhallintakäytäntöjä?",
    "ue.katalog.64": "ISO/IEC 27001 kohta 7.2",
    "ue.katalog.65": "Kryptografia ja salaus",
    "ue.katalog.66": "Kryptografian ja tarvittaessa salauksen käyttöä koskevat toimintaperiaatteet ja menettelyt.",
    "ue.katalog.67": "Onko olemassa kryptografiaperiaate, jossa määritellään, mitkä tiedot ja kanavat salataan ja millä algoritmeilla?",
    "ue.katalog.68": "ISO/IEC 27001 A.8.24",
    "ue.katalog.69": "Hallitaanko salausavaimia koko elinkaaren ajan: luonti, jakelu, säilytys, kierrätys, käytöstä poisto?",
    "ue.katalog.7": "Otetaanko toimenpiteiden valinnassa huomioon uusin kehitys, asiaankuuluvat eurooppalaiset ja kansainväliset standardit sekä toteutuskustannukset?",
    "ue.katalog.70": "Henkilöstö, pääsynhallinta ja omaisuudenhallinta",
    "ue.katalog.71": "Henkilöstöturvallisuus, pääsynhallinnan periaatteet ja omaisuudenhallinta.",
    "ue.katalog.72": "Pitääkö toimija ajantasaista omaisuusluetteloa, jossa on nimetyt omistajat ja luokitus?",
    "ue.katalog.73": "ISO/IEC 27001 A.5.9, A.5.12",
    "ue.katalog.74": "Onko olemassa vähimpien oikeuksien periaatteeseen perustuva pääsynhallintaperiaate, johon kuuluu oikeuksien säännöllinen tarkistus?",
    "ue.katalog.75": "ISO/IEC 27001 A.5.15, A.5.18",
    "ue.katalog.76": "Sovelletaanko rekrytoinnissa, tehtävän vaihtuessa ja työntekijän lähtiessä turvallisuusmenettelyjä, mukaan lukien oikeuksien peruuttaminen ja omaisuuden palautus?",
    "ue.katalog.77": "ISO/IEC 27001 A.6.1–A.6.5",
    "ue.katalog.78": "Onko etuoikeutettu pääsy rajoitettu, lokitettu ja tarkistettu?",
    "ue.katalog.79": "ISO/IEC 27001 A.8.2",
    "ue.katalog.8": "ISO/IEC 27001 kohta 6.1.3",
    "ue.katalog.80": "Monivaiheinen todennus ja suojattu viestintä",
    "ue.katalog.81": "Tarvittaessa — monivaiheinen tai jatkuva todennus, suojattu puhe-, video- ja tekstiviestintä sekä suojatut hätäviestintäjärjestelmät toimijan sisällä.",
    "ue.katalog.82": "Käytetäänkö monivaiheista tai jatkuvaa todennusta siellä, missä riskianalyysi sitä edellyttää, erityisesti etäkäytössä ja etuoikeutetuissa tileissä?",
    "ue.katalog.83": "ISO/IEC 27001 A.8.5",
    "ue.katalog.84": "Onko työkäytössä oleva puhe-, video- ja tekstiviestintä suojattu?",
    "ue.katalog.85": "ISO/IEC 27001 A.8.20",
    "ue.katalog.86": "Onko toimijalla suojattu sisäinen hätäviestintäjärjestelmä, joka on riippumaton perusinfrastruktuurista?",
    "ue.katalog.9": "Onko turvallisuustaso dokumentoitu riskiin nähden asianmukaiseksi perustelulla, jossa otetaan huomioon toimijan koko sekä poikkeamien yhteiskunnalliset ja taloudelliset vaikutukset?",
    "ue.kierownictwo.1": "Keskeisen tai tärkeän toimijan hallintoelin — osakeyhtiössä hallitus. Direktiivi ei määrittele käsitettä; sen laajuus kussakin maassa seuraa kansallisesta laista.",
    "ue.kierownictwo.10": "Määrittää toimijan asema ja huolehtia rekisteröinnistä",
    "ue.kierownictwo.11": "Sen määrittäminen, onko toimija keskeinen vai tärkeä, ja rekisteröintitietojen toimittaminen toimivaltaiselle viranomaiselle. Menettelyn ja määräajan määrää kansallinen laki.",
    "ue.kierownictwo.12": "Ottaa käyttöön riskianalyysi ja turvallisuusperiaatteet",
    "ue.kierownictwo.13": "Kaikki vaaratekijät huomioivaan lähestymistapaan perustuvat toimenpiteet, jotka ovat oikeassa suhteessa riskialttiuteen, toimijan kokoon ja poikkeamien vakavuuteen.",
    "ue.kierownictwo.14": "Järjestää poikkeamien käsittely ja ilmoittaminen",
    "ue.kierownictwo.15": "Poikkeamien käsittelymenettely ja kyky noudattaa 24 tunnin, 72 tunnin ja yhden kuukauden määräaikoja.",
    "ue.kierownictwo.16": "24 h / 72 h / kuukausi havaitsemisesta",
    "ue.kierownictwo.17": "Varmistaa toiminnan jatkuvuus",
    "ue.kierownictwo.18": "Jatkuvuussuunnitelma, varmuuskopiot, katastrofista palautuminen, kriisinhallinta.",
    "ue.kierownictwo.19": "Saattaa toimitusketju kuntoon",
    "ue.kierownictwo.2": "Hallintoelimen vastuu ei vaikuta julkisten laitosten ja virkamiesten vastuuta koskeviin kansallisiin sääntöihin (20 artiklan 1 kohdan toinen alakohta).",
    "ue.kierownictwo.20": "Toimittajaluettelo, niiden haavoittuvuuksien ja käytäntöjen arviointi, turvallisuusvaatimukset sopimuksissa.",
    "ue.kierownictwo.21": "Ottaa käyttöön pääsynhallinta ja omaisuudenhallinta",
    "ue.kierownictwo.22": "Omaisuusluettelo, vähimpien oikeuksien periaate, oikeuksien tarkistukset, monivaiheinen todennus siellä, missä riski sitä edellyttää.",
    "ue.kierownictwo.23": "Mitata toimenpiteiden vaikuttavuutta",
    "ue.kierownictwo.24": "Vaikuttavuuden arviointiperiaatteet ja -menettelyt, säännölliset tarkistukset, korjaavat toimenpiteet.",
    "ue.kierownictwo.25": "Hyväksyä",
    "ue.kierownictwo.26": "kyberturvallisuusriskien hallintatoimenpiteet (20 artiklan 1 kohta)",
    "ue.kierownictwo.27": "riskianalyysiä ja järjestelmien turvallisuutta koskevat toimintaperiaatteet",
    "ue.kierownictwo.28": "toteutuksen budjetti ja roolit",
    "ue.kierownictwo.29": "Valvoa",
    "ue.kierownictwo.3": "Poistaako velvoitteiden uskominen toiselle henkilölle vastuun, päättää kansallinen laki. Puolassa ei poista (kansallisesta kyberturvallisuusjärjestelmästä annetun lain 8c artiklan 3 kohta).",
    "ue.kierownictwo.30": "hyväksyttyjen toimenpiteiden toteutusta (20 artiklan 1 kohta)",
    "ue.kierownictwo.31": "vaikuttavuusarvioinnin tuloksia (21 artiklan 2 kohdan f alakohta)",
    "ue.kierownictwo.32": "poikkeamien ilmoittamisen määräaikojen noudattamista (23 artikla)",
    "ue.kierownictwo.33": "Dokumentoida",
    "ue.kierownictwo.34": "hyväksymispäätökset ja tarkistukset",
    "ue.kierownictwo.35": "osallistuminen koulutukseen (20 artiklan 2 kohta)",
    "ue.kierownictwo.36": "Hallintoelimen jäsen",
    "ue.kierownictwo.37": "toimenpiteiden hyväksyminen, valvonta, päätökset, budjetti",
    "ue.kierownictwo.38": "Projektipäällikkö",
    "ue.kierownictwo.39": "toteutuksen koordinointi, aikataulu, tilanne ja todisteet",
    "ue.kierownictwo.4": "Hyväksyä kyberturvallisuusriskien hallintatoimenpiteet",
    "ue.kierownictwo.40": "IT / kyberturvallisuus",
    "ue.kierownictwo.41": "riskianalyysi, tekniset toimenpiteet, poikkeamien käsittely",
    "ue.kierownictwo.42": "Lakiasiat / vaatimustenmukaisuus",
    "ue.kierownictwo.5": "Hallintoelin hyväksyy 21 artiklan noudattamiseksi toteutetut toimenpiteet. Se on elimen, ei IT-osaston päätös — ilman sitä toimenpiteillä ei ole valtuutusta.",
    "ue.kierownictwo.6": "Valvoa toimenpiteiden toteutusta",
    "ue.kierownictwo.7": "Toteutuksen valvonta on hallintoelimen velvoite. Toteutuksen voi delegoida, valvontaa ei.",
    "ue.kierownictwo.8": "Osallistua säännöllisesti koulutukseen",
    "ue.kierownictwo.9": "Hallintoelimen jäsenet osallistuvat säännöllisesti koulutukseen saadakseen riittävät tiedot riskien tunnistamiseen sekä riskienhallintakäytäntöjen ja niiden vaikutusten arviointiin toimijan palveluihin.",
    "ue.kierownictwo.daneRejestracyjne": "rekisteröintitiedot ja niiden päivittäminen (3 artiklan 4 ja 5 kohta)",
    "ue.meta.1": "Prosenttivaihtoehto on määräävä: {p0} % liikevaihdosta on enemmän kuin {p1} milj. €.",
    "ue.meta.10": "Direktiivi ei aseta velvoitteita yrityksille suoraan — sen tekee kansallinen laki, joka jäsenvaltion oli määrä antaa 17.10.2024 mennessä. Tämä moduuli näyttää vaatimukset direktiivin sanamuodossa, koska valitun maan kansallisen lain moduuli ei ole vielä valmis tai maa ei ole pannut direktiiviä täytäntöön.",
    "ue.meta.11": "Direktiivin mukaiset velvoitteet",
    "ue.meta.12": "Toimijoiden luettelo — 17.4.2025 mennessä",
    "ue.meta.13": "Jäsenvaltioiden oli laadittava keskeisten ja tärkeiden toimijoiden luettelo 17.4.2025 mennessä ja vaadittava toimijoita toimittamaan rekisteröintitiedot.",
    "ue.meta.14": "Asetus (EU) 2024/2690",
    "ue.meta.15": "Suoraan sovellettava 7.11.2024 alkaen",
    "ue.meta.16": "Täytäntöönpanoasetusta sovelletaan suoraan kaikissa jäsenvaltioissa direktiivin täytäntöönpanon tilasta riippumatta. Se koskee sen 1 artiklassa lueteltuja toimijoita: DNS-, aluetunnus-, pilvi-, datakeskus-, sisällönjakeluverkko-, hallinnoitujen palvelujen ja luottamuspalvelujen tarjoajia.",
    "ue.meta.17": "asetuksen (EU) 2024/2690 16 artikla",
    "ue.meta.18": "Vähintään 10 000 000 € tai vähintään 2 % yrityksen edellisen tilikauden maailmanlaajuisesta vuotuisesta kokonaisliikevaihdosta — sovelletaan suurempaa. Tämä on vähimmäisenimmäismäärä: kansallinen laki voi korottaa sitä.",
    "ue.meta.19": "Vähintään 7 000 000 € tai 1,4 % maailmanlaajuisesta vuotuisesta kokonaisliikevaihdosta — sovelletaan suurempaa. Vähimmäisenimmäismäärä.",
    "ue.meta.2": "Kiinteä määrä on määräävä: {p0} milj. € on enemmän kuin {p1} % liikevaihdosta.",
    "ue.meta.20": "Direktiivissä ei säädetä erillisestä sakosta törkeästä rikkomuksesta — se on joidenkin jäsenvaltioiden kansallisen lain rakennelma.",
    "ue.meta.21": "Jäsenvaltiot voivat säätää uhkasakoista rikkomuksen lopettamiseen pakottamiseksi. Määrän vahvistaa kansallinen laki.",
    "ue.meta.22": "Hallintoelin hyväksyy riskienhallintatoimenpiteet, valvoo niiden toteutusta ja voi joutua vastuuseen 21 artiklan rikkomisesta. Tämän vastuun säännöt ja laajuuden määrää kansallinen laki.",
    "ue.meta.23": "Hallintoelin hyväksyy kyberturvallisuusriskien hallintatoimenpiteet (20 artiklan 1 kohta).",
    "ue.meta.24": "Hallintoelin valvoo näiden toimenpiteiden toteutusta (20 artiklan 1 kohta).",
    "ue.meta.25": "Hallintoelimen jäsenet osallistuvat säännöllisesti koulutukseen (20 artiklan 2 kohta).",
    "ue.meta.26": "Keskeisen toimijan osalta viranomainen voi pyytää väliaikaista kieltoa hoitaa johtotehtäviä (32 artiklan 5 kohdan b alakohta).",
    "ue.meta.27": "Vähimmäisenimmäismäärän määrää direktiivi",
    "ue.meta.28": "Verrataan kahta arvoa: kiinteää euromäärää ja prosenttiosuutta yrityksen edellisen tilikauden maailmanlaajuisesta vuotuisesta kokonaisliikevaihdosta. Suurempi niistä on yläraja, josta jäsenvaltion on vähintään säädettävä. Kansallinen laki voi korottaa sitä.",
    "ue.meta.29": "Määrän enimmäismäärän rajoissa vahvistaa kansallinen viranomainen",
    "ue.meta.3": "Direktiivin enimmäismäärä ylittää toimijan vuotuisen liikevaihdon {p0}-kertaisesti. 34 artiklan 1 kohta edellyttää, että sakko on oikeassa suhteessa yksittäistapauksen olosuhteisiin — kyseessä on yläraja, ei odotettu sakko.",
    "ue.meta.30": "Sakon on oltava tehokas, oikeasuhteinen ja varoittava yksittäistapauksen olosuhteiden mukaan. Viranomainen ottaa huomioon vähintään 32 artiklan 7 kohdan kriteerit: rikkomuksen vakavuuden ja keston, aiemmat rikkomukset, aiheutuneen vahingon, tahallisuuden, korjaavat toimenpiteet ja yhteistyön.",
    "ue.meta.31": "Enimmäismäärä voi ylittää vuotuisen liikevaihdon moninkertaisesti — se on yläraja, ei odotettu määrä. Kansalliset vähimmäismäärät, uhkasakot ja sakkojen määräämismenettelyn määrää jäsenvaltion laki.",
    "ue.meta.32": "Päätettäessä hallinnollisen sakon määräämisestä ja sen määrästä otetaan kussakin yksittäistapauksessa asianmukaisesti huomioon vähintään 32 artiklan 7 kohdassa luetellut seikat.",
    "ue.meta.33": "rikkomuksen vakavuus ja rikottujen säännösten merkitys — vakavina pidetään joka tapauksessa: toistuvia rikkomuksia, merkittävien poikkeamien ilmoittamatta tai korjaamatta jättämistä, puutteiden korjaamatta jättämistä sitovien ohjeiden vastaisesti, tarkastusten tai seurannan estämistä, väärien tai törkeän epätarkkojen tietojen antamista",
    "ue.meta.34": "toimijan aiemmat merkitykselliset rikkomukset",
    "ue.meta.35": "aiheutunut aineellinen tai aineeton vahinko, mukaan lukien taloudelliset tappiot, vaikutukset muihin palveluihin ja vaikutusten kohteena olevien käyttäjien määrä",
    "ue.meta.36": "rikkomuksen tahallisuus tai tuottamuksellisuus",
    "ue.meta.37": "vahingon estämiseksi tai lieventämiseksi toteutetut toimenpiteet",
    "ue.meta.38": "hyväksyttyjen käytännesääntöjen tai sertifiointimekanismien noudattaminen",
    "ue.meta.39": "yhteistyön aste toimivaltaisten viranomaisten kanssa",
    "ue.meta.4": "Euroopan parlamentin ja neuvoston direktiivi (EU) 2022/2555 (NIS 2)",
    "ue.meta.40": "Direktiivissä ei nimenomaisesti säädetä sakosta luopumisesta — siitä, onko se mahdollista ja milloin, päättää kansallinen laki.",
    "ue.meta.41": "Tästä päivästä alkaen jäsenvaltioiden on sovellettava direktiivin täytäntöönpanevia kansallisia säännöksiä. Konkreettinen päivä, josta alkaen viranomainen voi määrätä sakon, seuraa kansallisesta laista.",
    "ue.meta.42": "NIS 2 -direktiivin voimaantulo",
    "ue.meta.43": "Kahdentenakymmenentenä päivänä virallisessa lehdessä julkaisemisesta.",
    "ue.meta.44": "Direktiivin täytäntöönpanon määräaika",
    "ue.meta.45": "Tähän päivään mennessä jäsenvaltioiden oli annettava ja julkaistava kansalliset säännökset.",
    "ue.meta.46": "Kansallisten säännösten soveltaminen ja NIS 1:n kumoaminen",
    "ue.meta.47": "Tästä päivästä alkaen jäsenvaltiot soveltavat täytäntöönpanosäännöksiä; direktiivi (EU) 2016/1148 kumotaan.",
    "ue.meta.48": "Asetuksen (EU) 2024/2690 soveltaminen",
    "ue.meta.49": "Täytäntöönpanoasetusta sovelletaan suoraan kahdennestakymmenennestä päivästä julkaisemisen jälkeen.",
    "ue.meta.5": "EUVL L 333, 27.12.2022",
    "ue.meta.50": "Keskeisten ja tärkeiden toimijoiden luettelo",
    "ue.meta.51": "Tähän päivään mennessä jäsenvaltiot laativat luettelon; toimijat toimittavat rekisteröintitiedot viranomaisille.",
    "ue.meta.52": "Komission ensimmäinen direktiivin uudelleentarkastelu",
    "ue.meta.53": "Komissio tarkastelee direktiivin toimivuutta ja antaa kertomuksen.",
    "ue.meta.54": "Ennakkovaroitus merkittävästä poikkeamasta",
    "ue.meta.55": "24 tuntia tiedon saamisesta",
    "ue.meta.56": "Ilmoitus merkittävästä poikkeamasta",
    "ue.meta.57": "72 tuntia tiedon saamisesta",
    "ue.meta.58": "Loppuraportti",
    "ue.meta.59": "kuukausi poikkeamailmoituksesta",
    "ue.meta.6": "Komission täytäntöönpanoasetus (EU) 2024/2690",
    "ue.meta.60": "Luottamuspalvelun tarjoajan poikkeamailmoitus",
    "ue.meta.61": "direktiivin (EU) 2022/2555 21 artiklan 5 kohta; asetuksen (EU) 2024/2690 1 ja 2 artikla",
    "ue.meta.62": "Ilman liikevaihtotietoja enimmäismäärä on direktiivin kiinteä määrä.",
    "ue.meta.63": "34 artiklan 4 ja 5 kohdan enimmäismäärät ovat vähimmäismääriä (”vähintään”) — kansallinen laki voi säätää korkeammista. Määrät euroina ilman muuntamista kansalliseen valuuttaan.",
    "ue.meta.64": "Jäsenvaltion toimivaltainen viranomainen",
    "ue.meta.65": "Hallintoelin voi joutua vastuuseen 21 artiklan rikkomisesta. Laajuuden ja menettelyn määrää kansallinen laki — tämä moduuli ei tunne niitä.",
    "ue.meta.66": "Johdon henkilökohtaisen vastuun laajuus seuraa kansallisesta laista. Puolassa se on enintään 300 % palkkiosta (kansallisesta kyberturvallisuusjärjestelmästä annetun lain 73a artiklan 4 kohta); muut jäsenvaltiot sääntelevät sitä toisin.",
    "ue.meta.7": "EUVL L, 2024/2690",
    "ue.meta.8": "Direktiivi (EU) 2022/2555",
    "ue.meta.9": "Täytäntöönpanon määräaika umpeutui 17.10.2024",
    "ue.moduly.1": "n. {p0} min",
    "ue.moduly.10": "Kymmenen osa-aluetta 21 artiklan 2 kohdan a–j alakohdasta: riskiperiaatteista monivaiheiseen todennukseen. Rikkomuksesta seuraa sakko 34 artiklan nojalla. Arviointi kypsyysasteikolla.",
    "ue.moduly.11": "Asetus 2024/2690 — hallinto ja prosessit",
    "ue.moduly.12": "Liitteen jaksot 1–5 ja 7–8: toimintaperiaatteet, riskienhallinta, poikkeamien käsittely, toiminnan jatkuvuus, toimitusketju, vaikuttavuuden arviointi, kyberhygienia. Suoraan sovellettava 7.11.2024 alkaen.",
    "ue.moduly.13": "Asetus 2024/2690 — tekniset vaatimukset",
    "ue.moduly.14": "Liitteen jaksot 6 ja 9–13: järjestelmien hankinta ja kehittäminen, kryptografia, henkilöstöturvallisuus, pääsynhallinta, omaisuudenhallinta, fyysinen ja ympäristöturvallisuus.",
    "ue.moduly.2": "n. {p0} h {p1} min",
    "ue.moduly.3": "n. {p0} h",
    "ue.moduly.4": "alle minuutti",
    "ue.moduly.5": "Nopea riskiarvio",
    "ue.moduly.6": "Läpileikkaavat kysymykset direktiivin kaikilta osa-alueilta. Kukin ratkaisee kokonaisen aiheryhmän. Mahdollistaa puutteiden laajuuden arvioinnin käymättä läpi koko kyselylomaketta.",
    "ue.moduly.7": "Direktiivin mukaiset velvoitteet",
    "ue.moduly.8": "Rekisteröintitiedot, poikkeamien ilmoittaminen 24 ja 72 tunnissa, hallintoelimen velvoitteet, valmius valvontaan. Tarkistettavissa asiakirjoista ilman teknistä analyysiä.",
    "ue.moduly.9": "Riskienhallintatoimenpiteet — 21 artiklan 2 kohta",
    "ue.obowiazki.1": "Rekisteröintitiedot toimijoiden luetteloon",
    "ue.obowiazki.10": "Merkittävien poikkeamien ilmoittaminen",
    "ue.obowiazki.11": "Toimija ilmoittaa merkittävistä poikkeamista CSIRT-toimijalle tai toimivaltaiselle viranomaiselle kolmessa vaiheessa: ennakkovaroitus, poikkeamailmoitus, loppuraportti. Määräajat alkavat kulua poikkeaman tietoon tulemisesta.",
    "ue.obowiazki.12": "Pystyykö toimija antamaan 24 tunnin kuluessa merkittävän poikkeaman tietoon tulemisesta ennakkovaroituksen, jossa ilmoitetaan, onko poikkeaman epäilty aiheutuneen lainvastaisista teoista ja voiko sillä olla rajat ylittäviä vaikutuksia?",
    "ue.obowiazki.13": "24 tuntia tiedon saamisesta",
    "ue.obowiazki.14": "Pystyykö toimija antamaan 72 tunnin kuluessa poikkeamailmoituksen, joka sisältää alustavan arvion vakavuudesta ja vaikutuksista sekä vaarantumisindikaattorit?",
    "ue.obowiazki.15": "72 tuntia tiedon saamisesta",
    "ue.obowiazki.16": "Toimittaako toimija viimeistään kuukauden kuluttua ilmoituksesta loppuraportin, joka sisältää poikkeaman kuvauksen, uhkatyypin, lieventämistoimenpiteet ja rajat ylittävät vaikutukset?",
    "ue.obowiazki.17": "kuukausi ilmoituksesta",
    "ue.obowiazki.18": "Tiedottaako toimija palvelujensa vastaanottajille merkittävistä poikkeamista, jotka voivat vaikuttaa kielteisesti näiden palvelujen tarjoamiseen?",
    "ue.obowiazki.19": "Tiedottaako toimija palvelujen vastaanottajille merkittävästä kyberuhkasta ja toimenpiteistä, joita vastaanottajat voivat toteuttaa?",
    "ue.obowiazki.2": "Jäsenvaltiot laativat keskeisten ja tärkeiden toimijoiden luettelon ja vaativat toimijoita toimittamaan rekisteröintitiedot. Menettelyn, määräajan ja portaalin määrää kansallinen laki.",
    "ue.obowiazki.20": "Jos toimija on luottamuspalvelun tarjoaja — ilmoittaako se merkittävistä poikkeamista 24 tunnin kuluessa tiedon saamisesta?",
    "ue.obowiazki.21": "koskee luottamuspalvelun tarjoajia",
    "ue.obowiazki.22": "Hallintoelin",
    "ue.obowiazki.23": "Hallintoelin hyväksyy riskienhallintatoimenpiteet, valvoo niiden toteutusta ja voi joutua vastuuseen. Elimen jäsenet osallistuvat säännöllisesti koulutukseen.",
    "ue.obowiazki.24": "Onko hallintoelin muodollisesti hyväksynyt 21 artiklan noudattamiseksi toteutetut kyberturvallisuusriskien hallintatoimenpiteet?",
    "ue.obowiazki.25": "Valvooko hallintoelin näiden toimenpiteiden toteutusta dokumentoidusti — esimerkiksi säännöllisillä raporteilla ja tarkistuksilla?",
    "ue.obowiazki.26": "Osallistuvatko hallintoelimen jäsenet säännöllisesti koulutukseen, jonka avulla he voivat tunnistaa riskejä ja arvioida riskienhallintakäytäntöjä, ja dokumentoidaanko osallistuminen?",
    "ue.obowiazki.27": "Valmius valvontatoimiin",
    "ue.obowiazki.28": "Keskeinen toimija on ennakko- ja jälkivalvonnan alainen, tärkeä toimija — vain jälkivalvonnan. Viranomainen voi vaatia tietoja, näyttöä toimintaperiaatteiden toteutuksesta ja tarkastusten tuloksia.",
    "ue.obowiazki.29": "Pystyykö toimija viranomaisen pyynnöstä esittämään näytön kyberturvallisuusperiaatteiden toteutuksesta, mukaan lukien turvallisuustarkastusten tulokset?",
    "ue.obowiazki.3": "Onko toimija määrittänyt liitteen I tai II toimialan ja yrityksen koon perusteella, onko se keskeinen vai tärkeä toimija?",
    "ue.obowiazki.30": "Pystyykö toimija viranomaisen pyynnöstä antamaan käyttöön valvontatehtävien suorittamiseen tarvittavat tiedot, asiakirjat ja informaation?",
    "ue.obowiazki.31": "Onko keskeinen toimija valmis viranomaisen tai riippumattoman tahon tekemään turvallisuustarkastukseen omalla kustannuksellaan?",
    "ue.obowiazki.4": "Onko toimija toimittanut toimivaltaiselle viranomaiselle rekisteröintitiedot: nimen, osoitteen ja yhteystiedot, toimialan ja alatoimialan sekä luettelon jäsenvaltioista, joissa se tarjoaa palveluja?",
    "ue.obowiazki.5": "Yhteystiedot käsittävät sähköpostiosoitteet, IP-osoitealueet ja puhelinnumerot. Kansallisen rekisteröinnin määräajan ja portaalin määrää jäsenvaltion laki.",
    "ue.obowiazki.6": "Onko olemassa menettely rekisteröintitietojen päivittämiseksi ilman aiheetonta viivytystä niiden muututtua?",
    "ue.obowiazki.7": "Direktiivi edellyttää päivittämistä ilman aiheetonta viivytystä; konkreettinen määräaika — esimerkiksi 14 päivää Puolassa — seuraa kansallisesta laista.",
    "ue.obowiazki.8": "Jos toimija on DNS-palveluntarjoaja, aluetunnusrekisteri, pilvi-, datakeskus-, CDN- tai hallinnoitujen palvelujen tarjoaja, verkossa toimiva markkinapaikka, hakukone tai sosiaalinen verkosto — onko se toimittanut 27 artiklan mukaiset lisätiedot, mukaan lukien päätoimipaikan osoitteen unionissa?",
    "ue.obowiazki.9": "koskee 26 artiklan 1 kohdan mukaisia toimijoita",
    "ue.role.1": "Jäsenvaltion toimivaltainen viranomainen",
    "ue.role.10": "Datakeskuspalvelut: kolokaatio, infrastruktuurin hosting ja niihin liittyvät palvelut.",
    "ue.role.11": "Datakeskukset",
    "ue.role.12": "Keskeinen toimija keskisuuren yrityksen kynnyksen yläpuolella (3 artiklan 1 kohdan a alakohta), tärkeä keskisuurena (3 artiklan 2 kohta). Keskisuurta pienempänä — soveltamisalan ulkopuolella, ellei jäsenvaltio nimeä toimijaa 2 artiklan 2 kohdan b–e alakohdan perusteella. Asetuksen 2024/2690 soveltamisalassa.",
    "ue.role.13": "Internetin yhdysliikennepisteen tarjoaja",
    "ue.role.14": "Infrastruktuuri, joka mahdollistaa liikenteen vaihdon riippumattomien verkkojen välillä.",
    "ue.role.15": "Internetin yhdysliikennepisteet",
    "ue.role.16": "Luokitus koon mukaan (3 artiklan 1 kohdan a alakohta ja 2 kohta). Asetus 2024/2690 ei kata yhdysliikennepisteitä — asetuksen 1 artiklassa on suljettu luettelo kohteista.",
    "ue.role.17": "DNS-palveluntarjoaja",
    "ue.role.18": "Verkkotunnusten selvityspalvelut, lukuun ottamatta juurinimipalvelinten ylläpitäjiä.",
    "ue.role.19": "Verkkotunnusjärjestelmä",
    "ue.role.2": "toimivaltainen viranomainen",
    "ue.role.20": "Keskeinen toimija koosta riippumatta (3 artiklan 1 kohdan b alakohta). Asetuksen 2024/2690 soveltamisalassa.",
    "ue.role.21": "Aluetunnusrekisteri",
    "ue.role.22": "Aluetunnusrekisterin ylläpito.",
    "ue.role.23": "Keskeinen toimija koosta riippumatta (3 artiklan 1 kohdan b alakohta). Lisäksi 28 artiklan velvoitteet rekisteröintitiedoista. Asetuksen 2024/2690 soveltamisalassa.",
    "ue.role.24": "Pilvipalvelujen tarjoaja",
    "ue.role.25": "Pilvipalvelut: infrastruktuuri, alusta, ohjelmisto palveluna.",
    "ue.role.26": "Pilvipalvelut",
    "ue.role.27": "Luokitus koon mukaan (3 artiklan 1 kohdan a alakohta ja 2 kohta). Asetuksen 2024/2690 soveltamisalassa.",
    "ue.role.28": "Sisällönjakeluverkon tarjoaja",
    "ue.role.29": "Hajautettujen palvelinten verkko, joka toimittaa sisältöä ja palveluja loppukäyttäjille.",
    "ue.role.3": "kansallisen lain mukaan nimetty; ennen kansallisen moduulin käyttöönottoa työkalu ei nimeä tiettyä laitosta",
    "ue.role.30": "Sisällönjakeluverkot",
    "ue.role.31": "Luottamuspalvelun tarjoaja",
    "ue.role.32": "Asetuksessa (EU) N:o 910/2014 tarkoitetut luottamuspalvelut: allekirjoitukset, leimat, aikaleimat, varmenteet.",
    "ue.role.33": "Luottamuspalvelut",
    "ue.role.34": "Direktiivin soveltamisalassa koosta riippumatta (2 artiklan 2 kohdan a alakohdan ii alakohta). Hyväksytty tarjoaja on keskeinen toimija koosta riippumatta (3 artiklan 1 kohdan b alakohta); muu kuin hyväksytty on keskeinen keskisuuren yrityksen kynnyksen yläpuolella, muutoin tärkeä. Asetuksen 2024/2690 soveltamisalassa.",
    "ue.role.35": "Hallinnoitujen palvelujen tarjoaja",
    "ue.role.36": "Asiakkaan ICT-infrastruktuurin hallinta: asennus, ylläpito, tuki, järjestelmien hallinnointi.",
    "ue.role.37": "ICT-palvelujen hallinta (B2B)",
    "ue.role.38": "Hallinnoidut palvelut",
    "ue.role.39": "Hallinnoitujen tietoturvapalvelujen tarjoaja",
    "ue.role.4": "Yleisten sähköisten viestintäverkkojen tai yleisesti saatavilla olevien sähköisten viestintäpalvelujen tarjoaja",
    "ue.role.40": "Hallinnoidut kyberturvallisuuspalvelut: valvonta, poikkeamiin reagointi, testaus, konsultointi.",
    "ue.role.41": "Hallinnoidut tietoturvapalvelut",
    "ue.role.42": "Direktiivi luokittelee koon mukaan (3 artiklan 1 kohdan a alakohta ja 2 kohta). Jäsenvaltiot voivat tiukentaa kynnystä — Puola pitää MSSP:tä keskeisenä toimijana jo pienestä yrityksestä alkaen; tämä moduuli soveltaa vain direktiivin sääntöä. Asetuksen 2024/2690 soveltamisalassa.",
    "ue.role.5": "Yleisten sähköisten viestintäverkkojen tarjoaminen tai yleisesti saatavilla olevien sähköisten viestintäpalvelujen, mukaan lukien internetyhteyden, tarjoaminen.",
    "ue.role.6": "Digitaalinen infrastruktuuri",
    "ue.role.7": "Sähköinen viestintä",
    "ue.role.8": "Direktiivin soveltamisalassa koosta riippumatta (2 artiklan 2 kohdan a alakohdan i alakohta). Keskisuuri tai suurempi yritys on keskeinen toimija (3 artiklan 1 kohdan c alakohta), mikro- ja pieni yritys — tärkeä (3 artiklan 2 kohta). Kansallinen sähköisen viestinnän laki voi asettaa lisävelvoitteita — tämä moduuli ei sisällä niitä.",
    "ue.role.9": "Datakeskuspalvelujen tarjoaja",
    "ue.role.podstawaArt3b": "direktiivin (EU) 2022/2555 3 artiklan 1 kohdan b alakohta",
    "ue.zaslepki.1": "Euroopan parlamentin ja neuvoston direktiivi (EU) 2022/2555 (NIS 2)",
    "ue.zaslepki.10": "Siitä, merkitäänkö osa toimijoista viran puolesta, päättää kansallinen laki.",
    "ue.zaslepki.11": "Selvitä, kuulutko direktiivin soveltamisalaan",
    "ue.zaslepki.12": "Liitteen I tai II toimiala ja yrityksen koko. Tämän osan hoitaa toimijan profiili tässä työkalussa.",
    "ue.zaslepki.13": "Selvitä maasi toimivaltainen viranomainen",
    "ue.zaslepki.14": "Kukin maa nimeää toimivaltaisen viranomaisen (8 artiklan 1 kohta). Ajantasaista luetteloa ylläpitävät ENISA ja komissio.",
    "ue.zaslepki.15": "Toimita rekisteröintitiedot",
    "ue.zaslepki.16": "Nimi, osoite ja yhteystiedot, toimiala ja alatoimiala, palvelujen tarjoamismaat (3 artiklan 4 kohta). Menettely kansallisen lain mukaan.",
    "ue.zaslepki.17": "Päivitä tiedot ilman aiheetonta viivytystä",
    "ue.zaslepki.18": "Jokainen rekisteröintitietojen muutos edellyttää päivitystä (3 artiklan 5 kohta).",
    "ue.zaslepki.19": "osoite ja ajantasaiset yhteystiedot: sähköpostiosoitteet, IP-osoitealueet, puhelinnumerot",
    "ue.zaslepki.2": "EUVL L 333, 27.12.2022, s. 80",
    "ue.zaslepki.20": "liitteen I tai II toimiala ja alatoimiala",
    "ue.zaslepki.21": "luettelo jäsenvaltioista, joissa toimija tarjoaa palveluja",
    "ue.zaslepki.22": "Määrää kansallinen laki.",
    "ue.zaslepki.23": "Direktiivi (EU) 2022/2555 — 3 artikla",
    "ue.zaslepki.24": "ENISA — jäsenvaltioiden toimivaltaiset viranomaiset",
    "ue.zaslepki.25": "Direktiivi (EU) 2022/2555",
    "ue.zaslepki.26": "EU-moduuli ei sisällä kansallisen viranomaisen ohjeita — ne tulevat kansallisen lain moduulin mukana.",
    "ue.zaslepki.27": "Rekisteritietojen automaattinen haku toimii vain maille, joilla on kansallisen lain moduuli. Täytä profiili käsin.",
    "ue.zaslepki.28": "Tilinpäätöksen lukeminen toimii vain maille, joilla on kansallisen lain moduuli. Syötä liikevaihto ja henkilöstömäärä käsin.",
    "ue.zaslepki.3": "Komission täytäntöönpanoasetus (EU) 2024/2690",
    "ue.zaslepki.4": "EUVL L, 2024/2690, 18.11.2024",
    "ue.zaslepki.5": "NIS 2 -direktiivissä ei ole erillistä sähköisen viestinnän kerrosta. Kansallinen sähköisen viestinnän laki voi asettaa lisävelvoitteita — tämä moduuli ei tunne niitä.",
    "ue.zaslepki.6": "Keskeisten ja tärkeiden toimijoiden luettelo",
    "ue.zaslepki.7": "Jäsenvaltion toimivaltainen viranomainen.",
    "ue.zaslepki.8": "Direktiivi velvoittaa jäsenvaltiot pitämään keskeisten ja tärkeiden toimijoiden luetteloa ja vaatimaan toimijoita toimittamaan rekisteröintitiedot. Portaalin, menettelyn ja määräajan määrää kansallinen laki — tämä moduuli ei tunne niitä, koska valitun maan kansallisen lain moduuli ei ole vielä valmis.",
    "ue.zaslepki.9": "Kaikki keskeiset ja tärkeät toimijat. Määräajan määrää kansallinen laki.",
    "ue.zaslepki.skrotDyrektywy": "NIS 2 -direktiivi",
    "ue.zaslepki.skrotReg2690": "Asetus 2024/2690",
    "xlsx.1": "{p0} – {p1} €",
    "xlsx.25": "Valuuttakurssi",
    "xlsx.4": "NIS 2 -DIREKTIIVIN (EU) 2022/2555 VAATIMUSTENMUKAISUUSRAPORTTI",
    "xlsx.58": "Sähköisen viestinnän toiminta: asetusta (EU) 2024/2690 ei sovelleta. Kynnysarvot määrää kansallinen laki (direktiivin 23 artiklan 11 kohta) — yhteinen moduuli ei tunne niitä.",
    "xlsx.68": "Työkalu on tarkoitettu itsearviointiin. Se ei ole tarkastus eikä oikeudellista neuvontaa.",
    "xlsx.69": "Toimijoille, jotka eivät kuulu asetuksen (EU) 2024/2690 soveltamisalaan, merkittävän poikkeaman kynnysarvot määrää kansallinen laki (direktiivin 23 artiklan 11 kohta).",
    "xlsx.70": "Profiilissa ilmoitetut roolit ovat ilmoitus. Aseman ratkaisee tosiasiallisesti harjoitettu toiminta (direktiivin (EU) 2022/2555 3 artikla).",
    "xlsx.etykietaKrs": "Rekisterinumero",
    "xlsx.etykietaNip": "Tunnistenumero",
    "xlsx.etykietaRegon": "Tilastonumero"
});
