/* Teksty modułu ue — język: fr.
   Te same klucze co w napisy/pl.js (wersja źródłowa); wstawki {p0}, {p1}…
   pozostają bez zmian. Klucze ue.cyt.* to wzorce składania odesłań
   do przepisów w tym języku — patrz kraje/ue/cytaty.js. */
KRAJE.napisy('ue', 'fr', {
    "app.10": "Vérifiez la liste des rôles ci-dessous — le statut dépend de l'activité réellement exercée (article 3 de la directive (UE) 2022/2555), non d'une inscription au registre.",
    "app.14": "Année précédente : {p0} EUR",
    "app.15": "Chiffre d'affaires de la période de référence : {p0} EUR",
    "app.19": "Interrogation des registres avec le numéro {p0}…",
    "app.34": " Md EUR",
    "app.35": " M EUR",
    "app.36": " k EUR",
    "app.37": "",
    "app.4": "La récupération automatique des données de registre n'est pas disponible pour ce pays — remplissez le profil manuellement.",
    "app.59": "Évaluation de conformité à la directive NIS 2 (JSON)",
    "app.68": "Pour ce pays, il n'existe pas de registre dans lequel l'outil pourrait récupérer des données — le profil se remplit manuellement.",
    "app.69": "Pour ce pays, il n'existe pas de registre dans lequel l'outil pourrait récupérer des données. Cliquez pour activer le mode hors ligne.",
    "app.73": " · compte de résultat en variante ",
    "app.74": "<div class=\"mt-2 tekst-uwaga\">Les données de registre n'indiquent aucun rôle du secteur des infrastructures numériques. Indiquez les rôles manuellement ci-dessous.</div>",
    "app.8": "Inscription au registre des fournisseurs de communications électroniques confirmée",
    "app.progDostawcy": "",
    "app.przyklad.adres": "1 rue de l'Exemple, 75000 Ville",
    "app.przyklad.forma": "Société à responsabilité limitée",
    "app.przyklad.nazwa": "Opérateur Exemple SARL",
    "app.statusVat": " · statut TVA : ",
    "dashboard.1": "D'après les rôles et la taille déclarés, l'entité n'est ni une entité essentielle ni une entité importante au sens de l'article 3 de la directive (UE) 2022/2555. Vérifiez le profil si le résultat ne correspond pas à vos attentes.",
    "dashboard.113": "Questions fréquentes",
    "dashboard.12": "— {p0} ; le délai de transposition en droit national a expiré le {p2}",
    "dashboard.123": "Directive NIS 2",
    "dashboard.30": "Liste des entités essentielles et importantes",
    "dashboard.4": "— directement applicable depuis le {p0} dans tous les États membres, sans transposition",
    "dashboard.42": "Variante forfaitaire : {p0}",
    "dashboard.45": "Critères de l'article 32, paragraphe 7, de la directive :",
    "dashboard.46": "Total",
    "dashboard.49": "L'entité exerce une activité de communications électroniques — la responsabilité du dirigeant est régie par le droit national",
    "dashboard.50": "",
    "dashboard.51": "",
    "dashboard.53": "Astreinte en cas de retard d'exécution d'une décision : de {p0} EUR à {p1} EUR par jour ({p2})",
    "dashboard.54": "Cas qualifié : jusqu'à {p0} EUR ({p1})",
    "dashboard.57": "({p0}). La date à partir de laquelle l'autorité nationale peut infliger des amendes est fixée par la loi de transposition — ce module ne la connaît pas. Les obligations de mise en œuvre découlent du droit national dès son entrée en vigueur.",
    "dashboard.65": "({p0}). La date à partir de laquelle l'autorité nationale peut infliger des amendes est fixée par la loi de transposition — ce module ne la connaît pas. Le risque financier n'est donc pas daté ici, tandis que les obligations de mise en œuvre découlent du droit national dès son entrée en vigueur.",
    "dashboard.83": "Activité de communications électroniques — les seuils sont fixés par le droit national.",
    "dashboard.84": "Le règlement (UE) 2024/2690 ne s'applique pas aux fournisseurs de réseaux et de services de communications électroniques publics. Pour eux, les seuils de l'incident important sont fixés par le droit national (article 23, paragraphe 11, de la directive) — ce module ne les connaît pas et n'indique donc aucune valeur.",
    "dashboard.terminRejestracji": "Le délai de communication des données d'enregistrement est fixé par le droit national (article 3, paragraphe 4, de la directive). Les fournisseurs visés à l'article 27, paragraphe 1 — services DNS, registres de noms de domaine de premier niveau, services en nuage, centres de données, réseaux de diffusion de contenu, services gérés et services de sécurité gérés — communiquent leurs données au registre de l'ENISA : initialement avant le 17 janvier 2025, puis toute modification sans retard injustifié.",
    "html.1": "ITORO — Évaluation de conformité à la directive NIS 2 (UE) 2022/2555",
    "html.10": "Évaluation de conformité à la directive NIS 2 — module commun",
    "html.100": "La lecture des états financiers ne fonctionne que pour les pays disposant d'un module de droit national. Pour ce pays, vous saisissez manuellement le <strong>chiffre d'affaires</strong> de l'exercice — le montant de l'amende en dépend.",
    "html.102": "La récupération automatique des données de registre ne fonctionne que pour les pays disposant d'un module de droit national. Vous indiquez manuellement les rôles et la taille de l'entreprise.",
    "html.11": "La directive (UE) 2022/2555 (NIS 2) doit être transposée en droit national. L'évaluation couvre les obligations qui découlent directement de la directive ainsi que le règlement d'exécution (UE) 2024/2690 de la Commission, directement applicable — dans la mesure où ils concernent l'entité.",
    "html.23": "vous saisissez manuellement le chiffre d'affaires et la taille — le module commun n'interroge pas les registres nationaux",
    "html.33": "directive (UE) 2022/2555 du Parlement européen et du Conseil du 14 décembre 2022 (NIS 2)",
    "html.33a": "{p0} — acte national de transposition de la directive ; ce module n'évalue pas encore ses exigences",
    "html.33b": "l'État n'a pas encore adopté d'acte de transposition — l'évaluation suit le droit de l'Union",
    "html.35": "obligations de l'organe de direction — article 20 de la directive",
    "html.36": "L'outil sert à l'autoévaluation. Il ne constitue ni un audit ni un avis juridique.",
    "html.40": "le module commun n'établit aucune connexion sortante — il n'interroge pas les registres",
    "html.59": "États financiers",
    "html.60": "La lecture des états financiers n'est disponible que pour les pays disposant d'un module de droit national. Pour ce pays, vous saisissez manuellement le chiffre d'affaires et l'effectif.",
    "html.62": "Recherche dans un registre",
    "html.63": "les registres des entreprises sont nationaux — le module commun ne les connaît pas",
    "html.64": "vous indiquez manuellement les rôles et la taille de l'entreprise",
    "html.66": "Numéro d'identification de l'entité",
    "html.68": "La récupération automatique des données de registre ne fonctionne que pour les pays disposant d'un module de droit national.",
    "html.76": "Chiffre d'affaires annuel (EUR)",
    "html.78": "Chiffre d'affaires de l'activité de communications électroniques (EUR)",
    "html.79": "Ce champ concerne les fournisseurs de réseaux ou de services de communications électroniques publics. Les seuils nationaux sont fixés par le droit de l'État membre.",
    "html.80": "Rémunération mensuelle du dirigeant (EUR)",
    "html.82": "Taux de change",
    "html.83": "Les plafonds d'amende de la directive sont exprimés en euros. La conversion en monnaie nationale et le taux relèvent du droit national — ici, les montants sont indiqués en euros sans conversion.",
    "html.84": "Le statut résulte uniquement de l'agrégation des données d'entreprises liées, et le système d'information de l'entité est indépendant (considérant 16 de la directive — l'application relève du droit national)",
    "html.85": "L'entité exerce des activités dans les domaines de la sécurité nationale, de la sécurité publique, de la défense ou de la répression pénale (article 2, paragraphe 7, de la directive)",
    "html.91": "Évaluation de conformité à la directive (UE) 2022/2555 du Parlement européen et du Conseil (NIS 2) et au règlement d'exécution (UE) 2024/2690 de la Commission — module commun pour les pays dont le module de droit national n'est pas encore prêt.",
    "html.94": "si l'entité est <strong>essentielle</strong>, <strong>importante</strong> ou hors du champ de la directive",
    "html.daneZeSprawozdania": "nom, numéro d'identification, adresse du siège",
    "html.rejestrMozliwy": "Le registre {p0} est public et gratuit : sa lecture peut être ajoutée à l’outil ; les pull requests sont les bienvenues (voir le README).",
    "html.tytulNaglowka": "Évaluation de conformité à la directive NIS 2",
    "html.zrodlaRecznie": "Ce module ne connaît pas les registres de votre État — renseignez le profil à la main. Le chiffre d'affaires annuel détermine le plafond de l'amende : indiquez-le avec précision.",
    "klasyfikacja.10": "article 3, paragraphe 1, point c), de la directive (UE) 2022/2555 (fournisseur de réseaux de communications électroniques publics ou de services de communications électroniques accessibles au public ayant au moins la qualité de moyenne entreprise)",
    "klasyfikacja.11": "article 3, paragraphe 2, lu conjointement avec l'article 2, paragraphe 2, point a) i), de la directive (UE) 2022/2555 (fournisseur de réseaux ou de services de communications électroniques publics ayant la qualité de micro ou petite entreprise)",
    "klasyfikacja.12": "article 3, paragraphe 1, point a), de la directive (UE) 2022/2555 (fournisseur de services de sécurité gérés dépassant les plafonds de la moyenne entreprise)",
    "klasyfikacja.13": "Les micro et petites entreprises ne relèvent pas de la directive au titre de ce rôle (article 2, paragraphe 1, a contrario).",
    "klasyfikacja.15": "article 3, paragraphe 1, point b), de la directive (UE) 2022/2555 (prestataire de services de confiance qualifié) — quelle que soit la taille de l'entreprise",
    "klasyfikacja.16": "article 3, paragraphe 2, lu conjointement avec l'article 2, paragraphe 2, point a) ii), de la directive (UE) 2022/2555 (prestataire de services de confiance non qualifié ayant la qualité de micro, petite ou moyenne entreprise)",
    "klasyfikacja.18": "article 3, paragraphe 2, de la directive (UE) 2022/2555 (entité de l'administration publique au niveau régional, si l'État membre le prévoit — article 2, paragraphe 2, point f) ii))",
    "klasyfikacja.19": "article 3, paragraphe 1, point f), de la directive (UE) 2022/2555 (entité de l'administration publique au niveau central — article 2, paragraphe 2, point f) i))",
    "klasyfikacja.2": "Surveillance ex ante et ex post (article 32 de la directive (UE) 2022/2555).",
    "klasyfikacja.20": "article 3, paragraphe 2, de la directive (UE) 2022/2555 (entité de l'administration publique au niveau régional — article 2, paragraphe 2, point f) ii))",
    "klasyfikacja.21": "L'étendue des obligations des entités de l'administration publique au niveau local est déterminée par le droit national (article 2, paragraphe 5, point a), de la directive).",
    "klasyfikacja.22": "Un État membre peut exempter les entités exerçant des activités dans les domaines de la sécurité nationale, de la sécurité publique, de la défense ou de la répression pénale (article 2, paragraphe 7, de la directive). L'exemption ne s'applique pas d'elle-même — vérifiez le résultat de l'évaluation au regard du droit national.",
    "klasyfikacja.23": "L'entité remplit les critères tant de l'entité essentielle que de l'entité importante. Elle est une entité essentielle (article 3, paragraphe 1, de la directive), et les exigences les plus élevées s'appliquent à toute l'activité couverte par la directive.",
    "klasyfikacja.25": "L'entité est essentielle : le catalogue complet des mesures de l'article 21, paragraphe 2, de la directive et la surveillance ex ante et ex post s'appliquent donc — l'évaluation couvre l'ensemble des questions.",
    "klasyfikacja.26": "En tant qu'entité importante, vous êtes soumis au même catalogue de mesures de l'article 21, paragraphe 2, mais uniquement à la surveillance ex post (article 33). Le plafond de l'amende est plus bas : 7 millions d'EUR ou 1,4 % du chiffre d'affaires (article 34, paragraphe 5). Des allègements pour les entités publiques peuvent être prévus par le droit national — ce module ne les connaît pas.",
    "klasyfikacja.28": "Les obligations des entités de l'administration publique découlent de l'article 2, paragraphe 2, point f), de la directive ; leur étendue exacte, y compris pour le niveau local et les établissements d'enseignement, est déterminée par le droit national (article 2, paragraphe 5).",
    "klasyfikacja.29": "Il a été déclaré que le statut de l'entité résulte uniquement de l'agrégation des données d'entreprises liées ou partenaires et que le système d'information de l'entité est indépendant. La directive permet une telle exclusion (considérant 16), mais c'est le droit national qui en décide — le module retient l'exclusion, qu'il faut vérifier au regard du droit de l'État membre et documenter.",
    "klasyfikacja.4": "Surveillance ex post uniquement — en présence d'éléments de preuve, d'indices ou d'informations relatifs à une infraction (article 33 de la directive (UE) 2022/2555).",
    "klasyfikacja.5": "Hors du champ de la directive",
    "klasyfikacja.6": "Aucune obligation au titre de la directive (UE) 2022/2555 pour le rôle indiqué.",
    "klasyfikacja.7": "article 3, paragraphe 1, point a), de la directive (UE) 2022/2555 (entité d'un type visé à l'annexe I dépassant les plafonds de la moyenne entreprise)",
    "klasyfikacja.8": "article 3, paragraphe 2, de la directive (UE) 2022/2555 (entité d'un type visé à l'annexe I remplissant les critères de la moyenne entreprise)",
    "klasyfikacja.9": "Les micro et petites entreprises ne relèvent pas de la directive au titre de ce rôle (article 2, paragraphe 1, a contrario).",
    "kreator.10": "Saisissez manuellement le chiffre d'affaires de l'année précédente.",
    "kreator.35": "<span class=\"text-secondary\">La lecture des états financiers n'est pas disponible pour ce pays.</span>",
    "kreator.37": "La lecture des états financiers n'est pas disponible pour ce pays — saisissez le chiffre d'affaires manuellement.",
    "kreator.56": "Oui — le règlement de l'UE est directement applicable depuis le 7 novembre 2024 dans tous les États membres et ne prévoit aucune période transitoire. Sa base est",
    "kreator.57": ", qui a habilité la Commission à préciser les exigences techniques et méthodologiques pour les fournisseurs visés à l'article 3, paragraphe 1, du règlement. Le délai de transposition de la directive a expiré le",
    "kreator.58": ", et la date à partir de laquelle l'autorité nationale peut infliger des amendes est fixée par le droit national. Les exigences techniques de l'annexe (sections 6 et 9 à 13) sont contraignantes dans leur rédaction actuelle — elles n'attendent aucune précision. On ne peut déroger qu'aux exigences assorties de la formule « le cas échéant », et uniquement avec une justification documentée.",
    "kreator.9": "États financiers →",
    "kreator.przepisReg2690": "l'article 21, paragraphe 5, de la directive (UE) 2022/2555",
    "kreator.terminReg2690": "17 octobre 2024",
    "punktacja.10": "Entités publiques",
    "punktacja.4": "Directive NIS 2 — article 21",
    "punktacja.5": "Directive NIS 2 — obligations formelles",
    "punktacja.8": "Communications électroniques",
    "punktacja.9": "Directive NIS 2 — entités publiques",
    "punktacja.skrotKsc": "NIS 2",
    "punktacja.skrotPke": "télécom",
    "ue.cyt.akapit": ", {p0} alinéa",
    "ue.cyt.art": "article {p0}",
    "ue.cyt.drugi": "deuxième",
    "ue.cyt.dyr": "{p0}, de la directive (UE) 2022/2555",
    "ue.cyt.i": "et",
    "ue.cyt.laczenie": "",
    "ue.cyt.lit": ", point {p0})",
    "ue.cyt.litery": "",
    "ue.cyt.pkt": ", point {p0})",
    "ue.cyt.rozdzielacz": " ; ",
    "ue.cyt.rozp": "{p0}, du règlement (UE) 2024/2690",
    "ue.cyt.ust": ", paragraphe {p0}",
    "ue.katalog.1": "Politiques relatives à l'analyse des risques et à la sécurité des systèmes d'information",
    "ue.katalog.10": "Gestion des incidents",
    "ue.katalog.11": "La gestion des incidents comprend les actions et procédures visant à prévenir, détecter, analyser et contenir un incident, à y répondre et à rétablir le fonctionnement normal (article 6, point 8)).",
    "ue.katalog.12": "Existe-t-il une procédure documentée de gestion des incidents couvrant la détection, l'analyse, le confinement, la réponse et le rétablissement ?",
    "ue.katalog.13": "ISO/IEC 27001 A.5.24–A.5.26",
    "ue.katalog.14": "La procédure permet-elle de respecter les délais de notification d'un incident important : alerte précoce sous 24 heures, notification sous 72 heures, rapport final sous un mois ?",
    "ue.katalog.15": "ISO/IEC 27001 A.5.24",
    "ue.katalog.16": "L'entité dispose-t-elle de critères pour qualifier un incident d'important, conformes à l'article 23, paragraphe 3 : perturbation opérationnelle grave ou pertes financières, ou dommage considérable pour d'autres personnes ?",
    "ue.katalog.17": "ISO/IEC 27001 A.5.25",
    "ue.katalog.18": "Les incidents sont-ils enregistrés et les enseignements de leur traitement utilisés pour améliorer les mesures ?",
    "ue.katalog.19": "ISO/IEC 27001 A.5.27",
    "ue.katalog.2": "Les mesures reposent sur une approche « tous risques » (article 21, paragraphe 2). Leur proportionnalité s'apprécie en tenant compte du degré d'exposition, de la taille de l'entité, de la probabilité des incidents et de leur gravité (article 21, paragraphe 1, deuxième alinéa).",
    "ue.katalog.20": "Continuité des activités et gestion des crises",
    "ue.katalog.21": "Continuité des activités, telle que la gestion des sauvegardes et la reprise des activités après un sinistre, et gestion des crises.",
    "ue.katalog.22": "Existe-t-il un plan de continuité des activités couvrant la reprise après un sinistre ?",
    "ue.katalog.23": "ISO/IEC 27001 A.5.29–A.5.30",
    "ue.katalog.24": "Les sauvegardes sont-elles réalisées, protégées et testées quant à leur capacité de restauration ?",
    "ue.katalog.25": "ISO/IEC 27001 A.8.13",
    "ue.katalog.26": "L'entité dispose-t-elle de procédures de gestion de crise avec des rôles et des canaux de communication définis ?",
    "ue.katalog.27": "ISO/IEC 27001 A.5.29",
    "ue.katalog.28": "Les plans de continuité et de reprise sont-ils testés périodiquement, avec des résultats documentés ?",
    "ue.katalog.29": "ISO/IEC 27001 A.5.30",
    "ue.katalog.3": "L'entité dispose-t-elle d'une politique documentée d'analyse des risques et de sécurité des systèmes d'information, approuvée par l'organe de direction ?",
    "ue.katalog.30": "Sécurité de la chaîne d'approvisionnement",
    "ue.katalog.31": "Sécurité de la chaîne d'approvisionnement, y compris les aspects liés à la sécurité concernant les relations entre l'entité et ses fournisseurs ou prestataires de services directs. L'entité tient compte des vulnérabilités propres à chaque fournisseur et de la qualité globale de ses produits et de ses pratiques de cybersécurité (article 21, paragraphe 3).",
    "ue.katalog.32": "L'entité tient-elle une liste de ses fournisseurs et prestataires directs avec une évaluation de leur importance pour la sécurité des réseaux et systèmes ?",
    "ue.katalog.33": "ISO/IEC 27001 A.5.19",
    "ue.katalog.34": "Le choix des mesures à l'égard des fournisseurs tient-il compte des vulnérabilités propres à chacun et de la qualité de leurs pratiques de cybersécurité et de développement sécurisé ?",
    "ue.katalog.35": "ISO/IEC 27001 A.5.19, A.5.21",
    "ue.katalog.36": "Les contrats avec les fournisseurs contiennent-ils des exigences de sécurité et une obligation d'informer des incidents et des vulnérabilités ?",
    "ue.katalog.37": "ISO/IEC 27001 A.5.20",
    "ue.katalog.38": "L'entité tient-elle compte des résultats des évaluations coordonnées des risques de sécurité des chaînes d'approvisionnement critiques visées à l'article 22 ?",
    "ue.katalog.39": "ISO/IEC 27001 A.5.21",
    "ue.katalog.4": "ISO/IEC 27001 points 5.2, 6.1.2",
    "ue.katalog.40": "Sécurité de l'acquisition, du développement et de la maintenance des systèmes",
    "ue.katalog.41": "Sécurité de l'acquisition, du développement et de la maintenance des réseaux et systèmes d'information, y compris le traitement et la divulgation des vulnérabilités.",
    "ue.katalog.42": "Les exigences de sécurité sont-elles définies avant l'acquisition ou le début du développement d'un système et vérifiées avant sa mise en service ?",
    "ue.katalog.43": "ISO/IEC 27001 A.8.25–A.8.29",
    "ue.katalog.44": "Existe-t-il un processus de traitement des vulnérabilités : identification, évaluation, correction dans un délai défini ?",
    "ue.katalog.45": "ISO/IEC 27001 A.8.8",
    "ue.katalog.46": "L'entité dispose-t-elle d'une procédure de divulgation des vulnérabilités, y compris un canal de réception des signalements de tiers ?",
    "ue.katalog.47": "Les modifications des systèmes passent-elles par un processus contrôlé de gestion des changements avec évaluation de l'impact sur la sécurité ?",
    "ue.katalog.48": "ISO/IEC 27001 A.8.32",
    "ue.katalog.49": "Évaluation de l'efficacité des mesures",
    "ue.katalog.5": "L'analyse des risques couvre-t-elle tous les risques pesant sur les réseaux et systèmes d'information et sur leur environnement physique, et pas seulement les cybermenaces ?",
    "ue.katalog.50": "Politiques et procédures pour évaluer l'efficacité des mesures de gestion des risques en matière de cybersécurité.",
    "ue.katalog.51": "Existe-t-il une politique documentée d'évaluation de l'efficacité des mesures, précisant le périmètre, la fréquence et les méthodes ?",
    "ue.katalog.52": "ISO/IEC 27001 point 9.1",
    "ue.katalog.53": "Les évaluations d'efficacité sont-elles réalisées périodiquement et leurs résultats communiqués à l'organe de direction ?",
    "ue.katalog.54": "ISO/IEC 27001 points 9.2–9.3",
    "ue.katalog.55": "Les faiblesses détectées donnent-elles lieu à des actions correctives documentées avec un responsable et une échéance ?",
    "ue.katalog.56": "ISO/IEC 27001 point 10.1",
    "ue.katalog.57": "Cyberhygiène et formation",
    "ue.katalog.58": "Pratiques de base en matière de cyberhygiène et formation à la cybersécurité. Les membres de l'organe de direction suivent régulièrement des formations (article 20, paragraphe 2).",
    "ue.katalog.59": "L'entité applique-t-elle des pratiques de base de cyberhygiène : mises à jour, gestion des mots de passe, limitation des privilèges, protection contre les logiciels malveillants ?",
    "ue.katalog.6": "ISO/IEC 27001 point 6.1.2",
    "ue.katalog.60": "ISO/IEC 27001 A.8.7, A.8.8",
    "ue.katalog.61": "Le personnel suit-il des formations à la cybersécurité adaptées à son rôle, avec une participation documentée ?",
    "ue.katalog.62": "ISO/IEC 27001 A.6.3",
    "ue.katalog.63": "Les membres de l'organe de direction suivent-ils régulièrement des formations leur permettant d'identifier les risques et d'évaluer les pratiques de gestion des risques ?",
    "ue.katalog.64": "ISO/IEC 27001 point 7.2",
    "ue.katalog.65": "Cryptographie et chiffrement",
    "ue.katalog.66": "Politiques et procédures relatives à l'utilisation de la cryptographie et, le cas échéant, du chiffrement.",
    "ue.katalog.67": "Existe-t-il une politique de cryptographie précisant quelles données et quels canaux sont chiffrés et avec quels algorithmes ?",
    "ue.katalog.68": "ISO/IEC 27001 A.8.24",
    "ue.katalog.69": "Les clés cryptographiques sont-elles gérées sur tout leur cycle de vie : génération, distribution, stockage, rotation, retrait ?",
    "ue.katalog.7": "Le choix des mesures tient-il compte de l'état des connaissances, des normes européennes et internationales pertinentes et du coût de mise en œuvre ?",
    "ue.katalog.70": "Ressources humaines, contrôle d'accès et gestion des actifs",
    "ue.katalog.71": "Sécurité des ressources humaines, politiques de contrôle d'accès et gestion des actifs.",
    "ue.katalog.72": "L'entité tient-elle un inventaire à jour des actifs avec des propriétaires désignés et une classification ?",
    "ue.katalog.73": "ISO/IEC 27001 A.5.9, A.5.12",
    "ue.katalog.74": "Existe-t-il une politique de contrôle d'accès fondée sur le principe du moindre privilège, avec une revue périodique des droits ?",
    "ue.katalog.75": "ISO/IEC 27001 A.5.15, A.5.18",
    "ue.katalog.76": "Des procédures de sécurité s'appliquent-elles à l'embauche, au changement de poste et au départ du personnel, y compris le retrait des droits et la restitution des actifs ?",
    "ue.katalog.77": "ISO/IEC 27001 A.6.1–A.6.5",
    "ue.katalog.78": "L'accès privilégié est-il limité, journalisé et revu ?",
    "ue.katalog.79": "ISO/IEC 27001 A.8.2",
    "ue.katalog.8": "ISO/IEC 27001 point 6.1.3",
    "ue.katalog.80": "Authentification multifacteur et communications sécurisées",
    "ue.katalog.81": "Le cas échéant — authentification multifacteur ou continue, communications vocales, vidéo et textuelles sécurisées et systèmes de communication d'urgence sécurisés au sein de l'entité.",
    "ue.katalog.82": "L'authentification multifacteur ou continue est-elle utilisée là où l'analyse des risques le justifie, en particulier pour l'accès à distance et les comptes privilégiés ?",
    "ue.katalog.83": "ISO/IEC 27001 A.8.5",
    "ue.katalog.84": "Les communications vocales, vidéo et textuelles utilisées à des fins professionnelles sont-elles sécurisées ?",
    "ue.katalog.85": "ISO/IEC 27001 A.8.20",
    "ue.katalog.86": "L'entité dispose-t-elle d'un système sécurisé de communication interne d'urgence, indépendant de l'infrastructure principale ?",
    "ue.katalog.9": "Le niveau de sécurité est-il documenté comme adapté au risque existant, avec une justification tenant compte de la taille de l'entité et de l'impact sociétal et économique des incidents ?",
    "ue.kierownictwo.1": "L'organe de direction d'une entité essentielle ou importante — dans une société de capitaux, le conseil d'administration ou la gérance. La directive ne définit pas cette notion ; son étendue dans un pays donné résulte du droit national.",
    "ue.kierownictwo.10": "Établir le statut de l'entité et veiller à l'enregistrement",
    "ue.kierownictwo.11": "Déterminer si l'entité est essentielle ou importante et communiquer les données d'enregistrement à l'autorité compétente. Les modalités et le délai sont fixés par le droit national.",
    "ue.kierownictwo.12": "Mettre en place l'analyse des risques et la politique de sécurité",
    "ue.kierownictwo.13": "Des mesures fondées sur une approche « tous risques », proportionnées à l'exposition, à la taille de l'entité et à la gravité des incidents.",
    "ue.kierownictwo.14": "Mettre en place la gestion et la notification des incidents",
    "ue.kierownictwo.15": "Une procédure de gestion des incidents et la capacité de respecter les délais de 24 heures, 72 heures et un mois.",
    "ue.kierownictwo.16": "24 h / 72 h / un mois à compter de la détection",
    "ue.kierownictwo.17": "Assurer la continuité des activités",
    "ue.kierownictwo.18": "Plan de continuité, sauvegardes, reprise après sinistre, gestion des crises.",
    "ue.kierownictwo.19": "Mettre en ordre la chaîne d'approvisionnement",
    "ue.kierownictwo.2": "La responsabilité de l'organe de direction s'entend sans préjudice des règles nationales relatives à la responsabilité des institutions publiques et des fonctionnaires (article 20, paragraphe 1, deuxième alinéa).",
    "ue.kierownictwo.20": "Liste des fournisseurs, évaluation de leurs vulnérabilités et pratiques, exigences de sécurité dans les contrats.",
    "ue.kierownictwo.21": "Mettre en place le contrôle d'accès et la gestion des actifs",
    "ue.kierownictwo.22": "Inventaire des actifs, principe du moindre privilège, revues des droits, authentification multifacteur là où le risque le justifie.",
    "ue.kierownictwo.23": "Mesurer l'efficacité des mesures",
    "ue.kierownictwo.24": "Politique et procédures d'évaluation de l'efficacité, revues périodiques, actions correctives.",
    "ue.kierownictwo.25": "Approuver",
    "ue.kierownictwo.26": "les mesures de gestion des risques en matière de cybersécurité (article 20, paragraphe 1)",
    "ue.kierownictwo.27": "la politique d'analyse des risques et de sécurité des systèmes",
    "ue.kierownictwo.28": "le budget et les rôles dans la mise en œuvre",
    "ue.kierownictwo.29": "Superviser",
    "ue.kierownictwo.3": "Le fait de confier des obligations à une autre personne exclut-il la responsabilité — c'est le droit national qui en décide. En Pologne, ce n'est pas le cas (article 8c, paragraphe 3, de la loi sur le système national de cybersécurité).",
    "ue.kierownictwo.30": "la mise en œuvre des mesures approuvées (article 20, paragraphe 1)",
    "ue.kierownictwo.31": "les résultats de l'évaluation de l'efficacité (article 21, paragraphe 2, point f))",
    "ue.kierownictwo.32": "le respect des délais de notification des incidents (article 23)",
    "ue.kierownictwo.33": "Documenter",
    "ue.kierownictwo.34": "les décisions d'approbation et les revues",
    "ue.kierownictwo.35": "la participation aux formations (article 20, paragraphe 2)",
    "ue.kierownictwo.36": "Membre de l'organe de direction",
    "ue.kierownictwo.37": "approbation des mesures, supervision, décisions, budget",
    "ue.kierownictwo.38": "Chef de projet",
    "ue.kierownictwo.39": "coordination de la mise en œuvre, calendrier, état d'avancement et preuves",
    "ue.kierownictwo.4": "Approuver les mesures de gestion des risques en matière de cybersécurité",
    "ue.kierownictwo.40": "Informatique / cybersécurité",
    "ue.kierownictwo.41": "analyse des risques, mesures techniques, gestion des incidents",
    "ue.kierownictwo.42": "Service juridique / conformité",
    "ue.kierownictwo.5": "L'organe de direction approuve les mesures prises pour se conformer à l'article 21. C'est une décision de l'organe, pas du service informatique — sans elle, les mesures n'ont pas de fondement.",
    "ue.kierownictwo.6": "Superviser la mise en œuvre des mesures",
    "ue.kierownictwo.7": "La supervision de la mise en œuvre incombe à l'organe de direction. L'exécution peut être confiée, la supervision non.",
    "ue.kierownictwo.8": "Suivre régulièrement des formations",
    "ue.kierownictwo.9": "Les membres de l'organe de direction suivent régulièrement des formations afin d'acquérir des connaissances leur permettant d'identifier les risques et d'évaluer les pratiques de gestion des risques et leur incidence sur les services de l'entité.",
    "ue.kierownictwo.daneRejestracyjne": "les données d'enregistrement et leurs mises à jour (article 3, paragraphes 4 et 5)",
    "ue.meta.1": "La variante en pourcentage l'emporte : {p0} % du chiffre d'affaires est supérieur à {p1} millions d'EUR.",
    "ue.meta.10": "La directive n'impose pas d'obligations directement aux entreprises — c'est la loi nationale qui le fait, que l'État membre devait adopter avant le 17 octobre 2024. Ce module présente les exigences dans les termes de la directive, car le module de droit national du pays sélectionné n'est pas encore prêt ou le pays n'a pas transposé la directive.",
    "ue.meta.11": "Obligations issues de la directive",
    "ue.meta.12": "Liste des entités — avant le 17 avril 2025",
    "ue.meta.13": "Les États membres devaient établir une liste des entités essentielles et importantes avant le 17 avril 2025 et exiger des entités qu'elles communiquent leurs données d'enregistrement.",
    "ue.meta.14": "Règlement (UE) 2024/2690",
    "ue.meta.15": "Directement applicable depuis le 7 novembre 2024",
    "ue.meta.16": "Le règlement d'exécution est directement applicable dans tous les États membres, quel que soit l'état de transposition de la directive. Il concerne les entités énumérées à son article 1er : DNS, TLD, nuage, centres de données, réseaux de diffusion de contenu, services gérés et services de confiance.",
    "ue.meta.17": "article 16 du règlement (UE) 2024/2690",
    "ue.meta.18": "Au moins 10 000 000 EUR ou au moins 2 % du chiffre d'affaires annuel mondial total de l'entreprise au cours de l'exercice précédent — le montant le plus élevé étant retenu. C'est un plafond minimal : le droit national peut le relever.",
    "ue.meta.19": "Au moins 7 000 000 EUR ou 1,4 % du chiffre d'affaires annuel mondial total — le montant le plus élevé étant retenu. Plafond minimal.",
    "ue.meta.2": "Le montant forfaitaire l'emporte : {p0} millions d'EUR est supérieur à {p1} % du chiffre d'affaires.",
    "ue.meta.20": "La directive ne prévoit pas d'amende distincte pour une infraction qualifiée — c'est une construction du droit national de certains pays.",
    "ue.meta.21": "Les États membres peuvent prévoir des astreintes pour contraindre à mettre fin à une infraction. Le montant est fixé par le droit national.",
    "ue.meta.22": "L'organe de direction approuve les mesures de gestion des risques, supervise leur mise en œuvre et peut être tenu responsable des violations de l'article 21. Les règles et l'étendue de cette responsabilité sont déterminées par le droit national.",
    "ue.meta.23": "L'organe de direction approuve les mesures de gestion des risques en matière de cybersécurité (article 20, paragraphe 1).",
    "ue.meta.24": "L'organe de direction supervise la mise en œuvre de ces mesures (article 20, paragraphe 1).",
    "ue.meta.25": "Les membres de l'organe de direction suivent régulièrement des formations (article 20, paragraphe 2).",
    "ue.meta.26": "À l'égard d'une entité essentielle, l'autorité peut demander une interdiction temporaire d'exercer des fonctions de direction (article 32, paragraphe 5, point b)).",
    "ue.meta.27": "Le plafond minimal est fixé par la directive",
    "ue.meta.28": "Deux valeurs sont comparées : un montant forfaitaire en euros et un pourcentage du chiffre d'affaires annuel mondial total de l'entreprise au cours de l'exercice précédent. La plus élevée constitue la limite supérieure que l'État membre doit au minimum prévoir. Le droit national peut la relever.",
    "ue.meta.29": "Le montant dans la limite du plafond est fixé par l'autorité nationale",
    "ue.meta.3": "Le plafond de la directive dépasse {p0} fois le chiffre d'affaires annuel de l'entité. L'article 34, paragraphe 1, exige que l'amende soit proportionnée aux circonstances de l'espèce — il s'agit d'une limite supérieure, non d'une amende attendue.",
    "ue.meta.30": "L'amende doit être effective, proportionnée et dissuasive selon les circonstances de l'espèce. L'autorité tient compte au moins des critères de l'article 32, paragraphe 7 : gravité et durée de l'infraction, infractions antérieures, dommages, caractère intentionnel, mesures correctives et coopération.",
    "ue.meta.31": "Le plafond peut dépasser plusieurs fois le chiffre d'affaires annuel — c'est une limite supérieure, non un montant attendu. Les minima nationaux, les astreintes et les modalités de fixation sont déterminés par la loi de l'État membre.",
    "ue.meta.32": "Pour décider s'il y a lieu d'infliger une amende administrative et pour en fixer le montant, il est dûment tenu compte, dans chaque cas d'espèce, au moins des éléments énumérés à l'article 32, paragraphe 7.",
    "ue.meta.33": "la gravité de l'infraction et l'importance des dispositions violées — sont considérés comme graves dans tous les cas : les infractions répétées, l'absence de notification ou de remédiation d'incidents importants, l'absence de correction des manquements malgré des injonctions contraignantes, l'obstruction aux audits ou au suivi, la fourniture d'informations fausses ou manifestement inexactes",
    "ue.meta.34": "toute infraction antérieure pertinente commise par l'entité",
    "ue.meta.35": "tout dommage matériel ou moral causé, y compris les pertes financières, l'incidence sur d'autres services et le nombre d'utilisateurs touchés",
    "ue.meta.36": "le caractère intentionnel ou non de l'infraction",
    "ue.meta.37": "les mesures prises pour prévenir ou atténuer le dommage",
    "ue.meta.38": "l'adhésion à des codes de conduite approuvés ou à des mécanismes de certification",
    "ue.meta.39": "le degré de coopération avec les autorités compétentes",
    "ue.meta.4": "Directive (UE) 2022/2555 du Parlement européen et du Conseil (NIS 2)",
    "ue.meta.40": "La directive ne prévoit pas expressément de renonciation à l'amende — le droit national décide si et quand elle est possible.",
    "ue.meta.41": "À partir de cette date, les États membres doivent appliquer les dispositions nationales transposant la directive. La date précise à partir de laquelle l'autorité peut infliger une amende résulte du droit national.",
    "ue.meta.42": "Entrée en vigueur de la directive NIS 2",
    "ue.meta.43": "Le vingtième jour suivant la publication au Journal officiel.",
    "ue.meta.44": "Délai de transposition de la directive",
    "ue.meta.45": "Avant cette date, les États membres devaient adopter et publier les dispositions nationales.",
    "ue.meta.46": "Application des dispositions nationales et abrogation de NIS 1",
    "ue.meta.47": "À partir de cette date, les États appliquent les dispositions de transposition ; la directive (UE) 2016/1148 est abrogée.",
    "ue.meta.48": "Application du règlement (UE) 2024/2690",
    "ue.meta.49": "Le règlement d'exécution est directement applicable à partir du vingtième jour suivant sa publication.",
    "ue.meta.5": "JO UE L 333 du 27.12.2022",
    "ue.meta.50": "Liste des entités essentielles et importantes",
    "ue.meta.51": "Avant cette date, les États membres établissent la liste ; les entités communiquent leurs données d'enregistrement aux autorités.",
    "ue.meta.52": "Premier réexamen de la directive par la Commission",
    "ue.meta.53": "La Commission réexamine le fonctionnement de la directive et présente un rapport.",
    "ue.meta.54": "Alerte précoce d'un incident important",
    "ue.meta.55": "24 heures après en avoir eu connaissance",
    "ue.meta.56": "Notification d'un incident important",
    "ue.meta.57": "72 heures après en avoir eu connaissance",
    "ue.meta.58": "Rapport final",
    "ue.meta.59": "un mois après la notification de l'incident",
    "ue.meta.6": "Règlement d'exécution (UE) 2024/2690 de la Commission",
    "ue.meta.60": "Notification d'un incident par un prestataire de services de confiance",
    "ue.meta.61": "article 21, paragraphe 5, de la directive (UE) 2022/2555 ; articles 1er et 2 du règlement (UE) 2024/2690",
    "ue.meta.62": "Sans données sur le chiffre d'affaires, le plafond est le montant forfaitaire de la directive.",
    "ue.meta.63": "Les plafonds de l'article 34, paragraphes 4 et 5, sont des minima (« au moins ») — le droit national peut en prévoir de plus élevés. Montants en euros, sans conversion en monnaie nationale.",
    "ue.meta.64": "Autorité compétente de l'État membre",
    "ue.meta.65": "L'organe de direction peut être tenu responsable des violations de l'article 21. L'étendue et les modalités sont déterminées par le droit national — ce module ne les connaît pas.",
    "ue.meta.66": "L'étendue de la responsabilité personnelle de la direction résulte de la loi nationale. Pour la Pologne, elle va jusqu'à 300 % de la rémunération (article 73a, paragraphe 4, de la loi sur le système national de cybersécurité) ; les autres pays en décident autrement.",
    "ue.meta.7": "JO UE L, 2024/2690",
    "ue.meta.8": "Directive (UE) 2022/2555",
    "ue.meta.9": "Le délai de transposition a expiré le 17 octobre 2024",
    "ue.moduly.1": "environ {p0} min",
    "ue.moduly.10": "Dix domaines de l'article 21, paragraphe 2, points a) à j) : de la politique de risque à l'authentification multifacteur. La violation est passible d'une amende au titre de l'article 34. Évaluation sur l'échelle de maturité.",
    "ue.moduly.11": "Règlement 2024/2690 — gouvernance et processus",
    "ue.moduly.12": "Sections 1 à 5 et 7 à 8 de l'annexe : politiques, gestion des risques, gestion des incidents, continuité des activités, chaîne d'approvisionnement, évaluation de l'efficacité, cyberhygiène. Directement applicable depuis le 7 novembre 2024.",
    "ue.moduly.13": "Règlement 2024/2690 — exigences techniques",
    "ue.moduly.14": "Sections 6 et 9 à 13 de l'annexe : acquisition et développement des systèmes, cryptographie, sécurité des ressources humaines, contrôle d'accès, gestion des actifs, sécurité physique et environnementale.",
    "ue.moduly.2": "environ {p0} h {p1} min",
    "ue.moduly.3": "environ {p0} h",
    "ue.moduly.4": "moins d'une minute",
    "ue.moduly.5": "Évaluation rapide des risques",
    "ue.moduly.6": "Questions transversales issues de tous les domaines de la directive. Chacune tranche pour un groupe entier de sujets. Permet d'estimer l'ampleur du retard sans parcourir tout le questionnaire.",
    "ue.moduly.7": "Obligations issues de la directive",
    "ue.moduly.8": "Données d'enregistrement, notification des incidents sous 24 et 72 heures, obligations de l'organe de direction, préparation à la surveillance. Vérifiable sur documents, sans analyse technique.",
    "ue.moduly.9": "Mesures de gestion des risques — article 21, paragraphe 2",
    "ue.obowiazki.1": "Données d'enregistrement pour la liste des entités",
    "ue.obowiazki.10": "Notification des incidents importants",
    "ue.obowiazki.11": "L'entité notifie les incidents importants au CSIRT ou à l'autorité compétente en trois étapes : alerte précoce, notification, rapport final. Les délais courent à compter de la prise de connaissance de l'incident.",
    "ue.obowiazki.12": "L'entité est-elle en mesure de transmettre une alerte précoce dans les 24 heures suivant la prise de connaissance d'un incident important, en indiquant si l'incident est présumé résulter d'actes illicites et s'il peut avoir un impact transfrontière ?",
    "ue.obowiazki.13": "24 heures après la prise de connaissance",
    "ue.obowiazki.14": "L'entité est-elle en mesure de transmettre une notification d'incident dans les 72 heures, avec une évaluation initiale de la gravité et de l'impact et des indicateurs de compromission ?",
    "ue.obowiazki.15": "72 heures après la prise de connaissance",
    "ue.obowiazki.16": "L'entité transmet-elle un rapport final au plus tard un mois après la notification, avec la description de l'incident, le type de menace, les mesures d'atténuation et l'impact transfrontière ?",
    "ue.obowiazki.17": "un mois après la notification",
    "ue.obowiazki.18": "L'entité informe-t-elle les destinataires de ses services des incidents importants susceptibles de nuire à la fourniture de ces services ?",
    "ue.obowiazki.19": "L'entité informe-t-elle les destinataires de ses services d'une cybermenace importante et des mesures correctives qu'ils peuvent prendre ?",
    "ue.obowiazki.2": "Les États membres établissent une liste des entités essentielles et importantes et exigent des entités qu'elles communiquent leurs données d'enregistrement. Les modalités, le délai et le portail sont fixés par le droit national.",
    "ue.obowiazki.20": "Si l'entité est un prestataire de services de confiance — notifie-t-elle les incidents importants dans les 24 heures suivant la prise de connaissance ?",
    "ue.obowiazki.21": "concerne les prestataires de services de confiance",
    "ue.obowiazki.22": "Organe de direction",
    "ue.obowiazki.23": "L'organe de direction approuve les mesures de gestion des risques, supervise leur mise en œuvre et peut être tenu responsable. Les membres de l'organe suivent régulièrement des formations.",
    "ue.obowiazki.24": "L'organe de direction a-t-il formellement approuvé les mesures de gestion des risques en matière de cybersécurité prises pour se conformer à l'article 21 ?",
    "ue.obowiazki.25": "L'organe de direction supervise-t-il la mise en œuvre de ces mesures de manière documentée — par exemple par des rapports et des revues périodiques ?",
    "ue.obowiazki.26": "Les membres de l'organe de direction suivent-ils régulièrement des formations leur permettant d'identifier les risques et d'évaluer les pratiques de gestion des risques, avec une participation documentée ?",
    "ue.obowiazki.27": "Préparation aux mesures de surveillance",
    "ue.obowiazki.28": "Une entité essentielle est soumise à la surveillance ex ante et ex post, une entité importante uniquement à la surveillance ex post. L'autorité peut demander des informations, des preuves de mise en œuvre des politiques et les résultats d'audits.",
    "ue.obowiazki.29": "L'entité est-elle en mesure, à la demande de l'autorité, de fournir des preuves de la mise en œuvre de ses politiques de cybersécurité, y compris les résultats d'audits de sécurité ?",
    "ue.obowiazki.3": "L'entité a-t-elle déterminé si elle est une entité essentielle ou importante, sur la base du secteur de l'annexe I ou II et de la taille de l'entreprise ?",
    "ue.obowiazki.30": "L'entité est-elle en mesure, à la demande de l'autorité, de fournir les données, documents et informations nécessaires à l'exercice des missions de surveillance ?",
    "ue.obowiazki.31": "L'entité essentielle est-elle préparée à un audit de sécurité réalisé par l'autorité ou un organisme indépendant, à ses propres frais ?",
    "ue.obowiazki.4": "L'entité a-t-elle communiqué à l'autorité compétente ses données d'enregistrement : nom, adresse et coordonnées, secteur et sous-secteur, liste des États membres où elle fournit des services ?",
    "ue.obowiazki.5": "Les coordonnées comprennent les adresses électroniques, les plages d'adresses IP et les numéros de téléphone. Le délai national et le portail d'enregistrement sont fixés par le droit de l'État membre.",
    "ue.obowiazki.6": "Existe-t-il un processus de mise à jour des données d'enregistrement sans retard injustifié après leur modification ?",
    "ue.obowiazki.7": "La directive exige une mise à jour sans retard injustifié ; un délai précis — par exemple 14 jours en Pologne — résulte du droit national.",
    "ue.obowiazki.8": "Si l'entité est un fournisseur de services DNS, un registre TLD, un fournisseur de services en nuage, de centre de données, de CDN, de services gérés, une place de marché en ligne, un moteur de recherche ou un réseau social — a-t-elle communiqué les données supplémentaires de l'article 27, y compris l'adresse de son établissement principal dans l'Union ?",
    "ue.obowiazki.9": "concerne les entités visées à l'article 26, paragraphe 1",
    "ue.role.1": "Autorité compétente de l'État membre",
    "ue.role.10": "Services de centre de données : colocation, hébergement d'infrastructure et services associés.",
    "ue.role.11": "Centres de données",
    "ue.role.12": "Entité essentielle au-dessus du seuil de la moyenne entreprise (article 3, paragraphe 1, point a)), importante à taille moyenne (article 3, paragraphe 2). En dessous de la taille moyenne — hors du champ, sauf si l'État membre désigne l'entité au titre de l'article 2, paragraphe 2, points b) à e). Couvert par le règlement 2024/2690.",
    "ue.role.13": "Fournisseur de point d'échange internet",
    "ue.role.14": "Infrastructure permettant l'échange de trafic entre des réseaux indépendants.",
    "ue.role.15": "Points d'échange internet",
    "ue.role.16": "Classification selon la taille (article 3, paragraphe 1, point a), et paragraphe 2). Le règlement 2024/2690 ne couvre pas les points d'échange internet — l'article 1er du règlement contient une liste fermée de destinataires.",
    "ue.role.17": "Fournisseur de services DNS",
    "ue.role.18": "Services de résolution de noms de domaine, à l'exclusion des opérateurs de serveurs racines.",
    "ue.role.19": "Système de noms de domaine",
    "ue.role.2": "autorité compétente",
    "ue.role.20": "Entité essentielle quelle que soit sa taille (article 3, paragraphe 1, point b)). Couvert par le règlement 2024/2690.",
    "ue.role.21": "Registre de noms de domaine de premier niveau",
    "ue.role.22": "Tenue d'un registre de domaine de premier niveau.",
    "ue.role.23": "Entité essentielle quelle que soit sa taille (article 3, paragraphe 1, point b)). En outre, obligations relatives aux données d'enregistrement de l'article 28. Couvert par le règlement 2024/2690.",
    "ue.role.24": "Fournisseur de services d'informatique en nuage",
    "ue.role.25": "Services d'informatique en nuage : infrastructure, plateforme, logiciel en tant que service.",
    "ue.role.26": "Services d'informatique en nuage",
    "ue.role.27": "Classification selon la taille (article 3, paragraphe 1, point a), et paragraphe 2). Couvert par le règlement 2024/2690.",
    "ue.role.28": "Fournisseur de réseau de diffusion de contenu",
    "ue.role.29": "Réseau de serveurs répartis fournissant contenus et services aux utilisateurs finaux.",
    "ue.role.3": "désignée par le droit national ; jusqu'à la mise en place du module national, l'outil ne nomme aucune institution précise",
    "ue.role.30": "Réseaux de diffusion de contenu",
    "ue.role.31": "Prestataire de services de confiance",
    "ue.role.32": "Services de confiance au sens du règlement (UE) n° 910/2014 : signatures, cachets, horodatages, certificats.",
    "ue.role.33": "Services de confiance",
    "ue.role.34": "Couvert par la directive quelle que soit sa taille (article 2, paragraphe 2, point a) ii)). Un prestataire qualifié est une entité essentielle quelle que soit sa taille (article 3, paragraphe 1, point b)) ; un prestataire non qualifié est essentiel au-dessus du seuil de la moyenne entreprise, important sinon. Couvert par le règlement 2024/2690.",
    "ue.role.35": "Fournisseur de services gérés",
    "ue.role.36": "Gestion de l'infrastructure TIC du client : installation, maintenance, support, administration des systèmes.",
    "ue.role.37": "Gestion des services TIC (interentreprises)",
    "ue.role.38": "Services gérés",
    "ue.role.39": "Fournisseur de services de sécurité gérés",
    "ue.role.4": "Fournisseur de réseaux de communications électroniques publics ou de services de communications électroniques accessibles au public",
    "ue.role.40": "Services gérés dans le domaine de la cybersécurité : supervision, réponse aux incidents, tests, conseil.",
    "ue.role.41": "Services de sécurité gérés",
    "ue.role.42": "La directive classe selon la taille (article 3, paragraphe 1, point a), et paragraphe 2). Les États membres peuvent durcir le seuil — la Pologne considère un MSSP comme entité essentielle dès la petite entreprise ; ce module applique uniquement la règle de la directive. Couvert par le règlement 2024/2690.",
    "ue.role.5": "Fourniture de réseaux de communications électroniques publics ou de services de communications électroniques accessibles au public, y compris l'accès à internet.",
    "ue.role.6": "Infrastructure numérique",
    "ue.role.7": "Communications électroniques",
    "ue.role.8": "Couvert par la directive quelle que soit sa taille (article 2, paragraphe 2, point a) i)). Une entreprise moyenne ou plus grande est une entité essentielle (article 3, paragraphe 1, point c)), une micro ou petite entreprise une entité importante (article 3, paragraphe 2). La loi nationale sur les télécommunications peut imposer des obligations supplémentaires — ce module ne les contient pas.",
    "ue.role.9": "Fournisseur de services de centre de données",
    "ue.role.podstawaArt3b": "article 3, paragraphe 1, point b), de la directive (UE) 2022/2555",
    "ue.zaslepki.1": "Directive (UE) 2022/2555 du Parlement européen et du Conseil (NIS 2)",
    "ue.zaslepki.10": "Le droit national décide si certaines entités sont inscrites d'office.",
    "ue.zaslepki.11": "Déterminez si vous relevez de la directive",
    "ue.zaslepki.12": "Secteur de l'annexe I ou II et taille de l'entreprise. Cette partie est prise en charge par le profil de l'entité dans cet outil.",
    "ue.zaslepki.13": "Identifiez l'autorité compétente dans votre pays",
    "ue.zaslepki.14": "Chaque État désigne une autorité compétente (article 8, paragraphe 1). L'ENISA et la Commission tiennent la liste à jour.",
    "ue.zaslepki.15": "Communiquez les données d'enregistrement",
    "ue.zaslepki.16": "Nom, adresse et coordonnées, secteur et sous-secteur, États où les services sont fournis (article 3, paragraphe 4). Modalités selon le droit national.",
    "ue.zaslepki.17": "Mettez les données à jour sans retard injustifié",
    "ue.zaslepki.18": "Toute modification des données d'enregistrement exige une mise à jour (article 3, paragraphe 5).",
    "ue.zaslepki.19": "adresse et coordonnées à jour : adresses électroniques, plages d'adresses IP, numéros de téléphone",
    "ue.zaslepki.2": "JO UE L 333 du 27.12.2022, p. 80",
    "ue.zaslepki.20": "secteur et sous-secteur de l'annexe I ou II",
    "ue.zaslepki.21": "liste des États membres dans lesquels l'entité fournit des services",
    "ue.zaslepki.22": "Fixé par le droit national.",
    "ue.zaslepki.23": "Directive (UE) 2022/2555 — article 3",
    "ue.zaslepki.24": "ENISA — autorités compétentes des États membres",
    "ue.zaslepki.25": "Directive (UE) 2022/2555",
    "ue.zaslepki.26": "Le module de l'UE ne contient pas de lignes directrices d'une autorité nationale — elles viendront avec le module de droit national.",
    "ue.zaslepki.27": "La récupération automatique des données de registre ne fonctionne que pour les pays disposant d'un module de droit national. Remplissez le profil manuellement.",
    "ue.zaslepki.28": "La lecture des états financiers ne fonctionne que pour les pays disposant d'un module de droit national. Saisissez manuellement le chiffre d'affaires et l'effectif.",
    "ue.zaslepki.3": "Règlement d'exécution (UE) 2024/2690 de la Commission",
    "ue.zaslepki.4": "JO UE L, 2024/2690, 18.11.2024",
    "ue.zaslepki.5": "La directive NIS 2 ne contient pas de couche distincte pour les communications électroniques. Le droit national des communications électroniques peut imposer des obligations supplémentaires — ce module ne les connaît pas.",
    "ue.zaslepki.6": "Liste des entités essentielles et importantes",
    "ue.zaslepki.7": "Autorité compétente de l'État membre.",
    "ue.zaslepki.8": "La directive impose aux États membres de tenir une liste des entités essentielles et importantes et d'exiger des entités qu'elles communiquent leurs données d'enregistrement. Le portail, les modalités et le délai sont fixés par le droit national — ce module ne les connaît pas, car le module de droit national du pays sélectionné n'est pas encore prêt.",
    "ue.zaslepki.9": "Toutes les entités essentielles et importantes. Le délai est fixé par le droit national.",
    "ue.zaslepki.skrotDyrektywy": "directive NIS 2",
    "ue.zaslepki.skrotReg2690": "règl. 2024/2690",
    "xlsx.1": "{p0} – {p1} EUR",
    "xlsx.25": "Taux de change",
    "xlsx.4": "RAPPORT DE CONFORMITÉ À LA DIRECTIVE NIS 2 (UE) 2022/2555",
    "xlsx.58": "Activité de communications électroniques : le règlement (UE) 2024/2690 ne s'applique pas. Les seuils sont fixés par le droit national (article 23, paragraphe 11, de la directive) — le module commun ne les connaît pas.",
    "xlsx.68": "L'outil sert à l'autoévaluation. Il ne constitue ni un audit ni un avis juridique.",
    "xlsx.69": "Pour les entités non couvertes par le règlement (UE) 2024/2690, les seuils de l'incident important sont fixés par le droit national (article 23, paragraphe 11, de la directive).",
    "xlsx.70": "Les rôles indiqués dans le profil sont une déclaration. Le statut dépend de l'activité réellement exercée (article 3 de la directive (UE) 2022/2555).",
    "xlsx.etykietaKrs": "Numéro de registre",
    "xlsx.etykietaNip": "Numéro d'identification",
    "xlsx.etykietaRegon": "Numéro statistique"
});
