/* Teksty modułu ue — język: ga.
   Te same klucze co w napisy/pl.js (wersja źródłowa); wstawki {p0}, {p1}…
   pozostają bez zmian. Klucze ue.cyt.* to wzorce składania odesłań
   do przepisów w tym języku — patrz kraje/ue/cytaty.js. */
KRAJE.napisy('ue', 'ga', {
    "app.10": "Seiceáil liosta na ról thíos — is í an ghníomhaíocht a dhéantar i ndáiríre a chinneann an stádas (Airteagal 3 de Threoir (AE) 2022/2555), ní iontráil i gclár.",
    "app.14": "Bliain roimhe sin: EUR {p0}",
    "app.15": "Ioncam don tréimhse tuairiscithe: EUR {p0}",
    "app.19": "Ag ceistiú clár de réir uimhir {p0}…",
    "app.34": " billiún EUR",
    "app.35": " milliún EUR",
    "app.36": " míle EUR",
    "app.37": "",
    "app.4": "Níl aisghabháil uathoibríoch sonraí clár ar fáil don tír seo — líon isteach an phróifíl de láimh.",
    "app.59": "Measúnú comhlíonta Threoir NIS 2 (JSON)",
    "app.68": "Níl aon chlár ann don tír seo óna bhféadfadh an uirlis sonraí a aisghabháil — líontar an phróifíl isteach de láimh.",
    "app.69": "Níl aon chlár ann don tír seo óna bhféadfadh an uirlis sonraí a aisghabháil. Cliceáil chun an mód as líne a chur ar siúl.",
    "app.73": " · cuntas brabúis agus caillteanais sa leagan ",
    "app.74": "<div class=\"mt-2 tekst-uwaga\">Ní léiríonn sonraí an chláir aon ról in earnáil an bhonneagair dhigitigh. Roghnaigh na róil de láimh thíos.</div>",
    "app.8": "Iontráil i gclár na soláthraithe cumarsáide leictreonaí deimhnithe",
    "app.progDostawcy": "",
    "app.przyklad.adres": "1 Sráid an tSampla, Baile",
    "app.przyklad.forma": "Cuideachta phríobháideach faoi theorainn scaireanna",
    "app.przyklad.nazwa": "Oibreoir Samplach Teo.",
    "app.statusVat": " · stádas CBL: ",
    "dashboard.1": "Bunaithe ar na róil agus ar an méid dearbhaithe, ní eintiteas riachtanach ná eintiteas tábhachtach é an t-eintiteas de réir bhrí Airteagal 3 de Threoir (AE) 2022/2555. Seiceáil an phróifíl má tá an toradh difriúil ón méid a rabhthas ag súil leis.",
    "dashboard.113": "Ceisteanna coitianta",
    "dashboard.12": "— {p0}; chuaigh an spriocdháta trasuite sa dlí náisiúnta in éag an {p2}",
    "dashboard.123": "Treoir NIS 2",
    "dashboard.30": "Liosta na n-eintiteas riachtanach agus tábhachtach",
    "dashboard.4": "— infheidhme go díreach ó {p0} i ngach Ballstát, gan trasuí",
    "dashboard.42": "Leagan méid seasta: {p0}",
    "dashboard.45": "Critéir ó Airteagal 32(7) den Treoir:",
    "dashboard.46": "Iomlán",
    "dashboard.49": "Déanann an t-eintiteas gníomhaíocht cumarsáide leictreonaí — is é an dlí náisiúnta a chinneann dliteanas an duine bainistíochta",
    "dashboard.50": "",
    "dashboard.51": "",
    "dashboard.53": "Pionós tréimhsiúil as moill ar chinneadh a chomhlíonadh: ó EUR {p0} go EUR {p1} in aghaidh an lae ({p2})",
    "dashboard.54": "Cás cáilithe: suas le EUR {p0} ({p1})",
    "dashboard.57": "({p0}). Is é an gníomh lena dtrasuítear an Treoir a chinneann cathain is féidir leis an údarás náisiúnta fíneálacha a ghearradh — níl a fhios ag an modúl seo. Eascraíonn oibleagáidí cur chun feidhme ón dlí náisiúnta ón lá a thagann sé i bhfeidhm.",
    "dashboard.65": "({p0}). Is é an gníomh lena dtrasuítear an Treoir a chinneann cathain is féidir leis an údarás náisiúnta fíneálacha a ghearradh — níl a fhios ag an modúl seo. Ní dhátaítear an riosca airgeadais anseo dá bhrí sin, agus eascraíonn oibleagáidí cur chun feidhme ón dlí náisiúnta ón lá a thagann sé i bhfeidhm.",
    "dashboard.83": "Gníomhaíocht cumarsáide leictreonaí — is é an dlí náisiúnta a leagann síos na tairseacha.",
    "dashboard.84": "Níl feidhm ag Rialachán (AE) 2024/2690 maidir le soláthraithe líonraí agus seirbhísí cumarsáide leictreonaí poiblí. Ina gcás siúd, is é an dlí náisiúnta a leagann síos na tairseacha do theagmhas suntasach (Airteagal 23(11) den Treoir) — níl a fhios ag an modúl seo iad, mar sin ní thugann sé aon fhigiúirí.",
    "dashboard.terminRejestracji": "Is é an dlí náisiúnta a leagann síos an spriocdháta chun sonraí clárúcháin a chur isteach (Airteagal 3(4) den Treoir). Cuireann soláthraithe faoi Airteagal 27(1) — soláthraithe seirbhísí DNS, clárlanna ainmneacha TLD, soláthraithe seirbhísí néalríomhaireachta, lárionad sonraí, líonraí seachadta ábhair, seirbhísí bainistithe agus seirbhísí slándála bainistithe — a gcuid sonraí isteach chuig clár ENISA: ar dtús faoin 17 Eanáir 2025, agus gach athrú gan moill mhíchuí.",
    "html.1": "ITORO — Measúnú comhlíonta Threoir NIS 2 (AE) 2022/2555",
    "html.10": "Measúnú comhlíonta Threoir NIS 2 — modúl coiteann",
    "html.100": "Ní oibríonn léamh ráitis airgeadais ach do thíortha a bhfuil modúl dlí náisiúnta acu. Don tír seo cuireann tú isteach an <strong>t-ioncam</strong> don bhliain airgeadais de láimh — braitheann leibhéal na fíneála air.",
    "html.102": "Ní oibríonn aisghabháil uathoibríoch sonraí clár ach do thíortha a bhfuil modúl dlí náisiúnta acu. Sonraíonn tú na róil agus méid an fhiontair de láimh.",
    "html.11": "Éilíonn Treoir (AE) 2022/2555 (NIS 2) trasuí sa dlí náisiúnta. Cumhdaíonn an measúnú na hoibleagáidí a eascraíonn go díreach ón Treoir agus Rialachán Cur Chun Feidhme (AE) 2024/2690 ón gCoimisiún, a bhfuil feidhm dhíreach aige — a mhéid a bhaineann siad leis an eintiteas.",
    "html.23": "cuireann tú isteach ioncam agus méid de láimh — ní cheistíonn an modúl coiteann cláir náisiúnta",
    "html.33": "Treoir (AE) 2022/2555 ó Pharlaimint na hEorpa agus ón gComhairle an 14 Nollaig 2022 (NIS 2)",
    "html.33a": "{p0} — an gníomh náisiúnta lena dtrasuítear an Treoir; ní dhéanann an modúl seo a cheanglais a mheas go fóill",
    "html.33b": "níor ghlac an Stát gníomh trasuite go fóill — leanann an measúnú dlí an Aontais",
    "html.35": "oibleagáidí an chomhlachta bainistíochta — Airteagal 20 den Treoir",
    "html.36": "Is chun féinmheasúnaithe an uirlis. Ní iniúchadh ná comhairle dlí í.",
    "html.40": "ní dhéanann an modúl coiteann aon naisc amach ar chor ar bith — ní cheistíonn sé cláir",
    "html.59": "Ráitis airgeadais",
    "html.60": "Níl léamh ráitis airgeadais ar fáil ach do thíortha a bhfuil modúl dlí náisiúnta acu. Don tír seo cuireann tú isteach ioncam agus líon foirne de láimh.",
    "html.62": "Cuardach cláir",
    "html.63": "is cláir náisiúnta iad cláir ghnó — níl a fhios ag an modúl coiteann iad",
    "html.64": "sonraíonn tú na róil agus méid an fhiontair de láimh",
    "html.66": "Uimhir aitheantais an eintitis",
    "html.68": "Ní oibríonn aisghabháil uathoibríoch sonraí clár ach do thíortha a bhfuil modúl dlí náisiúnta acu.",
    "html.76": "Ioncam bliantúil (EUR)",
    "html.78": "Ioncam ó ghníomhaíocht cumarsáide leictreonaí (EUR)",
    "html.79": "Baineann an réimse le soláthraithe líonraí nó seirbhísí cumarsáide leictreonaí poiblí. Is é dlí an Bhallstáit a leagann síos na tairseacha náisiúnta.",
    "html.80": "Luach saothair míosúil an chinn (EUR)",
    "html.82": "Ráta malairte",
    "html.83": "Sloinntear uasteorainneacha na bhfíneálacha sa Treoir in euro. Is é an dlí náisiúnta a chinneann an comhshó go hairgeadra náisiúnta agus an ráta — tugtar na méideanna anseo in euro gan comhshó.",
    "html.84": "Eascraíonn an stádas ó chomhiomlánú sonraí fiontar nasctha amháin, agus tá córas faisnéise an eintitis neamhspleách (aithris 16 den Treoir — is é an dlí náisiúnta a chinneann an cur i bhfeidhm)",
    "html.85": "Oibríonn an t-eintiteas i réimsí na slándála náisiúnta, na slándála poiblí, na cosanta nó fhorfheidhmiú an dlí (Airteagal 2(7) den Treoir)",
    "html.91": "Measúnú comhlíonta Threoir (AE) 2022/2555 ó Pharlaimint na hEorpa agus ón gComhairle (NIS 2) agus Rialachán Cur Chun Feidhme (AE) 2024/2690 ón gCoimisiún — modúl coiteann do thíortha nach bhfuil a modúl dlí náisiúnta réidh go fóill.",
    "html.94": "an eintiteas <strong>riachtanach</strong>, <strong>tábhachtach</strong> nó lasmuigh de raon feidhme na Treorach é an t-eintiteas",
    "html.daneZeSprawozdania": "ainm, uimhir aitheantais, seoladh na hoifige cláraithe",
    "html.rejestrMozliwy": "Tá clár {p0} poiblí agus saor in aisce — is féidir a léamh a chur leis an uirlis; fáiltímid roimh pull requests (féach an README).",
    "html.tytulNaglowka": "Measúnú comhlíonta Threoir NIS 2",
    "html.zrodlaRecznie": "Níl aithne ag an modúl seo ar chláir do Stáit — líon isteach an phróifíl de láimh. Is é an láimhdeachas bliantúil a chinneann uasteorainn na fíneála, mar sin cuir isteach go cruinn é.",
    "klasyfikacja.10": "Airteagal 3(1)(c) de Threoir (AE) 2022/2555 (soláthraí líonraí cumarsáide leictreonaí poiblí nó seirbhísí cumarsáide leictreonaí atá ar fáil go poiblí ar fiontar meánmhéide ar a laghad é)",
    "klasyfikacja.11": "Airteagal 3(2) i gcomhar le hAirteagal 2(2)(a)(i) de Threoir (AE) 2022/2555 (soláthraí líonraí nó seirbhísí cumarsáide leictreonaí poiblí ar micreafhiontar nó fiontar beag é)",
    "klasyfikacja.12": "Airteagal 3(1)(a) de Threoir (AE) 2022/2555 (soláthraí seirbhísí slándála bainistithe a sháraíonn na huasteorainneacha d'fhiontar meánmhéide)",
    "klasyfikacja.13": "Níl micreafhiontair ná fiontair bheaga cumhdaithe ag an Treoir de bharr an róil seo (Airteagal 2(1) a contrario).",
    "klasyfikacja.15": "Airteagal 3(1)(b) de Threoir (AE) 2022/2555 (soláthraí cáilithe seirbhísí iontaoibhe) — beag beann ar mhéid an fhiontair",
    "klasyfikacja.16": "Airteagal 3(2) i gcomhar le hAirteagal 2(2)(a)(ii) de Threoir (AE) 2022/2555 (soláthraí neamhcháilithe seirbhísí iontaoibhe ar micreafhiontar, fiontar beag nó fiontar meánmhéide é)",
    "klasyfikacja.18": "Airteagal 3(2) de Threoir (AE) 2022/2555 (eintiteas riaracháin phoiblí ar leibhéal réigiúnach, i gcás ina bhforálann an Ballstát amhlaidh — Airteagal 2(2)(f)(ii))",
    "klasyfikacja.19": "Airteagal 3(1)(f) de Threoir (AE) 2022/2555 (eintiteas riaracháin phoiblí ar leibhéal an rialtais láir — Airteagal 2(2)(f)(i))",
    "klasyfikacja.2": "Maoirseacht ex ante agus ex post (Airteagal 32 de Threoir (AE) 2022/2555).",
    "klasyfikacja.20": "Airteagal 3(2) de Threoir (AE) 2022/2555 (eintiteas riaracháin phoiblí ar leibhéal réigiúnach — Airteagal 2(2)(f)(ii))",
    "klasyfikacja.21": "Is é an dlí náisiúnta a chinneann raon feidhme oibleagáidí eintiteas riaracháin phoiblí ar leibhéal áitiúil (Airteagal 2(5)(a) den Treoir).",
    "klasyfikacja.22": "Féadfaidh Ballstát eintitis a dhíolmhú a dhéanann gníomhaíochtaí i réimsí na slándála náisiúnta, na slándála poiblí, na cosanta nó fhorfheidhmiú an dlí (Airteagal 2(7) den Treoir). Ní oibríonn an díolúine uaithi féin — fíoraigh toradh an mheasúnaithe i gcoinne an dlí náisiúnta.",
    "klasyfikacja.23": "Comhlíonann an t-eintiteas critéir eintitis riachtanaigh agus eintitis thábhachtaigh araon. Is eintiteas riachtanach é (Airteagal 3(1) den Treoir), agus tá feidhm ag na ceanglais níos déine maidir leis an ngníomhaíocht go léir a chumhdaítear leis an Treoir.",
    "klasyfikacja.25": "Tá an t-eintiteas riachtanach, mar sin tá feidhm ag catalóg iomlán na mbeart faoi Airteagal 21(2) den Treoir agus ag maoirseacht ex ante agus ex post — cumhdaíonn an measúnú an tacar iomlán ceisteanna.",
    "klasyfikacja.26": "Mar eintiteas tábhachtach tá tú faoi réir na catalóige céanna beart faoi Airteagal 21(2), ach faoi réir maoirseachta ex post amháin (Airteagal 33). Tá uasteorainn na fíneála níos ísle: EUR 7 milliún nó 1,4 % den láimhdeachas (Airteagal 34(5)). Féadfaidh an dlí náisiúnta faoisimh d'eintitis phoiblí a thabhairt isteach — níl a fhios ag an modúl seo iad.",
    "klasyfikacja.28": "Eascraíonn oibleagáidí eintiteas riaracháin phoiblí ó Airteagal 2(2)(f) den Treoir; is é an dlí náisiúnta a chinneann a raon feidhme beacht, lena n-áirítear don leibhéal áitiúil agus d'institiúidí oideachais (Airteagal 2(5)).",
    "klasyfikacja.29": "Dearbhaíodh gur ó chomhiomlánú sonraí fiontar nasctha nó comhpháirtíochta amháin a eascraíonn stádas an eintitis, agus go bhfuil córas faisnéise an eintitis neamhspleách. Ceadaíonn an Treoir eisiamh den sórt sin (aithris 16), ach is é an dlí náisiúnta a chinneann é — glacann an modúl leis an eisiamh, nach mór a fhíorú i gcoinne dhlí an Bhallstáit agus a dhoiciméadú.",
    "klasyfikacja.4": "Maoirseacht ex post amháin — i gcás ina bhfuil fianaise, tásc nó faisnéis ann faoi shárú (Airteagal 33 de Threoir (AE) 2022/2555).",
    "klasyfikacja.5": "Lasmuigh de raon feidhme na Treorach",
    "klasyfikacja.6": "Níl aon oibleagáidí faoi Threoir (AE) 2022/2555 don ról sonraithe.",
    "klasyfikacja.7": "Airteagal 3(1)(a) de Threoir (AE) 2022/2555 (eintiteas de chineál a liostaítear in Iarscríbhinn I a sháraíonn na huasteorainneacha d'fhiontar meánmhéide)",
    "klasyfikacja.8": "Airteagal 3(2) de Threoir (AE) 2022/2555 (eintiteas de chineál a liostaítear in Iarscríbhinn I a chomhlíonann na critéir d'fhiontar meánmhéide)",
    "klasyfikacja.9": "Níl micreafhiontair ná fiontair bheaga cumhdaithe ag an Treoir de bharr an róil seo (Airteagal 2(1) a contrario).",
    "kreator.10": "Cuir isteach ioncam na bliana roimhe sin de láimh.",
    "kreator.35": "<span class=\"text-secondary\">Níl léamh ráiteas airgeadais ar fáil don tír seo.</span>",
    "kreator.37": "Níl léamh ráiteas airgeadais ar fáil don tír seo — cuir isteach an t-ioncam de láimh.",
    "kreator.56": "Tá — tá feidhm dhíreach ag Rialachán an AE ón 7 Samhain 2024 i ngach Ballstát agus níl aon idirthréimhse aige. Is é a bhunús",
    "kreator.57": ", a thug de chumhacht don Choimisiún na ceanglais theicniúla agus mhodheolaíocha a leagan síos do na soláthraithe a liostaítear in Airteagal 3(1) den Rialachán. Chuaigh an spriocdháta chun an Treoir a thrasuí in éag an",
    "kreator.58": ", agus is é an dlí náisiúnta a chinneann cathain is féidir leis an údarás náisiúnta fíneálacha a ghearradh. Tá ceanglais theicniúla na hIarscríbhinne (ranna 6 agus 9–13) ceangailteach mar atá siad — ní fhanann siad le soiléiriú. Ní féidir imeacht ach ó cheanglais a cháilítear leis an bhfrása \"i gcás inarb iomchuí\", agus le húdar doiciméadaithe amháin.",
    "kreator.9": "Ráitis airgeadais →",
    "kreator.przepisReg2690": "Airteagal 21(5) de Threoir (AE) 2022/2555",
    "kreator.terminReg2690": "17 Deireadh Fómhair 2024",
    "punktacja.10": "Eintitis phoiblí",
    "punktacja.4": "Treoir NIS 2 — Airteagal 21",
    "punktacja.5": "Treoir NIS 2 — oibleagáidí foirmiúla",
    "punktacja.8": "Cumarsáid leictreonach",
    "punktacja.9": "Treoir NIS 2 — eintitis phoiblí",
    "punktacja.skrotKsc": "NIS 2",
    "punktacja.skrotPke": "teileachumarsáid",
    "ue.cyt.akapit": ", an {p0} fomhír",
    "ue.cyt.art": "Airteagal {p0}",
    "ue.cyt.drugi": "dara",
    "ue.cyt.dyr": "{p0} de Threoir (AE) 2022/2555",
    "ue.cyt.i": "agus",
    "ue.cyt.laczenie": "",
    "ue.cyt.lit": "({p0})",
    "ue.cyt.litery": "",
    "ue.cyt.pkt": ", pointe {p0}",
    "ue.cyt.rozdzielacz": "; ",
    "ue.cyt.rozp": "{p0} de Rialachán (AE) 2024/2690",
    "ue.cyt.ust": "({p0})",
    "ue.katalog.1": "Beartais maidir le hanailís riosca agus slándáil na gcóras faisnéise",
    "ue.katalog.10": "Láimhseáil teagmhas",
    "ue.katalog.11": "Ciallaíonn láimhseáil teagmhas aon ghníomhartha agus nósanna imeachta atá dírithe ar theagmhas a chosc, a bhrath, a anailísiú agus a shrianadh nó freagairt dó agus téarnamh uaidh (Airteagal 6, pointe (8)).",
    "ue.katalog.12": "An bhfuil nós imeachta doiciméadaithe láimhseála teagmhas ann a chumhdaíonn brath, anailís, srianadh, freagairt agus téarnamh?",
    "ue.katalog.13": "ISO/IEC 27001 A.5.24–A.5.26",
    "ue.katalog.14": "An gcuireann an nós imeachta ar chumas an eintitis na spriocdhátaí tuairiscithe do theagmhas suntasach a chomhlíonadh: réamhrabhadh laistigh de 24 uair an chloig, fógra teagmhais laistigh de 72 uair an chloig, tuarascáil deiridh laistigh de mhí amháin?",
    "ue.katalog.15": "ISO/IEC 27001 A.5.24",
    "ue.katalog.16": "An bhfuil critéir ag an eintiteas chun teagmhas a mheas mar theagmhas suntasach, i gcomhréir le hAirteagal 23(3): cur isteach oibríochtúil tromchúiseach nó caillteanas airgeadais, nó damáiste suntasach do dhaoine eile?",
    "ue.katalog.17": "ISO/IEC 27001 A.5.25",
    "ue.katalog.18": "An dtaifeadtar teagmhais agus an n-úsáidtear na ceachtanna a foghlaimíodh óna láimhseáil chun na bearta a fheabhsú?",
    "ue.katalog.19": "ISO/IEC 27001 A.5.27",
    "ue.katalog.2": "Tá na bearta bunaithe ar chur chuige uile-ghuaiseacha (Airteagal 21(2)). Measúnaítear a gcomhréireacht ag cur san áireamh a mhéid atá an t-eintiteas neamhchosanta, méid an eintitis, dóchúlacht na dteagmhas agus a ndéine (Airteagal 21(1), an dara fomhír).",
    "ue.katalog.20": "Leanúnachas gnó agus bainistíocht géarchéime",
    "ue.katalog.21": "Leanúnachas gnó, amhail bainistíocht cúltaca agus téarnamh ó thubaistí, agus bainistíocht géarchéime.",
    "ue.katalog.22": "An bhfuil plean leanúnachais gnó ann a chumhdaíonn téarnamh tar éis tubaiste?",
    "ue.katalog.23": "ISO/IEC 27001 A.5.29–A.5.30",
    "ue.katalog.24": "An ndéantar cúltacaí, an gcosnaítear iad agus an dtástáiltear iad maidir le hin-athchóiritheacht?",
    "ue.katalog.25": "ISO/IEC 27001 A.8.13",
    "ue.katalog.26": "An bhfuil nósanna imeachta bainistíochta géarchéime ag an eintiteas le róil shainithe agus cainéil chumarsáide?",
    "ue.katalog.27": "ISO/IEC 27001 A.5.29",
    "ue.katalog.28": "An dtástáiltear pleananna leanúnachais agus téarnaimh go tréimhsiúil, agus na torthaí doiciméadaithe?",
    "ue.katalog.29": "ISO/IEC 27001 A.5.30",
    "ue.katalog.3": "An bhfuil beartas doiciméadaithe ag an eintiteas maidir le hanailís riosca agus slándáil na gcóras faisnéise, arna fhormheas ag an gcomhlacht bainistíochta?",
    "ue.katalog.30": "Slándáil an tslabhra soláthair",
    "ue.katalog.31": "Slándáil an tslabhra soláthair, lena n-áirítear gnéithe a bhaineann le slándáil maidir leis na caidrimh idir an t-eintiteas agus a sholáthraithe díreacha nó a sholáthraithe seirbhíse. Cuireann an t-eintiteas san áireamh na leochaileachtaí a bhaineann go sonrach le gach soláthraí agus cáilíocht fhoriomlán a tháirgí agus a chleachtas cibearshlándála (Airteagal 21(3)).",
    "ue.katalog.32": "An gcoimeádann an t-eintiteas liosta de sholáthraithe díreacha agus de sholáthraithe seirbhíse mar aon le measúnú ar a dtábhacht do shlándáil líonraí agus córas?",
    "ue.katalog.33": "ISO/IEC 27001 A.5.19",
    "ue.katalog.34": "Agus bearta á roghnú do sholáthraithe, an gcuirtear san áireamh na leochaileachtaí a bhaineann go sonrach le gach ceann acu agus cáilíocht a gcleachtas cibearshlándála agus forbartha slána?",
    "ue.katalog.35": "ISO/IEC 27001 A.5.19, A.5.21",
    "ue.katalog.36": "An bhfuil ceanglais slándála agus oibleagáid chun teagmhais agus leochaileachtaí a thuairisciú i gconarthaí le soláthraithe?",
    "ue.katalog.37": "ISO/IEC 27001 A.5.20",
    "ue.katalog.38": "An gcuireann an t-eintiteas san áireamh torthaí na measúnuithe comhordaithe riosca slándála ar shlabhraí soláthair criticiúla dá dtagraítear in Airteagal 22?",
    "ue.katalog.39": "ISO/IEC 27001 A.5.21",
    "ue.katalog.4": "ISO/IEC 27001 clásail 5.2, 6.1.2",
    "ue.katalog.40": "Slándáil i bhfáil, forbairt agus cothabháil córas",
    "ue.katalog.41": "Slándáil i bhfáil, forbairt agus cothabháil córas líonra agus faisnéise, lena n-áirítear láimhseáil agus nochtadh leochaileachtaí.",
    "ue.katalog.42": "An sainítear ceanglais slándála sula bhfaightear córas nó sula dtosaíonn a fhorbairt, agus an bhfíoraítear iad roimh imscaradh?",
    "ue.katalog.43": "ISO/IEC 27001 A.8.25–A.8.29",
    "ue.katalog.44": "An bhfuil próiseas láimhseála leochaileachtaí ann: sainaithint, measúnú, leigheas laistigh d'am sainithe?",
    "ue.katalog.45": "ISO/IEC 27001 A.8.8",
    "ue.katalog.46": "An bhfuil nós imeachta nochta leochaileachtaí ag an eintiteas, lena n-áirítear cainéal chun tuairiscí ó thríú páirtithe a fháil?",
    "ue.katalog.47": "An dtéann athruithe ar chórais trí phróiseas rialaithe bainistíochta athruithe le measúnú ar an tionchar ar shlándáil?",
    "ue.katalog.48": "ISO/IEC 27001 A.8.32",
    "ue.katalog.49": "Measúnú ar éifeachtacht na mbeart",
    "ue.katalog.5": "An gcumhdaíonn an anailís riosca gach guais do chórais líonra agus faisnéise agus dá dtimpeallacht fhisiciúil, ní cibearbhagairtí amháin?",
    "ue.katalog.50": "Beartais agus nósanna imeachta chun éifeachtacht na mbeart bainistíochta riosca cibearshlándála a mheasúnú.",
    "ue.katalog.51": "An bhfuil beartas doiciméadaithe ann chun éifeachtacht na mbeart a mheasúnú a shainíonn an raon feidhme, an mhinicíocht agus na modhanna?",
    "ue.katalog.52": "ISO/IEC 27001 clásal 9.1",
    "ue.katalog.53": "An ndéantar measúnuithe éifeachtachta go tréimhsiúil agus an dtuairiscítear a dtorthaí don chomhlacht bainistíochta?",
    "ue.katalog.54": "ISO/IEC 27001 clásail 9.2–9.3",
    "ue.katalog.55": "An mbíonn gníomhartha ceartaitheacha doiciméadaithe le húinéir agus spriocdháta mar thoradh ar laigí sainaitheanta?",
    "ue.katalog.56": "ISO/IEC 27001 clásal 10.1",
    "ue.katalog.57": "Cibearshláinteachas agus oiliúint",
    "ue.katalog.58": "Bunchleachtais chibearshláinteachais agus oiliúint chibearshlándála. Leanann comhaltaí an chomhlachta bainistíochta oiliúint rialta (Airteagal 20(2)).",
    "ue.katalog.59": "An gcuireann an t-eintiteas bunchleachtais chibearshláinteachais i bhfeidhm: nuashonruithe, bainistíocht pasfhocal, srianadh pribhléidí, cosaint ar bhogearraí mailíseacha?",
    "ue.katalog.6": "ISO/IEC 27001 clásal 6.1.2",
    "ue.katalog.60": "ISO/IEC 27001 A.8.7, A.8.8",
    "ue.katalog.61": "An bhfaigheann fostaithe oiliúint chibearshlándála atá curtha in oiriúint dá ról, agus rannpháirtíocht doiciméadaithe?",
    "ue.katalog.62": "ISO/IEC 27001 A.6.3",
    "ue.katalog.63": "An leanann comhaltaí an chomhlachta bainistíochta oiliúint rialta a chuireann ar a gcumas rioscaí a shainaithint agus cleachtais bainistíochta riosca a mheasúnú?",
    "ue.katalog.64": "ISO/IEC 27001 clásal 7.2",
    "ue.katalog.65": "Cripteagrafaíocht agus criptiú",
    "ue.katalog.66": "Beartais agus nósanna imeachta maidir le húsáid cripteagrafaíochta agus, i gcás inarb iomchuí, criptithe.",
    "ue.katalog.67": "An bhfuil beartas cripteagrafaíochta ann a shainíonn cé na sonraí agus na cainéil atá faoi réir criptithe agus cé na halgartaim a úsáidtear?",
    "ue.katalog.68": "ISO/IEC 27001 A.8.24",
    "ue.katalog.69": "An mbainistítear eochracha cripteagrafacha thar a saolré iomlán: giniúint, dáileadh, stóráil, uainíocht, scor?",
    "ue.katalog.7": "An gcuireann rogha na mbeart san áireamh an teicneolaíocht is déanaí, caighdeáin Eorpacha agus idirnáisiúnta ábhartha agus costas an chur chun feidhme?",
    "ue.katalog.70": "Acmhainní daonna, rialú rochtana agus bainistíocht sócmhainní",
    "ue.katalog.71": "Slándáil acmhainní daonna, beartais rialaithe rochtana agus bainistíocht sócmhainní.",
    "ue.katalog.72": "An gcoimeádann an t-eintiteas fardal sócmhainní cothrom le dáta le húinéirí sannta agus aicmiú?",
    "ue.katalog.73": "ISO/IEC 27001 A.5.9, A.5.12",
    "ue.katalog.74": "An bhfuil beartas rialaithe rochtana ann atá bunaithe ar phrionsabal na pribhléide is lú, le hathbhreithniú tréimhsiúil ar phribhléidí?",
    "ue.katalog.75": "ISO/IEC 27001 A.5.15, A.5.18",
    "ue.katalog.76": "An gcuirtear nósanna imeachta slándála i bhfeidhm ar fhostú, ar athrú poist agus ar imeacht fostaí, lena n-áirítear pribhléidí a chúlghairm agus sócmhainní a thabhairt ar ais?",
    "ue.katalog.77": "ISO/IEC 27001 A.6.1–A.6.5",
    "ue.katalog.78": "An bhfuil rochtain phribhléideach srianta, logáilte agus athbhreithnithe?",
    "ue.katalog.79": "ISO/IEC 27001 A.8.2",
    "ue.katalog.8": "ISO/IEC 27001 clásal 6.1.3",
    "ue.katalog.80": "Fíordheimhniú ilfhachtóra agus cumarsáid dhaingnithe",
    "ue.katalog.81": "I gcás inarb iomchuí — fíordheimhniú ilfhachtóra nó leanúnach, cumarsáid ghutha, físe agus téacs dhaingnithe agus córais chumarsáide éigeandála dhaingnithe laistigh den eintiteas.",
    "ue.katalog.82": "An úsáidtear fíordheimhniú ilfhachtóra nó leanúnach i gcás ina dtugann an anailís riosca údar leis, go háirithe le haghaidh cianrochtana agus cuntas pribhléideach?",
    "ue.katalog.83": "ISO/IEC 27001 A.8.5",
    "ue.katalog.84": "An bhfuil an chumarsáid ghutha, físe agus téacs a úsáidtear chun críoch gnó daingnithe?",
    "ue.katalog.85": "ISO/IEC 27001 A.8.20",
    "ue.katalog.86": "An bhfuil córas cumarsáide éigeandála inmheánach daingnithe ag an eintiteas, neamhspleách ar an mbonneagar príomhúil?",
    "ue.katalog.9": "An bhfuil an leibhéal slándála doiciméadaithe mar leibhéal atá iomchuí don riosca atá ann, le húdar a chuireann san áireamh méid an eintitis agus tionchar sochaíoch agus eacnamaíoch na dteagmhas?",
    "ue.kierownictwo.1": "Comhlacht bainistíochta eintitis riachtanaigh nó thábhachtaigh — i gcuideachta, an bord stiúrthóirí. Ní shainmhíníonn an Treoir an téarma; eascraíonn a raon feidhme i dtír ar leith ón dlí náisiúnta.",
    "ue.kierownictwo.10": "Stádas an eintitis a chinneadh agus clárú a chinntiú",
    "ue.kierownictwo.11": "Cinneadh an eintiteas riachtanach nó tábhachtach é an t-eintiteas agus sonraí clárúcháin a chur faoi bhráid an údaráis inniúil. Is é an dlí náisiúnta a leagann síos an nós imeachta agus an spriocdháta.",
    "ue.kierownictwo.12": "Anailís riosca agus beartas slándála a chur chun feidhme",
    "ue.kierownictwo.13": "Bearta bunaithe ar chur chuige uile-ghuaiseacha, comhréireach le neamhchosaint, méid an eintitis agus déine na dteagmhas.",
    "ue.kierownictwo.14": "Láimhseáil agus tuairisciú teagmhas a bhunú",
    "ue.kierownictwo.15": "Nós imeachta láimhseála teagmhas agus an cumas na spriocdhátaí 24 uair an chloig, 72 uair an chloig agus mí amháin a chomhlíonadh.",
    "ue.kierownictwo.16": "24 u / 72 u / mí amháin ón mbrath",
    "ue.kierownictwo.17": "Leanúnachas gnó a chinntiú",
    "ue.kierownictwo.18": "Plean leanúnachais, cúltacaí, téarnamh ó thubaistí, bainistíocht géarchéime.",
    "ue.kierownictwo.19": "An slabhra soláthair a chur in ord",
    "ue.kierownictwo.2": "Tá dliteanas an chomhlachta bainistíochta gan dochar do rialacha náisiúnta maidir le dliteanas institiúidí poiblí agus oifigeach (Airteagal 20(1), an dara fomhír).",
    "ue.kierownictwo.20": "Liosta soláthraithe, measúnú ar a leochaileachtaí agus a gcleachtais, ceanglais slándála i gconarthaí.",
    "ue.kierownictwo.21": "Rialú rochtana agus bainistíocht sócmhainní a chur chun feidhme",
    "ue.kierownictwo.22": "Fardal sócmhainní, prionsabal na pribhléide is lú, athbhreithnithe ar phribhléidí, fíordheimhniú ilfhachtóra i gcás ina dtugann an riosca údar leis.",
    "ue.kierownictwo.23": "Éifeachtacht na mbeart a thomhas",
    "ue.kierownictwo.24": "Beartas agus nósanna imeachta measúnaithe éifeachtachta, athbhreithnithe tréimhsiúla, gníomhartha ceartaitheacha.",
    "ue.kierownictwo.25": "Formheas",
    "ue.kierownictwo.26": "na bearta bainistíochta riosca cibearshlándála (Airteagal 20(1))",
    "ue.kierownictwo.27": "an beartas maidir le hanailís riosca agus slándáil córas",
    "ue.kierownictwo.28": "an buiséad agus na róil sa chur chun feidhme",
    "ue.kierownictwo.29": "Maoirsiú",
    "ue.kierownictwo.3": "Is é an dlí náisiúnta a chinneann an mbaineann dualgais a chur ar iontaoibh duine eile an dliteanas. Sa Pholainn ní bhaineann (Airteagal 8c(3) den Acht um an gCóras Náisiúnta Cibearshlándála).",
    "ue.kierownictwo.30": "cur chun feidhme na mbeart formheasta (Airteagal 20(1))",
    "ue.kierownictwo.31": "torthaí an mheasúnaithe éifeachtachta (Airteagal 21(2)(f))",
    "ue.kierownictwo.32": "comhlíonadh na spriocdhátaí tuairiscithe teagmhas (Airteagal 23)",
    "ue.kierownictwo.33": "Doiciméadú",
    "ue.kierownictwo.34": "cinntí formheasa agus athbhreithnithe",
    "ue.kierownictwo.35": "rannpháirtíocht in oiliúint (Airteagal 20(2))",
    "ue.kierownictwo.36": "Comhalta den chomhlacht bainistíochta",
    "ue.kierownictwo.37": "formheas beart, maoirseacht, cinntí, buiséad",
    "ue.kierownictwo.38": "Bainisteoir tionscadail",
    "ue.kierownictwo.39": "comhordú an chur chun feidhme, sceideal, stádas agus fianaise",
    "ue.kierownictwo.4": "Na bearta bainistíochta riosca cibearshlándála a fhormheas",
    "ue.kierownictwo.40": "TF / cibearshlándáil",
    "ue.kierownictwo.41": "anailís riosca, bearta teicniúla, láimhseáil teagmhas",
    "ue.kierownictwo.42": "Dlí / comhlíonadh",
    "ue.kierownictwo.5": "Formheasann an comhlacht bainistíochta na bearta a dhéantar chun Airteagal 21 a chomhlíonadh. Is cinneadh de chuid an chomhlachta é, ní de chuid na roinne TF — gan é níl aon sainordú ag na bearta.",
    "ue.kierownictwo.6": "Maoirseacht a dhéanamh ar chur chun feidhme na mbeart",
    "ue.kierownictwo.7": "Is oibleagáid de chuid an chomhlachta bainistíochta í maoirseacht ar an gcur chun feidhme. Is féidir an cur i gcrích a tharmligean; ní féidir an mhaoirseacht.",
    "ue.kierownictwo.8": "Oiliúint rialta a leanúint",
    "ue.kierownictwo.9": "Leanann comhaltaí an chomhlachta bainistíochta oiliúint rialta chun eolas leordhóthanach a fháil chun rioscaí a shainaithint agus cleachtais bainistíochta riosca agus a dtionchar ar sheirbhísí an eintitis a mheasúnú.",
    "ue.kierownictwo.daneRejestracyjne": "sonraí clárúcháin agus a nuashonruithe (Airteagal 3(4) agus (5))",
    "ue.meta.1": "Is é an leagan céatadáin is mó: is mó {p0} % den láimhdeachas ná EUR {p1} milliún.",
    "ue.meta.10": "Ní fhorchuireann an Treoir oibleagáidí ar ghnóthais go díreach — is é an gníomh náisiúnta a dhéanann sin, gníomh a bhí le glacadh ag an mBallstát faoin 17 Deireadh Fómhair 2024. Taispeánann an modúl seo na ceanglais mar atá siad foclaithe sa Treoir, toisc nach bhfuil modúl an dlí náisiúnta don tír roghnaithe réidh go fóill nó nár thrasuigh an tír an Treoir.",
    "ue.meta.11": "Oibleagáidí faoin Treoir",
    "ue.meta.12": "Liosta eintiteas — faoin 17 Aibreán 2025",
    "ue.meta.13": "Bhí liosta de na heintitis riachtanacha agus thábhachtacha le bunú ag na Ballstáit faoin 17 Aibreán 2025 agus bhí orthu a cheangal ar eintitis sonraí clárúcháin a chur isteach.",
    "ue.meta.14": "Rialachán (AE) 2024/2690",
    "ue.meta.15": "Infheidhme go díreach ón 7 Samhain 2024",
    "ue.meta.16": "Tá feidhm dhíreach ag an Rialachán Cur Chun Feidhme i ngach Ballstát, beag beann ar staid trasuí na Treorach. Baineann sé leis na heintitis a liostaítear in Airteagal 1 de: soláthraithe DNS, TLD, néalríomhaireachta, lárionad sonraí, líonraí seachadta ábhair, seirbhísí bainistithe agus seirbhísí iontaoibhe.",
    "ue.meta.17": "Airteagal 16 de Rialachán (AE) 2024/2690",
    "ue.meta.18": "EUR 10 000 000 ar a laghad nó 2 % ar a laghad de láimhdeachas bliantúil domhanda iomlán an ghnóthais sa bhliain airgeadais roimhe sin — cibé acu is airde. Is íos-uasteorainn í seo: féadfaidh an dlí náisiúnta í a ardú.",
    "ue.meta.19": "EUR 7 000 000 ar a laghad nó 1,4 % den láimhdeachas bliantúil domhanda iomlán — cibé acu is airde. Íos-uasteorainn.",
    "ue.meta.2": "Is é an méid seasta is mó: is mó EUR {p0} milliún ná {p1} % den láimhdeachas.",
    "ue.meta.20": "Ní fhoráiltear sa Treoir d'fhíneáil ar leith i gcás sáraithe cháilithe — is tógáil de chuid dhlí náisiúnta roinnt Ballstát é sin.",
    "ue.meta.21": "Féadfaidh na Ballstáit foráil a dhéanamh d'íocaíochtaí pionóis tréimhsiúla chun iallach a chur ar eintiteas deireadh a chur le sárú. Is é an dlí náisiúnta a leagann síos an méid.",
    "ue.meta.22": "Formheasann an comhlacht bainistíochta na bearta bainistíochta riosca, déanann sé maoirseacht ar a gcur chun feidhme agus féadfar é a chur faoi dhliteanas as sáruithe ar Airteagal 21. Is é an dlí náisiúnta a chinneann rialacha agus méid an dliteanais sin.",
    "ue.meta.23": "Formheasann an comhlacht bainistíochta na bearta bainistíochta riosca cibearshlándála (Airteagal 20(1)).",
    "ue.meta.24": "Déanann an comhlacht bainistíochta maoirseacht ar chur chun feidhme na mbeart sin (Airteagal 20(1)).",
    "ue.meta.25": "Leanann comhaltaí an chomhlachta bainistíochta oiliúint rialta (Airteagal 20(2)).",
    "ue.meta.26": "I gcás eintitis riachtanaigh, féadfaidh an t-údarás toirmeasc sealadach ar fheidhmeanna bainistíochta a fheidhmiú a iarraidh (Airteagal 32(5)(b)).",
    "ue.meta.27": "Is í an Treoir a leagann síos an íos-uasteorainn",
    "ue.meta.28": "Cuirtear dhá luach i gcomparáid: méid seasta in euro agus céatadán de láimhdeachas bliantúil domhanda iomlán an ghnóthais sa bhliain airgeadais roimhe sin. Is é an ceann is airde díobh an uasteorainn nach mór don Bhallstát foráil a dhéanamh di ar a laghad. Féadfaidh an dlí náisiúnta í a ardú.",
    "ue.meta.29": "Is é an t-údarás náisiúnta a leagann síos an méid laistigh den uasteorainn",
    "ue.meta.3": "Sáraíonn an uasteorainn ón Treoir láimhdeachas bliantúil an eintitis faoi {p0}. Éilíonn Airteagal 34(1) go mbeidh an fhíneáil comhréireach le himthosca an cháis aonair — is uasteorainn í seo, ní fíneáil a bhfuiltear ag súil léi.",
    "ue.meta.30": "Ní mór don fhíneáil a bheith éifeachtach, comhréireach agus athchomhairleach de réir imthosca an cháis aonair. Cuireann an t-údarás san áireamh ar a laghad critéir Airteagal 32(7): tromchúis agus fad an tsáraithe, sáruithe roimhe sin, damáiste a rinneadh, intinn, bearta leigheasta agus comhar.",
    "ue.meta.31": "Féadfaidh an uasteorainn an láimhdeachas bliantúil a shárú go mór — is uasteorainn í, ní méid a bhfuiltear ag súil leis. Is é dlí an Bhallstáit a chinneann íosmhéideanna náisiúnta, pionóis thréimhsiúla agus an nós imeachta chun fíneálacha a shocrú.",
    "ue.meta.32": "Agus cinneadh á dhéanamh an ngearrfar fíneáil riaracháin agus a méid, tugtar aird chuí i ngach cás aonair ar a laghad ar na heilimintí a liostaítear in Airteagal 32(7).",
    "ue.meta.33": "tromchúis an tsáraithe agus tábhacht na bhforálacha a sáraíodh — meastar na nithe seo a leanas tromchúiseach i gcás ar bith: sáruithe arís agus arís eile, mainneachtain fógra a thabhairt faoi theagmhais shuntasacha nó iad a leigheas, mainneachtain easnaimh a leigheas contrártha do threoracha ceangailteacha, bac a chur ar iniúchtaí nó ar mhonatóireacht, faisnéis bhréagach nó an-mhíchruinn a sholáthar",
    "ue.meta.34": "aon sáruithe ábhartha roimhe sin ag an eintiteas",
    "ue.meta.35": "aon damáiste ábhartha nó neamhábhartha a rinneadh, lena n-áirítear caillteanas airgeadais, éifeachtaí ar sheirbhísí eile agus líon na n-úsáideoirí a ndearnadh difear dóibh",
    "ue.meta.36": "cineál d'aon ghnó nó faillíoch an tsáraithe",
    "ue.meta.37": "bearta a rinneadh chun an damáiste a chosc nó a mhaolú",
    "ue.meta.38": "cloí le cóid iompair fhormheasta nó le sásraí deimhniúcháin",
    "ue.meta.39": "a mhéid a chomhoibrítear leis na húdaráis inniúla",
    "ue.meta.4": "Treoir (AE) 2022/2555 ó Pharlaimint na hEorpa agus ón gComhairle (NIS 2)",
    "ue.meta.40": "Ní fhoráiltear go sainráite sa Treoir d'fhíneáil a tharscaoileadh — is é an dlí náisiúnta a chinneann an féidir agus cathain is féidir é sin a dhéanamh.",
    "ue.meta.41": "Ón dáta seo, ní mór do na Ballstáit na forálacha náisiúnta lena gcuirtear an Treoir chun feidhme a chur i bhfeidhm. Eascraíonn an dáta sonrach ónar féidir leis an údarás fíneáil a ghearradh ón dlí náisiúnta.",
    "ue.meta.42": "Teacht i bhfeidhm Threoir NIS 2",
    "ue.meta.43": "An fichiú lá tar éis a foilsithe san Iris Oifigiúil.",
    "ue.meta.44": "Spriocdháta chun an Treoir a thrasuí",
    "ue.meta.45": "Faoin dáta seo bhí forálacha náisiúnta le glacadh agus le foilsiú ag na Ballstáit.",
    "ue.meta.46": "Cur i bhfeidhm forálacha náisiúnta agus aisghairm NIS 1",
    "ue.meta.47": "Ón dáta seo cuireann na Ballstáit na forálacha cur chun feidhme i bhfeidhm; aisghairtear Treoir (AE) 2016/1148.",
    "ue.meta.48": "Cur i bhfeidhm Rialachán (AE) 2024/2690",
    "ue.meta.49": "Tá feidhm dhíreach ag an Rialachán Cur Chun Feidhme ón bhfichiú lá tar éis a fhoilsithe.",
    "ue.meta.5": "IO AE L 333, 27.12.2022",
    "ue.meta.50": "Liosta na n-eintiteas riachtanach agus tábhachtach",
    "ue.meta.51": "Faoin dáta seo bunaíonn na Ballstáit an liosta; cuireann eintitis sonraí clárúcháin faoi bhráid na n-údarás.",
    "ue.meta.52": "An chéad athbhreithniú ar an Treoir ag an gCoimisiún",
    "ue.meta.53": "Déanann an Coimisiún athbhreithniú ar fheidhmiú na Treorach agus cuireann sé tuarascáil isteach.",
    "ue.meta.54": "Réamhrabhadh faoi theagmhas suntasach",
    "ue.meta.55": "24 uair an chloig tar éis eolas a fháil",
    "ue.meta.56": "Fógra faoi theagmhas suntasach",
    "ue.meta.57": "72 uair an chloig tar éis eolas a fháil",
    "ue.meta.58": "Tuarascáil deiridh",
    "ue.meta.59": "mí amháin tar éis fhógra an teagmhais",
    "ue.meta.6": "Rialachán Cur Chun Feidhme (AE) 2024/2690 ón gCoimisiún",
    "ue.meta.60": "Fógra teagmhais ó sholáthraí seirbhísí iontaoibhe",
    "ue.meta.61": "Airteagal 21(5) de Threoir (AE) 2022/2555; Airteagail 1 agus 2 de Rialachán (AE) 2024/2690",
    "ue.meta.62": "Gan sonraí láimhdeachais is é an méid seasta ón Treoir an uasteorainn.",
    "ue.meta.63": "Is íosmhéideanna iad na huasteorainneacha in Airteagal 34(4) agus (5) (\"ar a laghad\") — féadfaidh an dlí náisiúnta foráil a dhéanamh do chinn níos airde. Méideanna in euro, gan comhshó go hairgeadra náisiúnta.",
    "ue.meta.64": "Údarás inniúil an Bhallstáit",
    "ue.meta.65": "Féadfar an comhlacht bainistíochta a chur faoi dhliteanas as sáruithe ar Airteagal 21. Is é an dlí náisiúnta a chinneann an méid agus an nós imeachta — níl a fhios ag an modúl seo iad.",
    "ue.meta.66": "Eascraíonn méid dhliteanas pearsanta na bainistíochta ón ngníomh náisiúnta. Don Pholainn is suas le 300 % den luach saothair é (Airteagal 73a(4) den Acht um an gCóras Náisiúnta Cibearshlándála); cinneann Ballstáit eile ar bhealach difriúil.",
    "ue.meta.7": "IO AE L, 2024/2690",
    "ue.meta.8": "Treoir (AE) 2022/2555",
    "ue.meta.9": "Chuaigh an spriocdháta trasuite in éag an 17 Deireadh Fómhair 2024",
    "ue.moduly.1": "thart ar {p0} nóim",
    "ue.moduly.10": "Deich réimse ó Airteagal 21(2), pointí (a) go (j): ó bheartas riosca go fíordheimhniú ilfhachtóra. Tá sárú inphionóis le fíneáil faoi Airteagal 34. Measúnú ar scála aibíochta.",
    "ue.moduly.11": "Rialachán 2024/2690 — rialachas agus próisis",
    "ue.moduly.12": "Ranna 1–5 agus 7–8 den Iarscríbhinn: beartais, bainistíocht riosca, láimhseáil teagmhas, leanúnachas gnó, slabhra soláthair, measúnú éifeachtachta, cibearshláinteachas. Infheidhme go díreach ón 7 Samhain 2024.",
    "ue.moduly.13": "Rialachán 2024/2690 — ceanglais theicniúla",
    "ue.moduly.14": "Ranna 6 agus 9–13 den Iarscríbhinn: fáil agus forbairt córas, cripteagrafaíocht, slándáil acmhainní daonna, rialú rochtana, bainistíocht sócmhainní, slándáil fhisiciúil agus chomhshaoil.",
    "ue.moduly.2": "thart ar {p0} u {p1} nóim",
    "ue.moduly.3": "thart ar {p0} u",
    "ue.moduly.4": "níos lú ná nóiméad",
    "ue.moduly.5": "Measúnú tapa riosca",
    "ue.moduly.6": "Ceisteanna uileghabhálacha ó gach réimse den Treoir. Cinneann gach ceann acu grúpa iomlán ábhar. Ceadaíonn sé méid na riaráistí a mheas gan an ceistneoir iomlán a chur i gcrích.",
    "ue.moduly.7": "Oibleagáidí faoin Treoir",
    "ue.moduly.8": "Sonraí clárúcháin, tuairisciú teagmhas laistigh de 24 agus 72 uair an chloig, oibleagáidí an chomhlachta bainistíochta, ullmhacht do mhaoirseacht. Infhíoraithe ó dhoiciméid, gan anailís theicniúil.",
    "ue.moduly.9": "Bearta bainistíochta riosca — Airteagal 21(2)",
    "ue.obowiazki.1": "Sonraí clárúcháin do liosta na n-eintiteas",
    "ue.obowiazki.10": "Tuairisciú teagmhas suntasach",
    "ue.obowiazki.11": "Tugann an t-eintiteas fógra faoi theagmhais shuntasacha don CSIRT nó don údarás inniúil i dtrí chéim: réamhrabhadh, fógra teagmhais, tuarascáil deiridh. Ritheann na spriocdhátaí ón eolas a fháil ar an teagmhas.",
    "ue.obowiazki.12": "An bhfuil an t-eintiteas in ann, laistigh de 24 uair an chloig ó eolas a fháil ar theagmhas suntasach, réamhrabhadh a thabhairt a léiríonn an bhfuil amhras ann gur gníomhartha neamhdhleathacha ba chúis leis an teagmhas agus an bhféadfadh tionchar trasteorann a bheith aige?",
    "ue.obowiazki.13": "24 uair an chloig tar éis eolas a fháil",
    "ue.obowiazki.14": "An bhfuil an t-eintiteas in ann, laistigh de 72 uair an chloig, fógra teagmhais a thabhairt le measúnú tosaigh ar dhéine agus ar thionchar agus táscairí comhréitigh?",
    "ue.obowiazki.15": "72 uair an chloig tar éis eolas a fháil",
    "ue.obowiazki.16": "An gcuireann an t-eintiteas tuarascáil deiridh isteach tráth nach déanaí ná mí amháin tar éis an fhógra, le cur síos ar an teagmhas, cineál na bagartha, bearta maolaithe agus tionchar trasteorann?",
    "ue.obowiazki.17": "mí amháin tar éis an fhógra",
    "ue.obowiazki.18": "An gcuireann an t-eintiteas faighteoirí a sheirbhísí ar an eolas faoi theagmhais shuntasacha a d'fhéadfadh dochar a dhéanamh do sholáthar na seirbhísí sin?",
    "ue.obowiazki.19": "An gcuireann an t-eintiteas faighteoirí seirbhíse ar an eolas faoi chibearbhagairt shuntasach agus faoi bhearta is féidir leis na faighteoirí a dhéanamh?",
    "ue.obowiazki.2": "Bunaíonn na Ballstáit liosta de na heintitis riachtanacha agus thábhachtacha agus ceanglaíonn siad ar eintitis sonraí clárúcháin a chur isteach. Is é an dlí náisiúnta a leagann síos an nós imeachta, an spriocdháta agus an tairseach.",
    "ue.obowiazki.20": "Más soláthraí seirbhísí iontaoibhe é an t-eintiteas — an dtugann sé fógra faoi theagmhais shuntasacha laistigh de 24 uair an chloig ó eolas a fháil?",
    "ue.obowiazki.21": "baineann le soláthraithe seirbhísí iontaoibhe",
    "ue.obowiazki.22": "Comhlacht bainistíochta",
    "ue.obowiazki.23": "Formheasann an comhlacht bainistíochta na bearta bainistíochta riosca, déanann sé maoirseacht ar a gcur chun feidhme agus féadfar é a chur faoi dhliteanas. Leanann comhaltaí an chomhlachta oiliúint rialta.",
    "ue.obowiazki.24": "Ar fhormheas an comhlacht bainistíochta go foirmiúil na bearta bainistíochta riosca cibearshlándála a rinneadh chun Airteagal 21 a chomhlíonadh?",
    "ue.obowiazki.25": "An ndéanann an comhlacht bainistíochta maoirseacht dhoiciméadaithe ar chur chun feidhme na mbeart sin — mar shampla trí thuarascálacha agus athbhreithnithe tréimhsiúla?",
    "ue.obowiazki.26": "An leanann comhaltaí an chomhlachta bainistíochta oiliúint rialta a chuireann ar a gcumas rioscaí a shainaithint agus cleachtais bainistíochta riosca a mheasúnú, agus an ndoiciméadaítear an rannpháirtíocht?",
    "ue.obowiazki.27": "Ullmhacht do bhearta maoirseachta",
    "ue.obowiazki.28": "Tá eintiteas riachtanach faoi réir maoirseachta ex ante agus ex post, eintiteas tábhachtach — faoi réir maoirseachta ex post amháin. Féadfaidh an t-údarás faisnéis, fianaise ar chur chun feidhme beartas agus torthaí iniúchta a éileamh.",
    "ue.obowiazki.29": "An bhfuil an t-eintiteas in ann, ar iarratas ón údarás, fianaise a thíolacadh ar chur chun feidhme beartas cibearshlándála, lena n-áirítear torthaí iniúchtaí slándála?",
    "ue.obowiazki.3": "Ar chinn an t-eintiteas an eintiteas riachtanach nó tábhachtach é, bunaithe ar an earnáil in Iarscríbhinn I nó II agus ar mhéid an fhiontair?",
    "ue.obowiazki.30": "An bhfuil an t-eintiteas in ann, ar iarratas ón údarás, na sonraí, na doiciméid agus an fhaisnéis is gá chun cúraimí maoirseachta a chomhlíonadh a chur ar fáil?",
    "ue.obowiazki.31": "An bhfuil an t-eintiteas riachtanach ullamh d'iniúchadh slándála a dhéanann an t-údarás nó comhlacht neamhspleách, ar a chostas féin?",
    "ue.obowiazki.4": "Ar chuir an t-eintiteas sonraí clárúcháin faoi bhráid an údaráis inniúil: ainm, seoladh agus sonraí teagmhála, earnáil agus fo-earnáil, liosta na mBallstát ina soláthraíonn sé seirbhísí?",
    "ue.obowiazki.5": "Cuimsíonn sonraí teagmhála seoltaí ríomhphoist, raonta seoltaí IP agus uimhreacha teileafóin. Is é dlí an Bhallstáit a chinneann an spriocdháta náisiúnta agus an tairseach chláraithe.",
    "ue.obowiazki.6": "An bhfuil nós imeachta ann chun sonraí clárúcháin a nuashonrú gan moill mhíchuí tar éis athraithe?",
    "ue.obowiazki.7": "Éilíonn an Treoir nuashonrú gan moill mhíchuí; eascraíonn an spriocdháta sonrach — mar shampla 14 lá sa Pholainn — ón dlí náisiúnta.",
    "ue.obowiazki.8": "Más soláthraí DNS, clárlann ainmneacha TLD, soláthraí néalríomhaireachta, lárionad sonraí, CDN, seirbhísí bainistithe, margadh ar líne, inneall cuardaigh nó líonra sóisialta é an t-eintiteas — ar chuir sé isteach na sonraí breise faoi Airteagal 27, lena n-áirítear seoladh na príomhbhunaíochta san Aontas?",
    "ue.obowiazki.9": "baineann le heintitis faoi Airteagal 26(1)",
    "ue.role.1": "Údarás inniúil an Bhallstáit",
    "ue.role.10": "Seirbhísí lárionad sonraí: comhlonnú, óstáil bonneagair agus seirbhísí gaolmhara.",
    "ue.role.11": "Lárionaid sonraí",
    "ue.role.12": "Eintiteas riachtanach os cionn thairseach an fhiontair mheánmhéide (Airteagal 3(1)(a)), tábhachtach ag méid meánach (Airteagal 3(2)). Faoi bhun méid meánach — lasmuigh den raon feidhme, mura sainaithníonn an Ballstát an t-eintiteas faoi Airteagal 2(2)(b) go (e). Cumhdaithe ag Rialachán 2024/2690.",
    "ue.role.13": "Soláthraí pointe malartaithe idirlín",
    "ue.role.14": "Bonneagar a chumasaíonn malartú tráchta idir líonraí neamhspleácha.",
    "ue.role.15": "Pointí malartaithe idirlín",
    "ue.role.16": "Aicmiú de réir méid (Airteagal 3(1)(a) agus (2)). Ní chumhdaíonn Rialachán 2024/2690 pointí malartaithe idirlín — tá liosta dúnta seolaithe in Airteagal 1 den Rialachán.",
    "ue.role.17": "Soláthraí seirbhísí DNS",
    "ue.role.18": "Seirbhísí réitigh ainmneacha fearainn, seachas oibreoirí fréamhfhreastalaithe ainmneacha.",
    "ue.role.19": "Córas ainmneacha fearainn",
    "ue.role.2": "údarás inniúil",
    "ue.role.20": "Eintiteas riachtanach beag beann ar mhéid (Airteagal 3(1)(b)). Cumhdaithe ag Rialachán 2024/2690.",
    "ue.role.21": "Clárlann ainmneacha TLD",
    "ue.role.22": "Clárlann fearainn barrleibhéil a bhainistiú.",
    "ue.role.23": "Eintiteas riachtanach beag beann ar mhéid (Airteagal 3(1)(b)). Ina theannta sin, oibleagáidí faoi Airteagal 28 maidir le sonraí clárúcháin. Cumhdaithe ag Rialachán 2024/2690.",
    "ue.role.24": "Soláthraí seirbhísí néalríomhaireachta",
    "ue.role.25": "Seirbhísí néalríomhaireachta: bonneagar, ardán, bogearraí mar sheirbhís.",
    "ue.role.26": "Seirbhísí néalríomhaireachta",
    "ue.role.27": "Aicmiú de réir méid (Airteagal 3(1)(a) agus (2)). Cumhdaithe ag Rialachán 2024/2690.",
    "ue.role.28": "Soláthraí líonra seachadta ábhair",
    "ue.role.29": "Líonra freastalaithe dáilte a sheachadann ábhar agus seirbhísí chuig úsáideoirí deiridh.",
    "ue.role.3": "ainmnithe faoin dlí náisiúnta; go dtí go dtabharfar isteach an modúl náisiúnta ní ainmníonn an uirlis institiúid shonrach",
    "ue.role.30": "Líonraí seachadta ábhair",
    "ue.role.31": "Soláthraí seirbhísí iontaoibhe",
    "ue.role.32": "Seirbhísí iontaoibhe de réir bhrí Rialachán (AE) Uimh. 910/2014: sínithe, séalaí, stampaí ama, deimhnithe.",
    "ue.role.33": "Seirbhísí iontaoibhe",
    "ue.role.34": "Cumhdaithe ag an Treoir beag beann ar mhéid (Airteagal 2(2)(a)(ii)). Is eintiteas riachtanach é soláthraí cáilithe beag beann ar mhéid (Airteagal 3(1)(b)); tá soláthraí neamhcháilithe riachtanach os cionn thairseach an fhiontair mheánmhéide, tábhachtach ar shlí eile. Cumhdaithe ag Rialachán 2024/2690.",
    "ue.role.35": "Soláthraí seirbhísí bainistithe",
    "ue.role.36": "Bainistíocht ar bhonneagar TFC an chustaiméara: suiteáil, cothabháil, tacaíocht, riarachán córas.",
    "ue.role.37": "Bainistíocht seirbhísí TFC (B2B)",
    "ue.role.38": "Seirbhísí bainistithe",
    "ue.role.39": "Soláthraí seirbhísí slándála bainistithe",
    "ue.role.4": "Soláthraí líonraí cumarsáide leictreonaí poiblí nó seirbhísí cumarsáide leictreonaí atá ar fáil go poiblí",
    "ue.role.40": "Seirbhísí cibearshlándála bainistithe: monatóireacht, freagairt do theagmhais, tástáil, comhairleoireacht.",
    "ue.role.41": "Seirbhísí slándála bainistithe",
    "ue.role.42": "Aicmíonn an Treoir de réir méid (Airteagal 3(1)(a) agus (2)). Féadfaidh na Ballstáit an tairseach a dhéanamh níos déine — measann an Pholainn MSSP mar eintiteas riachtanach cheana ó fhiontar beag; ní chuireann an modúl seo i bhfeidhm ach riail na Treorach. Cumhdaithe ag Rialachán 2024/2690.",
    "ue.role.5": "Soláthar líonraí cumarsáide leictreonaí poiblí nó seirbhísí cumarsáide leictreonaí atá ar fáil go poiblí, lena n-áirítear rochtain ar an idirlíon.",
    "ue.role.6": "Bonneagar digiteach",
    "ue.role.7": "Cumarsáid leictreonach",
    "ue.role.8": "Cumhdaithe ag an Treoir beag beann ar mhéid (Airteagal 2(2)(a)(i)). Is eintiteas riachtanach é fiontar meánmhéide nó níos mó (Airteagal 3(1)(c)), micreafhiontar agus fiontar beag — tábhachtach (Airteagal 3(2)). Féadfaidh an gníomh náisiúnta cumarsáide leictreonaí oibleagáidí breise a fhorchur — níl siad sa mhodúl seo.",
    "ue.role.9": "Soláthraí seirbhísí lárionad sonraí",
    "ue.role.podstawaArt3b": "Airteagal 3(1)(b) de Threoir (AE) 2022/2555",
    "ue.zaslepki.1": "Treoir (AE) 2022/2555 ó Pharlaimint na hEorpa agus ón gComhairle (NIS 2)",
    "ue.zaslepki.10": "Is é an dlí náisiúnta a chinneann an gcláraítear roinnt eintiteas ex officio.",
    "ue.zaslepki.11": "Faigh amach an bhfuil tú cumhdaithe ag an Treoir",
    "ue.zaslepki.12": "Earnáil in Iarscríbhinn I nó II agus méid an fhiontair. Déanann próifíl an eintitis san uirlis seo an chuid seo.",
    "ue.zaslepki.13": "Faigh amach an t-údarás inniúil i do thír",
    "ue.zaslepki.14": "Ainmníonn gach tír údarás inniúil (Airteagal 8(1)). Coimeádann ENISA agus an Coimisiún liosta cothrom le dáta.",
    "ue.zaslepki.15": "Cuir isteach sonraí clárúcháin",
    "ue.zaslepki.16": "Ainm, seoladh agus sonraí teagmhála, earnáil agus fo-earnáil, tíortha soláthair seirbhíse (Airteagal 3(4)). Nós imeachta faoin dlí náisiúnta.",
    "ue.zaslepki.17": "Nuashonraigh na sonraí gan moill mhíchuí",
    "ue.zaslepki.18": "Éilíonn gach athrú ar shonraí clárúcháin nuashonrú (Airteagal 3(5)).",
    "ue.zaslepki.19": "seoladh agus sonraí teagmhála reatha: seoltaí ríomhphoist, raonta seoltaí IP, uimhreacha teileafóin",
    "ue.zaslepki.2": "IO AE L 333, 27.12.2022, lch. 80",
    "ue.zaslepki.20": "earnáil agus fo-earnáil in Iarscríbhinn I nó II",
    "ue.zaslepki.21": "liosta na mBallstát ina soláthraíonn an t-eintiteas seirbhísí",
    "ue.zaslepki.22": "Leagtha síos ag an dlí náisiúnta.",
    "ue.zaslepki.23": "Treoir (AE) 2022/2555 — Airteagal 3",
    "ue.zaslepki.24": "ENISA — údaráis inniúla na mBallstát",
    "ue.zaslepki.25": "Treoir (AE) 2022/2555",
    "ue.zaslepki.26": "Níl aon treoirlínte ón údarás náisiúnta sa mhodúl AE — tiocfaidh siad le modúl an dlí náisiúnta.",
    "ue.zaslepki.27": "Ní oibríonn aisghabháil uathoibríoch sonraí clár ach do thíortha a bhfuil modúl dlí náisiúnta acu. Líon isteach an phróifíl de láimh.",
    "ue.zaslepki.28": "Ní oibríonn léamh ráitis airgeadais ach do thíortha a bhfuil modúl dlí náisiúnta acu. Cuir isteach ioncam agus líon foirne de láimh.",
    "ue.zaslepki.3": "Rialachán Cur Chun Feidhme (AE) 2024/2690 ón gCoimisiún",
    "ue.zaslepki.4": "IO AE L, 2024/2690, 18.11.2024",
    "ue.zaslepki.5": "Níl aon sraith ar leith cumarsáide leictreonaí i dTreoir NIS 2. Féadfaidh an dlí náisiúnta cumarsáide leictreonaí oibleagáidí breise a fhorchur — níl a fhios ag an modúl seo iad.",
    "ue.zaslepki.6": "Liosta na n-eintiteas riachtanach agus tábhachtach",
    "ue.zaslepki.7": "Údarás inniúil an Bhallstáit.",
    "ue.zaslepki.8": "Ceanglaíonn an Treoir ar na Ballstáit liosta de na heintitis riachtanacha agus thábhachtacha a choimeád agus a cheangal ar eintitis sonraí clárúcháin a chur isteach. Is é an dlí náisiúnta a leagann síos an tairseach, an nós imeachta agus an spriocdháta — níl a fhios ag an modúl seo iad, toisc nach bhfuil modúl an dlí náisiúnta don tír roghnaithe réidh go fóill.",
    "ue.zaslepki.9": "Gach eintiteas riachtanach agus tábhachtach. Is é an dlí náisiúnta a leagann síos an spriocdháta.",
    "ue.zaslepki.skrotDyrektywy": "Treoir NIS 2",
    "ue.zaslepki.skrotReg2690": "Rialachán 2024/2690",
    "xlsx.1": "EUR {p0} – {p1}",
    "xlsx.25": "Ráta malairte",
    "xlsx.4": "TUARASCÁIL COMHLÍONTA THREOIR NIS 2 (AE) 2022/2555",
    "xlsx.58": "Gníomhaíocht cumarsáide leictreonaí: níl feidhm ag Rialachán (AE) 2024/2690. Is é an dlí náisiúnta a leagann síos na tairseacha (Airteagal 23(11) den Treoir) — níl a fhios ag an modúl coiteann iad.",
    "xlsx.68": "Is chun féinmheasúnaithe an uirlis. Ní iniúchadh ná comhairle dlí í.",
    "xlsx.69": "I gcás eintiteas nach gcumhdaítear le Rialachán (AE) 2024/2690, is é an dlí náisiúnta a leagann síos na tairseacha do theagmhas suntasach (Airteagal 23(11) den Treoir).",
    "xlsx.70": "Is dearbhú iad na róil a shonraítear sa phróifíl. Is í an ghníomhaíocht a dhéantar i ndáiríre a chinneann an stádas (Airteagal 3 de Threoir (AE) 2022/2555).",
    "xlsx.etykietaKrs": "Uimhir chláir",
    "xlsx.etykietaNip": "Uimhir aitheantais",
    "xlsx.etykietaRegon": "Uimhir staidrimh"
});
