/* Teksty modułu ue — język: hr.
   Te same klucze co w napisy/pl.js (wersja źródłowa); wstawki {p0}, {p1}…
   pozostają bez zmian. Klucze ue.cyt.* to wzorce składania odesłań
   do przepisów w tym języku — patrz kraje/ue/cytaty.js. */
KRAJE.napisy('ue', 'hr', {
    "app.10": "Provjerite popis uloga u nastavku — o statusu odlučuje stvarno obavljana djelatnost (članak 3. Direktive (EU) 2022/2555), a ne upis u registar.",
    "app.14": "Prethodna godina: {p0} EUR",
    "app.15": "Prihod za izvještajno razdoblje: {p0} EUR",
    "app.19": "Pretražujem registre prema broju {p0}…",
    "app.34": " mlrd. EUR",
    "app.35": " mil. EUR",
    "app.36": " tis. EUR",
    "app.37": "",
    "app.4": "Automatsko dohvaćanje podataka iz registra nije dostupno za ovu državu — ispunite profil ručno.",
    "app.59": "Ocjena usklađenosti s Direktivom NIS 2 (JSON)",
    "app.68": "Za ovu državu ne postoji registar iz kojeg bi alat mogao dohvatiti podatke — profil se ispunjava ručno.",
    "app.69": "Za ovu državu ne postoji registar iz kojeg bi alat mogao dohvatiti podatke. Kliknite za uključivanje izvanmrežnog načina rada.",
    "app.73": " · račun dobiti i gubitka u varijanti ",
    "app.74": "<div class=\"mt-2 tekst-uwaga\">Iz registarskih podataka ne proizlazi nijedna uloga iz sektora digitalne infrastrukture. Uloge odaberite ručno u nastavku.</div>",
    "app.8": "Potvrđen upis u registar pružatelja elektroničkih komunikacija",
    "app.progDostawcy": "",
    "app.przyklad.adres": "Ogledna ulica 1, 10000 Grad",
    "app.przyklad.forma": "Društvo s ograničenom odgovornošću",
    "app.przyklad.nazwa": "Ogledni operator d.o.o.",
    "app.statusVat": " · status PDV-a: ",
    "dashboard.1": "Na temelju deklariranih uloga i veličine subjekt nije ni ključni ni važan subjekt u smislu članka 3. Direktive (EU) 2022/2555. Provjerite profil ako rezultat ne odgovara očekivanju.",
    "dashboard.113": "Česta pitanja",
    "dashboard.12": "— {p0}; rok za prenošenje u nacionalno pravo istekao je {p2}",
    "dashboard.123": "Direktiva NIS 2",
    "dashboard.30": "Popis ključnih i važnih subjekata",
    "dashboard.4": "— izravno se primjenjuje od {p0} u svim državama članicama, bez prenošenja",
    "dashboard.42": "Iznosna varijanta: {p0}",
    "dashboard.45": "Kriteriji iz članka 32. stavka 7. Direktive:",
    "dashboard.46": "Ukupno",
    "dashboard.49": "Subjekt obavlja djelatnost elektroničkih komunikacija — odgovornost upravljajuće osobe određuje nacionalno pravo",
    "dashboard.50": "",
    "dashboard.51": "",
    "dashboard.53": "Periodična kazna za kašnjenje u izvršenju odluke: od {p0} EUR do {p1} EUR po danu ({p2})",
    "dashboard.54": "Kvalificirani slučaj: do {p0} EUR ({p1})",
    "dashboard.57": "({p0}). Otkad nacionalno tijelo može izricati kazne, određuje zakon o prenošenju Direktive — ovaj ga modul ne poznaje. Obveze provedbe proizlaze iz nacionalnog prava od dana njegova stupanja na snagu.",
    "dashboard.65": "({p0}). Otkad nacionalno tijelo može izricati kazne, određuje zakon o prenošenju Direktive — ovaj ga modul ne poznaje. Financijski rizik stoga ovdje nije datiran, dok obveze provedbe proizlaze iz nacionalnog prava od dana njegova stupanja na snagu.",
    "dashboard.83": "Djelatnost elektroničkih komunikacija — pragove određuje nacionalno pravo.",
    "dashboard.84": "Uredba (EU) 2024/2690 ne primjenjuje se na pružatelje javnih elektroničkih komunikacijskih mreža i usluga. Za njih pragove značajnog incidenta određuje nacionalno pravo (članak 23. stavak 11. Direktive) — ovaj ih modul ne poznaje pa ne navodi brojčane vrijednosti.",
    "dashboard.terminRejestracji": "Rok za podnošenje registracijskih podataka određuje nacionalno pravo (članak 3. stavak 4. Direktive). Pružatelji iz članka 27. stavka 1. — usluga DNS-a, registri vršnih domena, pružatelji usluga u oblaku, podatkovnih centara, mreža za isporuku sadržaja, upravljanih usluga i upravljanih sigurnosnih usluga — dostavljaju podatke u registar ENISA-e: prvotno do 17. siječnja 2025., a svaku promjenu bez nepotrebne odgode.",
    "html.1": "ITORO — Ocjena usklađenosti s Direktivom NIS 2 (EU) 2022/2555",
    "html.10": "Ocjena usklađenosti s Direktivom NIS 2 — zajednički modul",
    "html.100": "Čitanje financijskog izvješća radi samo za države s modulom nacionalnog prava. Za ovu državu <strong>prihod</strong> za poslovnu godinu unosite ručno — o njemu ovisi visina kazne.",
    "html.102": "Automatsko dohvaćanje podataka iz registara radi samo za države s modulom nacionalnog prava. Uloge i veličinu poduzeća navodite ručno.",
    "html.11": "Direktiva (EU) 2022/2555 (NIS 2) zahtijeva prenošenje u nacionalno pravo. Ocjena obuhvaća obveze koje izravno proizlaze iz Direktive te izravno primjenjivu Provedbenu uredbu Komisije (EU) 2024/2690 — u mjeri u kojoj se odnose na subjekt.",
    "html.23": "prihod i veličinu unosite ručno — zajednički modul ne pretražuje nacionalne registre",
    "html.33": "Direktiva (EU) 2022/2555 Europskog parlamenta i Vijeća od 14. prosinca 2022. (NIS 2)",
    "html.33a": "{p0} — nacionalni akt kojim se prenosi direktiva; njegove zahtjeve ovaj modul još ne ocjenjuje",
    "html.33b": "država još nije donijela akt o prenošenju — procjena slijedi pravo Unije",
    "html.35": "obveze upravljačkog tijela — članak 20. Direktive",
    "html.36": "Alat služi samoocjeni. Nije revizija ni pravno mišljenje.",
    "html.40": "zajednički modul ne uspostavlja nikakve odlazne veze — ne pretražuje registre",
    "html.59": "Financijska izvješća",
    "html.60": "Čitanje financijskog izvješća dostupno je samo za države s modulom nacionalnog prava. Za ovu državu prihod i broj zaposlenih unosite ručno.",
    "html.62": "Pretraživanje registra",
    "html.63": "poslovni registri su nacionalni — zajednički ih modul ne poznaje",
    "html.64": "uloge i veličinu poduzeća navodite ručno",
    "html.66": "Identifikacijski broj subjekta",
    "html.68": "Automatsko dohvaćanje podataka iz registara radi samo za države s modulom nacionalnog prava.",
    "html.76": "Godišnji prihod (EUR)",
    "html.78": "Prihod od djelatnosti elektroničkih komunikacija (EUR)",
    "html.79": "Polje se odnosi na pružatelje javnih elektroničkih komunikacijskih mreža ili usluga. Nacionalne pragove određuje pravo države članice.",
    "html.80": "Mjesečna primanja čelnika (EUR)",
    "html.82": "Tečaj",
    "html.83": "Gornje granice kazni u Direktivi izražene su u eurima. Preračun u nacionalnu valutu i tečaj određuje nacionalno pravo — ovdje su iznosi navedeni u eurima bez preračuna.",
    "html.84": "Status proizlazi isključivo iz agregiranja podataka povezanih poduzeća, a informacijski sustav subjekta je neovisan (uvodna izjava 16. Direktive — o primjeni odlučuje nacionalno pravo)",
    "html.85": "Subjekt djeluje u području nacionalne sigurnosti, javne sigurnosti, obrane ili kaznenog progona (članak 2. stavak 7. Direktive)",
    "html.91": "Ocjena usklađenosti s Direktivom (EU) 2022/2555 Europskog parlamenta i Vijeća (NIS 2) i s Provedbenom uredbom Komisije (EU) 2024/2690 — zajednički modul za države čiji modul nacionalnog prava još nije gotov.",
    "html.94": "je li subjekt <strong>ključni</strong>, <strong>važan</strong> ili izvan područja primjene Direktive",
    "html.daneZeSprawozdania": "naziv, identifikacijski broj, adresa sjedišta",
    "html.rejestrMozliwy": "Registar {p0} javan je i besplatan — čitanje iz njega može se dodati; rado primamo pull requestove (vidjeti README).",
    "html.tytulNaglowka": "Ocjena usklađenosti s Direktivom NIS 2",
    "html.zrodlaRecznie": "Ovaj modul ne poznaje registre vaše države — profil ispunite ručno. Godišnji promet određuje gornju granicu kazne, pa ga unesite točno.",
    "klasyfikacja.10": "članak 3. stavak 1. točka (c) Direktive (EU) 2022/2555 (pružatelj javnih elektroničkih komunikacijskih mreža ili javno dostupnih elektroničkih komunikacijskih usluga koji je barem srednje poduzeće)",
    "klasyfikacja.11": "članak 3. stavak 2. u vezi s člankom 2. stavkom 2. točkom (a) podtočkom i. Direktive (EU) 2022/2555 (pružatelj javnih elektroničkih komunikacijskih mreža ili usluga koji je mikropoduzeće ili malo poduzeće)",
    "klasyfikacja.12": "članak 3. stavak 1. točka (a) Direktive (EU) 2022/2555 (pružatelj upravljanih sigurnosnih usluga koji premašuje gornje granice za srednje poduzeće)",
    "klasyfikacja.13": "Mikropoduzeća i mala poduzeća nisu obuhvaćena Direktivom po osnovi ove uloge (članak 2. stavak 1. a contrario).",
    "klasyfikacja.15": "članak 3. stavak 1. točka (b) Direktive (EU) 2022/2555 (kvalificirani pružatelj usluga povjerenja) — neovisno o veličini poduzeća",
    "klasyfikacja.16": "članak 3. stavak 2. u vezi s člankom 2. stavkom 2. točkom (a) podtočkom ii. Direktive (EU) 2022/2555 (nekvalificirani pružatelj usluga povjerenja koji je mikropoduzeće, malo ili srednje poduzeće)",
    "klasyfikacja.18": "članak 3. stavak 2. Direktive (EU) 2022/2555 (subjekt javne uprave na regionalnoj razini, ako država članica tako odredi — članak 2. stavak 2. točka (f) podtočka ii.)",
    "klasyfikacja.19": "članak 3. stavak 1. točka (f) Direktive (EU) 2022/2555 (subjekt javne uprave na razini središnje vlasti — članak 2. stavak 2. točka (f) podtočka i.)",
    "klasyfikacja.2": "Nadzor ex ante i ex post (članak 32. Direktive (EU) 2022/2555).",
    "klasyfikacja.20": "članak 3. stavak 2. Direktive (EU) 2022/2555 (subjekt javne uprave na regionalnoj razini — članak 2. stavak 2. točka (f) podtočka ii.)",
    "klasyfikacja.21": "Opseg obveza subjekata javne uprave na lokalnoj razini određuje nacionalno pravo (članak 2. stavak 5. točka (a) Direktive).",
    "klasyfikacja.22": "Država članica može izuzeti subjekte koji djeluju u području nacionalne sigurnosti, javne sigurnosti, obrane ili kaznenog progona (članak 2. stavak 7. Direktive). Izuzeće ne djeluje samo od sebe — rezultat ocjene provjerite prema nacionalnom pravu.",
    "klasyfikacja.23": "Subjekt ispunjava kriterije i ključnog i važnog subjekta. Ključni je subjekt (članak 3. stavak 1. Direktive), a stroži zahtjevi primjenjuju se na cjelokupnu djelatnost obuhvaćenu Direktivom.",
    "klasyfikacja.25": "Subjekt je ključan pa se na njega primjenjuje puni katalog mjera iz članka 21. stavka 2. Direktive te nadzor ex ante i ex post — ocjena obuhvaća puni skup pitanja.",
    "klasyfikacja.26": "Kao važan subjekt podliježete istom katalogu mjera iz članka 21. stavka 2., ali samo nadzoru ex post (članak 33.). Gornja granica kazne niža je: 7 mil. EUR ili 1,4 % prometa (članak 34. stavak 5.). Olakšice za javne subjekte može uvesti nacionalno pravo — ovaj ih modul ne poznaje.",
    "klasyfikacja.28": "Obveze subjekata javne uprave proizlaze iz članka 2. stavka 2. točke (f) Direktive; njihov točan opseg, uključujući lokalnu razinu i obrazovne ustanove, određuje nacionalno pravo (članak 2. stavak 5.).",
    "klasyfikacja.29": "Deklarirano je da status subjekta proizlazi isključivo iz agregiranja podataka povezanih ili partnerskih poduzeća te da je informacijski sustav subjekta neovisan. Direktiva dopušta takvo izuzeće (uvodna izjava 16.), ali o njemu odlučuje nacionalno pravo — modul prihvaća izuzeće koje treba provjeriti prema pravu države članice i dokumentirati.",
    "klasyfikacja.4": "Nadzor isključivo ex post — u slučaju dokaza, naznaka ili informacija o povredi (članak 33. Direktive (EU) 2022/2555).",
    "klasyfikacja.5": "Izvan područja primjene Direktive",
    "klasyfikacja.6": "Nema obveza koje proizlaze iz Direktive (EU) 2022/2555 za navedenu ulogu.",
    "klasyfikacja.7": "članak 3. stavak 1. točka (a) Direktive (EU) 2022/2555 (subjekt vrste iz Priloga I. koji premašuje gornje granice za srednje poduzeće)",
    "klasyfikacja.8": "članak 3. stavak 2. Direktive (EU) 2022/2555 (subjekt vrste iz Priloga I. koji ispunjava kriterije srednjeg poduzeća)",
    "klasyfikacja.9": "Mikropoduzeća i mala poduzeća nisu obuhvaćena Direktivom po osnovi ove uloge (članak 2. stavak 1. a contrario).",
    "kreator.10": "Prihod za prethodnu godinu unesite ručno.",
    "kreator.35": "<span class=\"text-secondary\">Čitanje financijskih izvješća nije dostupno za ovu državu.</span>",
    "kreator.37": "Čitanje financijskih izvješća nije dostupno za ovu državu — unesite prihod ručno.",
    "kreator.56": "Da — uredba EU-a izravno se primjenjuje od 7. studenoga 2024. u svim državama članicama i nema prijelaznog razdoblja. Temelj joj je",
    "kreator.57": ", koji je ovlastio Komisiju da utvrdi tehničke i metodološke zahtjeve za pružatelje iz članka 3. stavka 1. Uredbe. Rok za prenošenje Direktive istekao je",
    "kreator.58": ", a otkad nacionalno tijelo može izricati kazne, određuje nacionalno pravo. Tehnički zahtjevi iz Priloga (odjeljci 6. i 9.–13.) obvezujući su u sadašnjem tekstu — ne čekaju pojašnjenje. Odstupiti se može samo od zahtjeva s formulacijom „prema potrebi”, i to isključivo uz dokumentirano obrazloženje.",
    "kreator.9": "Financijska izvješća →",
    "kreator.przepisReg2690": "članak 21. stavak 5. Direktive (EU) 2022/2555",
    "kreator.terminReg2690": "17. listopada 2024.",
    "punktacja.10": "Javni subjekti",
    "punktacja.4": "Direktiva NIS 2 — članak 21.",
    "punktacja.5": "Direktiva NIS 2 — formalne obveze",
    "punktacja.8": "Elektroničke komunikacije",
    "punktacja.9": "Direktiva NIS 2 — javni subjekti",
    "punktacja.skrotKsc": "NIS 2",
    "punktacja.skrotPke": "telekom",
    "ue.cyt.akapit": "{p0} podstavak",
    "ue.cyt.art": "članak {p0}.",
    "ue.cyt.drugi": "drugi",
    "ue.cyt.dyr": "{p0} Direktive (EU) 2022/2555",
    "ue.cyt.i": "i",
    "ue.cyt.laczenie": " ",
    "ue.cyt.lit": "točka ({p0})",
    "ue.cyt.litery": "",
    "ue.cyt.pkt": "točka {p0}.",
    "ue.cyt.rozdzielacz": "; ",
    "ue.cyt.rozp": "{p0} Uredbe (EU) 2024/2690",
    "ue.cyt.ust": "stavak {p0}.",
    "ue.katalog.1": "Politike analize rizika i sigurnosti informacijskih sustava",
    "ue.katalog.10": "Postupanje s incidentima",
    "ue.katalog.11": "Postupanje s incidentima obuhvaća radnje i postupke usmjerene na sprječavanje, otkrivanje, analizu i ograničavanje incidenata, odgovor na njih i oporavak od njih (članak 6. točka 8.).",
    "ue.katalog.12": "Postoji li dokumentirani postupak postupanja s incidentima koji obuhvaća otkrivanje, analizu, ograničavanje, odgovor i oporavak?",
    "ue.katalog.13": "ISO/IEC 27001 A.5.24–A.5.26",
    "ue.katalog.14": "Omogućuje li postupak poštivanje rokova za prijavu značajnog incidenta: rano upozorenje u 24 sata, prijava u 72 sata, završno izvješće u mjesec dana?",
    "ue.katalog.15": "ISO/IEC 27001 A.5.24",
    "ue.katalog.16": "Ima li subjekt kriterije za priznavanje incidenta značajnim, u skladu s člankom 23. stavkom 3.: ozbiljni operativni poremećaji ili financijski gubici ili znatna šteta drugim osobama?",
    "ue.katalog.17": "ISO/IEC 27001 A.5.25",
    "ue.katalog.18": "Bilježe li se incidenti i koriste li se zaključci iz postupanja s njima za poboljšanje mjera?",
    "ue.katalog.19": "ISO/IEC 27001 A.5.27",
    "ue.katalog.2": "Mjere se temelje na pristupu koji uzima u obzir sve opasnosti (članak 21. stavak 2.). Njihova razmjernost ocjenjuje se uzimajući u obzir stupanj izloženosti, veličinu subjekta, vjerojatnost incidenata i njihovu ozbiljnost (članak 21. stavak 1. drugi podstavak).",
    "ue.katalog.20": "Kontinuitet poslovanja i upravljanje krizama",
    "ue.katalog.21": "Kontinuitet poslovanja, kao što su upravljanje sigurnosnim kopijama i oporavak od katastrofe, te upravljanje krizama.",
    "ue.katalog.22": "Postoji li plan kontinuiteta poslovanja koji obuhvaća oporavak nakon katastrofe?",
    "ue.katalog.23": "ISO/IEC 27001 A.5.29–A.5.30",
    "ue.katalog.24": "Izrađuju li se sigurnosne kopije, štite li se i testiraju li se s obzirom na mogućnost obnove?",
    "ue.katalog.25": "ISO/IEC 27001 A.8.13",
    "ue.katalog.26": "Ima li subjekt postupke upravljanja krizama s utvrđenim ulogama i komunikacijskim kanalima?",
    "ue.katalog.27": "ISO/IEC 27001 A.5.29",
    "ue.katalog.28": "Testiraju li se planovi kontinuiteta i oporavka periodično, a rezultati dokumentiraju?",
    "ue.katalog.29": "ISO/IEC 27001 A.5.30",
    "ue.katalog.3": "Ima li subjekt dokumentiranu politiku analize rizika i sigurnosti informacijskih sustava koju je odobrilo upravljačko tijelo?",
    "ue.katalog.30": "Sigurnost lanca opskrbe",
    "ue.katalog.31": "Sigurnost lanca opskrbe, uključujući sigurnosne aspekte odnosa između subjekta i njegovih izravnih dobavljača ili pružatelja usluga. Subjekt uzima u obzir ranjivosti svojstvene svakom dobavljaču te ukupnu kvalitetu njegovih proizvoda i praksi u području kibernetičke sigurnosti (članak 21. stavak 3.).",
    "ue.katalog.32": "Vodi li subjekt popis izravnih dobavljača i pružatelja usluga s ocjenom njihove važnosti za sigurnost mreža i sustava?",
    "ue.katalog.33": "ISO/IEC 27001 A.5.19",
    "ue.katalog.34": "Uzimaju li se pri odabiru mjera prema dobavljačima u obzir ranjivosti svojstvene svakom od njih te kvaliteta njihovih praksi kibernetičke sigurnosti i sigurnog razvoja?",
    "ue.katalog.35": "ISO/IEC 27001 A.5.19, A.5.21",
    "ue.katalog.36": "Sadrže li ugovori s dobavljačima sigurnosne zahtjeve i obvezu obavješćivanja o incidentima i ranjivostima?",
    "ue.katalog.37": "ISO/IEC 27001 A.5.20",
    "ue.katalog.38": "Uzima li subjekt u obzir rezultate koordiniranih procjena sigurnosnih rizika kritičnih lanaca opskrbe iz članka 22.?",
    "ue.katalog.39": "ISO/IEC 27001 A.5.21",
    "ue.katalog.4": "ISO/IEC 27001 točke 5.2, 6.1.2",
    "ue.katalog.40": "Sigurnost pri nabavi, razvoju i održavanju sustava",
    "ue.katalog.41": "Sigurnost u nabavi, razvoju i održavanju mrežnih i informacijskih sustava, uključujući postupanje s ranjivostima i njihovo otkrivanje.",
    "ue.katalog.42": "Utvrđuju li se sigurnosni zahtjevi prije nabave ili početka razvoja sustava i provjeravaju prije uvođenja?",
    "ue.katalog.43": "ISO/IEC 27001 A.8.25–A.8.29",
    "ue.katalog.44": "Postoji li proces postupanja s ranjivostima: identifikacija, ocjena, uklanjanje u određenom roku?",
    "ue.katalog.45": "ISO/IEC 27001 A.8.8",
    "ue.katalog.46": "Ima li subjekt postupak otkrivanja ranjivosti, uključujući kanal za primanje prijava od trećih osoba?",
    "ue.katalog.47": "Prolaze li promjene sustava kroz kontrolirani proces upravljanja promjenama s ocjenom utjecaja na sigurnost?",
    "ue.katalog.48": "ISO/IEC 27001 A.8.32",
    "ue.katalog.49": "Ocjena djelotvornosti mjera",
    "ue.katalog.5": "Obuhvaća li analiza rizika sve opasnosti za mrežne i informacijske sustave i njihovo fizičko okruženje, a ne samo kibernetičke prijetnje?",
    "ue.katalog.50": "Politike i postupci za ocjenu djelotvornosti mjera upravljanja kibernetičkim sigurnosnim rizicima.",
    "ue.katalog.51": "Postoji li dokumentirana politika ocjene djelotvornosti mjera koja određuje opseg, učestalost i metode?",
    "ue.katalog.52": "ISO/IEC 27001 točka 9.1",
    "ue.katalog.53": "Provode li se ocjene djelotvornosti periodično, a rezultati prenose upravljačkom tijelu?",
    "ue.katalog.54": "ISO/IEC 27001 točke 9.2–9.3",
    "ue.katalog.55": "Dovode li otkrivene slabosti do dokumentiranih korektivnih mjera s vlasnikom i rokom?",
    "ue.katalog.56": "ISO/IEC 27001 točka 10.1",
    "ue.katalog.57": "Kibernetička higijena i osposobljavanje",
    "ue.katalog.58": "Osnovne prakse kibernetičke higijene i osposobljavanje u području kibernetičke sigurnosti. Članovi upravljačkog tijela redovito prolaze osposobljavanje (članak 20. stavak 2.).",
    "ue.katalog.59": "Primjenjuje li subjekt osnovne prakse kibernetičke higijene: ažuriranja, upravljanje lozinkama, ograničavanje ovlasti, zaštitu od zlonamjernog softvera?",
    "ue.katalog.6": "ISO/IEC 27001 točka 6.1.2",
    "ue.katalog.60": "ISO/IEC 27001 A.8.7, A.8.8",
    "ue.katalog.61": "Prolaze li zaposlenici osposobljavanje iz kibernetičke sigurnosti prilagođeno njihovoj ulozi, a sudjelovanje se dokumentira?",
    "ue.katalog.62": "ISO/IEC 27001 A.6.3",
    "ue.katalog.63": "Prolaze li članovi upravljačkog tijela redovito osposobljavanje koje im omogućuje prepoznavanje rizika i ocjenu praksi upravljanja rizicima?",
    "ue.katalog.64": "ISO/IEC 27001 točka 7.2",
    "ue.katalog.65": "Kriptografija i šifriranje",
    "ue.katalog.66": "Politike i postupci upotrebe kriptografije i, prema potrebi, šifriranja.",
    "ue.katalog.67": "Postoji li politika upotrebe kriptografije koja određuje koji podaci i kanali podliježu šifriranju i kojim algoritmima?",
    "ue.katalog.68": "ISO/IEC 27001 A.8.24",
    "ue.katalog.69": "Upravlja li se kriptografskim ključevima kroz cijeli životni ciklus: generiranje, distribucija, pohrana, rotacija, povlačenje?",
    "ue.katalog.7": "Uzima li odabir mjera u obzir najnovija dostignuća, relevantne europske i međunarodne norme te troškove provedbe?",
    "ue.katalog.70": "Ljudski resursi, kontrola pristupa i upravljanje imovinom",
    "ue.katalog.71": "Sigurnost ljudskih resursa, politike kontrole pristupa i upravljanje imovinom.",
    "ue.katalog.72": "Vodi li subjekt ažuran popis imovine s dodijeljenim vlasnicima i klasifikacijom?",
    "ue.katalog.73": "ISO/IEC 27001 A.5.9, A.5.12",
    "ue.katalog.74": "Postoji li politika kontrole pristupa temeljena na načelu najmanjih ovlasti, s periodičnim pregledom ovlasti?",
    "ue.katalog.75": "ISO/IEC 27001 A.5.15, A.5.18",
    "ue.katalog.76": "Primjenjuju li se pri zapošljavanju, promjeni radnog mjesta i odlasku zaposlenika sigurnosni postupci, uključujući oduzimanje ovlasti i povrat imovine?",
    "ue.katalog.77": "ISO/IEC 27001 A.6.1–A.6.5",
    "ue.katalog.78": "Je li privilegirani pristup ograničen, bilježen i pregledavan?",
    "ue.katalog.79": "ISO/IEC 27001 A.8.2",
    "ue.katalog.8": "ISO/IEC 27001 točka 6.1.3",
    "ue.katalog.80": "Višefaktorska autentifikacija i sigurna komunikacija",
    "ue.katalog.81": "Prema potrebi — višefaktorska ili kontinuirana autentifikacija, zaštićena glasovna, video i tekstualna komunikacija te zaštićeni sustavi komunikacije u hitnim slučajevima unutar subjekta.",
    "ue.katalog.82": "Primjenjuje li se višefaktorska ili kontinuirana autentifikacija tamo gdje to analiza rizika opravdava, osobito za udaljeni pristup i privilegirane račune?",
    "ue.katalog.83": "ISO/IEC 27001 A.8.5",
    "ue.katalog.84": "Jesu li glasovne, video i tekstualne veze koje se koriste u poslovne svrhe zaštićene?",
    "ue.katalog.85": "ISO/IEC 27001 A.8.20",
    "ue.katalog.86": "Ima li subjekt zaštićeni sustav interne komunikacije za hitne slučajeve, neovisan o osnovnoj infrastrukturi?",
    "ue.katalog.9": "Je li razina sigurnosti dokumentirana kao primjerena postojećem riziku, uz obrazloženje koje uzima u obzir veličinu subjekta te društvene i gospodarske učinke incidenata?",
    "ue.kierownictwo.1": "Upravljačko tijelo ključnog ili važnog subjekta — u društvu kapitala uprava. Direktiva ne definira taj pojam; njegov opseg u pojedinoj državi proizlazi iz nacionalnog prava.",
    "ue.kierownictwo.10": "Utvrditi status subjekta i pobrinuti se za registraciju",
    "ue.kierownictwo.11": "Utvrđivanje je li subjekt ključan ili važan i podnošenje registracijskih podataka nadležnom tijelu. Postupak i rok određuje nacionalno pravo.",
    "ue.kierownictwo.12": "Uvesti analizu rizika i sigurnosnu politiku",
    "ue.kierownictwo.13": "Mjere temeljene na pristupu koji uzima u obzir sve opasnosti, razmjerne izloženosti, veličini subjekta i ozbiljnosti incidenata.",
    "ue.kierownictwo.14": "Pokrenuti postupanje s incidentima i njihovu prijavu",
    "ue.kierownictwo.15": "Postupak postupanja s incidentima i sposobnost poštivanja rokova od 24 sata, 72 sata i mjesec dana.",
    "ue.kierownictwo.16": "24 h / 72 h / mjesec dana od otkrivanja",
    "ue.kierownictwo.17": "Osigurati kontinuitet poslovanja",
    "ue.kierownictwo.18": "Plan kontinuiteta, sigurnosne kopije, oporavak nakon katastrofe, upravljanje krizama.",
    "ue.kierownictwo.19": "Urediti lanac opskrbe",
    "ue.kierownictwo.2": "Odgovornost upravljačkog tijela ne dovodi u pitanje nacionalne propise o odgovornosti javnih institucija i službenika (članak 20. stavak 1. drugi podstavak).",
    "ue.kierownictwo.20": "Popis dobavljača, ocjena njihovih ranjivosti i praksi, sigurnosni zahtjevi u ugovorima.",
    "ue.kierownictwo.21": "Uvesti kontrolu pristupa i upravljanje imovinom",
    "ue.kierownictwo.22": "Popis imovine, načelo najmanjih ovlasti, pregledi ovlasti, višefaktorska autentifikacija tamo gdje to rizik opravdava.",
    "ue.kierownictwo.23": "Mjeriti djelotvornost mjera",
    "ue.kierownictwo.24": "Politika i postupci ocjene djelotvornosti, periodični pregledi, korektivne mjere.",
    "ue.kierownictwo.25": "Odobravati",
    "ue.kierownictwo.26": "mjere upravljanja kibernetičkim sigurnosnim rizicima (članak 20. stavak 1.)",
    "ue.kierownictwo.27": "politiku analize rizika i sigurnosti sustava",
    "ue.kierownictwo.28": "proračun i uloge u provedbi",
    "ue.kierownictwo.29": "Nadzirati",
    "ue.kierownictwo.3": "Isključuje li povjeravanje obveza drugoj osobi odgovornost — odlučuje nacionalno pravo. U Poljskoj ne isključuje (članak 8.c stavak 3. Zakona o nacionalnom sustavu kibernetičke sigurnosti).",
    "ue.kierownictwo.30": "provedbu odobrenih mjera (članak 20. stavak 1.)",
    "ue.kierownictwo.31": "rezultate ocjene djelotvornosti (članak 21. stavak 2. točka (f))",
    "ue.kierownictwo.32": "poštivanje rokova za prijavu incidenata (članak 23.)",
    "ue.kierownictwo.33": "Dokumentirati",
    "ue.kierownictwo.34": "odluke o odobrenju i preglede",
    "ue.kierownictwo.35": "sudjelovanje u osposobljavanju (članak 20. stavak 2.)",
    "ue.kierownictwo.36": "Član upravljačkog tijela",
    "ue.kierownictwo.37": "odobravanje mjera, nadzor, odluke, proračun",
    "ue.kierownictwo.38": "Voditelj projekta",
    "ue.kierownictwo.39": "koordinacija provedbe, raspored, stanje i dokazi",
    "ue.kierownictwo.4": "Odobriti mjere upravljanja kibernetičkim sigurnosnim rizicima",
    "ue.kierownictwo.40": "IT / kibernetička sigurnost",
    "ue.kierownictwo.41": "analiza rizika, tehničke mjere, postupanje s incidentima",
    "ue.kierownictwo.42": "Pravni odjel / usklađenost",
    "ue.kierownictwo.5": "Upravljačko tijelo odobrava mjere donesene radi osiguranja usklađenosti s člankom 21. To je odluka tijela, a ne IT odjela — bez nje mjere nemaju uporište.",
    "ue.kierownictwo.6": "Nadzirati provedbu mjera",
    "ue.kierownictwo.7": "Nadzor nad provedbom obveza je upravljačkog tijela. Izvršenje se može povjeriti, nadzor ne.",
    "ue.kierownictwo.8": "Redovito prolaziti osposobljavanje",
    "ue.kierownictwo.9": "Članovi upravljačkog tijela redovito prolaze osposobljavanje kako bi stekli znanje koje im omogućuje prepoznavanje rizika i ocjenu praksi upravljanja rizicima te njihova utjecaja na usluge subjekta.",
    "ue.kierownictwo.daneRejestracyjne": "registracijski podaci i njihovo ažuriranje (članak 3. stavci 4.–5.)",
    "ue.meta.1": "Prevladava postotna varijanta: {p0} % prometa više je od {p1} mil. EUR.",
    "ue.meta.10": "Direktiva ne nameće obveze izravno poduzetnicima — to čini nacionalni zakon koji je država članica trebala donijeti do 17. listopada 2024. Ovaj modul prikazuje zahtjeve u tekstu Direktive jer modul nacionalnog prava za odabranu državu još nije gotov ili država nije prenijela Direktivu.",
    "ue.meta.11": "Obveze iz Direktive",
    "ue.meta.12": "Popis subjekata — do 17. travnja 2025.",
    "ue.meta.13": "Države članice trebale su do 17. travnja 2025. uspostaviti popis ključnih i važnih subjekata i zahtijevati od subjekata podnošenje registracijskih podataka.",
    "ue.meta.14": "Uredba (EU) 2024/2690",
    "ue.meta.15": "Izravno se primjenjuje od 7. studenoga 2024.",
    "ue.meta.16": "Provedbena uredba izravno se primjenjuje u svim državama članicama, neovisno o stanju prenošenja Direktive. Odnosi se na subjekte navedene u njezinu članku 1.: DNS, vršne domene, oblak, podatkovne centre, mreže za isporuku sadržaja, upravljane usluge i usluge povjerenja.",
    "ue.meta.17": "članak 16. Uredbe (EU) 2024/2690",
    "ue.meta.18": "Najmanje 10 000 000 EUR ili najmanje 2 % ukupnog godišnjeg prometa poduzeća na svjetskoj razini u prethodnoj financijskoj godini — primjenjuje se viši iznos. To je najniža gornja granica: nacionalno je pravo može povisiti.",
    "ue.meta.19": "Najmanje 7 000 000 EUR ili 1,4 % ukupnog godišnjeg prometa na svjetskoj razini — primjenjuje se viši iznos. Najniža gornja granica.",
    "ue.meta.2": "Prevladava fiksni iznos: {p0} mil. EUR više je od {p1} % prometa.",
    "ue.meta.20": "Direktiva ne predviđa zasebnu kaznu za kvalificiranu povredu — to je konstrukcija nacionalnog prava nekih država.",
    "ue.meta.21": "Države članice mogu predvidjeti periodične novčane kazne radi prisile na prestanak povrede. Visinu određuje nacionalno pravo.",
    "ue.meta.22": "Upravljačko tijelo odobrava mjere upravljanja rizicima, nadzire njihovu provedbu i može biti pozvano na odgovornost za povredu članka 21. Pravila i visinu te odgovornosti određuje nacionalno pravo.",
    "ue.meta.23": "Upravljačko tijelo odobrava mjere upravljanja kibernetičkim sigurnosnim rizicima (članak 20. stavak 1.).",
    "ue.meta.24": "Upravljačko tijelo nadzire provedbu tih mjera (članak 20. stavak 1.).",
    "ue.meta.25": "Članovi upravljačkog tijela redovito prolaze osposobljavanje (članak 20. stavak 2.).",
    "ue.meta.26": "Prema ključnom subjektu tijelo može zatražiti privremenu zabranu obavljanja upravljačkih funkcija (članak 32. stavak 5. točka (b)).",
    "ue.meta.27": "Najnižu gornju granicu određuje Direktiva",
    "ue.meta.28": "Uspoređuju se dvije vrijednosti: fiksni iznos u eurima i postotak ukupnog godišnjeg prometa poduzeća na svjetskoj razini u prethodnoj financijskoj godini. Viša od njih gornja je granica koju država članica mora najmanje predvidjeti. Nacionalno je pravo može povisiti.",
    "ue.meta.29": "Iznos u okviru gornje granice određuje nacionalno tijelo",
    "ue.meta.3": "Gornja granica iz Direktive premašuje godišnji promet subjekta {p0} puta. Članak 34. stavak 1. zahtijeva da kazna bude razmjerna okolnostima pojedinog slučaja — to je gornja granica, a ne očekivana kazna.",
    "ue.meta.30": "Kazna mora biti učinkovita, razmjerna i odvraćajuća s obzirom na okolnosti pojedinog slučaja. Tijelo uzima u obzir barem kriterije iz članka 32. stavka 7.: težinu i trajanje povrede, ranije povrede, štetu, namjeru, korektivne mjere i suradnju.",
    "ue.meta.31": "Gornja granica može višestruko premašiti godišnji promet — to je gornja granica, a ne očekivani iznos. Nacionalne minimume, periodične kazne i način odmjeravanja određuje zakon države članice.",
    "ue.meta.32": "Pri odlučivanju o izricanju upravne novčane kazne i o njezinoj visini u svakom se pojedinom slučaju uzimaju u obzir barem elementi navedeni u članku 32. stavku 7.",
    "ue.meta.33": "težina povrede i važnost povrijeđenih odredaba — ozbiljnima se u svakom slučaju smatraju: ponavljane povrede, neprijavljivanje ili neuklanjanje značajnih incidenata, neuklanjanje nedostataka protivno obvezujućim nalozima, ometanje revizija ili praćenja, davanje neistinitih ili grubo netočnih informacija",
    "ue.meta.34": "relevantne ranije povrede subjekta",
    "ue.meta.35": "prouzročena imovinska i neimovinska šteta, uključujući financijske gubitke, utjecaj na druge usluge i broj pogođenih korisnika",
    "ue.meta.36": "namjerna ili nehajna narav djela",
    "ue.meta.37": "mjere poduzete radi sprječavanja ili ublažavanja štete",
    "ue.meta.38": "primjena odobrenih kodeksa ponašanja ili mehanizama certificiranja",
    "ue.meta.39": "stupanj suradnje s nadležnim tijelima",
    "ue.meta.4": "Direktiva (EU) 2022/2555 Europskog parlamenta i Vijeća (NIS 2)",
    "ue.meta.40": "Direktiva ne predviđa izričito odustajanje od kazne — je li i kada moguće, odlučuje nacionalno pravo.",
    "ue.meta.41": "Od tog datuma države članice moraju primjenjivati nacionalne propise kojima se prenosi Direktiva. Konkretan datum od kojeg tijelo može izreći kaznu proizlazi iz nacionalnog prava.",
    "ue.meta.42": "Stupanje na snagu Direktive NIS 2",
    "ue.meta.43": "Dvadesetog dana od objave u Službenom listu.",
    "ue.meta.44": "Rok za prenošenje Direktive",
    "ue.meta.45": "Do tog datuma države članice trebale su donijeti i objaviti nacionalne propise.",
    "ue.meta.46": "Primjena nacionalnih propisa i stavljanje izvan snage NIS 1",
    "ue.meta.47": "Od tog datuma države primjenjuju propise o prenošenju; Direktiva (EU) 2016/1148 stavlja se izvan snage.",
    "ue.meta.48": "Primjena Uredbe (EU) 2024/2690",
    "ue.meta.49": "Provedbena uredba izravno se primjenjuje od dvadesetog dana od objave.",
    "ue.meta.5": "SL EU L 333, 27.12.2022.",
    "ue.meta.50": "Popis ključnih i važnih subjekata",
    "ue.meta.51": "Do tog datuma države članice uspostavljaju popis; subjekti podnose tijelima registracijske podatke.",
    "ue.meta.52": "Prvo preispitivanje Direktive od strane Komisije",
    "ue.meta.53": "Komisija preispituje funkcioniranje Direktive i podnosi izvješće.",
    "ue.meta.54": "Rano upozorenje o značajnom incidentu",
    "ue.meta.55": "24 sata od saznanja",
    "ue.meta.56": "Prijava značajnog incidenta",
    "ue.meta.57": "72 sata od saznanja",
    "ue.meta.58": "Završno izvješće",
    "ue.meta.59": "mjesec dana od prijave incidenta",
    "ue.meta.6": "Provedbena uredba Komisije (EU) 2024/2690",
    "ue.meta.60": "Prijava incidenta od strane pružatelja usluga povjerenja",
    "ue.meta.61": "članak 21. stavak 5. Direktive (EU) 2022/2555; članci 1. i 2. Uredbe (EU) 2024/2690",
    "ue.meta.62": "Bez podataka o prometu gornja je granica fiksni iznos iz Direktive.",
    "ue.meta.63": "Gornje granice iz članka 34. stavaka 4. i 5. najniže su („najmanje”) — nacionalno pravo može predvidjeti više. Iznosi u eurima, bez preračuna u nacionalnu valutu.",
    "ue.meta.64": "Nadležno tijelo države članice",
    "ue.meta.65": "Upravljačko tijelo može biti pozvano na odgovornost za povredu članka 21. Visinu i postupak određuje nacionalno pravo — ovaj ih modul ne poznaje.",
    "ue.meta.66": "Visina osobne odgovornosti uprave proizlazi iz nacionalnog zakona. Za Poljsku iznosi do 300 % primanja (članak 73.a stavak 4. Zakona o nacionalnom sustavu kibernetičke sigurnosti); druge države to uređuju drukčije.",
    "ue.meta.7": "SL EU L, 2024/2690",
    "ue.meta.8": "Direktiva (EU) 2022/2555",
    "ue.meta.9": "Rok za prenošenje istekao je 17. listopada 2024.",
    "ue.moduly.1": "oko {p0} min",
    "ue.moduly.10": "Deset područja iz članka 21. stavka 2. točaka (a)–(j): od politike rizika do višefaktorske autentifikacije. Povreda je kažnjiva novčanom kaznom iz članka 34. Ocjena na ljestvici zrelosti.",
    "ue.moduly.11": "Uredba 2024/2690 — upravljanje i procesi",
    "ue.moduly.12": "Odjeljci 1.–5. i 7.–8. Priloga: politike, upravljanje rizicima, postupanje s incidentima, kontinuitet poslovanja, lanac opskrbe, ocjena djelotvornosti, kibernetička higijena. Izravno se primjenjuje od 7. studenoga 2024.",
    "ue.moduly.13": "Uredba 2024/2690 — tehnički zahtjevi",
    "ue.moduly.14": "Odjeljci 6. i 9.–13. Priloga: nabava i razvoj sustava, kriptografija, sigurnost ljudskih resursa, kontrola pristupa, upravljanje imovinom, fizička sigurnost i sigurnost okoliša.",
    "ue.moduly.2": "oko {p0} h {p1} min",
    "ue.moduly.3": "oko {p0} h",
    "ue.moduly.4": "manje od minute",
    "ue.moduly.5": "Brza ocjena rizika",
    "ue.moduly.6": "Nadređena pitanja iz svih područja Direktive. Svako odlučuje o cijeloj skupini tema. Omogućuje procjenu opsega zaostataka bez prolaska kroz cijeli upitnik.",
    "ue.moduly.7": "Obveze iz Direktive",
    "ue.moduly.8": "Registracijski podaci, prijava incidenata u 24 i 72 sata, obveze upravljačkog tijela, spremnost za nadzor. Provjerljivo iz dokumenata, bez tehničke analize.",
    "ue.moduly.9": "Mjere upravljanja rizicima — članak 21. stavak 2.",
    "ue.obowiazki.1": "Registracijski podaci za popis subjekata",
    "ue.obowiazki.10": "Prijava značajnih incidenata",
    "ue.obowiazki.11": "Subjekt prijavljuje značajne incidente CSIRT-u ili nadležnom tijelu u tri koraka: rano upozorenje, prijava, završno izvješće. Rokovi teku od saznanja o incidentu.",
    "ue.obowiazki.12": "Može li subjekt dostaviti rano upozorenje u roku od 24 sata od saznanja o značajnom incidentu, s naznakom je li incident vjerojatno izazvan nezakonitim radnjama i može li imati prekogranični učinak?",
    "ue.obowiazki.13": "24 sata od saznanja",
    "ue.obowiazki.14": "Može li subjekt dostaviti prijavu incidenta u roku od 72 sata, s početnom procjenom ozbiljnosti i učinaka te pokazateljima kompromitiranosti?",
    "ue.obowiazki.15": "72 sata od saznanja",
    "ue.obowiazki.16": "Dostavlja li subjekt završno izvješće najkasnije mjesec dana nakon prijave, s opisom incidenta, vrstom prijetnje, korektivnim mjerama i prekograničnim učinkom?",
    "ue.obowiazki.17": "mjesec dana od prijave",
    "ue.obowiazki.18": "Obavješćuje li subjekt primatelje svojih usluga o značajnim incidentima koji mogu negativno utjecati na pružanje tih usluga?",
    "ue.obowiazki.19": "Obavješćuje li subjekt primatelje usluga o značajnoj kibernetičkoj prijetnji i korektivnim mjerama koje primatelji mogu primijeniti?",
    "ue.obowiazki.2": "Države članice uspostavljaju popis ključnih i važnih subjekata i zahtijevaju od subjekata podnošenje registracijskih podataka. Postupak, rok i portal određuje nacionalno pravo.",
    "ue.obowiazki.20": "Ako je subjekt pružatelj usluga povjerenja — prijavljuje li značajne incidente u roku od 24 sata od saznanja?",
    "ue.obowiazki.21": "odnosi se na pružatelje usluga povjerenja",
    "ue.obowiazki.22": "Upravljačko tijelo",
    "ue.obowiazki.23": "Upravljačko tijelo odobrava mjere upravljanja rizicima, nadzire njihovu provedbu i može biti pozvano na odgovornost. Članovi tijela redovito prolaze osposobljavanje.",
    "ue.obowiazki.24": "Je li upravljačko tijelo formalno odobrilo mjere upravljanja kibernetičkim sigurnosnim rizicima donesene radi osiguranja usklađenosti s člankom 21.?",
    "ue.obowiazki.25": "Nadzire li upravljačko tijelo provedbu tih mjera na dokumentiran način — primjerice periodičnim izvješćima i pregledima?",
    "ue.obowiazki.26": "Prolaze li članovi upravljačkog tijela redovito osposobljavanje koje omogućuje prepoznavanje rizika i ocjenu praksi upravljanja rizicima, a sudjelovanje je dokumentirano?",
    "ue.obowiazki.27": "Spremnost za nadzorne radnje",
    "ue.obowiazki.28": "Ključni subjekt podliježe nadzoru ex ante i ex post, važan subjekt — isključivo ex post. Tijelo može zahtijevati informacije, dokaze o provedbi politika i rezultate revizija.",
    "ue.obowiazki.29": "Može li subjekt na zahtjev tijela predočiti dokaze o provedbi politika kibernetičke sigurnosti, uključujući rezultate sigurnosnih revizija?",
    "ue.obowiazki.3": "Je li subjekt utvrdio je li ključni ili važan subjekt, na temelju sektora iz Priloga I. ili II. i veličine poduzeća?",
    "ue.obowiazki.30": "Može li subjekt na zahtjev tijela staviti na raspolaganje podatke, dokumente i informacije potrebne za obavljanje nadzornih zadaća?",
    "ue.obowiazki.31": "Je li ključni subjekt spreman za sigurnosnu reviziju koju provodi tijelo ili neovisni subjekt, o vlastitom trošku?",
    "ue.obowiazki.4": "Je li subjekt nadležnom tijelu podnio registracijske podatke: naziv, adresu i podatke za kontakt, sektor i podsektor, popis država članica u kojima pruža usluge?",
    "ue.obowiazki.5": "Podaci za kontakt obuhvaćaju adrese e-pošte, raspone IP adresa i telefonske brojeve. Nacionalni rok i portal za registraciju određuje pravo države članice.",
    "ue.obowiazki.6": "Postoji li proces ažuriranja registracijskih podataka bez nepotrebne odgode nakon njihove promjene?",
    "ue.obowiazki.7": "Direktiva zahtijeva ažuriranje bez nepotrebne odgode; konkretan rok — primjerice 14 dana u Poljskoj — proizlazi iz nacionalnog prava.",
    "ue.obowiazki.8": "Ako je subjekt pružatelj DNS-a, registar vršne domene, pružatelj usluga u oblaku, podatkovnog centra, CDN-a, upravljanih usluga, internetsko tržište, tražilica ili društvena mreža — je li podnio dodatne podatke iz članka 27., uključujući adresu glavnog poslovnog nastana u Uniji?",
    "ue.obowiazki.9": "odnosi se na subjekte iz članka 26. stavka 1.",
    "ue.role.1": "Nadležno tijelo države članice",
    "ue.role.10": "Usluge podatkovnog centra: kolokacija, hosting infrastrukture i povezane usluge.",
    "ue.role.11": "Podatkovni centri",
    "ue.role.12": "Ključni subjekt iznad praga srednjeg poduzeća (članak 3. stavak 1. točka (a)), važan pri srednjoj veličini (članak 3. stavak 2.). Ispod srednje veličine — izvan područja primjene, osim ako država članica ne odredi subjekt na temelju članka 2. stavka 2. točaka (b)–(e). Obuhvaćen Uredbom 2024/2690.",
    "ue.role.13": "Pružatelj usluga točke razmjene internetskog prometa",
    "ue.role.14": "Infrastruktura koja omogućuje razmjenu prometa između neovisnih mreža.",
    "ue.role.15": "Točke razmjene internetskog prometa",
    "ue.role.16": "Klasifikacija prema veličini (članak 3. stavak 1. točka (a) i stavak 2.). Uredba 2024/2690 ne obuhvaća točke razmjene internetskog prometa — članak 1. Uredbe sadrži zatvoreni popis adresata.",
    "ue.role.17": "Pružatelj usluga DNS-a",
    "ue.role.18": "Usluge razrješavanja naziva domena, isključujući operatore korijenskih poslužitelja naziva.",
    "ue.role.19": "Sustav naziva domena",
    "ue.role.2": "nadležno tijelo",
    "ue.role.20": "Ključni subjekt neovisno o veličini (članak 3. stavak 1. točka (b)). Obuhvaćen Uredbom 2024/2690.",
    "ue.role.21": "Registar naziva vršnih domena",
    "ue.role.22": "Vođenje registra vršne domene.",
    "ue.role.23": "Ključni subjekt neovisno o veličini (članak 3. stavak 1. točka (b)). Dodatno obveze u vezi s registracijskim podacima iz članka 28. Obuhvaćen Uredbom 2024/2690.",
    "ue.role.24": "Pružatelj usluga računalstva u oblaku",
    "ue.role.25": "Usluge računalstva u oblaku: infrastruktura, platforma, softver kao usluga.",
    "ue.role.26": "Usluge računalstva u oblaku",
    "ue.role.27": "Klasifikacija prema veličini (članak 3. stavak 1. točka (a) i stavak 2.). Obuhvaćen Uredbom 2024/2690.",
    "ue.role.28": "Pružatelj mreže za isporuku sadržaja",
    "ue.role.29": "Mreža distribuiranih poslužitelja koji isporučuju sadržaj i usluge krajnjim korisnicima.",
    "ue.role.3": "određuje nacionalno pravo; do uvođenja nacionalnog modula alat ne navodi konkretnu instituciju",
    "ue.role.30": "Mreže za isporuku sadržaja",
    "ue.role.31": "Pružatelj usluga povjerenja",
    "ue.role.32": "Usluge povjerenja u smislu Uredbe (EU) br. 910/2014: potpisi, pečati, vremenski žigovi, certifikati.",
    "ue.role.33": "Usluge povjerenja",
    "ue.role.34": "Obuhvaćen Direktivom neovisno o veličini (članak 2. stavak 2. točka (a) podtočka ii.). Kvalificirani pružatelj ključni je subjekt neovisno o veličini (članak 3. stavak 1. točka (b)); nekvalificirani je ključan iznad praga srednjeg poduzeća, inače važan. Obuhvaćen Uredbom 2024/2690.",
    "ue.role.35": "Pružatelj upravljanih usluga",
    "ue.role.36": "Upravljanje IKT infrastrukturom klijenta: instalacija, održavanje, podrška, administriranje sustava.",
    "ue.role.37": "Upravljanje IKT uslugama (B2B)",
    "ue.role.38": "Upravljane usluge",
    "ue.role.39": "Pružatelj upravljanih sigurnosnih usluga",
    "ue.role.4": "Pružatelj javnih elektroničkih komunikacijskih mreža ili javno dostupnih elektroničkih komunikacijskih usluga",
    "ue.role.40": "Upravljane usluge u području kibernetičke sigurnosti: praćenje, odgovor na incidente, testiranja, savjetovanje.",
    "ue.role.41": "Upravljane sigurnosne usluge",
    "ue.role.42": "Direktiva klasificira prema veličini (članak 3. stavak 1. točka (a) i stavak 2.). Države članice mogu pooštriti prag — Poljska MSSP smatra ključnim subjektom već od malog poduzeća; ovaj modul primjenjuje isključivo pravilo Direktive. Obuhvaćen Uredbom 2024/2690.",
    "ue.role.5": "Pružanje javnih elektroničkih komunikacijskih mreža ili javno dostupnih elektroničkih komunikacijskih usluga, uključujući pristup internetu.",
    "ue.role.6": "Digitalna infrastruktura",
    "ue.role.7": "Elektroničke komunikacije",
    "ue.role.8": "Obuhvaćen Direktivom neovisno o veličini (članak 2. stavak 2. točka (a) podtočka i.). Srednje ili veće poduzeće ključni je subjekt (članak 3. stavak 1. točka (c)), mikro i malo — važan (članak 3. stavak 2.). Nacionalni zakon o elektroničkim komunikacijama može nametnuti dodatne obveze — ovaj ih modul ne sadrži.",
    "ue.role.9": "Pružatelj usluga podatkovnog centra",
    "ue.role.podstawaArt3b": "članak 3. stavak 1. točka (b) Direktive (EU) 2022/2555",
    "ue.zaslepki.1": "Direktiva (EU) 2022/2555 Europskog parlamenta i Vijeća (NIS 2)",
    "ue.zaslepki.10": "Upisuje li se dio subjekata po službenoj dužnosti, odlučuje nacionalno pravo.",
    "ue.zaslepki.11": "Utvrdite podliježete li Direktivi",
    "ue.zaslepki.12": "Sektor iz Priloga I. ili II. i veličina poduzeća. Taj dio obavlja profil subjekta u ovom alatu.",
    "ue.zaslepki.13": "Utvrdite nadležno tijelo u svojoj državi",
    "ue.zaslepki.14": "Svaka država određuje nadležno tijelo (članak 8. stavak 1.). Ažurni popis vode ENISA i Komisija.",
    "ue.zaslepki.15": "Podnesite registracijske podatke",
    "ue.zaslepki.16": "Naziv, adresa i podaci za kontakt, sektor i podsektor, države pružanja usluga (članak 3. stavak 4.). Postupak prema nacionalnom pravu.",
    "ue.zaslepki.17": "Ažurirajte podatke bez nepotrebne odgode",
    "ue.zaslepki.18": "Svaka promjena registracijskih podataka zahtijeva ažuriranje (članak 3. stavak 5.).",
    "ue.zaslepki.19": "adresa i aktualni podaci za kontakt: adrese e-pošte, rasponi IP adresa, telefonski brojevi",
    "ue.zaslepki.2": "SL EU L 333, 27.12.2022., str. 80",
    "ue.zaslepki.20": "sektor i podsektor iz Priloga I. ili II.",
    "ue.zaslepki.21": "popis država članica u kojima subjekt pruža usluge",
    "ue.zaslepki.22": "Određuje nacionalno pravo.",
    "ue.zaslepki.23": "Direktiva (EU) 2022/2555 — članak 3.",
    "ue.zaslepki.24": "ENISA — nadležna tijela država članica",
    "ue.zaslepki.25": "Direktiva (EU) 2022/2555",
    "ue.zaslepki.26": "Modul EU-a ne sadrži smjernice nacionalnog tijela — one će doći s modulom nacionalnog prava.",
    "ue.zaslepki.27": "Automatsko dohvaćanje podataka iz registra radi samo za države s modulom nacionalnog prava. Ispunite profil ručno.",
    "ue.zaslepki.28": "Čitanje financijskog izvješća radi samo za države s modulom nacionalnog prava. Unesite prihod i broj zaposlenih ručno.",
    "ue.zaslepki.3": "Provedbena uredba Komisije (EU) 2024/2690",
    "ue.zaslepki.4": "SL EU L, 2024/2690, 18.11.2024.",
    "ue.zaslepki.5": "Direktiva NIS 2 ne sadrži zaseban sloj elektroničkih komunikacija. Nacionalno pravo elektroničkih komunikacija može nametnuti dodatne obveze — ovaj ih modul ne poznaje.",
    "ue.zaslepki.6": "Popis ključnih i važnih subjekata",
    "ue.zaslepki.7": "Nadležno tijelo države članice.",
    "ue.zaslepki.8": "Direktiva nalaže državama članicama vođenje popisa ključnih i važnih subjekata i zahtijevanje od subjekata podnošenja registracijskih podataka. Portal, postupak i rok određuje nacionalno pravo — ovaj ih modul ne poznaje jer modul nacionalnog prava za odabranu državu još nije gotov.",
    "ue.zaslepki.9": "Svi ključni i važni subjekti. Rok određuje nacionalno pravo.",
    "ue.zaslepki.skrotDyrektywy": "Direktiva NIS 2",
    "ue.zaslepki.skrotReg2690": "Uredba 2024/2690",
    "xlsx.1": "{p0} – {p1} EUR",
    "xlsx.25": "Tečaj",
    "xlsx.4": "IZVJEŠĆE O USKLAĐENOSTI S DIREKTIVOM NIS 2 (EU) 2022/2555",
    "xlsx.58": "Djelatnost elektroničkih komunikacija: Uredba (EU) 2024/2690 ne primjenjuje se. Pragove određuje nacionalno pravo (članak 23. stavak 11. Direktive) — zajednički ih modul ne poznaje.",
    "xlsx.68": "Alat služi samoocjeni. Nije revizija ni pravno mišljenje.",
    "xlsx.69": "Za subjekte koji nisu obuhvaćeni Uredbom (EU) 2024/2690 pragove značajnog incidenta određuje nacionalno pravo (članak 23. stavak 11. Direktive).",
    "xlsx.70": "Uloge navedene u profilu su izjava. O statusu odlučuje stvarno obavljana djelatnost (članak 3. Direktive (EU) 2022/2555).",
    "xlsx.etykietaKrs": "Registarski broj",
    "xlsx.etykietaNip": "Identifikacijski broj",
    "xlsx.etykietaRegon": "Statistički broj"
});
