/* Teksty modułu ue — język: hu.
   Te same klucze co w napisy/pl.js (wersja źródłowa); wstawki {p0}, {p1}…
   pozostają bez zmian. Klucze ue.cyt.* to wzorce składania odesłań
   do przepisów w tym języku — patrz kraje/ue/cytaty.js. */
KRAJE.napisy('ue', 'hu', {
    "app.10": "Ellenőrizze az alábbi szereplistát — a státuszt a ténylegesen végzett tevékenység határozza meg (az (EU) 2022/2555 irányelv 3. cikke), nem a nyilvántartási bejegyzés.",
    "app.14": "Előző év: {p0} EUR",
    "app.15": "A beszámolási időszak árbevétele: {p0} EUR",
    "app.19": "Nyilvántartások lekérdezése a(z) {p0} szám alapján…",
    "app.34": " Mrd EUR",
    "app.35": " M EUR",
    "app.36": " E EUR",
    "app.37": "",
    "app.4": "A nyilvántartási adatok automatikus lekérése ebben az országban nem elérhető — töltse ki a profilt kézzel.",
    "app.59": "NIS 2 irányelv megfelelési értékelés (JSON)",
    "app.68": "Ehhez az országhoz nincs olyan nyilvántartás, amelyből az eszköz adatokat kérhetne le — a profilt kézzel kell kitölteni.",
    "app.69": "Ehhez az országhoz nincs olyan nyilvántartás, amelyből az eszköz adatokat kérhetne le. Kattintson az offline mód bekapcsolásához.",
    "app.73": " · eredménykimutatás a következő változatban: ",
    "app.74": "<div class=\"mt-2 tekst-uwaga\">A nyilvántartási adatokból nem következik digitális infrastruktúra ágazati szerep. A szerepeket adja meg kézzel alább.</div>",
    "app.8": "Az elektronikus hírközlési szolgáltatók nyilvántartásába való bejegyzés megerősítve",
    "app.progDostawcy": "",
    "app.przyklad.adres": "Minta utca 1., 1000 Város",
    "app.przyklad.forma": "Korlátolt felelősségű társaság",
    "app.przyklad.nazwa": "Minta Szolgáltató Kft.",
    "app.statusVat": " · áfastátusz: ",
    "dashboard.1": "A megadott szerepek és méret alapján a szervezet az (EU) 2022/2555 irányelv 3. cikke értelmében sem alapvető, sem fontos szervezetnek nem minősül. Ellenőrizze a profilt, ha az eredmény eltér a várttól.",
    "dashboard.113": "Gyakori kérdések",
    "dashboard.12": "— {p0}; a nemzeti jogba való átültetés határideje lejárt: {p2}",
    "dashboard.123": "NIS 2 irányelv",
    "dashboard.30": "Az alapvető és fontos szervezetek jegyzéke",
    "dashboard.4": "— közvetlenül alkalmazandó {p0} óta minden tagállamban, átültetés nélkül",
    "dashboard.42": "Összegszerű változat: {p0}",
    "dashboard.45": "Az irányelv 32. cikk (7) bekezdésének szempontjai:",
    "dashboard.46": "Összesen",
    "dashboard.49": "A szervezet elektronikus hírközlési tevékenységet végez — a vezető felelősségét a nemzeti jog határozza meg",
    "dashboard.50": "",
    "dashboard.51": "",
    "dashboard.53": "Kényszerítő bírság a határozat végrehajtásának késedelme miatt: {p0} EUR-tól {p1} EUR-ig naponta ({p2})",
    "dashboard.54": "Minősített eset: legfeljebb {p0} EUR ({p1})",
    "dashboard.57": "({p0}). Azt, hogy a nemzeti hatóság mikortól szabhat ki bírságot, az irányelvet átültető törvény határozza meg — ezt a modul nem ismeri. A bevezetési kötelezettségek a nemzeti jog hatálybalépésétől következnek.",
    "dashboard.65": "({p0}). Azt, hogy a nemzeti hatóság mikortól szabhat ki bírságot, az irányelvet átültető törvény határozza meg — ezt a modul nem ismeri. A pénzügyi kockázat itt ezért nincs dátumhoz kötve, a bevezetési kötelezettségek viszont a nemzeti jog hatálybalépésétől következnek.",
    "dashboard.83": "Elektronikus hírközlési tevékenység — a küszöbértékeket a nemzeti jog határozza meg.",
    "dashboard.84": "Az (EU) 2024/2690 rendelet nem vonatkozik a nyilvános elektronikus hírközlő hálózatok és szolgáltatások szolgáltatóira. Esetükben a jelentős incidens küszöbértékeit a nemzeti jog határozza meg (az irányelv 23. cikk (11) bekezdése) — ezt a modul nem ismeri, ezért nem ad meg számértékeket.",
    "dashboard.terminRejestracji": "A nyilvántartási adatok benyújtásának határidejét a nemzeti jog határozza meg (az irányelv 3. cikk (4) bekezdése). A 27. cikk (1) bekezdése szerinti szolgáltatók — DNS-szolgáltatók, TLD-nyilvántartók, felhő-, adatközponti, tartalomszolgáltató hálózati, irányított és irányított biztonsági szolgáltatók — adataikat az ENISA nyilvántartásába továbbítják: eredetileg 2025. január 17-ig, minden változást pedig indokolatlan késedelem nélkül.",
    "html.1": "ITORO — Az (EU) 2022/2555 NIS 2 irányelv megfelelési értékelése",
    "html.10": "NIS 2 irányelv megfelelési értékelés — közös modul",
    "html.100": "A beszámoló beolvasása csak a nemzeti jogi modullal rendelkező országoknál működik. Ebben az országban az üzleti év <strong>árbevételét</strong> kézzel adja meg — ettől függ a bírság mértéke.",
    "html.102": "A nyilvántartási adatok automatikus lekérése csak a nemzeti jogi modullal rendelkező országoknál működik. A szerepeket és a vállalkozás méretét kézzel adja meg.",
    "html.11": "Az (EU) 2022/2555 irányelv (NIS 2) átültetést igényel a nemzeti jogba. Az értékelés az irányelvből közvetlenül következő kötelezettségekre és a Bizottság közvetlenül alkalmazandó (EU) 2024/2690 végrehajtási rendeletére terjed ki — amennyiben a szervezetet érintik.",
    "html.23": "az árbevételt és a méretet kézzel adja meg — a közös modul nem kérdezi le a nemzeti nyilvántartásokat",
    "html.33": "az Európai Parlament és a Tanács (EU) 2022/2555 irányelve (2022. december 14.) (NIS 2)",
    "html.33a": "{p0} — az irányelvet átültető nemzeti jogszabály; követelményeit ez a modul még nem értékeli",
    "html.33b": "az állam még nem fogadott el átültető jogszabályt — az értékelés az uniós jogot követi",
    "html.35": "az irányító testület kötelezettségei — az irányelv 20. cikke",
    "html.36": "Az eszköz önértékelést szolgál. Nem audit és nem jogi vélemény.",
    "html.40": "a közös modul semmilyen kimenő kapcsolatot nem létesít — nem kérdezi le a nyilvántartásokat",
    "html.59": "Beszámolók",
    "html.60": "A beszámoló beolvasása csak a nemzeti jogi modullal rendelkező országoknál elérhető. Ebben az országban az árbevételt és a létszámot kézzel adja meg.",
    "html.62": "Keresés nyilvántartásban",
    "html.63": "a cégnyilvántartások nemzetiek — a közös modul nem ismeri őket",
    "html.64": "a szerepeket és a vállalkozás méretét kézzel adja meg",
    "html.66": "A szervezet azonosítószáma",
    "html.68": "A nyilvántartási adatok automatikus lekérése csak a nemzeti jogi modullal rendelkező országoknál működik.",
    "html.76": "Éves árbevétel (EUR)",
    "html.78": "Az elektronikus hírközlési tevékenység árbevétele (EUR)",
    "html.79": "A mező a nyilvános elektronikus hírközlő hálózatok vagy szolgáltatások szolgáltatóira vonatkozik. A nemzeti küszöbértékeket a tagállam joga határozza meg.",
    "html.80": "A vezető havi javadalmazása (EUR)",
    "html.82": "Árfolyam",
    "html.83": "Az irányelvben a bírsághatárok euróban szerepelnek. A nemzeti valutára való átváltást és az árfolyamot a nemzeti jog határozza meg — itt az összegek euróban, átváltás nélkül szerepelnek.",
    "html.84": "A státusz kizárólag a kapcsolt vállalkozások adatainak összesítéséből ered, és a szervezet információs rendszere független (az irányelv (16) preambulumbekezdése — az alkalmazásról a nemzeti jog dönt)",
    "html.85": "A szervezet a nemzetbiztonság, a közbiztonság, a honvédelem vagy a bűnüldözés területén tevékenykedik (az irányelv 2. cikk (7) bekezdése)",
    "html.91": "Megfelelési értékelés az Európai Parlament és a Tanács (EU) 2022/2555 irányelve (NIS 2) és a Bizottság (EU) 2024/2690 végrehajtási rendelete alapján — közös modul azoknak az országoknak, amelyek nemzeti jogi modulja még nem készült el.",
    "html.94": "hogy a szervezet <strong>alapvető</strong>, <strong>fontos</strong>, vagy az irányelv hatályán kívül esik",
    "html.daneZeSprawozdania": "név, azonosítószám, székhely címe",
    "html.rejestrMozliwy": "A(z) {p0} nyilvántartás nyilvános és ingyenes — beolvasása hozzáadható az eszközhöz; szívesen fogadunk pull requestet (lásd a README-t).",
    "html.tytulNaglowka": "NIS 2 irányelv megfelelési értékelés",
    "html.zrodlaRecznie": "Ez a modul nem ismeri az Ön államának nyilvántartásait — töltse ki a profilt kézzel. Az éves árbevétel határozza meg a bírság felső határát, ezért pontosan adja meg.",
    "klasyfikacja.10": "az (EU) 2022/2555 irányelv 3. cikk (1) bekezdés c) pontja (nyilvános elektronikus hírközlő hálózatok vagy nyilvánosan elérhető elektronikus hírközlési szolgáltatások legalább középvállalkozásnak minősülő szolgáltatója)",
    "klasyfikacja.11": "az (EU) 2022/2555 irányelv 3. cikk (2) bekezdése a 2. cikk (2) bekezdés a) pont i. alpontjával összefüggésben (nyilvános elektronikus hírközlő hálózatok vagy szolgáltatások mikro- vagy kisvállalkozásnak minősülő szolgáltatója)",
    "klasyfikacja.12": "az (EU) 2022/2555 irányelv 3. cikk (1) bekezdés a) pontja (a középvállalkozás határértékeit meghaladó irányított biztonsági szolgáltató)",
    "klasyfikacja.13": "A mikro- és kisvállalkozások e szerep alapján nem tartoznak az irányelv hatálya alá (2. cikk (1) bekezdés, a contrario).",
    "klasyfikacja.15": "az (EU) 2022/2555 irányelv 3. cikk (1) bekezdés b) pontja (minősített bizalmi szolgáltató) — a vállalkozás méretétől függetlenül",
    "klasyfikacja.16": "az (EU) 2022/2555 irányelv 3. cikk (2) bekezdése a 2. cikk (2) bekezdés a) pont ii. alpontjával összefüggésben (mikro-, kis- vagy középvállalkozásnak minősülő, nem minősített bizalmi szolgáltató)",
    "klasyfikacja.18": "az (EU) 2022/2555 irányelv 3. cikk (2) bekezdése (regionális szintű közigazgatási szervezet, ha a tagállam így rendelkezik — 2. cikk (2) bekezdés f) pont ii. alpont)",
    "klasyfikacja.19": "az (EU) 2022/2555 irányelv 3. cikk (1) bekezdés f) pontja (központi szintű közigazgatási szervezet — 2. cikk (2) bekezdés f) pont i. alpont)",
    "klasyfikacja.2": "Előzetes és utólagos felügyelet (az (EU) 2022/2555 irányelv 32. cikke).",
    "klasyfikacja.20": "az (EU) 2022/2555 irányelv 3. cikk (2) bekezdése (regionális szintű közigazgatási szervezet — 2. cikk (2) bekezdés f) pont ii. alpont)",
    "klasyfikacja.21": "A helyi szintű közigazgatási szervezetek kötelezettségeinek körét a nemzeti jog határozza meg (az irányelv 2. cikk (5) bekezdés a) pontja).",
    "klasyfikacja.22": "A tagállam mentesítheti a nemzetbiztonság, a közbiztonság, a honvédelem vagy a bűnüldözés területén tevékenykedő szervezeteket (az irányelv 2. cikk (7) bekezdése). A mentesség nem működik magától — az értékelés eredményét a nemzeti joggal kell egybevetni.",
    "klasyfikacja.23": "A szervezet az alapvető és a fontos szervezet kritériumait egyaránt teljesíti. Alapvető szervezet (az irányelv 3. cikk (1) bekezdése), és a szigorúbb követelmények az irányelv hatálya alá tartozó teljes tevékenységre vonatkoznak.",
    "klasyfikacja.25": "A szervezet alapvető, ezért az irányelv 21. cikk (2) bekezdése szerinti teljes intézkedéskatalógus és az előzetes és utólagos felügyelet vonatkozik rá — az értékelés a teljes kérdéskészletre kiterjed.",
    "klasyfikacja.26": "Fontos szervezetként ugyanaz a 21. cikk (2) bekezdése szerinti intézkedéskatalógus vonatkozik Önökre, de csak utólagos felügyelet (33. cikk). A bírság felső határa alacsonyabb: 7 millió EUR vagy az árbevétel 1,4 %-a (34. cikk (5) bekezdés). A közintézményekre vonatkozó könnyítéseket a nemzeti jog vezethet be — ezt a modul nem ismeri.",
    "klasyfikacja.28": "A közigazgatási szervezetek kötelezettségei az irányelv 2. cikk (2) bekezdés f) pontjából következnek; pontos körüket, ideértve a helyi szintet és az oktatási intézményeket, a nemzeti jog határozza meg (2. cikk (5) bekezdés).",
    "klasyfikacja.29": "A nyilatkozat szerint a szervezet státusza kizárólag a kapcsolt vagy partnervállalkozások adatainak összesítéséből ered, és a szervezet információs rendszere független. Az irányelv megengedi ezt a kizárást ((16) preambulumbekezdés), de erről a nemzeti jog dönt — a modul feltételezi a kizárást, amelyet a tagállam jogával egybe kell vetni és dokumentálni kell.",
    "klasyfikacja.4": "Kizárólag utólagos felügyelet — jogsértésre utaló bizonyíték, jel vagy információ esetén (az (EU) 2022/2555 irányelv 33. cikke).",
    "klasyfikacja.5": "Az irányelv hatályán kívül",
    "klasyfikacja.6": "A megadott szerephez nem következik kötelezettség az (EU) 2022/2555 irányelvből.",
    "klasyfikacja.7": "az (EU) 2022/2555 irányelv 3. cikk (1) bekezdés a) pontja (az I. mellékletben felsorolt típusú, a középvállalkozás határértékeit meghaladó szervezet)",
    "klasyfikacja.8": "az (EU) 2022/2555 irányelv 3. cikk (2) bekezdése (az I. mellékletben felsorolt típusú, a középvállalkozás kritériumainak megfelelő szervezet)",
    "klasyfikacja.9": "A mikro- és kisvállalkozások e szerep alapján nem tartoznak az irányelv hatálya alá (2. cikk (1) bekezdés, a contrario).",
    "kreator.10": "Az előző évi árbevételt adja meg kézzel.",
    "kreator.35": "<span class=\"text-secondary\">A beszámolók beolvasása ebben az országban nem elérhető.</span>",
    "kreator.37": "A beszámolók beolvasása ebben az országban nem elérhető — adja meg az árbevételt kézzel.",
    "kreator.56": "Igen — az uniós rendelet 2024. november 7. óta közvetlenül alkalmazandó minden tagállamban, átmeneti időszak nélkül. Az alapja",
    "kreator.57": ", amely felhatalmazta a Bizottságot, hogy a rendelet 3. cikk (1) bekezdésében felsorolt szolgáltatókra műszaki és módszertani követelményeket állapítson meg. Az irányelv átültetési határideje lejárt:",
    "kreator.58": ", azt pedig, hogy a nemzeti hatóság mikortól szabhat ki bírságot, a nemzeti jog határozza meg. A melléklet műszaki követelményei (6. és 9–13. szakasz) jelenlegi szövegükben kötelezőek — nem várnak pontosításra. Csak az „adott esetben” kitétellel ellátott követelményektől lehet eltérni, és kizárólag dokumentált indoklással.",
    "kreator.9": "Beszámolók →",
    "kreator.przepisReg2690": "az (EU) 2022/2555 irányelv 21. cikk (5) bekezdése",
    "kreator.terminReg2690": "2024. október 17.",
    "punktacja.10": "Közintézmények",
    "punktacja.4": "NIS 2 irányelv — 21. cikk",
    "punktacja.5": "NIS 2 irányelv — formális kötelezettségek",
    "punktacja.8": "Elektronikus hírközlés",
    "punktacja.9": "NIS 2 irányelv — közintézmények",
    "punktacja.skrotKsc": "NIS 2",
    "punktacja.skrotPke": "hírközlés",
    "ue.cyt.akapit": "{p0} albekezdés",
    "ue.cyt.art": "{p0}. cikk",
    "ue.cyt.drugi": "második",
    "ue.cyt.dyr": "az (EU) 2022/2555 irányelv {p0}",
    "ue.cyt.i": "és",
    "ue.cyt.laczenie": " ",
    "ue.cyt.lit": "{p0}) pont",
    "ue.cyt.litery": "",
    "ue.cyt.pkt": "{p0}. pont",
    "ue.cyt.rozdzielacz": "; ",
    "ue.cyt.rozp": "az (EU) 2024/2690 rendelet {p0}",
    "ue.cyt.ust": "({p0}) bekezdés",
    "ue.katalog.1": "Kockázatelemzési és információsrendszer-biztonsági szabályzatok",
    "ue.katalog.10": "Incidenskezelés",
    "ue.katalog.11": "Az incidenskezelés az incidensek megelőzésére, észlelésére, elemzésére, elszigetelésére, az azokra való reagálásra és a helyreállításra irányuló intézkedéseket és eljárásokat foglalja magában (6. cikk 8. pont).",
    "ue.katalog.12": "Létezik dokumentált incidenskezelési eljárás, amely kiterjed az észlelésre, az elemzésre, az elszigetelésre, a reagálásra és a helyreállításra?",
    "ue.katalog.13": "ISO/IEC 27001 A.5.24–A.5.26",
    "ue.katalog.14": "Lehetővé teszi az eljárás a jelentős incidens bejelentési határidőinek betartását: korai figyelmeztetés 24 órán belül, bejelentés 72 órán belül, végleges jelentés egy hónapon belül?",
    "ue.katalog.15": "ISO/IEC 27001 A.5.24",
    "ue.katalog.16": "Rendelkezik a szervezet a 23. cikk (3) bekezdésének megfelelő kritériumokkal az incidens jelentősnek minősítéséhez: súlyos működési zavar vagy pénzügyi veszteség, illetve más személyeknek okozott jelentős kár?",
    "ue.katalog.17": "ISO/IEC 27001 A.5.25",
    "ue.katalog.18": "Nyilvántartják az incidenseket, és kezelésük tanulságait felhasználják az intézkedések javítására?",
    "ue.katalog.19": "ISO/IEC 27001 A.5.27",
    "ue.katalog.2": "Az intézkedések minden veszélyt figyelembe vevő megközelítésen alapulnak (21. cikk (2) bekezdés). Arányosságukat a kitettség mértékének, a szervezet méretének, az incidensek valószínűségének és súlyosságának figyelembevételével kell értékelni (21. cikk (1) bekezdés második albekezdés).",
    "ue.katalog.20": "Üzletmenet-folytonosság és válságkezelés",
    "ue.katalog.21": "Üzletmenet-folytonosság, például biztonsági mentések kezelése és katasztrófa utáni helyreállítás, valamint válságkezelés.",
    "ue.katalog.22": "Létezik üzletmenet-folytonossági terv, amely kiterjed a katasztrófa utáni helyreállításra?",
    "ue.katalog.23": "ISO/IEC 27001 A.5.29–A.5.30",
    "ue.katalog.24": "Készülnek biztonsági mentések, védettek és tesztelik a visszaállíthatóságukat?",
    "ue.katalog.25": "ISO/IEC 27001 A.8.13",
    "ue.katalog.26": "Rendelkezik a szervezet válságkezelési eljárásokkal meghatározott szerepekkel és kommunikációs csatornákkal?",
    "ue.katalog.27": "ISO/IEC 27001 A.5.29",
    "ue.katalog.28": "Rendszeresen tesztelik a folytonossági és helyreállítási terveket, és dokumentálják az eredményeket?",
    "ue.katalog.29": "ISO/IEC 27001 A.5.30",
    "ue.katalog.3": "Rendelkezik a szervezet az irányító testület által jóváhagyott, dokumentált kockázatelemzési és információsrendszer-biztonsági szabályzattal?",
    "ue.katalog.30": "Ellátási lánc biztonsága",
    "ue.katalog.31": "Az ellátási lánc biztonsága, beleértve a szervezet és közvetlen beszállítói vagy szolgáltatói közötti kapcsolatok biztonsági vonatkozásait. A szervezet figyelembe veszi az egyes beszállítókra jellemző sérülékenységeket, valamint termékeik és kiberbiztonsági gyakorlataik általános minőségét (21. cikk (3) bekezdés).",
    "ue.katalog.32": "Vezet a szervezet jegyzéket a közvetlen beszállítókról és szolgáltatókról a hálózatok és rendszerek biztonsága szempontjából vett jelentőségük értékelésével?",
    "ue.katalog.33": "ISO/IEC 27001 A.5.19",
    "ue.katalog.34": "A beszállítókkal szembeni intézkedések kiválasztásakor figyelembe veszik az egyes beszállítókra jellemző sérülékenységeket, valamint kiberbiztonsági és biztonságos fejlesztési gyakorlataik minőségét?",
    "ue.katalog.35": "ISO/IEC 27001 A.5.19, A.5.21",
    "ue.katalog.36": "Tartalmaznak a beszállítói szerződések biztonsági követelményeket és az incidensekről és sérülékenységekről szóló tájékoztatási kötelezettséget?",
    "ue.katalog.37": "ISO/IEC 27001 A.5.20",
    "ue.katalog.38": "Figyelembe veszi a szervezet a kritikus ellátási láncok 22. cikk szerinti összehangolt biztonsági kockázatértékeléseinek eredményeit?",
    "ue.katalog.39": "ISO/IEC 27001 A.5.21",
    "ue.katalog.4": "ISO/IEC 27001 5.2., 6.1.2. pont",
    "ue.katalog.40": "Biztonság a rendszerek beszerzése, fejlesztése és karbantartása során",
    "ue.katalog.41": "A hálózati és információs rendszerek beszerzésének, fejlesztésének és karbantartásának biztonsága, beleértve a sérülékenységek kezelését és közzétételét.",
    "ue.katalog.42": "Meghatározzák a biztonsági követelményeket a rendszer beszerzése vagy fejlesztésének megkezdése előtt, és ellenőrzik azokat az üzembe helyezés előtt?",
    "ue.katalog.43": "ISO/IEC 27001 A.8.25–A.8.29",
    "ue.katalog.44": "Létezik sérülékenységkezelési folyamat: azonosítás, értékelés, elhárítás meghatározott időn belül?",
    "ue.katalog.45": "ISO/IEC 27001 A.8.8",
    "ue.katalog.46": "Rendelkezik a szervezet sérülékenység-közzétételi eljárással, beleértve a harmadik felek bejelentéseinek fogadására szolgáló csatornát?",
    "ue.katalog.47": "A rendszerek változtatásai ellenőrzött változáskezelési folyamaton mennek át a biztonsági hatás értékelésével?",
    "ue.katalog.48": "ISO/IEC 27001 A.8.32",
    "ue.katalog.49": "Az intézkedések hatékonyságának értékelése",
    "ue.katalog.5": "Kiterjed a kockázatelemzés a hálózati és információs rendszereket és fizikai környezetüket érintő valamennyi veszélyre, nem csak a kiberfenyegetésekre?",
    "ue.katalog.50": "Szabályzatok és eljárások a kiberbiztonsági kockázatkezelési intézkedések hatékonyságának értékelésére.",
    "ue.katalog.51": "Létezik dokumentált hatékonyságértékelési szabályzat, amely meghatározza a hatókört, a gyakoriságot és a módszereket?",
    "ue.katalog.52": "ISO/IEC 27001 9.1. pont",
    "ue.katalog.53": "Rendszeresen végeznek hatékonyságértékelést, és eredményeit az irányító testület elé terjesztik?",
    "ue.katalog.54": "ISO/IEC 27001 9.2–9.3. pont",
    "ue.katalog.55": "A feltárt gyengeségek dokumentált, felelőssel és határidővel ellátott helyesbítő intézkedésekhez vezetnek?",
    "ue.katalog.56": "ISO/IEC 27001 10.1. pont",
    "ue.katalog.57": "Kiberhigiénia és képzés",
    "ue.katalog.58": "Alapvető kiberhigiéniai gyakorlatok és kiberbiztonsági képzés. Az irányító testület tagjai rendszeresen képzésen vesznek részt (20. cikk (2) bekezdés).",
    "ue.katalog.59": "Alkalmazza a szervezet az alapvető kiberhigiéniai gyakorlatokat: frissítések, jelszókezelés, jogosultságok korlátozása, kártékony szoftverek elleni védelem?",
    "ue.katalog.6": "ISO/IEC 27001 6.1.2. pont",
    "ue.katalog.60": "ISO/IEC 27001 A.8.7, A.8.8",
    "ue.katalog.61": "Részesülnek a munkavállalók a szerepükhöz igazított kiberbiztonsági képzésben, és dokumentálják a részvételt?",
    "ue.katalog.62": "ISO/IEC 27001 A.6.3",
    "ue.katalog.63": "Részt vesznek az irányító testület tagjai rendszeresen olyan képzésen, amely lehetővé teszi a kockázatok felismerését és a kockázatkezelési gyakorlatok értékelését?",
    "ue.katalog.64": "ISO/IEC 27001 7.2. pont",
    "ue.katalog.65": "Kriptográfia és titkosítás",
    "ue.katalog.66": "Szabályzatok és eljárások a kriptográfia és adott esetben a titkosítás alkalmazására.",
    "ue.katalog.67": "Létezik kriptográfiai szabályzat, amely meghatározza, mely adatokat és csatornákat titkosítanak, és milyen algoritmusokkal?",
    "ue.katalog.68": "ISO/IEC 27001 A.8.24",
    "ue.katalog.69": "A kriptográfiai kulcsokat teljes életciklusuk során kezelik: előállítás, elosztás, tárolás, rotáció, kivonás?",
    "ue.katalog.7": "Figyelembe veszi az intézkedések kiválasztása a technika állását, a vonatkozó európai és nemzetközi szabványokat és a bevezetés költségeit?",
    "ue.katalog.70": "Emberi erőforrások, hozzáférés-szabályozás és eszközkezelés",
    "ue.katalog.71": "Az emberi erőforrások biztonsága, hozzáférés-szabályozási szabályzatok és eszközkezelés.",
    "ue.katalog.72": "Vezet a szervezet naprakész eszközleltárt hozzárendelt tulajdonosokkal és besorolással?",
    "ue.katalog.73": "ISO/IEC 27001 A.5.9, A.5.12",
    "ue.katalog.74": "Létezik a legkisebb jogosultság elvén alapuló hozzáférés-szabályozási szabályzat a jogosultságok rendszeres felülvizsgálatával?",
    "ue.katalog.75": "ISO/IEC 27001 A.5.15, A.5.18",
    "ue.katalog.76": "Alkalmaznak biztonsági eljárásokat a munkavállaló felvételekor, munkakörváltásakor és távozásakor, beleértve a jogosultságok visszavonását és az eszközök visszaszolgáltatását?",
    "ue.katalog.77": "ISO/IEC 27001 A.6.1–A.6.5",
    "ue.katalog.78": "A kiemelt jogosultságú hozzáférés korlátozott, naplózott és felülvizsgált?",
    "ue.katalog.79": "ISO/IEC 27001 A.8.2",
    "ue.katalog.8": "ISO/IEC 27001 6.1.3. pont",
    "ue.katalog.80": "Többtényezős hitelesítés és biztonságos kommunikáció",
    "ue.katalog.81": "Adott esetben — többtényezős vagy folyamatos hitelesítés, biztonságos hang-, video- és szöveges kommunikáció, valamint biztonságos vészhelyzeti kommunikációs rendszerek a szervezeten belül.",
    "ue.katalog.82": "Alkalmaznak többtényezős vagy folyamatos hitelesítést ott, ahol a kockázatelemzés indokolja, különösen a távoli hozzáférésnél és a kiemelt jogosultságú fiókoknál?",
    "ue.katalog.83": "ISO/IEC 27001 A.8.5",
    "ue.katalog.84": "Biztonságosak a munkavégzésre használt hang-, video- és szöveges kapcsolatok?",
    "ue.katalog.85": "ISO/IEC 27001 A.8.20",
    "ue.katalog.86": "Rendelkezik a szervezet a fő infrastruktúrától független, biztonságos belső vészhelyzeti kommunikációs rendszerrel?",
    "ue.katalog.9": "Dokumentált, hogy a biztonsági szint megfelel a fennálló kockázatnak, olyan indoklással, amely figyelembe veszi a szervezet méretét és az incidensek társadalmi és gazdasági hatását?",
    "ue.kierownictwo.1": "Az alapvető vagy fontos szervezet irányító testülete — tőketársaságban az ügyvezetés vagy az igazgatóság. Az irányelv nem határozza meg a fogalmat; az adott országban a terjedelme a nemzeti jogból következik.",
    "ue.kierownictwo.10": "A szervezet státuszának megállapítása és a nyilvántartásba vétel biztosítása",
    "ue.kierownictwo.11": "Annak megállapítása, hogy a szervezet alapvető vagy fontos-e, és a nyilvántartási adatok benyújtása az illetékes hatósághoz. Az eljárást és a határidőt a nemzeti jog határozza meg.",
    "ue.kierownictwo.12": "Kockázatelemzés és biztonsági szabályzat bevezetése",
    "ue.kierownictwo.13": "Minden veszélyt figyelembe vevő megközelítésen alapuló intézkedések, amelyek arányosak a kitettséggel, a szervezet méretével és az incidensek súlyosságával.",
    "ue.kierownictwo.14": "Az incidenskezelés és -bejelentés beindítása",
    "ue.kierownictwo.15": "Incidenskezelési eljárás és a 24 órás, 72 órás és egy hónapos határidők betartásának képessége.",
    "ue.kierownictwo.16": "24 óra / 72 óra / egy hónap az észleléstől",
    "ue.kierownictwo.17": "Az üzletmenet-folytonosság biztosítása",
    "ue.kierownictwo.18": "Folytonossági terv, biztonsági mentések, katasztrófa utáni helyreállítás, válságkezelés.",
    "ue.kierownictwo.19": "Az ellátási lánc rendbetétele",
    "ue.kierownictwo.2": "Az irányító testület felelőssége nem érinti a közintézmények és a tisztviselők felelősségére vonatkozó nemzeti szabályokat (20. cikk (1) bekezdés második albekezdés).",
    "ue.kierownictwo.20": "Beszállítói jegyzék, sérülékenységeik és gyakorlataik értékelése, biztonsági követelmények a szerződésekben.",
    "ue.kierownictwo.21": "Hozzáférés-szabályozás és eszközkezelés bevezetése",
    "ue.kierownictwo.22": "Eszközleltár, a legkisebb jogosultság elve, jogosultság-felülvizsgálatok, többtényezős hitelesítés ott, ahol a kockázat indokolja.",
    "ue.kierownictwo.23": "Az intézkedések hatékonyságának mérése",
    "ue.kierownictwo.24": "Hatékonyságértékelési szabályzat és eljárások, rendszeres felülvizsgálatok, helyesbítő intézkedések.",
    "ue.kierownictwo.25": "Jóváhagyás",
    "ue.kierownictwo.26": "a kiberbiztonsági kockázatkezelési intézkedések (20. cikk (1) bekezdés)",
    "ue.kierownictwo.27": "a kockázatelemzési és rendszerbiztonsági szabályzat",
    "ue.kierownictwo.28": "a költségvetés és a bevezetési szerepek",
    "ue.kierownictwo.29": "Felügyelet",
    "ue.kierownictwo.3": "Azt, hogy a kötelezettségek másra bízása kizárja-e a felelősséget, a nemzeti jog dönti el. Lengyelországban nem zárja ki (a nemzeti kiberbiztonsági rendszerről szóló törvény 8c. cikk (3) bekezdése).",
    "ue.kierownictwo.30": "a jóváhagyott intézkedések végrehajtása (20. cikk (1) bekezdés)",
    "ue.kierownictwo.31": "a hatékonyságértékelés eredményei (21. cikk (2) bekezdés f) pont)",
    "ue.kierownictwo.32": "az incidensbejelentési határidők betartása (23. cikk)",
    "ue.kierownictwo.33": "Dokumentálás",
    "ue.kierownictwo.34": "jóváhagyó döntések és felülvizsgálatok",
    "ue.kierownictwo.35": "részvétel a képzéseken (20. cikk (2) bekezdés)",
    "ue.kierownictwo.36": "Az irányító testület tagja",
    "ue.kierownictwo.37": "intézkedések jóváhagyása, felügyelet, döntések, költségvetés",
    "ue.kierownictwo.38": "Projektvezető",
    "ue.kierownictwo.39": "a bevezetés koordinálása, ütemterv, állapot és bizonyítékok",
    "ue.kierownictwo.4": "A kiberbiztonsági kockázatkezelési intézkedések jóváhagyása",
    "ue.kierownictwo.40": "IT / kiberbiztonság",
    "ue.kierownictwo.41": "kockázatelemzés, műszaki intézkedések, incidenskezelés",
    "ue.kierownictwo.42": "Jogi osztály / megfelelőség",
    "ue.kierownictwo.5": "Az irányító testület hagyja jóvá a 21. cikknek való megfelelés érdekében hozott intézkedéseket. Ez a testület döntése, nem az informatikai osztályé — enélkül az intézkedéseknek nincs alapja.",
    "ue.kierownictwo.6": "Az intézkedések végrehajtásának felügyelete",
    "ue.kierownictwo.7": "A végrehajtás felügyelete az irányító testület kötelezettsége. A végrehajtás átruházható, a felügyelet nem.",
    "ue.kierownictwo.8": "Rendszeres képzésen való részvétel",
    "ue.kierownictwo.9": "Az irányító testület tagjai rendszeresen képzésen vesznek részt, hogy elegendő ismeretet szerezzenek a kockázatok felismeréséhez, valamint a kockázatkezelési gyakorlatok és azok szervezeti szolgáltatásokra gyakorolt hatásának értékeléséhez.",
    "ue.kierownictwo.daneRejestracyjne": "nyilvántartási adatok és frissítésük (3. cikk (4)–(5) bekezdés)",
    "ue.meta.1": "A százalékos változat érvényesül: az árbevétel {p0} %-a több, mint {p1} millió EUR.",
    "ue.meta.10": "Az irányelv nem ró közvetlenül kötelezettséget a vállalkozásokra — ezt a nemzeti törvény teszi, amelyet a tagállamnak 2024. október 17-ig kellett elfogadnia. Ez a modul az irányelv szövege szerint mutatja a követelményeket, mert a kiválasztott ország nemzeti jogi modulja még nem készült el, vagy az ország nem ültette át az irányelvet.",
    "ue.meta.11": "Az irányelvből eredő kötelezettségek",
    "ue.meta.12": "Szervezetek jegyzéke — 2025. április 17-ig",
    "ue.meta.13": "A tagállamoknak 2025. április 17-ig kellett létrehozniuk az alapvető és fontos szervezetek jegyzékét, és megkövetelniük a szervezetektől a nyilvántartási adatok benyújtását.",
    "ue.meta.14": "(EU) 2024/2690 rendelet",
    "ue.meta.15": "Közvetlenül alkalmazandó 2024. november 7. óta",
    "ue.meta.16": "A végrehajtási rendelet közvetlenül alkalmazandó minden tagállamban, az irányelv átültetésének állapotától függetlenül. Az 1. cikkében felsorolt szervezetekre vonatkozik: DNS, TLD, felhő, adatközpontok, tartalomszolgáltató hálózatok, irányított szolgáltatások és bizalmi szolgáltatások.",
    "ue.meta.17": "az (EU) 2024/2690 rendelet 16. cikke",
    "ue.meta.18": "Legalább 10 000 000 EUR vagy a vállalkozás előző üzleti évi teljes éves világszintű árbevételének legalább 2 %-a — a magasabb összeg alkalmazandó. Ez minimális felső határ: a nemzeti jog megemelheti.",
    "ue.meta.19": "Legalább 7 000 000 EUR vagy a teljes éves világszintű árbevétel 1,4 %-a — a magasabb összeg alkalmazandó. Minimális felső határ.",
    "ue.meta.2": "A rögzített összeg érvényesül: {p0} millió EUR több, mint az árbevétel {p1} %-a.",
    "ue.meta.20": "Az irányelv nem ír elő külön bírságot minősített jogsértésért — ez egyes országok nemzeti jogának konstrukciója.",
    "ue.meta.21": "A tagállamok kényszerítő bírságot írhatnak elő a jogsértés megszüntetésének kikényszerítésére. A mértékét a nemzeti jog határozza meg.",
    "ue.meta.22": "Az irányító testület jóváhagyja a kockázatkezelési intézkedéseket, felügyeli végrehajtásukat, és felelősségre vonható a 21. cikk megsértéséért. E felelősség szabályait és mértékét a nemzeti jog határozza meg.",
    "ue.meta.23": "Az irányító testület jóváhagyja a kiberbiztonsági kockázatkezelési intézkedéseket (20. cikk (1) bekezdés).",
    "ue.meta.24": "Az irányító testület felügyeli ezen intézkedések végrehajtását (20. cikk (1) bekezdés).",
    "ue.meta.25": "Az irányító testület tagjai rendszeresen képzésen vesznek részt (20. cikk (2) bekezdés).",
    "ue.meta.26": "Alapvető szervezettel szemben a hatóság kérheti a vezetői feladatok ellátásának ideiglenes megtiltását (32. cikk (5) bekezdés b) pont).",
    "ue.meta.27": "A minimális felső határt az irányelv határozza meg",
    "ue.meta.28": "Két értéket hasonlítanak össze: egy rögzített euróösszeget és a vállalkozás előző üzleti évi teljes éves világszintű árbevételének egy százalékát. A magasabb a felső határ, amelyet a tagállamnak legalább elő kell írnia. A nemzeti jog megemelheti.",
    "ue.meta.29": "A felső határon belüli összeget a nemzeti hatóság állapítja meg",
    "ue.meta.3": "Az irányelv szerinti felső határ {p0}-szorosan meghaladja a szervezet éves árbevételét. A 34. cikk (1) bekezdése megköveteli, hogy a bírság arányos legyen az egyedi eset körülményeivel — ez felső határ, nem várható bírság.",
    "ue.meta.30": "A bírságnak az egyedi eset körülményei szerint hatékonynak, arányosnak és visszatartó erejűnek kell lennie. A hatóság legalább a 32. cikk (7) bekezdésének szempontjait figyelembe veszi: a jogsértés súlya és időtartama, korábbi jogsértések, károk, szándékosság, helyreállító intézkedések és együttműködés.",
    "ue.meta.31": "A felső határ többszörösen meghaladhatja az éves árbevételt — ez felső határ, nem várható összeg. A nemzeti minimumokat, a kényszerítő bírságokat és a kiszabás módját a tagállam törvénye határozza meg.",
    "ue.meta.32": "A közigazgatási bírság kiszabásáról és mértékéről való döntéskor minden egyedi esetben kellően figyelembe kell venni legalább a 32. cikk (7) bekezdésében felsorolt elemeket.",
    "ue.meta.33": "a jogsértés súlya és a megsértett rendelkezések jelentősége — minden esetben súlyosnak minősül: az ismételt jogsértés, a jelentős incidensek bejelentésének vagy elhárításának elmulasztása, a hiányosságok kötelező utasítás ellenére való meg nem szüntetése, az auditok vagy a monitorozás akadályozása, hamis vagy súlyosan pontatlan információk szolgáltatása",
    "ue.meta.34": "a szervezet releváns korábbi jogsértései",
    "ue.meta.35": "az okozott vagyoni és nem vagyoni károk, beleértve a pénzügyi veszteséget, a más szolgáltatásokra gyakorolt hatást és az érintett felhasználók számát",
    "ue.meta.36": "a cselekmény szándékos vagy gondatlan jellege",
    "ue.meta.37": "a kár megelőzése vagy enyhítése érdekében tett intézkedések",
    "ue.meta.38": "jóváhagyott magatartási kódexek vagy tanúsítási mechanizmusok alkalmazása",
    "ue.meta.39": "az illetékes hatóságokkal való együttműködés mértéke",
    "ue.meta.4": "Az Európai Parlament és a Tanács (EU) 2022/2555 irányelve (NIS 2)",
    "ue.meta.40": "Az irányelv nem rendelkezik kifejezetten a bírság mellőzéséről — hogy ez lehetséges-e és mikor, a nemzeti jog dönti el.",
    "ue.meta.41": "Ettől az időponttól a tagállamoknak az irányelvet átültető nemzeti rendelkezéseket kell alkalmazniuk. A konkrét dátum, amelytől a hatóság bírságot szabhat ki, a nemzeti jogból következik.",
    "ue.meta.42": "A NIS 2 irányelv hatálybalépése",
    "ue.meta.43": "A Hivatalos Lapban való kihirdetést követő huszadik napon.",
    "ue.meta.44": "Az irányelv átültetési határideje",
    "ue.meta.45": "Eddig az időpontig kellett a tagállamoknak elfogadniuk és kihirdetniük a nemzeti rendelkezéseket.",
    "ue.meta.46": "A nemzeti rendelkezések alkalmazása és a NIS 1 hatályon kívül helyezése",
    "ue.meta.47": "Ettől az időponttól az államok az átültető rendelkezéseket alkalmazzák; az (EU) 2016/1148 irányelv hatályát veszti.",
    "ue.meta.48": "Az (EU) 2024/2690 rendelet alkalmazása",
    "ue.meta.49": "A végrehajtási rendelet a kihirdetést követő huszadik naptól közvetlenül alkalmazandó.",
    "ue.meta.5": "HL EU L 333., 2022.12.27.",
    "ue.meta.50": "Az alapvető és fontos szervezetek jegyzéke",
    "ue.meta.51": "Eddig az időpontig a tagállamok létrehozzák a jegyzéket; a szervezetek benyújtják a hatóságoknak a nyilvántartási adatokat.",
    "ue.meta.52": "Az irányelv első bizottsági felülvizsgálata",
    "ue.meta.53": "A Bizottság felülvizsgálja az irányelv működését és jelentést nyújt be.",
    "ue.meta.54": "Korai figyelmeztetés jelentős incidensről",
    "ue.meta.55": "24 óra a tudomásszerzéstől",
    "ue.meta.56": "Jelentős incidens bejelentése",
    "ue.meta.57": "72 óra a tudomásszerzéstől",
    "ue.meta.58": "Végleges jelentés",
    "ue.meta.59": "egy hónap az incidens bejelentésétől",
    "ue.meta.6": "A Bizottság (EU) 2024/2690 végrehajtási rendelete",
    "ue.meta.60": "Incidens bejelentése bizalmi szolgáltató által",
    "ue.meta.61": "az (EU) 2022/2555 irányelv 21. cikk (5) bekezdése; az (EU) 2024/2690 rendelet 1. és 2. cikke",
    "ue.meta.62": "Árbevételi adatok hiányában a felső határ az irányelv rögzített összege.",
    "ue.meta.63": "A 34. cikk (4) és (5) bekezdése szerinti felső határok minimumok („legalább”) — a nemzeti jog magasabbat írhat elő. Az összegek euróban, nemzeti valutára való átváltás nélkül.",
    "ue.meta.64": "A tagállam illetékes hatósága",
    "ue.meta.65": "Az irányító testület felelősségre vonható a 21. cikk megsértéséért. A mértéket és az eljárást a nemzeti jog határozza meg — ezt a modul nem ismeri.",
    "ue.meta.66": "A vezetés személyes felelősségének mértéke a nemzeti törvényből következik. Lengyelországban ez a javadalmazás 300 %-áig terjed (a nemzeti kiberbiztonsági rendszerről szóló törvény 73a. cikk (4) bekezdése); más országok másként rendelkeznek.",
    "ue.meta.7": "HL EU L, 2024/2690",
    "ue.meta.8": "(EU) 2022/2555 irányelv",
    "ue.meta.9": "Az átültetési határidő 2024. október 17-én lejárt",
    "ue.moduly.1": "kb. {p0} perc",
    "ue.moduly.10": "Tíz terület a 21. cikk (2) bekezdés a)–j) pontjából: a kockázati szabályzattól a többtényezős hitelesítésig. A jogsértés a 34. cikk szerint bírsággal sújtható. Értékelés érettségi skálán.",
    "ue.moduly.11": "2024/2690 rendelet — irányítás és folyamatok",
    "ue.moduly.12": "A melléklet 1–5. és 7–8. szakasza: szabályzatok, kockázatkezelés, incidenskezelés, üzletmenet-folytonosság, ellátási lánc, hatékonyságértékelés, kiberhigiénia. Közvetlenül alkalmazandó 2024. november 7. óta.",
    "ue.moduly.13": "2024/2690 rendelet — műszaki követelmények",
    "ue.moduly.14": "A melléklet 6. és 9–13. szakasza: rendszerek beszerzése és fejlesztése, kriptográfia, az emberi erőforrások biztonsága, hozzáférés-szabályozás, eszközkezelés, fizikai és környezeti biztonság.",
    "ue.moduly.2": "kb. {p0} óra {p1} perc",
    "ue.moduly.3": "kb. {p0} óra",
    "ue.moduly.4": "kevesebb mint egy perc",
    "ue.moduly.5": "Gyors kockázatértékelés",
    "ue.moduly.6": "Átfogó kérdések az irányelv minden területéről. Mindegyik egy egész témacsoportról dönt. Lehetővé teszi a lemaradás mértékének becslését a teljes kérdőív kitöltése nélkül.",
    "ue.moduly.7": "Az irányelvből eredő kötelezettségek",
    "ue.moduly.8": "Nyilvántartási adatok, incidensbejelentés 24 és 72 órán belül, az irányító testület kötelezettségei, felkészültség a felügyeletre. Dokumentumokból ellenőrizhető, műszaki elemzés nélkül.",
    "ue.moduly.9": "Kockázatkezelési intézkedések — 21. cikk (2) bekezdés",
    "ue.obowiazki.1": "Nyilvántartási adatok a szervezetek jegyzékéhez",
    "ue.obowiazki.10": "Jelentős incidensek bejelentése",
    "ue.obowiazki.11": "A szervezet a jelentős incidenseket három lépésben jelenti a CSIRT-nek vagy az illetékes hatóságnak: korai figyelmeztetés, bejelentés, végleges jelentés. A határidők az incidensről való tudomásszerzéstől számítanak.",
    "ue.obowiazki.12": "Képes a szervezet a jelentős incidensről való tudomásszerzéstől számított 24 órán belül korai figyelmeztetést küldeni, jelezve, hogy az incidenst feltehetően jogellenes cselekmény okozta-e, és lehet-e határokon átnyúló hatása?",
    "ue.obowiazki.13": "24 óra a tudomásszerzéstől",
    "ue.obowiazki.14": "Képes a szervezet 72 órán belül incidensbejelentést küldeni a súlyosság és a hatás előzetes értékelésével és a kompromittálódás mutatóival?",
    "ue.obowiazki.15": "72 óra a tudomásszerzéstől",
    "ue.obowiazki.16": "Benyújtja a szervezet a végleges jelentést legkésőbb egy hónappal a bejelentés után az incidens leírásával, a fenyegetés típusával, az enyhítő intézkedésekkel és a határokon átnyúló hatással?",
    "ue.obowiazki.17": "egy hónap a bejelentéstől",
    "ue.obowiazki.18": "Tájékoztatja a szervezet szolgáltatásainak igénybe vevőit azokról a jelentős incidensekről, amelyek hátrányosan befolyásolhatják e szolgáltatások nyújtását?",
    "ue.obowiazki.19": "Tájékoztatja a szervezet szolgáltatásainak igénybe vevőit a jelentős kiberfenyegetésről és az általuk alkalmazható ellenintézkedésekről?",
    "ue.obowiazki.2": "A tagállamok létrehozzák az alapvető és fontos szervezetek jegyzékét, és megkövetelik a szervezetektől a nyilvántartási adatok benyújtását. Az eljárást, a határidőt és a portált a nemzeti jog határozza meg.",
    "ue.obowiazki.20": "Ha a szervezet bizalmi szolgáltató — a tudomásszerzéstől számított 24 órán belül bejelenti a jelentős incidenseket?",
    "ue.obowiazki.21": "a bizalmi szolgáltatókra vonatkozik",
    "ue.obowiazki.22": "Irányító testület",
    "ue.obowiazki.23": "Az irányító testület jóváhagyja a kockázatkezelési intézkedéseket, felügyeli végrehajtásukat, és felelősségre vonható. A testület tagjai rendszeresen képzésen vesznek részt.",
    "ue.obowiazki.24": "Formálisan jóváhagyta az irányító testület a 21. cikknek való megfelelés érdekében hozott kiberbiztonsági kockázatkezelési intézkedéseket?",
    "ue.obowiazki.25": "Dokumentáltan felügyeli az irányító testület ezen intézkedések végrehajtását — például rendszeres jelentésekkel és felülvizsgálatokkal?",
    "ue.obowiazki.26": "Részt vesznek az irányító testület tagjai rendszeresen olyan képzésen, amely lehetővé teszi a kockázatok felismerését és a kockázatkezelési gyakorlatok értékelését, és dokumentált a részvétel?",
    "ue.obowiazki.27": "Felkészültség a felügyeleti intézkedésekre",
    "ue.obowiazki.28": "Az alapvető szervezet előzetes és utólagos felügyelet, a fontos szervezet kizárólag utólagos felügyelet alá tartozik. A hatóság információt, a szabályzatok végrehajtásának bizonyítékait és auditeredményeket kérhet.",
    "ue.obowiazki.29": "Képes a szervezet a hatóság kérésére bizonyítékot szolgáltatni a kiberbiztonsági szabályzatok végrehajtásáról, beleértve a biztonsági auditok eredményeit?",
    "ue.obowiazki.3": "Megállapította a szervezet az I. vagy II. melléklet szerinti ágazat és a vállalkozás mérete alapján, hogy alapvető vagy fontos szervezet-e?",
    "ue.obowiazki.30": "Képes a szervezet a hatóság kérésére rendelkezésre bocsátani a felügyeleti feladatok ellátásához szükséges adatokat, dokumentumokat és információkat?",
    "ue.obowiazki.31": "Felkészült az alapvető szervezet a hatóság vagy független szerv által saját költségén végzett biztonsági auditra?",
    "ue.obowiazki.4": "Benyújtotta a szervezet az illetékes hatósághoz a nyilvántartási adatokat: név, cím és elérhetőségek, ágazat és alágazat, azon tagállamok jegyzéke, ahol szolgáltatást nyújt?",
    "ue.obowiazki.5": "Az elérhetőségek magukban foglalják az e-mail-címeket, az IP-tartományokat és a telefonszámokat. A nemzeti határidőt és a nyilvántartási portált a tagállam joga határozza meg.",
    "ue.obowiazki.6": "Létezik folyamat a nyilvántartási adatok változás utáni, indokolatlan késedelem nélküli frissítésére?",
    "ue.obowiazki.7": "Az irányelv indokolatlan késedelem nélküli frissítést ír elő; a konkrét határidő — például 14 nap Lengyelországban — a nemzeti jogból következik.",
    "ue.obowiazki.8": "Ha a szervezet DNS-szolgáltató, TLD-nyilvántartó, felhőszolgáltató, adatközpont, CDN, irányított szolgáltató, online piactér, keresőmotor vagy közösségi hálózat — benyújtotta a 27. cikk szerinti további adatokat, beleértve uniós fő telephelyének címét?",
    "ue.obowiazki.9": "a 26. cikk (1) bekezdése szerinti szervezetekre vonatkozik",
    "ue.role.1": "A tagállam illetékes hatósága",
    "ue.role.10": "Adatközponti szolgáltatások: kolokáció, infrastruktúra-hoszting és kapcsolódó szolgáltatások.",
    "ue.role.11": "Adatközpontok",
    "ue.role.12": "Alapvető szervezet a középvállalkozás küszöbe felett (3. cikk (1) bekezdés a) pont), fontos szervezet közepes méret esetén (3. cikk (2) bekezdés). Közepes méret alatt — hatályon kívül, kivéve, ha a tagállam a 2. cikk (2) bekezdés b)–e) pontja alapján kijelöli a szervezetet. A 2024/2690 rendelet hatálya alá tartozik.",
    "ue.role.13": "Internetcsere-pont szolgáltató",
    "ue.role.14": "Független hálózatok közötti forgalomcserét lehetővé tevő infrastruktúra.",
    "ue.role.15": "Internetcsere-pontok",
    "ue.role.16": "Méret szerinti besorolás (3. cikk (1) bekezdés a) pont és (2) bekezdés). A 2024/2690 rendelet nem terjed ki az internetcsere-pontokra — a rendelet 1. cikke zárt címzetti listát tartalmaz.",
    "ue.role.17": "DNS-szolgáltató",
    "ue.role.18": "Tartománynév-feloldási szolgáltatások, a gyökér-névkiszolgálók üzemeltetői kivételével.",
    "ue.role.19": "Tartománynév-rendszer",
    "ue.role.2": "illetékes hatóság",
    "ue.role.20": "Alapvető szervezet mérettől függetlenül (3. cikk (1) bekezdés b) pont). A 2024/2690 rendelet hatálya alá tartozik.",
    "ue.role.21": "Legfelső szintű tartománynév-nyilvántartó",
    "ue.role.22": "Legfelső szintű tartomány nyilvántartásának vezetése.",
    "ue.role.23": "Alapvető szervezet mérettől függetlenül (3. cikk (1) bekezdés b) pont). Emellett a 28. cikk szerinti nyilvántartási adatokra vonatkozó kötelezettségek. A 2024/2690 rendelet hatálya alá tartozik.",
    "ue.role.24": "Felhőszolgáltató",
    "ue.role.25": "Felhőalapú számítástechnikai szolgáltatások: infrastruktúra, platform, szoftver mint szolgáltatás.",
    "ue.role.26": "Felhőszolgáltatások",
    "ue.role.27": "Méret szerinti besorolás (3. cikk (1) bekezdés a) pont és (2) bekezdés). A 2024/2690 rendelet hatálya alá tartozik.",
    "ue.role.28": "Tartalomszolgáltató hálózat szolgáltatója",
    "ue.role.29": "Elosztott kiszolgálók hálózata, amely tartalmat és szolgáltatásokat juttat el a végfelhasználókhoz.",
    "ue.role.3": "a nemzeti jog jelöli ki; a nemzeti modul bevezetéséig az eszköz nem nevez meg konkrét intézményt",
    "ue.role.30": "Tartalomszolgáltató hálózatok",
    "ue.role.31": "Bizalmi szolgáltató",
    "ue.role.32": "Bizalmi szolgáltatások a 910/2014/EU rendelet értelmében: aláírások, bélyegzők, időbélyegzők, tanúsítványok.",
    "ue.role.33": "Bizalmi szolgáltatások",
    "ue.role.34": "Az irányelv hatálya alá tartozik mérettől függetlenül (2. cikk (2) bekezdés a) pont ii. alpont). A minősített szolgáltató mérettől függetlenül alapvető szervezet (3. cikk (1) bekezdés b) pont); a nem minősített a középvállalkozás küszöbe felett alapvető, egyébként fontos. A 2024/2690 rendelet hatálya alá tartozik.",
    "ue.role.35": "Irányított szolgáltató",
    "ue.role.36": "Az ügyfél IKT-infrastruktúrájának kezelése: telepítés, karbantartás, támogatás, rendszeradminisztráció.",
    "ue.role.37": "IKT-szolgáltatások kezelése (B2B)",
    "ue.role.38": "Irányított szolgáltatások",
    "ue.role.39": "Irányított biztonsági szolgáltató",
    "ue.role.4": "Nyilvános elektronikus hírközlő hálózatok vagy nyilvánosan elérhető elektronikus hírközlési szolgáltatások szolgáltatója",
    "ue.role.40": "Irányított kiberbiztonsági szolgáltatások: monitorozás, incidensreagálás, tesztelés, tanácsadás.",
    "ue.role.41": "Irányított biztonsági szolgáltatások",
    "ue.role.42": "Az irányelv méret szerint sorol be (3. cikk (1) bekezdés a) pont és (2) bekezdés). A tagállamok szigoríthatják a küszöböt — Lengyelország az MSSP-t már kisvállalkozási mérettől alapvető szervezetnek tekinti; ez a modul kizárólag az irányelv szabályát alkalmazza. A 2024/2690 rendelet hatálya alá tartozik.",
    "ue.role.5": "Nyilvános elektronikus hírközlő hálózatok szolgáltatása vagy nyilvánosan elérhető elektronikus hírközlési szolgáltatások nyújtása, beleértve az internet-hozzáférést.",
    "ue.role.6": "Digitális infrastruktúra",
    "ue.role.7": "Elektronikus hírközlés",
    "ue.role.8": "Az irányelv hatálya alá tartozik mérettől függetlenül (2. cikk (2) bekezdés a) pont i. alpont). A közép- vagy nagyobb vállalkozás alapvető szervezet (3. cikk (1) bekezdés c) pont), a mikro- és kisvállalkozás fontos szervezet (3. cikk (2) bekezdés). A nemzeti hírközlési törvény további kötelezettségeket írhat elő — ezt a modul nem tartalmazza.",
    "ue.role.9": "Adatközponti szolgáltató",
    "ue.role.podstawaArt3b": "az (EU) 2022/2555 irányelv 3. cikk (1) bekezdés b) pontja",
    "ue.zaslepki.1": "Az Európai Parlament és a Tanács (EU) 2022/2555 irányelve (NIS 2)",
    "ue.zaslepki.10": "Hogy egyes szervezeteket hivatalból vesznek-e nyilvántartásba, a nemzeti jog dönti el.",
    "ue.zaslepki.11": "Állapítsa meg, hogy az irányelv hatálya alá tartozik-e",
    "ue.zaslepki.12": "Az I. vagy II. melléklet szerinti ágazat és a vállalkozás mérete. Ezt a részt az eszközben a szervezet profilja végzi el.",
    "ue.zaslepki.13": "Állapítsa meg országa illetékes hatóságát",
    "ue.zaslepki.14": "Minden állam kijelöl egy illetékes hatóságot (8. cikk (1) bekezdés). A naprakész listát az ENISA és a Bizottság vezeti.",
    "ue.zaslepki.15": "Nyújtsa be a nyilvántartási adatokat",
    "ue.zaslepki.16": "Név, cím és elérhetőségek, ágazat és alágazat, a szolgáltatásnyújtás államai (3. cikk (4) bekezdés). Eljárás a nemzeti jog szerint.",
    "ue.zaslepki.17": "Frissítse az adatokat indokolatlan késedelem nélkül",
    "ue.zaslepki.18": "A nyilvántartási adatok minden változása frissítést igényel (3. cikk (5) bekezdés).",
    "ue.zaslepki.19": "cím és aktuális elérhetőségek: e-mail-címek, IP-tartományok, telefonszámok",
    "ue.zaslepki.2": "HL EU L 333., 2022.12.27., 80. o.",
    "ue.zaslepki.20": "az I. vagy II. melléklet szerinti ágazat és alágazat",
    "ue.zaslepki.21": "azon tagállamok jegyzéke, ahol a szervezet szolgáltatást nyújt",
    "ue.zaslepki.22": "A nemzeti jog határozza meg.",
    "ue.zaslepki.23": "(EU) 2022/2555 irányelv — 3. cikk",
    "ue.zaslepki.24": "ENISA — a tagállamok illetékes hatóságai",
    "ue.zaslepki.25": "(EU) 2022/2555 irányelv",
    "ue.zaslepki.26": "Az uniós modul nem tartalmaz nemzeti hatósági iránymutatást — ez a nemzeti jogi modullal érkezik.",
    "ue.zaslepki.27": "A nyilvántartási adatok automatikus lekérése csak a nemzeti jogi modullal rendelkező országoknál működik. Töltse ki a profilt kézzel.",
    "ue.zaslepki.28": "A beszámoló beolvasása csak a nemzeti jogi modullal rendelkező országoknál működik. Adja meg az árbevételt és a létszámot kézzel.",
    "ue.zaslepki.3": "A Bizottság (EU) 2024/2690 végrehajtási rendelete",
    "ue.zaslepki.4": "HL EU L, 2024/2690, 2024.11.18.",
    "ue.zaslepki.5": "A NIS 2 irányelv nem tartalmaz külön hírközlési réteget. A nemzeti elektronikus hírközlési jog további kötelezettségeket írhat elő — ezt a modul nem ismeri.",
    "ue.zaslepki.6": "Az alapvető és fontos szervezetek jegyzéke",
    "ue.zaslepki.7": "A tagállam illetékes hatósága.",
    "ue.zaslepki.8": "Az irányelv előírja a tagállamoknak az alapvető és fontos szervezetek jegyzékének vezetését és a nyilvántartási adatok benyújtásának megkövetelését a szervezetektől. A portált, az eljárást és a határidőt a nemzeti jog határozza meg — ezt a modul nem ismeri, mert a kiválasztott ország nemzeti jogi modulja még nem készült el.",
    "ue.zaslepki.9": "Minden alapvető és fontos szervezet. A határidőt a nemzeti jog határozza meg.",
    "ue.zaslepki.skrotDyrektywy": "NIS 2 irányelv",
    "ue.zaslepki.skrotReg2690": "2024/2690 rendelet",
    "xlsx.1": "{p0} – {p1} EUR",
    "xlsx.25": "Árfolyam",
    "xlsx.4": "MEGFELELÉSI JELENTÉS — (EU) 2022/2555 NIS 2 IRÁNYELV",
    "xlsx.58": "Elektronikus hírközlési tevékenység: az (EU) 2024/2690 rendelet nem alkalmazandó. A küszöbértékeket a nemzeti jog határozza meg (az irányelv 23. cikk (11) bekezdése) — a közös modul nem ismeri őket.",
    "xlsx.68": "Az eszköz önértékelést szolgál. Nem audit és nem jogi vélemény.",
    "xlsx.69": "Az (EU) 2024/2690 rendelet hatálya alá nem tartozó szervezetek esetében a jelentős incidens küszöbértékeit a nemzeti jog határozza meg (az irányelv 23. cikk (11) bekezdése).",
    "xlsx.70": "A profilban megadott szerepek nyilatkozatnak minősülnek. A státuszt a ténylegesen végzett tevékenység határozza meg (az (EU) 2022/2555 irányelv 3. cikke).",
    "xlsx.etykietaKrs": "Cégjegyzékszám",
    "xlsx.etykietaNip": "Azonosítószám",
    "xlsx.etykietaRegon": "Statisztikai szám"
});
