/* Teksty modułu ue — język: it.
   Te same klucze co w napisy/pl.js (wersja źródłowa); wstawki {p0}, {p1}…
   pozostają bez zmian. Klucze ue.cyt.* to wzorce składania odesłań
   do przepisów w tym języku — patrz kraje/ue/cytaty.js. */
KRAJE.napisy('ue', 'it', {
    "app.10": "Verifica l'elenco dei ruoli qui sotto: lo status dipende dall'attività effettivamente svolta (articolo 3 della direttiva (UE) 2022/2555), non dall'iscrizione in un registro.",
    "app.14": "Anno precedente: {p0} EUR",
    "app.15": "Fatturato del periodo di riferimento: {p0} EUR",
    "app.19": "Interrogazione dei registri con il numero {p0}…",
    "app.34": " mld EUR",
    "app.35": " mln EUR",
    "app.36": " mila EUR",
    "app.37": "",
    "app.4": "Il recupero automatico dei dati dai registri non è disponibile per questo paese: compila il profilo manualmente.",
    "app.59": "Valutazione di conformità alla direttiva NIS 2 (JSON)",
    "app.68": "Per questo paese non esiste un registro da cui lo strumento possa recuperare i dati: il profilo si compila manualmente.",
    "app.69": "Per questo paese non esiste un registro da cui lo strumento possa recuperare i dati. Fai clic per attivare la modalità offline.",
    "app.73": " · conto economico nella variante ",
    "app.74": "<div class=\"mt-2 tekst-uwaga\">Dai dati dei registri non emerge alcun ruolo del settore delle infrastrutture digitali. Indica i ruoli manualmente qui sotto.</div>",
    "app.8": "Iscrizione nel registro dei fornitori di comunicazioni elettroniche confermata",
    "app.progDostawcy": "",
    "app.przyklad.adres": "Via dell'Esempio 1, 00100 Città",
    "app.przyklad.forma": "Società a responsabilità limitata",
    "app.przyklad.nazwa": "Operatore Esempio S.r.l.",
    "app.statusVat": " · stato IVA: ",
    "dashboard.1": "In base ai ruoli e alla dimensione dichiarati, il soggetto non è né essenziale né importante ai sensi dell'articolo 3 della direttiva (UE) 2022/2555. Verifica il profilo se il risultato non corrisponde alle attese.",
    "dashboard.113": "Domande frequenti",
    "dashboard.12": "— {p0}; il termine di recepimento nel diritto nazionale è scaduto il {p2}",
    "dashboard.123": "Direttiva NIS 2",
    "dashboard.30": "Elenco dei soggetti essenziali e importanti",
    "dashboard.4": "— direttamente applicabile dal {p0} in tutti gli Stati membri, senza recepimento",
    "dashboard.42": "Variante in importo fisso: {p0}",
    "dashboard.45": "Criteri dell'articolo 32, paragrafo 7, della direttiva:",
    "dashboard.46": "Totale",
    "dashboard.49": "Il soggetto svolge attività di comunicazione elettronica: la responsabilità della persona dirigente è regolata dal diritto nazionale",
    "dashboard.50": "",
    "dashboard.51": "",
    "dashboard.53": "Penalità di mora per ritardo nell'esecuzione di una decisione: da {p0} EUR a {p1} EUR al giorno ({p2})",
    "dashboard.54": "Caso qualificato: fino a {p0} EUR ({p1})",
    "dashboard.57": "({p0}). Da quando l'autorità nazionale può irrogare sanzioni lo stabilisce la legge di recepimento: questo modulo non la conosce. Gli obblighi di attuazione derivano dal diritto nazionale dalla sua entrata in vigore.",
    "dashboard.65": "({p0}). Da quando l'autorità nazionale può irrogare sanzioni lo stabilisce la legge di recepimento: questo modulo non la conosce. Il rischio finanziario non è quindi datato qui, mentre gli obblighi di attuazione derivano dal diritto nazionale dalla sua entrata in vigore.",
    "dashboard.83": "Attività di comunicazione elettronica: le soglie sono fissate dal diritto nazionale.",
    "dashboard.84": "Il regolamento (UE) 2024/2690 non si applica ai fornitori di reti pubbliche e servizi di comunicazione elettronica. Per loro le soglie dell'incidente significativo sono fissate dal diritto nazionale (articolo 23, paragrafo 11, della direttiva): questo modulo non le conosce e quindi non indica valori.",
    "dashboard.terminRejestracji": "Il termine per la trasmissione dei dati di registrazione è fissato dal diritto nazionale (articolo 3, paragrafo 4, della direttiva). I fornitori di cui all'articolo 27, paragrafo 1 — servizi DNS, registri dei nomi di dominio di primo livello, servizi cloud, data center, reti di distribuzione dei contenuti, servizi gestiti e servizi di sicurezza gestiti — trasmettono i dati al registro dell'ENISA: inizialmente entro il 17 gennaio 2025, e ogni modifica senza indebito ritardo.",
    "html.1": "ITORO — Valutazione di conformità alla direttiva NIS 2 (UE) 2022/2555",
    "html.10": "Valutazione di conformità alla direttiva NIS 2 — modulo comune",
    "html.100": "La lettura del bilancio funziona solo per i paesi con un modulo di diritto nazionale. Per questo paese inserisci manualmente il <strong>fatturato</strong> dell'esercizio: da esso dipende l'entità della sanzione.",
    "html.102": "Il recupero automatico dei dati dai registri funziona solo per i paesi con un modulo di diritto nazionale. Ruoli e dimensione dell'impresa li indichi manualmente.",
    "html.11": "La direttiva (UE) 2022/2555 (NIS 2) richiede il recepimento nel diritto nazionale. La valutazione copre gli obblighi che derivano direttamente dalla direttiva e il regolamento di esecuzione (UE) 2024/2690 della Commissione, direttamente applicabile, nella misura in cui riguardano il soggetto.",
    "html.23": "fatturato e dimensione li inserisci manualmente: il modulo comune non interroga i registri nazionali",
    "html.33": "direttiva (UE) 2022/2555 del Parlamento europeo e del Consiglio del 14 dicembre 2022 (NIS 2)",
    "html.33a": "{p0} — atto nazionale di recepimento della direttiva; questo modulo non ne valuta ancora i requisiti",
    "html.33b": "lo Stato non ha ancora adottato un atto di recepimento — la valutazione segue il diritto dell'Unione",
    "html.35": "obblighi dell'organo di gestione — articolo 20 della direttiva",
    "html.36": "Lo strumento serve all'autovalutazione. Non è un audit né un parere legale.",
    "html.40": "il modulo comune non effettua alcuna connessione in uscita: non interroga i registri",
    "html.59": "Bilanci",
    "html.60": "La lettura del bilancio è disponibile solo per i paesi con un modulo di diritto nazionale. Per questo paese inserisci manualmente fatturato e organico.",
    "html.62": "Ricerca nel registro",
    "html.63": "i registri delle imprese sono nazionali: il modulo comune non li conosce",
    "html.64": "ruoli e dimensione dell'impresa li indichi manualmente",
    "html.66": "Numero identificativo del soggetto",
    "html.68": "Il recupero automatico dei dati dai registri funziona solo per i paesi con un modulo di diritto nazionale.",
    "html.76": "Fatturato annuo (EUR)",
    "html.78": "Fatturato dell'attività di comunicazione elettronica (EUR)",
    "html.79": "Il campo riguarda i fornitori di reti pubbliche o servizi di comunicazione elettronica. Le soglie nazionali sono fissate dal diritto dello Stato membro.",
    "html.80": "Retribuzione mensile del responsabile (EUR)",
    "html.82": "Tasso di cambio",
    "html.83": "I massimali delle sanzioni nella direttiva sono espressi in euro. La conversione nella valuta nazionale e il cambio sono stabiliti dal diritto nazionale: qui gli importi sono indicati in euro senza conversione.",
    "html.84": "Lo status deriva esclusivamente dall'aggregazione dei dati delle imprese collegate e il sistema informativo del soggetto è indipendente (considerando 16 della direttiva: sull'applicazione decide il diritto nazionale)",
    "html.85": "Il soggetto opera nei settori della sicurezza nazionale, della pubblica sicurezza, della difesa o dell'attività di contrasto (articolo 2, paragrafo 7, della direttiva)",
    "html.91": "Valutazione di conformità alla direttiva (UE) 2022/2555 del Parlamento europeo e del Consiglio (NIS 2) e al regolamento di esecuzione (UE) 2024/2690 della Commissione — modulo comune per i paesi il cui modulo di diritto nazionale non è ancora pronto.",
    "html.94": "se il soggetto è <strong>essenziale</strong>, <strong>importante</strong> o fuori dall'ambito della direttiva",
    "html.daneZeSprawozdania": "nome, numero identificativo, indirizzo della sede",
    "html.rejestrMozliwy": "Il registro {p0} è pubblico e gratuito: la sua lettura può essere aggiunta allo strumento; accogliamo volentieri pull request (vedi README).",
    "html.tytulNaglowka": "Valutazione di conformità alla direttiva NIS 2",
    "html.zrodlaRecznie": "Questo modulo non conosce i registri del suo Stato: compili il profilo a mano. Il fatturato annuo determina il massimale della sanzione, quindi lo indichi con precisione.",
    "klasyfikacja.10": "articolo 3, paragrafo 1, lettera c), della direttiva (UE) 2022/2555 (fornitore di reti pubbliche di comunicazione elettronica o di servizi di comunicazione elettronica accessibili al pubblico che è almeno una media impresa)",
    "klasyfikacja.11": "articolo 3, paragrafo 2, in combinato disposto con l'articolo 2, paragrafo 2, lettera a), punto i), della direttiva (UE) 2022/2555 (fornitore di reti pubbliche o servizi di comunicazione elettronica che è una microimpresa o una piccola impresa)",
    "klasyfikacja.12": "articolo 3, paragrafo 1, lettera a), della direttiva (UE) 2022/2555 (fornitore di servizi di sicurezza gestiti che supera i massimali della media impresa)",
    "klasyfikacja.13": "Le microimprese e le piccole imprese non rientrano nella direttiva per questo ruolo (articolo 2, paragrafo 1, a contrario).",
    "klasyfikacja.15": "articolo 3, paragrafo 1, lettera b), della direttiva (UE) 2022/2555 (prestatore di servizi fiduciari qualificato) — indipendentemente dalla dimensione dell'impresa",
    "klasyfikacja.16": "articolo 3, paragrafo 2, in combinato disposto con l'articolo 2, paragrafo 2, lettera a), punto ii), della direttiva (UE) 2022/2555 (prestatore di servizi fiduciari non qualificato che è una microimpresa, una piccola o una media impresa)",
    "klasyfikacja.18": "articolo 3, paragrafo 2, della direttiva (UE) 2022/2555 (soggetto della pubblica amministrazione a livello regionale, se lo Stato membro lo prevede — articolo 2, paragrafo 2, lettera f), punto ii))",
    "klasyfikacja.19": "articolo 3, paragrafo 1, lettera f), della direttiva (UE) 2022/2555 (soggetto della pubblica amministrazione a livello centrale — articolo 2, paragrafo 2, lettera f), punto i))",
    "klasyfikacja.2": "Vigilanza ex ante ed ex post (articolo 32 della direttiva (UE) 2022/2555).",
    "klasyfikacja.20": "articolo 3, paragrafo 2, della direttiva (UE) 2022/2555 (soggetto della pubblica amministrazione a livello regionale — articolo 2, paragrafo 2, lettera f), punto ii))",
    "klasyfikacja.21": "L'ambito degli obblighi dei soggetti della pubblica amministrazione a livello locale è stabilito dal diritto nazionale (articolo 2, paragrafo 5, lettera a), della direttiva).",
    "klasyfikacja.22": "Uno Stato membro può esentare i soggetti che operano nei settori della sicurezza nazionale, della pubblica sicurezza, della difesa o dell'attività di contrasto (articolo 2, paragrafo 7, della direttiva). L'esenzione non opera da sola: verifica il risultato della valutazione con il diritto nazionale.",
    "klasyfikacja.23": "Il soggetto soddisfa i criteri sia del soggetto essenziale sia del soggetto importante. È un soggetto essenziale (articolo 3, paragrafo 1, della direttiva) e i requisiti più elevati si applicano a tutta l'attività coperta dalla direttiva.",
    "klasyfikacja.25": "Il soggetto è essenziale, quindi si applicano il catalogo completo delle misure di cui all'articolo 21, paragrafo 2, della direttiva e la vigilanza ex ante ed ex post: la valutazione copre l'insieme completo delle domande.",
    "klasyfikacja.26": "In quanto soggetto importante siete sottoposti allo stesso catalogo di misure dell'articolo 21, paragrafo 2, ma alla sola vigilanza ex post (articolo 33). Il massimale della sanzione è inferiore: 7 milioni di EUR o l'1,4 % del fatturato (articolo 34, paragrafo 5). Alleggerimenti per i soggetti pubblici possono essere previsti dal diritto nazionale: questo modulo non li conosce.",
    "klasyfikacja.28": "Gli obblighi dei soggetti della pubblica amministrazione derivano dall'articolo 2, paragrafo 2, lettera f), della direttiva; il loro ambito esatto, anche per il livello locale e gli istituti di istruzione, è stabilito dal diritto nazionale (articolo 2, paragrafo 5).",
    "klasyfikacja.29": "È stato dichiarato che lo status del soggetto deriva esclusivamente dall'aggregazione dei dati delle imprese collegate o associate e che il sistema informativo del soggetto è indipendente. La direttiva ammette tale esclusione (considerando 16), ma è il diritto nazionale a deciderla: il modulo assume l'esclusione, che va verificata con il diritto dello Stato membro e documentata.",
    "klasyfikacja.4": "Vigilanza solo ex post, in presenza di prove, indicazioni o informazioni di una violazione (articolo 33 della direttiva (UE) 2022/2555).",
    "klasyfikacja.5": "Fuori dall'ambito della direttiva",
    "klasyfikacja.6": "Nessun obbligo derivante dalla direttiva (UE) 2022/2555 per il ruolo indicato.",
    "klasyfikacja.7": "articolo 3, paragrafo 1, lettera a), della direttiva (UE) 2022/2555 (soggetto di un tipo di cui all'allegato I che supera i massimali della media impresa)",
    "klasyfikacja.8": "articolo 3, paragrafo 2, della direttiva (UE) 2022/2555 (soggetto di un tipo di cui all'allegato I che soddisfa i criteri della media impresa)",
    "klasyfikacja.9": "Le microimprese e le piccole imprese non rientrano nella direttiva per questo ruolo (articolo 2, paragrafo 1, a contrario).",
    "kreator.10": "Inserisci manualmente il fatturato dell'anno precedente.",
    "kreator.35": "<span class=\"text-secondary\">La lettura dei bilanci non è disponibile per questo paese.</span>",
    "kreator.37": "La lettura dei bilanci non è disponibile per questo paese: inserisci il fatturato manualmente.",
    "kreator.56": "Sì: il regolamento UE si applica direttamente dal 7 novembre 2024 in tutti gli Stati membri e non prevede un periodo transitorio. La sua base è",
    "kreator.57": ", che ha conferito alla Commissione il potere di stabilire i requisiti tecnici e metodologici per i fornitori di cui all'articolo 3, paragrafo 1, del regolamento. Il termine di recepimento della direttiva è scaduto il",
    "kreator.58": ", e da quando l'autorità nazionale può irrogare sanzioni lo stabilisce il diritto nazionale. I requisiti tecnici dell'allegato (sezioni 6 e da 9 a 13) sono vincolanti nella formulazione attuale: non attendono ulteriori precisazioni. Si può derogare solo ai requisiti con la formula «se del caso», ed esclusivamente documentandone la giustificazione.",
    "kreator.9": "Bilanci →",
    "kreator.przepisReg2690": "l'articolo 21, paragrafo 5, della direttiva (UE) 2022/2555",
    "kreator.terminReg2690": "17 ottobre 2024",
    "punktacja.10": "Soggetti pubblici",
    "punktacja.4": "Direttiva NIS 2 — articolo 21",
    "punktacja.5": "Direttiva NIS 2 — obblighi formali",
    "punktacja.8": "Comunicazioni elettroniche",
    "punktacja.9": "Direttiva NIS 2 — soggetti pubblici",
    "punktacja.skrotKsc": "NIS 2",
    "punktacja.skrotPke": "telecom",
    "ue.cyt.akapit": ", {p0} comma",
    "ue.cyt.art": "articolo {p0}",
    "ue.cyt.drugi": "secondo",
    "ue.cyt.dyr": "{p0}, della direttiva (UE) 2022/2555",
    "ue.cyt.i": "e",
    "ue.cyt.laczenie": "",
    "ue.cyt.lit": ", lettera {p0})",
    "ue.cyt.litery": "",
    "ue.cyt.pkt": ", punto {p0}",
    "ue.cyt.rozdzielacz": "; ",
    "ue.cyt.rozp": "{p0}, del regolamento (UE) 2024/2690",
    "ue.cyt.ust": ", paragrafo {p0}",
    "ue.katalog.1": "Politiche di analisi dei rischi e di sicurezza dei sistemi informatici",
    "ue.katalog.10": "Gestione degli incidenti",
    "ue.katalog.11": "La gestione degli incidenti comprende le azioni e le procedure volte a prevenire, rilevare, analizzare e contenere un incidente, a rispondervi e a ripristinare la normale operatività (articolo 6, punto 8).",
    "ue.katalog.12": "Esiste una procedura documentata di gestione degli incidenti che copre rilevamento, analisi, contenimento, risposta e ripristino?",
    "ue.katalog.13": "ISO/IEC 27001 A.5.24–A.5.26",
    "ue.katalog.14": "La procedura consente di rispettare i termini di notifica di un incidente significativo: preallarme entro 24 ore, notifica entro 72 ore, relazione finale entro un mese?",
    "ue.katalog.15": "ISO/IEC 27001 A.5.24",
    "ue.katalog.16": "Il soggetto dispone di criteri per considerare significativo un incidente, conformi all'articolo 23, paragrafo 3: gravi perturbazioni operative o perdite finanziarie, oppure danni considerevoli ad altre persone?",
    "ue.katalog.17": "ISO/IEC 27001 A.5.25",
    "ue.katalog.18": "Gli incidenti sono registrati e gli insegnamenti tratti dalla loro gestione sono usati per migliorare le misure?",
    "ue.katalog.19": "ISO/IEC 27001 A.5.27",
    "ue.katalog.2": "Le misure si basano su un approccio multirischio (articolo 21, paragrafo 2). La loro proporzionalità si valuta tenendo conto del grado di esposizione, della dimensione del soggetto, della probabilità degli incidenti e della loro gravità (articolo 21, paragrafo 1, secondo comma).",
    "ue.katalog.20": "Continuità operativa e gestione delle crisi",
    "ue.katalog.21": "Continuità operativa, come la gestione dei backup e il ripristino in caso di disastro, e gestione delle crisi.",
    "ue.katalog.22": "Esiste un piano di continuità operativa che copre il ripristino dopo un disastro?",
    "ue.katalog.23": "ISO/IEC 27001 A.5.29–A.5.30",
    "ue.katalog.24": "I backup sono eseguiti, protetti e testati quanto alla possibilità di ripristino?",
    "ue.katalog.25": "ISO/IEC 27001 A.8.13",
    "ue.katalog.26": "Il soggetto dispone di procedure di gestione delle crisi con ruoli e canali di comunicazione definiti?",
    "ue.katalog.27": "ISO/IEC 27001 A.5.29",
    "ue.katalog.28": "I piani di continuità e ripristino sono testati periodicamente e i risultati documentati?",
    "ue.katalog.29": "ISO/IEC 27001 A.5.30",
    "ue.katalog.3": "Il soggetto dispone di una politica documentata di analisi dei rischi e di sicurezza dei sistemi informatici, approvata dall'organo di gestione?",
    "ue.katalog.30": "Sicurezza della catena di approvvigionamento",
    "ue.katalog.31": "Sicurezza della catena di approvvigionamento, compresi gli aspetti relativi alla sicurezza riguardanti i rapporti tra il soggetto e i suoi fornitori o prestatori di servizi diretti. Il soggetto tiene conto delle vulnerabilità specifiche di ciascun fornitore e della qualità complessiva dei suoi prodotti e delle sue pratiche di cibersicurezza (articolo 21, paragrafo 3).",
    "ue.katalog.32": "Il soggetto tiene un elenco dei fornitori e prestatori di servizi diretti con una valutazione della loro rilevanza per la sicurezza delle reti e dei sistemi?",
    "ue.katalog.33": "ISO/IEC 27001 A.5.19",
    "ue.katalog.34": "Nella scelta delle misure verso i fornitori si tiene conto delle vulnerabilità specifiche di ciascuno e della qualità delle loro pratiche di cibersicurezza e di sviluppo sicuro?",
    "ue.katalog.35": "ISO/IEC 27001 A.5.19, A.5.21",
    "ue.katalog.36": "I contratti con i fornitori contengono requisiti di sicurezza e l'obbligo di informare su incidenti e vulnerabilità?",
    "ue.katalog.37": "ISO/IEC 27001 A.5.20",
    "ue.katalog.38": "Il soggetto tiene conto dei risultati delle valutazioni coordinate dei rischi per la sicurezza delle catene di approvvigionamento critiche di cui all'articolo 22?",
    "ue.katalog.39": "ISO/IEC 27001 A.5.21",
    "ue.katalog.4": "ISO/IEC 27001 punti 5.2, 6.1.2",
    "ue.katalog.40": "Sicurezza nell'acquisizione, nello sviluppo e nella manutenzione dei sistemi",
    "ue.katalog.41": "Sicurezza dell'acquisizione, dello sviluppo e della manutenzione dei sistemi informatici e di rete, compresa la gestione e la divulgazione delle vulnerabilità.",
    "ue.katalog.42": "I requisiti di sicurezza sono definiti prima dell'acquisizione o dell'avvio dello sviluppo di un sistema e verificati prima della messa in esercizio?",
    "ue.katalog.43": "ISO/IEC 27001 A.8.25–A.8.29",
    "ue.katalog.44": "Esiste un processo di gestione delle vulnerabilità: identificazione, valutazione, correzione entro un tempo definito?",
    "ue.katalog.45": "ISO/IEC 27001 A.8.8",
    "ue.katalog.46": "Il soggetto dispone di una procedura di divulgazione delle vulnerabilità, compreso un canale per ricevere segnalazioni da terzi?",
    "ue.katalog.47": "Le modifiche ai sistemi passano attraverso un processo controllato di gestione dei cambiamenti con valutazione dell'impatto sulla sicurezza?",
    "ue.katalog.48": "ISO/IEC 27001 A.8.32",
    "ue.katalog.49": "Valutazione dell'efficacia delle misure",
    "ue.katalog.5": "L'analisi dei rischi copre tutti i rischi per i sistemi informatici e di rete e per il loro ambiente fisico, e non solo le minacce informatiche?",
    "ue.katalog.50": "Politiche e procedure per valutare l'efficacia delle misure di gestione dei rischi di cibersicurezza.",
    "ue.katalog.51": "Esiste una politica documentata di valutazione dell'efficacia delle misure che definisce ambito, frequenza e metodi?",
    "ue.katalog.52": "ISO/IEC 27001 punto 9.1",
    "ue.katalog.53": "Le valutazioni di efficacia sono svolte periodicamente e i risultati comunicati all'organo di gestione?",
    "ue.katalog.54": "ISO/IEC 27001 punti 9.2–9.3",
    "ue.katalog.55": "Le debolezze rilevate portano ad azioni correttive documentate con responsabile e scadenza?",
    "ue.katalog.56": "ISO/IEC 27001 punto 10.1",
    "ue.katalog.57": "Igiene informatica e formazione",
    "ue.katalog.58": "Pratiche di base di igiene informatica e formazione in materia di cibersicurezza. I membri dell'organo di gestione seguono una formazione regolare (articolo 20, paragrafo 2).",
    "ue.katalog.59": "Il soggetto applica pratiche di base di igiene informatica: aggiornamenti, gestione delle password, limitazione dei privilegi, protezione dai malware?",
    "ue.katalog.6": "ISO/IEC 27001 punto 6.1.2",
    "ue.katalog.60": "ISO/IEC 27001 A.8.7, A.8.8",
    "ue.katalog.61": "Il personale segue una formazione in cibersicurezza adeguata al proprio ruolo, con partecipazione documentata?",
    "ue.katalog.62": "ISO/IEC 27001 A.6.3",
    "ue.katalog.63": "I membri dell'organo di gestione seguono una formazione regolare che consente loro di individuare i rischi e valutare le pratiche di gestione dei rischi?",
    "ue.katalog.64": "ISO/IEC 27001 punto 7.2",
    "ue.katalog.65": "Crittografia e cifratura",
    "ue.katalog.66": "Politiche e procedure relative all'uso della crittografia e, se del caso, della cifratura.",
    "ue.katalog.67": "Esiste una politica sull'uso della crittografia che definisce quali dati e canali sono cifrati e con quali algoritmi?",
    "ue.katalog.68": "ISO/IEC 27001 A.8.24",
    "ue.katalog.69": "Le chiavi crittografiche sono gestite lungo l'intero ciclo di vita: generazione, distribuzione, conservazione, rotazione, ritiro?",
    "ue.katalog.7": "La scelta delle misure tiene conto dello stato dell'arte, delle norme europee e internazionali pertinenti e dei costi di attuazione?",
    "ue.katalog.70": "Risorse umane, controllo degli accessi e gestione degli attivi",
    "ue.katalog.71": "Sicurezza delle risorse umane, politiche di controllo degli accessi e gestione degli attivi.",
    "ue.katalog.72": "Il soggetto tiene un inventario aggiornato degli attivi con proprietari assegnati e classificazione?",
    "ue.katalog.73": "ISO/IEC 27001 A.5.9, A.5.12",
    "ue.katalog.74": "Esiste una politica di controllo degli accessi basata sul principio del privilegio minimo, con revisione periodica delle autorizzazioni?",
    "ue.katalog.75": "ISO/IEC 27001 A.5.15, A.5.18",
    "ue.katalog.76": "All'assunzione, al cambio di mansione e all'uscita del personale si applicano procedure di sicurezza, compresi la revoca delle autorizzazioni e la restituzione degli attivi?",
    "ue.katalog.77": "ISO/IEC 27001 A.6.1–A.6.5",
    "ue.katalog.78": "L'accesso privilegiato è limitato, registrato e riesaminato?",
    "ue.katalog.79": "ISO/IEC 27001 A.8.2",
    "ue.katalog.8": "ISO/IEC 27001 punto 6.1.3",
    "ue.katalog.80": "Autenticazione a più fattori e comunicazioni protette",
    "ue.katalog.81": "Se del caso: autenticazione a più fattori o continua, comunicazioni vocali, video e testuali protette e sistemi di comunicazione di emergenza protetti all'interno del soggetto.",
    "ue.katalog.82": "L'autenticazione a più fattori o continua è usata dove l'analisi dei rischi lo giustifica, in particolare per l'accesso remoto e gli account privilegiati?",
    "ue.katalog.83": "ISO/IEC 27001 A.8.5",
    "ue.katalog.84": "Le comunicazioni vocali, video e testuali usate per scopi di lavoro sono protette?",
    "ue.katalog.85": "ISO/IEC 27001 A.8.20",
    "ue.katalog.86": "Il soggetto dispone di un sistema protetto di comunicazione interna di emergenza, indipendente dall'infrastruttura principale?",
    "ue.katalog.9": "Il livello di sicurezza è documentato come adeguato al rischio esistente, con una motivazione che tiene conto della dimensione del soggetto e dell'impatto sociale ed economico degli incidenti?",
    "ue.kierownictwo.1": "L'organo di gestione di un soggetto essenziale o importante: in una società di capitali, il consiglio di amministrazione. La direttiva non definisce la nozione; la sua portata in un dato paese deriva dal diritto nazionale.",
    "ue.kierownictwo.10": "Stabilire lo status del soggetto e assicurare la registrazione",
    "ue.kierownictwo.11": "Stabilire se il soggetto è essenziale o importante e trasmettere i dati di registrazione all'autorità competente. Modalità e termine sono fissati dal diritto nazionale.",
    "ue.kierownictwo.12": "Attuare l'analisi dei rischi e la politica di sicurezza",
    "ue.kierownictwo.13": "Misure basate su un approccio multirischio, proporzionate all'esposizione, alla dimensione del soggetto e alla gravità degli incidenti.",
    "ue.kierownictwo.14": "Avviare la gestione e la notifica degli incidenti",
    "ue.kierownictwo.15": "Procedura di gestione degli incidenti e capacità di rispettare i termini di 24 ore, 72 ore e un mese.",
    "ue.kierownictwo.16": "24 h / 72 h / un mese dal rilevamento",
    "ue.kierownictwo.17": "Garantire la continuità operativa",
    "ue.kierownictwo.18": "Piano di continuità, backup, ripristino dopo un disastro, gestione delle crisi.",
    "ue.kierownictwo.19": "Mettere ordine nella catena di approvvigionamento",
    "ue.kierownictwo.2": "La responsabilità dell'organo di gestione non pregiudica le norme nazionali sulla responsabilità delle istituzioni pubbliche e dei funzionari (articolo 20, paragrafo 1, secondo comma).",
    "ue.kierownictwo.20": "Elenco dei fornitori, valutazione delle loro vulnerabilità e pratiche, requisiti di sicurezza nei contratti.",
    "ue.kierownictwo.21": "Attuare il controllo degli accessi e la gestione degli attivi",
    "ue.kierownictwo.22": "Inventario degli attivi, principio del privilegio minimo, revisioni delle autorizzazioni, autenticazione a più fattori dove il rischio lo giustifica.",
    "ue.kierownictwo.23": "Misurare l'efficacia delle misure",
    "ue.kierownictwo.24": "Politica e procedure di valutazione dell'efficacia, riesami periodici, azioni correttive.",
    "ue.kierownictwo.25": "Approvare",
    "ue.kierownictwo.26": "le misure di gestione dei rischi di cibersicurezza (articolo 20, paragrafo 1)",
    "ue.kierownictwo.27": "la politica di analisi dei rischi e di sicurezza dei sistemi",
    "ue.kierownictwo.28": "il bilancio e i ruoli nell'attuazione",
    "ue.kierownictwo.29": "Sorvegliare",
    "ue.kierownictwo.3": "Se l'affidamento degli obblighi ad altra persona escluda la responsabilità lo decide il diritto nazionale. In Polonia non la esclude (articolo 8c, paragrafo 3, della legge sul sistema nazionale di cibersicurezza).",
    "ue.kierownictwo.30": "l'attuazione delle misure approvate (articolo 20, paragrafo 1)",
    "ue.kierownictwo.31": "i risultati della valutazione dell'efficacia (articolo 21, paragrafo 2, lettera f))",
    "ue.kierownictwo.32": "il rispetto dei termini di notifica degli incidenti (articolo 23)",
    "ue.kierownictwo.33": "Documentare",
    "ue.kierownictwo.34": "le decisioni di approvazione e i riesami",
    "ue.kierownictwo.35": "la partecipazione alla formazione (articolo 20, paragrafo 2)",
    "ue.kierownictwo.36": "Membro dell'organo di gestione",
    "ue.kierownictwo.37": "approvazione delle misure, sorveglianza, decisioni, bilancio",
    "ue.kierownictwo.38": "Responsabile di progetto",
    "ue.kierownictwo.39": "coordinamento dell'attuazione, cronoprogramma, stato ed evidenze",
    "ue.kierownictwo.4": "Approvare le misure di gestione dei rischi di cibersicurezza",
    "ue.kierownictwo.40": "IT / cibersicurezza",
    "ue.kierownictwo.41": "analisi dei rischi, misure tecniche, gestione degli incidenti",
    "ue.kierownictwo.42": "Ufficio legale / compliance",
    "ue.kierownictwo.5": "L'organo di gestione approva le misure adottate per conformarsi all'articolo 21. È una decisione dell'organo, non del reparto IT: senza di essa le misure non hanno legittimazione.",
    "ue.kierownictwo.6": "Sorvegliare l'attuazione delle misure",
    "ue.kierownictwo.7": "La sorveglianza sull'attuazione è un obbligo dell'organo di gestione. L'esecuzione può essere affidata, la sorveglianza no.",
    "ue.kierownictwo.8": "Seguire una formazione regolare",
    "ue.kierownictwo.9": "I membri dell'organo di gestione seguono una formazione regolare per acquisire conoscenze sufficienti a individuare i rischi e valutare le pratiche di gestione dei rischi e il loro impatto sui servizi del soggetto.",
    "ue.kierownictwo.daneRejestracyjne": "i dati di registrazione e i loro aggiornamenti (articolo 3, paragrafi 4 e 5)",
    "ue.meta.1": "Prevale la variante percentuale: il {p0} % del fatturato è superiore a {p1} milioni di EUR.",
    "ue.meta.10": "La direttiva non impone obblighi direttamente alle imprese: lo fa la legge nazionale, che lo Stato membro doveva adottare entro il 17 ottobre 2024. Questo modulo presenta i requisiti nella formulazione della direttiva, perché il modulo di diritto nazionale del paese selezionato non è ancora pronto oppure il paese non ha recepito la direttiva.",
    "ue.meta.11": "Obblighi derivanti dalla direttiva",
    "ue.meta.12": "Elenco dei soggetti — entro il 17 aprile 2025",
    "ue.meta.13": "Gli Stati membri dovevano istituire un elenco dei soggetti essenziali e importanti entro il 17 aprile 2025 ed esigere dai soggetti la trasmissione dei dati di registrazione.",
    "ue.meta.14": "Regolamento (UE) 2024/2690",
    "ue.meta.15": "Direttamente applicabile dal 7 novembre 2024",
    "ue.meta.16": "Il regolamento di esecuzione si applica direttamente in tutti gli Stati membri, indipendentemente dallo stato di recepimento della direttiva. Riguarda i soggetti elencati nel suo articolo 1: DNS, TLD, cloud, data center, reti di distribuzione dei contenuti, servizi gestiti e servizi fiduciari.",
    "ue.meta.17": "articolo 16 del regolamento (UE) 2024/2690",
    "ue.meta.18": "Almeno 10 000 000 EUR o almeno il 2 % del fatturato mondiale totale annuo dell'impresa nell'esercizio precedente, se superiore. È un massimale minimo: il diritto nazionale può innalzarlo.",
    "ue.meta.19": "Almeno 7 000 000 EUR o l'1,4 % del fatturato mondiale totale annuo, se superiore. Massimale minimo.",
    "ue.meta.2": "Prevale l'importo fisso: {p0} milioni di EUR è superiore al {p1} % del fatturato.",
    "ue.meta.20": "La direttiva non prevede una sanzione distinta per la violazione qualificata: è una costruzione del diritto nazionale di alcuni paesi.",
    "ue.meta.21": "Gli Stati membri possono prevedere penalità di mora per costringere a cessare una violazione. L'importo è stabilito dal diritto nazionale.",
    "ue.meta.22": "L'organo di gestione approva le misure di gestione dei rischi, ne sorveglia l'attuazione e può essere ritenuto responsabile delle violazioni dell'articolo 21. Le regole e la portata di tale responsabilità sono stabilite dal diritto nazionale.",
    "ue.meta.23": "L'organo di gestione approva le misure di gestione dei rischi di cibersicurezza (articolo 20, paragrafo 1).",
    "ue.meta.24": "L'organo di gestione sorveglia l'attuazione di tali misure (articolo 20, paragrafo 1).",
    "ue.meta.25": "I membri dell'organo di gestione seguono una formazione regolare (articolo 20, paragrafo 2).",
    "ue.meta.26": "Nei confronti di un soggetto essenziale l'autorità può chiedere il divieto temporaneo di esercitare funzioni dirigenziali (articolo 32, paragrafo 5, lettera b)).",
    "ue.meta.27": "Il massimale minimo è fissato dalla direttiva",
    "ue.meta.28": "Si confrontano due valori: un importo fisso in euro e una percentuale del fatturato mondiale totale annuo dell'impresa nell'esercizio precedente. Il maggiore è il limite massimo che lo Stato membro deve quantomeno prevedere. Il diritto nazionale può innalzarlo.",
    "ue.meta.29": "L'importo entro il massimale è stabilito dall'autorità nazionale",
    "ue.meta.3": "Il massimale della direttiva supera di {p0} volte il fatturato annuo del soggetto. L'articolo 34, paragrafo 1, esige che la sanzione sia proporzionata alle circostanze del singolo caso: è un limite massimo, non una sanzione attesa.",
    "ue.meta.30": "La sanzione deve essere effettiva, proporzionata e dissuasiva secondo le circostanze del singolo caso. L'autorità tiene conto almeno dei criteri dell'articolo 32, paragrafo 7: gravità e durata della violazione, violazioni precedenti, danni, intenzionalità, misure correttive e cooperazione.",
    "ue.meta.31": "Il massimale può superare più volte il fatturato annuo: è un limite massimo, non un importo atteso. Minimi nazionali, penalità di mora e modalità di determinazione sono stabiliti dalla legge dello Stato membro.",
    "ue.meta.32": "Nel decidere se irrogare una sanzione amministrativa pecuniaria e nel determinarne l'importo, in ogni singolo caso si tiene debitamente conto almeno degli elementi elencati nell'articolo 32, paragrafo 7.",
    "ue.meta.33": "gravità della violazione e importanza delle disposizioni violate; sono in ogni caso considerate gravi: le violazioni ripetute, la mancata notifica o la mancata correzione di incidenti significativi, la mancata rimozione delle carenze in violazione di istruzioni vincolanti, l'ostruzione di audit o monitoraggio, la fornitura di informazioni false o gravemente inesatte",
    "ue.meta.34": "eventuali violazioni precedenti pertinenti da parte del soggetto",
    "ue.meta.35": "danni materiali o immateriali causati, comprese le perdite finanziarie, l'impatto su altri servizi e il numero di utenti interessati",
    "ue.meta.36": "carattere doloso o colposo della violazione",
    "ue.meta.37": "misure adottate per prevenire o attenuare i danni",
    "ue.meta.38": "adesione a codici di condotta approvati o a meccanismi di certificazione",
    "ue.meta.39": "grado di cooperazione con le autorità competenti",
    "ue.meta.4": "Direttiva (UE) 2022/2555 del Parlamento europeo e del Consiglio (NIS 2)",
    "ue.meta.40": "La direttiva non prevede espressamente la rinuncia alla sanzione: se e quando sia possibile lo decide il diritto nazionale.",
    "ue.meta.41": "Da questa data gli Stati membri devono applicare le disposizioni nazionali di attuazione della direttiva. La data concreta da cui l'autorità può irrogare una sanzione deriva dal diritto nazionale.",
    "ue.meta.42": "Entrata in vigore della direttiva NIS 2",
    "ue.meta.43": "Il ventesimo giorno successivo alla pubblicazione nella Gazzetta ufficiale.",
    "ue.meta.44": "Termine di recepimento della direttiva",
    "ue.meta.45": "Entro questa data gli Stati membri dovevano adottare e pubblicare le disposizioni nazionali.",
    "ue.meta.46": "Applicazione delle disposizioni nazionali e abrogazione della NIS 1",
    "ue.meta.47": "Da questa data gli Stati applicano le disposizioni di attuazione; la direttiva (UE) 2016/1148 è abrogata.",
    "ue.meta.48": "Applicazione del regolamento (UE) 2024/2690",
    "ue.meta.49": "Il regolamento di esecuzione si applica direttamente dal ventesimo giorno successivo alla pubblicazione.",
    "ue.meta.5": "GU UE L 333 del 27.12.2022",
    "ue.meta.50": "Elenco dei soggetti essenziali e importanti",
    "ue.meta.51": "Entro questa data gli Stati membri istituiscono l'elenco; i soggetti trasmettono alle autorità i dati di registrazione.",
    "ue.meta.52": "Primo riesame della direttiva da parte della Commissione",
    "ue.meta.53": "La Commissione riesamina il funzionamento della direttiva e presenta una relazione.",
    "ue.meta.54": "Preallarme di un incidente significativo",
    "ue.meta.55": "24 ore dal momento in cui se ne viene a conoscenza",
    "ue.meta.56": "Notifica di un incidente significativo",
    "ue.meta.57": "72 ore dal momento in cui se ne viene a conoscenza",
    "ue.meta.58": "Relazione finale",
    "ue.meta.59": "un mese dalla notifica dell'incidente",
    "ue.meta.6": "Regolamento di esecuzione (UE) 2024/2690 della Commissione",
    "ue.meta.60": "Notifica di incidente da parte di un prestatore di servizi fiduciari",
    "ue.meta.61": "articolo 21, paragrafo 5, della direttiva (UE) 2022/2555; articoli 1 e 2 del regolamento (UE) 2024/2690",
    "ue.meta.62": "Senza dati sul fatturato il massimale è l'importo fisso della direttiva.",
    "ue.meta.63": "I massimali dell'articolo 34, paragrafi 4 e 5, sono minimi («almeno»): il diritto nazionale può prevederne di più elevati. Importi in euro, senza conversione nella valuta nazionale.",
    "ue.meta.64": "Autorità competente dello Stato membro",
    "ue.meta.65": "L'organo di gestione può essere ritenuto responsabile delle violazioni dell'articolo 21. Portata e modalità sono stabilite dal diritto nazionale: questo modulo non le conosce.",
    "ue.meta.66": "La portata della responsabilità personale della direzione deriva dalla legge nazionale. Per la Polonia arriva fino al 300 % della retribuzione (articolo 73a, paragrafo 4, della legge sul sistema nazionale di cibersicurezza); altri paesi decidono diversamente.",
    "ue.meta.7": "GU UE L, 2024/2690",
    "ue.meta.8": "Direttiva (UE) 2022/2555",
    "ue.meta.9": "Il termine di recepimento è scaduto il 17 ottobre 2024",
    "ue.moduly.1": "circa {p0} min",
    "ue.moduly.10": "Dieci aree dell'articolo 21, paragrafo 2, lettere da a) a j): dalla politica dei rischi all'autenticazione a più fattori. La violazione è soggetta a sanzione ai sensi dell'articolo 34. Valutazione sulla scala di maturità.",
    "ue.moduly.11": "Regolamento 2024/2690 — governance e processi",
    "ue.moduly.12": "Sezioni da 1 a 5 e da 7 a 8 dell'allegato: politiche, gestione dei rischi, gestione degli incidenti, continuità operativa, catena di approvvigionamento, valutazione dell'efficacia, igiene informatica. Direttamente applicabile dal 7 novembre 2024.",
    "ue.moduly.13": "Regolamento 2024/2690 — requisiti tecnici",
    "ue.moduly.14": "Sezioni 6 e da 9 a 13 dell'allegato: acquisizione e sviluppo dei sistemi, crittografia, sicurezza delle risorse umane, controllo degli accessi, gestione degli attivi, sicurezza fisica e ambientale.",
    "ue.moduly.2": "circa {p0} h {p1} min",
    "ue.moduly.3": "circa {p0} h",
    "ue.moduly.4": "meno di un minuto",
    "ue.moduly.5": "Valutazione rapida dei rischi",
    "ue.moduly.6": "Domande trasversali da tutte le aree della direttiva. Ciascuna decide per un intero gruppo di questioni. Consente di stimare l'entità degli arretrati senza percorrere l'intero questionario.",
    "ue.moduly.7": "Obblighi derivanti dalla direttiva",
    "ue.moduly.8": "Dati di registrazione, notifica degli incidenti entro 24 e 72 ore, obblighi dell'organo di gestione, prontezza alla vigilanza. Verificabili sui documenti, senza analisi tecnica.",
    "ue.moduly.9": "Misure di gestione dei rischi — articolo 21, paragrafo 2",
    "ue.obowiazki.1": "Dati di registrazione per l'elenco dei soggetti",
    "ue.obowiazki.10": "Notifica degli incidenti significativi",
    "ue.obowiazki.11": "Il soggetto notifica gli incidenti significativi al CSIRT o all'autorità competente in tre fasi: preallarme, notifica, relazione finale. I termini decorrono dal momento in cui si viene a conoscenza dell'incidente.",
    "ue.obowiazki.12": "Il soggetto è in grado di trasmettere un preallarme entro 24 ore dal momento in cui viene a conoscenza di un incidente significativo, indicando se si sospetta che l'incidente sia dovuto ad atti illeciti e se possa avere un impatto transfrontaliero?",
    "ue.obowiazki.13": "24 ore dal momento in cui se ne viene a conoscenza",
    "ue.obowiazki.14": "Il soggetto è in grado di trasmettere una notifica dell'incidente entro 72 ore, con una valutazione iniziale della gravità e dell'impatto e con indicatori di compromissione?",
    "ue.obowiazki.15": "72 ore dal momento in cui se ne viene a conoscenza",
    "ue.obowiazki.16": "Il soggetto trasmette una relazione finale entro un mese dalla notifica, con descrizione dell'incidente, tipo di minaccia, misure di attenuazione e impatto transfrontaliero?",
    "ue.obowiazki.17": "un mese dalla notifica",
    "ue.obowiazki.18": "Il soggetto informa i destinatari dei suoi servizi degli incidenti significativi che possono incidere negativamente sulla prestazione di tali servizi?",
    "ue.obowiazki.19": "Il soggetto informa i destinatari dei suoi servizi di una minaccia informatica significativa e delle misure che possono adottare?",
    "ue.obowiazki.2": "Gli Stati membri istituiscono un elenco dei soggetti essenziali e importanti ed esigono dai soggetti la trasmissione dei dati di registrazione. Modalità, termine e portale sono fissati dal diritto nazionale.",
    "ue.obowiazki.20": "Se il soggetto è un prestatore di servizi fiduciari, notifica gli incidenti significativi entro 24 ore dal momento in cui ne viene a conoscenza?",
    "ue.obowiazki.21": "riguarda i prestatori di servizi fiduciari",
    "ue.obowiazki.22": "Organo di gestione",
    "ue.obowiazki.23": "L'organo di gestione approva le misure di gestione dei rischi, ne sorveglia l'attuazione e può essere ritenuto responsabile. I membri dell'organo seguono una formazione regolare.",
    "ue.obowiazki.24": "L'organo di gestione ha formalmente approvato le misure di gestione dei rischi di cibersicurezza adottate per conformarsi all'articolo 21?",
    "ue.obowiazki.25": "L'organo di gestione sorveglia l'attuazione di tali misure in modo documentato, ad esempio tramite relazioni e riesami periodici?",
    "ue.obowiazki.26": "I membri dell'organo di gestione seguono una formazione regolare che consente loro di individuare i rischi e valutare le pratiche di gestione dei rischi, con partecipazione documentata?",
    "ue.obowiazki.27": "Prontezza alle attività di vigilanza",
    "ue.obowiazki.28": "Un soggetto essenziale è sottoposto a vigilanza ex ante ed ex post, un soggetto importante solo ex post. L'autorità può richiedere informazioni, prove dell'attuazione delle politiche e risultati degli audit.",
    "ue.obowiazki.29": "Il soggetto è in grado, su richiesta dell'autorità, di fornire prove dell'attuazione delle politiche di cibersicurezza, compresi i risultati degli audit di sicurezza?",
    "ue.obowiazki.3": "Il soggetto ha stabilito se è essenziale o importante, in base al settore di cui all'allegato I o II e alla dimensione dell'impresa?",
    "ue.obowiazki.30": "Il soggetto è in grado, su richiesta dell'autorità, di mettere a disposizione dati, documenti e informazioni necessari all'esercizio dei compiti di vigilanza?",
    "ue.obowiazki.31": "Il soggetto essenziale è preparato a un audit di sicurezza svolto dall'autorità o da un organismo indipendente, a proprie spese?",
    "ue.obowiazki.4": "Il soggetto ha trasmesso all'autorità competente i dati di registrazione: nome, indirizzo e recapiti, settore e sottosettore, elenco degli Stati membri in cui presta servizi?",
    "ue.obowiazki.5": "I recapiti comprendono indirizzi e-mail, intervalli di indirizzi IP e numeri di telefono. Termine nazionale e portale di registrazione sono fissati dal diritto dello Stato membro.",
    "ue.obowiazki.6": "Esiste un processo di aggiornamento dei dati di registrazione senza indebito ritardo dopo una modifica?",
    "ue.obowiazki.7": "La direttiva richiede l'aggiornamento senza indebito ritardo; un termine preciso — ad esempio 14 giorni in Polonia — deriva dal diritto nazionale.",
    "ue.obowiazki.8": "Se il soggetto è fornitore di servizi DNS, registro TLD, fornitore cloud, data center, CDN, servizi gestiti, mercato online, motore di ricerca o social network, ha trasmesso i dati aggiuntivi di cui all'articolo 27, compreso l'indirizzo dello stabilimento principale nell'Unione?",
    "ue.obowiazki.9": "riguarda i soggetti di cui all'articolo 26, paragrafo 1",
    "ue.role.1": "Autorità competente dello Stato membro",
    "ue.role.10": "Servizi di data center: colocation, hosting di infrastrutture e servizi correlati.",
    "ue.role.11": "Data center",
    "ue.role.12": "Soggetto essenziale sopra la soglia della media impresa (articolo 3, paragrafo 1, lettera a)), importante se media (articolo 3, paragrafo 2). Sotto la media, fuori dall'ambito, salvo che lo Stato membro individui il soggetto ai sensi dell'articolo 2, paragrafo 2, lettere da b) a e). Coperto dal regolamento 2024/2690.",
    "ue.role.13": "Fornitore di punti di interscambio internet",
    "ue.role.14": "Infrastruttura che consente lo scambio di traffico tra reti indipendenti.",
    "ue.role.15": "Punti di interscambio internet",
    "ue.role.16": "Classificazione per dimensione (articolo 3, paragrafo 1, lettera a), e paragrafo 2). Il regolamento 2024/2690 non copre i punti di interscambio internet: l'articolo 1 del regolamento contiene un elenco chiuso di destinatari.",
    "ue.role.17": "Fornitore di servizi DNS",
    "ue.role.18": "Servizi di risoluzione dei nomi di dominio, esclusi gli operatori dei server dei nomi radice.",
    "ue.role.19": "Sistema dei nomi di dominio",
    "ue.role.2": "autorità competente",
    "ue.role.20": "Soggetto essenziale indipendentemente dalla dimensione (articolo 3, paragrafo 1, lettera b)). Coperto dal regolamento 2024/2690.",
    "ue.role.21": "Registro dei nomi di dominio di primo livello",
    "ue.role.22": "Gestione di un registro di dominio di primo livello.",
    "ue.role.23": "Soggetto essenziale indipendentemente dalla dimensione (articolo 3, paragrafo 1, lettera b)). Inoltre, obblighi sui dati di registrazione di cui all'articolo 28. Coperto dal regolamento 2024/2690.",
    "ue.role.24": "Fornitore di servizi di cloud computing",
    "ue.role.25": "Servizi di cloud computing: infrastruttura, piattaforma, software come servizio.",
    "ue.role.26": "Servizi di cloud computing",
    "ue.role.27": "Classificazione per dimensione (articolo 3, paragrafo 1, lettera a), e paragrafo 2). Coperto dal regolamento 2024/2690.",
    "ue.role.28": "Fornitore di reti di distribuzione dei contenuti",
    "ue.role.29": "Rete di server distribuiti che fornisce contenuti e servizi agli utenti finali.",
    "ue.role.3": "designata dal diritto nazionale; fino all'attuazione del modulo nazionale lo strumento non indica un'istituzione specifica",
    "ue.role.30": "Reti di distribuzione dei contenuti",
    "ue.role.31": "Prestatore di servizi fiduciari",
    "ue.role.32": "Servizi fiduciari ai sensi del regolamento (UE) n. 910/2014: firme, sigilli, validazioni temporali, certificati.",
    "ue.role.33": "Servizi fiduciari",
    "ue.role.34": "Coperto dalla direttiva indipendentemente dalla dimensione (articolo 2, paragrafo 2, lettera a), punto ii)). Il prestatore qualificato è un soggetto essenziale indipendentemente dalla dimensione (articolo 3, paragrafo 1, lettera b)); quello non qualificato è essenziale sopra la soglia della media impresa, altrimenti importante. Coperto dal regolamento 2024/2690.",
    "ue.role.35": "Fornitore di servizi gestiti",
    "ue.role.36": "Gestione dell'infrastruttura TIC del cliente: installazione, manutenzione, supporto, amministrazione dei sistemi.",
    "ue.role.37": "Gestione dei servizi TIC (B2B)",
    "ue.role.38": "Servizi gestiti",
    "ue.role.39": "Fornitore di servizi di sicurezza gestiti",
    "ue.role.4": "Fornitore di reti pubbliche di comunicazione elettronica o di servizi di comunicazione elettronica accessibili al pubblico",
    "ue.role.40": "Servizi gestiti nel campo della cibersicurezza: monitoraggio, risposta agli incidenti, test, consulenza.",
    "ue.role.41": "Servizi di sicurezza gestiti",
    "ue.role.42": "La direttiva classifica per dimensione (articolo 3, paragrafo 1, lettera a), e paragrafo 2). Gli Stati membri possono inasprire la soglia: la Polonia considera l'MSSP soggetto essenziale già dalla piccola impresa; questo modulo applica solo la regola della direttiva. Coperto dal regolamento 2024/2690.",
    "ue.role.5": "Fornitura di reti pubbliche di comunicazione elettronica o di servizi di comunicazione elettronica accessibili al pubblico, compreso l'accesso a internet.",
    "ue.role.6": "Infrastrutture digitali",
    "ue.role.7": "Comunicazioni elettroniche",
    "ue.role.8": "Coperto dalla direttiva indipendentemente dalla dimensione (articolo 2, paragrafo 2, lettera a), punto i)). La media impresa o più grande è un soggetto essenziale (articolo 3, paragrafo 1, lettera c)), la micro o piccola impresa un soggetto importante (articolo 3, paragrafo 2). La legge nazionale sulle telecomunicazioni può imporre obblighi aggiuntivi: questo modulo non li contiene.",
    "ue.role.9": "Fornitore di servizi di data center",
    "ue.role.podstawaArt3b": "articolo 3, paragrafo 1, lettera b), della direttiva (UE) 2022/2555",
    "ue.zaslepki.1": "Direttiva (UE) 2022/2555 del Parlamento europeo e del Consiglio (NIS 2)",
    "ue.zaslepki.10": "Se una parte dei soggetti è iscritta d'ufficio lo decide il diritto nazionale.",
    "ue.zaslepki.11": "Stabilisci se rientri nella direttiva",
    "ue.zaslepki.12": "Settore di cui all'allegato I o II e dimensione dell'impresa. Questa parte è svolta dal profilo del soggetto in questo strumento.",
    "ue.zaslepki.13": "Individua l'autorità competente nel tuo paese",
    "ue.zaslepki.14": "Ogni Stato designa un'autorità competente (articolo 8, paragrafo 1). L'elenco aggiornato è tenuto dall'ENISA e dalla Commissione.",
    "ue.zaslepki.15": "Trasmetti i dati di registrazione",
    "ue.zaslepki.16": "Nome, indirizzo e recapiti, settore e sottosettore, Stati in cui presti servizi (articolo 3, paragrafo 4). Modalità secondo il diritto nazionale.",
    "ue.zaslepki.17": "Aggiorna i dati senza indebito ritardo",
    "ue.zaslepki.18": "Ogni modifica dei dati di registrazione richiede un aggiornamento (articolo 3, paragrafo 5).",
    "ue.zaslepki.19": "indirizzo e recapiti aggiornati: indirizzi e-mail, intervalli di indirizzi IP, numeri di telefono",
    "ue.zaslepki.2": "GU UE L 333 del 27.12.2022, pag. 80",
    "ue.zaslepki.20": "settore e sottosettore di cui all'allegato I o II",
    "ue.zaslepki.21": "elenco degli Stati membri in cui il soggetto presta servizi",
    "ue.zaslepki.22": "Stabilito dal diritto nazionale.",
    "ue.zaslepki.23": "Direttiva (UE) 2022/2555 — articolo 3",
    "ue.zaslepki.24": "ENISA — autorità competenti degli Stati membri",
    "ue.zaslepki.25": "Direttiva (UE) 2022/2555",
    "ue.zaslepki.26": "Il modulo UE non contiene orientamenti di un'autorità nazionale: arriveranno con il modulo di diritto nazionale.",
    "ue.zaslepki.27": "Il recupero automatico dei dati dai registri funziona solo per i paesi con un modulo di diritto nazionale. Compila il profilo manualmente.",
    "ue.zaslepki.28": "La lettura del bilancio funziona solo per i paesi con un modulo di diritto nazionale. Inserisci manualmente fatturato e organico.",
    "ue.zaslepki.3": "Regolamento di esecuzione (UE) 2024/2690 della Commissione",
    "ue.zaslepki.4": "GU UE L, 2024/2690, 18.11.2024",
    "ue.zaslepki.5": "La direttiva NIS 2 non contiene un livello distinto per le comunicazioni elettroniche. Il diritto nazionale delle comunicazioni elettroniche può imporre obblighi aggiuntivi: questo modulo non li conosce.",
    "ue.zaslepki.6": "Elenco dei soggetti essenziali e importanti",
    "ue.zaslepki.7": "Autorità competente dello Stato membro.",
    "ue.zaslepki.8": "La direttiva impone agli Stati membri di tenere un elenco dei soggetti essenziali e importanti e di esigere dai soggetti la trasmissione dei dati di registrazione. Portale, modalità e termine sono fissati dal diritto nazionale: questo modulo non li conosce, perché il modulo di diritto nazionale del paese selezionato non è ancora pronto.",
    "ue.zaslepki.9": "Tutti i soggetti essenziali e importanti. Il termine è fissato dal diritto nazionale.",
    "ue.zaslepki.skrotDyrektywy": "direttiva NIS 2",
    "ue.zaslepki.skrotReg2690": "reg. 2024/2690",
    "xlsx.1": "{p0} – {p1} EUR",
    "xlsx.25": "Tasso di cambio",
    "xlsx.4": "RELAZIONE DI CONFORMITÀ ALLA DIRETTIVA NIS 2 (UE) 2022/2555",
    "xlsx.58": "Attività di comunicazione elettronica: il regolamento (UE) 2024/2690 non si applica. Le soglie sono fissate dal diritto nazionale (articolo 23, paragrafo 11, della direttiva): il modulo comune non le conosce.",
    "xlsx.68": "Lo strumento serve all'autovalutazione. Non è un audit né un parere legale.",
    "xlsx.69": "Per i soggetti non coperti dal regolamento (UE) 2024/2690 le soglie dell'incidente significativo sono fissate dal diritto nazionale (articolo 23, paragrafo 11, della direttiva).",
    "xlsx.70": "I ruoli indicati nel profilo sono una dichiarazione. Lo status dipende dall'attività effettivamente svolta (articolo 3 della direttiva (UE) 2022/2555).",
    "xlsx.etykietaKrs": "Numero di registro",
    "xlsx.etykietaNip": "Numero identificativo",
    "xlsx.etykietaRegon": "Numero statistico"
});
