/* Teksty modułu ue — język: lt.
   Te same klucze co w napisy/pl.js (wersja źródłowa); wstawki {p0}, {p1}…
   pozostają bez zmian. Klucze ue.cyt.* to wzorce składania odesłań
   do przepisów w tym języku — patrz kraje/ue/cytaty.js. */
KRAJE.napisy('ue', 'lt', {
    "app.10": "Patikrinkite funkcijų sąrašą žemiau — statusą lemia faktiškai vykdoma veikla (Direktyvos (ES) 2022/2555 3 straipsnis), o ne įrašas registre.",
    "app.14": "Praėję metai: {p0} EUR",
    "app.15": "Ataskaitinio laikotarpio pajamos: {p0} EUR",
    "app.19": "Registruose ieškoma pagal numerį {p0}…",
    "app.34": " mlrd. EUR",
    "app.35": " mln. EUR",
    "app.36": " tūkst. EUR",
    "app.37": "",
    "app.4": "Automatinis registro duomenų gavimas šiai šaliai neprieinamas — profilį užpildykite rankiniu būdu.",
    "app.59": "Atitikties TIS 2 direktyvai vertinimas (JSON)",
    "app.68": "Šiai šaliai nėra registro, iš kurio įrankis galėtų gauti duomenis — profilis pildomas rankiniu būdu.",
    "app.69": "Šiai šaliai nėra registro, iš kurio įrankis galėtų gauti duomenis. Spustelėkite, kad įjungtumėte režimą be ryšio.",
    "app.73": " · pelno (nuostolių) ataskaita versija ",
    "app.74": "<div class=\"mt-2 tekst-uwaga\">Registro duomenys nerodo jokios skaitmeninės infrastruktūros sektoriaus funkcijos. Pasirinkite funkcijas rankiniu būdu žemiau.</div>",
    "app.8": "Patvirtintas įrašas elektroninių ryšių paslaugų teikėjų registre",
    "app.progDostawcy": "",
    "app.przyklad.adres": "Pavyzdžio g. 1, 01000 Miestas",
    "app.przyklad.forma": "Uždaroji akcinė bendrovė",
    "app.przyklad.nazwa": "Pavyzdinis operatorius, UAB",
    "app.statusVat": " · PVM statusas: ",
    "dashboard.1": "Pagal deklaruotas funkcijas ir dydį subjektas nėra nei esminis, nei svarbus subjektas pagal Direktyvos (ES) 2022/2555 3 straipsnį. Patikrinkite profilį, jei rezultatas skiriasi nuo to, ko tikėjotės.",
    "dashboard.113": "Dažnai užduodami klausimai",
    "dashboard.12": "— {p0}; perkėlimo į nacionalinę teisę terminas baigėsi {p2}",
    "dashboard.123": "TIS 2 direktyva",
    "dashboard.30": "Esminių ir svarbių subjektų sąrašas",
    "dashboard.4": "— tiesiogiai taikomas nuo {p0} visose valstybėse narėse, be perkėlimo",
    "dashboard.42": "Fiksuotos sumos variantas: {p0}",
    "dashboard.45": "Direktyvos 32 straipsnio 7 dalies kriterijai:",
    "dashboard.46": "Iš viso",
    "dashboard.49": "Subjektas vykdo elektroninių ryšių veiklą — vadovaujančio asmens atsakomybę nustato nacionalinė teisė",
    "dashboard.50": "",
    "dashboard.51": "",
    "dashboard.53": "Periodinė bauda už vėlavimą įvykdyti sprendimą: nuo {p0} EUR iki {p1} EUR per dieną ({p2})",
    "dashboard.54": "Kvalifikuotas atvejis: iki {p0} EUR ({p1})",
    "dashboard.57": "({p0}). Nuo kada nacionalinė institucija gali skirti baudas, nustato direktyvą perkeliantis įstatymas — šis modulis jo nežino. Įgyvendinimo pareigos išplaukia iš nacionalinės teisės nuo jos įsigaliojimo dienos.",
    "dashboard.65": "({p0}). Nuo kada nacionalinė institucija gali skirti baudas, nustato direktyvą perkeliantis įstatymas — šis modulis jo nežino. Todėl finansinė rizika čia nedatuojama, o įgyvendinimo pareigos išplaukia iš nacionalinės teisės nuo jos įsigaliojimo dienos.",
    "dashboard.83": "Elektroninių ryšių veikla — ribas nustato nacionalinė teisė.",
    "dashboard.84": "Reglamentas (ES) 2024/2690 netaikomas viešųjų elektroninių ryšių tinklų ir paslaugų teikėjams. Jiems didelio incidento ribas nustato nacionalinė teisė (direktyvos 23 straipsnio 11 dalis) — šis modulis jų nežino, todėl skaičių nepateikia.",
    "dashboard.terminRejestracji": "Registracijos duomenų pateikimo terminą nustato nacionalinė teisė (direktyvos 3 straipsnio 4 dalis). 27 straipsnio 1 dalyje nurodyti teikėjai — DNS paslaugų teikėjai, aukščiausio lygio domenų vardų registrai, debesijos kompiuterijos, duomenų centrų, turinio teikimo tinklų, valdomų paslaugų ir valdomų saugumo paslaugų teikėjai — duomenis pateikia į ENISA registrą: iš pradžių iki 2025 m. sausio 17 d., o kiekvieną pakeitimą — nepagrįstai nedelsdami.",
    "html.1": "ITORO — Atitikties TIS 2 direktyvai (ES) 2022/2555 vertinimas",
    "html.10": "Atitikties TIS 2 direktyvai vertinimas — bendrasis modulis",
    "html.100": "Finansinės ataskaitos skaitymas veikia tik šalims, turinčioms nacionalinės teisės modulį. Šiai šaliai finansinių metų <strong>pajamas</strong> įvedate rankiniu būdu — nuo jų priklauso baudos dydis.",
    "html.102": "Automatinis registro duomenų gavimas veikia tik šalims, turinčioms nacionalinės teisės modulį. Funkcijas ir įmonės dydį nurodote rankiniu būdu.",
    "html.11": "Direktyvą (ES) 2022/2555 (TIS 2) reikia perkelti į nacionalinę teisę. Vertinimas apima pareigas, tiesiogiai išplaukiančias iš direktyvos, ir tiesiogiai taikomą Komisijos įgyvendinimo reglamentą (ES) 2024/2690 — tiek, kiek jie susiję su subjektu.",
    "html.23": "pajamas ir dydį įvedate rankiniu būdu — bendrasis modulis nesikreipia į nacionalinius registrus",
    "html.33": "2022 m. gruodžio 14 d. Europos Parlamento ir Tarybos direktyva (ES) 2022/2555 (TIS 2)",
    "html.33a": "{p0} — direktyvą perkeliantis nacionalinis aktas; jo reikalavimų šis modulis dar nevertina",
    "html.33b": "valstybė dar nepriėmė perkėlimo akto — vertinama pagal Sąjungos teisę",
    "html.35": "valdymo organo pareigos — direktyvos 20 straipsnis",
    "html.36": "Įrankis skirtas savęs vertinimui. Tai nėra nei auditas, nei teisinė konsultacija.",
    "html.40": "bendrasis modulis neužmezga jokių išeinančių ryšių — nesikreipia į registrus",
    "html.59": "Finansinės ataskaitos",
    "html.60": "Finansinės ataskaitos skaitymas prieinamas tik šalims, turinčioms nacionalinės teisės modulį. Šiai šaliai pajamas ir darbuotojų skaičių įvedate rankiniu būdu.",
    "html.62": "Paieška registre",
    "html.63": "verslo registrai yra nacionaliniai — bendrasis modulis jų nežino",
    "html.64": "funkcijas ir įmonės dydį nurodote rankiniu būdu",
    "html.66": "Subjekto identifikavimo numeris",
    "html.68": "Automatinis registro duomenų gavimas veikia tik šalims, turinčioms nacionalinės teisės modulį.",
    "html.76": "Metinės pajamos (EUR)",
    "html.78": "Pajamos iš elektroninių ryšių veiklos (EUR)",
    "html.79": "Laukas skirtas viešųjų elektroninių ryšių tinklų ar paslaugų teikėjams. Nacionalines ribas nustato valstybės narės teisė.",
    "html.80": "Vadovo mėnesinis atlyginimas (EUR)",
    "html.82": "Valiutos kursas",
    "html.83": "Direktyvoje baudų ribos išreikštos eurais. Perskaičiavimą į nacionalinę valiutą ir kursą nustato nacionalinė teisė — čia sumos pateikiamos eurais be perskaičiavimo.",
    "html.84": "Statusas išplaukia vien iš susijusių įmonių duomenų sumavimo, o subjekto informacinė sistema yra nepriklausoma (direktyvos 16 konstatuojamoji dalis — dėl taikymo sprendžia nacionalinė teisė)",
    "html.85": "Subjektas vykdo veiklą nacionalinio saugumo, viešojo saugumo, gynybos arba teisėsaugos srityse (direktyvos 2 straipsnio 7 dalis)",
    "html.91": "Atitikties Europos Parlamento ir Tarybos direktyvai (ES) 2022/2555 (TIS 2) ir Komisijos įgyvendinimo reglamentui (ES) 2024/2690 vertinimas — bendrasis modulis šalims, kurių nacionalinės teisės modulis dar neparengtas.",
    "html.94": "ar subjektas yra <strong>esminis</strong>, <strong>svarbus</strong>, ar nepatenka į direktyvos taikymo sritį",
    "html.daneZeSprawozdania": "pavadinimas, identifikavimo numeris, buveinės adresas",
    "html.rejestrMozliwy": "Registras {p0} yra viešas ir nemokamas — jo skaitymą galima papildyti; laukiame pull request’ų (žr. README).",
    "html.tytulNaglowka": "Atitikties TIS 2 direktyvai vertinimas",
    "html.zrodlaRecznie": "Šis modulis nepažįsta jūsų valstybės registrų — profilį užpildykite ranka. Metinė apyvarta lemia baudos viršutinę ribą, todėl nurodykite ją tiksliai.",
    "klasyfikacja.10": "Direktyvos (ES) 2022/2555 3 straipsnio 1 dalies c punktas (viešųjų elektroninių ryšių tinklų arba viešai prieinamų elektroninių ryšių paslaugų teikėjas, kuris yra bent vidutinė įmonė)",
    "klasyfikacja.11": "Direktyvos (ES) 2022/2555 3 straipsnio 2 dalis kartu su 2 straipsnio 2 dalies a punkto i papunkčiu (viešųjų elektroninių ryšių tinklų arba paslaugų teikėjas, kuris yra labai maža arba maža įmonė)",
    "klasyfikacja.12": "Direktyvos (ES) 2022/2555 3 straipsnio 1 dalies a punktas (valdomų saugumo paslaugų teikėjas, viršijantis vidutinės įmonės ribas)",
    "klasyfikacja.13": "Labai mažoms ir mažoms įmonėms dėl šios funkcijos direktyva netaikoma (2 straipsnio 1 dalis a contrario).",
    "klasyfikacja.15": "Direktyvos (ES) 2022/2555 3 straipsnio 1 dalies b punktas (kvalifikuotas patikimumo užtikrinimo paslaugų teikėjas) — nepriklausomai nuo įmonės dydžio",
    "klasyfikacja.16": "Direktyvos (ES) 2022/2555 3 straipsnio 2 dalis kartu su 2 straipsnio 2 dalies a punkto ii papunkčiu (nekvalifikuotas patikimumo užtikrinimo paslaugų teikėjas, kuris yra labai maža, maža arba vidutinė įmonė)",
    "klasyfikacja.18": "Direktyvos (ES) 2022/2555 3 straipsnio 2 dalis (regioninio lygmens viešojo administravimo subjektas, jei valstybė narė taip numato — 2 straipsnio 2 dalies f punkto ii papunktis)",
    "klasyfikacja.19": "Direktyvos (ES) 2022/2555 3 straipsnio 1 dalies f punktas (centrinės valdžios lygmens viešojo administravimo subjektas — 2 straipsnio 2 dalies f punkto i papunktis)",
    "klasyfikacja.2": "Ex ante ir ex post priežiūra (Direktyvos (ES) 2022/2555 32 straipsnis).",
    "klasyfikacja.20": "Direktyvos (ES) 2022/2555 3 straipsnio 2 dalis (regioninio lygmens viešojo administravimo subjektas — 2 straipsnio 2 dalies f punkto ii papunktis)",
    "klasyfikacja.21": "Vietos lygmens viešojo administravimo subjektų pareigų apimtį nustato nacionalinė teisė (direktyvos 2 straipsnio 5 dalies a punktas).",
    "klasyfikacja.22": "Valstybė narė gali netaikyti direktyvos subjektams, vykdantiems veiklą nacionalinio saugumo, viešojo saugumo, gynybos ar teisėsaugos srityse (direktyvos 2 straipsnio 7 dalis). Išimtis neveikia savaime — vertinimo rezultatą patikrinkite pagal nacionalinę teisę.",
    "klasyfikacja.23": "Subjektas atitinka ir esminio, ir svarbaus subjekto kriterijus. Jis yra esminis subjektas (direktyvos 3 straipsnio 1 dalis), o griežtesni reikalavimai taikomi visai direktyvos apimamai veiklai.",
    "klasyfikacja.25": "Subjektas yra esminis, todėl jam taikomas visas direktyvos 21 straipsnio 2 dalies priemonių katalogas bei ex ante ir ex post priežiūra — vertinimas apima visą klausimų rinkinį.",
    "klasyfikacja.26": "Kaip svarbiam subjektui jums taikomas tas pats 21 straipsnio 2 dalies priemonių katalogas, tačiau tik ex post priežiūra (33 straipsnis). Baudos riba mažesnė: 7 mln. EUR arba 1,4 % apyvartos (34 straipsnio 5 dalis). Lengvatas viešiesiems subjektams gali nustatyti nacionalinė teisė — šis modulis jų nežino.",
    "klasyfikacja.28": "Viešojo administravimo subjektų pareigos išplaukia iš direktyvos 2 straipsnio 2 dalies f punkto; tikslią jų apimtį, įskaitant vietos lygmenį ir švietimo įstaigas, nustato nacionalinė teisė (2 straipsnio 5 dalis).",
    "klasyfikacja.29": "Deklaruota, kad subjekto statusas išplaukia vien iš susijusių arba įmonių partnerių duomenų sumavimo ir kad subjekto informacinė sistema yra nepriklausoma. Direktyva tokią išimtį leidžia (16 konstatuojamoji dalis), tačiau dėl jos sprendžia nacionalinė teisė — modulis išimtį priima, bet ją reikia patikrinti pagal valstybės narės teisę ir dokumentuoti.",
    "klasyfikacja.4": "Tik ex post priežiūra — esant įrodymams, požymiams ar informacijai apie pažeidimą (Direktyvos (ES) 2022/2555 33 straipsnis).",
    "klasyfikacja.5": "Nepatenka į direktyvos taikymo sritį",
    "klasyfikacja.6": "Dėl nurodytos funkcijos pareigų pagal Direktyvą (ES) 2022/2555 nekyla.",
    "klasyfikacja.7": "Direktyvos (ES) 2022/2555 3 straipsnio 1 dalies a punktas (I priede nurodyto tipo subjektas, viršijantis vidutinės įmonės ribas)",
    "klasyfikacja.8": "Direktyvos (ES) 2022/2555 3 straipsnio 2 dalis (I priede nurodyto tipo subjektas, atitinkantis vidutinės įmonės kriterijus)",
    "klasyfikacja.9": "Labai mažoms ir mažoms įmonėms dėl šios funkcijos direktyva netaikoma (2 straipsnio 1 dalis a contrario).",
    "kreator.10": "Praėjusių metų pajamas įveskite rankiniu būdu.",
    "kreator.35": "<span class=\"text-secondary\">Finansinių ataskaitų skaitymas šiai šaliai neprieinamas.</span>",
    "kreator.37": "Finansinių ataskaitų skaitymas šiai šaliai neprieinamas — pajamas įveskite rankiniu būdu.",
    "kreator.56": "Taip — ES reglamentas tiesiogiai taikomas nuo 2024 m. lapkričio 7 d. visose valstybėse narėse ir neturi pereinamojo laikotarpio. Jo pagrindas yra",
    "kreator.57": ", kuri įgaliojo Komisiją nustatyti techninius ir metodinius reikalavimus reglamento 3 straipsnio 1 dalyje nurodytiems teikėjams. Direktyvos perkėlimo terminas baigėsi",
    "kreator.58": ", o nuo kada nacionalinė institucija gali skirti baudas, nustato nacionalinė teisė. Priedo techniniai reikalavimai (6 ir 9–13 skirsniai) yra privalomi tokie, kokie yra — jie nelaukia patikslinimo. Nukrypti galima tik nuo reikalavimų su sąlyga „kai tinkama“, ir tik su dokumentuotu pagrindimu.",
    "kreator.9": "Finansinės ataskaitos →",
    "kreator.przepisReg2690": "Direktyvos (ES) 2022/2555 21 straipsnio 5 dalis",
    "kreator.terminReg2690": "2024 m. spalio 17 d.",
    "punktacja.10": "Viešieji subjektai",
    "punktacja.4": "TIS 2 direktyva — 21 straipsnis",
    "punktacja.5": "TIS 2 direktyva — formalios pareigos",
    "punktacja.8": "Elektroniniai ryšiai",
    "punktacja.9": "TIS 2 direktyva — viešieji subjektai",
    "punktacja.skrotKsc": "TIS 2",
    "punktacja.skrotPke": "telekom.",
    "ue.cyt.akapit": "{p0} pastraipa",
    "ue.cyt.art": "{p0} str.",
    "ue.cyt.drugi": "antra",
    "ue.cyt.dyr": "Direktyvos (ES) 2022/2555 {p0}",
    "ue.cyt.i": "ir",
    "ue.cyt.laczenie": " ",
    "ue.cyt.lit": "{p0} p.",
    "ue.cyt.litery": "",
    "ue.cyt.pkt": "{p0} p.",
    "ue.cyt.rozdzielacz": "; ",
    "ue.cyt.rozp": "Reglamento (ES) 2024/2690 {p0}",
    "ue.cyt.ust": "{p0} d.",
    "ue.katalog.1": "Rizikos analizės ir informacinių sistemų saugumo politika",
    "ue.katalog.10": "Incidentų valdymas",
    "ue.katalog.11": "Incidentų valdymas — tai veiksmai ir procedūros, kuriais siekiama užkirsti kelią incidentui, jį aptikti, analizuoti ir suvaldyti arba į jį reaguoti ir po jo atkurti veiklą (6 straipsnio 8 punktas).",
    "ue.katalog.12": "Ar yra dokumentuota incidentų valdymo procedūra, apimanti aptikimą, analizę, suvaldymą, reagavimą ir atkūrimą?",
    "ue.katalog.13": "ISO/IEC 27001 A.5.24–A.5.26",
    "ue.katalog.14": "Ar procedūra leidžia laikytis pranešimo apie didelį incidentą terminų: ankstyvasis perspėjimas per 24 valandas, pranešimas apie incidentą per 72 valandas, galutinė ataskaita per vieną mėnesį?",
    "ue.katalog.15": "ISO/IEC 27001 A.5.24",
    "ue.katalog.16": "Ar subjektas turi kriterijus, pagal kuriuos incidentas laikomas dideliu, atitinkančius 23 straipsnio 3 dalį: didelis veiklos sutrikimas ar finansiniai nuostoliai arba didelė žala kitiems asmenims?",
    "ue.katalog.17": "ISO/IEC 27001 A.5.25",
    "ue.katalog.18": "Ar incidentai registruojami ir ar jų valdymo patirtis naudojama priemonėms tobulinti?",
    "ue.katalog.19": "ISO/IEC 27001 A.5.27",
    "ue.katalog.2": "Priemonės grindžiamos visų pavojų metodu (21 straipsnio 2 dalis). Jų proporcingumas vertinamas atsižvelgiant į rizikos lygį, subjekto dydį, incidentų tikimybę ir jų sunkumą (21 straipsnio 1 dalies antra pastraipa).",
    "ue.katalog.20": "Veiklos tęstinumas ir krizių valdymas",
    "ue.katalog.21": "Veiklos tęstinumas, pavyzdžiui, atsarginių kopijų valdymas ir veiklos atkūrimas po ekstremaliųjų įvykių, bei krizių valdymas.",
    "ue.katalog.22": "Ar yra veiklos tęstinumo planas, apimantis veiklos atkūrimą po ekstremaliojo įvykio?",
    "ue.katalog.23": "ISO/IEC 27001 A.5.29–A.5.30",
    "ue.katalog.24": "Ar atsarginės kopijos daromos, saugomos ir tikrinamos, ar jas galima atkurti?",
    "ue.katalog.25": "ISO/IEC 27001 A.8.13",
    "ue.katalog.26": "Ar subjektas turi krizių valdymo procedūras su apibrėžtais vaidmenimis ir komunikacijos kanalais?",
    "ue.katalog.27": "ISO/IEC 27001 A.5.29",
    "ue.katalog.28": "Ar tęstinumo ir atkūrimo planai periodiškai testuojami, o rezultatai dokumentuojami?",
    "ue.katalog.29": "ISO/IEC 27001 A.5.30",
    "ue.katalog.3": "Ar subjektas turi dokumentuotą rizikos analizės ir informacinių sistemų saugumo politiką, patvirtintą valdymo organo?",
    "ue.katalog.30": "Tiekimo grandinės saugumas",
    "ue.katalog.31": "Tiekimo grandinės saugumas, įskaitant su saugumu susijusius subjekto ir jo tiesioginių tiekėjų ar paslaugų teikėjų santykių aspektus. Subjektas atsižvelgia į kiekvienam tiekėjui būdingas pažeidžiamas vietas ir bendrą jo produktų bei kibernetinio saugumo praktikos kokybę (21 straipsnio 3 dalis).",
    "ue.katalog.32": "Ar subjektas tvarko tiesioginių tiekėjų ir paslaugų teikėjų sąrašą su jų reikšmės tinklų ir sistemų saugumui vertinimu?",
    "ue.katalog.33": "ISO/IEC 27001 A.5.19",
    "ue.katalog.34": "Ar renkantis priemones tiekėjams atsižvelgiama į kiekvienam iš jų būdingas pažeidžiamas vietas ir jų kibernetinio saugumo bei saugaus kūrimo praktikos kokybę?",
    "ue.katalog.35": "ISO/IEC 27001 A.5.19, A.5.21",
    "ue.katalog.36": "Ar sutartyse su tiekėjais yra saugumo reikalavimai ir pareiga pranešti apie incidentus ir pažeidžiamas vietas?",
    "ue.katalog.37": "ISO/IEC 27001 A.5.20",
    "ue.katalog.38": "Ar subjektas atsižvelgia į 22 straipsnyje nurodytų koordinuotų ypatingos svarbos tiekimo grandinių saugumo rizikos vertinimų rezultatus?",
    "ue.katalog.39": "ISO/IEC 27001 A.5.21",
    "ue.katalog.4": "ISO/IEC 27001 5.2, 6.1.2 punktai",
    "ue.katalog.40": "Saugumas įsigyjant, kuriant ir prižiūrint sistemas",
    "ue.katalog.41": "Saugumas įsigyjant, kuriant ir prižiūrint tinklų ir informacines sistemas, įskaitant pažeidžiamų vietų valdymą ir atskleidimą.",
    "ue.katalog.42": "Ar saugumo reikalavimai apibrėžiami prieš įsigyjant sistemą ar pradedant ją kurti ir patikrinami prieš diegimą?",
    "ue.katalog.43": "ISO/IEC 27001 A.8.25–A.8.29",
    "ue.katalog.44": "Ar yra pažeidžiamų vietų valdymo procesas: nustatymas, vertinimas, pašalinimas per nustatytą laiką?",
    "ue.katalog.45": "ISO/IEC 27001 A.8.8",
    "ue.katalog.46": "Ar subjektas turi pažeidžiamų vietų atskleidimo procedūrą, įskaitant kanalą trečiųjų šalių pranešimams gauti?",
    "ue.katalog.47": "Ar sistemų pakeitimai vyksta per kontroliuojamą pakeitimų valdymo procesą su poveikio saugumui vertinimu?",
    "ue.katalog.48": "ISO/IEC 27001 A.8.32",
    "ue.katalog.49": "Priemonių veiksmingumo vertinimas",
    "ue.katalog.5": "Ar rizikos analizė apima visus pavojus tinklų ir informacinėms sistemoms bei jų fizinei aplinkai, o ne tik kibernetines grėsmes?",
    "ue.katalog.50": "Kibernetinio saugumo rizikos valdymo priemonių veiksmingumo vertinimo politika ir procedūros.",
    "ue.katalog.51": "Ar yra dokumentuota priemonių veiksmingumo vertinimo politika, apibrėžianti apimtį, dažnumą ir metodus?",
    "ue.katalog.52": "ISO/IEC 27001 9.1 punktas",
    "ue.katalog.53": "Ar veiksmingumo vertinimai atliekami periodiškai ir ar jų rezultatai pateikiami valdymo organui?",
    "ue.katalog.54": "ISO/IEC 27001 9.2–9.3 punktai",
    "ue.katalog.55": "Ar nustatyti trūkumai lemia dokumentuotus taisomuosius veiksmus su atsakingu asmeniu ir terminu?",
    "ue.katalog.56": "ISO/IEC 27001 10.1 punktas",
    "ue.katalog.57": "Kibernetinė higiena ir mokymai",
    "ue.katalog.58": "Pagrindinė kibernetinės higienos praktika ir kibernetinio saugumo mokymai. Valdymo organo nariai reguliariai dalyvauja mokymuose (20 straipsnio 2 dalis).",
    "ue.katalog.59": "Ar subjektas taiko pagrindinę kibernetinės higienos praktiką: atnaujinimus, slaptažodžių valdymą, teisių ribojimą, apsaugą nuo kenkimo programinės įrangos?",
    "ue.katalog.6": "ISO/IEC 27001 6.1.2 punktas",
    "ue.katalog.60": "ISO/IEC 27001 A.8.7, A.8.8",
    "ue.katalog.61": "Ar darbuotojai dalyvauja kibernetinio saugumo mokymuose, pritaikytuose jų vaidmeniui, ir ar dalyvavimas dokumentuojamas?",
    "ue.katalog.62": "ISO/IEC 27001 A.6.3",
    "ue.katalog.63": "Ar valdymo organo nariai reguliariai dalyvauja mokymuose, leidžiančiuose nustatyti riziką ir įvertinti rizikos valdymo praktiką?",
    "ue.katalog.64": "ISO/IEC 27001 7.2 punktas",
    "ue.katalog.65": "Kriptografija ir šifravimas",
    "ue.katalog.66": "Kriptografijos ir, kai tinkama, šifravimo naudojimo politika ir procedūros.",
    "ue.katalog.67": "Ar yra kriptografijos politika, apibrėžianti, kurie duomenys ir kanalai šifruojami ir kokiais algoritmais?",
    "ue.katalog.68": "ISO/IEC 27001 A.8.24",
    "ue.katalog.69": "Ar kriptografiniai raktai valdomi per visą gyvavimo ciklą: generavimas, platinimas, saugojimas, keitimas, panaikinimas?",
    "ue.katalog.7": "Ar renkantis priemones atsižvelgiama į naujausius technikos laimėjimus, atitinkamus Europos ir tarptautinius standartus bei įgyvendinimo sąnaudas?",
    "ue.katalog.70": "Žmogiškieji ištekliai, prieigos kontrolė ir turto valdymas",
    "ue.katalog.71": "Žmogiškųjų išteklių saugumas, prieigos kontrolės politika ir turto valdymas.",
    "ue.katalog.72": "Ar subjektas tvarko atnaujintą turto sąrašą su priskirtais savininkais ir klasifikacija?",
    "ue.katalog.73": "ISO/IEC 27001 A.5.9, A.5.12",
    "ue.katalog.74": "Ar yra prieigos kontrolės politika, grindžiama mažiausių teisių principu, su periodine teisių peržiūra?",
    "ue.katalog.75": "ISO/IEC 27001 A.5.15, A.5.18",
    "ue.katalog.76": "Ar priimant į darbą, keičiant pareigas ir darbuotojui išeinant taikomos saugumo procedūros, įskaitant teisių panaikinimą ir turto grąžinimą?",
    "ue.katalog.77": "ISO/IEC 27001 A.6.1–A.6.5",
    "ue.katalog.78": "Ar privilegijuota prieiga ribojama, registruojama ir peržiūrima?",
    "ue.katalog.79": "ISO/IEC 27001 A.8.2",
    "ue.katalog.8": "ISO/IEC 27001 6.1.3 punktas",
    "ue.katalog.80": "Daugiaveiksnis tapatumo nustatymas ir apsaugoti ryšiai",
    "ue.katalog.81": "Kai tinkama — daugiaveiksnis arba nuolatinis tapatumo nustatymas, apsaugoti balso, vaizdo ir tekstiniai ryšiai bei apsaugotos skubaus ryšio sistemos subjekto viduje.",
    "ue.katalog.82": "Ar daugiaveiksnis arba nuolatinis tapatumo nustatymas naudojamas ten, kur tai pagrindžia rizikos analizė, ypač nuotolinei prieigai ir privilegijuotoms paskyroms?",
    "ue.katalog.83": "ISO/IEC 27001 A.8.5",
    "ue.katalog.84": "Ar darbo tikslais naudojami balso, vaizdo ir tekstiniai ryšiai yra apsaugoti?",
    "ue.katalog.85": "ISO/IEC 27001 A.8.20",
    "ue.katalog.86": "Ar subjektas turi apsaugotą vidinę skubaus ryšio sistemą, nepriklausomą nuo pagrindinės infrastruktūros?",
    "ue.katalog.9": "Ar saugumo lygis dokumentuotas kaip atitinkantis kylančią riziką, su pagrindimu, kuriame atsižvelgta į subjekto dydį bei incidentų socialinį ir ekonominį poveikį?",
    "ue.kierownictwo.1": "Esminio arba svarbaus subjekto valdymo organas — bendrovėje valdyba. Direktyva šios sąvokos neapibrėžia; jos apimtis konkrečioje šalyje išplaukia iš nacionalinės teisės.",
    "ue.kierownictwo.10": "Nustatyti subjekto statusą ir pasirūpinti registracija",
    "ue.kierownictwo.11": "Nustatymas, ar subjektas yra esminis, ar svarbus, ir registracijos duomenų pateikimas kompetentingai institucijai. Tvarką ir terminą nustato nacionalinė teisė.",
    "ue.kierownictwo.12": "Įdiegti rizikos analizę ir saugumo politiką",
    "ue.kierownictwo.13": "Visų pavojų metodu grindžiamos priemonės, proporcingos rizikos lygiui, subjekto dydžiui ir incidentų sunkumui.",
    "ue.kierownictwo.14": "Sukurti incidentų valdymą ir pranešimą apie juos",
    "ue.kierownictwo.15": "Incidentų valdymo procedūra ir gebėjimas laikytis 24 valandų, 72 valandų ir vieno mėnesio terminų.",
    "ue.kierownictwo.16": "24 val. / 72 val. / mėnuo nuo aptikimo",
    "ue.kierownictwo.17": "Užtikrinti veiklos tęstinumą",
    "ue.kierownictwo.18": "Tęstinumo planas, atsarginės kopijos, veiklos atkūrimas po ekstremaliųjų įvykių, krizių valdymas.",
    "ue.kierownictwo.19": "Sutvarkyti tiekimo grandinę",
    "ue.kierownictwo.2": "Valdymo organo atsakomybė nedaro poveikio nacionalinėms taisyklėms dėl viešųjų institucijų ir pareigūnų atsakomybės (20 straipsnio 1 dalies antra pastraipa).",
    "ue.kierownictwo.20": "Tiekėjų sąrašas, jų pažeidžiamų vietų ir praktikos vertinimas, saugumo reikalavimai sutartyse.",
    "ue.kierownictwo.21": "Įdiegti prieigos kontrolę ir turto valdymą",
    "ue.kierownictwo.22": "Turto sąrašas, mažiausių teisių principas, teisių peržiūros, daugiaveiksnis tapatumo nustatymas ten, kur tai pagrindžia rizika.",
    "ue.kierownictwo.23": "Matuoti priemonių veiksmingumą",
    "ue.kierownictwo.24": "Veiksmingumo vertinimo politika ir procedūros, periodinės peržiūros, taisomieji veiksmai.",
    "ue.kierownictwo.25": "Patvirtinti",
    "ue.kierownictwo.26": "kibernetinio saugumo rizikos valdymo priemones (20 straipsnio 1 dalis)",
    "ue.kierownictwo.27": "rizikos analizės ir sistemų saugumo politiką",
    "ue.kierownictwo.28": "įgyvendinimo biudžetą ir vaidmenis",
    "ue.kierownictwo.29": "Prižiūrėti",
    "ue.kierownictwo.3": "Ar pareigų pavedimas kitam asmeniui panaikina atsakomybę, sprendžia nacionalinė teisė. Lenkijoje nepanaikina (Nacionalinės kibernetinio saugumo sistemos įstatymo 8c straipsnio 3 dalis).",
    "ue.kierownictwo.30": "patvirtintų priemonių įgyvendinimą (20 straipsnio 1 dalis)",
    "ue.kierownictwo.31": "veiksmingumo vertinimo rezultatus (21 straipsnio 2 dalies f punktas)",
    "ue.kierownictwo.32": "pranešimo apie incidentus terminų laikymąsi (23 straipsnis)",
    "ue.kierownictwo.33": "Dokumentuoti",
    "ue.kierownictwo.34": "patvirtinimo sprendimus ir peržiūras",
    "ue.kierownictwo.35": "dalyvavimą mokymuose (20 straipsnio 2 dalis)",
    "ue.kierownictwo.36": "Valdymo organo narys",
    "ue.kierownictwo.37": "priemonių patvirtinimas, priežiūra, sprendimai, biudžetas",
    "ue.kierownictwo.38": "Projekto vadovas",
    "ue.kierownictwo.39": "įgyvendinimo koordinavimas, grafikas, būklė ir įrodymai",
    "ue.kierownictwo.4": "Patvirtinti kibernetinio saugumo rizikos valdymo priemones",
    "ue.kierownictwo.40": "IT / kibernetinis saugumas",
    "ue.kierownictwo.41": "rizikos analizė, techninės priemonės, incidentų valdymas",
    "ue.kierownictwo.42": "Teisės skyrius / atitiktis",
    "ue.kierownictwo.5": "Valdymo organas patvirtina priemones, kurių imtasi siekiant laikytis 21 straipsnio. Tai organo, o ne IT skyriaus sprendimas — be jo priemonės neturi pagrindo.",
    "ue.kierownictwo.6": "Prižiūrėti priemonių įgyvendinimą",
    "ue.kierownictwo.7": "Įgyvendinimo priežiūra yra valdymo organo pareiga. Vykdymą galima pavesti, priežiūros — ne.",
    "ue.kierownictwo.8": "Reguliariai dalyvauti mokymuose",
    "ue.kierownictwo.9": "Valdymo organo nariai reguliariai dalyvauja mokymuose, kad įgytų pakankamai žinių rizikai nustatyti ir rizikos valdymo praktikai bei jos poveikiui subjekto paslaugoms įvertinti.",
    "ue.kierownictwo.daneRejestracyjne": "registracijos duomenys ir jų atnaujinimas (3 straipsnio 4 ir 5 dalys)",
    "ue.meta.1": "Viršija procentinis variantas: {p0} % apyvartos yra daugiau nei {p1} mln. EUR.",
    "ue.meta.10": "Direktyva pareigų įmonėms tiesiogiai nenustato — tai daro nacionalinis įstatymas, kurį valstybė narė turėjo priimti iki 2024 m. spalio 17 d. Šis modulis rodo reikalavimus taip, kaip jie suformuluoti direktyvoje, nes pasirinktos šalies nacionalinės teisės modulis dar neparengtas arba šalis direktyvos neperkėlė.",
    "ue.meta.11": "Pareigos pagal direktyvą",
    "ue.meta.12": "Subjektų sąrašas — iki 2025 m. balandžio 17 d.",
    "ue.meta.13": "Valstybės narės iki 2025 m. balandžio 17 d. turėjo sudaryti esminių ir svarbių subjektų sąrašą ir reikalauti, kad subjektai pateiktų registracijos duomenis.",
    "ue.meta.14": "Reglamentas (ES) 2024/2690",
    "ue.meta.15": "Tiesiogiai taikomas nuo 2024 m. lapkričio 7 d.",
    "ue.meta.16": "Įgyvendinimo reglamentas tiesiogiai taikomas visose valstybėse narėse, nepriklausomai nuo direktyvos perkėlimo būklės. Jis skirtas jo 1 straipsnyje nurodytiems subjektams: DNS, aukščiausio lygio domenų, debesijos, duomenų centrų, turinio teikimo tinklų, valdomų paslaugų ir patikimumo užtikrinimo paslaugų teikėjams.",
    "ue.meta.17": "Reglamento (ES) 2024/2690 16 straipsnis",
    "ue.meta.18": "Ne mažiau kaip 10 000 000 EUR arba ne mažiau kaip 2 % įmonės bendros pasaulinės metinės apyvartos praėjusiais finansiniais metais — taikoma didesnė suma. Tai minimali viršutinė riba: nacionalinė teisė gali ją padidinti.",
    "ue.meta.19": "Ne mažiau kaip 7 000 000 EUR arba 1,4 % bendros pasaulinės metinės apyvartos — taikoma didesnė suma. Minimali viršutinė riba.",
    "ue.meta.2": "Viršija fiksuota suma: {p0} mln. EUR yra daugiau nei {p1} % apyvartos.",
    "ue.meta.20": "Direktyva nenumato atskiros baudos už kvalifikuotą pažeidimą — tai kai kurių valstybių narių nacionalinės teisės konstrukcija.",
    "ue.meta.21": "Valstybės narės gali numatyti periodines baudas, siekdamos priversti nutraukti pažeidimą. Dydį nustato nacionalinė teisė.",
    "ue.meta.22": "Valdymo organas patvirtina rizikos valdymo priemones, prižiūri jų įgyvendinimą ir gali būti traukiamas atsakomybėn už 21 straipsnio pažeidimą. Šios atsakomybės taisykles ir apimtį nustato nacionalinė teisė.",
    "ue.meta.23": "Valdymo organas patvirtina kibernetinio saugumo rizikos valdymo priemones (20 straipsnio 1 dalis).",
    "ue.meta.24": "Valdymo organas prižiūri šių priemonių įgyvendinimą (20 straipsnio 1 dalis).",
    "ue.meta.25": "Valdymo organo nariai reguliariai dalyvauja mokymuose (20 straipsnio 2 dalis).",
    "ue.meta.26": "Esminio subjekto atveju institucija gali prašyti laikinai uždrausti eiti vadovaujamas pareigas (32 straipsnio 5 dalies b punktas).",
    "ue.meta.27": "Minimalią viršutinę ribą nustato direktyva",
    "ue.meta.28": "Lyginamos dvi vertės: fiksuota suma eurais ir įmonės bendros pasaulinės metinės apyvartos praėjusiais finansiniais metais procentas. Didesnė iš jų yra viršutinė riba, kurią valstybė narė turi numatyti bent jau minimaliai. Nacionalinė teisė gali ją padidinti.",
    "ue.meta.29": "Sumą neviršijant ribos nustato nacionalinė institucija",
    "ue.meta.3": "Direktyvos riba viršija subjekto metinę apyvartą {p0} kartų. 34 straipsnio 1 dalis reikalauja, kad bauda būtų proporcinga konkretaus atvejo aplinkybėms — tai viršutinė riba, o ne tikėtina bauda.",
    "ue.meta.30": "Bauda turi būti veiksminga, proporcinga ir atgrasanti pagal konkretaus atvejo aplinkybes. Institucija atsižvelgia bent į 32 straipsnio 7 dalies kriterijus: pažeidimo sunkumą ir trukmę, ankstesnius pažeidimus, padarytą žalą, tyčią, taisomąsias priemones ir bendradarbiavimą.",
    "ue.meta.31": "Viršutinė riba gali daug kartų viršyti metinę apyvartą — tai viršutinė riba, o ne tikėtina suma. Nacionalinius minimumus, periodines baudas ir baudų nustatymo tvarką nustato valstybės narės įstatymas.",
    "ue.meta.32": "Sprendžiant, ar skirti administracinę baudą, ir nustatant jos dydį, kiekvienu konkrečiu atveju deramai atsižvelgiama bent į 32 straipsnio 7 dalyje išvardytus elementus.",
    "ue.meta.33": "pažeidimo sunkumas ir pažeistų nuostatų svarba — sunkiais bet kuriuo atveju laikomi: pakartotiniai pažeidimai, nepranešimas apie didelius incidentus ar jų nepašalinimas, trūkumų nepašalinimas priešingai privalomiems nurodymams, trukdymas auditams ar stebėsenai, neteisingos ar labai netikslios informacijos pateikimas",
    "ue.meta.34": "bet kokie ankstesni reikšmingi subjekto pažeidimai",
    "ue.meta.35": "padaryta turtinė ar neturtinė žala, įskaitant finansinius nuostolius, poveikį kitoms paslaugoms ir paveiktų naudotojų skaičių",
    "ue.meta.36": "tyčinis ar neatsargus pažeidimo pobūdis",
    "ue.meta.37": "priemonės, kurių imtasi žalai išvengti ar sumažinti",
    "ue.meta.38": "patvirtintų elgesio kodeksų ar sertifikavimo mechanizmų laikymasis",
    "ue.meta.39": "bendradarbiavimo su kompetentingomis institucijomis laipsnis",
    "ue.meta.4": "Europos Parlamento ir Tarybos direktyva (ES) 2022/2555 (TIS 2)",
    "ue.meta.40": "Direktyva aiškiai nenumato atleidimo nuo baudos — ar ir kada tai galima, sprendžia nacionalinė teisė.",
    "ue.meta.41": "Nuo šios datos valstybės narės turi taikyti nacionalines direktyvą įgyvendinančias nuostatas. Konkreti data, nuo kurios institucija gali skirti baudą, išplaukia iš nacionalinės teisės.",
    "ue.meta.42": "TIS 2 direktyvos įsigaliojimas",
    "ue.meta.43": "Dvidešimtą dieną po paskelbimo Oficialiajame leidinyje.",
    "ue.meta.44": "Direktyvos perkėlimo terminas",
    "ue.meta.45": "Iki šios datos valstybės narės turėjo priimti ir paskelbti nacionalines nuostatas.",
    "ue.meta.46": "Nacionalinių nuostatų taikymas ir TIS 1 panaikinimas",
    "ue.meta.47": "Nuo šios datos valstybės narės taiko įgyvendinančias nuostatas; Direktyva (ES) 2016/1148 panaikinama.",
    "ue.meta.48": "Reglamento (ES) 2024/2690 taikymas",
    "ue.meta.49": "Įgyvendinimo reglamentas tiesiogiai taikomas nuo dvidešimtos dienos po paskelbimo.",
    "ue.meta.5": "ES OL L 333, 2022 12 27",
    "ue.meta.50": "Esminių ir svarbių subjektų sąrašas",
    "ue.meta.51": "Iki šios datos valstybės narės sudaro sąrašą; subjektai institucijoms pateikia registracijos duomenis.",
    "ue.meta.52": "Pirmoji Komisijos atliekama direktyvos peržiūra",
    "ue.meta.53": "Komisija peržiūri direktyvos veikimą ir pateikia ataskaitą.",
    "ue.meta.54": "Ankstyvasis perspėjimas apie didelį incidentą",
    "ue.meta.55": "24 valandos nuo sužinojimo",
    "ue.meta.56": "Pranešimas apie didelį incidentą",
    "ue.meta.57": "72 valandos nuo sužinojimo",
    "ue.meta.58": "Galutinė ataskaita",
    "ue.meta.59": "mėnuo nuo pranešimo apie incidentą",
    "ue.meta.6": "Komisijos įgyvendinimo reglamentas (ES) 2024/2690",
    "ue.meta.60": "Patikimumo užtikrinimo paslaugų teikėjo pranešimas apie incidentą",
    "ue.meta.61": "Direktyvos (ES) 2022/2555 21 straipsnio 5 dalis; Reglamento (ES) 2024/2690 1 ir 2 straipsniai",
    "ue.meta.62": "Be apyvartos duomenų viršutinė riba yra direktyvoje nurodyta fiksuota suma.",
    "ue.meta.63": "34 straipsnio 4 ir 5 dalių ribos yra minimalios („ne mažiau kaip“) — nacionalinė teisė gali numatyti didesnes. Sumos eurais, be perskaičiavimo į nacionalinę valiutą.",
    "ue.meta.64": "Valstybės narės kompetentinga institucija",
    "ue.meta.65": "Valdymo organas gali būti traukiamas atsakomybėn už 21 straipsnio pažeidimą. Apimtį ir tvarką nustato nacionalinė teisė — šis modulis jų nežino.",
    "ue.meta.66": "Vadovybės asmeninės atsakomybės apimtis išplaukia iš nacionalinio įstatymo. Lenkijoje tai iki 300 % atlyginimo (Nacionalinės kibernetinio saugumo sistemos įstatymo 73a straipsnio 4 dalis); kitos valstybės narės tai reguliuoja kitaip.",
    "ue.meta.7": "ES OL L, 2024/2690",
    "ue.meta.8": "Direktyva (ES) 2022/2555",
    "ue.meta.9": "Perkėlimo terminas baigėsi 2024 m. spalio 17 d.",
    "ue.moduly.1": "apie {p0} min.",
    "ue.moduly.10": "Dešimt sričių iš 21 straipsnio 2 dalies a–j punktų: nuo rizikos politikos iki daugiaveiksnio tapatumo nustatymo. Už pažeidimą gresia bauda pagal 34 straipsnį. Vertinimas pagal brandos skalę.",
    "ue.moduly.11": "Reglamentas 2024/2690 — valdymas ir procesai",
    "ue.moduly.12": "Priedo 1–5 ir 7–8 skirsniai: politika, rizikos valdymas, incidentų valdymas, veiklos tęstinumas, tiekimo grandinė, veiksmingumo vertinimas, kibernetinė higiena. Tiesiogiai taikomas nuo 2024 m. lapkričio 7 d.",
    "ue.moduly.13": "Reglamentas 2024/2690 — techniniai reikalavimai",
    "ue.moduly.14": "Priedo 6 ir 9–13 skirsniai: sistemų įsigijimas ir kūrimas, kriptografija, žmogiškųjų išteklių saugumas, prieigos kontrolė, turto valdymas, fizinis ir aplinkos saugumas.",
    "ue.moduly.2": "apie {p0} val. {p1} min.",
    "ue.moduly.3": "apie {p0} val.",
    "ue.moduly.4": "mažiau nei minutė",
    "ue.moduly.5": "Greitas rizikos vertinimas",
    "ue.moduly.6": "Bendrieji klausimai iš visų direktyvos sričių. Kiekvienas lemia visą temų grupę. Leidžia įvertinti atsilikimo mastą neperėjus viso klausimyno.",
    "ue.moduly.7": "Pareigos pagal direktyvą",
    "ue.moduly.8": "Registracijos duomenys, pranešimas apie incidentus per 24 ir 72 valandas, valdymo organo pareigos, pasirengimas priežiūrai. Patikrinama pagal dokumentus, be techninės analizės.",
    "ue.moduly.9": "Rizikos valdymo priemonės — 21 straipsnio 2 dalis",
    "ue.obowiazki.1": "Registracijos duomenys subjektų sąrašui",
    "ue.obowiazki.10": "Pranešimas apie didelius incidentus",
    "ue.obowiazki.11": "Subjektas apie didelius incidentus praneša CSIRT arba kompetentingai institucijai trimis etapais: ankstyvasis perspėjimas, pranešimas apie incidentą, galutinė ataskaita. Terminai skaičiuojami nuo sužinojimo apie incidentą.",
    "ue.obowiazki.12": "Ar subjektas geba per 24 valandas nuo sužinojimo apie didelį incidentą pateikti ankstyvąjį perspėjimą, nurodydamas, ar incidentas įtariamai sukeltas neteisėtų veiksmų ir ar jis gali turėti tarpvalstybinį poveikį?",
    "ue.obowiazki.13": "24 valandos nuo sužinojimo",
    "ue.obowiazki.14": "Ar subjektas geba per 72 valandas pateikti pranešimą apie incidentą su pirminiu sunkumo ir poveikio vertinimu bei užvaldymo rodikliais?",
    "ue.obowiazki.15": "72 valandos nuo sužinojimo",
    "ue.obowiazki.16": "Ar subjektas ne vėliau kaip per mėnesį nuo pranešimo pateikia galutinę ataskaitą su incidento aprašymu, grėsmės tipu, poveikio mažinimo priemonėmis ir tarpvalstybiniu poveikiu?",
    "ue.obowiazki.17": "mėnuo nuo pranešimo",
    "ue.obowiazki.18": "Ar subjektas informuoja savo paslaugų gavėjus apie didelius incidentus, galinčius neigiamai paveikti tų paslaugų teikimą?",
    "ue.obowiazki.19": "Ar subjektas informuoja paslaugų gavėjus apie didelę kibernetinę grėsmę ir apie priemones, kurių gavėjai gali imtis?",
    "ue.obowiazki.2": "Valstybės narės sudaro esminių ir svarbių subjektų sąrašą ir reikalauja, kad subjektai pateiktų registracijos duomenis. Tvarką, terminą ir portalą nustato nacionalinė teisė.",
    "ue.obowiazki.20": "Jei subjektas yra patikimumo užtikrinimo paslaugų teikėjas — ar jis apie didelius incidentus praneša per 24 valandas nuo sužinojimo?",
    "ue.obowiazki.21": "taikoma patikimumo užtikrinimo paslaugų teikėjams",
    "ue.obowiazki.22": "Valdymo organas",
    "ue.obowiazki.23": "Valdymo organas patvirtina rizikos valdymo priemones, prižiūri jų įgyvendinimą ir gali būti traukiamas atsakomybėn. Organo nariai reguliariai dalyvauja mokymuose.",
    "ue.obowiazki.24": "Ar valdymo organas formaliai patvirtino kibernetinio saugumo rizikos valdymo priemones, kurių imtasi siekiant laikytis 21 straipsnio?",
    "ue.obowiazki.25": "Ar valdymo organas dokumentuotai prižiūri šių priemonių įgyvendinimą — pavyzdžiui, per periodines ataskaitas ir peržiūras?",
    "ue.obowiazki.26": "Ar valdymo organo nariai reguliariai dalyvauja mokymuose, leidžiančiuose nustatyti riziką ir įvertinti rizikos valdymo praktiką, ir ar dalyvavimas dokumentuojamas?",
    "ue.obowiazki.27": "Pasirengimas priežiūros priemonėms",
    "ue.obowiazki.28": "Esminiam subjektui taikoma ex ante ir ex post priežiūra, svarbiam — tik ex post. Institucija gali reikalauti informacijos, politikos įgyvendinimo įrodymų ir auditų rezultatų.",
    "ue.obowiazki.29": "Ar subjektas geba institucijos prašymu pateikti kibernetinio saugumo politikos įgyvendinimo įrodymus, įskaitant saugumo auditų rezultatus?",
    "ue.obowiazki.3": "Ar subjektas nustatė, ar jis yra esminis, ar svarbus subjektas, pagal I arba II priedo sektorių ir įmonės dydį?",
    "ue.obowiazki.30": "Ar subjektas geba institucijos prašymu pateikti duomenis, dokumentus ir informaciją, reikalingus priežiūros užduotims atlikti?",
    "ue.obowiazki.31": "Ar esminis subjektas pasirengęs institucijos arba nepriklausomo subjekto atliekamam saugumo auditui savo lėšomis?",
    "ue.obowiazki.4": "Ar subjektas kompetentingai institucijai pateikė registracijos duomenis: pavadinimą, adresą ir kontaktinius duomenis, sektorių ir subsektorių, valstybių narių, kuriose teikia paslaugas, sąrašą?",
    "ue.obowiazki.5": "Kontaktiniai duomenys apima el. pašto adresus, IP adresų intervalus ir telefono numerius. Nacionalinį registracijos terminą ir portalą nustato valstybės narės teisė.",
    "ue.obowiazki.6": "Ar yra registracijos duomenų atnaujinimo nepagrįstai nedelsiant po jų pasikeitimo procedūra?",
    "ue.obowiazki.7": "Direktyva reikalauja atnaujinti nepagrįstai nedelsiant; konkretus terminas — pavyzdžiui, 14 dienų Lenkijoje — išplaukia iš nacionalinės teisės.",
    "ue.obowiazki.8": "Jei subjektas yra DNS paslaugų teikėjas, aukščiausio lygio domenų vardų registras, debesijos, duomenų centro, CDN, valdomų paslaugų teikėjas, elektroninė prekyvietė, paieškos sistema ar socialinis tinklas — ar jis pateikė papildomus 27 straipsnio duomenis, įskaitant pagrindinės buveinės Sąjungoje adresą?",
    "ue.obowiazki.9": "taikoma 26 straipsnio 1 dalyje nurodytiems subjektams",
    "ue.role.1": "Valstybės narės kompetentinga institucija",
    "ue.role.10": "Duomenų centro paslaugos: kolokacija, infrastruktūros talpinimas ir susijusios paslaugos.",
    "ue.role.11": "Duomenų centrai",
    "ue.role.12": "Esminis subjektas, viršijantis vidutinės įmonės ribą (3 straipsnio 1 dalies a punktas), svarbus — esant vidutiniam dydžiui (3 straipsnio 2 dalis). Mažesnis nei vidutinis — nepatenka į taikymo sritį, nebent valstybė narė subjektą nurodo pagal 2 straipsnio 2 dalies b–e punktus. Taikomas Reglamentas 2024/2690.",
    "ue.role.13": "Interneto duomenų srautų mainų taško teikėjas",
    "ue.role.14": "Infrastruktūra, leidžianti keistis duomenų srautais tarp nepriklausomų tinklų.",
    "ue.role.15": "Interneto duomenų srautų mainų taškai",
    "ue.role.16": "Klasifikacija pagal dydį (3 straipsnio 1 dalies a punktas ir 2 dalis). Reglamentas 2024/2690 duomenų srautų mainų taškams netaikomas — reglamento 1 straipsnyje pateiktas baigtinis adresatų sąrašas.",
    "ue.role.17": "DNS paslaugų teikėjas",
    "ue.role.18": "Domenų vardų sprendimo paslaugos, išskyrus šakninių vardų serverių operatorius.",
    "ue.role.19": "Domenų vardų sistema",
    "ue.role.2": "kompetentinga institucija",
    "ue.role.20": "Esminis subjektas nepriklausomai nuo dydžio (3 straipsnio 1 dalies b punktas). Taikomas Reglamentas 2024/2690.",
    "ue.role.21": "Aukščiausio lygio domenų vardų registras",
    "ue.role.22": "Aukščiausio lygio domeno registro tvarkymas.",
    "ue.role.23": "Esminis subjektas nepriklausomai nuo dydžio (3 straipsnio 1 dalies b punktas). Papildomai — 28 straipsnio pareigos dėl registracijos duomenų. Taikomas Reglamentas 2024/2690.",
    "ue.role.24": "Debesijos kompiuterijos paslaugų teikėjas",
    "ue.role.25": "Debesijos kompiuterijos paslaugos: infrastruktūra, platforma, programinė įranga kaip paslauga.",
    "ue.role.26": "Debesijos kompiuterijos paslaugos",
    "ue.role.27": "Klasifikacija pagal dydį (3 straipsnio 1 dalies a punktas ir 2 dalis). Taikomas Reglamentas 2024/2690.",
    "ue.role.28": "Turinio teikimo tinklo teikėjas",
    "ue.role.29": "Paskirstytų serverių tinklas, teikiantis turinį ir paslaugas galutiniams naudotojams.",
    "ue.role.3": "nustatyta nacionalinės teisės; iki nacionalinio modulio įdiegimo įrankis konkrečios institucijos nenurodo",
    "ue.role.30": "Turinio teikimo tinklai",
    "ue.role.31": "Patikimumo užtikrinimo paslaugų teikėjas",
    "ue.role.32": "Patikimumo užtikrinimo paslaugos pagal Reglamentą (ES) Nr. 910/2014: parašai, spaudai, laiko žymos, sertifikatai.",
    "ue.role.33": "Patikimumo užtikrinimo paslaugos",
    "ue.role.34": "Direktyva taikoma nepriklausomai nuo dydžio (2 straipsnio 2 dalies a punkto ii papunktis). Kvalifikuotas teikėjas yra esminis subjektas nepriklausomai nuo dydžio (3 straipsnio 1 dalies b punktas); nekvalifikuotas yra esminis, jei viršija vidutinės įmonės ribą, kitu atveju — svarbus. Taikomas Reglamentas 2024/2690.",
    "ue.role.35": "Valdomų paslaugų teikėjas",
    "ue.role.36": "Kliento IRT infrastruktūros valdymas: diegimas, priežiūra, palaikymas, sistemų administravimas.",
    "ue.role.37": "IRT paslaugų valdymas (B2B)",
    "ue.role.38": "Valdomos paslaugos",
    "ue.role.39": "Valdomų saugumo paslaugų teikėjas",
    "ue.role.4": "Viešųjų elektroninių ryšių tinklų arba viešai prieinamų elektroninių ryšių paslaugų teikėjas",
    "ue.role.40": "Valdomos kibernetinio saugumo paslaugos: stebėsena, reagavimas į incidentus, testavimas, konsultavimas.",
    "ue.role.41": "Valdomos saugumo paslaugos",
    "ue.role.42": "Direktyva klasifikuoja pagal dydį (3 straipsnio 1 dalies a punktas ir 2 dalis). Valstybės narės gali ribą sugriežtinti — Lenkija MSSP laiko esminiu subjektu jau nuo mažos įmonės; šis modulis taiko tik direktyvos taisyklę. Taikomas Reglamentas 2024/2690.",
    "ue.role.5": "Viešųjų elektroninių ryšių tinklų teikimas arba viešai prieinamų elektroninių ryšių paslaugų, įskaitant interneto prieigą, teikimas.",
    "ue.role.6": "Skaitmeninė infrastruktūra",
    "ue.role.7": "Elektroniniai ryšiai",
    "ue.role.8": "Direktyva taikoma nepriklausomai nuo dydžio (2 straipsnio 2 dalies a punkto i papunktis). Vidutinė ar didesnė įmonė yra esminis subjektas (3 straipsnio 1 dalies c punktas), labai maža ir maža — svarbus (3 straipsnio 2 dalis). Nacionalinis elektroninių ryšių įstatymas gali nustatyti papildomas pareigas — šiame modulyje jų nėra.",
    "ue.role.9": "Duomenų centro paslaugų teikėjas",
    "ue.role.podstawaArt3b": "Direktyvos (ES) 2022/2555 3 straipsnio 1 dalies b punktas",
    "ue.zaslepki.1": "Europos Parlamento ir Tarybos direktyva (ES) 2022/2555 (TIS 2)",
    "ue.zaslepki.10": "Ar dalis subjektų įrašoma ex officio, sprendžia nacionalinė teisė.",
    "ue.zaslepki.11": "Nustatykite, ar jums taikoma direktyva",
    "ue.zaslepki.12": "I arba II priedo sektorius ir įmonės dydis. Šią dalį atlieka subjekto profilis šiame įrankyje.",
    "ue.zaslepki.13": "Nustatykite savo šalies kompetentingą instituciją",
    "ue.zaslepki.14": "Kiekviena šalis paskiria kompetentingą instituciją (8 straipsnio 1 dalis). Atnaujintą sąrašą tvarko ENISA ir Komisija.",
    "ue.zaslepki.15": "Pateikite registracijos duomenis",
    "ue.zaslepki.16": "Pavadinimas, adresas ir kontaktiniai duomenys, sektorius ir subsektorius, paslaugų teikimo šalys (3 straipsnio 4 dalis). Tvarka pagal nacionalinę teisę.",
    "ue.zaslepki.17": "Atnaujinkite duomenis nepagrįstai nedelsdami",
    "ue.zaslepki.18": "Kiekvienas registracijos duomenų pasikeitimas reikalauja atnaujinimo (3 straipsnio 5 dalis).",
    "ue.zaslepki.19": "adresas ir aktualūs kontaktiniai duomenys: el. pašto adresai, IP adresų intervalai, telefono numeriai",
    "ue.zaslepki.2": "ES OL L 333, 2022 12 27, p. 80",
    "ue.zaslepki.20": "I arba II priedo sektorius ir subsektorius",
    "ue.zaslepki.21": "valstybių narių, kuriose subjektas teikia paslaugas, sąrašas",
    "ue.zaslepki.22": "Nustato nacionalinė teisė.",
    "ue.zaslepki.23": "Direktyva (ES) 2022/2555 — 3 straipsnis",
    "ue.zaslepki.24": "ENISA — valstybių narių kompetentingos institucijos",
    "ue.zaslepki.25": "Direktyva (ES) 2022/2555",
    "ue.zaslepki.26": "ES modulyje nėra nacionalinės institucijos gairių — jos atsiras kartu su nacionalinės teisės moduliu.",
    "ue.zaslepki.27": "Automatinis registro duomenų gavimas veikia tik šalims, turinčioms nacionalinės teisės modulį. Profilį užpildykite rankiniu būdu.",
    "ue.zaslepki.28": "Finansinės ataskaitos skaitymas veikia tik šalims, turinčioms nacionalinės teisės modulį. Pajamas ir darbuotojų skaičių įveskite rankiniu būdu.",
    "ue.zaslepki.3": "Komisijos įgyvendinimo reglamentas (ES) 2024/2690",
    "ue.zaslepki.4": "ES OL L, 2024/2690, 2024 11 18",
    "ue.zaslepki.5": "TIS 2 direktyvoje nėra atskiro elektroninių ryšių sluoksnio. Nacionalinė elektroninių ryšių teisė gali nustatyti papildomas pareigas — šis modulis jų nežino.",
    "ue.zaslepki.6": "Esminių ir svarbių subjektų sąrašas",
    "ue.zaslepki.7": "Valstybės narės kompetentinga institucija.",
    "ue.zaslepki.8": "Direktyva įpareigoja valstybes nares tvarkyti esminių ir svarbių subjektų sąrašą ir reikalauti, kad subjektai pateiktų registracijos duomenis. Portalą, tvarką ir terminą nustato nacionalinė teisė — šis modulis jų nežino, nes pasirinktos šalies nacionalinės teisės modulis dar neparengtas.",
    "ue.zaslepki.9": "Visi esminiai ir svarbūs subjektai. Terminą nustato nacionalinė teisė.",
    "ue.zaslepki.skrotDyrektywy": "TIS 2 direktyva",
    "ue.zaslepki.skrotReg2690": "Reglamentas 2024/2690",
    "xlsx.1": "{p0} – {p1} EUR",
    "xlsx.25": "Valiutos kursas",
    "xlsx.4": "ATITIKTIES TIS 2 DIREKTYVAI (ES) 2022/2555 ATASKAITA",
    "xlsx.58": "Elektroninių ryšių veikla: Reglamentas (ES) 2024/2690 netaikomas. Ribas nustato nacionalinė teisė (direktyvos 23 straipsnio 11 dalis) — bendrasis modulis jų nežino.",
    "xlsx.68": "Įrankis skirtas savęs vertinimui. Tai nėra nei auditas, nei teisinė konsultacija.",
    "xlsx.69": "Subjektams, kuriems Reglamentas (ES) 2024/2690 netaikomas, didelio incidento ribas nustato nacionalinė teisė (direktyvos 23 straipsnio 11 dalis).",
    "xlsx.70": "Profilyje nurodytos funkcijos yra deklaracija. Statusą lemia faktiškai vykdoma veikla (Direktyvos (ES) 2022/2555 3 straipsnis).",
    "xlsx.etykietaKrs": "Registro numeris",
    "xlsx.etykietaNip": "Identifikavimo numeris",
    "xlsx.etykietaRegon": "Statistinis numeris"
});
