/* Teksty modułu ue — język: lv.
   Te same klucze co w napisy/pl.js (wersja źródłowa); wstawki {p0}, {p1}…
   pozostają bez zmian. Klucze ue.cyt.* to wzorce składania odesłań
   do przepisów w tym języku — patrz kraje/ue/cytaty.js. */
KRAJE.napisy('ue', 'lv', {
    "app.10": "Pārbaudiet lomu sarakstu zemāk — statusu nosaka faktiski veiktā darbība (Direktīvas (ES) 2022/2555 3. pants), nevis ieraksts reģistrā.",
    "app.14": "Iepriekšējais gads: {p0} EUR",
    "app.15": "Pārskata perioda ieņēmumi: {p0} EUR",
    "app.19": "Vaicājums reģistriem pēc numura {p0}…",
    "app.34": " mljrd. EUR",
    "app.35": " milj. EUR",
    "app.36": " tūkst. EUR",
    "app.37": "",
    "app.4": "Automātiska reģistra datu iegūšana šai valstij nav pieejama — aizpildiet profilu manuāli.",
    "app.59": "Atbilstības TID 2 direktīvai novērtējums (JSON)",
    "app.68": "Šai valstij nav reģistra, no kura rīks varētu iegūt datus — profils tiek aizpildīts manuāli.",
    "app.69": "Šai valstij nav reģistra, no kura rīks varētu iegūt datus. Noklikšķiniet, lai ieslēgtu bezsaistes režīmu.",
    "app.73": " · peļņas vai zaudējumu aprēķins versijā ",
    "app.74": "<div class=\"mt-2 tekst-uwaga\">Reģistra dati neuzrāda nevienu digitālās infrastruktūras nozares lomu. Izvēlieties lomas manuāli zemāk.</div>",
    "app.8": "Apstiprināts ieraksts elektronisko sakaru pakalpojumu sniedzēju reģistrā",
    "app.progDostawcy": "",
    "app.przyklad.adres": "Parauga iela 1, Pilsēta, LV-1000",
    "app.przyklad.forma": "Sabiedrība ar ierobežotu atbildību",
    "app.przyklad.nazwa": "Parauga operators SIA",
    "app.statusVat": " · PVN statuss: ",
    "dashboard.1": "Pamatojoties uz deklarētajām lomām un lielumu, subjekts nav ne būtiska, ne svarīga vienība Direktīvas (ES) 2022/2555 3. panta nozīmē. Pārbaudiet profilu, ja rezultāts atšķiras no gaidītā.",
    "dashboard.113": "Biežāk uzdotie jautājumi",
    "dashboard.12": "— {p0}; transponēšanas nacionālajos tiesību aktos termiņš beidzās {p2}",
    "dashboard.123": "TID 2 direktīva",
    "dashboard.30": "Būtisko un svarīgo vienību saraksts",
    "dashboard.4": "— tieši piemērojama no {p0} visās dalībvalstīs, bez transponēšanas",
    "dashboard.42": "Fiksētās summas variants: {p0}",
    "dashboard.45": "Direktīvas 32. panta 7. punkta kritēriji:",
    "dashboard.46": "Kopā",
    "dashboard.49": "Subjekts veic elektronisko sakaru darbību — vadošās personas atbildību nosaka nacionālie tiesību akti",
    "dashboard.50": "",
    "dashboard.51": "",
    "dashboard.53": "Periodiskais sods par lēmuma izpildes kavējumu: no {p0} EUR līdz {p1} EUR dienā ({p2})",
    "dashboard.54": "Kvalificēts gadījums: līdz {p0} EUR ({p1})",
    "dashboard.57": "({p0}). No kura brīža nacionālā iestāde var uzlikt naudas sodus, nosaka direktīvu transponējošais likums — šis modulis to nezina. Ieviešanas pienākumi izriet no nacionālajiem tiesību aktiem no to spēkā stāšanās dienas.",
    "dashboard.65": "({p0}). No kura brīža nacionālā iestāde var uzlikt naudas sodus, nosaka direktīvu transponējošais likums — šis modulis to nezina. Tāpēc finansiālais risks šeit nav datēts, bet ieviešanas pienākumi izriet no nacionālajiem tiesību aktiem no to spēkā stāšanās dienas.",
    "dashboard.83": "Elektronisko sakaru darbība — sliekšņus nosaka nacionālie tiesību akti.",
    "dashboard.84": "Regula (ES) 2024/2690 neattiecas uz publisko elektronisko sakaru tīklu un pakalpojumu sniedzējiem. Tiem būtiska incidenta sliekšņus nosaka nacionālie tiesību akti (direktīvas 23. panta 11. punkts) — šis modulis tos nezina, tāpēc skaitļus nesniedz.",
    "dashboard.terminRejestracji": "Reģistrācijas datu iesniegšanas termiņu nosaka nacionālie tiesību akti (direktīvas 3. panta 4. punkts). 27. panta 1. punktā minētie sniedzēji — DNS pakalpojumu sniedzēji, augstākā līmeņa domēna vārdu reģistri, mākoņdatošanas, datu centru, satura piegādes tīklu, pārvaldītu pakalpojumu un pārvaldītu drošības pakalpojumu sniedzēji — datus iesniedz ENISA reģistrā: sākotnēji līdz 2025. gada 17. janvārim, bet katru izmaiņu — bez nepamatotas kavēšanās.",
    "html.1": "ITORO — Atbilstības TID 2 direktīvai (ES) 2022/2555 novērtējums",
    "html.10": "Atbilstības TID 2 direktīvai novērtējums — kopējais modulis",
    "html.100": "Finanšu pārskata nolasīšana darbojas tikai valstīm ar nacionālo tiesību aktu moduli. Šai valstij finanšu gada <strong>ieņēmumus</strong> ievadāt manuāli — no tiem atkarīgs naudas soda apmērs.",
    "html.102": "Automātiska reģistra datu iegūšana darbojas tikai valstīm ar nacionālo tiesību aktu moduli. Lomas un uzņēmuma lielumu norādāt manuāli.",
    "html.11": "Direktīva (ES) 2022/2555 (TID 2) prasa transponēšanu nacionālajos tiesību aktos. Novērtējums aptver pienākumus, kas izriet tieši no direktīvas, un tieši piemērojamo Komisijas Īstenošanas regulu (ES) 2024/2690 — tiktāl, ciktāl tie attiecas uz subjektu.",
    "html.23": "ieņēmumus un lielumu ievadāt manuāli — kopējais modulis nevaicā nacionālajiem reģistriem",
    "html.33": "Eiropas Parlamenta un Padomes 2022. gada 14. decembra Direktīva (ES) 2022/2555 (TID 2)",
    "html.33a": "{p0} — direktīvu transponējošs valsts akts; tā prasības šis modulis vēl nevērtē",
    "html.33b": "valsts vēl nav pieņēmusi transponēšanas aktu — novērtējums balstās uz Savienības tiesībām",
    "html.35": "pārvaldības struktūras pienākumi — direktīvas 20. pants",
    "html.36": "Rīks kalpo pašnovērtējumam. Tas nav ne audits, ne juridiska konsultācija.",
    "html.40": "kopējais modulis neveido nekādus izejošos savienojumus — nevaicā reģistriem",
    "html.59": "Finanšu pārskati",
    "html.60": "Finanšu pārskata nolasīšana pieejama tikai valstīm ar nacionālo tiesību aktu moduli. Šai valstij ieņēmumus un darbinieku skaitu ievadāt manuāli.",
    "html.62": "Meklēšana reģistrā",
    "html.63": "uzņēmumu reģistri ir nacionāli — kopējais modulis tos nezina",
    "html.64": "lomas un uzņēmuma lielumu norādāt manuāli",
    "html.66": "Subjekta identifikācijas numurs",
    "html.68": "Automātiska reģistra datu iegūšana darbojas tikai valstīm ar nacionālo tiesību aktu moduli.",
    "html.76": "Gada ieņēmumi (EUR)",
    "html.78": "Ieņēmumi no elektronisko sakaru darbības (EUR)",
    "html.79": "Lauks attiecas uz publisko elektronisko sakaru tīklu vai pakalpojumu sniedzējiem. Nacionālos sliekšņus nosaka dalībvalsts tiesību akti.",
    "html.80": "Vadītāja mēneša atalgojums (EUR)",
    "html.82": "Valūtas kurss",
    "html.83": "Direktīvā naudas sodu griesti izteikti eiro. Pārrēķinu nacionālajā valūtā un kursu nosaka nacionālie tiesību akti — šeit summas norādītas eiro bez pārrēķina.",
    "html.84": "Statuss izriet tikai no saistīto uzņēmumu datu summēšanas, un subjekta informācijas sistēma ir neatkarīga (direktīvas 16. apsvērums — par piemērošanu lemj nacionālie tiesību akti)",
    "html.85": "Subjekts darbojas valsts drošības, sabiedriskās drošības, aizsardzības vai tiesībaizsardzības jomā (direktīvas 2. panta 7. punkts)",
    "html.91": "Atbilstības Eiropas Parlamenta un Padomes Direktīvai (ES) 2022/2555 (TID 2) un Komisijas Īstenošanas regulai (ES) 2024/2690 novērtējums — kopējais modulis valstīm, kuru nacionālo tiesību aktu modulis vēl nav sagatavots.",
    "html.94": "vai subjekts ir <strong>būtiska</strong>, <strong>svarīga</strong> vienība vai ārpus direktīvas darbības jomas",
    "html.daneZeSprawozdania": "nosaukums, identifikācijas numurs, juridiskā adrese",
    "html.rejestrMozliwy": "Reģistrs {p0} ir publisks un bez maksas — tā nolasīšanu var pievienot; gaidām pull request (sk. README).",
    "html.tytulNaglowka": "Atbilstības TID 2 direktīvai novērtējums",
    "html.zrodlaRecznie": "Šis modulis nepazīst jūsu valsts reģistrus — aizpildiet profilu manuāli. Gada apgrozījums nosaka naudas soda augšējo robežu, tāpēc norādiet to precīzi.",
    "klasyfikacja.10": "Direktīvas (ES) 2022/2555 3. panta 1. punkta c) apakšpunkts (publisko elektronisko sakaru tīklu vai publiski pieejamu elektronisko sakaru pakalpojumu sniedzējs, kas ir vismaz vidējs uzņēmums)",
    "klasyfikacja.11": "Direktīvas (ES) 2022/2555 3. panta 2. punkts saistībā ar 2. panta 2. punkta a) apakšpunkta i) punktu (publisko elektronisko sakaru tīklu vai pakalpojumu sniedzējs, kas ir mikrouzņēmums vai mazs uzņēmums)",
    "klasyfikacja.12": "Direktīvas (ES) 2022/2555 3. panta 1. punkta a) apakšpunkts (pārvaldītu drošības pakalpojumu sniedzējs, kas pārsniedz vidēja uzņēmuma sliekšņus)",
    "klasyfikacja.13": "Mikrouzņēmumiem un maziem uzņēmumiem šīs lomas dēļ direktīva nav piemērojama (2. panta 1. punkts a contrario).",
    "klasyfikacja.15": "Direktīvas (ES) 2022/2555 3. panta 1. punkta b) apakšpunkts (kvalificēts uzticamības pakalpojumu sniedzējs) — neatkarīgi no uzņēmuma lieluma",
    "klasyfikacja.16": "Direktīvas (ES) 2022/2555 3. panta 2. punkts saistībā ar 2. panta 2. punkta a) apakšpunkta ii) punktu (nekvalificēts uzticamības pakalpojumu sniedzējs, kas ir mikrouzņēmums, mazs vai vidējs uzņēmums)",
    "klasyfikacja.18": "Direktīvas (ES) 2022/2555 3. panta 2. punkts (reģionālā līmeņa publiskās pārvaldes vienība, ja dalībvalsts tā paredz — 2. panta 2. punkta f) apakšpunkta ii) punkts)",
    "klasyfikacja.19": "Direktīvas (ES) 2022/2555 3. panta 1. punkta f) apakšpunkts (centrālās valdības līmeņa publiskās pārvaldes vienība — 2. panta 2. punkta f) apakšpunkta i) punkts)",
    "klasyfikacja.2": "Ex ante un ex post uzraudzība (Direktīvas (ES) 2022/2555 32. pants).",
    "klasyfikacja.20": "Direktīvas (ES) 2022/2555 3. panta 2. punkts (reģionālā līmeņa publiskās pārvaldes vienība — 2. panta 2. punkta f) apakšpunkta ii) punkts)",
    "klasyfikacja.21": "Vietējā līmeņa publiskās pārvaldes vienību pienākumu apjomu nosaka nacionālie tiesību akti (direktīvas 2. panta 5. punkta a) apakšpunkts).",
    "klasyfikacja.22": "Dalībvalsts var atbrīvot vienības, kas darbojas valsts drošības, sabiedriskās drošības, aizsardzības vai tiesībaizsardzības jomā (direktīvas 2. panta 7. punkts). Atbrīvojums nedarbojas pats no sevis — pārbaudiet novērtējuma rezultātu pēc nacionālajiem tiesību aktiem.",
    "klasyfikacja.23": "Subjekts atbilst gan būtiskas, gan svarīgas vienības kritērijiem. Tas ir būtiska vienība (direktīvas 3. panta 1. punkts), un stingrākās prasības attiecas uz visu direktīvas aptverto darbību.",
    "klasyfikacja.25": "Subjekts ir būtiska vienība, tāpēc tam piemērojams pilns direktīvas 21. panta 2. punkta pasākumu katalogs un ex ante un ex post uzraudzība — novērtējums aptver pilnu jautājumu kopumu.",
    "klasyfikacja.26": "Kā svarīgai vienībai jums piemērojams tas pats 21. panta 2. punkta pasākumu katalogs, bet tikai ex post uzraudzība (33. pants). Naudas soda griesti ir zemāki: 7 milj. EUR vai 1,4 % no apgrozījuma (34. panta 5. punkts). Atvieglojumus publiskajiem subjektiem var ieviest nacionālie tiesību akti — šis modulis tos nezina.",
    "klasyfikacja.28": "Publiskās pārvaldes vienību pienākumi izriet no direktīvas 2. panta 2. punkta f) apakšpunkta; to precīzo apjomu, tostarp vietējam līmenim un izglītības iestādēm, nosaka nacionālie tiesību akti (2. panta 5. punkts).",
    "klasyfikacja.29": "Deklarēts, ka subjekta statuss izriet tikai no saistīto vai partneruzņēmumu datu summēšanas un ka subjekta informācijas sistēma ir neatkarīga. Direktīva šādu izslēgšanu pieļauj (16. apsvērums), bet par to lemj nacionālie tiesību akti — modulis izslēgšanu pieņem, taču tā jāpārbauda pēc dalībvalsts tiesību aktiem un jādokumentē.",
    "klasyfikacja.4": "Tikai ex post uzraudzība — ja ir pierādījumi, norādes vai informācija par pārkāpumu (Direktīvas (ES) 2022/2555 33. pants).",
    "klasyfikacja.5": "Ārpus direktīvas darbības jomas",
    "klasyfikacja.6": "Norādītajai lomai no Direktīvas (ES) 2022/2555 pienākumi neizriet.",
    "klasyfikacja.7": "Direktīvas (ES) 2022/2555 3. panta 1. punkta a) apakšpunkts (I pielikumā minēta veida vienība, kas pārsniedz vidēja uzņēmuma sliekšņus)",
    "klasyfikacja.8": "Direktīvas (ES) 2022/2555 3. panta 2. punkts (I pielikumā minēta veida vienība, kas atbilst vidēja uzņēmuma kritērijiem)",
    "klasyfikacja.9": "Mikrouzņēmumiem un maziem uzņēmumiem šīs lomas dēļ direktīva nav piemērojama (2. panta 1. punkts a contrario).",
    "kreator.10": "Ievadiet iepriekšējā gada ieņēmumus manuāli.",
    "kreator.35": "<span class=\"text-secondary\">Finanšu pārskatu nolasīšana šai valstij nav pieejama.</span>",
    "kreator.37": "Finanšu pārskatu nolasīšana šai valstij nav pieejama — ievadiet ieņēmumus manuāli.",
    "kreator.56": "Jā — ES regula ir tieši piemērojama no 2024. gada 7. novembra visās dalībvalstīs, un tai nav pārejas perioda. Tās pamats ir",
    "kreator.57": ", kas pilnvaroja Komisiju noteikt tehniskās un metodoloģiskās prasības regulas 3. panta 1. punktā minētajiem sniedzējiem. Direktīvas transponēšanas termiņš beidzās",
    "kreator.58": ", bet no kura brīža nacionālā iestāde var uzlikt naudas sodus, nosaka nacionālie tiesību akti. Pielikuma tehniskās prasības (6. un 9.–13. sadaļa) ir saistošas pašreizējā redakcijā — tās negaida precizējumu. Atkāpties var tikai no prasībām ar klauzulu „attiecīgā gadījumā”, un tikai ar dokumentētu pamatojumu.",
    "kreator.9": "Finanšu pārskati →",
    "kreator.przepisReg2690": "Direktīvas (ES) 2022/2555 21. panta 5. punkts",
    "kreator.terminReg2690": "2024. gada 17. oktobrī",
    "punktacja.10": "Publiskie subjekti",
    "punktacja.4": "TID 2 direktīva — 21. pants",
    "punktacja.5": "TID 2 direktīva — formālie pienākumi",
    "punktacja.8": "Elektroniskie sakari",
    "punktacja.9": "TID 2 direktīva — publiskie subjekti",
    "punktacja.skrotKsc": "TID 2",
    "punktacja.skrotPke": "telekom.",
    "ue.cyt.akapit": "{p0} daļa",
    "ue.cyt.art": "{p0}. panta",
    "ue.cyt.drugi": "otrā",
    "ue.cyt.dyr": "Direktīvas (ES) 2022/2555 {p0}",
    "ue.cyt.i": "un",
    "ue.cyt.laczenie": " ",
    "ue.cyt.lit": "{p0}) apakšpunkts",
    "ue.cyt.litery": "",
    "ue.cyt.pkt": "{p0}. punkts",
    "ue.cyt.rozdzielacz": "; ",
    "ue.cyt.rozp": "Regulas (ES) 2024/2690 {p0}",
    "ue.cyt.ust": "{p0}. punkts",
    "ue.katalog.1": "Riska analīzes un informācijas sistēmu drošības politika",
    "ue.katalog.10": "Incidentu apstrāde",
    "ue.katalog.11": "Incidentu apstrāde ir darbības un procedūras, kuru mērķis ir novērst, atklāt, analizēt un ierobežot incidentu vai reaģēt uz to un atgūties pēc tā (6. panta 8. punkts).",
    "ue.katalog.12": "Vai ir dokumentēta incidentu apstrādes procedūra, kas aptver atklāšanu, analīzi, ierobežošanu, reaģēšanu un atgūšanos?",
    "ue.katalog.13": "ISO/IEC 27001 A.5.24–A.5.26",
    "ue.katalog.14": "Vai procedūra ļauj ievērot būtiska incidenta paziņošanas termiņus: agrīnais brīdinājums 24 stundu laikā, paziņojums par incidentu 72 stundu laikā, galīgais ziņojums viena mēneša laikā?",
    "ue.katalog.15": "ISO/IEC 27001 A.5.24",
    "ue.katalog.16": "Vai vienībai ir kritēriji incidenta atzīšanai par būtisku, kas atbilst 23. panta 3. punktam: smagi darbības traucējumi vai finansiāli zaudējumi vai ievērojams kaitējums citām personām?",
    "ue.katalog.17": "ISO/IEC 27001 A.5.25",
    "ue.katalog.18": "Vai incidenti tiek reģistrēti un vai to apstrādes atziņas izmanto pasākumu uzlabošanai?",
    "ue.katalog.19": "ISO/IEC 27001 A.5.27",
    "ue.katalog.2": "Pasākumi balstās uz visu apdraudējumu pieeju (21. panta 2. punkts). To samērīgumu vērtē, ņemot vērā riska pakāpi, vienības lielumu, incidentu iespējamību un smagumu (21. panta 1. punkta otrā daļa).",
    "ue.katalog.20": "Darbības nepārtrauktība un krīžu pārvaldība",
    "ue.katalog.21": "Darbības nepārtrauktība, piemēram, rezerves kopiju pārvaldība un darbības atjaunošana pēc katastrofas, un krīžu pārvaldība.",
    "ue.katalog.22": "Vai ir darbības nepārtrauktības plāns, kas aptver atjaunošanu pēc katastrofas?",
    "ue.katalog.23": "ISO/IEC 27001 A.5.29–A.5.30",
    "ue.katalog.24": "Vai rezerves kopijas tiek veidotas, aizsargātas un pārbaudītas attiecībā uz atjaunošanas iespēju?",
    "ue.katalog.25": "ISO/IEC 27001 A.8.13",
    "ue.katalog.26": "Vai vienībai ir krīžu pārvaldības procedūras ar noteiktām lomām un saziņas kanāliem?",
    "ue.katalog.27": "ISO/IEC 27001 A.5.29",
    "ue.katalog.28": "Vai nepārtrauktības un atjaunošanas plāni tiek periodiski testēti un rezultāti dokumentēti?",
    "ue.katalog.29": "ISO/IEC 27001 A.5.30",
    "ue.katalog.3": "Vai vienībai ir dokumentēta riska analīzes un informācijas sistēmu drošības politika, ko apstiprinājusi pārvaldības struktūra?",
    "ue.katalog.30": "Piegādes ķēdes drošība",
    "ue.katalog.31": "Piegādes ķēdes drošība, tostarp ar drošību saistītie aspekti attiecībās starp vienību un tās tiešajiem piegādātājiem vai pakalpojumu sniedzējiem. Vienība ņem vērā katram piegādātājam raksturīgās ievainojamības un tā produktu un kiberdrošības prakses vispārējo kvalitāti (21. panta 3. punkts).",
    "ue.katalog.32": "Vai vienība uztur tiešo piegādātāju un pakalpojumu sniedzēju sarakstu ar to nozīmīguma tīklu un sistēmu drošībai novērtējumu?",
    "ue.katalog.33": "ISO/IEC 27001 A.5.19",
    "ue.katalog.34": "Vai, izvēloties pasākumus attiecībā uz piegādātājiem, ņem vērā katram no tiem raksturīgās ievainojamības un to kiberdrošības un drošas izstrādes prakses kvalitāti?",
    "ue.katalog.35": "ISO/IEC 27001 A.5.19, A.5.21",
    "ue.katalog.36": "Vai līgumos ar piegādātājiem ir drošības prasības un pienākums ziņot par incidentiem un ievainojamībām?",
    "ue.katalog.37": "ISO/IEC 27001 A.5.20",
    "ue.katalog.38": "Vai vienība ņem vērā 22. pantā minēto kritisko piegādes ķēžu koordinēto drošības riska novērtējumu rezultātus?",
    "ue.katalog.39": "ISO/IEC 27001 A.5.21",
    "ue.katalog.4": "ISO/IEC 27001 5.2., 6.1.2. punkts",
    "ue.katalog.40": "Drošība sistēmu iegādē, izstrādē un uzturēšanā",
    "ue.katalog.41": "Drošība tīklu un informācijas sistēmu iegādē, izstrādē un uzturēšanā, tostarp ievainojamību apstrāde un atklāšana.",
    "ue.katalog.42": "Vai drošības prasības tiek noteiktas pirms sistēmas iegādes vai izstrādes sākuma un pārbaudītas pirms ieviešanas?",
    "ue.katalog.43": "ISO/IEC 27001 A.8.25–A.8.29",
    "ue.katalog.44": "Vai ir ievainojamību apstrādes process: identificēšana, novērtēšana, novēršana noteiktā laikā?",
    "ue.katalog.45": "ISO/IEC 27001 A.8.8",
    "ue.katalog.46": "Vai vienībai ir ievainojamību atklāšanas procedūra, tostarp kanāls trešo personu ziņojumu saņemšanai?",
    "ue.katalog.47": "Vai sistēmu izmaiņas notiek kontrolētā izmaiņu pārvaldības procesā ar ietekmes uz drošību novērtējumu?",
    "ue.katalog.48": "ISO/IEC 27001 A.8.32",
    "ue.katalog.49": "Pasākumu efektivitātes novērtēšana",
    "ue.katalog.5": "Vai riska analīze aptver visus apdraudējumus tīklu un informācijas sistēmām un to fiziskajai videi, ne tikai kiberdraudus?",
    "ue.katalog.50": "Politika un procedūras kiberdrošības riska pārvaldības pasākumu efektivitātes novērtēšanai.",
    "ue.katalog.51": "Vai ir dokumentēta pasākumu efektivitātes novērtēšanas politika, kas nosaka tvērumu, biežumu un metodes?",
    "ue.katalog.52": "ISO/IEC 27001 9.1. punkts",
    "ue.katalog.53": "Vai efektivitātes novērtējumi tiek veikti periodiski un to rezultāti nodoti pārvaldības struktūrai?",
    "ue.katalog.54": "ISO/IEC 27001 9.2.–9.3. punkts",
    "ue.katalog.55": "Vai konstatētās nepilnības noved pie dokumentētām koriģējošām darbībām ar atbildīgo un termiņu?",
    "ue.katalog.56": "ISO/IEC 27001 10.1. punkts",
    "ue.katalog.57": "Kiberhigiēna un apmācība",
    "ue.katalog.58": "Kiberhigiēnas pamatprakse un kiberdrošības apmācība. Pārvaldības struktūras locekļi regulāri piedalās apmācībā (20. panta 2. punkts).",
    "ue.katalog.59": "Vai vienība piemēro kiberhigiēnas pamatpraksi: atjauninājumus, paroļu pārvaldību, tiesību ierobežošanu, aizsardzību pret ļaunprogrammatūru?",
    "ue.katalog.6": "ISO/IEC 27001 6.1.2. punkts",
    "ue.katalog.60": "ISO/IEC 27001 A.8.7, A.8.8",
    "ue.katalog.61": "Vai darbinieki saņem viņu lomai pielāgotu kiberdrošības apmācību un vai dalība tiek dokumentēta?",
    "ue.katalog.62": "ISO/IEC 27001 A.6.3",
    "ue.katalog.63": "Vai pārvaldības struktūras locekļi regulāri piedalās apmācībā, kas ļauj identificēt riskus un novērtēt riska pārvaldības praksi?",
    "ue.katalog.64": "ISO/IEC 27001 7.2. punkts",
    "ue.katalog.65": "Kriptogrāfija un šifrēšana",
    "ue.katalog.66": "Politika un procedūras kriptogrāfijas un attiecīgā gadījumā šifrēšanas izmantošanai.",
    "ue.katalog.67": "Vai ir kriptogrāfijas politika, kas nosaka, kuri dati un kanāli tiek šifrēti un ar kādiem algoritmiem?",
    "ue.katalog.68": "ISO/IEC 27001 A.8.24",
    "ue.katalog.69": "Vai kriptogrāfiskās atslēgas tiek pārvaldītas visā dzīves ciklā: ģenerēšana, izplatīšana, glabāšana, rotācija, izņemšana no aprites?",
    "ue.katalog.7": "Vai pasākumu izvēlē ņem vērā jaunākos sasniegumus, attiecīgos Eiropas un starptautiskos standartus un ieviešanas izmaksas?",
    "ue.katalog.70": "Cilvēkresursi, piekļuves kontrole un aktīvu pārvaldība",
    "ue.katalog.71": "Cilvēkresursu drošība, piekļuves kontroles politika un aktīvu pārvaldība.",
    "ue.katalog.72": "Vai vienība uztur aktuālu aktīvu sarakstu ar piešķirtiem īpašniekiem un klasifikāciju?",
    "ue.katalog.73": "ISO/IEC 27001 A.5.9, A.5.12",
    "ue.katalog.74": "Vai ir piekļuves kontroles politika, kas balstās uz minimālo tiesību principu, ar periodisku tiesību pārskatīšanu?",
    "ue.katalog.75": "ISO/IEC 27001 A.5.15, A.5.18",
    "ue.katalog.76": "Vai, pieņemot darbā, mainot amatu un darbiniekam aizejot, tiek piemērotas drošības procedūras, tostarp tiesību atsaukšana un aktīvu atgriešana?",
    "ue.katalog.77": "ISO/IEC 27001 A.6.1–A.6.5",
    "ue.katalog.78": "Vai privileģētā piekļuve tiek ierobežota, reģistrēta un pārskatīta?",
    "ue.katalog.79": "ISO/IEC 27001 A.8.2",
    "ue.katalog.8": "ISO/IEC 27001 6.1.3. punkts",
    "ue.katalog.80": "Daudzfaktoru autentifikācija un drošināta saziņa",
    "ue.katalog.81": "Attiecīgā gadījumā — daudzfaktoru vai nepārtraukta autentifikācija, drošināta balss, video un teksta saziņa un drošinātas ārkārtas saziņas sistēmas vienības iekšienē.",
    "ue.katalog.82": "Vai daudzfaktoru vai nepārtraukta autentifikācija tiek izmantota tur, kur to pamato riska analīze, jo īpaši attālinātai piekļuvei un privileģētiem kontiem?",
    "ue.katalog.83": "ISO/IEC 27001 A.8.5",
    "ue.katalog.84": "Vai darba vajadzībām izmantotā balss, video un teksta saziņa ir drošināta?",
    "ue.katalog.85": "ISO/IEC 27001 A.8.20",
    "ue.katalog.86": "Vai vienībai ir drošināta iekšējā ārkārtas saziņas sistēma, neatkarīga no pamatinfrastruktūras?",
    "ue.katalog.9": "Vai drošības līmenis ir dokumentēts kā atbilstošs pastāvošajam riskam, ar pamatojumu, kas ņem vērā vienības lielumu un incidentu sociālo un ekonomisko ietekmi?",
    "ue.kierownictwo.1": "Būtiskas vai svarīgas vienības pārvaldības struktūra — kapitālsabiedrībā valde. Direktīva šo jēdzienu nedefinē; tā apjoms konkrētā valstī izriet no nacionālajiem tiesību aktiem.",
    "ue.kierownictwo.10": "Noteikt vienības statusu un nodrošināt reģistrāciju",
    "ue.kierownictwo.11": "Noteikšana, vai vienība ir būtiska vai svarīga, un reģistrācijas datu iesniegšana kompetentajai iestādei. Kārtību un termiņu nosaka nacionālie tiesību akti.",
    "ue.kierownictwo.12": "Ieviest riska analīzi un drošības politiku",
    "ue.kierownictwo.13": "Uz visu apdraudējumu pieeju balstīti pasākumi, samērīgi riska pakāpei, vienības lielumam un incidentu smagumam.",
    "ue.kierownictwo.14": "Izveidot incidentu apstrādi un paziņošanu",
    "ue.kierownictwo.15": "Incidentu apstrādes procedūra un spēja ievērot 24 stundu, 72 stundu un viena mēneša termiņus.",
    "ue.kierownictwo.16": "24 h / 72 h / mēnesis no atklāšanas",
    "ue.kierownictwo.17": "Nodrošināt darbības nepārtrauktību",
    "ue.kierownictwo.18": "Nepārtrauktības plāns, rezerves kopijas, atjaunošana pēc katastrofas, krīžu pārvaldība.",
    "ue.kierownictwo.19": "Sakārtot piegādes ķēdi",
    "ue.kierownictwo.2": "Pārvaldības struktūras atbildība neskar nacionālos noteikumus par publisko iestāžu un amatpersonu atbildību (20. panta 1. punkta otrā daļa).",
    "ue.kierownictwo.20": "Piegādātāju saraksts, to ievainojamību un prakses novērtējums, drošības prasības līgumos.",
    "ue.kierownictwo.21": "Ieviest piekļuves kontroli un aktīvu pārvaldību",
    "ue.kierownictwo.22": "Aktīvu saraksts, minimālo tiesību princips, tiesību pārskatīšana, daudzfaktoru autentifikācija tur, kur to pamato risks.",
    "ue.kierownictwo.23": "Mērīt pasākumu efektivitāti",
    "ue.kierownictwo.24": "Efektivitātes novērtēšanas politika un procedūras, periodiskas pārskatīšanas, koriģējošās darbības.",
    "ue.kierownictwo.25": "Apstiprināt",
    "ue.kierownictwo.26": "kiberdrošības riska pārvaldības pasākumus (20. panta 1. punkts)",
    "ue.kierownictwo.27": "riska analīzes un sistēmu drošības politiku",
    "ue.kierownictwo.28": "ieviešanas budžetu un lomas",
    "ue.kierownictwo.29": "Uzraudzīt",
    "ue.kierownictwo.3": "Vai pienākumu uzticēšana citai personai atbrīvo no atbildības, lemj nacionālie tiesību akti. Polijā neatbrīvo (Nacionālās kiberdrošības sistēmas likuma 8c panta 3. punkts).",
    "ue.kierownictwo.30": "apstiprināto pasākumu īstenošanu (20. panta 1. punkts)",
    "ue.kierownictwo.31": "efektivitātes novērtējuma rezultātus (21. panta 2. punkta f) apakšpunkts)",
    "ue.kierownictwo.32": "incidentu paziņošanas termiņu ievērošanu (23. pants)",
    "ue.kierownictwo.33": "Dokumentēt",
    "ue.kierownictwo.34": "apstiprināšanas lēmumus un pārskatīšanas",
    "ue.kierownictwo.35": "dalību apmācībā (20. panta 2. punkts)",
    "ue.kierownictwo.36": "Pārvaldības struktūras loceklis",
    "ue.kierownictwo.37": "pasākumu apstiprināšana, uzraudzība, lēmumi, budžets",
    "ue.kierownictwo.38": "Projekta vadītājs",
    "ue.kierownictwo.39": "ieviešanas koordinācija, grafiks, statuss un pierādījumi",
    "ue.kierownictwo.4": "Apstiprināt kiberdrošības riska pārvaldības pasākumus",
    "ue.kierownictwo.40": "IT / kiberdrošība",
    "ue.kierownictwo.41": "riska analīze, tehniskie pasākumi, incidentu apstrāde",
    "ue.kierownictwo.42": "Juridiskā nodaļa / atbilstība",
    "ue.kierownictwo.5": "Pārvaldības struktūra apstiprina pasākumus, kas veikti, lai izpildītu 21. pantu. Tas ir struktūras, nevis IT nodaļas lēmums — bez tā pasākumiem nav pamata.",
    "ue.kierownictwo.6": "Uzraudzīt pasākumu īstenošanu",
    "ue.kierownictwo.7": "Īstenošanas uzraudzība ir pārvaldības struktūras pienākums. Izpildi var deleģēt, uzraudzību — nē.",
    "ue.kierownictwo.8": "Regulāri piedalīties apmācībā",
    "ue.kierownictwo.9": "Pārvaldības struktūras locekļi regulāri piedalās apmācībā, lai iegūtu pietiekamas zināšanas risku identificēšanai un riska pārvaldības prakses un tās ietekmes uz vienības pakalpojumiem novērtēšanai.",
    "ue.kierownictwo.daneRejestracyjne": "reģistrācijas dati un to atjaunināšana (3. panta 4. un 5. punkts)",
    "ue.meta.1": "Pārsvaru gūst procentuālais variants: {p0} % no apgrozījuma ir vairāk nekā {p1} milj. EUR.",
    "ue.meta.10": "Direktīva pienākumus uzņēmumiem tieši neuzliek — to dara nacionālais likums, kas dalībvalstij bija jāpieņem līdz 2024. gada 17. oktobrim. Šis modulis rāda prasības direktīvas formulējumā, jo izvēlētās valsts nacionālo tiesību aktu modulis vēl nav sagatavots vai valsts direktīvu nav transponējusi.",
    "ue.meta.11": "Pienākumi saskaņā ar direktīvu",
    "ue.meta.12": "Vienību saraksts — līdz 2025. gada 17. aprīlim",
    "ue.meta.13": "Dalībvalstīm līdz 2025. gada 17. aprīlim bija jāizveido būtisko un svarīgo vienību saraksts un jāpieprasa vienībām iesniegt reģistrācijas datus.",
    "ue.meta.14": "Regula (ES) 2024/2690",
    "ue.meta.15": "Tieši piemērojama no 2024. gada 7. novembra",
    "ue.meta.16": "Īstenošanas regula ir tieši piemērojama visās dalībvalstīs neatkarīgi no direktīvas transponēšanas stāvokļa. Tā attiecas uz tās 1. pantā minētajām vienībām: DNS, augstākā līmeņa domēnu, mākoņdatošanas, datu centru, satura piegādes tīklu, pārvaldītu pakalpojumu un uzticamības pakalpojumu sniedzējiem.",
    "ue.meta.17": "Regulas (ES) 2024/2690 16. pants",
    "ue.meta.18": "Vismaz 10 000 000 EUR vai vismaz 2 % no uzņēmuma kopējā pasaules gada apgrozījuma iepriekšējā finanšu gadā — piemēro lielāko summu. Tie ir minimālie griesti: nacionālie tiesību akti tos var paaugstināt.",
    "ue.meta.19": "Vismaz 7 000 000 EUR vai 1,4 % no kopējā pasaules gada apgrozījuma — piemēro lielāko summu. Minimālie griesti.",
    "ue.meta.2": "Pārsvaru gūst fiksētā summa: {p0} milj. EUR ir vairāk nekā {p1} % no apgrozījuma.",
    "ue.meta.20": "Direktīva neparedz atsevišķu naudas sodu par kvalificētu pārkāpumu — tā ir dažu dalībvalstu nacionālo tiesību aktu konstrukcija.",
    "ue.meta.21": "Dalībvalstis var paredzēt periodiskus soda maksājumus, lai piespiestu izbeigt pārkāpumu. Apmēru nosaka nacionālie tiesību akti.",
    "ue.meta.22": "Pārvaldības struktūra apstiprina riska pārvaldības pasākumus, uzrauga to īstenošanu un var tikt saukta pie atbildības par 21. panta pārkāpumu. Šīs atbildības noteikumus un apjomu nosaka nacionālie tiesību akti.",
    "ue.meta.23": "Pārvaldības struktūra apstiprina kiberdrošības riska pārvaldības pasākumus (20. panta 1. punkts).",
    "ue.meta.24": "Pārvaldības struktūra uzrauga šo pasākumu īstenošanu (20. panta 1. punkts).",
    "ue.meta.25": "Pārvaldības struktūras locekļi regulāri piedalās apmācībā (20. panta 2. punkts).",
    "ue.meta.26": "Attiecībā uz būtisku vienību iestāde var pieprasīt pagaidu aizliegumu pildīt vadības funkcijas (32. panta 5. punkta b) apakšpunkts).",
    "ue.meta.27": "Minimālos griestus nosaka direktīva",
    "ue.meta.28": "Salīdzina divas vērtības: fiksētu summu eiro un procentu no uzņēmuma kopējā pasaules gada apgrozījuma iepriekšējā finanšu gadā. Lielākā no tām ir augšējā robeža, kas dalībvalstij jāparedz vismaz. Nacionālie tiesību akti to var paaugstināt.",
    "ue.meta.29": "Summu griestu ietvaros nosaka nacionālā iestāde",
    "ue.meta.3": "Direktīvas griesti pārsniedz subjekta gada apgrozījumu {p0} reizes. 34. panta 1. punkts prasa, lai naudas sods būtu samērīgs ar konkrētā gadījuma apstākļiem — tā ir augšējā robeža, nevis sagaidāmais naudas sods.",
    "ue.meta.30": "Naudas sodam jābūt iedarbīgam, samērīgam un atturošam atbilstoši konkrētā gadījuma apstākļiem. Iestāde ņem vērā vismaz 32. panta 7. punkta kritērijus: pārkāpuma smagumu un ilgumu, iepriekšējos pārkāpumus, nodarīto kaitējumu, nodomu, koriģējošos pasākumus un sadarbību.",
    "ue.meta.31": "Griesti var daudzkārt pārsniegt gada apgrozījumu — tā ir augšējā robeža, nevis sagaidāmā summa. Nacionālos minimumus, periodiskos sodus un naudas sodu noteikšanas kārtību nosaka dalībvalsts likums.",
    "ue.meta.32": "Lemjot par administratīvā naudas soda uzlikšanu un tā apmēru, katrā atsevišķā gadījumā pienācīgi ņem vērā vismaz 32. panta 7. punktā uzskaitītos elementus.",
    "ue.meta.33": "pārkāpuma smagums un pārkāpto noteikumu nozīmīgums — par smagiem jebkurā gadījumā uzskata: atkārtotus pārkāpumus, būtisku incidentu nepaziņošanu vai nenovēršanu, trūkumu nenovēršanu pretēji saistošiem norādījumiem, revīziju vai uzraudzības kavēšanu, nepatiesas vai rupji neprecīzas informācijas sniegšanu",
    "ue.meta.34": "jebkuri būtiski iepriekšējie vienības pārkāpumi",
    "ue.meta.35": "nodarītais mantiskais vai nemantiskais kaitējums, tostarp finansiālie zaudējumi, ietekme uz citiem pakalpojumiem un skarto lietotāju skaits",
    "ue.meta.36": "pārkāpuma tīšs vai nolaidīgs raksturs",
    "ue.meta.37": "pasākumi kaitējuma novēršanai vai mazināšanai",
    "ue.meta.38": "apstiprinātu rīcības kodeksu vai sertifikācijas mehānismu ievērošana",
    "ue.meta.39": "sadarbības pakāpe ar kompetentajām iestādēm",
    "ue.meta.4": "Eiropas Parlamenta un Padomes Direktīva (ES) 2022/2555 (TID 2)",
    "ue.meta.40": "Direktīva tieši neparedz atteikšanos no naudas soda — vai un kad tas iespējams, lemj nacionālie tiesību akti.",
    "ue.meta.41": "No šī datuma dalībvalstīm jāpiemēro nacionālie direktīvas īstenošanas noteikumi. Konkrētais datums, no kura iestāde var uzlikt naudas sodu, izriet no nacionālajiem tiesību aktiem.",
    "ue.meta.42": "TID 2 direktīvas stāšanās spēkā",
    "ue.meta.43": "Divdesmitajā dienā pēc publicēšanas Oficiālajā Vēstnesī.",
    "ue.meta.44": "Direktīvas transponēšanas termiņš",
    "ue.meta.45": "Līdz šim datumam dalībvalstīm bija jāpieņem un jāpublicē nacionālie noteikumi.",
    "ue.meta.46": "Nacionālo noteikumu piemērošana un TID 1 atcelšana",
    "ue.meta.47": "No šī datuma dalībvalstis piemēro īstenošanas noteikumus; Direktīva (ES) 2016/1148 tiek atcelta.",
    "ue.meta.48": "Regulas (ES) 2024/2690 piemērošana",
    "ue.meta.49": "Īstenošanas regula ir tieši piemērojama no divdesmitās dienas pēc publicēšanas.",
    "ue.meta.5": "ES OV L 333, 27.12.2022.",
    "ue.meta.50": "Būtisko un svarīgo vienību saraksts",
    "ue.meta.51": "Līdz šim datumam dalībvalstis izveido sarakstu; vienības iesniedz iestādēm reģistrācijas datus.",
    "ue.meta.52": "Pirmā Komisijas veiktā direktīvas pārskatīšana",
    "ue.meta.53": "Komisija pārskata direktīvas darbību un iesniedz ziņojumu.",
    "ue.meta.54": "Agrīnais brīdinājums par būtisku incidentu",
    "ue.meta.55": "24 stundas no uzzināšanas",
    "ue.meta.56": "Paziņojums par būtisku incidentu",
    "ue.meta.57": "72 stundas no uzzināšanas",
    "ue.meta.58": "Galīgais ziņojums",
    "ue.meta.59": "mēnesis no paziņojuma par incidentu",
    "ue.meta.6": "Komisijas Īstenošanas regula (ES) 2024/2690",
    "ue.meta.60": "Uzticamības pakalpojumu sniedzēja paziņojums par incidentu",
    "ue.meta.61": "Direktīvas (ES) 2022/2555 21. panta 5. punkts; Regulas (ES) 2024/2690 1. un 2. pants",
    "ue.meta.62": "Bez apgrozījuma datiem griesti ir direktīvā noteiktā fiksētā summa.",
    "ue.meta.63": "34. panta 4. un 5. punkta griesti ir minimālie („vismaz”) — nacionālie tiesību akti var paredzēt augstākus. Summas eiro, bez pārrēķina nacionālajā valūtā.",
    "ue.meta.64": "Dalībvalsts kompetentā iestāde",
    "ue.meta.65": "Pārvaldības struktūra var tikt saukta pie atbildības par 21. panta pārkāpumu. Apjomu un kārtību nosaka nacionālie tiesību akti — šis modulis tos nezina.",
    "ue.meta.66": "Vadības personīgās atbildības apjoms izriet no nacionālā likuma. Polijā tas ir līdz 300 % no atalgojuma (Nacionālās kiberdrošības sistēmas likuma 73a panta 4. punkts); citas dalībvalstis to regulē citādi.",
    "ue.meta.7": "ES OV L, 2024/2690",
    "ue.meta.8": "Direktīva (ES) 2022/2555",
    "ue.meta.9": "Transponēšanas termiņš beidzās 2024. gada 17. oktobrī",
    "ue.moduly.1": "apm. {p0} min",
    "ue.moduly.10": "Desmit jomas no 21. panta 2. punkta a)–j) apakšpunkta: no riska politikas līdz daudzfaktoru autentifikācijai. Par pārkāpumu draud naudas sods saskaņā ar 34. pantu. Novērtējums brieduma skalā.",
    "ue.moduly.11": "Regula 2024/2690 — pārvaldība un procesi",
    "ue.moduly.12": "Pielikuma 1.–5. un 7.–8. sadaļa: politika, riska pārvaldība, incidentu apstrāde, darbības nepārtrauktība, piegādes ķēde, efektivitātes novērtēšana, kiberhigiēna. Tieši piemērojama no 2024. gada 7. novembra.",
    "ue.moduly.13": "Regula 2024/2690 — tehniskās prasības",
    "ue.moduly.14": "Pielikuma 6. un 9.–13. sadaļa: sistēmu iegāde un izstrāde, kriptogrāfija, cilvēkresursu drošība, piekļuves kontrole, aktīvu pārvaldība, fiziskā un vides drošība.",
    "ue.moduly.2": "apm. {p0} h {p1} min",
    "ue.moduly.3": "apm. {p0} h",
    "ue.moduly.4": "mazāk nekā minūte",
    "ue.moduly.5": "Ātrs riska novērtējums",
    "ue.moduly.6": "Vispārīgie jautājumi no visām direktīvas jomām. Katrs izšķir veselu tēmu grupu. Ļauj novērtēt atpalicības apjomu, neizejot visu anketu.",
    "ue.moduly.7": "Pienākumi saskaņā ar direktīvu",
    "ue.moduly.8": "Reģistrācijas dati, incidentu paziņošana 24 un 72 stundu laikā, pārvaldības struktūras pienākumi, gatavība uzraudzībai. Pārbaudāms pēc dokumentiem, bez tehniskās analīzes.",
    "ue.moduly.9": "Riska pārvaldības pasākumi — 21. panta 2. punkts",
    "ue.obowiazki.1": "Reģistrācijas dati vienību sarakstam",
    "ue.obowiazki.10": "Būtisku incidentu paziņošana",
    "ue.obowiazki.11": "Vienība par būtiskiem incidentiem paziņo CSIRT vai kompetentajai iestādei trīs posmos: agrīnais brīdinājums, paziņojums par incidentu, galīgais ziņojums. Termiņus skaita no uzzināšanas par incidentu.",
    "ue.obowiazki.12": "Vai vienība spēj 24 stundu laikā no uzzināšanas par būtisku incidentu iesniegt agrīno brīdinājumu, norādot, vai incidentu, iespējams, izraisījusi nelikumīga darbība un vai tam varētu būt pārrobežu ietekme?",
    "ue.obowiazki.13": "24 stundas no uzzināšanas",
    "ue.obowiazki.14": "Vai vienība spēj 72 stundu laikā iesniegt paziņojumu par incidentu ar sākotnējo smaguma un ietekmes novērtējumu un kompromitēšanas indikatoriem?",
    "ue.obowiazki.15": "72 stundas no uzzināšanas",
    "ue.obowiazki.16": "Vai vienība ne vēlāk kā mēneša laikā pēc paziņojuma iesniedz galīgo ziņojumu ar incidenta aprakstu, draudu veidu, mazināšanas pasākumiem un pārrobežu ietekmi?",
    "ue.obowiazki.17": "mēnesis no paziņojuma",
    "ue.obowiazki.18": "Vai vienība informē savu pakalpojumu saņēmējus par būtiskiem incidentiem, kas varētu negatīvi ietekmēt šo pakalpojumu sniegšanu?",
    "ue.obowiazki.19": "Vai vienība informē pakalpojumu saņēmējus par būtisku kiberdraudu un par pasākumiem, ko saņēmēji var veikt?",
    "ue.obowiazki.2": "Dalībvalstis izveido būtisko un svarīgo vienību sarakstu un pieprasa vienībām iesniegt reģistrācijas datus. Kārtību, termiņu un portālu nosaka nacionālie tiesību akti.",
    "ue.obowiazki.20": "Ja vienība ir uzticamības pakalpojumu sniedzējs — vai tā par būtiskiem incidentiem paziņo 24 stundu laikā no uzzināšanas?",
    "ue.obowiazki.21": "attiecas uz uzticamības pakalpojumu sniedzējiem",
    "ue.obowiazki.22": "Pārvaldības struktūra",
    "ue.obowiazki.23": "Pārvaldības struktūra apstiprina riska pārvaldības pasākumus, uzrauga to īstenošanu un var tikt saukta pie atbildības. Struktūras locekļi regulāri piedalās apmācībā.",
    "ue.obowiazki.24": "Vai pārvaldības struktūra ir formāli apstiprinājusi kiberdrošības riska pārvaldības pasākumus, kas veikti, lai izpildītu 21. pantu?",
    "ue.obowiazki.25": "Vai pārvaldības struktūra dokumentēti uzrauga šo pasākumu īstenošanu — piemēram, ar periodiskiem ziņojumiem un pārskatīšanām?",
    "ue.obowiazki.26": "Vai pārvaldības struktūras locekļi regulāri piedalās apmācībā, kas ļauj identificēt riskus un novērtēt riska pārvaldības praksi, un vai dalība tiek dokumentēta?",
    "ue.obowiazki.27": "Gatavība uzraudzības pasākumiem",
    "ue.obowiazki.28": "Būtiska vienība ir pakļauta ex ante un ex post uzraudzībai, svarīga vienība — tikai ex post. Iestāde var pieprasīt informāciju, politikas īstenošanas pierādījumus un revīziju rezultātus.",
    "ue.obowiazki.29": "Vai vienība spēj pēc iestādes pieprasījuma iesniegt kiberdrošības politikas īstenošanas pierādījumus, tostarp drošības revīziju rezultātus?",
    "ue.obowiazki.3": "Vai vienība ir noteikusi, vai tā ir būtiska vai svarīga vienība, pamatojoties uz I vai II pielikuma nozari un uzņēmuma lielumu?",
    "ue.obowiazki.30": "Vai vienība spēj pēc iestādes pieprasījuma darīt pieejamus datus, dokumentus un informāciju, kas nepieciešami uzraudzības uzdevumu veikšanai?",
    "ue.obowiazki.31": "Vai būtiskā vienība ir gatava iestādes vai neatkarīgas struktūras veiktai drošības revīzijai par saviem līdzekļiem?",
    "ue.obowiazki.4": "Vai vienība ir iesniegusi kompetentajai iestādei reģistrācijas datus: nosaukumu, adresi un kontaktinformāciju, nozari un apakšnozari, to dalībvalstu sarakstu, kurās tā sniedz pakalpojumus?",
    "ue.obowiazki.5": "Kontaktinformācija ietver e-pasta adreses, IP adrešu diapazonus un tālruņa numurus. Nacionālo reģistrācijas termiņu un portālu nosaka dalībvalsts tiesību akti.",
    "ue.obowiazki.6": "Vai ir procedūra reģistrācijas datu atjaunināšanai bez nepamatotas kavēšanās pēc to izmaiņām?",
    "ue.obowiazki.7": "Direktīva prasa atjaunināt bez nepamatotas kavēšanās; konkrēts termiņš — piemēram, 14 dienas Polijā — izriet no nacionālajiem tiesību aktiem.",
    "ue.obowiazki.8": "Ja vienība ir DNS pakalpojumu sniedzējs, augstākā līmeņa domēna vārdu reģistrs, mākoņdatošanas, datu centra, CDN, pārvaldītu pakalpojumu sniedzējs, tiešsaistes tirdzniecības vieta, meklētājprogramma vai sociālais tīkls — vai tā ir iesniegusi 27. panta papildu datus, tostarp galvenās uzņēmējdarbības vietas Savienībā adresi?",
    "ue.obowiazki.9": "attiecas uz 26. panta 1. punktā minētajām vienībām",
    "ue.role.1": "Dalībvalsts kompetentā iestāde",
    "ue.role.10": "Datu centra pakalpojumi: kolokācija, infrastruktūras mitināšana un saistītie pakalpojumi.",
    "ue.role.11": "Datu centri",
    "ue.role.12": "Būtiska vienība virs vidēja uzņēmuma sliekšņa (3. panta 1. punkta a) apakšpunkts), svarīga — vidējā lielumā (3. panta 2. punkts). Zem vidējā lieluma — ārpus darbības jomas, ja vien dalībvalsts vienību nenosaka saskaņā ar 2. panta 2. punkta b)–e) apakšpunktu. Piemērojama Regula 2024/2690.",
    "ue.role.13": "Interneta plūsmu apmaiņas punkta sniedzējs",
    "ue.role.14": "Infrastruktūra, kas ļauj apmainīties ar datu plūsmu starp neatkarīgiem tīkliem.",
    "ue.role.15": "Interneta plūsmu apmaiņas punkti",
    "ue.role.16": "Klasifikācija pēc lieluma (3. panta 1. punkta a) apakšpunkts un 2. punkts). Regula 2024/2690 plūsmu apmaiņas punktus neaptver — regulas 1. pantā ir slēgts adresātu saraksts.",
    "ue.role.17": "DNS pakalpojumu sniedzējs",
    "ue.role.18": "Domēna vārdu atrises pakalpojumi, izņemot saknes vārdu serveru operatorus.",
    "ue.role.19": "Domēna vārdu sistēma",
    "ue.role.2": "kompetentā iestāde",
    "ue.role.20": "Būtiska vienība neatkarīgi no lieluma (3. panta 1. punkta b) apakšpunkts). Piemērojama Regula 2024/2690.",
    "ue.role.21": "Augstākā līmeņa domēna vārdu reģistrs",
    "ue.role.22": "Augstākā līmeņa domēna reģistra uzturēšana.",
    "ue.role.23": "Būtiska vienība neatkarīgi no lieluma (3. panta 1. punkta b) apakšpunkts). Papildus 28. panta pienākumi attiecībā uz reģistrācijas datiem. Piemērojama Regula 2024/2690.",
    "ue.role.24": "Mākoņdatošanas pakalpojumu sniedzējs",
    "ue.role.25": "Mākoņdatošanas pakalpojumi: infrastruktūra, platforma, programmatūra kā pakalpojums.",
    "ue.role.26": "Mākoņdatošanas pakalpojumi",
    "ue.role.27": "Klasifikācija pēc lieluma (3. panta 1. punkta a) apakšpunkts un 2. punkts). Piemērojama Regula 2024/2690.",
    "ue.role.28": "Satura piegādes tīkla sniedzējs",
    "ue.role.29": "Izkliedētu serveru tīkls, kas piegādā saturu un pakalpojumus galalietotājiem.",
    "ue.role.3": "noteikta nacionālajos tiesību aktos; līdz nacionālā moduļa ieviešanai rīks konkrētu iestādi nenorāda",
    "ue.role.30": "Satura piegādes tīkli",
    "ue.role.31": "Uzticamības pakalpojumu sniedzējs",
    "ue.role.32": "Uzticamības pakalpojumi Regulas (ES) Nr. 910/2014 nozīmē: paraksti, zīmogi, laika zīmogi, sertifikāti.",
    "ue.role.33": "Uzticamības pakalpojumi",
    "ue.role.34": "Direktīva piemērojama neatkarīgi no lieluma (2. panta 2. punkta a) apakšpunkta ii) punkts). Kvalificēts sniedzējs ir būtiska vienība neatkarīgi no lieluma (3. panta 1. punkta b) apakšpunkts); nekvalificēts ir būtiska virs vidēja uzņēmuma sliekšņa, citādi — svarīga. Piemērojama Regula 2024/2690.",
    "ue.role.35": "Pārvaldītu pakalpojumu sniedzējs",
    "ue.role.36": "Klienta IKT infrastruktūras pārvaldība: uzstādīšana, uzturēšana, atbalsts, sistēmu administrēšana.",
    "ue.role.37": "IKT pakalpojumu pārvaldība (B2B)",
    "ue.role.38": "Pārvaldīti pakalpojumi",
    "ue.role.39": "Pārvaldītu drošības pakalpojumu sniedzējs",
    "ue.role.4": "Publisko elektronisko sakaru tīklu vai publiski pieejamu elektronisko sakaru pakalpojumu sniedzējs",
    "ue.role.40": "Pārvaldīti kiberdrošības pakalpojumi: uzraudzība, reaģēšana uz incidentiem, testēšana, konsultācijas.",
    "ue.role.41": "Pārvaldīti drošības pakalpojumi",
    "ue.role.42": "Direktīva klasificē pēc lieluma (3. panta 1. punkta a) apakšpunkts un 2. punkts). Dalībvalstis var slieksni pastiprināt — Polija MSSP uzskata par būtisku vienību jau no maza uzņēmuma; šis modulis piemēro tikai direktīvas noteikumu. Piemērojama Regula 2024/2690.",
    "ue.role.5": "Publisko elektronisko sakaru tīklu nodrošināšana vai publiski pieejamu elektronisko sakaru pakalpojumu, tostarp piekļuves internetam, sniegšana.",
    "ue.role.6": "Digitālā infrastruktūra",
    "ue.role.7": "Elektroniskie sakari",
    "ue.role.8": "Direktīva piemērojama neatkarīgi no lieluma (2. panta 2. punkta a) apakšpunkta i) punkts). Vidējs vai lielāks uzņēmums ir būtiska vienība (3. panta 1. punkta c) apakšpunkts), mikrouzņēmums un mazs uzņēmums — svarīga (3. panta 2. punkts). Nacionālais elektronisko sakaru likums var uzlikt papildu pienākumus — šis modulis tos nesatur.",
    "ue.role.9": "Datu centra pakalpojumu sniedzējs",
    "ue.role.podstawaArt3b": "Direktīvas (ES) 2022/2555 3. panta 1. punkta b) apakšpunkts",
    "ue.zaslepki.1": "Eiropas Parlamenta un Padomes Direktīva (ES) 2022/2555 (TID 2)",
    "ue.zaslepki.10": "Vai daļa vienību tiek ierakstīta ex officio, lemj nacionālie tiesību akti.",
    "ue.zaslepki.11": "Noskaidrojiet, vai uz jums attiecas direktīva",
    "ue.zaslepki.12": "I vai II pielikuma nozare un uzņēmuma lielums. Šo daļu veic subjekta profils šajā rīkā.",
    "ue.zaslepki.13": "Noskaidrojiet savas valsts kompetento iestādi",
    "ue.zaslepki.14": "Katra valsts izraugās kompetento iestādi (8. panta 1. punkts). Aktuālo sarakstu uztur ENISA un Komisija.",
    "ue.zaslepki.15": "Iesniedziet reģistrācijas datus",
    "ue.zaslepki.16": "Nosaukums, adrese un kontaktinformācija, nozare un apakšnozare, pakalpojumu sniegšanas valstis (3. panta 4. punkts). Kārtība saskaņā ar nacionālajiem tiesību aktiem.",
    "ue.zaslepki.17": "Atjauniniet datus bez nepamatotas kavēšanās",
    "ue.zaslepki.18": "Katra reģistrācijas datu izmaiņa prasa atjaunināšanu (3. panta 5. punkts).",
    "ue.zaslepki.19": "adrese un aktuālā kontaktinformācija: e-pasta adreses, IP adrešu diapazoni, tālruņa numuri",
    "ue.zaslepki.2": "ES OV L 333, 27.12.2022., 80. lpp.",
    "ue.zaslepki.20": "I vai II pielikuma nozare un apakšnozare",
    "ue.zaslepki.21": "to dalībvalstu saraksts, kurās vienība sniedz pakalpojumus",
    "ue.zaslepki.22": "Nosaka nacionālie tiesību akti.",
    "ue.zaslepki.23": "Direktīva (ES) 2022/2555 — 3. pants",
    "ue.zaslepki.24": "ENISA — dalībvalstu kompetentās iestādes",
    "ue.zaslepki.25": "Direktīva (ES) 2022/2555",
    "ue.zaslepki.26": "ES modulis nesatur nacionālās iestādes vadlīnijas — tās parādīsies kopā ar nacionālo tiesību aktu moduli.",
    "ue.zaslepki.27": "Automātiska reģistra datu iegūšana darbojas tikai valstīm ar nacionālo tiesību aktu moduli. Aizpildiet profilu manuāli.",
    "ue.zaslepki.28": "Finanšu pārskata nolasīšana darbojas tikai valstīm ar nacionālo tiesību aktu moduli. Ievadiet ieņēmumus un darbinieku skaitu manuāli.",
    "ue.zaslepki.3": "Komisijas Īstenošanas regula (ES) 2024/2690",
    "ue.zaslepki.4": "ES OV L, 2024/2690, 18.11.2024.",
    "ue.zaslepki.5": "TID 2 direktīvā nav atsevišķa elektronisko sakaru slāņa. Nacionālie elektronisko sakaru tiesību akti var uzlikt papildu pienākumus — šis modulis tos nezina.",
    "ue.zaslepki.6": "Būtisko un svarīgo vienību saraksts",
    "ue.zaslepki.7": "Dalībvalsts kompetentā iestāde.",
    "ue.zaslepki.8": "Direktīva uzliek dalībvalstīm pienākumu uzturēt būtisko un svarīgo vienību sarakstu un pieprasīt vienībām iesniegt reģistrācijas datus. Portālu, kārtību un termiņu nosaka nacionālie tiesību akti — šis modulis tos nezina, jo izvēlētās valsts nacionālo tiesību aktu modulis vēl nav sagatavots.",
    "ue.zaslepki.9": "Visas būtiskās un svarīgās vienības. Termiņu nosaka nacionālie tiesību akti.",
    "ue.zaslepki.skrotDyrektywy": "TID 2 direktīva",
    "ue.zaslepki.skrotReg2690": "Regula 2024/2690",
    "xlsx.1": "{p0} – {p1} EUR",
    "xlsx.25": "Valūtas kurss",
    "xlsx.4": "PĀRSKATS PAR ATBILSTĪBU TID 2 DIREKTĪVAI (ES) 2022/2555",
    "xlsx.58": "Elektronisko sakaru darbība: Regula (ES) 2024/2690 nav piemērojama. Sliekšņus nosaka nacionālie tiesību akti (direktīvas 23. panta 11. punkts) — kopējais modulis tos nezina.",
    "xlsx.68": "Rīks kalpo pašnovērtējumam. Tas nav ne audits, ne juridiska konsultācija.",
    "xlsx.69": "Subjektiem, uz kuriem Regula (ES) 2024/2690 neattiecas, būtiska incidenta sliekšņus nosaka nacionālie tiesību akti (direktīvas 23. panta 11. punkts).",
    "xlsx.70": "Profilā norādītās lomas ir deklarācija. Statusu nosaka faktiski veiktā darbība (Direktīvas (ES) 2022/2555 3. pants).",
    "xlsx.etykietaKrs": "Reģistra numurs",
    "xlsx.etykietaNip": "Identifikācijas numurs",
    "xlsx.etykietaRegon": "Statistikas numurs"
});
