/* Teksty modułu ue — język: mt.
   Te same klucze co w napisy/pl.js (wersja źródłowa); wstawki {p0}, {p1}…
   pozostają bez zmian. Klucze ue.cyt.* to wzorce składania odesłań
   do przepisów w tym języku — patrz kraje/ue/cytaty.js. */
KRAJE.napisy('ue', 'mt', {
    "app.10": "Iċċekkja l-lista tar-rwoli hawn taħt — l-istatus huwa ddeterminat mill-attività li fil-fatt titwettaq (l-Artikolu 3 tad-Direttiva (UE) 2022/2555), mhux minn entrata fir-reġistru.",
    "app.14": "Sena ta' qabel: EUR {p0}",
    "app.15": "Dħul għall-perjodu ta' rappurtar: EUR {p0}",
    "app.19": "Qed jiġu kkonsultati r-reġistri bin-numru {p0}…",
    "app.34": " biljun EUR",
    "app.35": " miljun EUR",
    "app.36": " elf EUR",
    "app.37": "",
    "app.4": "Il-ġbir awtomatiku tad-data mir-reġistru mhuwiex disponibbli għal dan il-pajjiż — imla l-profil manwalment.",
    "app.59": "Valutazzjoni tal-konformità mad-Direttiva NIS 2 (JSON)",
    "app.68": "Għal dan il-pajjiż m'hemm l-ebda reġistru li minnu l-għodda tista' tiġbor id-data — il-profil jimtela manwalment.",
    "app.69": "Għal dan il-pajjiż m'hemm l-ebda reġistru li minnu l-għodda tista' tiġbor id-data. Ikklikkja biex tixgħel il-modalità offline.",
    "app.73": " · kont tal-profitt u t-telf fil-verżjoni ",
    "app.74": "<div class=\"mt-2 tekst-uwaga\">Id-data tar-reġistru ma tindika l-ebda rwol fis-settur tal-infrastruttura diġitali. Agħżel ir-rwoli manwalment hawn taħt.</div>",
    "app.8": "Entrata fir-reġistru tal-fornituri tal-komunikazzjonijiet elettroniċi kkonfermata",
    "app.progDostawcy": "",
    "app.przyklad.adres": "1, Triq l-Eżempju, Belt",
    "app.przyklad.forma": "Kumpanija privata b'responsabbiltà limitata",
    "app.przyklad.nazwa": "Operatur Eżempju Ltd",
    "app.statusVat": " · status tal-VAT: ",
    "dashboard.1": "Abbażi tar-rwoli u d-daqs iddikjarati, l-entità la hija entità essenzjali u lanqas entità importanti fis-sens tal-Artikolu 3 tad-Direttiva (UE) 2022/2555. Iċċekkja l-profil jekk ir-riżultat ikun differenti minn dak mistenni.",
    "dashboard.113": "Mistoqsijiet frekwenti",
    "dashboard.12": "— {p0}; l-iskadenza għat-traspożizzjoni fil-liġi nazzjonali skadiet fil-{p2}",
    "dashboard.123": "Direttiva NIS 2",
    "dashboard.30": "Lista tal-entitajiet essenzjali u importanti",
    "dashboard.4": "— applikabbli direttament mill-{p0} fl-Istati Membri kollha, mingħajr traspożizzjoni",
    "dashboard.42": "Varjant b'ammont fiss: {p0}",
    "dashboard.45": "Kriterji tal-Artikolu 32(7) tad-Direttiva:",
    "dashboard.46": "Total",
    "dashboard.49": "L-entità twettaq attività ta' komunikazzjonijiet elettroniċi — ir-responsabbiltà tal-persuna maniġerjali hija ddeterminata mil-liġi nazzjonali",
    "dashboard.50": "",
    "dashboard.51": "",
    "dashboard.53": "Pagament perjodiku ta' penali għal dewmien fil-konformità ma' deċiżjoni: minn EUR {p0} sa EUR {p1} kuljum ({p2})",
    "dashboard.54": "Każ kwalifikat: sa EUR {p0} ({p1})",
    "dashboard.57": "({p0}). Minn meta l-awtorità nazzjonali tista' timponi multi huwa ddeterminat mill-att li jittrasponi d-Direttiva — dan il-modulu ma jafux. L-obbligi ta' implimentazzjoni joħorġu mil-liġi nazzjonali mill-jum tad-dħul fis-seħħ tagħha.",
    "dashboard.65": "({p0}). Minn meta l-awtorità nazzjonali tista' timponi multi huwa ddeterminat mill-att li jittrasponi d-Direttiva — dan il-modulu ma jafux. Għalhekk ir-riskju finanzjarju mhuwiex datat hawn, filwaqt li l-obbligi ta' implimentazzjoni joħorġu mil-liġi nazzjonali mill-jum tad-dħul fis-seħħ tagħha.",
    "dashboard.83": "Attività ta' komunikazzjonijiet elettroniċi — il-limiti huma stabbiliti mil-liġi nazzjonali.",
    "dashboard.84": "Ir-Regolament (UE) 2024/2690 ma japplikax għall-fornituri ta' netwerks u servizzi pubbliċi ta' komunikazzjonijiet elettroniċi. Għalihom, il-limiti ta' inċident sinifikanti huma stabbiliti mil-liġi nazzjonali (l-Artikolu 23(11) tad-Direttiva) — dan il-modulu ma jafhomx, għalhekk ma jagħtix ċifri.",
    "dashboard.terminRejestracji": "L-iskadenza għas-sottomissjoni tad-data ta' reġistrazzjoni hija stabbilita mil-liġi nazzjonali (l-Artikolu 3(4) tad-Direttiva). Il-fornituri skont l-Artikolu 27(1) — fornituri ta' servizzi tad-DNS, reġistri tal-ismijiet ta' dominju tal-ogħla livell, fornituri ta' servizzi tal-cloud computing, taċ-ċentru tad-data, ta' netwerks ta' twassil ta' kontenut, ta' servizzi ġestiti u ta' servizzi ta' sigurtà ġestiti — jissottomettu d-data tagħhom lir-reġistru tal-ENISA: oriġinarjament sas-17 ta' Jannar 2025, u kull bidla mingħajr dewmien żejjed.",
    "html.1": "ITORO — Valutazzjoni tal-konformità mad-Direttiva NIS 2 (UE) 2022/2555",
    "html.10": "Valutazzjoni tal-konformità mad-Direttiva NIS 2 — modulu komuni",
    "html.100": "Il-qari ta' rapport finanzjarju jaħdem biss għal pajjiżi b'modulu tal-liġi nazzjonali. Għal dan il-pajjiż iddaħħal id-<strong>dħul</strong> għas-sena finanzjarja manwalment — il-livell tal-multa jiddependi minnu.",
    "html.102": "Il-ġbir awtomatiku tad-data mir-reġistru jaħdem biss għal pajjiżi b'modulu tal-liġi nazzjonali. Ir-rwoli u d-daqs tal-intrapriża tindikahom manwalment.",
    "html.11": "Id-Direttiva (UE) 2022/2555 (NIS 2) teħtieġ traspożizzjoni fil-liġi nazzjonali. Il-valutazzjoni tkopri l-obbligi li joħorġu direttament mid-Direttiva u r-Regolament ta' Implimentazzjoni tal-Kummissjoni (UE) 2024/2690, li japplika direttament — sa fejn jikkonċernaw l-entità.",
    "html.23": "id-dħul u d-daqs iddaħħalhom manwalment — il-modulu komuni ma jikkonsultax ir-reġistri nazzjonali",
    "html.33": "Direttiva (UE) 2022/2555 tal-Parlament Ewropew u tal-Kunsill tal-14 ta' Diċembru 2022 (NIS 2)",
    "html.33a": "{p0} — l-att nazzjonali li jittrasponi d-Direttiva; dan il-modulu għadu ma jivvalutax ir-rekwiżiti tiegħu",
    "html.33b": "l-Istat għadu ma adottax att ta' traspożizzjoni — il-valutazzjoni ssegwi d-dritt tal-Unjoni",
    "html.35": "obbligi tal-korp ta' ġestjoni — l-Artikolu 20 tad-Direttiva",
    "html.36": "L-għodda sservi għall-awtovalutazzjoni. La hija awditu u lanqas parir legali.",
    "html.40": "il-modulu komuni ma jagħmel l-ebda konnessjoni 'l barra — ma jikkonsultax ir-reġistri",
    "html.59": "Rapporti finanzjarji",
    "html.60": "Il-qari ta' rapport finanzjarju huwa disponibbli biss għal pajjiżi b'modulu tal-liġi nazzjonali. Għal dan il-pajjiż iddaħħal id-dħul u n-numru ta' impjegati manwalment.",
    "html.62": "Tfittxija fir-reġistru",
    "html.63": "ir-reġistri kummerċjali huma nazzjonali — il-modulu komuni ma jafhomx",
    "html.64": "ir-rwoli u d-daqs tal-intrapriża tindikahom manwalment",
    "html.66": "Numru ta' identifikazzjoni tal-entità",
    "html.68": "Il-ġbir awtomatiku tad-data mir-reġistru jaħdem biss għal pajjiżi b'modulu tal-liġi nazzjonali.",
    "html.76": "Dħul annwali (EUR)",
    "html.78": "Dħul mill-attività ta' komunikazzjonijiet elettroniċi (EUR)",
    "html.79": "Il-qasam jikkonċerna fornituri ta' netwerks jew servizzi pubbliċi ta' komunikazzjonijiet elettroniċi. Il-limiti nazzjonali huma stabbiliti mil-liġi tal-Istat Membru.",
    "html.80": "Remunerazzjoni ta' kull xahar tal-kap (EUR)",
    "html.82": "Rata tal-kambju",
    "html.83": "Il-limiti massimi tal-multi fid-Direttiva huma espressi f'euro. Il-konverżjoni għall-munita nazzjonali u r-rata huma ddeterminati mil-liġi nazzjonali — hawnhekk l-ammonti jingħataw f'euro mingħajr konverżjoni.",
    "html.84": "L-istatus joħroġ esklużivament mill-aggregazzjoni tad-data ta' intrapriżi marbuta, u s-sistema tal-informazzjoni tal-entità hija indipendenti (il-premessa 16 tad-Direttiva — il-liġi nazzjonali tiddeċiedi dwar l-applikazzjoni)",
    "html.85": "L-entità topera fl-oqsma tas-sigurtà nazzjonali, is-sigurtà pubblika, id-difiża jew l-infurzar tal-liġi (l-Artikolu 2(7) tad-Direttiva)",
    "html.91": "Valutazzjoni tal-konformità mad-Direttiva (UE) 2022/2555 tal-Parlament Ewropew u tal-Kunsill (NIS 2) u mar-Regolament ta' Implimentazzjoni tal-Kummissjoni (UE) 2024/2690 — modulu komuni għall-pajjiżi li l-modulu tal-liġi nazzjonali tagħhom għadu mhux lest.",
    "html.94": "jekk l-entità hijiex <strong>essenzjali</strong>, <strong>importanti</strong> jew barra mill-kamp ta' applikazzjoni tad-Direttiva",
    "html.daneZeSprawozdania": "isem, numru ta' identifikazzjoni, indirizz tas-sede",
    "html.rejestrMozliwy": "Ir-reġistru {p0} huwa pubbliku u bla ħlas — il-qari tiegħu jista’ jiżdied; nilqgħu pull requests (ara r-README).",
    "html.tytulNaglowka": "Valutazzjoni tal-konformità mad-Direttiva NIS 2",
    "html.zrodlaRecznie": "Dan il-modulu ma jafx ir-reġistri tal-pajjiż tiegħek — imla l-profil bl-idejn. Il-fatturat annwali jiddetermina l-multa massima, għalhekk daħħlu b’mod preċiż.",
    "klasyfikacja.10": "l-Artikolu 3(1)(c) tad-Direttiva (UE) 2022/2555 (fornitur ta' netwerks pubbliċi ta' komunikazzjonijiet elettroniċi jew ta' servizzi ta' komunikazzjonijiet elettroniċi disponibbli għall-pubbliku li huwa mill-inqas intrapriża medja)",
    "klasyfikacja.11": "l-Artikolu 3(2) flimkien mal-Artikolu 2(2)(a)(i) tad-Direttiva (UE) 2022/2555 (fornitur ta' netwerks jew servizzi pubbliċi ta' komunikazzjonijiet elettroniċi li huwa mikrointrapriża jew intrapriża żgħira)",
    "klasyfikacja.12": "l-Artikolu 3(1)(a) tad-Direttiva (UE) 2022/2555 (fornitur ta' servizzi ta' sigurtà ġestiti li jaqbeż il-limiti massimi għal intrapriża medja)",
    "klasyfikacja.13": "Il-mikrointrapriżi u l-intrapriżi żgħar mhumiex koperti mid-Direttiva minħabba dan ir-rwol (l-Artikolu 2(1) a contrario).",
    "klasyfikacja.15": "l-Artikolu 3(1)(b) tad-Direttiva (UE) 2022/2555 (fornitur kwalifikat ta' servizzi fiduċjarji) — irrispettivament mid-daqs tal-intrapriża",
    "klasyfikacja.16": "l-Artikolu 3(2) flimkien mal-Artikolu 2(2)(a)(ii) tad-Direttiva (UE) 2022/2555 (fornitur mhux kwalifikat ta' servizzi fiduċjarji li huwa mikrointrapriża, intrapriża żgħira jew medja)",
    "klasyfikacja.18": "l-Artikolu 3(2) tad-Direttiva (UE) 2022/2555 (entità tal-amministrazzjoni pubblika fil-livell reġjonali, fejn l-Istat Membru jipprovdi hekk — l-Artikolu 2(2)(f)(ii))",
    "klasyfikacja.19": "l-Artikolu 3(1)(f) tad-Direttiva (UE) 2022/2555 (entità tal-amministrazzjoni pubblika fil-livell tal-gvern ċentrali — l-Artikolu 2(2)(f)(i))",
    "klasyfikacja.2": "Superviżjoni ex ante u ex post (l-Artikolu 32 tad-Direttiva (UE) 2022/2555).",
    "klasyfikacja.20": "l-Artikolu 3(2) tad-Direttiva (UE) 2022/2555 (entità tal-amministrazzjoni pubblika fil-livell reġjonali — l-Artikolu 2(2)(f)(ii))",
    "klasyfikacja.21": "L-ambitu tal-obbligi tal-entitajiet tal-amministrazzjoni pubblika fil-livell lokali huwa ddeterminat mil-liġi nazzjonali (l-Artikolu 2(5)(a) tad-Direttiva).",
    "klasyfikacja.22": "Stat Membru jista' jeżenta entitajiet li jwettqu attivitajiet fl-oqsma tas-sigurtà nazzjonali, is-sigurtà pubblika, id-difiża jew l-infurzar tal-liġi (l-Artikolu 2(7) tad-Direttiva). L-eżenzjoni ma taħdimx waħedha — ivverifika r-riżultat tal-valutazzjoni skont il-liġi nazzjonali.",
    "klasyfikacja.23": "L-entità tissodisfa l-kriterji kemm ta' entità essenzjali kif ukoll ta' entità importanti. Hija entità essenzjali (l-Artikolu 3(1) tad-Direttiva), u r-rekwiżiti aktar stretti japplikaw għall-attività kollha koperta mid-Direttiva.",
    "klasyfikacja.25": "L-entità hija essenzjali, għalhekk japplikaw il-katalgu sħiħ tal-miżuri skont l-Artikolu 21(2) tad-Direttiva u s-superviżjoni ex ante u ex post — il-valutazzjoni tkopri s-sett sħiħ ta' mistoqsijiet.",
    "klasyfikacja.26": "Bħala entità importanti intom soġġetti għall-istess katalgu ta' miżuri skont l-Artikolu 21(2), iżda għas-superviżjoni ex post biss (l-Artikolu 33). Il-limitu massimu tal-multa huwa aktar baxx: EUR 7 miljun jew 1,4 % tal-fatturat (l-Artikolu 34(5)). Eżenzjonijiet għall-entitajiet pubbliċi jistgħu jiġu introdotti mil-liġi nazzjonali — dan il-modulu ma jafhomx.",
    "klasyfikacja.28": "L-obbligi tal-entitajiet tal-amministrazzjoni pubblika joħorġu mill-Artikolu 2(2)(f) tad-Direttiva; l-ambitu eżatt tagħhom, inkluż għal-livell lokali u l-istituzzjonijiet edukattivi, huwa ddeterminat mil-liġi nazzjonali (l-Artikolu 2(5)).",
    "klasyfikacja.29": "Ġie ddikjarat li l-istatus tal-entità jirriżulta biss mill-aggregazzjoni tad-data ta' intrapriżi marbuta jew sħab, u li s-sistema tal-informazzjoni tal-entità hija indipendenti. Id-Direttiva tippermetti tali esklużjoni (il-premessa 16), iżda l-liġi nazzjonali tiddeċiedi dwarha — il-modulu jaċċetta l-esklużjoni, li trid tiġi vverifikata skont il-liġi tal-Istat Membru u dokumentata.",
    "klasyfikacja.4": "Superviżjoni ex post biss — fejn hemm evidenza, indikazzjoni jew informazzjoni ta' ksur (l-Artikolu 33 tad-Direttiva (UE) 2022/2555).",
    "klasyfikacja.5": "Barra mill-kamp ta' applikazzjoni tad-Direttiva",
    "klasyfikacja.6": "Għar-rwol indikat ma joħorġu l-ebda obbligi mid-Direttiva (UE) 2022/2555.",
    "klasyfikacja.7": "l-Artikolu 3(1)(a) tad-Direttiva (UE) 2022/2555 (entità ta' tip elenkat fl-Anness I li taqbeż il-limiti massimi għal intrapriża medja)",
    "klasyfikacja.8": "l-Artikolu 3(2) tad-Direttiva (UE) 2022/2555 (entità ta' tip elenkat fl-Anness I li tissodisfa l-kriterji għal intrapriża medja)",
    "klasyfikacja.9": "Il-mikrointrapriżi u l-intrapriżi żgħar mhumiex koperti mid-Direttiva minħabba dan ir-rwol (l-Artikolu 2(1) a contrario).",
    "kreator.10": "Daħħal id-dħul tas-sena ta' qabel manwalment.",
    "kreator.35": "<span class=\"text-secondary\">Il-qari tar-rapporti finanzjarji mhuwiex disponibbli għal dan il-pajjiż.</span>",
    "kreator.37": "Il-qari tar-rapporti finanzjarji mhuwiex disponibbli għal dan il-pajjiż — daħħal id-dħul manwalment.",
    "kreator.56": "Iva — ir-Regolament tal-UE japplika direttament mis-7 ta' Novembru 2024 fl-Istati Membri kollha u m'għandu l-ebda perjodu tranżitorju. Il-bażi tiegħu hija",
    "kreator.57": ", li ta s-setgħa lill-Kummissjoni biex tistabbilixxi r-rekwiżiti tekniċi u metodoloġiċi għall-fornituri elenkati fl-Artikolu 3(1) tar-Regolament. L-iskadenza għat-traspożizzjoni tad-Direttiva skadiet fis-",
    "kreator.58": ", u minn meta l-awtorità nazzjonali tista' timponi multi huwa ddeterminat mil-liġi nazzjonali. Ir-rekwiżiti tekniċi tal-Anness (it-taqsimiet 6 u 9–13) huma vinkolanti kif inhuma — ma jistennewx kjarifika. Deroga hija possibbli biss mir-rekwiżiti bil-klawżola \"fejn xieraq\", u biss b'ġustifikazzjoni dokumentata.",
    "kreator.9": "Rapporti finanzjarji →",
    "kreator.przepisReg2690": "l-Artikolu 21(5) tad-Direttiva (UE) 2022/2555",
    "kreator.terminReg2690": "17 ta' Ottubru 2024",
    "punktacja.10": "Entitajiet pubbliċi",
    "punktacja.4": "Direttiva NIS 2 — l-Artikolu 21",
    "punktacja.5": "Direttiva NIS 2 — obbligi formali",
    "punktacja.8": "Komunikazzjonijiet elettroniċi",
    "punktacja.9": "Direttiva NIS 2 — entitajiet pubbliċi",
    "punktacja.skrotKsc": "NIS 2",
    "punktacja.skrotPke": "telekom",
    "ue.cyt.akapit": ", it-{p0} subparagrafu",
    "ue.cyt.art": "l-Artikolu {p0}",
    "ue.cyt.drugi": "tieni",
    "ue.cyt.dyr": "{p0} tad-Direttiva (UE) 2022/2555",
    "ue.cyt.i": "u",
    "ue.cyt.laczenie": "",
    "ue.cyt.lit": "({p0})",
    "ue.cyt.litery": "",
    "ue.cyt.pkt": ", il-punt {p0}",
    "ue.cyt.rozdzielacz": "; ",
    "ue.cyt.rozp": "{p0} tar-Regolament (UE) 2024/2690",
    "ue.cyt.ust": "({p0})",
    "ue.katalog.1": "Politiki dwar l-analiżi tar-riskju u s-sigurtà tas-sistemi tal-informazzjoni",
    "ue.katalog.10": "Trattament tal-inċidenti",
    "ue.katalog.11": "It-trattament tal-inċidenti jinkludi l-azzjonijiet u l-proċeduri kollha maħsuba biex jipprevjenu, jidentifikaw, janalizzaw u jrażżnu inċident jew biex jirrispondu għalih u jirkupraw minnu (l-Artikolu 6, il-punt (8)).",
    "ue.katalog.12": "Hemm proċedura dokumentata għat-trattament tal-inċidenti li tkopri l-identifikazzjoni, l-analiżi, it-trażżin, ir-rispons u l-irkupru?",
    "ue.katalog.13": "ISO/IEC 27001 A.5.24–A.5.26",
    "ue.katalog.14": "Il-proċedura tippermetti li jiġu rrispettati l-iskadenzi għar-rappurtar ta' inċident sinifikanti: twissija bikrija fi żmien 24 siegħa, notifika tal-inċident fi żmien 72 siegħa, rapport finali fi żmien xahar?",
    "ue.katalog.15": "ISO/IEC 27001 A.5.24",
    "ue.katalog.16": "L-entità għandha kriterji biex inċident jitqies sinifikanti, konsistenti mal-Artikolu 23(3): tfixkil operazzjonali serju jew telf finanzjarju, jew ħsara konsiderevoli lil persuni oħra?",
    "ue.katalog.17": "ISO/IEC 27001 A.5.25",
    "ue.katalog.18": "L-inċidenti jiġu rreġistrati u t-tagħlimiet mit-trattament tagħhom jintużaw biex jittejbu l-miżuri?",
    "ue.katalog.19": "ISO/IEC 27001 A.5.27",
    "ue.katalog.2": "Il-miżuri huma bbażati fuq approċċ li jqis il-perikli kollha (l-Artikolu 21(2)). Il-proporzjonalità tagħhom tiġi vvalutata billi jitqiesu l-grad ta' espożizzjoni, id-daqs tal-entità, il-probabbiltà tal-inċidenti u s-severità tagħhom (l-Artikolu 21(1), it-tieni subparagrafu).",
    "ue.katalog.20": "Kontinwità tan-negozju u ġestjoni tal-kriżijiet",
    "ue.katalog.21": "Kontinwità tan-negozju, bħall-ġestjoni tal-backups u l-irkupru minn diżastri, u ġestjoni tal-kriżijiet.",
    "ue.katalog.22": "Hemm pjan ta' kontinwità tan-negozju li jkopri l-irkupru wara diżastru?",
    "ue.katalog.23": "ISO/IEC 27001 A.5.29–A.5.30",
    "ue.katalog.24": "Il-backups isiru, jiġu protetti u ttestjati għall-possibbiltà ta' restawr?",
    "ue.katalog.25": "ISO/IEC 27001 A.8.13",
    "ue.katalog.26": "L-entità għandha proċeduri ta' ġestjoni tal-kriżijiet bi rwoli u kanali ta' komunikazzjoni definiti?",
    "ue.katalog.27": "ISO/IEC 27001 A.5.29",
    "ue.katalog.28": "Il-pjanijiet ta' kontinwità u ta' rkupru jiġu ttestjati perjodikament, bir-riżultati dokumentati?",
    "ue.katalog.29": "ISO/IEC 27001 A.5.30",
    "ue.katalog.3": "L-entità għandha politika dokumentata dwar l-analiżi tar-riskju u s-sigurtà tas-sistemi tal-informazzjoni, approvata mill-korp ta' ġestjoni?",
    "ue.katalog.30": "Sigurtà tal-katina tal-provvista",
    "ue.katalog.31": "Sigurtà tal-katina tal-provvista, inklużi l-aspetti relatati mas-sigurtà li jikkonċernaw ir-relazzjonijiet bejn l-entità u l-fornituri diretti jew il-fornituri ta' servizzi tagħha. L-entità tqis il-vulnerabbiltajiet speċifiċi għal kull fornitur u l-kwalità ġenerali tal-prodotti u tal-prattiki taċ-ċibersigurtà tiegħu (l-Artikolu 21(3)).",
    "ue.katalog.32": "L-entità żżomm lista ta' fornituri diretti u fornituri ta' servizzi flimkien ma' valutazzjoni tas-sinifikat tagħhom għas-sigurtà tan-netwerks u tas-sistemi?",
    "ue.katalog.33": "ISO/IEC 27001 A.5.19",
    "ue.katalog.34": "Meta jintgħażlu l-miżuri għall-fornituri, jitqiesu l-vulnerabbiltajiet speċifiċi għal kull wieħed minnhom u l-kwalità tal-prattiki taċ-ċibersigurtà u tal-iżvilupp sigur tagħhom?",
    "ue.katalog.35": "ISO/IEC 27001 A.5.19, A.5.21",
    "ue.katalog.36": "Il-kuntratti mal-fornituri fihom rekwiżiti ta' sigurtà u obbligu li jiġu rrappurtati inċidenti u vulnerabbiltajiet?",
    "ue.katalog.37": "ISO/IEC 27001 A.5.20",
    "ue.katalog.38": "L-entità tqis ir-riżultati tal-valutazzjonijiet ikkoordinati tar-riskju għas-sigurtà tal-ktajjen tal-provvista kritiċi msemmija fl-Artikolu 22?",
    "ue.katalog.39": "ISO/IEC 27001 A.5.21",
    "ue.katalog.4": "ISO/IEC 27001 klawżoli 5.2, 6.1.2",
    "ue.katalog.40": "Sigurtà fl-akkwist, l-iżvilupp u l-manutenzjoni tas-sistemi",
    "ue.katalog.41": "Sigurtà fl-akkwist, l-iżvilupp u l-manutenzjoni tas-sistemi tan-netwerks u tal-informazzjoni, inklużi t-trattament u d-divulgazzjoni tal-vulnerabbiltajiet.",
    "ue.katalog.42": "Ir-rekwiżiti ta' sigurtà jiġu definiti qabel ma sistema tiġi akkwistata jew jibda l-iżvilupp tagħha, u vverifikati qabel l-implimentazzjoni?",
    "ue.katalog.43": "ISO/IEC 27001 A.8.25–A.8.29",
    "ue.katalog.44": "Hemm proċess ta' trattament tal-vulnerabbiltajiet: identifikazzjoni, valutazzjoni, rimedju fi żmien definit?",
    "ue.katalog.45": "ISO/IEC 27001 A.8.8",
    "ue.katalog.46": "L-entità għandha proċedura ta' divulgazzjoni tal-vulnerabbiltajiet, inkluż kanal biex jiġu riċevuti rapporti minn partijiet terzi?",
    "ue.katalog.47": "Il-bidliet fis-sistemi jgħaddu minn proċess ikkontrollat ta' ġestjoni tal-bidliet b'valutazzjoni tal-impatt fuq is-sigurtà?",
    "ue.katalog.48": "ISO/IEC 27001 A.8.32",
    "ue.katalog.49": "Valutazzjoni tal-effettività tal-miżuri",
    "ue.katalog.5": "L-analiżi tar-riskju tkopri l-perikli kollha għas-sistemi tan-netwerks u tal-informazzjoni u l-ambjent fiżiku tagħhom, mhux biss it-theddid ċibernetiku?",
    "ue.katalog.50": "Politiki u proċeduri għall-valutazzjoni tal-effettività tal-miżuri tal-ġestjoni tar-riskju taċ-ċibersigurtà.",
    "ue.katalog.51": "Hemm politika dokumentata għall-valutazzjoni tal-effettività tal-miżuri li tiddefinixxi l-ambitu, il-frekwenza u l-metodi?",
    "ue.katalog.52": "ISO/IEC 27001 klawżola 9.1",
    "ue.katalog.53": "Il-valutazzjonijiet tal-effettività jsiru perjodikament u r-riżultati tagħhom jiġu rrappurtati lill-korp ta' ġestjoni?",
    "ue.katalog.54": "ISO/IEC 27001 klawżoli 9.2–9.3",
    "ue.katalog.55": "Id-dgħufijiet identifikati jwasslu għal azzjonijiet korrettivi dokumentati b'responsabbli u skadenza?",
    "ue.katalog.56": "ISO/IEC 27001 klawżola 10.1",
    "ue.katalog.57": "Iġjene ċibernetika u taħriġ",
    "ue.katalog.58": "Prattiki bażiċi ta' iġjene ċibernetika u taħriġ fiċ-ċibersigurtà. Il-membri tal-korp ta' ġestjoni jsegwu taħriġ regolari (l-Artikolu 20(2)).",
    "ue.katalog.59": "L-entità tapplika prattiki bażiċi ta' iġjene ċibernetika: aġġornamenti, ġestjoni tal-passwords, restrizzjoni tal-privileġġi, protezzjoni kontra l-malware?",
    "ue.katalog.6": "ISO/IEC 27001 klawżola 6.1.2",
    "ue.katalog.60": "ISO/IEC 27001 A.8.7, A.8.8",
    "ue.katalog.61": "L-impjegati jirċievu taħriġ fiċ-ċibersigurtà mfassal għar-rwol tagħhom, bil-parteċipazzjoni dokumentata?",
    "ue.katalog.62": "ISO/IEC 27001 A.6.3",
    "ue.katalog.63": "Il-membri tal-korp ta' ġestjoni jsegwu taħriġ regolari li jippermettilhom jidentifikaw ir-riskji u jivvalutaw il-prattiki tal-ġestjoni tar-riskju?",
    "ue.katalog.64": "ISO/IEC 27001 klawżola 7.2",
    "ue.katalog.65": "Kriptografija u kriptaġġ",
    "ue.katalog.66": "Politiki u proċeduri dwar l-użu tal-kriptografija u, fejn xieraq, tal-kriptaġġ.",
    "ue.katalog.67": "Hemm politika tal-kriptografija li tiddefinixxi liema data u kanali huma soġġetti għall-kriptaġġ u b'liema algoritmi?",
    "ue.katalog.68": "ISO/IEC 27001 A.8.24",
    "ue.katalog.69": "Iċ-ċwievet kriptografiċi jiġu ġestiti tul iċ-ċiklu tal-ħajja kollu: ġenerazzjoni, distribuzzjoni, ħażna, rotazzjoni, irtirar?",
    "ue.katalog.7": "L-għażla tal-miżuri tqis l-aktar teknoloġija avvanzata, l-istandards Ewropej u internazzjonali rilevanti u l-kost tal-implimentazzjoni?",
    "ue.katalog.70": "Riżorsi umani, kontroll tal-aċċess u ġestjoni tal-assi",
    "ue.katalog.71": "Sigurtà tar-riżorsi umani, politiki ta' kontroll tal-aċċess u ġestjoni tal-assi.",
    "ue.katalog.72": "L-entità żżomm inventarju aġġornat tal-assi bi sidien assenjati u klassifikazzjoni?",
    "ue.katalog.73": "ISO/IEC 27001 A.5.9, A.5.12",
    "ue.katalog.74": "Hemm politika ta' kontroll tal-aċċess ibbażata fuq il-prinċipju tal-inqas privileġġ, b'reviżjoni perjodika tal-privileġġi?",
    "ue.katalog.75": "ISO/IEC 27001 A.5.15, A.5.18",
    "ue.katalog.76": "Jiġu applikati proċeduri ta' sigurtà mal-ingaġġ, mal-bidla fil-pożizzjoni u mat-tluq ta' impjegat, inklużi r-revoka tal-privileġġi u r-ritorn tal-assi?",
    "ue.katalog.77": "ISO/IEC 27001 A.6.1–A.6.5",
    "ue.katalog.78": "L-aċċess privileġġjat huwa ristrett, irreġistrat u rivedut?",
    "ue.katalog.79": "ISO/IEC 27001 A.8.2",
    "ue.katalog.8": "ISO/IEC 27001 klawżola 6.1.3",
    "ue.katalog.80": "Awtentikazzjoni b'aktar minn fattur wieħed u komunikazzjonijiet siguri",
    "ue.katalog.81": "Fejn xieraq — awtentikazzjoni b'aktar minn fattur wieħed jew kontinwa, komunikazzjonijiet siguri bil-vuċi, bil-vidjo u bit-test u sistemi siguri ta' komunikazzjoni ta' emerġenza fi ħdan l-entità.",
    "ue.katalog.82": "L-awtentikazzjoni b'aktar minn fattur wieħed jew kontinwa tintuża fejn l-analiżi tar-riskju tiġġustifikaha, b'mod partikolari għall-aċċess remot u l-kontijiet privileġġjati?",
    "ue.katalog.83": "ISO/IEC 27001 A.8.5",
    "ue.katalog.84": "Il-komunikazzjonijiet bil-vuċi, bil-vidjo u bit-test użati għal skopijiet tax-xogħol huma siguri?",
    "ue.katalog.85": "ISO/IEC 27001 A.8.20",
    "ue.katalog.86": "L-entità għandha sistema interna sigura ta' komunikazzjoni ta' emerġenza, indipendenti mill-infrastruttura primarja?",
    "ue.katalog.9": "Il-livell ta' sigurtà huwa dokumentat bħala xieraq għar-riskju eżistenti, b'ġustifikazzjoni li tqis id-daqs tal-entità u l-impatt soċjali u ekonomiku tal-inċidenti?",
    "ue.kierownictwo.1": "Il-korp ta' ġestjoni ta' entità essenzjali jew importanti — f'kumpanija, il-bord tad-diretturi. Id-Direttiva ma tiddefinixxix it-terminu; l-ambitu tiegħu f'pajjiż partikolari joħroġ mil-liġi nazzjonali.",
    "ue.kierownictwo.10": "Iddetermina l-istatus tal-entità u żgura r-reġistrazzjoni",
    "ue.kierownictwo.11": "Determinazzjoni ta' jekk l-entità hijiex essenzjali jew importanti u sottomissjoni tad-data ta' reġistrazzjoni lill-awtorità kompetenti. Il-proċedura u l-iskadenza huma stabbiliti mil-liġi nazzjonali.",
    "ue.kierownictwo.12": "Implimenta l-analiżi tar-riskju u politika ta' sigurtà",
    "ue.kierownictwo.13": "Miżuri bbażati fuq approċċ li jqis il-perikli kollha, proporzjonati għall-espożizzjoni, id-daqs tal-entità u s-severità tal-inċidenti.",
    "ue.kierownictwo.14": "Stabbilixxi t-trattament u r-rappurtar tal-inċidenti",
    "ue.kierownictwo.15": "Proċedura ta' trattament tal-inċidenti u l-kapaċità li jiġu rrispettati l-iskadenzi ta' 24 siegħa, 72 siegħa u xahar.",
    "ue.kierownictwo.16": "24 s / 72 s / xahar mid-detezzjoni",
    "ue.kierownictwo.17": "Żgura l-kontinwità tan-negozju",
    "ue.kierownictwo.18": "Pjan ta' kontinwità, backups, irkupru minn diżastri, ġestjoni tal-kriżijiet.",
    "ue.kierownictwo.19": "Irranġa l-katina tal-provvista",
    "ue.kierownictwo.2": "Ir-responsabbiltà tal-korp ta' ġestjoni hija mingħajr preġudizzju għar-regoli nazzjonali dwar ir-responsabbiltà tal-istituzzjonijiet pubbliċi u tal-uffiċjali (l-Artikolu 20(1), it-tieni subparagrafu).",
    "ue.kierownictwo.20": "Lista ta' fornituri, valutazzjoni tal-vulnerabbiltajiet u tal-prattiki tagħhom, rekwiżiti ta' sigurtà fil-kuntratti.",
    "ue.kierownictwo.21": "Implimenta l-kontroll tal-aċċess u l-ġestjoni tal-assi",
    "ue.kierownictwo.22": "Inventarju tal-assi, prinċipju tal-inqas privileġġ, reviżjonijiet tal-privileġġi, awtentikazzjoni b'aktar minn fattur wieħed fejn ir-riskju jiġġustifikaha.",
    "ue.kierownictwo.23": "Kejjel l-effettività tal-miżuri",
    "ue.kierownictwo.24": "Politika u proċeduri ta' valutazzjoni tal-effettività, reviżjonijiet perjodiċi, azzjonijiet korrettivi.",
    "ue.kierownictwo.25": "Approva",
    "ue.kierownictwo.26": "il-miżuri tal-ġestjoni tar-riskju taċ-ċibersigurtà (l-Artikolu 20(1))",
    "ue.kierownictwo.27": "il-politika dwar l-analiżi tar-riskju u s-sigurtà tas-sistemi",
    "ue.kierownictwo.28": "il-baġit u r-rwoli fl-implimentazzjoni",
    "ue.kierownictwo.29": "Issorvelja",
    "ue.kierownictwo.3": "Jekk l-afdar tad-dmirijiet lil persuna oħra jneħħix ir-responsabbiltà huwa deċiż mil-liġi nazzjonali. Fil-Polonja ma jneħħihiex (l-Artikolu 8c(3) tal-Att dwar is-Sistema Nazzjonali taċ-Ċibersigurtà).",
    "ue.kierownictwo.30": "l-implimentazzjoni tal-miżuri approvati (l-Artikolu 20(1))",
    "ue.kierownictwo.31": "ir-riżultati tal-valutazzjoni tal-effettività (l-Artikolu 21(2)(f))",
    "ue.kierownictwo.32": "il-konformità mal-iskadenzi għar-rappurtar tal-inċidenti (l-Artikolu 23)",
    "ue.kierownictwo.33": "Iddokumenta",
    "ue.kierownictwo.34": "id-deċiżjonijiet ta' approvazzjoni u r-reviżjonijiet",
    "ue.kierownictwo.35": "il-parteċipazzjoni fit-taħriġ (l-Artikolu 20(2))",
    "ue.kierownictwo.36": "Membru tal-korp ta' ġestjoni",
    "ue.kierownictwo.37": "approvazzjoni tal-miżuri, sorveljanza, deċiżjonijiet, baġit",
    "ue.kierownictwo.38": "Maniġer tal-proġett",
    "ue.kierownictwo.39": "koordinazzjoni tal-implimentazzjoni, skeda, status u evidenza",
    "ue.kierownictwo.4": "Approva l-miżuri tal-ġestjoni tar-riskju taċ-ċibersigurtà",
    "ue.kierownictwo.40": "IT / ċibersigurtà",
    "ue.kierownictwo.41": "analiżi tar-riskju, miżuri tekniċi, trattament tal-inċidenti",
    "ue.kierownictwo.42": "Legali / konformità",
    "ue.kierownictwo.5": "Il-korp ta' ġestjoni japprova l-miżuri meħuda għall-konformità mal-Artikolu 21. Din hija deċiżjoni tal-korp, mhux tad-dipartiment tal-IT — mingħajrha l-miżuri m'għandhomx mandat.",
    "ue.kierownictwo.6": "Issorvelja l-implimentazzjoni tal-miżuri",
    "ue.kierownictwo.7": "Is-sorveljanza tal-implimentazzjoni hija obbligu tal-korp ta' ġestjoni. L-eżekuzzjoni tista' tiġi ddelegata; is-sorveljanza le.",
    "ue.kierownictwo.8": "Segwi taħriġ regolari",
    "ue.kierownictwo.9": "Il-membri tal-korp ta' ġestjoni jsegwu taħriġ regolari biex jiksbu għarfien suffiċjenti biex jidentifikaw ir-riskji u jivvalutaw il-prattiki tal-ġestjoni tar-riskju u l-impatt tagħhom fuq is-servizzi tal-entità.",
    "ue.kierownictwo.daneRejestracyjne": "id-data ta' reġistrazzjoni u l-aġġornamenti tagħha (l-Artikolu 3(4) u (5))",
    "ue.meta.1": "Jipprevali l-varjant perċentwali: {p0} % tal-fatturat huwa aktar minn EUR {p1} miljun.",
    "ue.meta.10": "Id-Direttiva ma timponix obbligi fuq l-impriżi direttament — dan jagħmlu l-att nazzjonali, li l-Istat Membru kellu jadotta sas-17 ta' Ottubru 2024. Dan il-modulu juri r-rekwiżiti kif formulati fid-Direttiva, għaliex il-modulu tal-liġi nazzjonali għall-pajjiż magħżul għadu mhux lest jew il-pajjiż ma ttrasponiex id-Direttiva.",
    "ue.meta.11": "Obbligi skont id-Direttiva",
    "ue.meta.12": "Lista tal-entitajiet — sas-17 ta' April 2025",
    "ue.meta.13": "L-Istati Membri kellhom jistabbilixxu lista tal-entitajiet essenzjali u importanti sas-17 ta' April 2025 u jeħtieġu li l-entitajiet jissottomettu d-data ta' reġistrazzjoni.",
    "ue.meta.14": "Regolament (UE) 2024/2690",
    "ue.meta.15": "Applikabbli direttament mis-7 ta' Novembru 2024",
    "ue.meta.16": "Ir-Regolament ta' Implimentazzjoni japplika direttament fl-Istati Membri kollha, irrispettivament mill-istat tat-traspożizzjoni tad-Direttiva. Jikkonċerna l-entitajiet elenkati fl-Artikolu 1 tiegħu: fornituri tad-DNS, tat-TLD, tal-cloud, taċ-ċentri tad-data, tan-netwerks ta' twassil ta' kontenut, ta' servizzi ġestiti u ta' servizzi fiduċjarji.",
    "ue.meta.17": "l-Artikolu 16 tar-Regolament (UE) 2024/2690",
    "ue.meta.18": "Mill-inqas EUR 10 000 000 jew mill-inqas 2 % tal-fatturat annwali totali dinji tal-impriża fis-sena finanzjarja preċedenti — skont liema jkun l-ogħla. Dan huwa limitu massimu minimu: il-liġi nazzjonali tista' żżidu.",
    "ue.meta.19": "Mill-inqas EUR 7 000 000 jew 1,4 % tal-fatturat annwali totali dinji — skont liema jkun l-ogħla. Limitu massimu minimu.",
    "ue.meta.2": "Jipprevali l-ammont fiss: EUR {p0} miljun huwa aktar minn {p1} % tal-fatturat.",
    "ue.meta.20": "Id-Direttiva ma tipprovdix multa separata għal ksur kwalifikat — dik hija kostruzzjoni tal-liġi nazzjonali ta' xi Stati Membri.",
    "ue.meta.21": "L-Istati Membri jistgħu jipprovdu għal pagamenti perjodiċi ta' penali biex iġiegħlu entità twaqqaf ksur. L-ammont huwa stabbilit mil-liġi nazzjonali.",
    "ue.meta.22": "Il-korp ta' ġestjoni japprova l-miżuri tal-ġestjoni tar-riskju, jissorvelja l-implimentazzjoni tagħhom u jista' jinżamm responsabbli għal ksur tal-Artikolu 21. Ir-regoli u l-ambitu ta' dik ir-responsabbiltà huma ddeterminati mil-liġi nazzjonali.",
    "ue.meta.23": "Il-korp ta' ġestjoni japprova l-miżuri tal-ġestjoni tar-riskju taċ-ċibersigurtà (l-Artikolu 20(1)).",
    "ue.meta.24": "Il-korp ta' ġestjoni jissorvelja l-implimentazzjoni ta' dawk il-miżuri (l-Artikolu 20(1)).",
    "ue.meta.25": "Il-membri tal-korp ta' ġestjoni jsegwu taħriġ regolari (l-Artikolu 20(2)).",
    "ue.meta.26": "Fir-rigward ta' entità essenzjali, l-awtorità tista' titlob projbizzjoni temporanja mill-eżerċizzju ta' funzjonijiet maniġerjali (l-Artikolu 32(5)(b)).",
    "ue.meta.27": "Il-limitu massimu minimu huwa stabbilit mid-Direttiva",
    "ue.meta.28": "Jitqabblu żewġ valuri: ammont fiss f'euro u perċentwal tal-fatturat annwali totali dinji tal-impriża fis-sena finanzjarja preċedenti. L-ogħla fost it-tnejn huwa l-limitu ta' fuq li l-Istat Membru għandu jipprovdi bħala minimu. Il-liġi nazzjonali tista' żżidu.",
    "ue.meta.29": "L-ammont fi ħdan il-limitu massimu huwa stabbilit mill-awtorità nazzjonali",
    "ue.meta.3": "Il-limitu massimu mid-Direttiva jaqbeż il-fatturat annwali tal-entità b'{p0} darbiet. L-Artikolu 34(1) jeħtieġ li l-multa tkun proporzjonata għaċ-ċirkostanzi tal-każ individwali — dan huwa limitu ta' fuq, mhux multa mistennija.",
    "ue.meta.30": "Il-multa trid tkun effettiva, proporzjonata u dissważiva skont iċ-ċirkostanzi tal-każ individwali. L-awtorità tqis mill-inqas il-kriterji tal-Artikolu 32(7): il-gravità u d-durata tal-ksur, ksur preċedenti, il-ħsara kkawżata, l-intenzjoni, il-miżuri ta' rimedju u l-kooperazzjoni.",
    "ue.meta.31": "Il-limitu massimu jista' jaqbeż il-fatturat annwali b'ħafna drabi — huwa limitu ta' fuq, mhux ammont mistenni. Il-minimi nazzjonali, il-pagamenti perjodiċi ta' penali u l-proċedura għall-iffissar tal-multi huma ddeterminati mil-liġi tal-Istat Membru.",
    "ue.meta.32": "Meta jiġi deċiż jekk tiġix imposta multa amministrattiva u l-ammont tagħha, f'kull każ individwali tingħata kunsiderazzjoni dovuta mill-inqas lill-elementi elenkati fl-Artikolu 32(7).",
    "ue.meta.33": "il-gravità tal-ksur u l-importanza tad-dispożizzjonijiet miksura — dawn li ġejjin jitqiesu serji f'kull każ: ksur ripetut, nuqqas ta' notifika jew ta' rimedju ta' inċidenti sinifikanti, nuqqas ta' rimedju ta' nuqqasijiet kontra struzzjonijiet vinkolanti, ostakolar ta' awditi jew monitoraġġ, għoti ta' informazzjoni falza jew gravament ineżatta",
    "ue.meta.34": "kwalunkwe ksur preċedenti rilevanti mill-entità",
    "ue.meta.35": "kwalunkwe ħsara materjali jew mhux materjali kkawżata, inkluż telf finanzjarju, effetti fuq servizzi oħra u n-numru ta' utenti affettwati",
    "ue.meta.36": "in-natura intenzjonali jew negliġenti tal-ksur",
    "ue.meta.37": "miżuri meħuda biex tiġi prevenuta jew mitigata l-ħsara",
    "ue.meta.38": "aderenza ma' kodiċijiet ta' kondotta jew mekkaniżmi ta' ċertifikazzjoni approvati",
    "ue.meta.39": "il-grad ta' kooperazzjoni mal-awtoritajiet kompetenti",
    "ue.meta.4": "Direttiva (UE) 2022/2555 tal-Parlament Ewropew u tal-Kunsill (NIS 2)",
    "ue.meta.40": "Id-Direttiva ma tipprovdix espressament għar-rinunzja ta' multa — jekk u meta dan huwa possibbli huwa deċiż mil-liġi nazzjonali.",
    "ue.meta.41": "Minn din id-data l-Istati Membri għandhom japplikaw id-dispożizzjonijiet nazzjonali li jimplimentaw id-Direttiva. Id-data speċifika li minnha l-awtorità tista' timponi multa toħroġ mil-liġi nazzjonali.",
    "ue.meta.42": "Dħul fis-seħħ tad-Direttiva NIS 2",
    "ue.meta.43": "Fl-għoxrin jum wara l-pubblikazzjoni f'Il-Ġurnal Uffiċjali.",
    "ue.meta.44": "Skadenza għat-traspożizzjoni tad-Direttiva",
    "ue.meta.45": "Sa din id-data l-Istati Membri kellhom jadottaw u jippubblikaw id-dispożizzjonijiet nazzjonali.",
    "ue.meta.46": "Applikazzjoni tad-dispożizzjonijiet nazzjonali u tħassir tan-NIS 1",
    "ue.meta.47": "Minn din id-data l-Istati Membri japplikaw id-dispożizzjonijiet ta' implimentazzjoni; id-Direttiva (UE) 2016/1148 titħassar.",
    "ue.meta.48": "Applikazzjoni tar-Regolament (UE) 2024/2690",
    "ue.meta.49": "Ir-Regolament ta' Implimentazzjoni japplika direttament mill-għoxrin jum wara l-pubblikazzjoni.",
    "ue.meta.5": "ĠU UE L 333, 27.12.2022",
    "ue.meta.50": "Lista tal-entitajiet essenzjali u importanti",
    "ue.meta.51": "Sa din id-data l-Istati Membri jistabbilixxu l-lista; l-entitajiet jissottomettu d-data ta' reġistrazzjoni lill-awtoritajiet.",
    "ue.meta.52": "L-ewwel rieżami tad-Direttiva mill-Kummissjoni",
    "ue.meta.53": "Il-Kummissjoni tirrieżamina l-funzjonament tad-Direttiva u tissottometti rapport.",
    "ue.meta.54": "Twissija bikrija ta' inċident sinifikanti",
    "ue.meta.55": "24 siegħa wara li ssir taf",
    "ue.meta.56": "Notifika ta' inċident sinifikanti",
    "ue.meta.57": "72 siegħa wara li ssir taf",
    "ue.meta.58": "Rapport finali",
    "ue.meta.59": "xahar wara n-notifika tal-inċident",
    "ue.meta.6": "Regolament ta' Implimentazzjoni tal-Kummissjoni (UE) 2024/2690",
    "ue.meta.60": "Notifika ta' inċident minn fornitur ta' servizzi fiduċjarji",
    "ue.meta.61": "l-Artikolu 21(5) tad-Direttiva (UE) 2022/2555; l-Artikoli 1 u 2 tar-Regolament (UE) 2024/2690",
    "ue.meta.62": "Mingħajr data tal-fatturat, il-limitu massimu huwa l-ammont fiss mid-Direttiva.",
    "ue.meta.63": "Il-limiti massimi fl-Artikolu 34(4) u (5) huma minimi (\"mill-inqas\") — il-liġi nazzjonali tista' tipprovdi għal ogħla. Ammonti f'euro, mingħajr konverżjoni għall-munita nazzjonali.",
    "ue.meta.64": "Awtorità kompetenti tal-Istat Membru",
    "ue.meta.65": "Il-korp ta' ġestjoni jista' jinżamm responsabbli għal ksur tal-Artikolu 21. L-ambitu u l-proċedura huma ddeterminati mil-liġi nazzjonali — dan il-modulu ma jafhomx.",
    "ue.meta.66": "L-ambitu tar-responsabbiltà personali tal-maniġment joħroġ mill-att nazzjonali. Għall-Polonja huwa sa 300 % tar-remunerazzjoni (l-Artikolu 73a(4) tal-Att dwar is-Sistema Nazzjonali taċ-Ċibersigurtà); Stati Membri oħra jiddeċiedu b'mod differenti.",
    "ue.meta.7": "ĠU UE L, 2024/2690",
    "ue.meta.8": "Direttiva (UE) 2022/2555",
    "ue.meta.9": "L-iskadenza għat-traspożizzjoni skadiet fis-17 ta' Ottubru 2024",
    "ue.moduly.1": "madwar {p0} min",
    "ue.moduly.10": "Għaxar oqsma mill-Artikolu 21(2), il-punti (a) sa (j): mill-politika tar-riskju sal-awtentikazzjoni b'aktar minn fattur wieħed. Il-ksur huwa punibbli b'multa skont l-Artikolu 34. Valutazzjoni fuq skala ta' maturità.",
    "ue.moduly.11": "Regolament 2024/2690 — governanza u proċessi",
    "ue.moduly.12": "It-taqsimiet 1–5 u 7–8 tal-Anness: politiki, ġestjoni tar-riskju, trattament tal-inċidenti, kontinwità tan-negozju, katina tal-provvista, valutazzjoni tal-effettività, iġjene ċibernetika. Applikabbli direttament mis-7 ta' Novembru 2024.",
    "ue.moduly.13": "Regolament 2024/2690 — rekwiżiti tekniċi",
    "ue.moduly.14": "It-taqsimiet 6 u 9–13 tal-Anness: akkwist u żvilupp tas-sistemi, kriptografija, sigurtà tar-riżorsi umani, kontroll tal-aċċess, ġestjoni tal-assi, sigurtà fiżika u ambjentali.",
    "ue.moduly.2": "madwar {p0} s {p1} min",
    "ue.moduly.3": "madwar {p0} s",
    "ue.moduly.4": "inqas minn minuta",
    "ue.moduly.5": "Valutazzjoni rapida tar-riskju",
    "ue.moduly.6": "Mistoqsijiet ġenerali mill-oqsma kollha tad-Direttiva. Kull waħda tiddeċiedi dwar grupp sħiħ ta' suġġetti. Tippermetti li jiġi vvalutat l-ambitu tal-arretrati mingħajr ma jgħaddi l-kwestjonarju kollu.",
    "ue.moduly.7": "Obbligi skont id-Direttiva",
    "ue.moduly.8": "Data ta' reġistrazzjoni, rappurtar tal-inċidenti fi żmien 24 u 72 siegħa, obbligi tal-korp ta' ġestjoni, tħejjija għas-superviżjoni. Verifikabbli mid-dokumenti, mingħajr analiżi teknika.",
    "ue.moduly.9": "Miżuri tal-ġestjoni tar-riskju — l-Artikolu 21(2)",
    "ue.obowiazki.1": "Data ta' reġistrazzjoni għal-lista tal-entitajiet",
    "ue.obowiazki.10": "Rappurtar ta' inċidenti sinifikanti",
    "ue.obowiazki.11": "L-entità tinnotifika l-inċidenti sinifikanti lis-CSIRT jew lill-awtorità kompetenti fi tliet passi: twissija bikrija, notifika tal-inċident, rapport finali. L-iskadenzi jibdew minn meta ssir taf bl-inċident.",
    "ue.obowiazki.12": "L-entità kapaċi, fi żmien 24 siegħa minn meta ssir taf b'inċident sinifikanti, tissottometti twissija bikrija li tindika jekk l-inċident huwiex suspettat li ġie kkawżat minn atti illegali u jekk jistax ikollu impatt transfruntier?",
    "ue.obowiazki.13": "24 siegħa wara li ssir taf",
    "ue.obowiazki.14": "L-entità kapaċi, fi żmien 72 siegħa, tissottometti notifika tal-inċident b'valutazzjoni inizjali tas-severità u tal-impatt u indikaturi ta' kompromess?",
    "ue.obowiazki.15": "72 siegħa wara li ssir taf",
    "ue.obowiazki.16": "L-entità tissottometti, mhux aktar tard minn xahar wara n-notifika, rapport finali b'deskrizzjoni tal-inċident, it-tip ta' theddida, il-miżuri ta' mitigazzjoni u l-impatt transfruntier?",
    "ue.obowiazki.17": "xahar wara n-notifika",
    "ue.obowiazki.18": "L-entità tinforma lir-riċevituri tas-servizzi tagħha dwar inċidenti sinifikanti li jistgħu jaffettwaw ħażin il-forniment ta' dawk is-servizzi?",
    "ue.obowiazki.19": "L-entità tinforma lir-riċevituri tas-servizzi dwar theddida ċibernetika sinifikanti u dwar il-miżuri li r-riċevituri jistgħu jieħdu?",
    "ue.obowiazki.2": "L-Istati Membri jistabbilixxu lista tal-entitajiet essenzjali u importanti u jeħtieġu li l-entitajiet jissottomettu d-data ta' reġistrazzjoni. Il-proċedura, l-iskadenza u l-portal huma stabbiliti mil-liġi nazzjonali.",
    "ue.obowiazki.20": "Jekk l-entità hija fornitur ta' servizzi fiduċjarji — tinnotifika l-inċidenti sinifikanti fi żmien 24 siegħa minn meta ssir taf?",
    "ue.obowiazki.21": "jikkonċerna l-fornituri ta' servizzi fiduċjarji",
    "ue.obowiazki.22": "Korp ta' ġestjoni",
    "ue.obowiazki.23": "Il-korp ta' ġestjoni japprova l-miżuri tal-ġestjoni tar-riskju, jissorvelja l-implimentazzjoni tagħhom u jista' jinżamm responsabbli. Il-membri tal-korp isegwu taħriġ regolari.",
    "ue.obowiazki.24": "Il-korp ta' ġestjoni approva formalment il-miżuri tal-ġestjoni tar-riskju taċ-ċibersigurtà meħuda għall-konformità mal-Artikolu 21?",
    "ue.obowiazki.25": "Il-korp ta' ġestjoni jissorvelja b'mod dokumentat l-implimentazzjoni ta' dawn il-miżuri — pereżempju permezz ta' rapporti u reviżjonijiet perjodiċi?",
    "ue.obowiazki.26": "Il-membri tal-korp ta' ġestjoni jsegwu taħriġ regolari li jippermettilhom jidentifikaw ir-riskji u jivvalutaw il-prattiki tal-ġestjoni tar-riskju, u l-parteċipazzjoni hija dokumentata?",
    "ue.obowiazki.27": "Tħejjija għall-miżuri superviżorji",
    "ue.obowiazki.28": "Entità essenzjali hija soġġetta għas-superviżjoni ex ante u ex post, entità importanti — għal dik ex post biss. L-awtorità tista' titlob informazzjoni, evidenza tal-implimentazzjoni tal-politiki u riżultati tal-awditi.",
    "ue.obowiazki.29": "L-entità kapaċi, fuq talba tal-awtorità, tipprovdi evidenza tal-implimentazzjoni tal-politiki taċ-ċibersigurtà, inklużi r-riżultati tal-awditi tas-sigurtà?",
    "ue.obowiazki.3": "L-entità ddeterminat jekk hijiex entità essenzjali jew importanti, abbażi tas-settur fl-Anness I jew II u d-daqs tal-intrapriża?",
    "ue.obowiazki.30": "L-entità kapaċi, fuq talba tal-awtorità, tagħmel disponibbli d-data, id-dokumenti u l-informazzjoni meħtieġa biex jitwettqu l-kompiti superviżorji?",
    "ue.obowiazki.31": "L-entità essenzjali hija ppreparata għal awditu tas-sigurtà mwettaq mill-awtorità jew minn korp indipendenti, bi spejjeż tagħha?",
    "ue.obowiazki.4": "L-entità ssottomettiet id-data ta' reġistrazzjoni lill-awtorità kompetenti: isem, indirizz u dettalji ta' kuntatt, settur u subsettur, lista tal-Istati Membri fejn tipprovdi s-servizzi?",
    "ue.obowiazki.5": "Id-dettalji ta' kuntatt jinkludu indirizzi tal-email, firxiet ta' indirizzi IP u numri tat-telefown. L-iskadenza u l-portal nazzjonali għar-reġistrazzjoni huma ddeterminati mil-liġi tal-Istat Membru.",
    "ue.obowiazki.6": "Hemm proċedura għall-aġġornament tad-data ta' reġistrazzjoni mingħajr dewmien żejjed wara bidla?",
    "ue.obowiazki.7": "Id-Direttiva teħtieġ aġġornament mingħajr dewmien żejjed; l-iskadenza speċifika — pereżempju 14-il jum fil-Polonja — toħroġ mil-liġi nazzjonali.",
    "ue.obowiazki.8": "Jekk l-entità hija fornitur tad-DNS, reġistru tal-ismijiet ta' dominju tal-ogħla livell, fornitur tal-cloud, taċ-ċentru tad-data, tas-CDN, ta' servizzi ġestiti, suq online, magna tat-tiftix jew netwerk soċjali — issottomettiet id-data addizzjonali skont l-Artikolu 27, inkluż l-indirizz tal-istabbiliment prinċipali fl-Unjoni?",
    "ue.obowiazki.9": "jikkonċerna l-entitajiet skont l-Artikolu 26(1)",
    "ue.role.1": "Awtorità kompetenti tal-Istat Membru",
    "ue.role.10": "Servizzi taċ-ċentru tad-data: kolokazzjoni, hosting tal-infrastruttura u servizzi relatati.",
    "ue.role.11": "Ċentri tad-data",
    "ue.role.12": "Entità essenzjali 'l fuq mil-limitu ta' intrapriża medja (l-Artikolu 3(1)(a)), importanti f'daqs medju (l-Artikolu 3(2)). Taħt id-daqs medju — barra mill-kamp ta' applikazzjoni, sakemm l-Istat Membru ma jidentifikax l-entità skont l-Artikolu 2(2)(b) sa (e). Kopert mir-Regolament 2024/2690.",
    "ue.role.13": "Fornitur ta' punt ta' skambju tal-internet",
    "ue.role.14": "Infrastruttura li tippermetti l-iskambju tat-traffiku bejn netwerks indipendenti.",
    "ue.role.15": "Punti ta' skambju tal-internet",
    "ue.role.16": "Klassifikazzjoni skont id-daqs (l-Artikolu 3(1)(a) u (2)). Ir-Regolament 2024/2690 ma jkoprix il-punti ta' skambju tal-internet — l-Artikolu 1 tar-Regolament fih lista magħluqa ta' destinatarji.",
    "ue.role.17": "Fornitur ta' servizzi tad-DNS",
    "ue.role.18": "Servizzi ta' riżoluzzjoni tal-ismijiet ta' dominju, minbarra l-operaturi tas-servers tal-ismijiet tal-għeruq.",
    "ue.role.19": "Sistema tal-ismijiet ta' dominju",
    "ue.role.2": "awtorità kompetenti",
    "ue.role.20": "Entità essenzjali irrispettivament mid-daqs (l-Artikolu 3(1)(b)). Kopert mir-Regolament 2024/2690.",
    "ue.role.21": "Reġistru tal-ismijiet ta' dominju tal-ogħla livell",
    "ue.role.22": "Ġestjoni tar-reġistru ta' dominju tal-ogħla livell.",
    "ue.role.23": "Entità essenzjali irrispettivament mid-daqs (l-Artikolu 3(1)(b)). Barra minn hekk, obbligi skont l-Artikolu 28 dwar id-data ta' reġistrazzjoni. Kopert mir-Regolament 2024/2690.",
    "ue.role.24": "Fornitur ta' servizzi tal-cloud computing",
    "ue.role.25": "Servizzi tal-cloud computing: infrastruttura, pjattaforma, software bħala servizz.",
    "ue.role.26": "Servizzi tal-cloud computing",
    "ue.role.27": "Klassifikazzjoni skont id-daqs (l-Artikolu 3(1)(a) u (2)). Kopert mir-Regolament 2024/2690.",
    "ue.role.28": "Fornitur ta' netwerk ta' twassil ta' kontenut",
    "ue.role.29": "Netwerk ta' servers distribwiti li jwasslu kontenut u servizzi lill-utenti finali.",
    "ue.role.3": "maħtura mil-liġi nazzjonali; sakemm jiġi introdott il-modulu nazzjonali, l-għodda ma tindikax istituzzjoni speċifika",
    "ue.role.30": "Netwerks ta' twassil ta' kontenut",
    "ue.role.31": "Fornitur ta' servizzi fiduċjarji",
    "ue.role.32": "Servizzi fiduċjarji fis-sens tar-Regolament (UE) Nru 910/2014: firem, siġilli, timbri tal-ħin, ċertifikati.",
    "ue.role.33": "Servizzi fiduċjarji",
    "ue.role.34": "Kopert mid-Direttiva irrispettivament mid-daqs (l-Artikolu 2(2)(a)(ii)). Fornitur kwalifikat huwa entità essenzjali irrispettivament mid-daqs (l-Artikolu 3(1)(b)); wieħed mhux kwalifikat huwa essenzjali 'l fuq mil-limitu ta' intrapriża medja, inkella importanti. Kopert mir-Regolament 2024/2690.",
    "ue.role.35": "Fornitur ta' servizzi ġestiti",
    "ue.role.36": "Ġestjoni tal-infrastruttura tal-ICT tal-klijent: installazzjoni, manutenzjoni, appoġġ, amministrazzjoni tas-sistemi.",
    "ue.role.37": "Ġestjoni ta' servizzi tal-ICT (B2B)",
    "ue.role.38": "Servizzi ġestiti",
    "ue.role.39": "Fornitur ta' servizzi ta' sigurtà ġestiti",
    "ue.role.4": "Fornitur ta' netwerks pubbliċi ta' komunikazzjonijiet elettroniċi jew ta' servizzi ta' komunikazzjonijiet elettroniċi disponibbli għall-pubbliku",
    "ue.role.40": "Servizzi ġestiti taċ-ċibersigurtà: monitoraġġ, rispons għall-inċidenti, ittestjar, konsulenza.",
    "ue.role.41": "Servizzi ta' sigurtà ġestiti",
    "ue.role.42": "Id-Direttiva tikklassifika skont id-daqs (l-Artikolu 3(1)(a) u (2)). L-Istati Membri jistgħu jagħmlu l-limitu aktar strett — il-Polonja tqis lill-MSSP bħala entità essenzjali diġà minn intrapriża żgħira; dan il-modulu japplika esklużivament ir-regola tad-Direttiva. Kopert mir-Regolament 2024/2690.",
    "ue.role.5": "Forniment ta' netwerks pubbliċi ta' komunikazzjonijiet elettroniċi jew ta' servizzi ta' komunikazzjonijiet elettroniċi disponibbli għall-pubbliku, inkluż l-aċċess għall-internet.",
    "ue.role.6": "Infrastruttura diġitali",
    "ue.role.7": "Komunikazzjonijiet elettroniċi",
    "ue.role.8": "Kopert mid-Direttiva irrispettivament mid-daqs (l-Artikolu 2(2)(a)(i)). Intrapriża medja jew akbar hija entità essenzjali (l-Artikolu 3(1)(c)), mikrointrapriża u intrapriża żgħira — importanti (l-Artikolu 3(2)). L-att nazzjonali dwar il-komunikazzjonijiet elettroniċi jista' jimponi obbligi addizzjonali — dan il-modulu ma fihomx.",
    "ue.role.9": "Fornitur ta' servizzi taċ-ċentru tad-data",
    "ue.role.podstawaArt3b": "l-Artikolu 3(1)(b) tad-Direttiva (UE) 2022/2555",
    "ue.zaslepki.1": "Direttiva (UE) 2022/2555 tal-Parlament Ewropew u tal-Kunsill (NIS 2)",
    "ue.zaslepki.10": "Jekk xi entitajiet jiġux irreġistrati ex officio huwa deċiż mil-liġi nazzjonali.",
    "ue.zaslepki.11": "Iddetermina jekk intix kopert mid-Direttiva",
    "ue.zaslepki.12": "Settur fl-Anness I jew II u daqs tal-intrapriża. Din il-parti ssir mill-profil tal-entità f'din l-għodda.",
    "ue.zaslepki.13": "Iddetermina l-awtorità kompetenti f'pajjiżek",
    "ue.zaslepki.14": "Kull pajjiż jaħtar awtorità kompetenti (l-Artikolu 8(1)). Lista aġġornata tinżamm mill-ENISA u mill-Kummissjoni.",
    "ue.zaslepki.15": "Issottometti d-data ta' reġistrazzjoni",
    "ue.zaslepki.16": "Isem, indirizz u dettalji ta' kuntatt, settur u subsettur, pajjiżi fejn jiġu pprovduti s-servizzi (l-Artikolu 3(4)). Proċedura skont il-liġi nazzjonali.",
    "ue.zaslepki.17": "Aġġorna d-data mingħajr dewmien żejjed",
    "ue.zaslepki.18": "Kull bidla fid-data ta' reġistrazzjoni teħtieġ aġġornament (l-Artikolu 3(5)).",
    "ue.zaslepki.19": "indirizz u dettalji ta' kuntatt attwali: indirizzi tal-email, firxiet ta' indirizzi IP, numri tat-telefown",
    "ue.zaslepki.2": "ĠU UE L 333, 27.12.2022, p. 80",
    "ue.zaslepki.20": "settur u subsettur fl-Anness I jew II",
    "ue.zaslepki.21": "lista tal-Istati Membri fejn l-entità tipprovdi s-servizzi",
    "ue.zaslepki.22": "Stabbilita mil-liġi nazzjonali.",
    "ue.zaslepki.23": "Direttiva (UE) 2022/2555 — l-Artikolu 3",
    "ue.zaslepki.24": "ENISA — awtoritajiet kompetenti tal-Istati Membri",
    "ue.zaslepki.25": "Direttiva (UE) 2022/2555",
    "ue.zaslepki.26": "Il-modulu tal-UE ma fihx linji gwida tal-awtorità nazzjonali — dawn jiġu mal-modulu tal-liġi nazzjonali.",
    "ue.zaslepki.27": "Il-ġbir awtomatiku tad-data mir-reġistru jaħdem biss għal pajjiżi b'modulu tal-liġi nazzjonali. Imla l-profil manwalment.",
    "ue.zaslepki.28": "Il-qari ta' rapport finanzjarju jaħdem biss għal pajjiżi b'modulu tal-liġi nazzjonali. Daħħal id-dħul u n-numru ta' impjegati manwalment.",
    "ue.zaslepki.3": "Regolament ta' Implimentazzjoni tal-Kummissjoni (UE) 2024/2690",
    "ue.zaslepki.4": "ĠU UE L, 2024/2690, 18.11.2024",
    "ue.zaslepki.5": "Id-Direttiva NIS 2 ma fihiex saff separat ta' komunikazzjonijiet elettroniċi. Il-liġi nazzjonali dwar il-komunikazzjonijiet elettroniċi tista' timponi obbligi addizzjonali — dan il-modulu ma jafhomx.",
    "ue.zaslepki.6": "Lista tal-entitajiet essenzjali u importanti",
    "ue.zaslepki.7": "Awtorità kompetenti tal-Istat Membru.",
    "ue.zaslepki.8": "Id-Direttiva tobbliga lill-Istati Membri jżommu lista tal-entitajiet essenzjali u importanti u jeħtieġu li l-entitajiet jissottomettu d-data ta' reġistrazzjoni. Il-portal, il-proċedura u l-iskadenza huma stabbiliti mil-liġi nazzjonali — dan il-modulu ma jafhomx, għaliex il-modulu tal-liġi nazzjonali għall-pajjiż magħżul għadu mhux lest.",
    "ue.zaslepki.9": "L-entitajiet essenzjali u importanti kollha. L-iskadenza hija stabbilita mil-liġi nazzjonali.",
    "ue.zaslepki.skrotDyrektywy": "Direttiva NIS 2",
    "ue.zaslepki.skrotReg2690": "Regolament 2024/2690",
    "xlsx.1": "EUR {p0} – {p1}",
    "xlsx.25": "Rata tal-kambju",
    "xlsx.4": "RAPPORT TAL-KONFORMITÀ MAD-DIRETTIVA NIS 2 (UE) 2022/2555",
    "xlsx.58": "Attività ta' komunikazzjonijiet elettroniċi: ir-Regolament (UE) 2024/2690 ma japplikax. Il-limiti huma stabbiliti mil-liġi nazzjonali (l-Artikolu 23(11) tad-Direttiva) — il-modulu komuni ma jafhomx.",
    "xlsx.68": "L-għodda sservi għall-awtovalutazzjoni. La hija awditu u lanqas parir legali.",
    "xlsx.69": "Għall-entitajiet mhux koperti mir-Regolament (UE) 2024/2690, il-limiti ta' inċident sinifikanti huma stabbiliti mil-liġi nazzjonali (l-Artikolu 23(11) tad-Direttiva).",
    "xlsx.70": "Ir-rwoli indikati fil-profil huma dikjarazzjoni. L-istatus huwa ddeterminat mill-attività li fil-fatt titwettaq (l-Artikolu 3 tad-Direttiva (UE) 2022/2555).",
    "xlsx.etykietaKrs": "Numru tar-reġistru",
    "xlsx.etykietaNip": "Numru ta' identifikazzjoni",
    "xlsx.etykietaRegon": "Numru statistiku"
});
