/* Teksty modułu ue — język: nl.
   Te same klucze co w napisy/pl.js (wersja źródłowa); wstawki {p0}, {p1}…
   pozostają bez zmian. Klucze ue.cyt.* to wzorce składania odesłań
   do przepisów w tym języku — patrz kraje/ue/cytaty.js. */
KRAJE.napisy('ue', 'nl', {
    "app.10": "Controleer de lijst van rollen hieronder — de status wordt bepaald door de daadwerkelijk uitgeoefende activiteit (artikel 3 van Richtlijn (EU) 2022/2555), niet door een registerinschrijving.",
    "app.14": "Vorig jaar: {p0} EUR",
    "app.15": "Omzet van de verslagperiode: {p0} EUR",
    "app.19": "Registers worden geraadpleegd met nummer {p0}…",
    "app.34": " mld EUR",
    "app.35": " mln EUR",
    "app.36": " dzd EUR",
    "app.37": "",
    "app.4": "Het automatisch ophalen van registergegevens is voor dit land niet beschikbaar — vul het profiel handmatig in.",
    "app.59": "Nalevingsbeoordeling NIS 2-richtlijn (JSON)",
    "app.68": "Voor dit land bestaat geen register waaruit het instrument gegevens kan ophalen — het profiel wordt handmatig ingevuld.",
    "app.69": "Voor dit land bestaat geen register waaruit het instrument gegevens kan ophalen. Klik om de offlinemodus in te schakelen.",
    "app.73": " · winst-en-verliesrekening in de variant ",
    "app.74": "<div class=\"mt-2 tekst-uwaga\">Uit de registergegevens blijkt geen rol in de sector digitale infrastructuur. Geef de rollen hieronder handmatig op.</div>",
    "app.8": "Inschrijving in het register van aanbieders van elektronische communicatie bevestigd",
    "app.progDostawcy": "",
    "app.przyklad.adres": "Voorbeeldstraat 1, 1000 AA Stad",
    "app.przyklad.forma": "Besloten vennootschap",
    "app.przyklad.nazwa": "Voorbeeld Operator B.V.",
    "app.statusVat": " · btw-status: ",
    "dashboard.1": "Op basis van de opgegeven rollen en grootte is de entiteit noch een essentiële noch een belangrijke entiteit in de zin van artikel 3 van Richtlijn (EU) 2022/2555. Controleer het profiel als het resultaat niet overeenkomt met wat u verwachtte.",
    "dashboard.113": "Veelgestelde vragen",
    "dashboard.12": "— {p0}; de omzettingstermijn naar nationaal recht is verstreken op {p2}",
    "dashboard.123": "NIS 2-richtlijn",
    "dashboard.30": "Lijst van essentiële en belangrijke entiteiten",
    "dashboard.4": "— rechtstreeks van toepassing sinds {p0} in alle lidstaten, zonder omzetting",
    "dashboard.42": "Vastbedragvariant: {p0}",
    "dashboard.45": "Criteria van artikel 32, lid 7, van de richtlijn:",
    "dashboard.46": "Totaal",
    "dashboard.49": "De entiteit oefent een elektronischecommunicatieactiviteit uit — de aansprakelijkheid van de leidinggevende wordt door het nationale recht bepaald",
    "dashboard.50": "",
    "dashboard.51": "",
    "dashboard.53": "Dwangsom bij vertraging in de uitvoering van een besluit: van {p0} EUR tot {p1} EUR per dag ({p2})",
    "dashboard.54": "Gekwalificeerd geval: tot {p0} EUR ({p1})",
    "dashboard.57": "({p0}). Vanaf wanneer de nationale autoriteit boetes kan opleggen, bepaalt de omzettingswet — deze module kent die niet. De invoeringsverplichtingen vloeien voort uit het nationale recht vanaf de inwerkingtreding ervan.",
    "dashboard.65": "({p0}). Vanaf wanneer de nationale autoriteit boetes kan opleggen, bepaalt de omzettingswet — deze module kent die niet. Het financiële risico is hier daarom niet gedateerd, terwijl de invoeringsverplichtingen uit het nationale recht voortvloeien vanaf de inwerkingtreding ervan.",
    "dashboard.83": "Elektronischecommunicatieactiviteit — de drempels worden door het nationale recht bepaald.",
    "dashboard.84": "Verordening (EU) 2024/2690 is niet van toepassing op aanbieders van openbare elektronischecommunicatienetwerken en -diensten. Voor hen worden de drempels voor een significant incident door het nationale recht bepaald (artikel 23, lid 11, van de richtlijn) — deze module kent ze niet en geeft daarom geen cijfers.",
    "dashboard.terminRejestracji": "De termijn voor het indienen van registratiegegevens wordt door het nationale recht bepaald (artikel 3, lid 4, van de richtlijn). Aanbieders als bedoeld in artikel 27, lid 1 — DNS-diensten, TLD-registers, clouddiensten, datacentra, netwerken voor de levering van inhoud, beheerde diensten en beheerde beveiligingsdiensten — dienen hun gegevens in bij het ENISA-register: aanvankelijk uiterlijk 17 januari 2025, en elke wijziging onverwijld.",
    "html.1": "ITORO — Nalevingsbeoordeling NIS 2-richtlijn (EU) 2022/2555",
    "html.10": "Nalevingsbeoordeling NIS 2-richtlijn — gemeenschappelijke module",
    "html.100": "Het inlezen van een jaarrekening werkt alleen voor landen met een module nationaal recht. Voor dit land voert u de <strong>omzet</strong> van het boekjaar handmatig in — daarvan hangt de hoogte van de boete af.",
    "html.102": "Het automatisch ophalen van registergegevens werkt alleen voor landen met een module nationaal recht. Rollen en ondernemingsgrootte geeft u handmatig op.",
    "html.11": "Richtlijn (EU) 2022/2555 (NIS 2) moet in nationaal recht worden omgezet. De beoordeling omvat de verplichtingen die rechtstreeks uit de richtlijn voortvloeien en Uitvoeringsverordening (EU) 2024/2690 van de Commissie, die rechtstreeks van toepassing is — voor zover zij de entiteit betreffen.",
    "html.23": "omzet en grootte voert u handmatig in — de gemeenschappelijke module raadpleegt geen nationale registers",
    "html.33": "Richtlijn (EU) 2022/2555 van het Europees Parlement en de Raad van 14 december 2022 (NIS 2)",
    "html.33a": "{p0} — nationale omzettingswet; de eisen daarvan beoordeelt deze module nog niet",
    "html.33b": "het land heeft nog geen omzettingswet aangenomen — de beoordeling volgt het Unierecht",
    "html.35": "verplichtingen van het bestuursorgaan — artikel 20 van de richtlijn",
    "html.36": "Het instrument dient voor zelfbeoordeling. Het is geen audit en geen juridisch advies.",
    "html.40": "de gemeenschappelijke module maakt geen enkele uitgaande verbinding — zij raadpleegt geen registers",
    "html.59": "Jaarrekeningen",
    "html.60": "Het inlezen van een jaarrekening is alleen beschikbaar voor landen met een module nationaal recht. Voor dit land voert u omzet en personeelsbestand handmatig in.",
    "html.62": "Registeropzoeking",
    "html.63": "handelsregisters zijn nationaal — de gemeenschappelijke module kent ze niet",
    "html.64": "rollen en ondernemingsgrootte geeft u handmatig op",
    "html.66": "Identificatienummer van de entiteit",
    "html.68": "Het automatisch ophalen van registergegevens werkt alleen voor landen met een module nationaal recht.",
    "html.76": "Jaaromzet (EUR)",
    "html.78": "Omzet uit elektronischecommunicatieactiviteit (EUR)",
    "html.79": "Dit veld betreft aanbieders van openbare elektronischecommunicatienetwerken of -diensten. Nationale drempels worden bepaald door het recht van de lidstaat.",
    "html.80": "Maandelijkse bezoldiging van de leidinggevende (EUR)",
    "html.82": "Wisselkoers",
    "html.83": "De boeteplafonds in de richtlijn zijn in euro uitgedrukt. Omrekening naar de nationale valuta en de koers worden door het nationale recht bepaald — hier staan de bedragen in euro zonder omrekening.",
    "html.84": "De status vloeit uitsluitend voort uit de samentelling van gegevens van verbonden ondernemingen, en het informatiesysteem van de entiteit is onafhankelijk (overweging 16 van de richtlijn — of dit geldt, beslist het nationale recht)",
    "html.85": "De entiteit is actief op het gebied van nationale veiligheid, openbare veiligheid, defensie of rechtshandhaving (artikel 2, lid 7, van de richtlijn)",
    "html.91": "Nalevingsbeoordeling aan de hand van Richtlijn (EU) 2022/2555 van het Europees Parlement en de Raad (NIS 2) en Uitvoeringsverordening (EU) 2024/2690 van de Commissie — gemeenschappelijke module voor landen waarvan de module nationaal recht nog niet klaar is.",
    "html.94": "of de entiteit <strong>essentieel</strong>, <strong>belangrijk</strong> of buiten het toepassingsgebied van de richtlijn is",
    "html.daneZeSprawozdania": "naam, identificatienummer, adres van de zetel",
    "html.rejestrMozliwy": "Het register {p0} is openbaar en kosteloos — het uitlezen kan worden toegevoegd; pull requests zijn welkom (zie README).",
    "html.tytulNaglowka": "Nalevingsbeoordeling NIS 2-richtlijn",
    "html.zrodlaRecznie": "Deze module kent de registers van uw land niet — vul het profiel handmatig in. De jaaromzet bepaalt het boetemaximum, geef die dus nauwkeurig op.",
    "klasyfikacja.10": "artikel 3, lid 1, punt c), van Richtlijn (EU) 2022/2555 (aanbieder van openbare elektronischecommunicatienetwerken of van openbare elektronischecommunicatiediensten die ten minste een middelgrote onderneming is)",
    "klasyfikacja.11": "artikel 3, lid 2, juncto artikel 2, lid 2, punt a), i), van Richtlijn (EU) 2022/2555 (aanbieder van openbare elektronischecommunicatienetwerken of -diensten die een micro- of kleine onderneming is)",
    "klasyfikacja.12": "artikel 3, lid 1, punt a), van Richtlijn (EU) 2022/2555 (aanbieder van beheerde beveiligingsdiensten die de plafonds voor een middelgrote onderneming overschrijdt)",
    "klasyfikacja.13": "Micro- en kleine ondernemingen vallen uit hoofde van deze rol niet onder de richtlijn (artikel 2, lid 1, a contrario).",
    "klasyfikacja.15": "artikel 3, lid 1, punt b), van Richtlijn (EU) 2022/2555 (gekwalificeerde verlener van vertrouwensdiensten) — ongeacht de ondernemingsgrootte",
    "klasyfikacja.16": "artikel 3, lid 2, juncto artikel 2, lid 2, punt a), ii), van Richtlijn (EU) 2022/2555 (niet-gekwalificeerde verlener van vertrouwensdiensten die een micro-, kleine of middelgrote onderneming is)",
    "klasyfikacja.18": "artikel 3, lid 2, van Richtlijn (EU) 2022/2555 (overheidsinstantie op regionaal niveau, indien de lidstaat daarin voorziet — artikel 2, lid 2, punt f), ii))",
    "klasyfikacja.19": "artikel 3, lid 1, punt f), van Richtlijn (EU) 2022/2555 (overheidsinstantie op het niveau van de centrale overheid — artikel 2, lid 2, punt f), i))",
    "klasyfikacja.2": "Toezicht vooraf en achteraf (artikel 32 van Richtlijn (EU) 2022/2555).",
    "klasyfikacja.20": "artikel 3, lid 2, van Richtlijn (EU) 2022/2555 (overheidsinstantie op regionaal niveau — artikel 2, lid 2, punt f), ii))",
    "klasyfikacja.21": "De omvang van de verplichtingen van overheidsinstanties op lokaal niveau wordt door het nationale recht bepaald (artikel 2, lid 5, punt a), van de richtlijn).",
    "klasyfikacja.22": "Een lidstaat kan entiteiten die actief zijn op het gebied van nationale veiligheid, openbare veiligheid, defensie of rechtshandhaving vrijstellen (artikel 2, lid 7, van de richtlijn). De vrijstelling werkt niet vanzelf — toets het resultaat van de beoordeling aan het nationale recht.",
    "klasyfikacja.23": "De entiteit voldoet aan de criteria van zowel een essentiële als een belangrijke entiteit. Zij is een essentiële entiteit (artikel 3, lid 1, van de richtlijn), en de hogere vereisten gelden voor alle activiteiten die onder de richtlijn vallen.",
    "klasyfikacja.25": "De entiteit is essentieel, dus gelden de volledige catalogus van maatregelen van artikel 21, lid 2, van de richtlijn en het toezicht vooraf en achteraf — de beoordeling omvat de volledige set vragen.",
    "klasyfikacja.26": "Als belangrijke entiteit valt u onder dezelfde catalogus van maatregelen van artikel 21, lid 2, maar alleen onder toezicht achteraf (artikel 33). Het boeteplafond is lager: 7 miljoen EUR of 1,4 % van de omzet (artikel 34, lid 5). Verlichtingen voor overheidsinstanties kunnen bij nationaal recht worden ingevoerd — deze module kent ze niet.",
    "klasyfikacja.28": "De verplichtingen van overheidsinstanties vloeien voort uit artikel 2, lid 2, punt f), van de richtlijn; de precieze omvang, ook voor het lokale niveau en onderwijsinstellingen, wordt door het nationale recht bepaald (artikel 2, lid 5).",
    "klasyfikacja.29": "Er is verklaard dat de status van de entiteit uitsluitend voortvloeit uit de samentelling van gegevens van verbonden of partnerondernemingen en dat het informatiesysteem van de entiteit onafhankelijk is. De richtlijn staat zo'n uitsluiting toe (overweging 16), maar het nationale recht beslist erover — de module gaat uit van de uitsluiting, die aan het recht van de lidstaat moet worden getoetst en gedocumenteerd.",
    "klasyfikacja.4": "Uitsluitend toezicht achteraf — bij bewijs, aanwijzingen of informatie over een inbreuk (artikel 33 van Richtlijn (EU) 2022/2555).",
    "klasyfikacja.5": "Buiten het toepassingsgebied van de richtlijn",
    "klasyfikacja.6": "Geen verplichtingen uit Richtlijn (EU) 2022/2555 voor de opgegeven rol.",
    "klasyfikacja.7": "artikel 3, lid 1, punt a), van Richtlijn (EU) 2022/2555 (entiteit van een in bijlage I genoemd type die de plafonds voor een middelgrote onderneming overschrijdt)",
    "klasyfikacja.8": "artikel 3, lid 2, van Richtlijn (EU) 2022/2555 (entiteit van een in bijlage I genoemd type die aan de criteria voor een middelgrote onderneming voldoet)",
    "klasyfikacja.9": "Micro- en kleine ondernemingen vallen uit hoofde van deze rol niet onder de richtlijn (artikel 2, lid 1, a contrario).",
    "kreator.10": "Voer de omzet van het vorige jaar handmatig in.",
    "kreator.35": "<span class=\"text-secondary\">Het inlezen van jaarrekeningen is voor dit land niet beschikbaar.</span>",
    "kreator.37": "Het inlezen van jaarrekeningen is voor dit land niet beschikbaar — voer de omzet handmatig in.",
    "kreator.56": "Ja — de EU-verordening is sinds 7 november 2024 rechtstreeks van toepassing in alle lidstaten en kent geen overgangsperiode. De grondslag is",
    "kreator.57": ", dat de Commissie de bevoegdheid gaf om de technische en methodologische vereisten voor de in artikel 3, lid 1, van de verordening genoemde aanbieders vast te stellen. De omzettingstermijn van de richtlijn is verstreken op",
    "kreator.58": ", en vanaf wanneer de nationale autoriteit boetes kan opleggen, wordt door het nationale recht bepaald. De technische vereisten van de bijlage (afdelingen 6 en 9–13) zijn in hun huidige vorm bindend — zij wachten niet op nadere uitwerking. Alleen van vereisten met de formule ‘in voorkomend geval’ kan worden afgeweken, en uitsluitend met een gedocumenteerde motivering.",
    "kreator.9": "Jaarrekeningen →",
    "kreator.przepisReg2690": "artikel 21, lid 5, van Richtlijn (EU) 2022/2555",
    "kreator.terminReg2690": "17 oktober 2024",
    "punktacja.10": "Overheidsinstanties",
    "punktacja.4": "NIS 2-richtlijn — artikel 21",
    "punktacja.5": "NIS 2-richtlijn — formele verplichtingen",
    "punktacja.8": "Elektronische communicatie",
    "punktacja.9": "NIS 2-richtlijn — overheidsinstanties",
    "punktacja.skrotKsc": "NIS 2",
    "punktacja.skrotPke": "telecom",
    "ue.cyt.akapit": ", {p0} alinea",
    "ue.cyt.art": "artikel {p0}",
    "ue.cyt.drugi": "tweede",
    "ue.cyt.dyr": "{p0}, van Richtlijn (EU) 2022/2555",
    "ue.cyt.i": "en",
    "ue.cyt.laczenie": "",
    "ue.cyt.lit": ", punt {p0})",
    "ue.cyt.litery": "",
    "ue.cyt.pkt": ", punt {p0}",
    "ue.cyt.rozdzielacz": "; ",
    "ue.cyt.rozp": "{p0}, van Verordening (EU) 2024/2690",
    "ue.cyt.ust": ", lid {p0}",
    "ue.katalog.1": "Beleid inzake risicoanalyse en beveiliging van informatiesystemen",
    "ue.katalog.10": "Incidentenbehandeling",
    "ue.katalog.11": "Incidentenbehandeling omvat alle acties en procedures om incidenten te voorkomen, op te sporen, te analyseren en in te dammen, erop te reageren en ervan te herstellen (artikel 6, punt 8).",
    "ue.katalog.12": "Bestaat er een gedocumenteerde procedure voor incidentenbehandeling die opsporing, analyse, indamming, reactie en herstel omvat?",
    "ue.katalog.13": "ISO/IEC 27001 A.5.24–A.5.26",
    "ue.katalog.14": "Maakt de procedure het mogelijk de meldingstermijnen voor een significant incident te halen: vroegtijdige waarschuwing binnen 24 uur, melding binnen 72 uur, eindverslag binnen een maand?",
    "ue.katalog.15": "ISO/IEC 27001 A.5.24",
    "ue.katalog.16": "Beschikt de entiteit over criteria om een incident als significant aan te merken, in lijn met artikel 23, lid 3: ernstige operationele verstoring of financieel verlies, dan wel aanzienlijke schade voor anderen?",
    "ue.katalog.17": "ISO/IEC 27001 A.5.25",
    "ue.katalog.18": "Worden incidenten geregistreerd en worden de lessen uit de afhandeling gebruikt om de maatregelen te verbeteren?",
    "ue.katalog.19": "ISO/IEC 27001 A.5.27",
    "ue.katalog.2": "De maatregelen zijn gebaseerd op een allhazardsbenadering (artikel 21, lid 2). De evenredigheid ervan wordt beoordeeld met inachtneming van de mate van blootstelling, de grootte van de entiteit, de waarschijnlijkheid van incidenten en de ernst ervan (artikel 21, lid 1, tweede alinea).",
    "ue.katalog.20": "Bedrijfscontinuïteit en crisisbeheer",
    "ue.katalog.21": "Bedrijfscontinuïteit, zoals back-upbeheer en noodherstel, en crisisbeheer.",
    "ue.katalog.22": "Bestaat er een bedrijfscontinuïteitsplan dat het herstel na een noodsituatie omvat?",
    "ue.katalog.23": "ISO/IEC 27001 A.5.29–A.5.30",
    "ue.katalog.24": "Worden back-ups gemaakt, beschermd en getest op herstelbaarheid?",
    "ue.katalog.25": "ISO/IEC 27001 A.8.13",
    "ue.katalog.26": "Beschikt de entiteit over crisisbeheerprocedures met vastgelegde rollen en communicatiekanalen?",
    "ue.katalog.27": "ISO/IEC 27001 A.5.29",
    "ue.katalog.28": "Worden de continuïteits- en herstelplannen periodiek getest en de resultaten gedocumenteerd?",
    "ue.katalog.29": "ISO/IEC 27001 A.5.30",
    "ue.katalog.3": "Beschikt de entiteit over een gedocumenteerd, door het bestuursorgaan goedgekeurd beleid inzake risicoanalyse en beveiliging van informatiesystemen?",
    "ue.katalog.30": "Beveiliging van de toeleveringsketen",
    "ue.katalog.31": "Beveiliging van de toeleveringsketen, met inbegrip van beveiligingsaspecten van de relaties tussen de entiteit en haar rechtstreekse leveranciers of dienstverleners. De entiteit houdt rekening met de specifieke kwetsbaarheden van elke leverancier en de algehele kwaliteit van diens producten en cyberbeveiligingspraktijken (artikel 21, lid 3).",
    "ue.katalog.32": "Houdt de entiteit een lijst bij van rechtstreekse leveranciers en dienstverleners met een beoordeling van hun belang voor de beveiliging van netwerken en systemen?",
    "ue.katalog.33": "ISO/IEC 27001 A.5.19",
    "ue.katalog.34": "Wordt bij de keuze van maatregelen jegens leveranciers rekening gehouden met hun specifieke kwetsbaarheden en de kwaliteit van hun cyberbeveiligings- en veilige-ontwikkelingspraktijken?",
    "ue.katalog.35": "ISO/IEC 27001 A.5.19, A.5.21",
    "ue.katalog.36": "Bevatten contracten met leveranciers beveiligingsvereisten en een verplichting om incidenten en kwetsbaarheden te melden?",
    "ue.katalog.37": "ISO/IEC 27001 A.5.20",
    "ue.katalog.38": "Houdt de entiteit rekening met de resultaten van de gecoördineerde beveiligingsrisicobeoordelingen van kritieke toeleveringsketens als bedoeld in artikel 22?",
    "ue.katalog.39": "ISO/IEC 27001 A.5.21",
    "ue.katalog.4": "ISO/IEC 27001 punten 5.2, 6.1.2",
    "ue.katalog.40": "Beveiliging bij verwerving, ontwikkeling en onderhoud van systemen",
    "ue.katalog.41": "Beveiliging bij de verwerving, ontwikkeling en het onderhoud van netwerk- en informatiesystemen, met inbegrip van de afhandeling en bekendmaking van kwetsbaarheden.",
    "ue.katalog.42": "Worden beveiligingsvereisten vastgesteld vóór de verwerving of het begin van de ontwikkeling van een systeem en gecontroleerd vóór de ingebruikname?",
    "ue.katalog.43": "ISO/IEC 27001 A.8.25–A.8.29",
    "ue.katalog.44": "Bestaat er een proces voor de afhandeling van kwetsbaarheden: identificatie, beoordeling, verhelpen binnen een vastgestelde termijn?",
    "ue.katalog.45": "ISO/IEC 27001 A.8.8",
    "ue.katalog.46": "Beschikt de entiteit over een procedure voor de bekendmaking van kwetsbaarheden, inclusief een kanaal voor meldingen van derden?",
    "ue.katalog.47": "Doorlopen wijzigingen in systemen een gecontroleerd wijzigingsbeheerproces met beoordeling van de impact op de beveiliging?",
    "ue.katalog.48": "ISO/IEC 27001 A.8.32",
    "ue.katalog.49": "Beoordeling van de doeltreffendheid van maatregelen",
    "ue.katalog.5": "Bestrijkt de risicoanalyse alle gevaren voor netwerk- en informatiesystemen en hun fysieke omgeving, en niet alleen cyberdreigingen?",
    "ue.katalog.50": "Beleid en procedures om de doeltreffendheid van maatregelen voor het beheer van cyberbeveiligingsrisico's te beoordelen.",
    "ue.katalog.51": "Bestaat er een gedocumenteerd beleid voor de beoordeling van de doeltreffendheid van maatregelen, met reikwijdte, frequentie en methoden?",
    "ue.katalog.52": "ISO/IEC 27001 punt 9.1",
    "ue.katalog.53": "Worden doeltreffendheidsbeoordelingen periodiek uitgevoerd en de resultaten aan het bestuursorgaan gerapporteerd?",
    "ue.katalog.54": "ISO/IEC 27001 punten 9.2–9.3",
    "ue.katalog.55": "Leiden vastgestelde zwakke punten tot gedocumenteerde corrigerende maatregelen met eigenaar en termijn?",
    "ue.katalog.56": "ISO/IEC 27001 punt 10.1",
    "ue.katalog.57": "Cyberhygiëne en opleiding",
    "ue.katalog.58": "Basispraktijken op het gebied van cyberhygiëne en opleiding op het gebied van cyberbeveiliging. Leden van het bestuursorgaan volgen regelmatig opleidingen (artikel 20, lid 2).",
    "ue.katalog.59": "Past de entiteit basispraktijken van cyberhygiëne toe: updates, wachtwoordbeheer, beperking van rechten, bescherming tegen malware?",
    "ue.katalog.6": "ISO/IEC 27001 punt 6.1.2",
    "ue.katalog.60": "ISO/IEC 27001 A.8.7, A.8.8",
    "ue.katalog.61": "Volgen werknemers op hun rol afgestemde cyberbeveiligingsopleidingen, en wordt deelname gedocumenteerd?",
    "ue.katalog.62": "ISO/IEC 27001 A.6.3",
    "ue.katalog.63": "Volgen leden van het bestuursorgaan regelmatig opleidingen waarmee zij risico's kunnen herkennen en risicobeheerpraktijken kunnen beoordelen?",
    "ue.katalog.64": "ISO/IEC 27001 punt 7.2",
    "ue.katalog.65": "Cryptografie en encryptie",
    "ue.katalog.66": "Beleid en procedures inzake het gebruik van cryptografie en, in voorkomend geval, encryptie.",
    "ue.katalog.67": "Bestaat er een cryptografiebeleid dat bepaalt welke gegevens en kanalen worden versleuteld en met welke algoritmen?",
    "ue.katalog.68": "ISO/IEC 27001 A.8.24",
    "ue.katalog.69": "Worden cryptografische sleutels over de volledige levenscyclus beheerd: aanmaak, distributie, opslag, rotatie, buitengebruikstelling?",
    "ue.katalog.7": "Houdt de keuze van maatregelen rekening met de stand van de techniek, relevante Europese en internationale normen en de uitvoeringskosten?",
    "ue.katalog.70": "Personeel, toegangsbeheer en activabeheer",
    "ue.katalog.71": "Beveiliging van personeel, toegangsbeheerbeleid en activabeheer.",
    "ue.katalog.72": "Houdt de entiteit een actueel activaregister bij met toegewezen eigenaren en classificatie?",
    "ue.katalog.73": "ISO/IEC 27001 A.5.9, A.5.12",
    "ue.katalog.74": "Bestaat er een toegangsbeheerbeleid op basis van het beginsel van minimale rechten, met periodieke herziening van rechten?",
    "ue.katalog.75": "ISO/IEC 27001 A.5.15, A.5.18",
    "ue.katalog.76": "Worden bij indiensttreding, functiewijziging en vertrek van personeel beveiligingsprocedures toegepast, waaronder het intrekken van rechten en het teruggeven van activa?",
    "ue.katalog.77": "ISO/IEC 27001 A.6.1–A.6.5",
    "ue.katalog.78": "Is geprivilegieerde toegang beperkt, gelogd en herzien?",
    "ue.katalog.79": "ISO/IEC 27001 A.8.2",
    "ue.katalog.8": "ISO/IEC 27001 punt 6.1.3",
    "ue.katalog.80": "Multifactorauthenticatie en beveiligde communicatie",
    "ue.katalog.81": "In voorkomend geval — multifactor- of continue authenticatie, beveiligde spraak-, video- en tekstcommunicatie en beveiligde noodcommunicatiesystemen binnen de entiteit.",
    "ue.katalog.82": "Wordt multifactor- of continue authenticatie toegepast waar de risicoanalyse dat rechtvaardigt, met name voor toegang op afstand en geprivilegieerde accounts?",
    "ue.katalog.83": "ISO/IEC 27001 A.8.5",
    "ue.katalog.84": "Zijn de voor zakelijke doeleinden gebruikte spraak-, video- en tekstverbindingen beveiligd?",
    "ue.katalog.85": "ISO/IEC 27001 A.8.20",
    "ue.katalog.86": "Beschikt de entiteit over een beveiligd intern noodcommunicatiesysteem dat onafhankelijk is van de hoofdinfrastructuur?",
    "ue.katalog.9": "Is het beveiligingsniveau gedocumenteerd als passend bij het bestaande risico, met een motivering die rekening houdt met de grootte van de entiteit en de maatschappelijke en economische gevolgen van incidenten?",
    "ue.kierownictwo.1": "Het bestuursorgaan van een essentiële of belangrijke entiteit — bij een kapitaalvennootschap het bestuur. De richtlijn definieert het begrip niet; de reikwijdte ervan in een land volgt uit het nationale recht.",
    "ue.kierownictwo.10": "De status van de entiteit vaststellen en voor registratie zorgen",
    "ue.kierownictwo.11": "Vaststellen of de entiteit essentieel of belangrijk is en registratiegegevens indienen bij de bevoegde autoriteit. Procedure en termijn worden door het nationale recht bepaald.",
    "ue.kierownictwo.12": "Risicoanalyse en beveiligingsbeleid invoeren",
    "ue.kierownictwo.13": "Maatregelen op basis van een allhazardsbenadering, evenredig aan de blootstelling, de grootte van de entiteit en de ernst van incidenten.",
    "ue.kierownictwo.14": "Incidentenbehandeling en -melding opzetten",
    "ue.kierownictwo.15": "Een procedure voor incidentenbehandeling en het vermogen om de termijnen van 24 uur, 72 uur en een maand te halen.",
    "ue.kierownictwo.16": "24 u / 72 u / een maand na ontdekking",
    "ue.kierownictwo.17": "Bedrijfscontinuïteit waarborgen",
    "ue.kierownictwo.18": "Continuïteitsplan, back-ups, herstel na een noodsituatie, crisisbeheer.",
    "ue.kierownictwo.19": "De toeleveringsketen op orde brengen",
    "ue.kierownictwo.2": "De aansprakelijkheid van het bestuursorgaan laat de nationale regels inzake de aansprakelijkheid van overheidsinstellingen en ambtenaren onverlet (artikel 20, lid 1, tweede alinea).",
    "ue.kierownictwo.20": "Lijst van leveranciers, beoordeling van hun kwetsbaarheden en praktijken, beveiligingsvereisten in contracten.",
    "ue.kierownictwo.21": "Toegangsbeheer en activabeheer invoeren",
    "ue.kierownictwo.22": "Activaregister, beginsel van minimale rechten, herziening van rechten, multifactorauthenticatie waar het risico dat rechtvaardigt.",
    "ue.kierownictwo.23": "De doeltreffendheid van maatregelen meten",
    "ue.kierownictwo.24": "Beleid en procedures voor doeltreffendheidsbeoordeling, periodieke herzieningen, corrigerende maatregelen.",
    "ue.kierownictwo.25": "Goedkeuren",
    "ue.kierownictwo.26": "de maatregelen voor het beheer van cyberbeveiligingsrisico's (artikel 20, lid 1)",
    "ue.kierownictwo.27": "het beleid inzake risicoanalyse en systeembeveiliging",
    "ue.kierownictwo.28": "het budget en de rollen bij de invoering",
    "ue.kierownictwo.29": "Toezien op",
    "ue.kierownictwo.3": "Of het toevertrouwen van taken aan een ander de aansprakelijkheid uitsluit, beslist het nationale recht. In Polen niet (artikel 8c, lid 3, van de wet op het nationale cyberbeveiligingssysteem).",
    "ue.kierownictwo.30": "de uitvoering van de goedgekeurde maatregelen (artikel 20, lid 1)",
    "ue.kierownictwo.31": "de resultaten van de doeltreffendheidsbeoordeling (artikel 21, lid 2, punt f))",
    "ue.kierownictwo.32": "het naleven van de meldingstermijnen voor incidenten (artikel 23)",
    "ue.kierownictwo.33": "Documenteren",
    "ue.kierownictwo.34": "goedkeuringsbesluiten en herzieningen",
    "ue.kierownictwo.35": "deelname aan opleidingen (artikel 20, lid 2)",
    "ue.kierownictwo.36": "Lid van het bestuursorgaan",
    "ue.kierownictwo.37": "goedkeuring van maatregelen, toezicht, besluiten, budget",
    "ue.kierownictwo.38": "Projectleider",
    "ue.kierownictwo.39": "coördinatie van de invoering, planning, status en bewijs",
    "ue.kierownictwo.4": "De maatregelen voor het beheer van cyberbeveiligingsrisico's goedkeuren",
    "ue.kierownictwo.40": "IT / cyberbeveiliging",
    "ue.kierownictwo.41": "risicoanalyse, technische maatregelen, incidentenbehandeling",
    "ue.kierownictwo.42": "Juridische zaken / compliance",
    "ue.kierownictwo.5": "Het bestuursorgaan keurt de maatregelen goed die zijn genomen om aan artikel 21 te voldoen. Dat is een besluit van het orgaan, niet van de IT-afdeling — zonder dat besluit missen de maatregelen een grondslag.",
    "ue.kierownictwo.6": "Toezien op de uitvoering van de maatregelen",
    "ue.kierownictwo.7": "Het toezicht op de uitvoering is een verplichting van het bestuursorgaan. De uitvoering kan worden toevertrouwd, het toezicht niet.",
    "ue.kierownictwo.8": "Regelmatig opleidingen volgen",
    "ue.kierownictwo.9": "Leden van het bestuursorgaan volgen regelmatig opleidingen om voldoende kennis te verwerven om risico's te herkennen en risicobeheerpraktijken en de gevolgen daarvan voor de diensten van de entiteit te beoordelen.",
    "ue.kierownictwo.daneRejestracyjne": "registratiegegevens en de bijwerking ervan (artikel 3, leden 4 en 5)",
    "ue.meta.1": "De percentagevariant prevaleert: {p0} % van de omzet is hoger dan {p1} miljoen EUR.",
    "ue.meta.10": "De richtlijn legt ondernemingen geen verplichtingen rechtstreeks op — dat doet de nationale wet, die de lidstaat uiterlijk 17 oktober 2024 moest vaststellen. Deze module toont de vereisten in de bewoordingen van de richtlijn, omdat de module nationaal recht van het gekozen land nog niet klaar is of het land de richtlijn niet heeft omgezet.",
    "ue.meta.11": "Verplichtingen uit de richtlijn",
    "ue.meta.12": "Lijst van entiteiten — uiterlijk 17 april 2025",
    "ue.meta.13": "De lidstaten moesten uiterlijk 17 april 2025 een lijst van essentiële en belangrijke entiteiten opstellen en van entiteiten verlangen dat zij registratiegegevens indienen.",
    "ue.meta.14": "Verordening (EU) 2024/2690",
    "ue.meta.15": "Rechtstreeks van toepassing sinds 7 november 2024",
    "ue.meta.16": "De uitvoeringsverordening is rechtstreeks van toepassing in alle lidstaten, ongeacht de stand van de omzetting van de richtlijn. Zij betreft de entiteiten die in artikel 1 ervan zijn genoemd: DNS, TLD, cloud, datacentra, netwerken voor de levering van inhoud, beheerde diensten en vertrouwensdiensten.",
    "ue.meta.17": "artikel 16 van Verordening (EU) 2024/2690",
    "ue.meta.18": "Ten minste 10 000 000 EUR of ten minste 2 % van de totale wereldwijde jaaromzet van de onderneming in het voorgaande boekjaar — het hoogste bedrag geldt. Dit is een minimumplafond: het nationale recht kan het verhogen.",
    "ue.meta.19": "Ten minste 7 000 000 EUR of 1,4 % van de totale wereldwijde jaaromzet — het hoogste bedrag geldt. Minimumplafond.",
    "ue.meta.2": "Het vaste bedrag prevaleert: {p0} miljoen EUR is hoger dan {p1} % van de omzet.",
    "ue.meta.20": "De richtlijn voorziet niet in een afzonderlijke boete voor een gekwalificeerde inbreuk — dat is een constructie van het nationale recht van sommige landen.",
    "ue.meta.21": "De lidstaten kunnen dwangsommen vaststellen om beëindiging van een inbreuk af te dwingen. De hoogte wordt door het nationale recht bepaald.",
    "ue.meta.22": "Het bestuursorgaan keurt de risicobeheersmaatregelen goed, houdt toezicht op de uitvoering ervan en kan aansprakelijk worden gesteld voor inbreuken op artikel 21. De regels en omvang van die aansprakelijkheid worden door het nationale recht bepaald.",
    "ue.meta.23": "Het bestuursorgaan keurt de maatregelen voor het beheer van cyberbeveiligingsrisico's goed (artikel 20, lid 1).",
    "ue.meta.24": "Het bestuursorgaan houdt toezicht op de uitvoering van die maatregelen (artikel 20, lid 1).",
    "ue.meta.25": "Leden van het bestuursorgaan volgen regelmatig opleidingen (artikel 20, lid 2).",
    "ue.meta.26": "Ten aanzien van een essentiële entiteit kan de autoriteit om een tijdelijk verbod op het uitoefenen van leidinggevende functies verzoeken (artikel 32, lid 5, punt b)).",
    "ue.meta.27": "Het minimumplafond wordt door de richtlijn bepaald",
    "ue.meta.28": "Twee waarden worden vergeleken: een vast bedrag in euro en een percentage van de totale wereldwijde jaaromzet van de onderneming in het voorgaande boekjaar. De hoogste is de bovengrens die de lidstaat ten minste moet vaststellen. Het nationale recht kan die verhogen.",
    "ue.meta.29": "Het bedrag binnen het plafond wordt door de nationale autoriteit bepaald",
    "ue.meta.3": "Het plafond uit de richtlijn is {p0} keer de jaaromzet van de entiteit. Artikel 34, lid 1, vereist dat de boete evenredig is aan de omstandigheden van het individuele geval — dit is een bovengrens, geen te verwachten boete.",
    "ue.meta.30": "De boete moet doeltreffend, evenredig en afschrikkend zijn, gelet op de omstandigheden van het individuele geval. De autoriteit houdt ten minste rekening met de criteria van artikel 32, lid 7: ernst en duur van de inbreuk, eerdere inbreuken, schade, opzet, herstelmaatregelen en medewerking.",
    "ue.meta.31": "Het plafond kan een veelvoud van de jaaromzet bedragen — het is een bovengrens, geen te verwachten bedrag. Nationale minima, dwangsommen en de wijze van vaststelling worden door de wet van de lidstaat bepaald.",
    "ue.meta.32": "Bij het besluit om een administratieve geldboete op te leggen en over de hoogte ervan wordt in elk individueel geval naar behoren rekening gehouden met ten minste de in artikel 32, lid 7, genoemde elementen.",
    "ue.meta.33": "de ernst van de inbreuk en het belang van de geschonden bepalingen — als ernstig gelden in elk geval: herhaalde inbreuken, het niet melden of verhelpen van significante incidenten, het niet verhelpen van tekortkomingen in strijd met bindende instructies, het belemmeren van audits of monitoring, het verstrekken van onjuiste of grof onnauwkeurige informatie",
    "ue.meta.34": "relevante eerdere inbreuken door de entiteit",
    "ue.meta.35": "veroorzaakte materiële of immateriële schade, met inbegrip van financieel verlies, gevolgen voor andere diensten en het aantal getroffen gebruikers",
    "ue.meta.36": "het opzettelijke of nalatige karakter van de inbreuk",
    "ue.meta.37": "maatregelen om de schade te voorkomen of te beperken",
    "ue.meta.38": "naleving van goedgekeurde gedragscodes of certificeringsmechanismen",
    "ue.meta.39": "de mate van medewerking met de bevoegde autoriteiten",
    "ue.meta.4": "Richtlijn (EU) 2022/2555 van het Europees Parlement en de Raad (NIS 2)",
    "ue.meta.40": "De richtlijn voorziet niet uitdrukkelijk in het afzien van een boete — of en wanneer dat mogelijk is, beslist het nationale recht.",
    "ue.meta.41": "Vanaf deze datum moeten de lidstaten de nationale bepalingen ter uitvoering van de richtlijn toepassen. De concrete datum vanaf wanneer de autoriteit een boete kan opleggen, volgt uit het nationale recht.",
    "ue.meta.42": "Inwerkingtreding van de NIS 2-richtlijn",
    "ue.meta.43": "Op de twintigste dag na de bekendmaking in het Publicatieblad.",
    "ue.meta.44": "Omzettingstermijn van de richtlijn",
    "ue.meta.45": "Uiterlijk op deze datum moesten de lidstaten nationale bepalingen vaststellen en bekendmaken.",
    "ue.meta.46": "Toepassing van nationale bepalingen en intrekking van NIS 1",
    "ue.meta.47": "Vanaf deze datum passen de lidstaten de uitvoeringsbepalingen toe; Richtlijn (EU) 2016/1148 wordt ingetrokken.",
    "ue.meta.48": "Toepassing van Verordening (EU) 2024/2690",
    "ue.meta.49": "De uitvoeringsverordening is rechtstreeks van toepassing vanaf de twintigste dag na de bekendmaking.",
    "ue.meta.5": "PB EU L 333 van 27.12.2022",
    "ue.meta.50": "Lijst van essentiële en belangrijke entiteiten",
    "ue.meta.51": "Uiterlijk op deze datum stellen de lidstaten de lijst op; entiteiten dienen registratiegegevens in bij de autoriteiten.",
    "ue.meta.52": "Eerste evaluatie van de richtlijn door de Commissie",
    "ue.meta.53": "De Commissie evalueert de werking van de richtlijn en brengt verslag uit.",
    "ue.meta.54": "Vroegtijdige waarschuwing voor een significant incident",
    "ue.meta.55": "24 uur na kennisname",
    "ue.meta.56": "Melding van een significant incident",
    "ue.meta.57": "72 uur na kennisname",
    "ue.meta.58": "Eindverslag",
    "ue.meta.59": "een maand na de incidentmelding",
    "ue.meta.6": "Uitvoeringsverordening (EU) 2024/2690 van de Commissie",
    "ue.meta.60": "Incidentmelding door een verlener van vertrouwensdiensten",
    "ue.meta.61": "artikel 21, lid 5, van Richtlijn (EU) 2022/2555; artikelen 1 en 2 van Verordening (EU) 2024/2690",
    "ue.meta.62": "Zonder omzetgegevens is het plafond het vaste bedrag uit de richtlijn.",
    "ue.meta.63": "De plafonds van artikel 34, leden 4 en 5, zijn minima (‘ten minste’) — het nationale recht kan in hogere voorzien. Bedragen in euro, zonder omrekening naar de nationale valuta.",
    "ue.meta.64": "Bevoegde autoriteit van de lidstaat",
    "ue.meta.65": "Het bestuursorgaan kan aansprakelijk worden gesteld voor inbreuken op artikel 21. Omvang en procedure worden door het nationale recht bepaald — deze module kent ze niet.",
    "ue.meta.66": "De omvang van de persoonlijke aansprakelijkheid van het bestuur volgt uit de nationale wet. Voor Polen is dat tot 300 % van de bezoldiging (artikel 73a, lid 4, van de wet op het nationale cyberbeveiligingssysteem); andere landen regelen dit anders.",
    "ue.meta.7": "PB EU L, 2024/2690",
    "ue.meta.8": "Richtlijn (EU) 2022/2555",
    "ue.meta.9": "De omzettingstermijn is verstreken op 17 oktober 2024",
    "ue.moduly.1": "ongeveer {p0} min",
    "ue.moduly.10": "Tien gebieden uit artikel 21, lid 2, punten a) tot en met j): van risicobeleid tot multifactorauthenticatie. Inbreuk is beboetbaar op grond van artikel 34. Beoordeling op de volwassenheidsschaal.",
    "ue.moduly.11": "Verordening 2024/2690 — governance en processen",
    "ue.moduly.12": "Afdelingen 1–5 en 7–8 van de bijlage: beleid, risicobeheer, incidentenbehandeling, bedrijfscontinuïteit, toeleveringsketen, doeltreffendheidsbeoordeling, cyberhygiëne. Rechtstreeks van toepassing sinds 7 november 2024.",
    "ue.moduly.13": "Verordening 2024/2690 — technische vereisten",
    "ue.moduly.14": "Afdelingen 6 en 9–13 van de bijlage: verwerving en ontwikkeling van systemen, cryptografie, beveiliging van personeel, toegangsbeheer, activabeheer, fysieke en omgevingsbeveiliging.",
    "ue.moduly.2": "ongeveer {p0} u {p1} min",
    "ue.moduly.3": "ongeveer {p0} u",
    "ue.moduly.4": "minder dan een minuut",
    "ue.moduly.5": "Snelle risicobeoordeling",
    "ue.moduly.6": "Overkoepelende vragen uit alle gebieden van de richtlijn. Elke vraag beslist over een hele groep onderwerpen. Hiermee schat u de omvang van de achterstand zonder de volledige vragenlijst te doorlopen.",
    "ue.moduly.7": "Verplichtingen uit de richtlijn",
    "ue.moduly.8": "Registratiegegevens, incidentmelding binnen 24 en 72 uur, verplichtingen van het bestuursorgaan, gereedheid voor toezicht. Te verifiëren aan de hand van documenten, zonder technische analyse.",
    "ue.moduly.9": "Risicobeheersmaatregelen — artikel 21, lid 2",
    "ue.obowiazki.1": "Registratiegegevens voor de lijst van entiteiten",
    "ue.obowiazki.10": "Melding van significante incidenten",
    "ue.obowiazki.11": "De entiteit meldt significante incidenten aan het CSIRT of de bevoegde autoriteit in drie stappen: vroegtijdige waarschuwing, melding, eindverslag. De termijnen lopen vanaf de kennisname van het incident.",
    "ue.obowiazki.12": "Kan de entiteit binnen 24 uur na kennisname van een significant incident een vroegtijdige waarschuwing sturen, met vermelding of het incident vermoedelijk door onrechtmatig handelen is veroorzaakt en of het grensoverschrijdende gevolgen kan hebben?",
    "ue.obowiazki.13": "24 uur na kennisname",
    "ue.obowiazki.14": "Kan de entiteit binnen 72 uur een incidentmelding sturen, met een eerste beoordeling van ernst en gevolgen en indicatoren van aantasting?",
    "ue.obowiazki.15": "72 uur na kennisname",
    "ue.obowiazki.16": "Dient de entiteit uiterlijk een maand na de melding een eindverslag in, met een beschrijving van het incident, het soort dreiging, de mitigerende maatregelen en de grensoverschrijdende gevolgen?",
    "ue.obowiazki.17": "een maand na de melding",
    "ue.obowiazki.18": "Stelt de entiteit de ontvangers van haar diensten in kennis van significante incidenten die de verlening van die diensten negatief kunnen beïnvloeden?",
    "ue.obowiazki.19": "Stelt de entiteit de ontvangers van haar diensten in kennis van een significante cyberdreiging en van de maatregelen die zij kunnen nemen?",
    "ue.obowiazki.2": "De lidstaten stellen een lijst van essentiële en belangrijke entiteiten op en verlangen van entiteiten dat zij registratiegegevens indienen. Procedure, termijn en portaal worden door het nationale recht bepaald.",
    "ue.obowiazki.20": "Als de entiteit een verlener van vertrouwensdiensten is — meldt zij significante incidenten binnen 24 uur na kennisname?",
    "ue.obowiazki.21": "betreft verleners van vertrouwensdiensten",
    "ue.obowiazki.22": "Bestuursorgaan",
    "ue.obowiazki.23": "Het bestuursorgaan keurt de risicobeheersmaatregelen goed, houdt toezicht op de uitvoering ervan en kan aansprakelijk worden gesteld. Leden van het orgaan volgen regelmatig opleidingen.",
    "ue.obowiazki.24": "Heeft het bestuursorgaan de maatregelen voor het beheer van cyberbeveiligingsrisico's die zijn genomen om aan artikel 21 te voldoen, formeel goedgekeurd?",
    "ue.obowiazki.25": "Houdt het bestuursorgaan op gedocumenteerde wijze toezicht op de uitvoering van die maatregelen — bijvoorbeeld via periodieke verslagen en herzieningen?",
    "ue.obowiazki.26": "Volgen leden van het bestuursorgaan regelmatig opleidingen waarmee zij risico's kunnen herkennen en risicobeheerpraktijken kunnen beoordelen, met gedocumenteerde deelname?",
    "ue.obowiazki.27": "Gereedheid voor toezichtmaatregelen",
    "ue.obowiazki.28": "Een essentiële entiteit staat onder toezicht vooraf en achteraf, een belangrijke entiteit alleen onder toezicht achteraf. De autoriteit kan informatie, bewijs van de uitvoering van beleid en auditresultaten opvragen.",
    "ue.obowiazki.29": "Kan de entiteit op verzoek van de autoriteit bewijs overleggen van de uitvoering van het cyberbeveiligingsbeleid, inclusief de resultaten van beveiligingsaudits?",
    "ue.obowiazki.3": "Heeft de entiteit vastgesteld of zij een essentiële of belangrijke entiteit is, op basis van de sector uit bijlage I of II en de ondernemingsgrootte?",
    "ue.obowiazki.30": "Kan de entiteit op verzoek van de autoriteit de gegevens, documenten en informatie verstrekken die nodig zijn voor de uitoefening van de toezichtstaken?",
    "ue.obowiazki.31": "Is de essentiële entiteit voorbereid op een beveiligingsaudit door de autoriteit of een onafhankelijke instantie, op eigen kosten?",
    "ue.obowiazki.4": "Heeft de entiteit registratiegegevens bij de bevoegde autoriteit ingediend: naam, adres en contactgegevens, sector en subsector, lijst van lidstaten waar zij diensten verleent?",
    "ue.obowiazki.5": "Contactgegevens omvatten e-mailadressen, IP-bereiken en telefoonnummers. De nationale termijn en het registratieportaal worden door het recht van de lidstaat bepaald.",
    "ue.obowiazki.6": "Bestaat er een proces om registratiegegevens onverwijld bij te werken na een wijziging?",
    "ue.obowiazki.7": "De richtlijn vereist bijwerking zonder onnodige vertraging; een concrete termijn — bijvoorbeeld 14 dagen in Polen — volgt uit het nationale recht.",
    "ue.obowiazki.8": "Als de entiteit een DNS-dienstverlener, TLD-register, cloudaanbieder, datacentrum, CDN, aanbieder van beheerde diensten, onlinemarktplaats, zoekmachine of sociaal netwerk is — heeft zij de aanvullende gegevens uit artikel 27 ingediend, inclusief het adres van haar hoofdvestiging in de Unie?",
    "ue.obowiazki.9": "betreft entiteiten als bedoeld in artikel 26, lid 1",
    "ue.role.1": "Bevoegde autoriteit van de lidstaat",
    "ue.role.10": "Datacentradiensten: colocatie, infrastructuurhosting en aanverwante diensten.",
    "ue.role.11": "Datacentra",
    "ue.role.12": "Essentiële entiteit boven de drempel voor middelgrote ondernemingen (artikel 3, lid 1, punt a)), belangrijke entiteit bij middelgrote omvang (artikel 3, lid 2). Onder middelgroot — buiten het toepassingsgebied, tenzij de lidstaat de entiteit aanwijst op grond van artikel 2, lid 2, punten b) tot en met e). Valt onder Verordening 2024/2690.",
    "ue.role.13": "Aanbieder van een internetknooppunt",
    "ue.role.14": "Infrastructuur die de uitwisseling van verkeer tussen onafhankelijke netwerken mogelijk maakt.",
    "ue.role.15": "Internetknooppunten",
    "ue.role.16": "Indeling op grootte (artikel 3, lid 1, punt a), en lid 2). Verordening 2024/2690 bestrijkt internetknooppunten niet — artikel 1 van de verordening bevat een gesloten lijst van adressaten.",
    "ue.role.17": "DNS-dienstverlener",
    "ue.role.18": "Domeinnaamomzettingsdiensten, met uitzondering van exploitanten van rootnaamservers.",
    "ue.role.19": "Domeinnaamsysteem",
    "ue.role.2": "bevoegde autoriteit",
    "ue.role.20": "Essentiële entiteit ongeacht de grootte (artikel 3, lid 1, punt b)). Valt onder Verordening 2024/2690.",
    "ue.role.21": "Register voor topleveldomeinnamen",
    "ue.role.22": "Het beheer van een topleveldomeinregister.",
    "ue.role.23": "Essentiële entiteit ongeacht de grootte (artikel 3, lid 1, punt b)). Daarnaast verplichtingen inzake registratiegegevens uit artikel 28. Valt onder Verordening 2024/2690.",
    "ue.role.24": "Aanbieder van cloudcomputingdiensten",
    "ue.role.25": "Cloudcomputingdiensten: infrastructuur, platform, software als dienst.",
    "ue.role.26": "Cloudcomputingdiensten",
    "ue.role.27": "Indeling op grootte (artikel 3, lid 1, punt a), en lid 2). Valt onder Verordening 2024/2690.",
    "ue.role.28": "Aanbieder van een netwerk voor de levering van inhoud",
    "ue.role.29": "Een netwerk van verspreide servers dat inhoud en diensten aan eindgebruikers levert.",
    "ue.role.3": "aangewezen bij nationaal recht; tot de nationale module is ingevoerd, noemt het instrument geen specifieke instelling",
    "ue.role.30": "Netwerken voor de levering van inhoud",
    "ue.role.31": "Verlener van vertrouwensdiensten",
    "ue.role.32": "Vertrouwensdiensten in de zin van Verordening (EU) nr. 910/2014: handtekeningen, zegels, tijdstempels, certificaten.",
    "ue.role.33": "Vertrouwensdiensten",
    "ue.role.34": "Valt ongeacht de grootte onder de richtlijn (artikel 2, lid 2, punt a), ii)). Een gekwalificeerde verlener is ongeacht de grootte een essentiële entiteit (artikel 3, lid 1, punt b)); een niet-gekwalificeerde is essentieel boven de drempel voor middelgrote ondernemingen en anders belangrijk. Valt onder Verordening 2024/2690.",
    "ue.role.35": "Aanbieder van beheerde diensten",
    "ue.role.36": "Beheer van de ICT-infrastructuur van de klant: installatie, onderhoud, ondersteuning, systeembeheer.",
    "ue.role.37": "Beheer van ICT-diensten (B2B)",
    "ue.role.38": "Beheerde diensten",
    "ue.role.39": "Aanbieder van beheerde beveiligingsdiensten",
    "ue.role.4": "Aanbieder van openbare elektronischecommunicatienetwerken of van openbare elektronischecommunicatiediensten",
    "ue.role.40": "Beheerde diensten op het gebied van cyberbeveiliging: monitoring, incidentrespons, tests, advies.",
    "ue.role.41": "Beheerde beveiligingsdiensten",
    "ue.role.42": "De richtlijn deelt in op grootte (artikel 3, lid 1, punt a), en lid 2). De lidstaten mogen de drempel aanscherpen — Polen beschouwt een MSSP al vanaf de omvang van een kleine onderneming als essentiële entiteit; deze module past uitsluitend de regel van de richtlijn toe. Valt onder Verordening 2024/2690.",
    "ue.role.5": "Aanbieden van openbare elektronischecommunicatienetwerken of van openbare elektronischecommunicatiediensten, inclusief internettoegang.",
    "ue.role.6": "Digitale infrastructuur",
    "ue.role.7": "Elektronische communicatie",
    "ue.role.8": "Valt ongeacht de grootte onder de richtlijn (artikel 2, lid 2, punt a), i)). Een middelgrote of grotere onderneming is een essentiële entiteit (artikel 3, lid 1, punt c)), een micro- of kleine onderneming een belangrijke (artikel 3, lid 2). De nationale telecommunicatiewet kan aanvullende verplichtingen opleggen — deze module bevat die niet.",
    "ue.role.9": "Aanbieder van datacentradiensten",
    "ue.role.podstawaArt3b": "artikel 3, lid 1, punt b), van Richtlijn (EU) 2022/2555",
    "ue.zaslepki.1": "Richtlijn (EU) 2022/2555 van het Europees Parlement en de Raad (NIS 2)",
    "ue.zaslepki.10": "Of sommige entiteiten ambtshalve worden ingeschreven, beslist het nationale recht.",
    "ue.zaslepki.11": "Stel vast of u onder de richtlijn valt",
    "ue.zaslepki.12": "Sector uit bijlage I of II en ondernemingsgrootte. Dit deel wordt door het profiel van de entiteit in dit instrument gedaan.",
    "ue.zaslepki.13": "Bepaal de bevoegde autoriteit in uw land",
    "ue.zaslepki.14": "Elke lidstaat wijst een bevoegde autoriteit aan (artikel 8, lid 1). ENISA en de Commissie houden de actuele lijst bij.",
    "ue.zaslepki.15": "Dien de registratiegegevens in",
    "ue.zaslepki.16": "Naam, adres en contactgegevens, sector en subsector, landen waar diensten worden verleend (artikel 3, lid 4). Procedure volgens het nationale recht.",
    "ue.zaslepki.17": "Werk de gegevens onverwijld bij",
    "ue.zaslepki.18": "Elke wijziging van de registratiegegevens vereist een bijwerking (artikel 3, lid 5).",
    "ue.zaslepki.19": "adres en actuele contactgegevens: e-mailadressen, IP-bereiken, telefoonnummers",
    "ue.zaslepki.2": "PB EU L 333 van 27.12.2022, blz. 80",
    "ue.zaslepki.20": "sector en subsector uit bijlage I of II",
    "ue.zaslepki.21": "lijst van lidstaten waarin de entiteit diensten verleent",
    "ue.zaslepki.22": "Wordt door het nationale recht bepaald.",
    "ue.zaslepki.23": "Richtlijn (EU) 2022/2555 — artikel 3",
    "ue.zaslepki.24": "ENISA — bevoegde autoriteiten van de lidstaten",
    "ue.zaslepki.25": "Richtlijn (EU) 2022/2555",
    "ue.zaslepki.26": "De EU-module bevat geen richtsnoeren van een nationale autoriteit — die komen met de module nationaal recht.",
    "ue.zaslepki.27": "Het automatisch ophalen van registergegevens werkt alleen voor landen met een module nationaal recht. Vul het profiel handmatig in.",
    "ue.zaslepki.28": "Het inlezen van een jaarrekening werkt alleen voor landen met een module nationaal recht. Voer omzet en personeelsbestand handmatig in.",
    "ue.zaslepki.3": "Uitvoeringsverordening (EU) 2024/2690 van de Commissie",
    "ue.zaslepki.4": "PB EU L, 2024/2690, 18.11.2024",
    "ue.zaslepki.5": "De NIS 2-richtlijn bevat geen afzonderlijke telecommunicatielaag. Het nationale recht inzake elektronische communicatie kan aanvullende verplichtingen opleggen — deze module kent ze niet.",
    "ue.zaslepki.6": "Lijst van essentiële en belangrijke entiteiten",
    "ue.zaslepki.7": "Bevoegde autoriteit van de lidstaat.",
    "ue.zaslepki.8": "De richtlijn verplicht de lidstaten een lijst van essentiële en belangrijke entiteiten bij te houden en van entiteiten te verlangen dat zij registratiegegevens indienen. Portaal, procedure en termijn worden door het nationale recht bepaald — deze module kent ze niet, omdat de module nationaal recht van het gekozen land nog niet klaar is.",
    "ue.zaslepki.9": "Alle essentiële en belangrijke entiteiten. De termijn wordt door het nationale recht bepaald.",
    "ue.zaslepki.skrotDyrektywy": "NIS 2-richtlijn",
    "ue.zaslepki.skrotReg2690": "Vo. 2024/2690",
    "xlsx.1": "{p0} – {p1} EUR",
    "xlsx.25": "Wisselkoers",
    "xlsx.4": "NALEVINGSRAPPORT NIS 2-RICHTLIJN (EU) 2022/2555",
    "xlsx.58": "Elektronischecommunicatieactiviteit: Verordening (EU) 2024/2690 is niet van toepassing. De drempels worden door het nationale recht bepaald (artikel 23, lid 11, van de richtlijn) — de gemeenschappelijke module kent ze niet.",
    "xlsx.68": "Het instrument dient voor zelfbeoordeling. Het is geen audit en geen juridisch advies.",
    "xlsx.69": "Voor entiteiten die niet onder Verordening (EU) 2024/2690 vallen, worden de drempels voor een significant incident door het nationale recht bepaald (artikel 23, lid 11, van de richtlijn).",
    "xlsx.70": "De in het profiel opgegeven rollen zijn een verklaring. De status wordt bepaald door de daadwerkelijk uitgeoefende activiteit (artikel 3 van Richtlijn (EU) 2022/2555).",
    "xlsx.etykietaKrs": "Registernummer",
    "xlsx.etykietaNip": "Identificatienummer",
    "xlsx.etykietaRegon": "Statistisch nummer"
});
