/* Teksty modułu ue — wersja źródłowa (polska).
   Klucze ue.plik.N nadane mechanicznie przy ekstrakcji; wartość to
   dokładny napis z kodu, z {p0}, {p1}… w miejscu wstawek. Ten sam
   plik zawiera też klucze interfejsu zależne od prawa (te same nazwy
   co w locale/<jezyk>.js). Inne języki: napisy/<kod>.js. */
KRAJE.napisy('ue', 'pl', {
    "app.10": "Zweryfikuj listę ról niżej — o statusie decyduje działalność faktycznie wykonywana (art. 3 dyrektywy (UE) 2022/2555), a nie wpis w rejestrze.",
    "app.14": "Rok wcześniej: {p0} EUR",
    "app.15": "Przychód za okres sprawozdawczy: {p0} EUR",
    "app.19": "Odpytuję rejestry po numerze {p0}…",
    "app.34": " mld EUR",
    "app.35": " mln EUR",
    "app.36": " tys. EUR",
    "app.37": "",
    "app.4": "Automatyczne pobieranie danych z rejestru nie jest dostępne dla tego państwa — wypełnij profil ręcznie.",
    "app.59": "Ocena zgodności z dyrektywą NIS 2 (JSON)",
    "app.68": "Dla tego państwa nie ma rejestru, z którego narzędzie mogłoby pobrać dane — profil wypełnia się ręcznie.",
    "app.69": "Dla tego państwa nie ma rejestru, z którego narzędzie mogłoby pobrać dane. Kliknij, aby włączyć tryb offline.",
    "app.73": " · rachunek zysków i strat w wariancie ",
    "app.74": "<div class=\"mt-2 tekst-uwaga\">Z danych rejestrowych nie wynika żadna rola z sektora infrastruktury cyfrowej. Wskaż role ręcznie niżej.</div>",
    "app.8": "Potwierdzono wpis do rejestru dostawców łączności elektronicznej",
    "app.progDostawcy": "",
    "app.przyklad.adres": "ul. Przykładowa 1, 00-001 Miasto",
    "app.przyklad.forma": "Spółka z ograniczoną odpowiedzialnością",
    "app.przyklad.nazwa": "Przykładowy Operator sp. z o.o.",
    "app.statusVat": " · status VAT: ",
    "dashboard.1": "Na podstawie zadeklarowanych ról i wielkości podmiot nie jest podmiotem kluczowym ani ważnym w rozumieniu art. 3 dyrektywy (UE) 2022/2555. Zweryfikuj profil, jeżeli wynik jest niezgodny z oczekiwaniem.",
    "dashboard.113": "Częste pytania",
    "dashboard.12": "— {p0}; termin transpozycji do prawa krajowego upłynął {p2}",
    "dashboard.123": "Dyrektywa NIS 2",
    "dashboard.30": "Wykaz podmiotów kluczowych i ważnych",
    "dashboard.4": "— stosowane bezpośrednio od {p0} we wszystkich państwach członkowskich, bez transpozycji",
    "dashboard.42": "Wariant kwotowy: {p0}",
    "dashboard.45": "Kryteria z art. 32 ust. 7 dyrektywy:",
    "dashboard.46": "Łącznie",
    "dashboard.49": "Podmiot prowadzi działalność telekomunikacyjną — odpowiedzialność osoby zarządzającej określa prawo krajowe",
    "dashboard.50": "",
    "dashboard.51": "",
    "dashboard.53": "Kara okresowa za zwłokę w wykonaniu decyzji: od {p0} EUR do {p1} EUR za każdy dzień ({p2})",
    "dashboard.54": "Przypadek kwalifikowany: do {p0} EUR ({p1})",
    "dashboard.57": "({p0}). Od kiedy organ krajowy może nakładać kary, określa ustawa transponująca dyrektywę — ten moduł jej nie zna. Obowiązki wdrożeniowe wynikają z prawa krajowego od dnia jego wejścia w życie.",
    "dashboard.65": "({p0}). Od kiedy organ krajowy może nakładać kary, określa ustawa transponująca dyrektywę — ten moduł jej nie zna. Ryzyko finansowe nie jest więc tu datowane, natomiast obowiązki wdrożeniowe wynikają z prawa krajowego od dnia jego wejścia w życie.",
    "dashboard.83": "Działalność telekomunikacyjna — progi określa prawo krajowe.",
    "dashboard.84": "Rozporządzenie (UE) 2024/2690 nie ma zastosowania do dostawców publicznych sieci i usług łączności elektronicznej. Progi uznania incydentu za poważny określa dla nich prawo krajowe (art. 23 ust. 11 dyrektywy) — ten moduł ich nie zna, więc nie podaje wartości liczbowych.",
    "dashboard.terminRejestracji": "Termin przedłożenia danych rejestracyjnych określa prawo krajowe (art. 3 ust. 4 dyrektywy). Dostawcy z art. 27 ust. 1 — usług DNS, rejestry TLD, usług chmurowych, ośrodków przetwarzania danych, sieci dostarczania treści, usług zarządzanych i usług zarządzanych w zakresie bezpieczeństwa — przekazują dane do rejestru ENISA: pierwotnie do 17 stycznia 2025 r., a każdą zmianę bez zbędnej zwłoki.",
    "html.1": "ITORO — Ocena zgodności z dyrektywą NIS 2 (UE) 2022/2555",
    "html.10": "Ocena zgodności z dyrektywą NIS 2 — moduł wspólny",
    "html.100": "Odczyt sprawozdania finansowego działa wyłącznie dla państw z modułem prawa krajowego. Dla tego państwa <strong>przychód</strong> za rok obrotowy wpisujesz ręcznie — od niego zależy wysokość kary.",
    "html.102": "Automatyczne pobieranie danych z rejestrów działa wyłącznie dla państw z modułem prawa krajowego. Role i wielkość przedsiębiorstwa wskazujesz ręcznie.",
    "html.11": "Dyrektywa (UE) 2022/2555 (NIS 2) wymaga transpozycji do prawa krajowego. Ocena obejmuje obowiązki wynikające wprost z dyrektywy oraz rozporządzenie wykonawcze Komisji (UE) 2024/2690, stosowane bezpośrednio — w zakresie, w jakim dotyczą podmiotu.",
    "html.23": "przychód i wielkość wpisujesz ręcznie — moduł wspólny nie odpytuje rejestrów krajowych",
    "html.33": "dyrektywa Parlamentu Europejskiego i Rady (UE) 2022/2555 z 14 grudnia 2022 r. (NIS 2)",
    "html.33a": "{p0} — krajowy akt wdrażający dyrektywę; jego wymogów ten moduł jeszcze nie ocenia",
    "html.33b": "państwo nie uchwaliło jeszcze aktu wdrażającego — ocena według prawa Unii",
    "html.35": "obowiązki organu zarządzającego — art. 20 dyrektywy",
    "html.36": "Narzędzie służy samoocenie. Nie jest audytem ani opinią prawną.",
    "html.40": "moduł wspólny nie wykonuje żadnych połączeń wychodzących — nie odpytuje rejestrów",
    "html.59": "Sprawozdania finansowe",
    "html.60": "Odczyt sprawozdania finansowego jest dostępny wyłącznie dla państw z modułem prawa krajowego. Dla tego państwa przychód i zatrudnienie wpisujesz ręcznie.",
    "html.62": "Wyszukanie w rejestrze",
    "html.63": "rejestry gospodarcze są krajowe — moduł wspólny ich nie zna",
    "html.64": "role i wielkość przedsiębiorstwa wskazujesz ręcznie",
    "html.66": "Numer identyfikacyjny podmiotu",
    "html.68": "Automatyczne pobieranie danych z rejestrów działa wyłącznie dla państw z modułem prawa krajowego.",
    "html.76": "Roczny przychód (EUR)",
    "html.78": "Przychód z działalności telekomunikacyjnej (EUR)",
    "html.79": "Pole dotyczy dostawców publicznych sieci lub usług łączności elektronicznej. Progi krajowe określa prawo państwa członkowskiego.",
    "html.80": "Miesięczne wynagrodzenie kierownika (EUR)",
    "html.82": "Kurs walutowy",
    "html.83": "Pułapy kar w dyrektywie są wyrażone w euro. Przeliczenie na walutę krajową i kurs określa prawo krajowe — tu kwoty podane są w euro bez przeliczania.",
    "html.84": "Status wynika wyłącznie z agregacji danych przedsiębiorstw powiązanych, a system informacyjny podmiotu jest niezależny (motyw 16 dyrektywy — o zastosowaniu rozstrzyga prawo krajowe)",
    "html.85": "Podmiot działa w dziedzinie bezpieczeństwa narodowego, bezpieczeństwa publicznego, obronności lub egzekwowania prawa (art. 2 ust. 7 dyrektywy)",
    "html.91": "Ocena zgodności z dyrektywą Parlamentu Europejskiego i Rady (UE) 2022/2555 (NIS 2) oraz z rozporządzeniem wykonawczym Komisji (UE) 2024/2690 — moduł wspólny dla państw, których moduł prawa krajowego nie jest jeszcze gotowy.",
    "html.94": "czy podmiot jest <strong>kluczowy</strong>, <strong>ważny</strong>, czy poza zakresem dyrektywy",
    "html.daneZeSprawozdania": "nazwa, numer identyfikacyjny, adres siedziby",
    "html.rejestrMozliwy": "Rejestr {p0} jest publiczny i bezpłatny — odczyt można dopisać do narzędzia; przyjmujemy pull requesty (patrz README).",
    "html.tytulNaglowka": "Ocena zgodności z dyrektywą NIS 2",
    "html.zrodlaRecznie": "Ten moduł nie zna rejestrów Twojego państwa — profil wypełnij ręcznie. Roczny przychód wyznacza pułap kary, więc wpisz go dokładnie.",
    "klasyfikacja.10": "art. 3 ust. 1 lit. c dyrektywy (UE) 2022/2555 (dostawca publicznej sieci lub publicznie dostępnych usług łączności elektronicznej będący co najmniej średnim przedsiębiorstwem)",
    "klasyfikacja.11": "art. 3 ust. 2 w zw. z art. 2 ust. 2 lit. a ppkt (i) dyrektywy (UE) 2022/2555 (dostawca publicznej sieci lub usług łączności elektronicznej będący mikro- lub małym przedsiębiorstwem)",
    "klasyfikacja.12": "art. 3 ust. 1 lit. a dyrektywy (UE) 2022/2555 (dostawca usług zarządzanych w zakresie bezpieczeństwa przekraczający pułapy dla średniego przedsiębiorstwa)",
    "klasyfikacja.13": "Mikro- i mali przedsiębiorcy nie są objęci dyrektywą z tytułu tej roli (art. 2 ust. 1 a contrario).",
    "klasyfikacja.15": "art. 3 ust. 1 lit. b dyrektywy (UE) 2022/2555 (kwalifikowany dostawca usług zaufania) — niezależnie od wielkości przedsiębiorstwa",
    "klasyfikacja.16": "art. 3 ust. 2 w zw. z art. 2 ust. 2 lit. a ppkt (ii) dyrektywy (UE) 2022/2555 (niekwalifikowany dostawca usług zaufania będący mikro-, małym lub średnim przedsiębiorstwem)",
    "klasyfikacja.18": "art. 3 ust. 2 dyrektywy (UE) 2022/2555 (podmiot administracji publicznej na poziomie regionalnym, jeżeli państwo członkowskie tak postanowi — art. 2 ust. 2 lit. f ppkt (ii))",
    "klasyfikacja.19": "art. 3 ust. 1 lit. f dyrektywy (UE) 2022/2555 (podmiot administracji publicznej na poziomie centralnym — art. 2 ust. 2 lit. f ppkt (i))",
    "klasyfikacja.2": "Nadzór ex ante i ex post (art. 32 dyrektywy (UE) 2022/2555).",
    "klasyfikacja.20": "art. 3 ust. 2 dyrektywy (UE) 2022/2555 (podmiot administracji publicznej na poziomie regionalnym — art. 2 ust. 2 lit. f ppkt (ii))",
    "klasyfikacja.21": "Zakres obowiązków podmiotów administracji publicznej na poziomie lokalnym określa prawo krajowe (art. 2 ust. 5 lit. a dyrektywy).",
    "klasyfikacja.22": "Państwo członkowskie może wyłączyć podmioty prowadzące działalność w dziedzinie bezpieczeństwa narodowego, bezpieczeństwa publicznego, obronności lub egzekwowania prawa (art. 2 ust. 7 dyrektywy). Wyłączenie nie działa samo z siebie — wynik oceny należy zweryfikować z prawem krajowym.",
    "klasyfikacja.23": "Podmiot spełnia kryteria zarówno podmiotu kluczowego, jak i ważnego. Jest podmiotem kluczowym (art. 3 ust. 1 dyrektywy), a wyższe wymagania stosuje się do całej działalności objętej dyrektywą.",
    "klasyfikacja.25": "Podmiot jest kluczowy, więc obowiązuje go pełny katalog środków z art. 21 ust. 2 dyrektywy oraz nadzór ex ante i ex post — ocena obejmuje pełny zestaw pytań.",
    "klasyfikacja.26": "Jako podmiot ważny podlegacie temu samemu katalogowi środków z art. 21 ust. 2, ale nadzorowi wyłącznie ex post (art. 33). Pułap kary jest niższy: 7 mln EUR albo 1,4 % obrotu (art. 34 ust. 5). Złagodzenia obowiązków dla podmiotów publicznych może wprowadzić prawo krajowe — ten moduł ich nie zna.",
    "klasyfikacja.28": "Obowiązki podmiotów administracji publicznej wynikają z art. 2 ust. 2 lit. f dyrektywy; ich dokładny zakres, w tym dla poziomu lokalnego i placówek edukacyjnych, określa prawo krajowe (art. 2 ust. 5).",
    "klasyfikacja.29": "Zadeklarowano, że status podmiotu wynika wyłącznie z agregacji danych przedsiębiorstw powiązanych lub partnerskich, a system informacyjny podmiotu jest niezależny. Dyrektywa dopuszcza takie wyłączenie (motyw 16), ale rozstrzyga o nim prawo krajowe — moduł przyjmuje wyłączenie, które należy zweryfikować z prawem państwa członkowskiego i udokumentować.",
    "klasyfikacja.4": "Nadzór wyłącznie ex post — w razie dowodów, przesłanek lub informacji o naruszeniu (art. 33 dyrektywy (UE) 2022/2555).",
    "klasyfikacja.5": "Poza zakresem dyrektywy",
    "klasyfikacja.6": "Brak obowiązków wynikających z dyrektywy (UE) 2022/2555 dla wskazanej roli.",
    "klasyfikacja.7": "art. 3 ust. 1 lit. a dyrektywy (UE) 2022/2555 (podmiot z załącznika I przekraczający pułapy dla średniego przedsiębiorstwa)",
    "klasyfikacja.8": "art. 3 ust. 2 dyrektywy (UE) 2022/2555 (podmiot z załącznika I spełniający kryteria średniego przedsiębiorstwa)",
    "klasyfikacja.9": "Mikro- i mali przedsiębiorcy nie są objęci dyrektywą z tytułu tej roli (art. 2 ust. 1 a contrario).",
    "kreator.10": "Przychód za poprzedni rok wpisz ręcznie.",
    "kreator.35": "<span class=\"text-secondary\">Odczyt sprawozdań finansowych nie jest dostępny dla tego państwa.</span>",
    "kreator.37": "Odczyt sprawozdań finansowych nie jest dostępny dla tego państwa — wpisz przychód ręcznie.",
    "kreator.56": "Tak — rozporządzenie unijne stosuje się bezpośrednio od 7 listopada 2024 r. we wszystkich państwach członkowskich i nie ma okresu przejściowego. Podstawą jest",
    "kreator.57": ", który upoważnił Komisję do określenia wymogów technicznych i metodologicznych dla dostawców z art. 3 ust. 1 rozporządzenia. Termin transpozycji dyrektywy upłynął",
    "kreator.58": ", a od kiedy organ krajowy może nakładać kary, określa prawo krajowe. Wymogi techniczne z załącznika (sekcje 6 i 9–13) są wiążące w obecnym brzmieniu — nie czekają na doprecyzowanie. Odstąpić można tylko od wymogów opatrzonych formułą „w stosownych przypadkach”, i wyłącznie dokumentując uzasadnienie.",
    "kreator.9": "Sprawozdania finansowe →",
    "kreator.przepisReg2690": "art. 21 ust. 5 dyrektywy (UE) 2022/2555",
    "kreator.terminReg2690": "17 października 2024 r.",
    "punktacja.10": "Podmioty publiczne",
    "punktacja.4": "Dyrektywa NIS 2 — art. 21",
    "punktacja.5": "Dyrektywa NIS 2 — obowiązki formalne",
    "punktacja.8": "Łączność elektroniczna",
    "punktacja.9": "Dyrektywa NIS 2 — podmioty publiczne",
    "punktacja.skrotKsc": "NIS 2",
    "punktacja.skrotPke": "telekom",
    "ue.cyt.akapit": "akapit {p0}",
    "ue.cyt.art": "art. {p0}",
    "ue.cyt.drugi": "drugi",
    "ue.cyt.dyr": "{p0} dyrektywy (UE) 2022/2555",
    "ue.cyt.i": "i",
    "ue.cyt.laczenie": " ",
    "ue.cyt.lit": "lit. {p0}",
    "ue.cyt.pkt": "pkt {p0}",
    "ue.cyt.rozdzielacz": "; ",
    "ue.cyt.rozp": "{p0} rozporządzenia (UE) 2024/2690",
    "ue.cyt.ust": "ust. {p0}",
    "ue.katalog.1": "Polityka analizy ryzyka i bezpieczeństwa systemów informatycznych",
    "ue.katalog.10": "Obsługa incydentu",
    "ue.katalog.11": "Obsługa incydentu obejmuje działania i procedury mające na celu zapobieganie incydentom, wykrywanie ich, analizowanie, ograniczanie ich zasięgu lub reagowanie na nie oraz przywracanie normalnego działania (art. 6 pkt 8).",
    "ue.katalog.12": "Czy istnieje udokumentowana procedura obsługi incydentu obejmująca wykrywanie, analizę, ograniczanie zasięgu, reagowanie i przywracanie normalnego działania?",
    "ue.katalog.13": "ISO/IEC 27001 A.5.24–A.5.26",
    "ue.katalog.14": "Czy procedura pozwala dotrzymać terminów zgłoszenia poważnego incydentu: wczesne ostrzeżenie w 24 godziny, zgłoszenie w 72 godziny, sprawozdanie końcowe w miesiąc?",
    "ue.katalog.15": "ISO/IEC 27001 A.5.24",
    "ue.katalog.16": "Czy podmiot ma kryteria uznania incydentu za poważny, zgodne z art. 23 ust. 3: dotkliwe zakłócenia operacyjne lub straty finansowe albo znaczne szkody dla innych osób?",
    "ue.katalog.17": "ISO/IEC 27001 A.5.25",
    "ue.katalog.18": "Czy incydenty są rejestrowane, a wnioski z ich obsługi wykorzystywane do doskonalenia środków?",
    "ue.katalog.19": "ISO/IEC 27001 A.5.27",
    "ue.katalog.2": "Środki bazują na podejściu uwzględniającym wszystkie zagrożenia (art. 21 ust. 2). Ich proporcjonalność ocenia się z uwzględnieniem stopnia narażenia, wielkości podmiotu, prawdopodobieństwa incydentów i ich dotkliwości (art. 21 ust. 1 akapit drugi).",
    "ue.katalog.20": "Ciągłość działania i zarządzanie kryzysowe",
    "ue.katalog.21": "Ciągłość działania, w tym zarządzanie kopiami zapasowymi i przywracanie normalnego działania po wystąpieniu sytuacji nadzwyczajnej, oraz zarządzanie kryzysowe.",
    "ue.katalog.22": "Czy istnieje plan ciągłości działania obejmujący przywracanie normalnego działania po sytuacji nadzwyczajnej?",
    "ue.katalog.23": "ISO/IEC 27001 A.5.29–A.5.30",
    "ue.katalog.24": "Czy kopie zapasowe są wykonywane, chronione i testowane pod kątem możliwości odtworzenia?",
    "ue.katalog.25": "ISO/IEC 27001 A.8.13",
    "ue.katalog.26": "Czy podmiot ma procedury zarządzania kryzysowego z określonymi rolami i kanałami komunikacji?",
    "ue.katalog.27": "ISO/IEC 27001 A.5.29",
    "ue.katalog.28": "Czy plany ciągłości i odtwarzania są testowane cyklicznie, a wyniki dokumentowane?",
    "ue.katalog.29": "ISO/IEC 27001 A.5.30",
    "ue.katalog.3": "Czy podmiot ma udokumentowaną politykę analizy ryzyka i bezpieczeństwa systemów informatycznych, zatwierdzoną przez organ zarządzający?",
    "ue.katalog.30": "Bezpieczeństwo łańcucha dostaw",
    "ue.katalog.31": "Bezpieczeństwo łańcucha dostaw, w tym aspekty dotyczące stosunków między podmiotem a jego bezpośrednimi dostawcami lub usługodawcami. Podmiot uwzględnia podatności właściwe dla każdego dostawcy oraz ogólną jakość jego produktów i praktyk w zakresie cyberbezpieczeństwa (art. 21 ust. 3).",
    "ue.katalog.32": "Czy podmiot prowadzi wykaz bezpośrednich dostawców i usługodawców wraz z oceną ich znaczenia dla bezpieczeństwa sieci i systemów?",
    "ue.katalog.33": "ISO/IEC 27001 A.5.19",
    "ue.katalog.34": "Czy przy doborze środków wobec dostawców uwzględniane są podatności właściwe dla każdego z nich oraz jakość ich praktyk w zakresie cyberbezpieczeństwa i bezpiecznego rozwoju?",
    "ue.katalog.35": "ISO/IEC 27001 A.5.19, A.5.21",
    "ue.katalog.36": "Czy umowy z dostawcami zawierają wymagania bezpieczeństwa oraz obowiązek informowania o incydentach i podatnościach?",
    "ue.katalog.37": "ISO/IEC 27001 A.5.20",
    "ue.katalog.38": "Czy podmiot uwzględnia wyniki skoordynowanych ocen ryzyka bezpieczeństwa krytycznych łańcuchów dostaw, o których mowa w art. 22?",
    "ue.katalog.39": "ISO/IEC 27001 A.5.21",
    "ue.katalog.4": "ISO/IEC 27001 pkt 5.2, 6.1.2",
    "ue.katalog.40": "Bezpieczeństwo w nabywaniu, rozwoju i utrzymaniu systemów",
    "ue.katalog.41": "Bezpieczeństwo w procesie nabywania, rozwoju i utrzymania sieci i systemów informatycznych, w tym postępowanie w przypadku podatności i ich ujawnianie.",
    "ue.katalog.42": "Czy wymagania bezpieczeństwa są określane przed nabyciem lub rozpoczęciem rozwoju systemu i weryfikowane przed wdrożeniem?",
    "ue.katalog.43": "ISO/IEC 27001 A.8.25–A.8.29",
    "ue.katalog.44": "Czy istnieje proces postępowania z podatnościami: identyfikacja, ocena, usuwanie w określonym czasie?",
    "ue.katalog.45": "ISO/IEC 27001 A.8.8",
    "ue.katalog.46": "Czy podmiot ma procedurę ujawniania podatności, w tym kanał przyjmowania zgłoszeń od osób trzecich?",
    "ue.katalog.47": "Czy zmiany w systemach przechodzą przez kontrolowany proces zarządzania zmianą z oceną wpływu na bezpieczeństwo?",
    "ue.katalog.48": "ISO/IEC 27001 A.8.32",
    "ue.katalog.49": "Ocena skuteczności środków",
    "ue.katalog.5": "Czy analiza ryzyka obejmuje wszystkie zagrożenia dla sieci i systemów informatycznych oraz ich środowiska fizycznego, a nie tylko zagrożenia cybernetyczne?",
    "ue.katalog.50": "Polityki i procedury służące ocenie skuteczności środków zarządzania ryzykiem w cyberbezpieczeństwie.",
    "ue.katalog.51": "Czy istnieje udokumentowana polityka oceny skuteczności środków, określająca zakres, częstotliwość i metody?",
    "ue.katalog.52": "ISO/IEC 27001 pkt 9.1",
    "ue.katalog.53": "Czy oceny skuteczności są przeprowadzane cyklicznie, a ich wyniki przekazywane organowi zarządzającemu?",
    "ue.katalog.54": "ISO/IEC 27001 pkt 9.2–9.3",
    "ue.katalog.55": "Czy wykryte słabości prowadzą do udokumentowanych działań korygujących z właścicielem i terminem?",
    "ue.katalog.56": "ISO/IEC 27001 pkt 10.1",
    "ue.katalog.57": "Cyberhigiena i szkolenia",
    "ue.katalog.58": "Podstawowe praktyki cyberhigieny i szkolenia w zakresie cyberbezpieczeństwa. Członkowie organu zarządzającego odbywają regularne szkolenia (art. 20 ust. 2).",
    "ue.katalog.59": "Czy podmiot stosuje podstawowe praktyki cyberhigieny: aktualizacje, zarządzanie hasłami, ograniczanie uprawnień, ochronę przed złośliwym oprogramowaniem?",
    "ue.katalog.6": "ISO/IEC 27001 pkt 6.1.2",
    "ue.katalog.60": "ISO/IEC 27001 A.8.7, A.8.8",
    "ue.katalog.61": "Czy pracownicy przechodzą szkolenia z cyberbezpieczeństwa dostosowane do ich roli, a udział jest dokumentowany?",
    "ue.katalog.62": "ISO/IEC 27001 A.6.3",
    "ue.katalog.63": "Czy członkowie organu zarządzającego odbywają regularne szkolenia pozwalające rozpoznać ryzyko i ocenić praktyki zarządzania ryzykiem?",
    "ue.katalog.64": "ISO/IEC 27001 pkt 7.2",
    "ue.katalog.65": "Kryptografia i szyfrowanie",
    "ue.katalog.66": "Polityki i procedury stosowania kryptografii i, w stosownych przypadkach, szyfrowania.",
    "ue.katalog.67": "Czy istnieje polityka stosowania kryptografii określająca, jakie dane i kanały podlegają szyfrowaniu oraz jakimi algorytmami?",
    "ue.katalog.68": "ISO/IEC 27001 A.8.24",
    "ue.katalog.69": "Czy klucze kryptograficzne są zarządzane w pełnym cyklu: generowanie, dystrybucja, przechowywanie, rotacja, wycofanie?",
    "ue.katalog.7": "Czy dobór środków uwzględnia najnowszy stan wiedzy, odpowiednie normy europejskie i międzynarodowe oraz koszty wdrożenia?",
    "ue.katalog.70": "Zasoby ludzkie, kontrola dostępu i zarządzanie aktywami",
    "ue.katalog.71": "Bezpieczeństwo zasobów ludzkich, polityka kontroli dostępu i zarządzanie aktywami.",
    "ue.katalog.72": "Czy podmiot prowadzi aktualny wykaz aktywów z przypisanymi właścicielami i klasyfikacją?",
    "ue.katalog.73": "ISO/IEC 27001 A.5.9, A.5.12",
    "ue.katalog.74": "Czy istnieje polityka kontroli dostępu oparta na zasadzie najmniejszych uprawnień, z cyklicznym przeglądem uprawnień?",
    "ue.katalog.75": "ISO/IEC 27001 A.5.15, A.5.18",
    "ue.katalog.76": "Czy przy zatrudnianiu, zmianie stanowiska i odejściu pracownika stosowane są procedury bezpieczeństwa, w tym odbieranie uprawnień i zwrot aktywów?",
    "ue.katalog.77": "ISO/IEC 27001 A.6.1–A.6.5",
    "ue.katalog.78": "Czy dostęp uprzywilejowany jest ograniczony, rejestrowany i przeglądany?",
    "ue.katalog.79": "ISO/IEC 27001 A.8.2",
    "ue.katalog.8": "ISO/IEC 27001 pkt 6.1.3",
    "ue.katalog.80": "Uwierzytelnianie wieloskładnikowe i bezpieczna komunikacja",
    "ue.katalog.81": "W stosownych przypadkach — uwierzytelnianie wieloskładnikowe lub ciągłe, zabezpieczone połączenia głosowe, tekstowe i wideo oraz zabezpieczone systemy łączności wewnątrz podmiotu w sytuacjach nadzwyczajnych.",
    "ue.katalog.82": "Czy uwierzytelnianie wieloskładnikowe lub ciągłe jest stosowane tam, gdzie analiza ryzyka to uzasadnia, w szczególności dla dostępu zdalnego i kont uprzywilejowanych?",
    "ue.katalog.83": "ISO/IEC 27001 A.8.5",
    "ue.katalog.84": "Czy połączenia głosowe, tekstowe i wideo używane do spraw służbowych są zabezpieczone?",
    "ue.katalog.85": "ISO/IEC 27001 A.8.20",
    "ue.katalog.86": "Czy podmiot ma zabezpieczony system łączności wewnętrznej na wypadek sytuacji nadzwyczajnej, niezależny od podstawowej infrastruktury?",
    "ue.katalog.9": "Czy poziom bezpieczeństwa jest udokumentowany jako odpowiedni do istniejącego ryzyka, z uzasadnieniem uwzględniającym wielkość podmiotu i skutki społeczne i gospodarcze incydentów?",
    "ue.kierownictwo.1": "Organ zarządzający podmiotu kluczowego lub ważnego — w spółce kapitałowej zarząd. Dyrektywa nie definiuje tego pojęcia; jego zakres w danym państwie wynika z prawa krajowego.",
    "ue.kierownictwo.10": "Ustalić status podmiotu i dopilnować rejestracji",
    "ue.kierownictwo.11": "Ustalenie, czy podmiot jest kluczowy czy ważny, i przedłożenie danych rejestracyjnych właściwemu organowi. Tryb i termin określa prawo krajowe.",
    "ue.kierownictwo.12": "Wdrożyć analizę ryzyka i politykę bezpieczeństwa",
    "ue.kierownictwo.13": "Środki bazujące na podejściu uwzględniającym wszystkie zagrożenia, proporcjonalne do narażenia, wielkości podmiotu i dotkliwości incydentów.",
    "ue.kierownictwo.14": "Uruchomić obsługę i zgłaszanie incydentów",
    "ue.kierownictwo.15": "Procedura obsługi incydentu oraz zdolność dotrzymania terminów 24 godzin, 72 godzin i miesiąca.",
    "ue.kierownictwo.16": "24 h / 72 h / miesiąc od wykrycia",
    "ue.kierownictwo.17": "Zapewnić ciągłość działania",
    "ue.kierownictwo.18": "Plan ciągłości, kopie zapasowe, przywracanie po sytuacji nadzwyczajnej, zarządzanie kryzysowe.",
    "ue.kierownictwo.19": "Uporządkować łańcuch dostaw",
    "ue.kierownictwo.2": "Odpowiedzialność organu zarządzającego nie narusza przepisów krajowych o odpowiedzialności instytucji publicznych i urzędników (art. 20 ust. 1 akapit drugi).",
    "ue.kierownictwo.20": "Wykaz dostawców, ocena ich podatności i praktyk, wymagania bezpieczeństwa w umowach.",
    "ue.kierownictwo.21": "Wdrożyć kontrolę dostępu i zarządzanie aktywami",
    "ue.kierownictwo.22": "Wykaz aktywów, zasada najmniejszych uprawnień, przeglądy uprawnień, uwierzytelnianie wieloskładnikowe tam, gdzie ryzyko to uzasadnia.",
    "ue.kierownictwo.23": "Mierzyć skuteczność środków",
    "ue.kierownictwo.24": "Polityka i procedury oceny skuteczności, cykliczne przeglądy, działania korygujące.",
    "ue.kierownictwo.25": "Zatwierdzać",
    "ue.kierownictwo.26": "środki zarządzania ryzykiem w cyberbezpieczeństwie (art. 20 ust. 1)",
    "ue.kierownictwo.27": "politykę analizy ryzyka i bezpieczeństwa systemów",
    "ue.kierownictwo.28": "budżet i role we wdrożeniu",
    "ue.kierownictwo.29": "Nadzorować",
    "ue.kierownictwo.3": "Czy powierzenie obowiązków innej osobie wyłącza odpowiedzialność — rozstrzyga prawo krajowe. W Polsce nie wyłącza (art. 8c ust. 3 ustawy o KSC).",
    "ue.kierownictwo.30": "wdrażanie zatwierdzonych środków (art. 20 ust. 1)",
    "ue.kierownictwo.31": "wyniki oceny skuteczności (art. 21 ust. 2 lit. f)",
    "ue.kierownictwo.32": "dotrzymywanie terminów zgłoszeń incydentów (art. 23)",
    "ue.kierownictwo.33": "Dokumentować",
    "ue.kierownictwo.34": "decyzje zatwierdzające i przeglądy",
    "ue.kierownictwo.35": "udział w szkoleniach (art. 20 ust. 2)",
    "ue.kierownictwo.36": "Członek organu zarządzającego",
    "ue.kierownictwo.37": "zatwierdzanie środków, nadzór, decyzje, budżet",
    "ue.kierownictwo.38": "Kierownik projektu",
    "ue.kierownictwo.39": "koordynacja wdrożenia, harmonogram, status i dowody",
    "ue.kierownictwo.4": "Zatwierdzić środki zarządzania ryzykiem w cyberbezpieczeństwie",
    "ue.kierownictwo.40": "IT / cyberbezpieczeństwo",
    "ue.kierownictwo.41": "analiza ryzyka, środki techniczne, obsługa incydentów",
    "ue.kierownictwo.42": "Dział prawny / compliance",
    "ue.kierownictwo.5": "Organ zarządzający zatwierdza środki przyjęte w celu zapewnienia zgodności z art. 21. To decyzja organu, nie działu IT — bez niej środki nie mają umocowania.",
    "ue.kierownictwo.6": "Nadzorować wdrażanie środków",
    "ue.kierownictwo.7": "Nadzór nad wdrażaniem jest obowiązkiem organu zarządzającego. Wykonanie można powierzyć, nadzoru nie.",
    "ue.kierownictwo.8": "Odbywać regularne szkolenia",
    "ue.kierownictwo.9": "Członkowie organu zarządzającego odbywają regularne szkolenia, żeby zdobyć wiedzę pozwalającą rozpoznać ryzyko i ocenić praktyki zarządzania nim oraz ich wpływ na usługi podmiotu.",
    "ue.kierownictwo.daneRejestracyjne": "dane rejestracyjne i ich aktualizacje (art. 3 ust. 4–5)",
    "ue.meta.1": "Przeważa wariant procentowy: {p0} % obrotu jest wyższe niż {p1} mln EUR.",
    "ue.meta.10": "Dyrektywa nie nakłada obowiązków bezpośrednio na przedsiębiorcę — robi to ustawa krajowa, którą państwo członkowskie miało uchwalić do 17 października 2024 r. Ten moduł pokazuje wymogi w brzmieniu dyrektywy, bo moduł prawa krajowego dla wybranego państwa nie jest jeszcze gotowy albo państwo nie dokonało transpozycji.",
    "ue.meta.11": "Obowiązki z dyrektywy",
    "ue.meta.12": "Wykaz podmiotów — do 17 kwietnia 2025 r.",
    "ue.meta.13": "Państwa członkowskie miały ustanowić wykaz podmiotów kluczowych i ważnych do 17 kwietnia 2025 r. i wymagać od podmiotów przedłożenia danych rejestracyjnych.",
    "ue.meta.14": "Rozporządzenie (UE) 2024/2690",
    "ue.meta.15": "Stosowane bezpośrednio od 7 listopada 2024 r.",
    "ue.meta.16": "Rozporządzenie wykonawcze stosuje się bezpośrednio we wszystkich państwach członkowskich, niezależnie od stanu transpozycji dyrektywy. Dotyczy podmiotów wymienionych w jego art. 1: DNS, TLD, chmury, centrów danych, sieci dostarczania treści, usług zarządzanych i usług zaufania.",
    "ue.meta.17": "art. 16 rozporządzenia (UE) 2024/2690",
    "ue.meta.18": "Co najmniej 10 000 000 EUR albo co najmniej 2 % łącznego rocznego światowego obrotu przedsiębiorstwa w poprzednim roku obrotowym — zastosowanie ma kwota wyższa. To pułap minimalny: prawo krajowe może go podnieść.",
    "ue.meta.19": "Co najmniej 7 000 000 EUR albo 1,4 % łącznego rocznego światowego obrotu — zastosowanie ma kwota wyższa. Pułap minimalny.",
    "ue.meta.2": "Przeważa kwota stała: {p0} mln EUR jest wyższe niż {p1} % obrotu.",
    "ue.meta.20": "Dyrektywa nie przewiduje odrębnej kary za naruszenie kwalifikowane — to konstrukcja prawa krajowego niektórych państw.",
    "ue.meta.21": "Państwa członkowskie mogą przewidzieć okresowe kary pieniężne w celu przymuszenia do zaprzestania naruszenia. Wysokość ustala prawo krajowe.",
    "ue.meta.22": "Organ zarządzający zatwierdza środki zarządzania ryzykiem, nadzoruje ich wdrażanie i może być pociągnięty do odpowiedzialności za naruszenie art. 21. Zasady i wysokość tej odpowiedzialności określa prawo krajowe.",
    "ue.meta.23": "Organ zarządzający zatwierdza środki zarządzania ryzykiem w cyberbezpieczeństwie (art. 20 ust. 1).",
    "ue.meta.24": "Organ zarządzający nadzoruje wdrażanie tych środków (art. 20 ust. 1).",
    "ue.meta.25": "Członkowie organu zarządzającego odbywają regularne szkolenia (art. 20 ust. 2).",
    "ue.meta.26": "Wobec podmiotu kluczowego organ może wystąpić o czasowy zakaz pełnienia funkcji zarządczych (art. 32 ust. 5 lit. b).",
    "ue.meta.27": "Pułap minimalny wyznacza dyrektywa",
    "ue.meta.28": "Porównuje się dwie wartości: kwotę stałą w euro oraz procent łącznego rocznego światowego obrotu przedsiębiorstwa w poprzednim roku obrotowym. Wyższa z nich to górna granica, jaką państwo członkowskie musi co najmniej przewidzieć. Prawo krajowe może ją podnieść.",
    "ue.meta.29": "Kwotę w granicach pułapu ustala organ krajowy",
    "ue.meta.3": "Pułap z dyrektywy przewyższa roczny obrót podmiotu {p0}-krotnie. Art. 34 ust. 1 wymaga, by kara była proporcjonalna do okoliczności indywidualnego przypadku — to górna granica, nie kara oczekiwana.",
    "ue.meta.30": "Kara ma być skuteczna, proporcjonalna i odstraszająca stosownie do okoliczności indywidualnego przypadku. Organ uwzględnia co najmniej kryteria z art. 32 ust. 7: wagę i czas trwania naruszenia, wcześniejsze naruszenia, szkody, umyślność, środki zaradcze i współpracę.",
    "ue.meta.31": "Pułap może wielokrotnie przewyższać roczny obrót — to górna granica, a nie kwota oczekiwana. Krajowe minima, kary okresowe i tryb wymiaru określa ustawa państwa członkowskiego.",
    "ue.meta.32": "Podejmując decyzję o nałożeniu administracyjnej kary pieniężnej i o jej wysokości, w każdym indywidualnym przypadku należycie uwzględnia się co najmniej elementy wymienione w art. 32 ust. 7.",
    "ue.meta.33": "waga naruszenia i znaczenie naruszonych przepisów — za poważne uznaje się w każdym przypadku: powtarzające się naruszenia, niezgłoszenie lub nieusunięcie poważnych incydentów, nieusunięcie uchybień wbrew wiążącym nakazom, utrudnianie audytów lub monitorowania, dostarczanie nieprawdziwych lub rażąco niedokładnych informacji",
    "ue.meta.34": "istotne wcześniejsze naruszenia ze strony podmiotu",
    "ue.meta.35": "spowodowane szkody majątkowe i niemajątkowe, w tym straty finansowe, wpływ na inne usługi i liczba dotkniętych użytkowników",
    "ue.meta.36": "umyślny lub nieumyślny charakter czynu",
    "ue.meta.37": "środki zastosowane, aby zapobiec szkodom lub je ograniczyć",
    "ue.meta.38": "stosowanie zatwierdzonych kodeksów postępowania lub mechanizmów certyfikacji",
    "ue.meta.39": "stopień współpracy z właściwymi organami",
    "ue.meta.4": "Dyrektywa Parlamentu Europejskiego i Rady (UE) 2022/2555 (NIS 2)",
    "ue.meta.40": "Dyrektywa nie przewiduje wprost odstąpienia od kary — czy i kiedy jest ono możliwe, rozstrzyga prawo krajowe.",
    "ue.meta.41": "Od tej daty państwa członkowskie mają stosować przepisy krajowe wdrażające dyrektywę. Konkretna data, od której organ może nałożyć karę, wynika z prawa krajowego.",
    "ue.meta.42": "Wejście w życie dyrektywy NIS 2",
    "ue.meta.43": "Dwudziestego dnia po publikacji w Dzienniku Urzędowym.",
    "ue.meta.44": "Termin transpozycji dyrektywy",
    "ue.meta.45": "Do tej daty państwa członkowskie miały przyjąć i opublikować przepisy krajowe.",
    "ue.meta.46": "Stosowanie przepisów krajowych i uchylenie NIS 1",
    "ue.meta.47": "Od tej daty państwa stosują przepisy wdrażające; dyrektywa (UE) 2016/1148 traci moc.",
    "ue.meta.48": "Stosowanie rozporządzenia (UE) 2024/2690",
    "ue.meta.49": "Rozporządzenie wykonawcze stosuje się bezpośrednio od dwudziestego dnia po publikacji.",
    "ue.meta.5": "Dz.U. UE L 333 z 27.12.2022",
    "ue.meta.50": "Wykaz podmiotów kluczowych i ważnych",
    "ue.meta.51": "Do tej daty państwa członkowskie ustanawiają wykaz; podmioty przedkładają organom dane rejestracyjne.",
    "ue.meta.52": "Pierwszy przegląd dyrektywy przez Komisję",
    "ue.meta.53": "Komisja dokonuje przeglądu funkcjonowania dyrektywy i składa sprawozdanie.",
    "ue.meta.54": "Wczesne ostrzeżenie o poważnym incydencie",
    "ue.meta.55": "24 godziny od powzięcia wiedzy",
    "ue.meta.56": "Zgłoszenie poważnego incydentu",
    "ue.meta.57": "72 godziny od powzięcia wiedzy",
    "ue.meta.58": "Sprawozdanie końcowe",
    "ue.meta.59": "miesiąc od zgłoszenia incydentu",
    "ue.meta.6": "Rozporządzenie wykonawcze Komisji (UE) 2024/2690",
    "ue.meta.60": "Zgłoszenie incydentu przez dostawcę usług zaufania",
    "ue.meta.61": "art. 21 ust. 5 dyrektywy (UE) 2022/2555; art. 1 i 2 rozporządzenia (UE) 2024/2690",
    "ue.meta.62": "Bez danych o obrocie pułapem jest kwota stała z dyrektywy.",
    "ue.meta.63": "Pułapy z art. 34 ust. 4 i 5 są minimalne („co najmniej\") — prawo krajowe może przewidzieć wyższe. Kwoty w euro, bez przeliczania na walutę krajową.",
    "ue.meta.64": "Właściwy organ państwa członkowskiego",
    "ue.meta.65": "Organ zarządzający może być pociągnięty do odpowiedzialności za naruszenie art. 21. Wysokość i tryb określa prawo krajowe — ten moduł ich nie zna.",
    "ue.meta.66": "Wysokość odpowiedzialności osobistej kierownictwa wynika z ustawy krajowej. Dla Polski jest to do 300 % wynagrodzenia (art. 73a ust. 4 ustawy o KSC); inne państwa rozstrzygają to inaczej.",
    "ue.meta.7": "Dz.U. UE L, 2024/2690",
    "ue.meta.8": "Dyrektywa (UE) 2022/2555",
    "ue.meta.9": "Termin transpozycji minął 17 października 2024 r.",
    "ue.moduly.1": "około {p0} min",
    "ue.moduly.10": "Dziesięć obszarów z art. 21 ust. 2 lit. a–j: od polityki ryzyka po uwierzytelnianie wieloskładnikowe. Naruszenie zagrożone karą z art. 34. Ocena w skali dojrzałości.",
    "ue.moduly.11": "Rozporządzenie 2024/2690 — zarządzanie i procesy",
    "ue.moduly.12": "Sekcje 1–5 i 7–8 załącznika: polityki, zarządzanie ryzykiem, obsługa incydentów, ciągłość działania, łańcuch dostaw, ocena skuteczności, cyberhigiena. Stosowane bezpośrednio od 7 listopada 2024 r.",
    "ue.moduly.13": "Rozporządzenie 2024/2690 — wymogi techniczne",
    "ue.moduly.14": "Sekcje 6 i 9–13 załącznika: nabywanie i rozwój systemów, kryptografia, bezpieczeństwo zasobów ludzkich, kontrola dostępu, zarządzanie aktywami, bezpieczeństwo fizyczne i środowiskowe.",
    "ue.moduly.2": "około {p0} godz. {p1} min",
    "ue.moduly.3": "około {p0} godz.",
    "ue.moduly.4": "poniżej minuty",
    "ue.moduly.5": "Szybka ocena ryzyka",
    "ue.moduly.6": "Pytania nadrzędne z wszystkich obszarów dyrektywy. Każde rozstrzyga o całej grupie zagadnień. Pozwala oszacować skalę zaległości bez przechodzenia pełnego kwestionariusza.",
    "ue.moduly.7": "Obowiązki z dyrektywy",
    "ue.moduly.8": "Dane rejestracyjne, zgłaszanie incydentów w 24 i 72 godziny, obowiązki organu zarządzającego, gotowość na nadzór. Sprawdzalne z dokumentów, bez analizy technicznej.",
    "ue.moduly.9": "Środki zarządzania ryzykiem — art. 21 ust. 2",
    "ue.obowiazki.1": "Dane rejestracyjne dla wykazu podmiotów",
    "ue.obowiazki.10": "Zgłaszanie poważnych incydentów",
    "ue.obowiazki.11": "Podmiot zgłasza poważne incydenty do CSIRT lub właściwego organu w trzech krokach: wczesne ostrzeżenie, zgłoszenie, sprawozdanie końcowe. Terminy biegną od powzięcia wiedzy o incydencie.",
    "ue.obowiazki.12": "Czy podmiot jest w stanie przekazać wczesne ostrzeżenie w ciągu 24 godzin od powzięcia wiedzy o poważnym incydencie, ze wskazaniem, czy incydent wywołano działaniem bezprawnym i czy może mieć wpływ transgraniczny?",
    "ue.obowiazki.13": "24 godziny od powzięcia wiedzy",
    "ue.obowiazki.14": "Czy podmiot jest w stanie przekazać zgłoszenie incydentu w ciągu 72 godzin, z wstępną oceną dotkliwości, skutków i wskaźnikami integralności systemu?",
    "ue.obowiazki.15": "72 godziny od powzięcia wiedzy",
    "ue.obowiazki.16": "Czy podmiot przekazuje sprawozdanie końcowe nie później niż miesiąc po zgłoszeniu, z opisem incydentu, rodzajem zagrożenia, środkami zaradczymi i wpływem transgranicznym?",
    "ue.obowiazki.17": "miesiąc od zgłoszenia",
    "ue.obowiazki.18": "Czy podmiot powiadamia odbiorców swoich usług o poważnych incydentach, które mogą niekorzystnie wpłynąć na świadczenie tych usług?",
    "ue.obowiazki.19": "Czy podmiot powiadamia odbiorców usług o poważnym cyberzagrożeniu i środkach zaradczych, które odbiorcy mogą zastosować?",
    "ue.obowiazki.2": "Państwa członkowskie ustanawiają wykaz podmiotów kluczowych i ważnych i wymagają od podmiotów przedłożenia danych rejestracyjnych. Tryb, termin i portal określa prawo krajowe.",
    "ue.obowiazki.20": "Jeżeli podmiot jest dostawcą usług zaufania — czy zgłasza poważne incydenty w ciągu 24 godzin od powzięcia wiedzy?",
    "ue.obowiazki.21": "dotyczy dostawców usług zaufania",
    "ue.obowiazki.22": "Organ zarządzający",
    "ue.obowiazki.23": "Organ zarządzający zatwierdza środki zarządzania ryzykiem, nadzoruje ich wdrażanie i może być pociągnięty do odpowiedzialności. Członkowie organu odbywają regularne szkolenia.",
    "ue.obowiazki.24": "Czy organ zarządzający formalnie zatwierdził środki zarządzania ryzykiem w cyberbezpieczeństwie przyjęte w celu zapewnienia zgodności z art. 21?",
    "ue.obowiazki.25": "Czy organ zarządzający nadzoruje wdrażanie tych środków w sposób udokumentowany — na przykład przez cykliczne sprawozdania i przeglądy?",
    "ue.obowiazki.26": "Czy członkowie organu zarządzającego odbywają regularne szkolenia pozwalające rozpoznać ryzyko i ocenić praktyki zarządzania ryzykiem, a udział jest udokumentowany?",
    "ue.obowiazki.27": "Gotowość na czynności nadzorcze",
    "ue.obowiazki.28": "Podmiot kluczowy podlega nadzorowi prewencyjnemu i następczemu, podmiot ważny — wyłącznie następczemu. Organ może żądać informacji, dowodów wdrożenia polityk i wyników audytów.",
    "ue.obowiazki.29": "Czy podmiot jest w stanie na żądanie organu przedstawić dowody wdrożenia polityk cyberbezpieczeństwa, w tym wyniki audytów bezpieczeństwa?",
    "ue.obowiazki.3": "Czy podmiot ustalił, czy jest podmiotem kluczowym czy ważnym, na podstawie sektora z załącznika I lub II i wielkości przedsiębiorstwa?",
    "ue.obowiazki.30": "Czy podmiot jest w stanie na żądanie organu udostępnić dane, dokumenty i informacje niezbędne do wykonywania zadań nadzorczych?",
    "ue.obowiazki.31": "Czy podmiot kluczowy jest przygotowany na audyt bezpieczeństwa przeprowadzany przez organ lub niezależny podmiot, na własny koszt?",
    "ue.obowiazki.4": "Czy podmiot przedłożył właściwemu organowi dane rejestracyjne: nazwę, adres i dane kontaktowe, sektor i podsektor, wykaz państw członkowskich, w których świadczy usługi?",
    "ue.obowiazki.5": "Dane kontaktowe obejmują adresy poczty elektronicznej, zakresy adresów IP i numery telefonów. Krajowy termin i portal rejestracji określa prawo państwa członkowskiego.",
    "ue.obowiazki.6": "Czy istnieje proces aktualizacji danych rejestracyjnych bez zbędnej zwłoki po ich zmianie?",
    "ue.obowiazki.7": "Dyrektywa wymaga aktualizacji bez zbędnej zwłoki; konkretny termin — na przykład 14 dni w Polsce — wynika z prawa krajowego.",
    "ue.obowiazki.8": "Jeżeli podmiot jest dostawcą DNS, rejestrem TLD, dostawcą chmury, centrum danych, CDN, usług zarządzanych, platformy handlowej, wyszukiwarki albo sieci społecznościowej — czy przedłożył dodatkowe dane z art. 27, w tym adres głównego zakładu w Unii?",
    "ue.obowiazki.9": "dotyczy podmiotów z art. 26 ust. 1",
    "ue.role.1": "Właściwy organ państwa członkowskiego",
    "ue.role.10": "Usługi centrum danych: kolokacja, hosting infrastruktury i powiązane usługi.",
    "ue.role.11": "Ośrodki przetwarzania danych",
    "ue.role.12": "Podmiot kluczowy powyżej progu średniego przedsiębiorstwa (art. 3 ust. 1 lit. a), ważny przy średnim (art. 3 ust. 2). Poniżej średniego — poza zakresem, chyba że państwo członkowskie wskaże podmiot na podstawie art. 2 ust. 2 lit. b–e. Objęty rozporządzeniem 2024/2690.",
    "ue.role.13": "Dostawca punktu wymiany ruchu internetowego",
    "ue.role.14": "Infrastruktura umożliwiająca wymianę ruchu między niezależnymi sieciami.",
    "ue.role.15": "Punkty wymiany ruchu",
    "ue.role.16": "Klasyfikacja progowa (art. 3 ust. 1 lit. a i ust. 2). Rozporządzenie 2024/2690 nie obejmuje punktów wymiany ruchu — art. 1 rozporządzenia zawiera zamknięty katalog adresatów.",
    "ue.role.17": "Dostawca usług DNS",
    "ue.role.18": "Usługi rozpoznawania nazw domen, z wyłączeniem operatorów głównych serwerów nazw.",
    "ue.role.19": "System nazw domen",
    "ue.role.2": "organ właściwy",
    "ue.role.20": "Podmiot kluczowy niezależnie od wielkości (art. 3 ust. 1 lit. b). Objęty rozporządzeniem 2024/2690.",
    "ue.role.21": "Rejestr nazw domen najwyższego poziomu",
    "ue.role.22": "Prowadzenie rejestru domeny najwyższego poziomu.",
    "ue.role.23": "Podmiot kluczowy niezależnie od wielkości (art. 3 ust. 1 lit. b). Dodatkowo obowiązki dotyczące danych rejestracyjnych z art. 28. Objęty rozporządzeniem 2024/2690.",
    "ue.role.24": "Dostawca usług chmurowych",
    "ue.role.25": "Usługi przetwarzania w chmurze: infrastruktura, platforma, oprogramowanie jako usługa.",
    "ue.role.26": "Usługi chmurowe",
    "ue.role.27": "Klasyfikacja progowa (art. 3 ust. 1 lit. a i ust. 2). Objęty rozporządzeniem 2024/2690.",
    "ue.role.28": "Dostawca sieci dostarczania treści",
    "ue.role.29": "Sieć rozproszonych serwerów dostarczających treści i usługi użytkownikom końcowym.",
    "ue.role.3": "wyznaczany przez prawo krajowe; do czasu wdrożenia modułu krajowego narzędzie nie wskazuje konkretnej instytucji",
    "ue.role.30": "Sieci dostarczania treści",
    "ue.role.31": "Dostawca usług zaufania",
    "ue.role.32": "Usługi zaufania w rozumieniu rozporządzenia (UE) nr 910/2014: podpisy, pieczęcie, znaczniki czasu, certyfikaty.",
    "ue.role.33": "Usługi zaufania",
    "ue.role.34": "Objęty dyrektywą niezależnie od wielkości (art. 2 ust. 2 lit. a ppkt (ii)). Dostawca kwalifikowany jest podmiotem kluczowym niezależnie od wielkości (art. 3 ust. 1 lit. b); niekwalifikowany — kluczowym powyżej progu średniego, w pozostałych przypadkach ważnym. Objęty rozporządzeniem 2024/2690.",
    "ue.role.35": "Dostawca usług zarządzanych",
    "ue.role.36": "Zarządzanie infrastrukturą ICT klienta: instalacja, utrzymanie, wsparcie, administrowanie systemami.",
    "ue.role.37": "Zarządzanie usługami ICT (B2B)",
    "ue.role.38": "Usługi zarządzane",
    "ue.role.39": "Dostawca usług zarządzanych w zakresie bezpieczeństwa",
    "ue.role.4": "Dostawca publicznej sieci lub publicznie dostępnych usług łączności elektronicznej",
    "ue.role.40": "Usługi zarządzane w dziedzinie cyberbezpieczeństwa: monitorowanie, reagowanie na incydenty, testy, doradztwo.",
    "ue.role.41": "Usługi zarządzane w zakresie bezpieczeństwa",
    "ue.role.42": "Dyrektywa klasyfikuje progowo (art. 3 ust. 1 lit. a i ust. 2). Państwa członkowskie mogą zaostrzyć próg — Polska uznaje MSSP za podmiot kluczowy już od małego przedsiębiorcy; ten moduł stosuje wyłącznie regułę dyrektywy. Objęty rozporządzeniem 2024/2690.",
    "ue.role.5": "Dostarczanie publicznych sieci łączności elektronicznej lub świadczenie publicznie dostępnych usług łączności elektronicznej, w tym dostępu do internetu.",
    "ue.role.6": "Infrastruktura cyfrowa",
    "ue.role.7": "Łączność elektroniczna",
    "ue.role.8": "Objęty dyrektywą niezależnie od wielkości (art. 2 ust. 2 lit. a ppkt (i)). Średni przedsiębiorca lub większy jest podmiotem kluczowym (art. 3 ust. 1 lit. c), mikro- i mały — ważnym (art. 3 ust. 2). Krajowa ustawa telekomunikacyjna może nakładać dodatkowe obowiązki — ten moduł ich nie zawiera.",
    "ue.role.9": "Dostawca usług ośrodka przetwarzania danych",
    "ue.role.podstawaArt3b": "art. 3 ust. 1 lit. b dyrektywy (UE) 2022/2555",
    "ue.zaslepki.1": "Dyrektywa Parlamentu Europejskiego i Rady (UE) 2022/2555 (NIS 2)",
    "ue.zaslepki.10": "Czy część podmiotów jest wpisywana z urzędu, rozstrzyga prawo krajowe.",
    "ue.zaslepki.11": "Ustal, czy podlegasz dyrektywie",
    "ue.zaslepki.12": "Sektor z załącznika I albo II oraz wielkość przedsiębiorstwa. Tę część wykonuje profil podmiotu w tym narzędziu.",
    "ue.zaslepki.13": "Ustal właściwy organ w swoim państwie",
    "ue.zaslepki.14": "Każde państwo wyznacza organ właściwy (art. 8 ust. 1). Aktualną listę prowadzi ENISA i Komisja.",
    "ue.zaslepki.15": "Przedłóż dane rejestracyjne",
    "ue.zaslepki.16": "Nazwa, adres i dane kontaktowe, sektor i podsektor, państwa świadczenia usług (art. 3 ust. 4). Tryb według prawa krajowego.",
    "ue.zaslepki.17": "Aktualizuj dane bez zbędnej zwłoki",
    "ue.zaslepki.18": "Każda zmiana danych rejestracyjnych wymaga aktualizacji (art. 3 ust. 5).",
    "ue.zaslepki.19": "adres i aktualne dane kontaktowe: adresy poczty elektronicznej, zakresy adresów IP, numery telefonów",
    "ue.zaslepki.2": "Dz.U. UE L 333 z 27.12.2022, s. 80",
    "ue.zaslepki.20": "sektor i podsektor z załącznika I albo II",
    "ue.zaslepki.21": "wykaz państw członkowskich, w których podmiot świadczy usługi",
    "ue.zaslepki.22": "Określa prawo krajowe.",
    "ue.zaslepki.23": "Dyrektywa (UE) 2022/2555 — art. 3",
    "ue.zaslepki.24": "ENISA — organy właściwe państw członkowskich",
    "ue.zaslepki.25": "Dyrektywa (UE) 2022/2555",
    "ue.zaslepki.26": "Moduł unijny nie zawiera wytycznych krajowego organu — te pojawią się wraz z modułem prawa krajowego.",
    "ue.zaslepki.27": "Automatyczne pobieranie danych z rejestru działa wyłącznie dla państw z modułem prawa krajowego. Wypełnij profil ręcznie.",
    "ue.zaslepki.28": "Odczyt sprawozdania finansowego działa wyłącznie dla państw z modułem prawa krajowego. Wpisz przychód i zatrudnienie ręcznie.",
    "ue.zaslepki.3": "Rozporządzenie wykonawcze Komisji (UE) 2024/2690",
    "ue.zaslepki.4": "Dz.U. UE L, 2024/2690, 18.11.2024",
    "ue.zaslepki.5": "Dyrektywa NIS 2 nie zawiera odrębnej warstwy telekomunikacyjnej. Krajowe prawo łączności elektronicznej może nakładać dodatkowe obowiązki — ten moduł ich nie zna.",
    "ue.zaslepki.6": "Wykaz podmiotów kluczowych i ważnych",
    "ue.zaslepki.7": "Właściwy organ państwa członkowskiego.",
    "ue.zaslepki.8": "Dyrektywa nakazuje państwom członkowskim prowadzić wykaz podmiotów kluczowych i ważnych oraz wymagać od podmiotów przedłożenia danych rejestracyjnych. Portal, tryb i termin określa prawo krajowe — ten moduł ich nie zna, bo moduł prawa krajowego dla wybranego państwa nie jest jeszcze gotowy.",
    "ue.zaslepki.9": "Wszystkie podmioty kluczowe i ważne. Termin określa prawo krajowe.",
    "ue.zaslepki.skrotDyrektywy": "dyrektywa NIS 2",
    "ue.zaslepki.skrotReg2690": "rozp. 2024/2690",
    "xlsx.1": "{p0} – {p1} EUR",
    "xlsx.25": "Kurs walutowy",
    "xlsx.4": "RAPORT ZGODNOŚCI Z DYREKTYWĄ NIS 2 (UE) 2022/2555",
    "xlsx.58": "Działalność telekomunikacyjna: rozporządzenie (UE) 2024/2690 nie ma zastosowania. Progi określa prawo krajowe (art. 23 ust. 11 dyrektywy) — moduł wspólny ich nie zna.",
    "xlsx.68": "Narzędzie służy samoocenie. Nie jest audytem ani opinią prawną.",
    "xlsx.69": "Progi uznania incydentu za poważny dla podmiotów nieobjętych rozporządzeniem (UE) 2024/2690 określa prawo krajowe (art. 23 ust. 11 dyrektywy).",
    "xlsx.70": "Role wskazane w profilu są deklaracją. O statusie decyduje faktycznie wykonywana działalność (art. 3 dyrektywy (UE) 2022/2555).",
    "xlsx.etykietaKrs": "Numer rejestrowy",
    "xlsx.etykietaNip": "Numer identyfikacyjny",
    "xlsx.etykietaRegon": "Numer statystyczny",
    "ue.cyt.litery": ""
});
