/* Teksty modułu ue — język: pt.
   Te same klucze co w napisy/pl.js (wersja źródłowa); wstawki {p0}, {p1}…
   pozostają bez zmian. Klucze ue.cyt.* to wzorce składania odesłań
   do przepisów w tym języku — patrz kraje/ue/cytaty.js. */
KRAJE.napisy('ue', 'pt', {
    "app.10": "Verifique a lista de funções abaixo — o estatuto é determinado pela atividade efetivamente exercida (artigo 3.º da Diretiva (UE) 2022/2555), não por uma inscrição no registo.",
    "app.14": "Ano anterior: {p0} EUR",
    "app.15": "Receitas do período de relato: {p0} EUR",
    "app.19": "A consultar registos pelo número {p0}…",
    "app.34": " mil milhões de EUR",
    "app.35": " milhões de EUR",
    "app.36": " mil EUR",
    "app.37": "",
    "app.4": "A obtenção automática de dados do registo não está disponível para este país — preencha o perfil manualmente.",
    "app.59": "Avaliação de conformidade com a Diretiva NIS 2 (JSON)",
    "app.68": "Para este país não existe registo do qual a ferramenta possa obter dados — o perfil é preenchido manualmente.",
    "app.69": "Para este país não existe registo do qual a ferramenta possa obter dados. Clique para ativar o modo offline.",
    "app.73": " · demonstração de resultados na versão ",
    "app.74": "<div class=\"mt-2 tekst-uwaga\">Os dados do registo não indicam nenhuma função no setor das infraestruturas digitais. Selecione as funções manualmente abaixo.</div>",
    "app.8": "Inscrição no registo de prestadores de comunicações eletrónicas confirmada",
    "app.progDostawcy": "",
    "app.przyklad.adres": "Rua do Exemplo 1, 1000-001 Cidade",
    "app.przyklad.forma": "Sociedade por quotas",
    "app.przyklad.nazwa": "Operador Exemplo, Lda.",
    "app.statusVat": " · estatuto de IVA: ",
    "dashboard.1": "Com base nas funções e na dimensão declaradas, a entidade não é nem essencial nem importante na aceção do artigo 3.º da Diretiva (UE) 2022/2555. Verifique o perfil se o resultado diferir do esperado.",
    "dashboard.113": "Perguntas frequentes",
    "dashboard.12": "— {p0}; o prazo de transposição para o direito nacional expirou em {p2}",
    "dashboard.123": "Diretiva NIS 2",
    "dashboard.30": "Lista de entidades essenciais e importantes",
    "dashboard.4": "— diretamente aplicável desde {p0} em todos os Estados-Membros, sem transposição",
    "dashboard.42": "Variante de montante fixo: {p0}",
    "dashboard.45": "Critérios do artigo 32.º, n.º 7, da diretiva:",
    "dashboard.46": "Total",
    "dashboard.49": "A entidade exerce atividade de comunicações eletrónicas — a responsabilidade do dirigente é determinada pelo direito nacional",
    "dashboard.50": "",
    "dashboard.51": "",
    "dashboard.53": "Sanção pecuniária compulsória por atraso no cumprimento de uma decisão: de {p0} EUR a {p1} EUR por dia ({p2})",
    "dashboard.54": "Caso qualificado: até {p0} EUR ({p1})",
    "dashboard.57": "({p0}). A partir de quando a autoridade nacional pode aplicar coimas é determinado pela lei de transposição da diretiva — este módulo não a conhece. As obrigações de implementação decorrem do direito nacional a partir do dia da sua entrada em vigor.",
    "dashboard.65": "({p0}). A partir de quando a autoridade nacional pode aplicar coimas é determinado pela lei de transposição da diretiva — este módulo não a conhece. O risco financeiro não é, por isso, datado aqui, enquanto as obrigações de implementação decorrem do direito nacional a partir do dia da sua entrada em vigor.",
    "dashboard.83": "Atividade de comunicações eletrónicas — os limiares são fixados pelo direito nacional.",
    "dashboard.84": "O Regulamento (UE) 2024/2690 não se aplica aos fornecedores de redes e serviços de comunicações eletrónicas públicos. Para estes, os limiares de incidente significativo são fixados pelo direito nacional (artigo 23.º, n.º 11, da diretiva) — este módulo não os conhece e, por isso, não apresenta valores.",
    "dashboard.terminRejestracji": "O prazo para a apresentação dos dados de registo é fixado pelo direito nacional (artigo 3.º, n.º 4, da diretiva). Os prestadores do artigo 27.º, n.º 1 — prestadores de serviços de DNS, registos de nomes de domínio de topo, prestadores de serviços de computação em nuvem, de centro de dados, de redes de distribuição de conteúdos, de serviços geridos e de serviços de segurança geridos — apresentam os seus dados ao registo da ENISA: inicialmente até 17 de janeiro de 2025 e cada alteração sem demora injustificada.",
    "html.1": "ITORO — Avaliação de conformidade com a Diretiva NIS 2 (UE) 2022/2555",
    "html.10": "Avaliação de conformidade com a Diretiva NIS 2 — módulo comum",
    "html.100": "A leitura de demonstrações financeiras só funciona para países com módulo de direito nacional. Para este país, introduz as <strong>receitas</strong> do exercício manualmente — o nível da coima depende delas.",
    "html.102": "A obtenção automática de dados do registo só funciona para países com módulo de direito nacional. As funções e a dimensão da empresa são indicadas manualmente.",
    "html.11": "A Diretiva (UE) 2022/2555 (NIS 2) exige transposição para o direito nacional. A avaliação abrange as obrigações que decorrem diretamente da diretiva e o Regulamento de Execução (UE) 2024/2690 da Comissão, diretamente aplicável — na medida em que digam respeito à entidade.",
    "html.23": "as receitas e a dimensão são introduzidas manualmente — o módulo comum não consulta registos nacionais",
    "html.33": "Diretiva (UE) 2022/2555 do Parlamento Europeu e do Conselho, de 14 de dezembro de 2022 (NIS 2)",
    "html.33a": "{p0} — ato nacional de transposição da diretiva; este módulo ainda não avalia os seus requisitos",
    "html.33b": "o Estado ainda não adotou um ato de transposição — a avaliação segue o direito da União",
    "html.35": "obrigações do órgão de direção — artigo 20.º da diretiva",
    "html.36": "A ferramenta serve para autoavaliação. Não é uma auditoria nem aconselhamento jurídico.",
    "html.40": "o módulo comum não estabelece qualquer ligação de saída — não consulta registos",
    "html.59": "Demonstrações financeiras",
    "html.60": "A leitura de demonstrações financeiras só está disponível para países com módulo de direito nacional. Para este país, introduz as receitas e o número de efetivos manualmente.",
    "html.62": "Pesquisa no registo",
    "html.63": "os registos comerciais são nacionais — o módulo comum não os conhece",
    "html.64": "as funções e a dimensão da empresa são indicadas manualmente",
    "html.66": "Número de identificação da entidade",
    "html.68": "A obtenção automática de dados do registo só funciona para países com módulo de direito nacional.",
    "html.76": "Receitas anuais (EUR)",
    "html.78": "Receitas da atividade de comunicações eletrónicas (EUR)",
    "html.79": "O campo diz respeito aos fornecedores de redes ou serviços de comunicações eletrónicas públicos. Os limiares nacionais são fixados pelo direito do Estado-Membro.",
    "html.80": "Remuneração mensal do responsável (EUR)",
    "html.82": "Taxa de câmbio",
    "html.83": "Os limites máximos das coimas na diretiva são expressos em euros. A conversão para a moeda nacional e a taxa são determinadas pelo direito nacional — aqui os montantes são apresentados em euros sem conversão.",
    "html.84": "O estatuto decorre exclusivamente da agregação dos dados de empresas associadas e o sistema de informação da entidade é independente (considerando 16 da diretiva — a aplicação é decidida pelo direito nacional)",
    "html.85": "A entidade atua nos domínios da segurança nacional, da segurança pública, da defesa ou da aplicação da lei (artigo 2.º, n.º 7, da diretiva)",
    "html.91": "Avaliação de conformidade com a Diretiva (UE) 2022/2555 do Parlamento Europeu e do Conselho (NIS 2) e com o Regulamento de Execução (UE) 2024/2690 da Comissão — módulo comum para os países cujo módulo de direito nacional ainda não está pronto.",
    "html.94": "se a entidade é <strong>essencial</strong>, <strong>importante</strong> ou está fora do âmbito de aplicação da diretiva",
    "html.daneZeSprawozdania": "nome, número de identificação, endereço da sede",
    "html.rejestrMozliwy": "O registo {p0} é público e gratuito — a sua leitura pode ser acrescentada; aceitamos pull requests (ver README).",
    "html.tytulNaglowka": "Avaliação de conformidade com a Diretiva NIS 2",
    "html.zrodlaRecznie": "Este módulo não conhece os registos do seu Estado — preencha o perfil à mão. O volume de negócios anual determina o limite da coima, por isso indique-o com precisão.",
    "klasyfikacja.10": "artigo 3.º, n.º 1, alínea c), da Diretiva (UE) 2022/2555 (fornecedor de redes de comunicações eletrónicas públicas ou de serviços de comunicações eletrónicas acessíveis ao público que seja pelo menos uma média empresa)",
    "klasyfikacja.11": "artigo 3.º, n.º 2, em conjugação com o artigo 2.º, n.º 2, alínea a), subalínea i), da Diretiva (UE) 2022/2555 (fornecedor de redes ou serviços de comunicações eletrónicas públicos que seja uma micro ou pequena empresa)",
    "klasyfikacja.12": "artigo 3.º, n.º 1, alínea a), da Diretiva (UE) 2022/2555 (prestador de serviços de segurança geridos que excede os limites máximos de média empresa)",
    "klasyfikacja.13": "As micro e pequenas empresas não são abrangidas pela diretiva a título desta função (artigo 2.º, n.º 1, a contrario).",
    "klasyfikacja.15": "artigo 3.º, n.º 1, alínea b), da Diretiva (UE) 2022/2555 (prestador qualificado de serviços de confiança) — independentemente da dimensão da empresa",
    "klasyfikacja.16": "artigo 3.º, n.º 2, em conjugação com o artigo 2.º, n.º 2, alínea a), subalínea ii), da Diretiva (UE) 2022/2555 (prestador não qualificado de serviços de confiança que seja uma micro, pequena ou média empresa)",
    "klasyfikacja.18": "artigo 3.º, n.º 2, da Diretiva (UE) 2022/2555 (entidade da administração pública a nível regional, se o Estado-Membro assim o determinar — artigo 2.º, n.º 2, alínea f), subalínea ii))",
    "klasyfikacja.19": "artigo 3.º, n.º 1, alínea f), da Diretiva (UE) 2022/2555 (entidade da administração pública a nível central — artigo 2.º, n.º 2, alínea f), subalínea i))",
    "klasyfikacja.2": "Supervisão ex ante e ex post (artigo 32.º da Diretiva (UE) 2022/2555).",
    "klasyfikacja.20": "artigo 3.º, n.º 2, da Diretiva (UE) 2022/2555 (entidade da administração pública a nível regional — artigo 2.º, n.º 2, alínea f), subalínea ii))",
    "klasyfikacja.21": "O âmbito das obrigações das entidades da administração pública a nível local é determinado pelo direito nacional (artigo 2.º, n.º 5, alínea a), da diretiva).",
    "klasyfikacja.22": "Um Estado-Membro pode isentar as entidades que exercem atividades nos domínios da segurança nacional, da segurança pública, da defesa ou da aplicação da lei (artigo 2.º, n.º 7, da diretiva). A isenção não opera por si só — verifique o resultado da avaliação à luz do direito nacional.",
    "klasyfikacja.23": "A entidade cumpre os critérios tanto de entidade essencial como de entidade importante. É uma entidade essencial (artigo 3.º, n.º 1, da diretiva) e os requisitos mais rigorosos aplicam-se a toda a atividade abrangida pela diretiva.",
    "klasyfikacja.25": "A entidade é essencial, pelo que se aplica o catálogo completo de medidas do artigo 21.º, n.º 2, da diretiva e a supervisão ex ante e ex post — a avaliação abrange o conjunto completo de perguntas.",
    "klasyfikacja.26": "Enquanto entidade importante, está sujeita ao mesmo catálogo de medidas do artigo 21.º, n.º 2, mas apenas a supervisão ex post (artigo 33.º). O limite máximo da coima é mais baixo: 7 milhões de EUR ou 1,4 % do volume de negócios (artigo 34.º, n.º 5). Atenuações para entidades públicas podem ser introduzidas pelo direito nacional — este módulo não as conhece.",
    "klasyfikacja.28": "As obrigações das entidades da administração pública decorrem do artigo 2.º, n.º 2, alínea f), da diretiva; o seu âmbito exato, incluindo para o nível local e os estabelecimentos de ensino, é determinado pelo direito nacional (artigo 2.º, n.º 5).",
    "klasyfikacja.29": "Foi declarado que o estatuto da entidade resulta exclusivamente da agregação dos dados de empresas associadas ou parceiras e que o sistema de informação da entidade é independente. A diretiva permite essa exclusão (considerando 16), mas é o direito nacional que a decide — o módulo aceita a exclusão, que deve ser verificada à luz do direito do Estado-Membro e documentada.",
    "klasyfikacja.4": "Apenas supervisão ex post — perante provas, indícios ou informações de infração (artigo 33.º da Diretiva (UE) 2022/2555).",
    "klasyfikacja.5": "Fora do âmbito de aplicação da diretiva",
    "klasyfikacja.6": "Para a função indicada não decorrem obrigações da Diretiva (UE) 2022/2555.",
    "klasyfikacja.7": "artigo 3.º, n.º 1, alínea a), da Diretiva (UE) 2022/2555 (entidade de um tipo referido no anexo I que excede os limites máximos de média empresa)",
    "klasyfikacja.8": "artigo 3.º, n.º 2, da Diretiva (UE) 2022/2555 (entidade de um tipo referido no anexo I que cumpre os critérios de média empresa)",
    "klasyfikacja.9": "As micro e pequenas empresas não são abrangidas pela diretiva a título desta função (artigo 2.º, n.º 1, a contrario).",
    "kreator.10": "Introduza as receitas do ano anterior manualmente.",
    "kreator.35": "<span class=\"text-secondary\">A leitura de demonstrações financeiras não está disponível para este país.</span>",
    "kreator.37": "A leitura de demonstrações financeiras não está disponível para este país — introduza as receitas manualmente.",
    "kreator.56": "Sim — o regulamento da UE é diretamente aplicável desde 7 de novembro de 2024 em todos os Estados-Membros e não tem período transitório. A sua base é",
    "kreator.57": ", que habilitou a Comissão a estabelecer os requisitos técnicos e metodológicos para os prestadores referidos no artigo 3.º, n.º 1, do regulamento. O prazo de transposição da diretiva expirou em",
    "kreator.58": ", e a partir de quando a autoridade nacional pode aplicar coimas é determinado pelo direito nacional. Os requisitos técnicos do anexo (secções 6 e 9 a 13) são vinculativos na sua redação atual — não aguardam clarificação. Só é possível derrogar os requisitos com a cláusula «se for caso disso», e apenas com uma justificação documentada.",
    "kreator.9": "Demonstrações financeiras →",
    "kreator.przepisReg2690": "o artigo 21.º, n.º 5, da Diretiva (UE) 2022/2555",
    "kreator.terminReg2690": "17 de outubro de 2024",
    "punktacja.10": "Entidades públicas",
    "punktacja.4": "Diretiva NIS 2 — artigo 21.º",
    "punktacja.5": "Diretiva NIS 2 — obrigações formais",
    "punktacja.8": "Comunicações eletrónicas",
    "punktacja.9": "Diretiva NIS 2 — entidades públicas",
    "punktacja.skrotKsc": "NIS 2",
    "punktacja.skrotPke": "telecom",
    "ue.cyt.akapit": ", {p0} parágrafo",
    "ue.cyt.art": "artigo {p0}.º",
    "ue.cyt.drugi": "segundo",
    "ue.cyt.dyr": "{p0}, da Diretiva (UE) 2022/2555",
    "ue.cyt.i": "e",
    "ue.cyt.laczenie": "",
    "ue.cyt.lit": ", alínea {p0})",
    "ue.cyt.litery": "",
    "ue.cyt.pkt": ", ponto {p0}",
    "ue.cyt.rozdzielacz": "; ",
    "ue.cyt.rozp": "{p0}, do Regulamento (UE) 2024/2690",
    "ue.cyt.ust": ", n.º {p0}",
    "ue.katalog.1": "Políticas de análise dos riscos e de segurança dos sistemas de informação",
    "ue.katalog.10": "Tratamento de incidentes",
    "ue.katalog.11": "O tratamento de incidentes abrange as ações e os procedimentos destinados a prevenir, detetar, analisar e conter um incidente, ou a responder-lhe e a recuperar dele (artigo 6.º, ponto 8).",
    "ue.katalog.12": "Existe um procedimento documentado de tratamento de incidentes que abrange a deteção, a análise, a contenção, a resposta e a recuperação?",
    "ue.katalog.13": "ISO/IEC 27001 A.5.24–A.5.26",
    "ue.katalog.14": "O procedimento permite cumprir os prazos de notificação de um incidente significativo: alerta precoce em 24 horas, notificação do incidente em 72 horas, relatório final no prazo de um mês?",
    "ue.katalog.15": "ISO/IEC 27001 A.5.24",
    "ue.katalog.16": "A entidade dispõe de critérios para considerar um incidente significativo, em conformidade com o artigo 23.º, n.º 3: perturbação operacional grave ou perda financeira, ou danos consideráveis para outras pessoas?",
    "ue.katalog.17": "ISO/IEC 27001 A.5.25",
    "ue.katalog.18": "Os incidentes são registados e as lições retiradas do seu tratamento são utilizadas para melhorar as medidas?",
    "ue.katalog.19": "ISO/IEC 27001 A.5.27",
    "ue.katalog.2": "As medidas baseiam-se numa abordagem que abrange todos os perigos (artigo 21.º, n.º 2). A sua proporcionalidade é avaliada tendo em conta o grau de exposição, a dimensão da entidade, a probabilidade de incidentes e a sua gravidade (artigo 21.º, n.º 1, segundo parágrafo).",
    "ue.katalog.20": "Continuidade da atividade e gestão de crises",
    "ue.katalog.21": "Continuidade da atividade, como a gestão de cópias de segurança e a recuperação de desastres, e gestão de crises.",
    "ue.katalog.22": "Existe um plano de continuidade da atividade que abrange a recuperação após um desastre?",
    "ue.katalog.23": "ISO/IEC 27001 A.5.29–A.5.30",
    "ue.katalog.24": "As cópias de segurança são efetuadas, protegidas e testadas quanto à possibilidade de restauro?",
    "ue.katalog.25": "ISO/IEC 27001 A.8.13",
    "ue.katalog.26": "A entidade dispõe de procedimentos de gestão de crises com funções e canais de comunicação definidos?",
    "ue.katalog.27": "ISO/IEC 27001 A.5.29",
    "ue.katalog.28": "Os planos de continuidade e de recuperação são testados periodicamente e os resultados documentados?",
    "ue.katalog.29": "ISO/IEC 27001 A.5.30",
    "ue.katalog.3": "A entidade dispõe de uma política documentada de análise dos riscos e de segurança dos sistemas de informação, aprovada pelo órgão de direção?",
    "ue.katalog.30": "Segurança da cadeia de abastecimento",
    "ue.katalog.31": "Segurança da cadeia de abastecimento, incluindo os aspetos de segurança relativos às relações entre a entidade e os seus fornecedores diretos ou prestadores de serviços. A entidade tem em conta as vulnerabilidades específicas de cada fornecedor e a qualidade global dos seus produtos e práticas de cibersegurança (artigo 21.º, n.º 3).",
    "ue.katalog.32": "A entidade mantém uma lista de fornecedores diretos e prestadores de serviços com uma avaliação da sua importância para a segurança das redes e dos sistemas?",
    "ue.katalog.33": "ISO/IEC 27001 A.5.19",
    "ue.katalog.34": "Na escolha das medidas relativas aos fornecedores, são tidas em conta as vulnerabilidades específicas de cada um e a qualidade das suas práticas de cibersegurança e de desenvolvimento seguro?",
    "ue.katalog.35": "ISO/IEC 27001 A.5.19, A.5.21",
    "ue.katalog.36": "Os contratos com fornecedores contêm requisitos de segurança e a obrigação de comunicar incidentes e vulnerabilidades?",
    "ue.katalog.37": "ISO/IEC 27001 A.5.20",
    "ue.katalog.38": "A entidade tem em conta os resultados das avaliações coordenadas dos riscos de segurança das cadeias de abastecimento críticas referidas no artigo 22.º?",
    "ue.katalog.39": "ISO/IEC 27001 A.5.21",
    "ue.katalog.4": "ISO/IEC 27001, cláusulas 5.2, 6.1.2",
    "ue.katalog.40": "Segurança na aquisição, desenvolvimento e manutenção de sistemas",
    "ue.katalog.41": "Segurança na aquisição, desenvolvimento e manutenção de sistemas de rede e de informação, incluindo o tratamento e a divulgação de vulnerabilidades.",
    "ue.katalog.42": "Os requisitos de segurança são definidos antes da aquisição ou do início do desenvolvimento de um sistema e verificados antes da entrada em produção?",
    "ue.katalog.43": "ISO/IEC 27001 A.8.25–A.8.29",
    "ue.katalog.44": "Existe um processo de tratamento de vulnerabilidades: identificação, avaliação, correção num prazo definido?",
    "ue.katalog.45": "ISO/IEC 27001 A.8.8",
    "ue.katalog.46": "A entidade dispõe de um procedimento de divulgação de vulnerabilidades, incluindo um canal para receber comunicações de terceiros?",
    "ue.katalog.47": "As alterações aos sistemas passam por um processo controlado de gestão de alterações com avaliação do impacto na segurança?",
    "ue.katalog.48": "ISO/IEC 27001 A.8.32",
    "ue.katalog.49": "Avaliação da eficácia das medidas",
    "ue.katalog.5": "A análise dos riscos abrange todos os perigos para os sistemas de rede e de informação e o seu ambiente físico, e não apenas as ciberameaças?",
    "ue.katalog.50": "Políticas e procedimentos para avaliar a eficácia das medidas de gestão dos riscos de cibersegurança.",
    "ue.katalog.51": "Existe uma política documentada de avaliação da eficácia das medidas que define o âmbito, a frequência e os métodos?",
    "ue.katalog.52": "ISO/IEC 27001, cláusula 9.1",
    "ue.katalog.53": "As avaliações de eficácia são realizadas periodicamente e os seus resultados comunicados ao órgão de direção?",
    "ue.katalog.54": "ISO/IEC 27001, cláusulas 9.2–9.3",
    "ue.katalog.55": "As deficiências identificadas dão origem a ações corretivas documentadas com responsável e prazo?",
    "ue.katalog.56": "ISO/IEC 27001, cláusula 10.1",
    "ue.katalog.57": "Ciber-higiene e formação",
    "ue.katalog.58": "Práticas básicas de ciber-higiene e formação em cibersegurança. Os membros do órgão de direção frequentam regularmente formação (artigo 20.º, n.º 2).",
    "ue.katalog.59": "A entidade aplica práticas básicas de ciber-higiene: atualizações, gestão de palavras-passe, restrição de privilégios, proteção contra software malicioso?",
    "ue.katalog.6": "ISO/IEC 27001, cláusula 6.1.2",
    "ue.katalog.60": "ISO/IEC 27001 A.8.7, A.8.8",
    "ue.katalog.61": "Os trabalhadores recebem formação em cibersegurança adaptada à sua função, com a participação documentada?",
    "ue.katalog.62": "ISO/IEC 27001 A.6.3",
    "ue.katalog.63": "Os membros do órgão de direção frequentam regularmente formação que lhes permite identificar riscos e avaliar as práticas de gestão dos riscos?",
    "ue.katalog.64": "ISO/IEC 27001, cláusula 7.2",
    "ue.katalog.65": "Criptografia e cifragem",
    "ue.katalog.66": "Políticas e procedimentos relativos à utilização de criptografia e, se for caso disso, de cifragem.",
    "ue.katalog.67": "Existe uma política de criptografia que define que dados e canais são cifrados e com que algoritmos?",
    "ue.katalog.68": "ISO/IEC 27001 A.8.24",
    "ue.katalog.69": "As chaves criptográficas são geridas ao longo de todo o ciclo de vida: geração, distribuição, armazenamento, rotação, retirada?",
    "ue.katalog.7": "A escolha das medidas tem em conta o estado da técnica, as normas europeias e internacionais pertinentes e o custo de implementação?",
    "ue.katalog.70": "Recursos humanos, controlo de acesso e gestão de ativos",
    "ue.katalog.71": "Segurança dos recursos humanos, políticas de controlo de acesso e gestão de ativos.",
    "ue.katalog.72": "A entidade mantém um inventário de ativos atualizado com proprietários atribuídos e classificação?",
    "ue.katalog.73": "ISO/IEC 27001 A.5.9, A.5.12",
    "ue.katalog.74": "Existe uma política de controlo de acesso baseada no princípio do menor privilégio, com revisão periódica dos privilégios?",
    "ue.katalog.75": "ISO/IEC 27001 A.5.15, A.5.18",
    "ue.katalog.76": "São aplicados procedimentos de segurança na contratação, na mudança de função e na saída de um trabalhador, incluindo a revogação de privilégios e a devolução de ativos?",
    "ue.katalog.77": "ISO/IEC 27001 A.6.1–A.6.5",
    "ue.katalog.78": "O acesso privilegiado é restrito, registado e revisto?",
    "ue.katalog.79": "ISO/IEC 27001 A.8.2",
    "ue.katalog.8": "ISO/IEC 27001, cláusula 6.1.3",
    "ue.katalog.80": "Autenticação multifator e comunicações protegidas",
    "ue.katalog.81": "Se for caso disso — autenticação multifator ou contínua, comunicações de voz, vídeo e texto protegidas e sistemas de comunicação de emergência protegidos no interior da entidade.",
    "ue.katalog.82": "A autenticação multifator ou contínua é utilizada onde a análise dos riscos o justifica, em especial para o acesso remoto e as contas privilegiadas?",
    "ue.katalog.83": "ISO/IEC 27001 A.8.5",
    "ue.katalog.84": "As comunicações de voz, vídeo e texto utilizadas para fins profissionais estão protegidas?",
    "ue.katalog.85": "ISO/IEC 27001 A.8.20",
    "ue.katalog.86": "A entidade dispõe de um sistema interno protegido de comunicação de emergência, independente da infraestrutura principal?",
    "ue.katalog.9": "O nível de segurança está documentado como adequado ao risco existente, com uma justificação que tem em conta a dimensão da entidade e o impacto social e económico dos incidentes?",
    "ue.kierownictwo.1": "O órgão de direção de uma entidade essencial ou importante — numa sociedade de capitais, o conselho de administração. A diretiva não define o conceito; o seu âmbito em cada país decorre do direito nacional.",
    "ue.kierownictwo.10": "Determinar o estatuto da entidade e assegurar o registo",
    "ue.kierownictwo.11": "Determinação de se a entidade é essencial ou importante e apresentação dos dados de registo à autoridade competente. O procedimento e o prazo são fixados pelo direito nacional.",
    "ue.kierownictwo.12": "Implementar a análise dos riscos e uma política de segurança",
    "ue.kierownictwo.13": "Medidas baseadas numa abordagem que abrange todos os perigos, proporcionadas à exposição, à dimensão da entidade e à gravidade dos incidentes.",
    "ue.kierownictwo.14": "Estabelecer o tratamento e a notificação de incidentes",
    "ue.kierownictwo.15": "Um procedimento de tratamento de incidentes e a capacidade de cumprir os prazos de 24 horas, 72 horas e um mês.",
    "ue.kierownictwo.16": "24 h / 72 h / um mês a contar da deteção",
    "ue.kierownictwo.17": "Assegurar a continuidade da atividade",
    "ue.kierownictwo.18": "Plano de continuidade, cópias de segurança, recuperação de desastres, gestão de crises.",
    "ue.kierownictwo.19": "Organizar a cadeia de abastecimento",
    "ue.kierownictwo.2": "A responsabilidade do órgão de direção não prejudica as regras nacionais sobre a responsabilidade das instituições públicas e dos funcionários (artigo 20.º, n.º 1, segundo parágrafo).",
    "ue.kierownictwo.20": "Lista de fornecedores, avaliação das suas vulnerabilidades e práticas, requisitos de segurança nos contratos.",
    "ue.kierownictwo.21": "Implementar o controlo de acesso e a gestão de ativos",
    "ue.kierownictwo.22": "Inventário de ativos, princípio do menor privilégio, revisões de privilégios, autenticação multifator onde o risco o justifica.",
    "ue.kierownictwo.23": "Medir a eficácia das medidas",
    "ue.kierownictwo.24": "Política e procedimentos de avaliação da eficácia, revisões periódicas, ações corretivas.",
    "ue.kierownictwo.25": "Aprovar",
    "ue.kierownictwo.26": "as medidas de gestão dos riscos de cibersegurança (artigo 20.º, n.º 1)",
    "ue.kierownictwo.27": "a política de análise dos riscos e de segurança dos sistemas",
    "ue.kierownictwo.28": "o orçamento e as funções na implementação",
    "ue.kierownictwo.29": "Supervisionar",
    "ue.kierownictwo.3": "Se a delegação de obrigações noutra pessoa exclui a responsabilidade é decidido pelo direito nacional. Na Polónia não exclui (artigo 8.º-C, n.º 3, da Lei do Sistema Nacional de Cibersegurança).",
    "ue.kierownictwo.30": "a implementação das medidas aprovadas (artigo 20.º, n.º 1)",
    "ue.kierownictwo.31": "os resultados da avaliação da eficácia (artigo 21.º, n.º 2, alínea f))",
    "ue.kierownictwo.32": "o cumprimento dos prazos de notificação de incidentes (artigo 23.º)",
    "ue.kierownictwo.33": "Documentar",
    "ue.kierownictwo.34": "as decisões de aprovação e as revisões",
    "ue.kierownictwo.35": "a participação em formação (artigo 20.º, n.º 2)",
    "ue.kierownictwo.36": "Membro do órgão de direção",
    "ue.kierownictwo.37": "aprovação das medidas, supervisão, decisões, orçamento",
    "ue.kierownictwo.38": "Gestor de projeto",
    "ue.kierownictwo.39": "coordenação da implementação, calendário, estado e provas",
    "ue.kierownictwo.4": "Aprovar as medidas de gestão dos riscos de cibersegurança",
    "ue.kierownictwo.40": "TI / cibersegurança",
    "ue.kierownictwo.41": "análise dos riscos, medidas técnicas, tratamento de incidentes",
    "ue.kierownictwo.42": "Jurídico / conformidade",
    "ue.kierownictwo.5": "O órgão de direção aprova as medidas tomadas para cumprir o artigo 21.º. É uma decisão do órgão, não do departamento de TI — sem ela as medidas não têm fundamento.",
    "ue.kierownictwo.6": "Supervisionar a implementação das medidas",
    "ue.kierownictwo.7": "A supervisão da implementação é uma obrigação do órgão de direção. A execução pode ser delegada; a supervisão não.",
    "ue.kierownictwo.8": "Frequentar regularmente formação",
    "ue.kierownictwo.9": "Os membros do órgão de direção frequentam regularmente formação para adquirir conhecimentos suficientes para identificar riscos e avaliar as práticas de gestão dos riscos e o seu impacto nos serviços da entidade.",
    "ue.kierownictwo.daneRejestracyjne": "dados de registo e respetiva atualização (artigo 3.º, n.os 4 e 5)",
    "ue.meta.1": "Prevalece a variante percentual: {p0} % do volume de negócios é mais do que {p1} milhões de EUR.",
    "ue.meta.10": "A diretiva não impõe obrigações às empresas diretamente — fá-lo a lei nacional, que o Estado-Membro deveria ter adotado até 17 de outubro de 2024. Este módulo apresenta os requisitos na redação da diretiva, porque o módulo de direito nacional para o país selecionado ainda não está pronto ou o país não transpôs a diretiva.",
    "ue.meta.11": "Obrigações decorrentes da diretiva",
    "ue.meta.12": "Lista de entidades — até 17 de abril de 2025",
    "ue.meta.13": "Os Estados-Membros deveriam estabelecer, até 17 de abril de 2025, uma lista de entidades essenciais e importantes e exigir às entidades a apresentação dos dados de registo.",
    "ue.meta.14": "Regulamento (UE) 2024/2690",
    "ue.meta.15": "Diretamente aplicável desde 7 de novembro de 2024",
    "ue.meta.16": "O regulamento de execução é diretamente aplicável em todos os Estados-Membros, independentemente do estado de transposição da diretiva. Diz respeito às entidades enumeradas no seu artigo 1.º: prestadores de DNS, domínios de topo, computação em nuvem, centros de dados, redes de distribuição de conteúdos, serviços geridos e serviços de confiança.",
    "ue.meta.17": "artigo 16.º do Regulamento (UE) 2024/2690",
    "ue.meta.18": "Pelo menos 10 000 000 EUR ou pelo menos 2 % do volume de negócios anual total a nível mundial da empresa no exercício anterior — consoante o valor mais elevado. Trata-se de um limite máximo mínimo: o direito nacional pode aumentá-lo.",
    "ue.meta.19": "Pelo menos 7 000 000 EUR ou 1,4 % do volume de negócios anual total a nível mundial — consoante o valor mais elevado. Limite máximo mínimo.",
    "ue.meta.2": "Prevalece o montante fixo: {p0} milhões de EUR é mais do que {p1} % do volume de negócios.",
    "ue.meta.20": "A diretiva não prevê uma coima distinta para a infração qualificada — trata-se de uma construção do direito nacional de alguns Estados-Membros.",
    "ue.meta.21": "Os Estados-Membros podem prever sanções pecuniárias compulsórias para obrigar à cessação de uma infração. O montante é fixado pelo direito nacional.",
    "ue.meta.22": "O órgão de direção aprova as medidas de gestão dos riscos, supervisiona a sua implementação e pode ser responsabilizado por infrações ao artigo 21.º. As regras e o âmbito dessa responsabilidade são determinados pelo direito nacional.",
    "ue.meta.23": "O órgão de direção aprova as medidas de gestão dos riscos de cibersegurança (artigo 20.º, n.º 1).",
    "ue.meta.24": "O órgão de direção supervisiona a implementação dessas medidas (artigo 20.º, n.º 1).",
    "ue.meta.25": "Os membros do órgão de direção frequentam regularmente formação (artigo 20.º, n.º 2).",
    "ue.meta.26": "No caso de uma entidade essencial, a autoridade pode solicitar a proibição temporária do exercício de funções de direção (artigo 32.º, n.º 5, alínea b)).",
    "ue.meta.27": "O limite máximo mínimo é fixado pela diretiva",
    "ue.meta.28": "Comparam-se dois valores: um montante fixo em euros e uma percentagem do volume de negócios anual total a nível mundial da empresa no exercício anterior. O mais elevado dos dois é o limite superior que o Estado-Membro deve prever no mínimo. O direito nacional pode aumentá-lo.",
    "ue.meta.29": "O montante dentro do limite máximo é fixado pela autoridade nacional",
    "ue.meta.3": "O limite máximo da diretiva excede o volume de negócios anual da entidade em {p0} vezes. O artigo 34.º, n.º 1, exige que a coima seja proporcionada às circunstâncias de cada caso — trata-se de um limite superior, não de uma coima esperada.",
    "ue.meta.30": "A coima deve ser efetiva, proporcionada e dissuasiva em função das circunstâncias de cada caso. A autoridade tem em conta pelo menos os critérios do artigo 32.º, n.º 7: a gravidade e a duração da infração, infrações anteriores, os danos causados, a intenção, as medidas corretivas e a cooperação.",
    "ue.meta.31": "O limite máximo pode exceder várias vezes o volume de negócios anual — é um limite superior, não um montante esperado. Os mínimos nacionais, as sanções pecuniárias compulsórias e o procedimento de graduação são determinados pela lei do Estado-Membro.",
    "ue.meta.32": "Ao decidir se deve ser aplicada uma coima administrativa e o seu montante, são devidamente tidos em conta, em cada caso concreto, pelo menos os elementos enumerados no artigo 32.º, n.º 7.",
    "ue.meta.33": "a gravidade da infração e a importância das disposições violadas — consideram-se graves, em qualquer caso: infrações repetidas, a não notificação ou não correção de incidentes significativos, a não correção de deficiências contrariando instruções vinculativas, a obstrução de auditorias ou da monitorização, a prestação de informações falsas ou grosseiramente inexatas",
    "ue.meta.34": "quaisquer infrações anteriores pertinentes da entidade",
    "ue.meta.35": "os danos materiais ou não materiais causados, incluindo perdas financeiras, efeitos noutros serviços e o número de utilizadores afetados",
    "ue.meta.36": "o caráter doloso ou negligente da infração",
    "ue.meta.37": "as medidas tomadas para prevenir ou atenuar os danos",
    "ue.meta.38": "o cumprimento de códigos de conduta ou mecanismos de certificação aprovados",
    "ue.meta.39": "o grau de cooperação com as autoridades competentes",
    "ue.meta.4": "Diretiva (UE) 2022/2555 do Parlamento Europeu e do Conselho (NIS 2)",
    "ue.meta.40": "A diretiva não prevê expressamente a dispensa da coima — se e quando tal é possível é decidido pelo direito nacional.",
    "ue.meta.41": "A partir desta data, os Estados-Membros devem aplicar as disposições nacionais de transposição da diretiva. A data concreta a partir da qual a autoridade pode aplicar uma coima decorre do direito nacional.",
    "ue.meta.42": "Entrada em vigor da Diretiva NIS 2",
    "ue.meta.43": "No vigésimo dia seguinte ao da publicação no Jornal Oficial.",
    "ue.meta.44": "Prazo de transposição da diretiva",
    "ue.meta.45": "Até esta data, os Estados-Membros deveriam adotar e publicar as disposições nacionais.",
    "ue.meta.46": "Aplicação das disposições nacionais e revogação da NIS 1",
    "ue.meta.47": "A partir desta data, os Estados-Membros aplicam as disposições de transposição; a Diretiva (UE) 2016/1148 é revogada.",
    "ue.meta.48": "Aplicação do Regulamento (UE) 2024/2690",
    "ue.meta.49": "O regulamento de execução é diretamente aplicável a partir do vigésimo dia seguinte ao da publicação.",
    "ue.meta.5": "JO UE L 333 de 27.12.2022",
    "ue.meta.50": "Lista de entidades essenciais e importantes",
    "ue.meta.51": "Até esta data, os Estados-Membros estabelecem a lista; as entidades apresentam os dados de registo às autoridades.",
    "ue.meta.52": "Primeira revisão da diretiva pela Comissão",
    "ue.meta.53": "A Comissão reexamina o funcionamento da diretiva e apresenta um relatório.",
    "ue.meta.54": "Alerta precoce de incidente significativo",
    "ue.meta.55": "24 horas após tomar conhecimento",
    "ue.meta.56": "Notificação de incidente significativo",
    "ue.meta.57": "72 horas após tomar conhecimento",
    "ue.meta.58": "Relatório final",
    "ue.meta.59": "um mês após a notificação do incidente",
    "ue.meta.6": "Regulamento de Execução (UE) 2024/2690 da Comissão",
    "ue.meta.60": "Notificação de incidente por um prestador de serviços de confiança",
    "ue.meta.61": "artigo 21.º, n.º 5, da Diretiva (UE) 2022/2555; artigos 1.º e 2.º do Regulamento (UE) 2024/2690",
    "ue.meta.62": "Sem dados de volume de negócios, o limite máximo é o montante fixo da diretiva.",
    "ue.meta.63": "Os limites máximos do artigo 34.º, n.os 4 e 5, são mínimos («pelo menos») — o direito nacional pode prever valores mais elevados. Montantes em euros, sem conversão para a moeda nacional.",
    "ue.meta.64": "Autoridade competente do Estado-Membro",
    "ue.meta.65": "O órgão de direção pode ser responsabilizado por infrações ao artigo 21.º. O âmbito e o procedimento são determinados pelo direito nacional — este módulo não os conhece.",
    "ue.meta.66": "O âmbito da responsabilidade pessoal da direção decorre da lei nacional. Para a Polónia é até 300 % da remuneração (artigo 73.º-A, n.º 4, da Lei do Sistema Nacional de Cibersegurança); outros Estados-Membros regulam-no de forma diferente.",
    "ue.meta.7": "JO UE L, 2024/2690",
    "ue.meta.8": "Diretiva (UE) 2022/2555",
    "ue.meta.9": "O prazo de transposição expirou em 17 de outubro de 2024",
    "ue.moduly.1": "cerca de {p0} min",
    "ue.moduly.10": "Dez áreas do artigo 21.º, n.º 2, alíneas a) a j): da política de riscos à autenticação multifator. A infração é punível com coima nos termos do artigo 34.º. Avaliação numa escala de maturidade.",
    "ue.moduly.11": "Regulamento 2024/2690 — governação e processos",
    "ue.moduly.12": "Secções 1 a 5 e 7 a 8 do anexo: políticas, gestão dos riscos, tratamento de incidentes, continuidade da atividade, cadeia de abastecimento, avaliação da eficácia, ciber-higiene. Diretamente aplicável desde 7 de novembro de 2024.",
    "ue.moduly.13": "Regulamento 2024/2690 — requisitos técnicos",
    "ue.moduly.14": "Secções 6 e 9 a 13 do anexo: aquisição e desenvolvimento de sistemas, criptografia, segurança dos recursos humanos, controlo de acesso, gestão de ativos, segurança física e ambiental.",
    "ue.moduly.2": "cerca de {p0} h {p1} min",
    "ue.moduly.3": "cerca de {p0} h",
    "ue.moduly.4": "menos de um minuto",
    "ue.moduly.5": "Avaliação rápida do risco",
    "ue.moduly.6": "Perguntas transversais de todas as áreas da diretiva. Cada uma decide sobre um grupo inteiro de temas. Permite avaliar a dimensão dos atrasos sem percorrer todo o questionário.",
    "ue.moduly.7": "Obrigações decorrentes da diretiva",
    "ue.moduly.8": "Dados de registo, notificação de incidentes em 24 e 72 horas, obrigações do órgão de direção, preparação para a supervisão. Verificável a partir de documentos, sem análise técnica.",
    "ue.moduly.9": "Medidas de gestão dos riscos — artigo 21.º, n.º 2",
    "ue.obowiazki.1": "Dados de registo para a lista de entidades",
    "ue.obowiazki.10": "Notificação de incidentes significativos",
    "ue.obowiazki.11": "A entidade notifica os incidentes significativos à CSIRT ou à autoridade competente em três etapas: alerta precoce, notificação do incidente, relatório final. Os prazos correm a partir do conhecimento do incidente.",
    "ue.obowiazki.12": "A entidade é capaz de, no prazo de 24 horas após tomar conhecimento de um incidente significativo, apresentar um alerta precoce indicando se o incidente é presumivelmente causado por atos ilícitos e se pode ter impacto transfronteiriço?",
    "ue.obowiazki.13": "24 horas após tomar conhecimento",
    "ue.obowiazki.14": "A entidade é capaz de, no prazo de 72 horas, apresentar uma notificação do incidente com uma avaliação inicial da gravidade e do impacto e indicadores de comprometimento?",
    "ue.obowiazki.15": "72 horas após tomar conhecimento",
    "ue.obowiazki.16": "A entidade apresenta, o mais tardar um mês após a notificação, um relatório final com a descrição do incidente, o tipo de ameaça, as medidas de atenuação e o impacto transfronteiriço?",
    "ue.obowiazki.17": "um mês após a notificação",
    "ue.obowiazki.18": "A entidade informa os destinatários dos seus serviços sobre incidentes significativos suscetíveis de afetar negativamente a prestação desses serviços?",
    "ue.obowiazki.19": "A entidade informa os destinatários dos serviços sobre uma ciberameaça significativa e sobre as medidas que os destinatários podem tomar?",
    "ue.obowiazki.2": "Os Estados-Membros estabelecem uma lista de entidades essenciais e importantes e exigem às entidades a apresentação dos dados de registo. O procedimento, o prazo e o portal são fixados pelo direito nacional.",
    "ue.obowiazki.20": "Se a entidade for um prestador de serviços de confiança — notifica os incidentes significativos no prazo de 24 horas após tomar conhecimento?",
    "ue.obowiazki.21": "aplica-se aos prestadores de serviços de confiança",
    "ue.obowiazki.22": "Órgão de direção",
    "ue.obowiazki.23": "O órgão de direção aprova as medidas de gestão dos riscos, supervisiona a sua implementação e pode ser responsabilizado. Os membros do órgão frequentam regularmente formação.",
    "ue.obowiazki.24": "O órgão de direção aprovou formalmente as medidas de gestão dos riscos de cibersegurança tomadas para cumprir o artigo 21.º?",
    "ue.obowiazki.25": "O órgão de direção supervisiona de forma documentada a implementação dessas medidas — por exemplo, através de relatórios e revisões periódicos?",
    "ue.obowiazki.26": "Os membros do órgão de direção frequentam regularmente formação que lhes permite identificar riscos e avaliar as práticas de gestão dos riscos, e a participação é documentada?",
    "ue.obowiazki.27": "Preparação para as medidas de supervisão",
    "ue.obowiazki.28": "A entidade essencial está sujeita a supervisão ex ante e ex post; a entidade importante — apenas ex post. A autoridade pode exigir informações, provas da aplicação das políticas e resultados de auditorias.",
    "ue.obowiazki.29": "A entidade é capaz de, a pedido da autoridade, apresentar provas da aplicação das políticas de cibersegurança, incluindo os resultados de auditorias de segurança?",
    "ue.obowiazki.3": "A entidade determinou se é uma entidade essencial ou importante, com base no setor do anexo I ou II e na dimensão da empresa?",
    "ue.obowiazki.30": "A entidade é capaz de, a pedido da autoridade, disponibilizar os dados, documentos e informações necessários ao desempenho das funções de supervisão?",
    "ue.obowiazki.31": "A entidade essencial está preparada para uma auditoria de segurança realizada pela autoridade ou por um organismo independente, a expensas próprias?",
    "ue.obowiazki.4": "A entidade apresentou à autoridade competente os dados de registo: nome, endereço e dados de contacto, setor e subsetor, lista dos Estados-Membros em que presta serviços?",
    "ue.obowiazki.5": "Os dados de contacto incluem endereços de correio eletrónico, intervalos de endereços IP e números de telefone. O prazo e o portal nacionais de registo são determinados pelo direito do Estado-Membro.",
    "ue.obowiazki.6": "Existe um procedimento de atualização dos dados de registo sem demora injustificada após a sua alteração?",
    "ue.obowiazki.7": "A diretiva exige a atualização sem demora injustificada; o prazo concreto — por exemplo 14 dias na Polónia — decorre do direito nacional.",
    "ue.obowiazki.8": "Se a entidade for um prestador de DNS, um registo de nomes de domínio de topo, um prestador de serviços de computação em nuvem, de centro de dados, de CDN, de serviços geridos, um mercado em linha, um motor de pesquisa ou uma rede social — apresentou os dados adicionais do artigo 27.º, incluindo o endereço do estabelecimento principal na União?",
    "ue.obowiazki.9": "aplica-se às entidades do artigo 26.º, n.º 1",
    "ue.role.1": "Autoridade competente do Estado-Membro",
    "ue.role.10": "Serviços de centro de dados: colocação, alojamento de infraestrutura e serviços conexos.",
    "ue.role.11": "Centros de dados",
    "ue.role.12": "Entidade essencial acima do limiar de média empresa (artigo 3.º, n.º 1, alínea a)), importante na dimensão média (artigo 3.º, n.º 2). Abaixo da dimensão média — fora do âmbito de aplicação, salvo se o Estado-Membro designar a entidade ao abrigo do artigo 2.º, n.º 2, alíneas b) a e). Abrangido pelo Regulamento 2024/2690.",
    "ue.role.13": "Prestador de ponto de troca de tráfego da Internet",
    "ue.role.14": "Infraestrutura que permite a troca de tráfego entre redes independentes.",
    "ue.role.15": "Pontos de troca de tráfego da Internet",
    "ue.role.16": "Classificação por dimensão (artigo 3.º, n.º 1, alínea a), e n.º 2). O Regulamento 2024/2690 não abrange os pontos de troca de tráfego — o artigo 1.º do regulamento contém uma lista fechada de destinatários.",
    "ue.role.17": "Prestador de serviços de DNS",
    "ue.role.18": "Serviços de resolução de nomes de domínio, com exceção dos operadores de servidores de nomes de raiz.",
    "ue.role.19": "Sistema de nomes de domínio",
    "ue.role.2": "autoridade competente",
    "ue.role.20": "Entidade essencial independentemente da dimensão (artigo 3.º, n.º 1, alínea b)). Abrangido pelo Regulamento 2024/2690.",
    "ue.role.21": "Registo de nomes de domínio de topo",
    "ue.role.22": "Gestão do registo de um domínio de topo.",
    "ue.role.23": "Entidade essencial independentemente da dimensão (artigo 3.º, n.º 1, alínea b)). Adicionalmente, obrigações do artigo 28.º relativas aos dados de registo. Abrangido pelo Regulamento 2024/2690.",
    "ue.role.24": "Prestador de serviços de computação em nuvem",
    "ue.role.25": "Serviços de computação em nuvem: infraestrutura, plataforma, software como serviço.",
    "ue.role.26": "Serviços de computação em nuvem",
    "ue.role.27": "Classificação por dimensão (artigo 3.º, n.º 1, alínea a), e n.º 2). Abrangido pelo Regulamento 2024/2690.",
    "ue.role.28": "Prestador de rede de distribuição de conteúdos",
    "ue.role.29": "Rede de servidores distribuídos que entregam conteúdos e serviços aos utilizadores finais.",
    "ue.role.3": "designada pelo direito nacional; até à introdução do módulo nacional, a ferramenta não indica uma instituição concreta",
    "ue.role.30": "Redes de distribuição de conteúdos",
    "ue.role.31": "Prestador de serviços de confiança",
    "ue.role.32": "Serviços de confiança na aceção do Regulamento (UE) n.º 910/2014: assinaturas, selos, selos temporais, certificados.",
    "ue.role.33": "Serviços de confiança",
    "ue.role.34": "Abrangido pela diretiva independentemente da dimensão (artigo 2.º, n.º 2, alínea a), subalínea ii)). O prestador qualificado é entidade essencial independentemente da dimensão (artigo 3.º, n.º 1, alínea b)); o não qualificado é essencial acima do limiar de média empresa, caso contrário importante. Abrangido pelo Regulamento 2024/2690.",
    "ue.role.35": "Prestador de serviços geridos",
    "ue.role.36": "Gestão da infraestrutura de TIC do cliente: instalação, manutenção, apoio, administração de sistemas.",
    "ue.role.37": "Gestão de serviços de TIC (B2B)",
    "ue.role.38": "Serviços geridos",
    "ue.role.39": "Prestador de serviços de segurança geridos",
    "ue.role.4": "Fornecedor de redes de comunicações eletrónicas públicas ou de serviços de comunicações eletrónicas acessíveis ao público",
    "ue.role.40": "Serviços geridos de cibersegurança: monitorização, resposta a incidentes, testes, consultoria.",
    "ue.role.41": "Serviços de segurança geridos",
    "ue.role.42": "A diretiva classifica por dimensão (artigo 3.º, n.º 1, alínea a), e n.º 2). Os Estados-Membros podem tornar o limiar mais rigoroso — a Polónia considera os MSSP entidades essenciais já a partir de pequena empresa; este módulo aplica exclusivamente a regra da diretiva. Abrangido pelo Regulamento 2024/2690.",
    "ue.role.5": "Oferta de redes de comunicações eletrónicas públicas ou prestação de serviços de comunicações eletrónicas acessíveis ao público, incluindo o acesso à Internet.",
    "ue.role.6": "Infraestruturas digitais",
    "ue.role.7": "Comunicações eletrónicas",
    "ue.role.8": "Abrangido pela diretiva independentemente da dimensão (artigo 2.º, n.º 2, alínea a), subalínea i)). Uma média empresa ou maior é entidade essencial (artigo 3.º, n.º 1, alínea c)); micro e pequenas — importante (artigo 3.º, n.º 2). A lei nacional das comunicações eletrónicas pode impor obrigações adicionais — este módulo não as contém.",
    "ue.role.9": "Prestador de serviços de centro de dados",
    "ue.role.podstawaArt3b": "artigo 3.º, n.º 1, alínea b), da Diretiva (UE) 2022/2555",
    "ue.zaslepki.1": "Diretiva (UE) 2022/2555 do Parlamento Europeu e do Conselho (NIS 2)",
    "ue.zaslepki.10": "Se algumas entidades são inscritas oficiosamente é decidido pelo direito nacional.",
    "ue.zaslepki.11": "Determine se está abrangido pela diretiva",
    "ue.zaslepki.12": "Setor do anexo I ou II e dimensão da empresa. Esta parte é feita pelo perfil da entidade nesta ferramenta.",
    "ue.zaslepki.13": "Identifique a autoridade competente no seu país",
    "ue.zaslepki.14": "Cada país designa uma autoridade competente (artigo 8.º, n.º 1). Uma lista atualizada é mantida pela ENISA e pela Comissão.",
    "ue.zaslepki.15": "Apresente os dados de registo",
    "ue.zaslepki.16": "Nome, endereço e dados de contacto, setor e subsetor, países de prestação de serviços (artigo 3.º, n.º 4). Procedimento segundo o direito nacional.",
    "ue.zaslepki.17": "Atualize os dados sem demora injustificada",
    "ue.zaslepki.18": "Qualquer alteração dos dados de registo exige atualização (artigo 3.º, n.º 5).",
    "ue.zaslepki.19": "endereço e dados de contacto atuais: endereços de correio eletrónico, intervalos de endereços IP, números de telefone",
    "ue.zaslepki.2": "JO UE L 333 de 27.12.2022, p. 80",
    "ue.zaslepki.20": "setor e subsetor do anexo I ou II",
    "ue.zaslepki.21": "lista dos Estados-Membros em que a entidade presta serviços",
    "ue.zaslepki.22": "Fixado pelo direito nacional.",
    "ue.zaslepki.23": "Diretiva (UE) 2022/2555 — artigo 3.º",
    "ue.zaslepki.24": "ENISA — autoridades competentes dos Estados-Membros",
    "ue.zaslepki.25": "Diretiva (UE) 2022/2555",
    "ue.zaslepki.26": "O módulo UE não contém orientações da autoridade nacional — estas virão com o módulo de direito nacional.",
    "ue.zaslepki.27": "A obtenção automática de dados do registo só funciona para países com módulo de direito nacional. Preencha o perfil manualmente.",
    "ue.zaslepki.28": "A leitura de demonstrações financeiras só funciona para países com módulo de direito nacional. Introduza as receitas e o número de efetivos manualmente.",
    "ue.zaslepki.3": "Regulamento de Execução (UE) 2024/2690 da Comissão",
    "ue.zaslepki.4": "JO UE L, 2024/2690, 18.11.2024",
    "ue.zaslepki.5": "A Diretiva NIS 2 não contém uma camada distinta de comunicações eletrónicas. O direito nacional das comunicações eletrónicas pode impor obrigações adicionais — este módulo não as conhece.",
    "ue.zaslepki.6": "Lista de entidades essenciais e importantes",
    "ue.zaslepki.7": "Autoridade competente do Estado-Membro.",
    "ue.zaslepki.8": "A diretiva impõe aos Estados-Membros que mantenham uma lista de entidades essenciais e importantes e exijam às entidades a apresentação dos dados de registo. O portal, o procedimento e o prazo são fixados pelo direito nacional — este módulo não os conhece, porque o módulo de direito nacional para o país selecionado ainda não está pronto.",
    "ue.zaslepki.9": "Todas as entidades essenciais e importantes. O prazo é fixado pelo direito nacional.",
    "ue.zaslepki.skrotDyrektywy": "Diretiva NIS 2",
    "ue.zaslepki.skrotReg2690": "Regulamento 2024/2690",
    "xlsx.1": "{p0} – {p1} EUR",
    "xlsx.25": "Taxa de câmbio",
    "xlsx.4": "RELATÓRIO DE CONFORMIDADE COM A DIRETIVA NIS 2 (UE) 2022/2555",
    "xlsx.58": "Atividade de comunicações eletrónicas: o Regulamento (UE) 2024/2690 não se aplica. Os limiares são fixados pelo direito nacional (artigo 23.º, n.º 11, da diretiva) — o módulo comum não os conhece.",
    "xlsx.68": "A ferramenta serve para autoavaliação. Não é uma auditoria nem aconselhamento jurídico.",
    "xlsx.69": "Para as entidades não abrangidas pelo Regulamento (UE) 2024/2690, os limiares de incidente significativo são fixados pelo direito nacional (artigo 23.º, n.º 11, da diretiva).",
    "xlsx.70": "As funções indicadas no perfil constituem uma declaração. O estatuto é determinado pela atividade efetivamente exercida (artigo 3.º da Diretiva (UE) 2022/2555).",
    "xlsx.etykietaKrs": "Número de registo",
    "xlsx.etykietaNip": "Número de identificação",
    "xlsx.etykietaRegon": "Número estatístico"
});
