/* Teksty modułu ue — język: ro.
   Te same klucze co w napisy/pl.js (wersja źródłowa); wstawki {p0}, {p1}…
   pozostają bez zmian. Klucze ue.cyt.* to wzorce składania odesłań
   do przepisów w tym języku — patrz kraje/ue/cytaty.js. */
KRAJE.napisy('ue', 'ro', {
    "app.10": "Verificați lista rolurilor de mai jos — statutul este determinat de activitatea desfășurată efectiv (articolul 3 din Directiva (UE) 2022/2555), nu de înscrierea într-un registru.",
    "app.14": "Anul precedent: {p0} EUR",
    "app.15": "Cifra de afaceri a perioadei de raportare: {p0} EUR",
    "app.19": "Se interoghează registrele după numărul {p0}…",
    "app.34": " mld. EUR",
    "app.35": " mil. EUR",
    "app.36": " mii EUR",
    "app.37": "",
    "app.4": "Preluarea automată a datelor din registru nu este disponibilă pentru această țară — completați profilul manual.",
    "app.59": "Evaluare a conformității cu Directiva NIS 2 (JSON)",
    "app.68": "Pentru această țară nu există un registru din care instrumentul să poată prelua date — profilul se completează manual.",
    "app.69": "Pentru această țară nu există un registru din care instrumentul să poată prelua date. Faceți clic pentru a activa modul offline.",
    "app.73": " · contul de profit și pierdere în varianta ",
    "app.74": "<div class=\"mt-2 tekst-uwaga\">Din datele de registru nu rezultă niciun rol din sectorul infrastructurii digitale. Indicați rolurile manual mai jos.</div>",
    "app.8": "Înscrierea în registrul furnizorilor de comunicații electronice a fost confirmată",
    "app.progDostawcy": "",
    "app.przyklad.adres": "Str. Exemplului nr. 1, 010000 Oraș",
    "app.przyklad.forma": "Societate cu răspundere limitată",
    "app.przyklad.nazwa": "Operator Exemplu S.R.L.",
    "app.statusVat": " · statut TVA: ",
    "dashboard.1": "Pe baza rolurilor și a dimensiunii declarate, entitatea nu este nici esențială, nici importantă în sensul articolului 3 din Directiva (UE) 2022/2555. Verificați profilul dacă rezultatul nu corespunde așteptărilor.",
    "dashboard.113": "Întrebări frecvente",
    "dashboard.12": "— {p0}; termenul de transpunere în dreptul național a expirat la {p2}",
    "dashboard.123": "Directiva NIS 2",
    "dashboard.30": "Lista entităților esențiale și importante",
    "dashboard.4": "— direct aplicabil de la {p0} în toate statele membre, fără transpunere",
    "dashboard.42": "Varianta în sumă fixă: {p0}",
    "dashboard.45": "Criteriile de la articolul 32 alineatul (7) din directivă:",
    "dashboard.46": "Total",
    "dashboard.49": "Entitatea desfășoară activitate de comunicații electronice — răspunderea persoanei de conducere este stabilită de dreptul național",
    "dashboard.50": "",
    "dashboard.51": "",
    "dashboard.53": "Penalitate pentru întârzierea executării unei decizii: de la {p0} EUR la {p1} EUR pe zi ({p2})",
    "dashboard.54": "Caz calificat: până la {p0} EUR ({p1})",
    "dashboard.57": "({p0}). De când autoritatea națională poate aplica amenzi stabilește legea de transpunere a directivei — acest modul nu o cunoaște. Obligațiile de implementare decurg din dreptul național de la intrarea sa în vigoare.",
    "dashboard.65": "({p0}). De când autoritatea națională poate aplica amenzi stabilește legea de transpunere a directivei — acest modul nu o cunoaște. Riscul financiar nu este așadar datat aici, dar obligațiile de implementare decurg din dreptul național de la intrarea sa în vigoare.",
    "dashboard.83": "Activitate de comunicații electronice — pragurile sunt stabilite de dreptul național.",
    "dashboard.84": "Regulamentul (UE) 2024/2690 nu se aplică furnizorilor de rețele și servicii publice de comunicații electronice. Pentru aceștia, pragurile incidentului semnificativ sunt stabilite de dreptul național (articolul 23 alineatul (11) din directivă) — acest modul nu le cunoaște, deci nu indică valori numerice.",
    "dashboard.terminRejestracji": "Termenul de depunere a datelor de înregistrare este stabilit de dreptul național (articolul 3 alineatul (4) din directivă). Furnizorii de la articolul 27 alineatul (1) — servicii DNS, registre TLD, servicii cloud, centre de date, rețele de distribuție a conținutului, servicii gestionate și servicii de securitate gestionate — transmit datele registrului ENISA: inițial până la 17 ianuarie 2025, iar orice modificare fără întârzieri nejustificate.",
    "html.1": "ITORO — Evaluarea conformității cu Directiva NIS 2 (UE) 2022/2555",
    "html.10": "Evaluarea conformității cu Directiva NIS 2 — modul comun",
    "html.100": "Citirea situației financiare funcționează doar pentru țările cu modul de drept național. Pentru această țară introduceți manual <strong>cifra de afaceri</strong> a exercițiului financiar — de ea depinde cuantumul amenzii.",
    "html.102": "Preluarea automată a datelor din registre funcționează doar pentru țările cu modul de drept național. Rolurile și dimensiunea întreprinderii le indicați manual.",
    "html.11": "Directiva (UE) 2022/2555 (NIS 2) necesită transpunere în dreptul național. Evaluarea acoperă obligațiile care decurg direct din directivă și Regulamentul de punere în aplicare (UE) 2024/2690 al Comisiei, direct aplicabil — în măsura în care privesc entitatea.",
    "html.23": "cifra de afaceri și dimensiunea le introduceți manual — modulul comun nu interoghează registrele naționale",
    "html.33": "Directiva (UE) 2022/2555 a Parlamentului European și a Consiliului din 14 decembrie 2022 (NIS 2)",
    "html.33a": "{p0} — actul național de transpunere a directivei; cerințele sale nu sunt încă evaluate în acest modul",
    "html.33b": "statul nu a adoptat încă un act de transpunere — evaluarea urmează dreptul Uniunii",
    "html.35": "obligațiile organului de conducere — articolul 20 din directivă",
    "html.36": "Instrumentul servește autoevaluării. Nu este un audit și nici o opinie juridică.",
    "html.40": "modulul comun nu realizează nicio conexiune de ieșire — nu interoghează registre",
    "html.59": "Situații financiare",
    "html.60": "Citirea situației financiare este disponibilă doar pentru țările cu modul de drept național. Pentru această țară introduceți manual cifra de afaceri și numărul de angajați.",
    "html.62": "Căutare în registru",
    "html.63": "registrele comerciale sunt naționale — modulul comun nu le cunoaște",
    "html.64": "rolurile și dimensiunea întreprinderii le indicați manual",
    "html.66": "Numărul de identificare al entității",
    "html.68": "Preluarea automată a datelor din registre funcționează doar pentru țările cu modul de drept național.",
    "html.76": "Cifra de afaceri anuală (EUR)",
    "html.78": "Cifra de afaceri din activitatea de comunicații electronice (EUR)",
    "html.79": "Câmpul privește furnizorii de rețele sau servicii publice de comunicații electronice. Pragurile naționale sunt stabilite de dreptul statului membru.",
    "html.80": "Remunerația lunară a conducătorului (EUR)",
    "html.82": "Curs valutar",
    "html.83": "Plafoanele amenzilor din directivă sunt exprimate în euro. Conversia în moneda națională și cursul sunt stabilite de dreptul național — aici sumele sunt indicate în euro, fără conversie.",
    "html.84": "Statutul rezultă exclusiv din agregarea datelor întreprinderilor afiliate, iar sistemul informatic al entității este independent (considerentul 16 al directivei — aplicarea este decisă de dreptul național)",
    "html.85": "Entitatea desfășoară activități în domeniul securității naționale, al securității publice, al apărării sau al asigurării respectării legii (articolul 2 alineatul (7) din directivă)",
    "html.91": "Evaluarea conformității cu Directiva (UE) 2022/2555 a Parlamentului European și a Consiliului (NIS 2) și cu Regulamentul de punere în aplicare (UE) 2024/2690 al Comisiei — modul comun pentru țările al căror modul de drept național nu este încă gata.",
    "html.94": "dacă entitatea este <strong>esențială</strong>, <strong>importantă</strong> sau în afara domeniului directivei",
    "html.daneZeSprawozdania": "denumire, număr de identificare, adresa sediului",
    "html.rejestrMozliwy": "Registrul {p0} este public și gratuit — citirea lui poate fi adăugată; primim pull request-uri (vezi README).",
    "html.tytulNaglowka": "Evaluarea conformității cu Directiva NIS 2",
    "html.zrodlaRecznie": "Acest modul nu cunoaște registrele statului dumneavoastră — completați profilul manual. Cifra de afaceri anuală determină plafonul amenzii, deci introduceți-o cu precizie.",
    "klasyfikacja.10": "articolul 3 alineatul (1) litera (c) din Directiva (UE) 2022/2555 (furnizor de rețele publice de comunicații electronice sau de servicii de comunicații electronice destinate publicului care este cel puțin întreprindere mijlocie)",
    "klasyfikacja.11": "articolul 3 alineatul (2) coroborat cu articolul 2 alineatul (2) litera (a) punctul (i) din Directiva (UE) 2022/2555 (furnizor de rețele sau servicii publice de comunicații electronice care este microîntreprindere sau întreprindere mică)",
    "klasyfikacja.12": "articolul 3 alineatul (1) litera (a) din Directiva (UE) 2022/2555 (furnizor de servicii de securitate gestionate care depășește plafoanele întreprinderii mijlocii)",
    "klasyfikacja.13": "Microîntreprinderile și întreprinderile mici nu intră sub incidența directivei în temeiul acestui rol (articolul 2 alineatul (1), a contrario).",
    "klasyfikacja.15": "articolul 3 alineatul (1) litera (b) din Directiva (UE) 2022/2555 (prestator calificat de servicii de încredere) — indiferent de dimensiunea întreprinderii",
    "klasyfikacja.16": "articolul 3 alineatul (2) coroborat cu articolul 2 alineatul (2) litera (a) punctul (ii) din Directiva (UE) 2022/2555 (prestator necalificat de servicii de încredere care este microîntreprindere, întreprindere mică sau mijlocie)",
    "klasyfikacja.18": "articolul 3 alineatul (2) din Directiva (UE) 2022/2555 (entitate a administrației publice la nivel regional, dacă statul membru prevede astfel — articolul 2 alineatul (2) litera (f) punctul (ii))",
    "klasyfikacja.19": "articolul 3 alineatul (1) litera (f) din Directiva (UE) 2022/2555 (entitate a administrației publice la nivel central — articolul 2 alineatul (2) litera (f) punctul (i))",
    "klasyfikacja.2": "Supraveghere ex ante și ex post (articolul 32 din Directiva (UE) 2022/2555).",
    "klasyfikacja.20": "articolul 3 alineatul (2) din Directiva (UE) 2022/2555 (entitate a administrației publice la nivel regional — articolul 2 alineatul (2) litera (f) punctul (ii))",
    "klasyfikacja.21": "Întinderea obligațiilor entităților administrației publice la nivel local este stabilită de dreptul național (articolul 2 alineatul (5) litera (a) din directivă).",
    "klasyfikacja.22": "Un stat membru poate exonera entitățile care desfășoară activități în domeniul securității naționale, al securității publice, al apărării sau al asigurării respectării legii (articolul 2 alineatul (7) din directivă). Exonerarea nu operează de la sine — verificați rezultatul evaluării cu dreptul național.",
    "klasyfikacja.23": "Entitatea îndeplinește criteriile atât ale entității esențiale, cât și ale celei importante. Este entitate esențială (articolul 3 alineatul (1) din directivă), iar cerințele mai stricte se aplică întregii activități acoperite de directivă.",
    "klasyfikacja.25": "Entitatea este esențială, deci i se aplică catalogul complet de măsuri de la articolul 21 alineatul (2) din directivă și supravegherea ex ante și ex post — evaluarea acoperă setul complet de întrebări.",
    "klasyfikacja.26": "Ca entitate importantă, vă supuneți aceluiași catalog de măsuri de la articolul 21 alineatul (2), dar numai supravegherii ex post (articolul 33). Plafonul amenzii este mai mic: 7 mil. EUR sau 1,4 % din cifra de afaceri (articolul 34 alineatul (5)). Facilități pentru entitățile publice pot fi introduse de dreptul național — acest modul nu le cunoaște.",
    "klasyfikacja.28": "Obligațiile entităților administrației publice decurg din articolul 2 alineatul (2) litera (f) din directivă; întinderea lor exactă, inclusiv pentru nivelul local și instituțiile de învățământ, este stabilită de dreptul național (articolul 2 alineatul (5)).",
    "klasyfikacja.29": "S-a declarat că statutul entității rezultă exclusiv din agregarea datelor întreprinderilor afiliate sau partenere și că sistemul informatic al entității este independent. Directiva admite o astfel de excludere (considerentul 16), dar decizia revine dreptului național — modulul adoptă excluderea, care trebuie verificată cu dreptul statului membru și documentată.",
    "klasyfikacja.4": "Supraveghere exclusiv ex post — în cazul unor dovezi, indicii sau informații privind o încălcare (articolul 33 din Directiva (UE) 2022/2555).",
    "klasyfikacja.5": "În afara domeniului de aplicare al directivei",
    "klasyfikacja.6": "Nicio obligație care să decurgă din Directiva (UE) 2022/2555 pentru rolul indicat.",
    "klasyfikacja.7": "articolul 3 alineatul (1) litera (a) din Directiva (UE) 2022/2555 (entitate de un tip menționat în anexa I care depășește plafoanele întreprinderii mijlocii)",
    "klasyfikacja.8": "articolul 3 alineatul (2) din Directiva (UE) 2022/2555 (entitate de un tip menționat în anexa I care îndeplinește criteriile întreprinderii mijlocii)",
    "klasyfikacja.9": "Microîntreprinderile și întreprinderile mici nu intră sub incidența directivei în temeiul acestui rol (articolul 2 alineatul (1), a contrario).",
    "kreator.10": "Introduceți manual cifra de afaceri a anului precedent.",
    "kreator.35": "<span class=\"text-secondary\">Citirea situațiilor financiare nu este disponibilă pentru această țară.</span>",
    "kreator.37": "Citirea situațiilor financiare nu este disponibilă pentru această țară — introduceți cifra de afaceri manual.",
    "kreator.56": "Da — regulamentul UE se aplică direct de la 7 noiembrie 2024 în toate statele membre și nu are perioadă de tranziție. Temeiul său este",
    "kreator.57": ", care a împuternicit Comisia să stabilească cerințele tehnice și metodologice pentru furnizorii de la articolul 3 alineatul (1) din regulament. Termenul de transpunere a directivei a expirat la",
    "kreator.58": ", iar de când autoritatea națională poate aplica amenzi stabilește dreptul național. Cerințele tehnice din anexă (secțiunile 6 și 9-13) sunt obligatorii în forma actuală — nu așteaptă detalieri. Se poate deroga doar de la cerințele însoțite de formula „după caz”, și numai documentând justificarea.",
    "kreator.9": "Situații financiare →",
    "kreator.przepisReg2690": "articolul 21 alineatul (5) din Directiva (UE) 2022/2555",
    "kreator.terminReg2690": "17 octombrie 2024",
    "punktacja.10": "Entități publice",
    "punktacja.4": "Directiva NIS 2 — articolul 21",
    "punktacja.5": "Directiva NIS 2 — obligații formale",
    "punktacja.8": "Comunicații electronice",
    "punktacja.9": "Directiva NIS 2 — entități publice",
    "punktacja.skrotKsc": "NIS 2",
    "punktacja.skrotPke": "telecom",
    "ue.cyt.akapit": "al {p0} paragraf",
    "ue.cyt.art": "articolul {p0}",
    "ue.cyt.drugi": "doilea",
    "ue.cyt.dyr": "{p0} din Directiva (UE) 2022/2555",
    "ue.cyt.i": "și",
    "ue.cyt.laczenie": " ",
    "ue.cyt.lit": "litera ({p0})",
    "ue.cyt.litery": "",
    "ue.cyt.pkt": "punctul {p0}",
    "ue.cyt.rozdzielacz": "; ",
    "ue.cyt.rozp": "{p0} din Regulamentul (UE) 2024/2690",
    "ue.cyt.ust": "alineatul ({p0})",
    "ue.katalog.1": "Politici de analiză a riscurilor și de securitate a sistemelor informatice",
    "ue.katalog.10": "Gestionarea incidentelor",
    "ue.katalog.11": "Gestionarea incidentelor cuprinde acțiunile și procedurile menite să prevină, să detecteze, să analizeze și să limiteze un incident, să răspundă la acesta și să restabilească funcționarea normală (articolul 6 punctul 8).",
    "ue.katalog.12": "Există o procedură documentată de gestionare a incidentelor care acoperă detectarea, analiza, limitarea, răspunsul și restabilirea?",
    "ue.katalog.13": "ISO/IEC 27001 A.5.24–A.5.26",
    "ue.katalog.14": "Permite procedura respectarea termenelor de notificare a unui incident semnificativ: avertizare timpurie în 24 de ore, notificare în 72 de ore, raport final într-o lună?",
    "ue.katalog.15": "ISO/IEC 27001 A.5.24",
    "ue.katalog.16": "Are entitatea criterii pentru a considera un incident semnificativ, conforme cu articolul 23 alineatul (3): perturbări operaționale grave sau pierderi financiare ori prejudicii considerabile aduse altor persoane?",
    "ue.katalog.17": "ISO/IEC 27001 A.5.25",
    "ue.katalog.18": "Sunt incidentele înregistrate, iar concluziile gestionării lor folosite pentru îmbunătățirea măsurilor?",
    "ue.katalog.19": "ISO/IEC 27001 A.5.27",
    "ue.katalog.2": "Măsurile se bazează pe o abordare care ia în considerare toate pericolele (articolul 21 alineatul (2)). Proporționalitatea lor se evaluează ținând seama de gradul de expunere, de dimensiunea entității, de probabilitatea incidentelor și de gravitatea lor (articolul 21 alineatul (1) al doilea paragraf).",
    "ue.katalog.20": "Continuitatea activității și gestionarea crizelor",
    "ue.katalog.21": "Continuitatea activității, precum gestionarea copiilor de rezervă și recuperarea în caz de dezastru, și gestionarea crizelor.",
    "ue.katalog.22": "Există un plan de continuitate a activității care acoperă recuperarea după un dezastru?",
    "ue.katalog.23": "ISO/IEC 27001 A.5.29–A.5.30",
    "ue.katalog.24": "Sunt copiile de rezervă realizate, protejate și testate în privința posibilității de restaurare?",
    "ue.katalog.25": "ISO/IEC 27001 A.8.13",
    "ue.katalog.26": "Are entitatea proceduri de gestionare a crizelor cu roluri și canale de comunicare definite?",
    "ue.katalog.27": "ISO/IEC 27001 A.5.29",
    "ue.katalog.28": "Sunt planurile de continuitate și de recuperare testate periodic, iar rezultatele documentate?",
    "ue.katalog.29": "ISO/IEC 27001 A.5.30",
    "ue.katalog.3": "Are entitatea o politică documentată de analiză a riscurilor și de securitate a sistemelor informatice, aprobată de organul de conducere?",
    "ue.katalog.30": "Securitatea lanțului de aprovizionare",
    "ue.katalog.31": "Securitatea lanțului de aprovizionare, inclusiv aspectele legate de securitate privind relațiile dintre entitate și furnizorii sau prestatorii săi direcți. Entitatea ține seama de vulnerabilitățile specifice fiecărui furnizor și de calitatea generală a produselor și a practicilor sale de securitate cibernetică (articolul 21 alineatul (3)).",
    "ue.katalog.32": "Ține entitatea o listă a furnizorilor și prestatorilor direcți, cu o evaluare a importanței lor pentru securitatea rețelelor și a sistemelor?",
    "ue.katalog.33": "ISO/IEC 27001 A.5.19",
    "ue.katalog.34": "La alegerea măsurilor față de furnizori se ține seama de vulnerabilitățile specifice fiecăruia și de calitatea practicilor lor de securitate cibernetică și de dezvoltare securizată?",
    "ue.katalog.35": "ISO/IEC 27001 A.5.19, A.5.21",
    "ue.katalog.36": "Conțin contractele cu furnizorii cerințe de securitate și obligația de a informa despre incidente și vulnerabilități?",
    "ue.katalog.37": "ISO/IEC 27001 A.5.20",
    "ue.katalog.38": "Ține entitatea seama de rezultatele evaluărilor coordonate ale riscurilor de securitate ale lanțurilor de aprovizionare critice menționate la articolul 22?",
    "ue.katalog.39": "ISO/IEC 27001 A.5.21",
    "ue.katalog.4": "ISO/IEC 27001 punctele 5.2, 6.1.2",
    "ue.katalog.40": "Securitatea la achiziționarea, dezvoltarea și întreținerea sistemelor",
    "ue.katalog.41": "Securitatea în achiziționarea, dezvoltarea și întreținerea rețelelor și sistemelor informatice, inclusiv gestionarea și divulgarea vulnerabilităților.",
    "ue.katalog.42": "Sunt cerințele de securitate definite înainte de achiziționarea sau începerea dezvoltării unui sistem și verificate înainte de punerea în funcțiune?",
    "ue.katalog.43": "ISO/IEC 27001 A.8.25–A.8.29",
    "ue.katalog.44": "Există un proces de gestionare a vulnerabilităților: identificare, evaluare, remediere într-un termen stabilit?",
    "ue.katalog.45": "ISO/IEC 27001 A.8.8",
    "ue.katalog.46": "Are entitatea o procedură de divulgare a vulnerabilităților, inclusiv un canal pentru primirea semnalărilor de la terți?",
    "ue.katalog.47": "Trec modificările sistemelor printr-un proces controlat de gestionare a schimbărilor, cu evaluarea impactului asupra securității?",
    "ue.katalog.48": "ISO/IEC 27001 A.8.32",
    "ue.katalog.49": "Evaluarea eficacității măsurilor",
    "ue.katalog.5": "Acoperă analiza riscurilor toate pericolele pentru rețelele și sistemele informatice și pentru mediul lor fizic, nu doar amenințările cibernetice?",
    "ue.katalog.50": "Politici și proceduri pentru evaluarea eficacității măsurilor de gestionare a riscurilor în materie de securitate cibernetică.",
    "ue.katalog.51": "Există o politică documentată de evaluare a eficacității măsurilor, care definește domeniul, frecvența și metodele?",
    "ue.katalog.52": "ISO/IEC 27001 punctul 9.1",
    "ue.katalog.53": "Sunt evaluările de eficacitate realizate periodic, iar rezultatele transmise organului de conducere?",
    "ue.katalog.54": "ISO/IEC 27001 punctele 9.2–9.3",
    "ue.katalog.55": "Duc slăbiciunile detectate la acțiuni corective documentate, cu responsabil și termen?",
    "ue.katalog.56": "ISO/IEC 27001 punctul 10.1",
    "ue.katalog.57": "Igiena cibernetică și instruirea",
    "ue.katalog.58": "Practici de bază de igienă cibernetică și instruire în domeniul securității cibernetice. Membrii organului de conducere urmează instruiri periodice (articolul 20 alineatul (2)).",
    "ue.katalog.59": "Aplică entitatea practici de bază de igienă cibernetică: actualizări, gestionarea parolelor, limitarea privilegiilor, protecție împotriva programelor malware?",
    "ue.katalog.6": "ISO/IEC 27001 punctul 6.1.2",
    "ue.katalog.60": "ISO/IEC 27001 A.8.7, A.8.8",
    "ue.katalog.61": "Urmează angajații instruiri de securitate cibernetică adaptate rolului lor, iar participarea este documentată?",
    "ue.katalog.62": "ISO/IEC 27001 A.6.3",
    "ue.katalog.63": "Urmează membrii organului de conducere instruiri periodice care le permit să identifice riscurile și să evalueze practicile de gestionare a riscurilor?",
    "ue.katalog.64": "ISO/IEC 27001 punctul 7.2",
    "ue.katalog.65": "Criptografie și criptare",
    "ue.katalog.66": "Politici și proceduri privind utilizarea criptografiei și, după caz, a criptării.",
    "ue.katalog.67": "Există o politică de criptografie care stabilește ce date și canale sunt criptate și cu ce algoritmi?",
    "ue.katalog.68": "ISO/IEC 27001 A.8.24",
    "ue.katalog.69": "Sunt cheile criptografice gestionate pe întregul ciclu de viață: generare, distribuire, stocare, rotație, retragere?",
    "ue.katalog.7": "Ține seama alegerea măsurilor de stadiul tehnicii, de standardele europene și internaționale relevante și de costul implementării?",
    "ue.katalog.70": "Resurse umane, controlul accesului și gestionarea activelor",
    "ue.katalog.71": "Securitatea resurselor umane, politici de control al accesului și gestionarea activelor.",
    "ue.katalog.72": "Ține entitatea un inventar actualizat al activelor, cu proprietari desemnați și clasificare?",
    "ue.katalog.73": "ISO/IEC 27001 A.5.9, A.5.12",
    "ue.katalog.74": "Există o politică de control al accesului bazată pe principiul privilegiului minim, cu revizuirea periodică a drepturilor?",
    "ue.katalog.75": "ISO/IEC 27001 A.5.15, A.5.18",
    "ue.katalog.76": "Se aplică proceduri de securitate la angajare, la schimbarea postului și la plecarea angajatului, inclusiv retragerea drepturilor și returnarea activelor?",
    "ue.katalog.77": "ISO/IEC 27001 A.6.1–A.6.5",
    "ue.katalog.78": "Este accesul privilegiat limitat, jurnalizat și revizuit?",
    "ue.katalog.79": "ISO/IEC 27001 A.8.2",
    "ue.katalog.8": "ISO/IEC 27001 punctul 6.1.3",
    "ue.katalog.80": "Autentificare multifactor și comunicații securizate",
    "ue.katalog.81": "După caz — autentificare multifactor sau continuă, comunicații vocale, video și text securizate și sisteme securizate de comunicații de urgență în cadrul entității.",
    "ue.katalog.82": "Este utilizată autentificarea multifactor sau continuă acolo unde analiza riscurilor o justifică, în special pentru accesul de la distanță și conturile privilegiate?",
    "ue.katalog.83": "ISO/IEC 27001 A.8.5",
    "ue.katalog.84": "Sunt securizate comunicațiile vocale, video și text utilizate în scop profesional?",
    "ue.katalog.85": "ISO/IEC 27001 A.8.20",
    "ue.katalog.86": "Are entitatea un sistem securizat de comunicații interne de urgență, independent de infrastructura principală?",
    "ue.katalog.9": "Este nivelul de securitate documentat ca fiind adecvat riscului existent, cu o justificare care ține seama de dimensiunea entității și de impactul social și economic al incidentelor?",
    "ue.kierownictwo.1": "Organul de conducere al unei entități esențiale sau importante — într-o societate de capitaluri, consiliul de administrație. Directiva nu definește noțiunea; întinderea ei într-o anumită țară decurge din dreptul național.",
    "ue.kierownictwo.10": "Stabilirea statutului entității și asigurarea înregistrării",
    "ue.kierownictwo.11": "Stabilirea dacă entitatea este esențială sau importantă și depunerea datelor de înregistrare la autoritatea competentă. Procedura și termenul sunt stabilite de dreptul național.",
    "ue.kierownictwo.12": "Implementarea analizei riscurilor și a politicii de securitate",
    "ue.kierownictwo.13": "Măsuri bazate pe o abordare care ia în considerare toate pericolele, proporționale cu expunerea, dimensiunea entității și gravitatea incidentelor.",
    "ue.kierownictwo.14": "Punerea în funcțiune a gestionării și notificării incidentelor",
    "ue.kierownictwo.15": "Procedură de gestionare a incidentelor și capacitatea de a respecta termenele de 24 de ore, 72 de ore și o lună.",
    "ue.kierownictwo.16": "24 h / 72 h / o lună de la detectare",
    "ue.kierownictwo.17": "Asigurarea continuității activității",
    "ue.kierownictwo.18": "Plan de continuitate, copii de rezervă, recuperare după dezastru, gestionarea crizelor.",
    "ue.kierownictwo.19": "Punerea în ordine a lanțului de aprovizionare",
    "ue.kierownictwo.2": "Răspunderea organului de conducere nu aduce atingere normelor naționale privind răspunderea instituțiilor publice și a funcționarilor (articolul 20 alineatul (1) al doilea paragraf).",
    "ue.kierownictwo.20": "Lista furnizorilor, evaluarea vulnerabilităților și practicilor lor, cerințe de securitate în contracte.",
    "ue.kierownictwo.21": "Implementarea controlului accesului și a gestionării activelor",
    "ue.kierownictwo.22": "Inventarul activelor, principiul privilegiului minim, revizuiri ale drepturilor, autentificare multifactor acolo unde riscul o justifică.",
    "ue.kierownictwo.23": "Măsurarea eficacității măsurilor",
    "ue.kierownictwo.24": "Politică și proceduri de evaluare a eficacității, revizuiri periodice, acțiuni corective.",
    "ue.kierownictwo.25": "Aprobare",
    "ue.kierownictwo.26": "măsurile de gestionare a riscurilor în materie de securitate cibernetică (articolul 20 alineatul (1))",
    "ue.kierownictwo.27": "politica de analiză a riscurilor și de securitate a sistemelor",
    "ue.kierownictwo.28": "bugetul și rolurile în implementare",
    "ue.kierownictwo.29": "Supraveghere",
    "ue.kierownictwo.3": "Dacă încredințarea obligațiilor altei persoane exclude răspunderea decide dreptul național. În Polonia nu o exclude (articolul 8c alineatul (3) din Legea privind sistemul național de securitate cibernetică).",
    "ue.kierownictwo.30": "implementarea măsurilor aprobate (articolul 20 alineatul (1))",
    "ue.kierownictwo.31": "rezultatele evaluării eficacității (articolul 21 alineatul (2) litera (f))",
    "ue.kierownictwo.32": "respectarea termenelor de notificare a incidentelor (articolul 23)",
    "ue.kierownictwo.33": "Documentare",
    "ue.kierownictwo.34": "deciziile de aprobare și revizuirile",
    "ue.kierownictwo.35": "participarea la instruiri (articolul 20 alineatul (2))",
    "ue.kierownictwo.36": "Membru al organului de conducere",
    "ue.kierownictwo.37": "aprobarea măsurilor, supraveghere, decizii, buget",
    "ue.kierownictwo.38": "Manager de proiect",
    "ue.kierownictwo.39": "coordonarea implementării, calendar, stadiu și dovezi",
    "ue.kierownictwo.4": "Aprobarea măsurilor de gestionare a riscurilor în materie de securitate cibernetică",
    "ue.kierownictwo.40": "IT / securitate cibernetică",
    "ue.kierownictwo.41": "analiza riscurilor, măsuri tehnice, gestionarea incidentelor",
    "ue.kierownictwo.42": "Departamentul juridic / conformitate",
    "ue.kierownictwo.5": "Organul de conducere aprobă măsurile adoptate pentru asigurarea conformității cu articolul 21. Este o decizie a organului, nu a departamentului IT — fără ea măsurile nu au temei.",
    "ue.kierownictwo.6": "Supravegherea implementării măsurilor",
    "ue.kierownictwo.7": "Supravegherea implementării este o obligație a organului de conducere. Executarea poate fi încredințată, supravegherea nu.",
    "ue.kierownictwo.8": "Participarea la instruiri periodice",
    "ue.kierownictwo.9": "Membrii organului de conducere urmează instruiri periodice pentru a dobândi cunoștințe suficiente pentru a identifica riscurile și a evalua practicile de gestionare a riscurilor și impactul lor asupra serviciilor entității.",
    "ue.kierownictwo.daneRejestracyjne": "datele de înregistrare și actualizarea lor (articolul 3 alineatele (4)-(5))",
    "ue.meta.1": "Prevalează varianta procentuală: {p0} % din cifra de afaceri depășește {p1} mil. EUR.",
    "ue.meta.10": "Directiva nu impune obligații direct întreprinderilor — o face legea națională, pe care statul membru trebuia să o adopte până la 17 octombrie 2024. Acest modul prezintă cerințele în formularea directivei, deoarece modulul de drept național pentru țara selectată nu este încă gata sau țara nu a transpus directiva.",
    "ue.meta.11": "Obligații din directivă",
    "ue.meta.12": "Lista entităților — până la 17 aprilie 2025",
    "ue.meta.13": "Statele membre trebuiau să stabilească o listă a entităților esențiale și importante până la 17 aprilie 2025 și să ceară entităților să depună datele de înregistrare.",
    "ue.meta.14": "Regulamentul (UE) 2024/2690",
    "ue.meta.15": "Direct aplicabil de la 7 noiembrie 2024",
    "ue.meta.16": "Regulamentul de punere în aplicare se aplică direct în toate statele membre, indiferent de stadiul transpunerii directivei. Privește entitățile enumerate la articolul 1: DNS, TLD, cloud, centre de date, rețele de distribuție a conținutului, servicii gestionate și servicii de încredere.",
    "ue.meta.17": "articolul 16 din Regulamentul (UE) 2024/2690",
    "ue.meta.18": "Cel puțin 10 000 000 EUR sau cel puțin 2 % din cifra de afaceri mondială totală anuală a întreprinderii în exercițiul financiar precedent — se aplică valoarea mai mare. Este un plafon minim: dreptul național îl poate majora.",
    "ue.meta.19": "Cel puțin 7 000 000 EUR sau 1,4 % din cifra de afaceri mondială totală anuală — se aplică valoarea mai mare. Plafon minim.",
    "ue.meta.2": "Prevalează suma fixă: {p0} mil. EUR depășește {p1} % din cifra de afaceri.",
    "ue.meta.20": "Directiva nu prevede o amendă distinctă pentru încălcarea calificată — este o construcție a dreptului național al unor state.",
    "ue.meta.21": "Statele membre pot prevedea penalități cu titlu cominatoriu pentru a impune încetarea încălcării. Cuantumul este stabilit de dreptul național.",
    "ue.meta.22": "Organul de conducere aprobă măsurile de gestionare a riscurilor, supraveghează implementarea lor și poate fi tras la răspundere pentru încălcarea articolului 21. Regulile și întinderea acestei răspunderi sunt stabilite de dreptul național.",
    "ue.meta.23": "Organul de conducere aprobă măsurile de gestionare a riscurilor în materie de securitate cibernetică (articolul 20 alineatul (1)).",
    "ue.meta.24": "Organul de conducere supraveghează implementarea acestor măsuri (articolul 20 alineatul (1)).",
    "ue.meta.25": "Membrii organului de conducere urmează instruiri periodice (articolul 20 alineatul (2)).",
    "ue.meta.26": "Față de o entitate esențială, autoritatea poate solicita interzicerea temporară a exercitării funcțiilor de conducere (articolul 32 alineatul (5) litera (b)).",
    "ue.meta.27": "Plafonul minim este stabilit de directivă",
    "ue.meta.28": "Se compară două valori: o sumă fixă în euro și un procent din cifra de afaceri mondială totală anuală a întreprinderii în exercițiul financiar precedent. Cea mai mare este limita superioară pe care statul membru trebuie să o prevadă cel puțin. Dreptul național o poate majora.",
    "ue.meta.29": "Cuantumul în limita plafonului este stabilit de autoritatea națională",
    "ue.meta.3": "Plafonul din directivă depășește de {p0} ori cifra de afaceri anuală a entității. Articolul 34 alineatul (1) cere ca amenda să fie proporțională cu circumstanțele fiecărui caz — este o limită superioară, nu o amendă așteptată.",
    "ue.meta.30": "Amenda trebuie să fie eficace, proporțională și disuasivă în funcție de circumstanțele fiecărui caz. Autoritatea ține seama cel puțin de criteriile de la articolul 32 alineatul (7): gravitatea și durata încălcării, încălcările anterioare, prejudiciile, intenția, măsurile de remediere și cooperarea.",
    "ue.meta.31": "Plafonul poate depăși de mai multe ori cifra de afaceri anuală — este o limită superioară, nu o sumă așteptată. Minimele naționale, penalitățile cominatorii și modul de stabilire sunt determinate de legea statului membru.",
    "ue.meta.32": "La luarea deciziei de aplicare a unei amenzi administrative și la stabilirea cuantumului acesteia, în fiecare caz în parte se ține seama în mod corespunzător cel puțin de elementele enumerate la articolul 32 alineatul (7).",
    "ue.meta.33": "gravitatea încălcării și importanța dispozițiilor încălcate — se consideră grave în orice caz: încălcările repetate, nenotificarea sau neremedierea incidentelor semnificative, neremedierea deficiențelor contrar instrucțiunilor obligatorii, obstrucționarea auditurilor sau a monitorizării, furnizarea de informații false sau grav inexacte",
    "ue.meta.34": "încălcările anterioare relevante ale entității",
    "ue.meta.35": "prejudiciile materiale și morale cauzate, inclusiv pierderile financiare, impactul asupra altor servicii și numărul de utilizatori afectați",
    "ue.meta.36": "caracterul intenționat sau din neglijență al faptei",
    "ue.meta.37": "măsurile luate pentru a preveni sau a limita prejudiciile",
    "ue.meta.38": "respectarea codurilor de conduită aprobate sau a mecanismelor de certificare",
    "ue.meta.39": "gradul de cooperare cu autoritățile competente",
    "ue.meta.4": "Directiva (UE) 2022/2555 a Parlamentului European și a Consiliului (NIS 2)",
    "ue.meta.40": "Directiva nu prevede expres renunțarea la amendă — dacă și când este posibilă decide dreptul național.",
    "ue.meta.41": "De la această dată statele membre trebuie să aplice dispozițiile naționale de transpunere a directivei. Data concretă de la care autoritatea poate aplica o amendă decurge din dreptul național.",
    "ue.meta.42": "Intrarea în vigoare a Directivei NIS 2",
    "ue.meta.43": "În a douăzecea zi de la publicarea în Jurnalul Oficial.",
    "ue.meta.44": "Termenul de transpunere a directivei",
    "ue.meta.45": "Până la această dată statele membre trebuiau să adopte și să publice dispozițiile naționale.",
    "ue.meta.46": "Aplicarea dispozițiilor naționale și abrogarea NIS 1",
    "ue.meta.47": "De la această dată statele aplică dispozițiile de transpunere; Directiva (UE) 2016/1148 se abrogă.",
    "ue.meta.48": "Aplicarea Regulamentului (UE) 2024/2690",
    "ue.meta.49": "Regulamentul de punere în aplicare se aplică direct din a douăzecea zi de la publicare.",
    "ue.meta.5": "JO UE L 333, 27.12.2022",
    "ue.meta.50": "Lista entităților esențiale și importante",
    "ue.meta.51": "Până la această dată statele membre stabilesc lista; entitățile depun autorităților datele de înregistrare.",
    "ue.meta.52": "Prima revizuire a directivei de către Comisie",
    "ue.meta.53": "Comisia revizuiește funcționarea directivei și prezintă un raport.",
    "ue.meta.54": "Avertizare timpurie privind un incident semnificativ",
    "ue.meta.55": "24 de ore de la luarea la cunoștință",
    "ue.meta.56": "Notificarea unui incident semnificativ",
    "ue.meta.57": "72 de ore de la luarea la cunoștință",
    "ue.meta.58": "Raport final",
    "ue.meta.59": "o lună de la notificarea incidentului",
    "ue.meta.6": "Regulamentul de punere în aplicare (UE) 2024/2690 al Comisiei",
    "ue.meta.60": "Notificarea incidentului de către un prestator de servicii de încredere",
    "ue.meta.61": "articolul 21 alineatul (5) din Directiva (UE) 2022/2555; articolele 1 și 2 din Regulamentul (UE) 2024/2690",
    "ue.meta.62": "Fără date privind cifra de afaceri, plafonul este suma fixă din directivă.",
    "ue.meta.63": "Plafoanele de la articolul 34 alineatele (4) și (5) sunt minime („cel puțin”) — dreptul național poate prevedea altele mai mari. Sume în euro, fără conversie în moneda națională.",
    "ue.meta.64": "Autoritatea competentă a statului membru",
    "ue.meta.65": "Organul de conducere poate fi tras la răspundere pentru încălcarea articolului 21. Întinderea și procedura sunt stabilite de dreptul național — acest modul nu le cunoaște.",
    "ue.meta.66": "Întinderea răspunderii personale a conducerii decurge din legea națională. Pentru Polonia este de până la 300 % din remunerație (articolul 73a alineatul (4) din Legea privind sistemul național de securitate cibernetică); alte state decid altfel.",
    "ue.meta.7": "JO UE L, 2024/2690",
    "ue.meta.8": "Directiva (UE) 2022/2555",
    "ue.meta.9": "Termenul de transpunere a expirat la 17 octombrie 2024",
    "ue.moduly.1": "circa {p0} min",
    "ue.moduly.10": "Zece domenii de la articolul 21 alineatul (2) literele (a)-(j): de la politica de risc la autentificarea multifactor. Încălcarea se sancționează cu amendă conform articolului 34. Evaluare pe scara de maturitate.",
    "ue.moduly.11": "Regulamentul 2024/2690 — guvernanță și procese",
    "ue.moduly.12": "Secțiunile 1-5 și 7-8 din anexă: politici, gestionarea riscurilor, gestionarea incidentelor, continuitatea activității, lanțul de aprovizionare, evaluarea eficacității, igiena cibernetică. Direct aplicabil de la 7 noiembrie 2024.",
    "ue.moduly.13": "Regulamentul 2024/2690 — cerințe tehnice",
    "ue.moduly.14": "Secțiunile 6 și 9-13 din anexă: achiziționarea și dezvoltarea sistemelor, criptografie, securitatea resurselor umane, controlul accesului, gestionarea activelor, securitatea fizică și a mediului.",
    "ue.moduly.2": "circa {p0} h {p1} min",
    "ue.moduly.3": "circa {p0} h",
    "ue.moduly.4": "sub un minut",
    "ue.moduly.5": "Evaluare rapidă a riscurilor",
    "ue.moduly.6": "Întrebări transversale din toate domeniile directivei. Fiecare decide asupra unui întreg grup de aspecte. Permite estimarea amplorii restanțelor fără a parcurge întregul chestionar.",
    "ue.moduly.7": "Obligații din directivă",
    "ue.moduly.8": "Date de înregistrare, notificarea incidentelor în 24 și 72 de ore, obligațiile organului de conducere, pregătirea pentru supraveghere. Verificabile din documente, fără analiză tehnică.",
    "ue.moduly.9": "Măsuri de gestionare a riscurilor — articolul 21 alineatul (2)",
    "ue.obowiazki.1": "Date de înregistrare pentru lista entităților",
    "ue.obowiazki.10": "Notificarea incidentelor semnificative",
    "ue.obowiazki.11": "Entitatea notifică incidentele semnificative către CSIRT sau autoritatea competentă în trei pași: avertizare timpurie, notificare, raport final. Termenele curg de la luarea la cunoștință a incidentului.",
    "ue.obowiazki.12": "Este entitatea în măsură să transmită o avertizare timpurie în 24 de ore de la luarea la cunoștință a unui incident semnificativ, indicând dacă incidentul este suspectat a fi cauzat de acte ilicite și dacă poate avea impact transfrontalier?",
    "ue.obowiazki.13": "24 de ore de la luarea la cunoștință",
    "ue.obowiazki.14": "Este entitatea în măsură să transmită o notificare a incidentului în 72 de ore, cu o evaluare inițială a gravității și a impactului și cu indicatori de compromitere?",
    "ue.obowiazki.15": "72 de ore de la luarea la cunoștință",
    "ue.obowiazki.16": "Transmite entitatea un raport final cel târziu la o lună după notificare, cu descrierea incidentului, tipul amenințării, măsurile de atenuare și impactul transfrontalier?",
    "ue.obowiazki.17": "o lună de la notificare",
    "ue.obowiazki.18": "Informează entitatea destinatarii serviciilor sale despre incidentele semnificative care pot afecta negativ prestarea acestor servicii?",
    "ue.obowiazki.19": "Informează entitatea destinatarii serviciilor despre o amenințare cibernetică semnificativă și despre măsurile pe care le pot lua?",
    "ue.obowiazki.2": "Statele membre stabilesc o listă a entităților esențiale și importante și cer entităților să depună datele de înregistrare. Procedura, termenul și portalul sunt stabilite de dreptul național.",
    "ue.obowiazki.20": "Dacă entitatea este prestator de servicii de încredere — notifică incidentele semnificative în 24 de ore de la luarea la cunoștință?",
    "ue.obowiazki.21": "privește prestatorii de servicii de încredere",
    "ue.obowiazki.22": "Organul de conducere",
    "ue.obowiazki.23": "Organul de conducere aprobă măsurile de gestionare a riscurilor, supraveghează implementarea lor și poate fi tras la răspundere. Membrii organului urmează instruiri periodice.",
    "ue.obowiazki.24": "A aprobat organul de conducere în mod formal măsurile de gestionare a riscurilor în materie de securitate cibernetică adoptate pentru conformitatea cu articolul 21?",
    "ue.obowiazki.25": "Supraveghează organul de conducere implementarea acestor măsuri în mod documentat — de exemplu prin rapoarte și revizuiri periodice?",
    "ue.obowiazki.26": "Urmează membrii organului de conducere instruiri periodice care le permit să identifice riscurile și să evalueze practicile de gestionare a riscurilor, cu participare documentată?",
    "ue.obowiazki.27": "Pregătirea pentru acțiunile de supraveghere",
    "ue.obowiazki.28": "Entitatea esențială este supusă supravegherii ex ante și ex post, entitatea importantă — exclusiv ex post. Autoritatea poate solicita informații, dovezi ale implementării politicilor și rezultate ale auditurilor.",
    "ue.obowiazki.29": "Este entitatea în măsură ca, la cererea autorității, să prezinte dovezi ale implementării politicilor de securitate cibernetică, inclusiv rezultatele auditurilor de securitate?",
    "ue.obowiazki.3": "A stabilit entitatea dacă este esențială sau importantă, pe baza sectorului din anexa I sau II și a dimensiunii întreprinderii?",
    "ue.obowiazki.30": "Este entitatea în măsură ca, la cererea autorității, să pună la dispoziție datele, documentele și informațiile necesare exercitării atribuțiilor de supraveghere?",
    "ue.obowiazki.31": "Este entitatea esențială pregătită pentru un audit de securitate efectuat de autoritate sau de un organism independent, pe cheltuială proprie?",
    "ue.obowiazki.4": "A depus entitatea la autoritatea competentă datele de înregistrare: denumire, adresă și date de contact, sector și subsector, lista statelor membre în care prestează servicii?",
    "ue.obowiazki.5": "Datele de contact includ adrese de e-mail, intervale de adrese IP și numere de telefon. Termenul național și portalul de înregistrare sunt stabilite de dreptul statului membru.",
    "ue.obowiazki.6": "Există un proces de actualizare a datelor de înregistrare fără întârzieri nejustificate după modificarea lor?",
    "ue.obowiazki.7": "Directiva cere actualizarea fără întârzieri nejustificate; un termen concret — de exemplu 14 zile în Polonia — decurge din dreptul național.",
    "ue.obowiazki.8": "Dacă entitatea este furnizor DNS, registru TLD, furnizor cloud, centru de date, CDN, servicii gestionate, piață online, motor de căutare sau rețea socială — a depus datele suplimentare de la articolul 27, inclusiv adresa sediului principal din Uniune?",
    "ue.obowiazki.9": "privește entitățile de la articolul 26 alineatul (1)",
    "ue.role.1": "Autoritatea competentă a statului membru",
    "ue.role.10": "Servicii de centru de date: colocare, găzduire de infrastructură și servicii conexe.",
    "ue.role.11": "Centre de date",
    "ue.role.12": "Entitate esențială peste pragul întreprinderii mijlocii (articolul 3 alineatul (1) litera (a)), importantă la dimensiune mijlocie (articolul 3 alineatul (2)). Sub dimensiunea mijlocie — în afara domeniului, cu excepția cazului în care statul membru desemnează entitatea în temeiul articolului 2 alineatul (2) literele (b)-(e). Intră sub incidența Regulamentului 2024/2690.",
    "ue.role.13": "Furnizor de punct de interconectare la internet",
    "ue.role.14": "Infrastructură care permite schimbul de trafic între rețele independente.",
    "ue.role.15": "Puncte de interconectare la internet",
    "ue.role.16": "Clasificare în funcție de dimensiune (articolul 3 alineatul (1) litera (a) și alineatul (2)). Regulamentul 2024/2690 nu acoperă punctele de interconectare la internet — articolul 1 din regulament conține o listă închisă de destinatari.",
    "ue.role.17": "Furnizor de servicii DNS",
    "ue.role.18": "Servicii de rezoluție a numelor de domenii, cu excepția operatorilor de servere de nume rădăcină.",
    "ue.role.19": "Sistemul numelor de domenii",
    "ue.role.2": "autoritate competentă",
    "ue.role.20": "Entitate esențială indiferent de dimensiune (articolul 3 alineatul (1) litera (b)). Intră sub incidența Regulamentului 2024/2690.",
    "ue.role.21": "Registru de nume de domenii de nivel superior",
    "ue.role.22": "Administrarea unui registru al unui domeniu de nivel superior.",
    "ue.role.23": "Entitate esențială indiferent de dimensiune (articolul 3 alineatul (1) litera (b)). În plus, obligații privind datele de înregistrare de la articolul 28. Intră sub incidența Regulamentului 2024/2690.",
    "ue.role.24": "Furnizor de servicii de cloud computing",
    "ue.role.25": "Servicii de cloud computing: infrastructură, platformă, software ca serviciu.",
    "ue.role.26": "Servicii de cloud computing",
    "ue.role.27": "Clasificare în funcție de dimensiune (articolul 3 alineatul (1) litera (a) și alineatul (2)). Intră sub incidența Regulamentului 2024/2690.",
    "ue.role.28": "Furnizor de rețea de distribuție a conținutului",
    "ue.role.29": "Rețea de servere distribuite care livrează conținut și servicii utilizatorilor finali.",
    "ue.role.3": "desemnată de dreptul național; până la implementarea modulului național, instrumentul nu indică o instituție anume",
    "ue.role.30": "Rețele de distribuție a conținutului",
    "ue.role.31": "Prestator de servicii de încredere",
    "ue.role.32": "Servicii de încredere în sensul Regulamentului (UE) nr. 910/2014: semnături, sigilii, mărci temporale, certificate.",
    "ue.role.33": "Servicii de încredere",
    "ue.role.34": "Intră sub incidența directivei indiferent de dimensiune (articolul 2 alineatul (2) litera (a) punctul (ii)). Prestatorul calificat este entitate esențială indiferent de dimensiune (articolul 3 alineatul (1) litera (b)); cel necalificat este esențial peste pragul întreprinderii mijlocii, altfel important. Intră sub incidența Regulamentului 2024/2690.",
    "ue.role.35": "Furnizor de servicii gestionate",
    "ue.role.36": "Gestionarea infrastructurii TIC a clientului: instalare, întreținere, asistență, administrarea sistemelor.",
    "ue.role.37": "Gestionarea serviciilor TIC (B2B)",
    "ue.role.38": "Servicii gestionate",
    "ue.role.39": "Furnizor de servicii de securitate gestionate",
    "ue.role.4": "Furnizor de rețele publice de comunicații electronice sau de servicii de comunicații electronice destinate publicului",
    "ue.role.40": "Servicii gestionate în domeniul securității cibernetice: monitorizare, răspuns la incidente, teste, consultanță.",
    "ue.role.41": "Servicii de securitate gestionate",
    "ue.role.42": "Directiva clasifică în funcție de dimensiune (articolul 3 alineatul (1) litera (a) și alineatul (2)). Statele membre pot înăspri pragul — Polonia consideră MSSP entitate esențială încă de la întreprinderea mică; acest modul aplică exclusiv regula directivei. Intră sub incidența Regulamentului 2024/2690.",
    "ue.role.5": "Furnizarea de rețele publice de comunicații electronice sau prestarea de servicii de comunicații electronice destinate publicului, inclusiv acces la internet.",
    "ue.role.6": "Infrastructură digitală",
    "ue.role.7": "Comunicații electronice",
    "ue.role.8": "Intră sub incidența directivei indiferent de dimensiune (articolul 2 alineatul (2) litera (a) punctul (i)). Întreprinderea mijlocie sau mai mare este entitate esențială (articolul 3 alineatul (1) litera (c)), microîntreprinderea și întreprinderea mică — importantă (articolul 3 alineatul (2)). Legea națională a telecomunicațiilor poate impune obligații suplimentare — acest modul nu le conține.",
    "ue.role.9": "Furnizor de servicii de centru de date",
    "ue.role.podstawaArt3b": "articolul 3 alineatul (1) litera (b) din Directiva (UE) 2022/2555",
    "ue.zaslepki.1": "Directiva (UE) 2022/2555 a Parlamentului European și a Consiliului (NIS 2)",
    "ue.zaslepki.10": "Dacă unele entități sunt înscrise din oficiu decide dreptul național.",
    "ue.zaslepki.11": "Stabiliți dacă intrați sub incidența directivei",
    "ue.zaslepki.12": "Sectorul din anexa I sau II și dimensiunea întreprinderii. Această parte este realizată de profilul entității din acest instrument.",
    "ue.zaslepki.13": "Stabiliți autoritatea competentă din țara dumneavoastră",
    "ue.zaslepki.14": "Fiecare stat desemnează o autoritate competentă (articolul 8 alineatul (1)). Lista actualizată este ținută de ENISA și de Comisie.",
    "ue.zaslepki.15": "Depuneți datele de înregistrare",
    "ue.zaslepki.16": "Denumire, adresă și date de contact, sector și subsector, statele în care se prestează servicii (articolul 3 alineatul (4)). Procedura conform dreptului național.",
    "ue.zaslepki.17": "Actualizați datele fără întârzieri nejustificate",
    "ue.zaslepki.18": "Orice modificare a datelor de înregistrare necesită actualizare (articolul 3 alineatul (5)).",
    "ue.zaslepki.19": "adresa și datele de contact actuale: adrese de e-mail, intervale de adrese IP, numere de telefon",
    "ue.zaslepki.2": "JO UE L 333, 27.12.2022, p. 80",
    "ue.zaslepki.20": "sectorul și subsectorul din anexa I sau II",
    "ue.zaslepki.21": "lista statelor membre în care entitatea prestează servicii",
    "ue.zaslepki.22": "Stabilit de dreptul național.",
    "ue.zaslepki.23": "Directiva (UE) 2022/2555 — articolul 3",
    "ue.zaslepki.24": "ENISA — autoritățile competente ale statelor membre",
    "ue.zaslepki.25": "Directiva (UE) 2022/2555",
    "ue.zaslepki.26": "Modulul UE nu conține orientări ale unei autorități naționale — acestea vor veni odată cu modulul de drept național.",
    "ue.zaslepki.27": "Preluarea automată a datelor din registru funcționează doar pentru țările cu modul de drept național. Completați profilul manual.",
    "ue.zaslepki.28": "Citirea situației financiare funcționează doar pentru țările cu modul de drept național. Introduceți manual cifra de afaceri și numărul de angajați.",
    "ue.zaslepki.3": "Regulamentul de punere în aplicare (UE) 2024/2690 al Comisiei",
    "ue.zaslepki.4": "JO UE L, 2024/2690, 18.11.2024",
    "ue.zaslepki.5": "Directiva NIS 2 nu conține un strat separat de comunicații electronice. Dreptul național al comunicațiilor electronice poate impune obligații suplimentare — acest modul nu le cunoaște.",
    "ue.zaslepki.6": "Lista entităților esențiale și importante",
    "ue.zaslepki.7": "Autoritatea competentă a statului membru.",
    "ue.zaslepki.8": "Directiva impune statelor membre să țină o listă a entităților esențiale și importante și să ceară entităților depunerea datelor de înregistrare. Portalul, procedura și termenul sunt stabilite de dreptul național — acest modul nu le cunoaște, deoarece modulul de drept național pentru țara selectată nu este încă gata.",
    "ue.zaslepki.9": "Toate entitățile esențiale și importante. Termenul este stabilit de dreptul național.",
    "ue.zaslepki.skrotDyrektywy": "Directiva NIS 2",
    "ue.zaslepki.skrotReg2690": "Reg. 2024/2690",
    "xlsx.1": "{p0} – {p1} EUR",
    "xlsx.25": "Curs valutar",
    "xlsx.4": "RAPORT DE CONFORMITATE CU DIRECTIVA NIS 2 (UE) 2022/2555",
    "xlsx.58": "Activitate de comunicații electronice: Regulamentul (UE) 2024/2690 nu se aplică. Pragurile sunt stabilite de dreptul național (articolul 23 alineatul (11) din directivă) — modulul comun nu le cunoaște.",
    "xlsx.68": "Instrumentul servește autoevaluării. Nu este un audit și nici o opinie juridică.",
    "xlsx.69": "Pentru entitățile care nu intră sub incidența Regulamentului (UE) 2024/2690, pragurile incidentului semnificativ sunt stabilite de dreptul național (articolul 23 alineatul (11) din directivă).",
    "xlsx.70": "Rolurile indicate în profil sunt o declarație. Statutul este determinat de activitatea desfășurată efectiv (articolul 3 din Directiva (UE) 2022/2555).",
    "xlsx.etykietaKrs": "Număr de registru",
    "xlsx.etykietaNip": "Număr de identificare",
    "xlsx.etykietaRegon": "Număr statistic"
});
