/* Teksty modułu ue — język: sk.
   Te same klucze co w napisy/pl.js (wersja źródłowa); wstawki {p0}, {p1}…
   pozostają bez zmian. Klucze ue.cyt.* to wzorce składania odesłań
   do przepisów w tym języku — patrz kraje/ue/cytaty.js. */
KRAJE.napisy('ue', 'sk', {
    "app.10": "Skontrolujte zoznam rol nižšie — o statuse rozhoduje skutočne vykonávaná činnosť (článok 3 smernice (EÚ) 2022/2555), nie zápis v registri.",
    "app.14": "Predchádzajúci rok: {p0} EUR",
    "app.15": "Obrat za vykazované obdobie: {p0} EUR",
    "app.19": "Dopytujem registre podľa čísla {p0}…",
    "app.34": " mld. EUR",
    "app.35": " mil. EUR",
    "app.36": " tis. EUR",
    "app.37": "",
    "app.4": "Automatické načítanie údajov z registra nie je pre tento štát dostupné — vyplňte profil ručne.",
    "app.59": "Posúdenie súladu so smernicou NIS 2 (JSON)",
    "app.68": "Pre tento štát neexistuje register, z ktorého by nástroj mohol načítať údaje — profil sa vypĺňa ručne.",
    "app.69": "Pre tento štát neexistuje register, z ktorého by nástroj mohol načítať údaje. Kliknutím zapnete režim offline.",
    "app.73": " · výkaz ziskov a strát vo variante ",
    "app.74": "<div class=\"mt-2 tekst-uwaga\">Z údajov registra nevyplýva žiadna rola v odvetví digitálnej infraštruktúry. Roly vyberte ručne nižšie.</div>",
    "app.8": "Potvrdený zápis v registri poskytovateľov elektronických komunikácií",
    "app.progDostawcy": "",
    "app.przyklad.adres": "Vzorová 1, 811 01 Mesto",
    "app.przyklad.forma": "Spoločnosť s ručením obmedzeným",
    "app.przyklad.nazwa": "Vzorový operátor s.r.o.",
    "app.statusVat": " · stav DPH: ",
    "dashboard.1": "Na základe deklarovaných rol a veľkosti nie je subjekt kľúčovým ani dôležitým subjektom v zmysle článku 3 smernice (EÚ) 2022/2555. Skontrolujte profil, ak výsledok nezodpovedá očakávaniu.",
    "dashboard.113": "Časté otázky",
    "dashboard.12": "— {p0}; lehota na transpozíciu do národného práva uplynula {p2}",
    "dashboard.123": "Smernica NIS 2",
    "dashboard.30": "Zoznam kľúčových a dôležitých subjektov",
    "dashboard.4": "— priamo uplatniteľné od {p0} vo všetkých členských štátoch, bez transpozície",
    "dashboard.42": "Sumový variant: {p0}",
    "dashboard.45": "Kritériá z čl. 32 ods. 7 smernice:",
    "dashboard.46": "Spolu",
    "dashboard.49": "Subjekt vykonáva činnosť v oblasti elektronických komunikácií — zodpovednosť vedúcej osoby určuje národné právo",
    "dashboard.50": "",
    "dashboard.51": "",
    "dashboard.53": "Penále za omeškanie s výkonom rozhodnutia: od {p0} EUR do {p1} EUR za každý deň ({p2})",
    "dashboard.54": "Kvalifikovaný prípad: do {p0} EUR ({p1})",
    "dashboard.57": "({p0}). Odkedy môže národný orgán ukladať pokuty, určuje zákon transponujúci smernicu — tento modul ho nepozná. Povinnosti zavedenia vyplývajú z národného práva odo dňa jeho účinnosti.",
    "dashboard.65": "({p0}). Odkedy môže národný orgán ukladať pokuty, určuje zákon transponujúci smernicu — tento modul ho nepozná. Finančné riziko tu preto nie je datované, povinnosti zavedenia však vyplývajú z národného práva odo dňa jeho účinnosti.",
    "dashboard.83": "Činnosť v oblasti elektronických komunikácií — prahové hodnoty určuje národné právo.",
    "dashboard.84": "Nariadenie (EÚ) 2024/2690 sa nevzťahuje na poskytovateľov verejných sietí a služieb elektronických komunikácií. Prahové hodnoty významného incidentu pre nich určuje národné právo (čl. 23 ods. 11 smernice) — tento modul ich nepozná, a preto neuvádza číselné hodnoty.",
    "dashboard.terminRejestracji": "Lehotu na predloženie registračných údajov určuje národné právo (čl. 3 ods. 4 smernice). Poskytovatelia podľa čl. 27 ods. 1 — služieb DNS, registre TLD, cloudových služieb, dátových centier, sietí na sprístupňovanie obsahu, riadených služieb a riadených bezpečnostných služieb — odovzdávajú údaje do registra ENISA: pôvodne do 17. januára 2025, každú zmenu bez zbytočného odkladu.",
    "html.1": "ITORO — Posúdenie súladu so smernicou NIS 2 (EÚ) 2022/2555",
    "html.10": "Posúdenie súladu so smernicou NIS 2 — spoločný modul",
    "html.100": "Načítanie účtovnej závierky funguje len pre štáty s modulom národného práva. Pre tento štát zadávate <strong>obrat</strong> za účtovné obdobie ručne — od neho závisí výška pokuty.",
    "html.102": "Automatické načítanie údajov z registrov funguje len pre štáty s modulom národného práva. Roly a veľkosť podniku uvádzate ručne.",
    "html.11": "Smernica (EÚ) 2022/2555 (NIS 2) vyžaduje transpozíciu do národného práva. Posúdenie zahŕňa povinnosti vyplývajúce priamo zo smernice a priamo uplatniteľné vykonávacie nariadenie Komisie (EÚ) 2024/2690 — v rozsahu, v akom sa subjektu týkajú.",
    "html.23": "obrat a veľkosť zadávate ručne — spoločný modul nedopytuje národné registre",
    "html.33": "smernica Európskeho parlamentu a Rady (EÚ) 2022/2555 zo 14. decembra 2022 (NIS 2)",
    "html.33a": "{p0} — vnútroštátny predpis transponujúci smernicu; jeho požiadavky tento modul zatiaľ nehodnotí",
    "html.33b": "štát zatiaľ neprijal transpozičný predpis — hodnotenie vychádza z práva Únie",
    "html.35": "povinnosti riadiaceho orgánu — článok 20 smernice",
    "html.36": "Nástroj slúži na sebahodnotenie. Nie je auditom ani právnym stanoviskom.",
    "html.40": "spoločný modul nevykonáva žiadne odchádzajúce spojenia — nedopytuje registre",
    "html.59": "Účtovné závierky",
    "html.60": "Načítanie účtovnej závierky je dostupné len pre štáty s modulom národného práva. Pre tento štát zadávate obrat a počet zamestnancov ručne.",
    "html.62": "Vyhľadanie v registri",
    "html.63": "obchodné registre sú národné — spoločný modul ich nepozná",
    "html.64": "roly a veľkosť podniku uvádzate ručne",
    "html.66": "Identifikačné číslo subjektu",
    "html.68": "Automatické načítanie údajov z registrov funguje len pre štáty s modulom národného práva.",
    "html.76": "Ročný obrat (EUR)",
    "html.78": "Obrat z činnosti v oblasti elektronických komunikácií (EUR)",
    "html.79": "Pole sa týka poskytovateľov verejných sietí alebo služieb elektronických komunikácií. Národné prahové hodnoty určuje právo členského štátu.",
    "html.80": "Mesačná odmena vedúceho (EUR)",
    "html.82": "Výmenný kurz",
    "html.83": "Stropy pokút v smernici sú vyjadrené v eurách. Prepočet na národnú menu a kurz určuje národné právo — tu sú sumy uvedené v eurách bez prepočtu.",
    "html.84": "Status vyplýva výlučne zo sčítania údajov prepojených podnikov a informačný systém subjektu je nezávislý (odôvodnenie 16 smernice — o uplatnení rozhoduje národné právo)",
    "html.85": "Subjekt pôsobí v oblasti národnej bezpečnosti, verejnej bezpečnosti, obrany alebo presadzovania práva (čl. 2 ods. 7 smernice)",
    "html.91": "Posúdenie súladu so smernicou Európskeho parlamentu a Rady (EÚ) 2022/2555 (NIS 2) a s vykonávacím nariadením Komisie (EÚ) 2024/2690 — spoločný modul pre štáty, ktorých modul národného práva ešte nie je hotový.",
    "html.94": "či je subjekt <strong>kľúčový</strong>, <strong>dôležitý</strong>, alebo mimo pôsobnosti smernice",
    "html.daneZeSprawozdania": "názov, identifikačné číslo, adresa sídla",
    "html.rejestrMozliwy": "Register {p0} je verejný a bezplatný — jeho čítanie možno doplniť; prijímame pull requesty (pozri README).",
    "html.tytulNaglowka": "Posúdenie súladu so smernicou NIS 2",
    "html.zrodlaRecznie": "Tento modul nepozná registre vášho štátu — profil vyplňte ručne. Ročný obrat určuje hornú hranicu pokuty, preto ho zadajte presne.",
    "klasyfikacja.10": "čl. 3 ods. 1 písm. c) smernice (EÚ) 2022/2555 (poskytovateľ verejných elektronických komunikačných sietí alebo verejne dostupných elektronických komunikačných služieb, ktorý je aspoň stredným podnikom)",
    "klasyfikacja.11": "čl. 3 ods. 2 v spojení s čl. 2 ods. 2 písm. a) bodom i) smernice (EÚ) 2022/2555 (poskytovateľ verejných sietí alebo služieb elektronických komunikácií, ktorý je mikropodnikom alebo malým podnikom)",
    "klasyfikacja.12": "čl. 3 ods. 1 písm. a) smernice (EÚ) 2022/2555 (poskytovateľ riadených bezpečnostných služieb presahujúci stropy pre stredný podnik)",
    "klasyfikacja.13": "Mikropodniky a malé podniky nie sú z titulu tejto roly smernicou dotknuté (čl. 2 ods. 1 a contrario).",
    "klasyfikacja.15": "čl. 3 ods. 1 písm. b) smernice (EÚ) 2022/2555 (kvalifikovaný poskytovateľ dôveryhodných služieb) — bez ohľadu na veľkosť podniku",
    "klasyfikacja.16": "čl. 3 ods. 2 v spojení s čl. 2 ods. 2 písm. a) bodom ii) smernice (EÚ) 2022/2555 (nekvalifikovaný poskytovateľ dôveryhodných služieb, ktorý je mikropodnikom, malým alebo stredným podnikom)",
    "klasyfikacja.18": "čl. 3 ods. 2 smernice (EÚ) 2022/2555 (subjekt verejnej správy na regionálnej úrovni, ak tak členský štát ustanoví — čl. 2 ods. 2 písm. f) bod ii))",
    "klasyfikacja.19": "čl. 3 ods. 1 písm. f) smernice (EÚ) 2022/2555 (subjekt verejnej správy na ústrednej úrovni — čl. 2 ods. 2 písm. f) bod i))",
    "klasyfikacja.2": "Dohľad ex ante a ex post (článok 32 smernice (EÚ) 2022/2555).",
    "klasyfikacja.20": "čl. 3 ods. 2 smernice (EÚ) 2022/2555 (subjekt verejnej správy na regionálnej úrovni — čl. 2 ods. 2 písm. f) bod ii))",
    "klasyfikacja.21": "Rozsah povinností subjektov verejnej správy na miestnej úrovni určuje národné právo (čl. 2 ods. 5 písm. a) smernice).",
    "klasyfikacja.22": "Členský štát môže vyňať subjekty pôsobiace v oblasti národnej bezpečnosti, verejnej bezpečnosti, obrany alebo presadzovania práva (čl. 2 ods. 7 smernice). Výnimka nepôsobí sama od seba — výsledok posúdenia overte podľa národného práva.",
    "klasyfikacja.23": "Subjekt spĺňa kritériá kľúčového aj dôležitého subjektu. Je kľúčovým subjektom (čl. 3 ods. 1 smernice) a prísnejšie požiadavky sa vzťahujú na celú činnosť, na ktorú sa smernica vzťahuje.",
    "klasyfikacja.25": "Subjekt je kľúčový, preto sa naň vzťahuje úplný katalóg opatrení podľa čl. 21 ods. 2 smernice a dohľad ex ante aj ex post — posúdenie zahŕňa úplný súbor otázok.",
    "klasyfikacja.26": "Ako dôležitý subjekt podliehate rovnakému katalógu opatrení podľa čl. 21 ods. 2, ale iba dohľadu ex post (článok 33). Strop pokuty je nižší: 7 mil. EUR alebo 1,4 % obratu (čl. 34 ods. 5). Úľavy pre verejné subjekty môže zaviesť národné právo — tento modul ich nepozná.",
    "klasyfikacja.28": "Povinnosti subjektov verejnej správy vyplývajú z čl. 2 ods. 2 písm. f) smernice; ich presný rozsah vrátane miestnej úrovne a vzdelávacích zariadení určuje národné právo (čl. 2 ods. 5).",
    "klasyfikacja.29": "Bolo deklarované, že status subjektu vyplýva výlučne zo sčítania údajov prepojených alebo partnerských podnikov a že informačný systém subjektu je nezávislý. Smernica takú výnimku pripúšťa (odôvodnenie 16), rozhoduje o nej však národné právo — modul výnimku prijíma a treba ju overiť podľa práva členského štátu a zdokumentovať.",
    "klasyfikacja.4": "Iba dohľad ex post — pri dôkazoch, náznakoch alebo informáciách o porušení (článok 33 smernice (EÚ) 2022/2555).",
    "klasyfikacja.5": "Mimo pôsobnosti smernice",
    "klasyfikacja.6": "Pre uvedenú rolu nevyplývajú zo smernice (EÚ) 2022/2555 žiadne povinnosti.",
    "klasyfikacja.7": "čl. 3 ods. 1 písm. a) smernice (EÚ) 2022/2555 (subjekt druhu uvedeného v prílohe I presahujúci stropy pre stredný podnik)",
    "klasyfikacja.8": "čl. 3 ods. 2 smernice (EÚ) 2022/2555 (subjekt druhu uvedeného v prílohe I spĺňajúci kritériá stredného podniku)",
    "klasyfikacja.9": "Mikropodniky a malé podniky nie sú z titulu tejto roly smernicou dotknuté (čl. 2 ods. 1 a contrario).",
    "kreator.10": "Obrat za predchádzajúci rok zadajte ručne.",
    "kreator.35": "<span class=\"text-secondary\">Načítanie účtovných závierok nie je pre tento štát dostupné.</span>",
    "kreator.37": "Načítanie účtovných závierok nie je pre tento štát dostupné — zadajte obrat ručne.",
    "kreator.56": "Áno — nariadenie EÚ sa uplatňuje priamo od 7. novembra 2024 vo všetkých členských štátoch a nemá prechodné obdobie. Základom je",
    "kreator.57": ", ktorý splnomocnil Komisiu na stanovenie technických a metodických požiadaviek pre poskytovateľov uvedených v čl. 3 ods. 1 nariadenia. Lehota na transpozíciu smernice uplynula",
    "kreator.58": ", a odkedy môže národný orgán ukladať pokuty, určuje národné právo. Technické požiadavky prílohy (oddiely 6 a 9–13) sú záväzné v súčasnom znení — nečakajú na spresnenie. Odchýliť sa možno iba od požiadaviek s doložkou „v príslušných prípadoch“, a to výlučne so zdokumentovaným odôvodnením.",
    "kreator.9": "Účtovné závierky →",
    "kreator.przepisReg2690": "čl. 21 ods. 5 smernice (EÚ) 2022/2555",
    "kreator.terminReg2690": "17. októbra 2024",
    "punktacja.10": "Verejné subjekty",
    "punktacja.4": "Smernica NIS 2 — článok 21",
    "punktacja.5": "Smernica NIS 2 — formálne povinnosti",
    "punktacja.8": "Elektronické komunikácie",
    "punktacja.9": "Smernica NIS 2 — verejné subjekty",
    "punktacja.skrotKsc": "NIS 2",
    "punktacja.skrotPke": "telekom",
    "ue.cyt.akapit": "pododsek {p0}",
    "ue.cyt.art": "čl. {p0}",
    "ue.cyt.drugi": "2",
    "ue.cyt.dyr": "{p0} smernice (EÚ) 2022/2555",
    "ue.cyt.i": "a",
    "ue.cyt.laczenie": " ",
    "ue.cyt.lit": "písm. {p0})",
    "ue.cyt.litery": "",
    "ue.cyt.pkt": "bod {p0}",
    "ue.cyt.rozdzielacz": "; ",
    "ue.cyt.rozp": "{p0} nariadenia (EÚ) 2024/2690",
    "ue.cyt.ust": "ods. {p0}",
    "ue.katalog.1": "Politiky analýzy rizík a bezpečnosti informačných systémov",
    "ue.katalog.10": "Riešenie incidentov",
    "ue.katalog.11": "Riešenie incidentov zahŕňa všetky opatrenia a postupy zamerané na predchádzanie incidentom, ich odhaľovanie, analýzu a obmedzenie, reakciu na ne a obnovu po nich (čl. 6 bod 8).",
    "ue.katalog.12": "Existuje zdokumentovaný postup riešenia incidentov zahŕňajúci odhalenie, analýzu, obmedzenie, reakciu a obnovu?",
    "ue.katalog.13": "ISO/IEC 27001 A.5.24–A.5.26",
    "ue.katalog.14": "Umožňuje postup dodržať lehoty na hlásenie významného incidentu: včasné varovanie do 24 hodín, hlásenie do 72 hodín, záverečná správa do jedného mesiaca?",
    "ue.katalog.15": "ISO/IEC 27001 A.5.24",
    "ue.katalog.16": "Má subjekt kritériá na uznanie incidentu za významný v súlade s čl. 23 ods. 3: závažné narušenie prevádzky alebo finančné straty, alebo značná ujma iným osobám?",
    "ue.katalog.17": "ISO/IEC 27001 A.5.25",
    "ue.katalog.18": "Sú incidenty evidované a poznatky z ich riešenia využívané na zlepšovanie opatrení?",
    "ue.katalog.19": "ISO/IEC 27001 A.5.27",
    "ue.katalog.2": "Opatrenia vychádzajú z prístupu zohľadňujúceho všetky riziká (čl. 21 ods. 2). Ich primeranosť sa posudzuje s ohľadom na mieru vystavenia riziku, veľkosť subjektu, pravdepodobnosť incidentov a ich závažnosť (čl. 21 ods. 1 druhý pododsek).",
    "ue.katalog.20": "Kontinuita činností a krízové riadenie",
    "ue.katalog.21": "Kontinuita činností, ako je správa záloh a obnova po havárii, a krízové riadenie.",
    "ue.katalog.22": "Existuje plán kontinuity činností zahŕňajúci obnovu po havárii?",
    "ue.katalog.23": "ISO/IEC 27001 A.5.29–A.5.30",
    "ue.katalog.24": "Vytvárajú sa zálohy, sú chránené a testované z hľadiska obnoviteľnosti?",
    "ue.katalog.25": "ISO/IEC 27001 A.8.13",
    "ue.katalog.26": "Má subjekt postupy krízového riadenia s vymedzenými rolami a komunikačnými kanálmi?",
    "ue.katalog.27": "ISO/IEC 27001 A.5.29",
    "ue.katalog.28": "Testujú sa plány kontinuity a obnovy pravidelne a dokumentujú sa výsledky?",
    "ue.katalog.29": "ISO/IEC 27001 A.5.30",
    "ue.katalog.3": "Má subjekt zdokumentovanú politiku analýzy rizík a bezpečnosti informačných systémov schválenú riadiacim orgánom?",
    "ue.katalog.30": "Bezpečnosť dodávateľského reťazca",
    "ue.katalog.31": "Bezpečnosť dodávateľského reťazca vrátane bezpečnostných aspektov vzťahov medzi subjektom a jeho priamymi dodávateľmi alebo poskytovateľmi služieb. Subjekt zohľadňuje zraniteľnosti špecifické pre každého dodávateľa a celkovú kvalitu jeho produktov a postupov v oblasti kybernetickej bezpečnosti (čl. 21 ods. 3).",
    "ue.katalog.32": "Vedie subjekt zoznam priamych dodávateľov a poskytovateľov služieb s hodnotením ich významu pre bezpečnosť sietí a systémov?",
    "ue.katalog.33": "ISO/IEC 27001 A.5.19",
    "ue.katalog.34": "Zohľadňujú sa pri výbere opatrení voči dodávateľom zraniteľnosti špecifické pre každého z nich a kvalita ich postupov kybernetickej bezpečnosti a bezpečného vývoja?",
    "ue.katalog.35": "ISO/IEC 27001 A.5.19, A.5.21",
    "ue.katalog.36": "Obsahujú zmluvy s dodávateľmi bezpečnostné požiadavky a povinnosť informovať o incidentoch a zraniteľnostiach?",
    "ue.katalog.37": "ISO/IEC 27001 A.5.20",
    "ue.katalog.38": "Zohľadňuje subjekt výsledky koordinovaných posúdení bezpečnostných rizík kritických dodávateľských reťazcov podľa článku 22?",
    "ue.katalog.39": "ISO/IEC 27001 A.5.21",
    "ue.katalog.4": "ISO/IEC 27001 body 5.2, 6.1.2",
    "ue.katalog.40": "Bezpečnosť pri obstarávaní, vývoji a údržbe systémov",
    "ue.katalog.41": "Bezpečnosť obstarávania, vývoja a údržby sietí a informačných systémov vrátane riešenia a zverejňovania zraniteľností.",
    "ue.katalog.42": "Sú bezpečnostné požiadavky stanovené pred obstaraním alebo začatím vývoja systému a overené pred nasadením?",
    "ue.katalog.43": "ISO/IEC 27001 A.8.25–A.8.29",
    "ue.katalog.44": "Existuje proces riešenia zraniteľností: identifikácia, posúdenie, odstránenie v stanovenej lehote?",
    "ue.katalog.45": "ISO/IEC 27001 A.8.8",
    "ue.katalog.46": "Má subjekt postup zverejňovania zraniteľností vrátane kanála na prijímanie hlásení od tretích strán?",
    "ue.katalog.47": "Prechádzajú zmeny systémov riadeným procesom riadenia zmien s posúdením vplyvu na bezpečnosť?",
    "ue.katalog.48": "ISO/IEC 27001 A.8.32",
    "ue.katalog.49": "Posudzovanie účinnosti opatrení",
    "ue.katalog.5": "Zahŕňa analýza rizík všetky riziká pre siete a informačné systémy a ich fyzické prostredie, nielen kybernetické hrozby?",
    "ue.katalog.50": "Politiky a postupy na posudzovanie účinnosti opatrení na riadenie kybernetických bezpečnostných rizík.",
    "ue.katalog.51": "Existuje zdokumentovaná politika posudzovania účinnosti opatrení vymedzujúca rozsah, frekvenciu a metódy?",
    "ue.katalog.52": "ISO/IEC 27001 bod 9.1",
    "ue.katalog.53": "Vykonávajú sa posúdenia účinnosti pravidelne a odovzdávajú sa ich výsledky riadiacemu orgánu?",
    "ue.katalog.54": "ISO/IEC 27001 body 9.2–9.3",
    "ue.katalog.55": "Vedú zistené slabiny k zdokumentovaným nápravným opatreniam s vlastníkom a lehotou?",
    "ue.katalog.56": "ISO/IEC 27001 bod 10.1",
    "ue.katalog.57": "Kybernetická hygiena a školenia",
    "ue.katalog.58": "Základné postupy kybernetickej hygieny a školenia v oblasti kybernetickej bezpečnosti. Členovia riadiaceho orgánu sa pravidelne zúčastňujú na školeniach (čl. 20 ods. 2).",
    "ue.katalog.59": "Uplatňuje subjekt základné postupy kybernetickej hygieny: aktualizácie, správu hesiel, obmedzenie oprávnení, ochranu pred škodlivým softvérom?",
    "ue.katalog.6": "ISO/IEC 27001 bod 6.1.2",
    "ue.katalog.60": "ISO/IEC 27001 A.8.7, A.8.8",
    "ue.katalog.61": "Absolvujú zamestnanci školenia kybernetickej bezpečnosti prispôsobené ich role a je účasť dokumentovaná?",
    "ue.katalog.62": "ISO/IEC 27001 A.6.3",
    "ue.katalog.63": "Zúčastňujú sa členovia riadiaceho orgánu pravidelne na školeniach umožňujúcich rozpoznať riziká a posúdiť postupy riadenia rizík?",
    "ue.katalog.64": "ISO/IEC 27001 bod 7.2",
    "ue.katalog.65": "Kryptografia a šifrovanie",
    "ue.katalog.66": "Politiky a postupy používania kryptografie a v príslušných prípadoch šifrovania.",
    "ue.katalog.67": "Existuje politika používania kryptografie vymedzujúca, ktoré údaje a kanály sa šifrujú a akými algoritmami?",
    "ue.katalog.68": "ISO/IEC 27001 A.8.24",
    "ue.katalog.69": "Spravujú sa kryptografické kľúče v celom životnom cykle: generovanie, distribúcia, uloženie, rotácia, vyradenie?",
    "ue.katalog.7": "Zohľadňuje výber opatrení najnovší stav techniky, príslušné európske a medzinárodné normy a náklady na zavedenie?",
    "ue.katalog.70": "Ľudské zdroje, riadenie prístupu a správa aktív",
    "ue.katalog.71": "Bezpečnosť ľudských zdrojov, politiky riadenia prístupu a správa aktív.",
    "ue.katalog.72": "Vedie subjekt aktuálny zoznam aktív s priradenými vlastníkmi a klasifikáciou?",
    "ue.katalog.73": "ISO/IEC 27001 A.5.9, A.5.12",
    "ue.katalog.74": "Existuje politika riadenia prístupu založená na zásade najnižších oprávnení s pravidelným preskúmaním oprávnení?",
    "ue.katalog.75": "ISO/IEC 27001 A.5.15, A.5.18",
    "ue.katalog.76": "Uplatňujú sa pri nástupe, zmene pozície a odchode zamestnanca bezpečnostné postupy vrátane odobratia oprávnení a vrátenia aktív?",
    "ue.katalog.77": "ISO/IEC 27001 A.6.1–A.6.5",
    "ue.katalog.78": "Je privilegovaný prístup obmedzený, zaznamenávaný a preskúmavaný?",
    "ue.katalog.79": "ISO/IEC 27001 A.8.2",
    "ue.katalog.8": "ISO/IEC 27001 bod 6.1.3",
    "ue.katalog.80": "Viacfaktorová autentifikácia a zabezpečená komunikácia",
    "ue.katalog.81": "V príslušných prípadoch — viacfaktorová alebo priebežná autentifikácia, zabezpečená hlasová, obrazová a textová komunikácia a zabezpečené systémy núdzovej komunikácie v rámci subjektu.",
    "ue.katalog.82": "Používa sa viacfaktorová alebo priebežná autentifikácia tam, kde to analýza rizík odôvodňuje, najmä pre vzdialený prístup a privilegované účty?",
    "ue.katalog.83": "ISO/IEC 27001 A.8.5",
    "ue.katalog.84": "Je hlasová, obrazová a textová komunikácia používaná na služobné účely zabezpečená?",
    "ue.katalog.85": "ISO/IEC 27001 A.8.20",
    "ue.katalog.86": "Má subjekt zabezpečený systém internej núdzovej komunikácie nezávislý od hlavnej infraštruktúry?",
    "ue.katalog.9": "Je úroveň bezpečnosti zdokumentovaná ako primeraná existujúcemu riziku, s odôvodnením zohľadňujúcim veľkosť subjektu a spoločenské a hospodárske dôsledky incidentov?",
    "ue.kierownictwo.1": "Riadiaci orgán kľúčového alebo dôležitého subjektu — v kapitálovej spoločnosti predstavenstvo či konatelia. Smernica tento pojem nedefinuje; jeho rozsah v danom štáte vyplýva z národného práva.",
    "ue.kierownictwo.10": "Určiť status subjektu a zabezpečiť registráciu",
    "ue.kierownictwo.11": "Určenie, či je subjekt kľúčový alebo dôležitý, a predloženie registračných údajov príslušnému orgánu. Postup a lehotu určuje národné právo.",
    "ue.kierownictwo.12": "Zaviesť analýzu rizík a bezpečnostnú politiku",
    "ue.kierownictwo.13": "Opatrenia vychádzajúce z prístupu zohľadňujúceho všetky riziká, primerané vystaveniu riziku, veľkosti subjektu a závažnosti incidentov.",
    "ue.kierownictwo.14": "Spustiť riešenie a hlásenie incidentov",
    "ue.kierownictwo.15": "Postup riešenia incidentov a schopnosť dodržať lehoty 24 hodín, 72 hodín a jedného mesiaca.",
    "ue.kierownictwo.16": "24 h / 72 h / mesiac od zistenia",
    "ue.kierownictwo.17": "Zabezpečiť kontinuitu činností",
    "ue.kierownictwo.18": "Plán kontinuity, zálohy, obnova po havárii, krízové riadenie.",
    "ue.kierownictwo.19": "Usporiadať dodávateľský reťazec",
    "ue.kierownictwo.2": "Zodpovednosťou riadiaceho orgánu nie sú dotknuté národné predpisy o zodpovednosti verejných inštitúcií a úradníkov (čl. 20 ods. 1 druhý pododsek).",
    "ue.kierownictwo.20": "Zoznam dodávateľov, hodnotenie ich zraniteľností a postupov, bezpečnostné požiadavky v zmluvách.",
    "ue.kierownictwo.21": "Zaviesť riadenie prístupu a správu aktív",
    "ue.kierownictwo.22": "Zoznam aktív, zásada najnižších oprávnení, preskúmania oprávnení, viacfaktorová autentifikácia tam, kde to riziko odôvodňuje.",
    "ue.kierownictwo.23": "Merať účinnosť opatrení",
    "ue.kierownictwo.24": "Politika a postupy posudzovania účinnosti, pravidelné preskúmania, nápravné opatrenia.",
    "ue.kierownictwo.25": "Schvaľovať",
    "ue.kierownictwo.26": "opatrenia na riadenie kybernetických bezpečnostných rizík (čl. 20 ods. 1)",
    "ue.kierownictwo.27": "politiku analýzy rizík a bezpečnosti systémov",
    "ue.kierownictwo.28": "rozpočet a roly pri zavádzaní",
    "ue.kierownictwo.29": "Dohliadať",
    "ue.kierownictwo.3": "Či zverenie povinností inej osobe vylučuje zodpovednosť, rozhoduje národné právo. V Poľsku nevylučuje (čl. 8c ods. 3 zákona o národnom systéme kybernetickej bezpečnosti).",
    "ue.kierownictwo.30": "na vykonávanie schválených opatrení (čl. 20 ods. 1)",
    "ue.kierownictwo.31": "na výsledky posúdenia účinnosti (čl. 21 ods. 2 písm. f))",
    "ue.kierownictwo.32": "na dodržiavanie lehôt na hlásenie incidentov (článok 23)",
    "ue.kierownictwo.33": "Dokumentovať",
    "ue.kierownictwo.34": "schvaľovacie rozhodnutia a preskúmania",
    "ue.kierownictwo.35": "účasť na školeniach (čl. 20 ods. 2)",
    "ue.kierownictwo.36": "Člen riadiaceho orgánu",
    "ue.kierownictwo.37": "schvaľovanie opatrení, dohľad, rozhodnutia, rozpočet",
    "ue.kierownictwo.38": "Vedúci projektu",
    "ue.kierownictwo.39": "koordinácia zavádzania, harmonogram, stav a dôkazy",
    "ue.kierownictwo.4": "Schváliť opatrenia na riadenie kybernetických bezpečnostných rizík",
    "ue.kierownictwo.40": "IT / kybernetická bezpečnosť",
    "ue.kierownictwo.41": "analýza rizík, technické opatrenia, riešenie incidentov",
    "ue.kierownictwo.42": "Právne oddelenie / compliance",
    "ue.kierownictwo.5": "Riadiaci orgán schvaľuje opatrenia prijaté na zabezpečenie súladu s článkom 21. Je to rozhodnutie orgánu, nie IT oddelenia — bez neho opatrenia nemajú oporu.",
    "ue.kierownictwo.6": "Dohliadať na vykonávanie opatrení",
    "ue.kierownictwo.7": "Dohľad nad vykonávaním je povinnosťou riadiaceho orgánu. Vykonanie možno zveriť, dohľad nie.",
    "ue.kierownictwo.8": "Pravidelne sa zúčastňovať na školeniach",
    "ue.kierownictwo.9": "Členovia riadiaceho orgánu sa pravidelne zúčastňujú na školeniach, aby získali dostatočné znalosti na rozpoznanie rizík a posúdenie postupov riadenia rizík a ich vplyvu na služby subjektu.",
    "ue.kierownictwo.daneRejestracyjne": "registračné údaje a ich aktualizácia (čl. 3 ods. 4–5)",
    "ue.meta.1": "Prevažuje percentuálny variant: {p0} % obratu je viac ako {p1} mil. EUR.",
    "ue.meta.10": "Smernica neukladá povinnosti podnikom priamo — robí to národný zákon, ktorý mal členský štát prijať do 17. októbra 2024. Tento modul zobrazuje požiadavky v znení smernice, pretože modul národného práva pre vybraný štát ešte nie je hotový alebo štát smernicu netransponoval.",
    "ue.meta.11": "Povinnosti zo smernice",
    "ue.meta.12": "Zoznam subjektov — do 17. apríla 2025",
    "ue.meta.13": "Členské štáty mali do 17. apríla 2025 vytvoriť zoznam kľúčových a dôležitých subjektov a vyžadovať od subjektov predloženie registračných údajov.",
    "ue.meta.14": "Nariadenie (EÚ) 2024/2690",
    "ue.meta.15": "Priamo uplatniteľné od 7. novembra 2024",
    "ue.meta.16": "Vykonávacie nariadenie sa uplatňuje priamo vo všetkých členských štátoch bez ohľadu na stav transpozície smernice. Týka sa subjektov uvedených v jeho článku 1: DNS, TLD, cloudu, dátových centier, sietí na sprístupňovanie obsahu, riadených služieb a dôveryhodných služieb.",
    "ue.meta.17": "článok 16 nariadenia (EÚ) 2024/2690",
    "ue.meta.18": "Najmenej 10 000 000 EUR alebo najmenej 2 % celkového celosvetového ročného obratu podniku v predchádzajúcom účtovnom období — uplatní sa vyššia suma. Ide o minimálny strop: národné právo ho môže zvýšiť.",
    "ue.meta.19": "Najmenej 7 000 000 EUR alebo 1,4 % celkového celosvetového ročného obratu — uplatní sa vyššia suma. Minimálny strop.",
    "ue.meta.2": "Prevažuje pevná suma: {p0} mil. EUR je viac ako {p1} % obratu.",
    "ue.meta.20": "Smernica neustanovuje samostatnú pokutu za kvalifikované porušenie — ide o konštrukciu národného práva niektorých štátov.",
    "ue.meta.21": "Členské štáty môžu ustanoviť penále na vynútenie ukončenia porušovania. Výšku určuje národné právo.",
    "ue.meta.22": "Riadiaci orgán schvaľuje opatrenia na riadenie rizík, dohliada na ich vykonávanie a môže niesť zodpovednosť za porušenie článku 21. Zásady a rozsah tejto zodpovednosti určuje národné právo.",
    "ue.meta.23": "Riadiaci orgán schvaľuje opatrenia na riadenie kybernetických bezpečnostných rizík (čl. 20 ods. 1).",
    "ue.meta.24": "Riadiaci orgán dohliada na vykonávanie týchto opatrení (čl. 20 ods. 1).",
    "ue.meta.25": "Členovia riadiaceho orgánu sa pravidelne zúčastňujú na školeniach (čl. 20 ods. 2).",
    "ue.meta.26": "Voči kľúčovému subjektu môže orgán požiadať o dočasný zákaz výkonu riadiacich funkcií (čl. 32 ods. 5 písm. b)).",
    "ue.meta.27": "Minimálny strop určuje smernica",
    "ue.meta.28": "Porovnávajú sa dve hodnoty: pevná suma v eurách a percento celkového celosvetového ročného obratu podniku v predchádzajúcom účtovnom období. Vyššia z nich je horná hranica, ktorú členský štát musí prinajmenšom ustanoviť. Národné právo ju môže zvýšiť.",
    "ue.meta.29": "Sumu v rámci stropu určuje národný orgán",
    "ue.meta.3": "Strop zo smernice prevyšuje ročný obrat subjektu {p0}-násobne. Čl. 34 ods. 1 vyžaduje, aby pokuta bola primeraná okolnostiam jednotlivého prípadu — ide o hornú hranicu, nie o očakávanú pokutu.",
    "ue.meta.30": "Pokuta má byť účinná, primeraná a odrádzajúca vzhľadom na okolnosti jednotlivého prípadu. Orgán zohľadňuje aspoň kritériá z čl. 32 ods. 7: závažnosť a trvanie porušenia, predchádzajúce porušenia, škody, úmysel, nápravné opatrenia a spoluprácu.",
    "ue.meta.31": "Strop môže mnohonásobne prevyšovať ročný obrat — ide o hornú hranicu, nie o očakávanú sumu. Národné minimá, penále a spôsob vymerania určuje zákon členského štátu.",
    "ue.meta.32": "Pri rozhodovaní o uložení správnej pokuty a o jej výške sa v každom jednotlivom prípade náležite zohľadnia aspoň prvky uvedené v čl. 32 ods. 7.",
    "ue.meta.33": "závažnosť porušenia a význam porušených ustanovení — za závažné sa v každom prípade považujú: opakované porušenia, nenahlásenie alebo nenapravenie významných incidentov, nenapravenie nedostatkov v rozpore so záväznými príkazmi, marenie auditov alebo monitorovania, poskytnutie nepravdivých alebo hrubo nepresných informácií",
    "ue.meta.34": "relevantné predchádzajúce porušenia zo strany subjektu",
    "ue.meta.35": "spôsobené majetkové a nemajetkové škody vrátane finančných strát, vplyvu na iné služby a počtu dotknutých používateľov",
    "ue.meta.36": "úmyselná alebo nedbanlivostná povaha konania",
    "ue.meta.37": "opatrenia prijaté na zabránenie škodám alebo ich zmiernenie",
    "ue.meta.38": "dodržiavanie schválených kódexov správania alebo mechanizmov certifikácie",
    "ue.meta.39": "miera spolupráce s príslušnými orgánmi",
    "ue.meta.4": "Smernica Európskeho parlamentu a Rady (EÚ) 2022/2555 (NIS 2)",
    "ue.meta.40": "Smernica výslovne neustanovuje upustenie od pokuty — či a kedy je možné, rozhoduje národné právo.",
    "ue.meta.41": "Od tohto dátumu majú členské štáty uplatňovať národné predpisy transponujúce smernicu. Konkrétny dátum, od ktorého môže orgán uložiť pokutu, vyplýva z národného práva.",
    "ue.meta.42": "Nadobudnutie účinnosti smernice NIS 2",
    "ue.meta.43": "Dvadsiatym dňom po uverejnení v Úradnom vestníku.",
    "ue.meta.44": "Lehota na transpozíciu smernice",
    "ue.meta.45": "Do tohto dátumu mali členské štáty prijať a uverejniť národné predpisy.",
    "ue.meta.46": "Uplatňovanie národných predpisov a zrušenie NIS 1",
    "ue.meta.47": "Od tohto dátumu štáty uplatňujú transpozičné predpisy; smernica (EÚ) 2016/1148 sa zrušuje.",
    "ue.meta.48": "Uplatňovanie nariadenia (EÚ) 2024/2690",
    "ue.meta.49": "Vykonávacie nariadenie sa uplatňuje priamo od dvadsiateho dňa po uverejnení.",
    "ue.meta.5": "Ú. v. EÚ L 333, 27.12.2022",
    "ue.meta.50": "Zoznam kľúčových a dôležitých subjektov",
    "ue.meta.51": "Do tohto dátumu členské štáty vytvoria zoznam; subjekty predložia orgánom registračné údaje.",
    "ue.meta.52": "Prvé preskúmanie smernice Komisiou",
    "ue.meta.53": "Komisia preskúma fungovanie smernice a predloží správu.",
    "ue.meta.54": "Včasné varovanie o významnom incidente",
    "ue.meta.55": "24 hodín od okamihu, keď sa subjekt dozvie",
    "ue.meta.56": "Hlásenie významného incidentu",
    "ue.meta.57": "72 hodín od okamihu, keď sa subjekt dozvie",
    "ue.meta.58": "Záverečná správa",
    "ue.meta.59": "mesiac od hlásenia incidentu",
    "ue.meta.6": "Vykonávacie nariadenie Komisie (EÚ) 2024/2690",
    "ue.meta.60": "Hlásenie incidentu poskytovateľom dôveryhodných služieb",
    "ue.meta.61": "čl. 21 ods. 5 smernice (EÚ) 2022/2555; články 1 a 2 nariadenia (EÚ) 2024/2690",
    "ue.meta.62": "Bez údajov o obrate je stropom pevná suma zo smernice.",
    "ue.meta.63": "Stropy podľa čl. 34 ods. 4 a 5 sú minimálne („najmenej“) — národné právo môže ustanoviť vyššie. Sumy v eurách, bez prepočtu na národnú menu.",
    "ue.meta.64": "Príslušný orgán členského štátu",
    "ue.meta.65": "Riadiaci orgán môže niesť zodpovednosť za porušenie článku 21. Rozsah a postup určuje národné právo — tento modul ich nepozná.",
    "ue.meta.66": "Rozsah osobnej zodpovednosti vedenia vyplýva z národného zákona. Pre Poľsko je to až 300 % odmeny (čl. 73a ods. 4 zákona o národnom systéme kybernetickej bezpečnosti); iné štáty to riešia inak.",
    "ue.meta.7": "Ú. v. EÚ L, 2024/2690",
    "ue.meta.8": "Smernica (EÚ) 2022/2555",
    "ue.meta.9": "Lehota na transpozíciu uplynula 17. októbra 2024",
    "ue.moduly.1": "približne {p0} min",
    "ue.moduly.10": "Desať oblastí z čl. 21 ods. 2 písm. a) až j): od politiky rizík po viacfaktorovú autentifikáciu. Porušenie je sankcionované pokutou podľa článku 34. Hodnotenie na škále vyspelosti.",
    "ue.moduly.11": "Nariadenie 2024/2690 — riadenie a procesy",
    "ue.moduly.12": "Oddiely 1–5 a 7–8 prílohy: politiky, riadenie rizík, riešenie incidentov, kontinuita činností, dodávateľský reťazec, posudzovanie účinnosti, kybernetická hygiena. Priamo uplatniteľné od 7. novembra 2024.",
    "ue.moduly.13": "Nariadenie 2024/2690 — technické požiadavky",
    "ue.moduly.14": "Oddiely 6 a 9–13 prílohy: obstarávanie a vývoj systémov, kryptografia, bezpečnosť ľudských zdrojov, riadenie prístupu, správa aktív, fyzická bezpečnosť a bezpečnosť prostredia.",
    "ue.moduly.2": "približne {p0} h {p1} min",
    "ue.moduly.3": "približne {p0} h",
    "ue.moduly.4": "menej ako minúta",
    "ue.moduly.5": "Rýchle posúdenie rizík",
    "ue.moduly.6": "Nadradené otázky zo všetkých oblastí smernice. Každá rozhoduje o celej skupine tém. Umožňuje odhadnúť rozsah restov bez prechodu celým dotazníkom.",
    "ue.moduly.7": "Povinnosti zo smernice",
    "ue.moduly.8": "Registračné údaje, hlásenie incidentov do 24 a 72 hodín, povinnosti riadiaceho orgánu, pripravenosť na dohľad. Overiteľné z dokumentov, bez technickej analýzy.",
    "ue.moduly.9": "Opatrenia na riadenie rizík — čl. 21 ods. 2",
    "ue.obowiazki.1": "Registračné údaje pre zoznam subjektov",
    "ue.obowiazki.10": "Hlásenie významných incidentov",
    "ue.obowiazki.11": "Subjekt hlási významné incidenty jednotke CSIRT alebo príslušnému orgánu v troch krokoch: včasné varovanie, hlásenie, záverečná správa. Lehoty plynú od okamihu, keď sa subjekt o incidente dozvie.",
    "ue.obowiazki.12": "Je subjekt schopný odovzdať včasné varovanie do 24 hodín od okamihu, keď sa o významnom incidente dozvie, s uvedením, či je incident pravdepodobne spôsobený protiprávnym konaním a či môže mať cezhraničný vplyv?",
    "ue.obowiazki.13": "24 hodín od okamihu, keď sa subjekt dozvie",
    "ue.obowiazki.14": "Je subjekt schopný odovzdať hlásenie incidentu do 72 hodín s prvotným posúdením závažnosti a vplyvu a s indikátormi kompromitácie?",
    "ue.obowiazki.15": "72 hodín od okamihu, keď sa subjekt dozvie",
    "ue.obowiazki.16": "Odovzdáva subjekt záverečnú správu najneskôr mesiac po hlásení, s opisom incidentu, druhom hrozby, nápravnými opatreniami a cezhraničným vplyvom?",
    "ue.obowiazki.17": "mesiac od hlásenia",
    "ue.obowiazki.18": "Informuje subjekt príjemcov svojich služieb o významných incidentoch, ktoré môžu nepriaznivo ovplyvniť poskytovanie týchto služieb?",
    "ue.obowiazki.19": "Informuje subjekt príjemcov služieb o významnej kybernetickej hrozbe a o nápravných opatreniach, ktoré môžu príjemcovia prijať?",
    "ue.obowiazki.2": "Členské štáty vytvoria zoznam kľúčových a dôležitých subjektov a vyžadujú od subjektov predloženie registračných údajov. Postup, lehotu a portál určuje národné právo.",
    "ue.obowiazki.20": "Ak je subjekt poskytovateľom dôveryhodných služieb — hlási významné incidenty do 24 hodín od okamihu, keď sa o nich dozvie?",
    "ue.obowiazki.21": "týka sa poskytovateľov dôveryhodných služieb",
    "ue.obowiazki.22": "Riadiaci orgán",
    "ue.obowiazki.23": "Riadiaci orgán schvaľuje opatrenia na riadenie rizík, dohliada na ich vykonávanie a môže niesť zodpovednosť. Členovia orgánu sa pravidelne zúčastňujú na školeniach.",
    "ue.obowiazki.24": "Schválil riadiaci orgán formálne opatrenia na riadenie kybernetických bezpečnostných rizík prijaté na zabezpečenie súladu s článkom 21?",
    "ue.obowiazki.25": "Dohliada riadiaci orgán na vykonávanie týchto opatrení zdokumentovaným spôsobom — napríklad pravidelnými správami a preskúmaniami?",
    "ue.obowiazki.26": "Zúčastňujú sa členovia riadiaceho orgánu pravidelne na školeniach umožňujúcich rozpoznať riziká a posúdiť postupy riadenia rizík, a je účasť zdokumentovaná?",
    "ue.obowiazki.27": "Pripravenosť na dohľadové úkony",
    "ue.obowiazki.28": "Kľúčový subjekt podlieha dohľadu ex ante aj ex post, dôležitý subjekt iba ex post. Orgán môže požadovať informácie, dôkazy o zavedení politík a výsledky auditov.",
    "ue.obowiazki.29": "Je subjekt schopný na žiadosť orgánu predložiť dôkazy o zavedení politík kybernetickej bezpečnosti vrátane výsledkov bezpečnostných auditov?",
    "ue.obowiazki.3": "Určil subjekt, či je kľúčovým alebo dôležitým subjektom, na základe odvetvia z prílohy I alebo II a veľkosti podniku?",
    "ue.obowiazki.30": "Je subjekt schopný na žiadosť orgánu sprístupniť údaje, dokumenty a informácie nevyhnutné na výkon dohľadových úloh?",
    "ue.obowiazki.31": "Je kľúčový subjekt pripravený na bezpečnostný audit vykonávaný orgánom alebo nezávislým subjektom na vlastné náklady?",
    "ue.obowiazki.4": "Predložil subjekt príslušnému orgánu registračné údaje: názov, adresu a kontaktné údaje, odvetvie a pododvetvie, zoznam členských štátov, v ktorých poskytuje služby?",
    "ue.obowiazki.5": "Kontaktné údaje zahŕňajú e-mailové adresy, rozsahy IP adries a telefónne čísla. Národnú lehotu a registračný portál určuje právo členského štátu.",
    "ue.obowiazki.6": "Existuje proces aktualizácie registračných údajov bez zbytočného odkladu po ich zmene?",
    "ue.obowiazki.7": "Smernica vyžaduje aktualizáciu bez zbytočného odkladu; konkrétna lehota — napríklad 14 dní v Poľsku — vyplýva z národného práva.",
    "ue.obowiazki.8": "Ak je subjekt poskytovateľom DNS, registrom TLD, poskytovateľom cloudu, dátového centra, CDN, riadených služieb, online trhoviskom, vyhľadávačom alebo sociálnou sieťou — predložil dodatočné údaje podľa článku 27 vrátane adresy hlavnej prevádzkarne v Únii?",
    "ue.obowiazki.9": "týka sa subjektov podľa čl. 26 ods. 1",
    "ue.role.1": "Príslušný orgán členského štátu",
    "ue.role.10": "Služby dátového centra: kolokácia, hosting infraštruktúry a súvisiace služby.",
    "ue.role.11": "Dátové centrá",
    "ue.role.12": "Kľúčový subjekt nad prahom stredného podniku (čl. 3 ods. 1 písm. a)), dôležitý pri strednej veľkosti (čl. 3 ods. 2). Pod strednou veľkosťou — mimo pôsobnosti, pokiaľ členský štát subjekt neurčí podľa čl. 2 ods. 2 písm. b) až e). Dotknutý nariadením 2024/2690.",
    "ue.role.13": "Poskytovateľ výmenného uzla internetu",
    "ue.role.14": "Infraštruktúra umožňujúca výmenu prevádzky medzi nezávislými sieťami.",
    "ue.role.15": "Výmenné uzly internetu",
    "ue.role.16": "Klasifikácia podľa veľkosti (čl. 3 ods. 1 písm. a) a ods. 2). Nariadenie 2024/2690 sa na výmenné uzly internetu nevzťahuje — článok 1 nariadenia obsahuje uzavretý výpočet adresátov.",
    "ue.role.17": "Poskytovateľ služieb DNS",
    "ue.role.18": "Služby prekladu doménových mien s výnimkou prevádzkovateľov koreňových menných serverov.",
    "ue.role.19": "Systém doménových mien",
    "ue.role.2": "príslušný orgán",
    "ue.role.20": "Kľúčový subjekt bez ohľadu na veľkosť (čl. 3 ods. 1 písm. b)). Dotknutý nariadením 2024/2690.",
    "ue.role.21": "Register TLD",
    "ue.role.22": "Vedenie registra domény najvyššej úrovne.",
    "ue.role.23": "Kľúčový subjekt bez ohľadu na veľkosť (čl. 3 ods. 1 písm. b)). Navyše povinnosti týkajúce sa registračných údajov podľa článku 28. Dotknutý nariadením 2024/2690.",
    "ue.role.24": "Poskytovateľ služieb cloud computingu",
    "ue.role.25": "Služby cloud computingu: infraštruktúra, platforma, softvér ako služba.",
    "ue.role.26": "Služby cloud computingu",
    "ue.role.27": "Klasifikácia podľa veľkosti (čl. 3 ods. 1 písm. a) a ods. 2). Dotknutý nariadením 2024/2690.",
    "ue.role.28": "Poskytovateľ siete na sprístupňovanie obsahu",
    "ue.role.29": "Sieť distribuovaných serverov sprístupňujúcich obsah a služby koncovým používateľom.",
    "ue.role.3": "určený národným právom; do zavedenia národného modulu nástroj neuvádza konkrétnu inštitúciu",
    "ue.role.30": "Siete na sprístupňovanie obsahu",
    "ue.role.31": "Poskytovateľ dôveryhodných služieb",
    "ue.role.32": "Dôveryhodné služby v zmysle nariadenia (EÚ) č. 910/2014: podpisy, pečate, časové pečiatky, certifikáty.",
    "ue.role.33": "Dôveryhodné služby",
    "ue.role.34": "Smernicou dotknutý bez ohľadu na veľkosť (čl. 2 ods. 2 písm. a) bod ii)). Kvalifikovaný poskytovateľ je kľúčovým subjektom bez ohľadu na veľkosť (čl. 3 ods. 1 písm. b)); nekvalifikovaný je kľúčovým nad prahom stredného podniku, inak dôležitým. Dotknutý nariadením 2024/2690.",
    "ue.role.35": "Poskytovateľ riadených služieb",
    "ue.role.36": "Správa infraštruktúry IKT zákazníka: inštalácia, údržba, podpora, správa systémov.",
    "ue.role.37": "Riadenie služieb IKT (B2B)",
    "ue.role.38": "Riadené služby",
    "ue.role.39": "Poskytovateľ riadených bezpečnostných služieb",
    "ue.role.4": "Poskytovateľ verejných elektronických komunikačných sietí alebo verejne dostupných elektronických komunikačných služieb",
    "ue.role.40": "Riadené služby v oblasti kybernetickej bezpečnosti: monitorovanie, reakcia na incidenty, testy, poradenstvo.",
    "ue.role.41": "Riadené bezpečnostné služby",
    "ue.role.42": "Smernica klasifikuje podľa veľkosti (čl. 3 ods. 1 písm. a) a ods. 2). Členské štáty môžu prah sprísniť — Poľsko považuje MSSP za kľúčový subjekt už od malého podniku; tento modul uplatňuje výlučne pravidlo smernice. Dotknutý nariadením 2024/2690.",
    "ue.role.5": "Poskytovanie verejných elektronických komunikačných sietí alebo verejne dostupných elektronických komunikačných služieb vrátane prístupu k internetu.",
    "ue.role.6": "Digitálna infraštruktúra",
    "ue.role.7": "Elektronické komunikácie",
    "ue.role.8": "Smernicou dotknutý bez ohľadu na veľkosť (čl. 2 ods. 2 písm. a) bod i)). Stredný alebo väčší podnik je kľúčovým subjektom (čl. 3 ods. 1 písm. c)), mikropodnik a malý podnik dôležitým (čl. 3 ods. 2). Národný zákon o elektronických komunikáciách môže ukladať ďalšie povinnosti — tento modul ich neobsahuje.",
    "ue.role.9": "Poskytovateľ služieb dátového centra",
    "ue.role.podstawaArt3b": "čl. 3 ods. 1 písm. b) smernice (EÚ) 2022/2555",
    "ue.zaslepki.1": "Smernica Európskeho parlamentu a Rady (EÚ) 2022/2555 (NIS 2)",
    "ue.zaslepki.10": "Či je časť subjektov zapisovaná z úradnej moci, rozhoduje národné právo.",
    "ue.zaslepki.11": "Zistite, či podliehate smernici",
    "ue.zaslepki.12": "Odvetvie z prílohy I alebo II a veľkosť podniku. Túto časť vykonáva profil subjektu v tomto nástroji.",
    "ue.zaslepki.13": "Zistite príslušný orgán vo svojom štáte",
    "ue.zaslepki.14": "Každý štát určí príslušný orgán (čl. 8 ods. 1). Aktuálny zoznam vedie ENISA a Komisia.",
    "ue.zaslepki.15": "Predložte registračné údaje",
    "ue.zaslepki.16": "Názov, adresa a kontaktné údaje, odvetvie a pododvetvie, štáty poskytovania služieb (čl. 3 ods. 4). Postup podľa národného práva.",
    "ue.zaslepki.17": "Aktualizujte údaje bez zbytočného odkladu",
    "ue.zaslepki.18": "Každá zmena registračných údajov vyžaduje aktualizáciu (čl. 3 ods. 5).",
    "ue.zaslepki.19": "adresa a aktuálne kontaktné údaje: e-mailové adresy, rozsahy IP adries, telefónne čísla",
    "ue.zaslepki.2": "Ú. v. EÚ L 333, 27.12.2022, s. 80",
    "ue.zaslepki.20": "odvetvie a pododvetvie z prílohy I alebo II",
    "ue.zaslepki.21": "zoznam členských štátov, v ktorých subjekt poskytuje služby",
    "ue.zaslepki.22": "Určuje národné právo.",
    "ue.zaslepki.23": "Smernica (EÚ) 2022/2555 — článok 3",
    "ue.zaslepki.24": "ENISA — príslušné orgány členských štátov",
    "ue.zaslepki.25": "Smernica (EÚ) 2022/2555",
    "ue.zaslepki.26": "Únijný modul neobsahuje usmernenia národného orgánu — tie prídu s modulom národného práva.",
    "ue.zaslepki.27": "Automatické načítanie údajov z registra funguje len pre štáty s modulom národného práva. Vyplňte profil ručne.",
    "ue.zaslepki.28": "Načítanie účtovnej závierky funguje len pre štáty s modulom národného práva. Zadajte obrat a počet zamestnancov ručne.",
    "ue.zaslepki.3": "Vykonávacie nariadenie Komisie (EÚ) 2024/2690",
    "ue.zaslepki.4": "Ú. v. EÚ L, 2024/2690, 18.11.2024",
    "ue.zaslepki.5": "Smernica NIS 2 neobsahuje samostatnú vrstvu elektronických komunikácií. Národné právo elektronických komunikácií môže ukladať ďalšie povinnosti — tento modul ich nepozná.",
    "ue.zaslepki.6": "Zoznam kľúčových a dôležitých subjektov",
    "ue.zaslepki.7": "Príslušný orgán členského štátu.",
    "ue.zaslepki.8": "Smernica ukladá členským štátom viesť zoznam kľúčových a dôležitých subjektov a vyžadovať od subjektov predloženie registračných údajov. Portál, postup a lehotu určuje národné právo — tento modul ich nepozná, pretože modul národného práva pre vybraný štát ešte nie je hotový.",
    "ue.zaslepki.9": "Všetky kľúčové a dôležité subjekty. Lehotu určuje národné právo.",
    "ue.zaslepki.skrotDyrektywy": "smernica NIS 2",
    "ue.zaslepki.skrotReg2690": "nar. 2024/2690",
    "xlsx.1": "{p0} – {p1} EUR",
    "xlsx.25": "Výmenný kurz",
    "xlsx.4": "SPRÁVA O SÚLADE SO SMERNICOU NIS 2 (EÚ) 2022/2555",
    "xlsx.58": "Činnosť v oblasti elektronických komunikácií: nariadenie (EÚ) 2024/2690 sa neuplatňuje. Prahové hodnoty určuje národné právo (čl. 23 ods. 11 smernice) — spoločný modul ich nepozná.",
    "xlsx.68": "Nástroj slúži na sebahodnotenie. Nie je auditom ani právnym stanoviskom.",
    "xlsx.69": "Pre subjekty, na ktoré sa nevzťahuje nariadenie (EÚ) 2024/2690, určuje prahové hodnoty významného incidentu národné právo (čl. 23 ods. 11 smernice).",
    "xlsx.70": "Roly uvedené v profile sú vyhlásením. O statuse rozhoduje skutočne vykonávaná činnosť (článok 3 smernice (EÚ) 2022/2555).",
    "xlsx.etykietaKrs": "Registrové číslo",
    "xlsx.etykietaNip": "Identifikačné číslo",
    "xlsx.etykietaRegon": "Štatistické číslo"
});
