/* Teksty modułu ue — język: sl.
   Te same klucze co w napisy/pl.js (wersja źródłowa); wstawki {p0}, {p1}…
   pozostają bez zmian. Klucze ue.cyt.* to wzorce składania odesłań
   do przepisów w tym języku — patrz kraje/ue/cytaty.js. */
KRAJE.napisy('ue', 'sl', {
    "app.10": "Preverite seznam vlog spodaj — o statusu odloča dejansko opravljana dejavnost (člen 3 Direktive (EU) 2022/2555), ne vpis v register.",
    "app.14": "Predhodno leto: {p0} EUR",
    "app.15": "Prihodki za poročevalsko obdobje: {p0} EUR",
    "app.19": "Poizvedujem po registrih po številki {p0}…",
    "app.34": " mrd. EUR",
    "app.35": " mio. EUR",
    "app.36": " tis. EUR",
    "app.37": "",
    "app.4": "Samodejno pridobivanje podatkov iz registra za to državo ni na voljo — profil izpolnite ročno.",
    "app.59": "Ocena skladnosti z Direktivo NIS 2 (JSON)",
    "app.68": "Za to državo ni registra, iz katerega bi orodje lahko pridobilo podatke — profil se izpolni ročno.",
    "app.69": "Za to državo ni registra, iz katerega bi orodje lahko pridobilo podatke. Kliknite za vklop načina brez povezave.",
    "app.73": " · izkaz poslovnega izida v različici ",
    "app.74": "<div class=\"mt-2 tekst-uwaga\">Iz registrskih podatkov ne izhaja nobena vloga iz sektorja digitalne infrastrukture. Vloge izberite ročno spodaj.</div>",
    "app.8": "Potrjen vpis v register ponudnikov elektronskih komunikacij",
    "app.progDostawcy": "",
    "app.przyklad.adres": "Vzorčna ulica 1, 1000 Mesto",
    "app.przyklad.forma": "Družba z omejeno odgovornostjo",
    "app.przyklad.nazwa": "Vzorčni operater d.o.o.",
    "app.statusVat": " · status DDV: ",
    "dashboard.1": "Na podlagi prijavljenih vlog in velikosti subjekt ni niti bistveni niti pomembni subjekt v smislu člena 3 Direktive (EU) 2022/2555. Preverite profil, če rezultat ne ustreza pričakovanju.",
    "dashboard.113": "Pogosta vprašanja",
    "dashboard.12": "— {p0}; rok za prenos v nacionalno pravo je potekel {p2}",
    "dashboard.123": "Direktiva NIS 2",
    "dashboard.30": "Seznam bistvenih in pomembnih subjektov",
    "dashboard.4": "— neposredno uporabljiva od {p0} v vseh državah članicah, brez prenosa",
    "dashboard.42": "Zneskovna različica: {p0}",
    "dashboard.45": "Merila iz člena 32(7) direktive:",
    "dashboard.46": "Skupaj",
    "dashboard.49": "Subjekt opravlja dejavnost elektronskih komunikacij — odgovornost vodilne osebe določa nacionalno pravo",
    "dashboard.50": "",
    "dashboard.51": "",
    "dashboard.53": "Periodična kazen za zamudo pri izvršitvi odločbe: od {p0} EUR do {p1} EUR na dan ({p2})",
    "dashboard.54": "Kvalificirani primer: do {p0} EUR ({p1})",
    "dashboard.57": "({p0}). Od kdaj lahko nacionalni organ izreka globe, določa zakon o prenosu direktive — ta modul ga ne pozna. Obveznosti uvedbe izhajajo iz nacionalnega prava od dneva njegove uveljavitve.",
    "dashboard.65": "({p0}). Od kdaj lahko nacionalni organ izreka globe, določa zakon o prenosu direktive — ta modul ga ne pozna. Finančno tveganje zato tu ni datirano, obveznosti uvedbe pa izhajajo iz nacionalnega prava od dneva njegove uveljavitve.",
    "dashboard.83": "Dejavnost elektronskih komunikacij — pragove določa nacionalno pravo.",
    "dashboard.84": "Uredba (EU) 2024/2690 se ne uporablja za ponudnike javnih elektronskih komunikacijskih omrežij in storitev. Zanje pragove pomembnega incidenta določa nacionalno pravo (člen 23(11) direktive) — ta modul jih ne pozna, zato ne navaja številčnih vrednosti.",
    "dashboard.terminRejestracji": "Rok za predložitev registracijskih podatkov določa nacionalno pravo (člen 3(4) direktive). Ponudniki iz člena 27(1) — storitev DNS, registri vrhnjih domen, ponudniki storitev v oblaku, podatkovnih centrov, omrežij za dostavo vsebin, upravljanih storitev in upravljanih varnostnih storitev — podatke posredujejo v register agencije ENISA: prvotno do 17. januarja 2025, vsako spremembo pa brez nepotrebnega odlašanja.",
    "html.1": "ITORO — Ocena skladnosti z Direktivo NIS 2 (EU) 2022/2555",
    "html.10": "Ocena skladnosti z Direktivo NIS 2 — skupni modul",
    "html.100": "Branje računovodskega poročila deluje le za države z modulom nacionalnega prava. Za to državo <strong>prihodke</strong> za poslovno leto vnesete ročno — od njih je odvisna višina globe.",
    "html.102": "Samodejno pridobivanje podatkov iz registrov deluje le za države z modulom nacionalnega prava. Vloge in velikost podjetja navedete ročno.",
    "html.11": "Direktiva (EU) 2022/2555 (NIS 2) zahteva prenos v nacionalno pravo. Ocena zajema obveznosti, ki izhajajo neposredno iz direktive, in neposredno uporabljivo Izvedbeno uredbo Komisije (EU) 2024/2690 — v obsegu, v katerem zadevajo subjekt.",
    "html.23": "prihodke in velikost vnesete ročno — skupni modul ne poizveduje po nacionalnih registrih",
    "html.33": "Direktiva (EU) 2022/2555 Evropskega parlamenta in Sveta z dne 14. decembra 2022 (NIS 2)",
    "html.33a": "{p0} — nacionalni akt za prenos direktive; njegovih zahtev ta modul še ne ocenjuje",
    "html.33b": "država še ni sprejela akta za prenos — ocena sledi pravu Unije",
    "html.35": "obveznosti upravljalnega organa — člen 20 direktive",
    "html.36": "Orodje služi samooceni. Ni revizija niti pravno mnenje.",
    "html.40": "skupni modul ne vzpostavlja nobenih izhodnih povezav — ne poizveduje po registrih",
    "html.59": "Računovodska poročila",
    "html.60": "Branje računovodskega poročila je na voljo le za države z modulom nacionalnega prava. Za to državo prihodke in število zaposlenih vnesete ročno.",
    "html.62": "Iskanje v registru",
    "html.63": "poslovni registri so nacionalni — skupni modul jih ne pozna",
    "html.64": "vloge in velikost podjetja navedete ročno",
    "html.66": "Identifikacijska številka subjekta",
    "html.68": "Samodejno pridobivanje podatkov iz registrov deluje le za države z modulom nacionalnega prava.",
    "html.76": "Letni prihodki (EUR)",
    "html.78": "Prihodki iz dejavnosti elektronskih komunikacij (EUR)",
    "html.79": "Polje zadeva ponudnike javnih elektronskih komunikacijskih omrežij ali storitev. Nacionalne pragove določa pravo države članice.",
    "html.80": "Mesečni prejemki vodje (EUR)",
    "html.82": "Menjalni tečaj",
    "html.83": "Zgornje meje glob v direktivi so izražene v evrih. Preračun v nacionalno valuto in tečaj določa nacionalno pravo — tu so zneski navedeni v evrih brez preračuna.",
    "html.84": "Status izhaja izključno iz združevanja podatkov povezanih podjetij, informacijski sistem subjekta pa je neodvisen (uvodna izjava 16 direktive — o uporabi odloča nacionalno pravo)",
    "html.85": "Subjekt deluje na področju nacionalne varnosti, javne varnosti, obrambe ali preprečevanja, odkrivanja in preiskovanja kaznivih dejanj (člen 2(7) direktive)",
    "html.91": "Ocena skladnosti z Direktivo (EU) 2022/2555 Evropskega parlamenta in Sveta (NIS 2) in z Izvedbeno uredbo Komisije (EU) 2024/2690 — skupni modul za države, katerih modul nacionalnega prava še ni pripravljen.",
    "html.94": "ali je subjekt <strong>bistveni</strong>, <strong>pomembni</strong> ali zunaj področja uporabe direktive",
    "html.daneZeSprawozdania": "ime, identifikacijska številka, naslov sedeža",
    "html.rejestrMozliwy": "Register {p0} je javen in brezplačen — branje iz njega je mogoče dodati; veseli smo pull requestov (glej README).",
    "html.tytulNaglowka": "Ocena skladnosti z Direktivo NIS 2",
    "html.zrodlaRecznie": "Ta modul ne pozna registrov vaše države — profil izpolnite ročno. Letni promet določa zgornjo mejo globe, zato ga vnesite natančno.",
    "klasyfikacja.10": "člen 3(1), točka (c), Direktive (EU) 2022/2555 (ponudnik javnih elektronskih komunikacijskih omrežij ali javno dostopnih elektronskih komunikacijskih storitev, ki je vsaj srednje podjetje)",
    "klasyfikacja.11": "člen 3(2) v povezavi s členom 2(2), točka (a)(i), Direktive (EU) 2022/2555 (ponudnik javnih elektronskih komunikacijskih omrežij ali storitev, ki je mikro ali malo podjetje)",
    "klasyfikacja.12": "člen 3(1), točka (a), Direktive (EU) 2022/2555 (ponudnik upravljanih varnostnih storitev, ki presega zgornje meje za srednje podjetje)",
    "klasyfikacja.13": "Mikro in mala podjetja iz naslova te vloge niso zajeta v direktivo (člen 2(1), a contrario).",
    "klasyfikacja.15": "člen 3(1), točka (b), Direktive (EU) 2022/2555 (kvalificirani ponudnik storitev zaupanja) — ne glede na velikost podjetja",
    "klasyfikacja.16": "člen 3(2) v povezavi s členom 2(2), točka (a)(ii), Direktive (EU) 2022/2555 (nekvalificirani ponudnik storitev zaupanja, ki je mikro, malo ali srednje podjetje)",
    "klasyfikacja.18": "člen 3(2) Direktive (EU) 2022/2555 (subjekt javne uprave na regionalni ravni, če država članica tako določi — člen 2(2), točka (f)(ii))",
    "klasyfikacja.19": "člen 3(1), točka (f), Direktive (EU) 2022/2555 (subjekt javne uprave na osrednji ravni — člen 2(2), točka (f)(i))",
    "klasyfikacja.2": "Predhodni in naknadni nadzor (člen 32 Direktive (EU) 2022/2555).",
    "klasyfikacja.20": "člen 3(2) Direktive (EU) 2022/2555 (subjekt javne uprave na regionalni ravni — člen 2(2), točka (f)(ii))",
    "klasyfikacja.21": "Obseg obveznosti subjektov javne uprave na lokalni ravni določa nacionalno pravo (člen 2(5), točka (a), direktive).",
    "klasyfikacja.22": "Država članica lahko izvzame subjekte, ki delujejo na področju nacionalne varnosti, javne varnosti, obrambe ali preprečevanja, odkrivanja in preiskovanja kaznivih dejanj (člen 2(7) direktive). Izvzetje ne deluje samo od sebe — rezultat ocene preverite po nacionalnem pravu.",
    "klasyfikacja.23": "Subjekt izpolnjuje merila tako bistvenega kot pomembnega subjekta. Je bistveni subjekt (člen 3(1) direktive), strožje zahteve pa se uporabljajo za celotno dejavnost, zajeto v direktivo.",
    "klasyfikacja.25": "Subjekt je bistven, zato zanj veljata celoten katalog ukrepov iz člena 21(2) direktive ter predhodni in naknadni nadzor — ocena zajema celoten sklop vprašanj.",
    "klasyfikacja.26": "Kot pomembni subjekt ste podrejeni istemu katalogu ukrepov iz člena 21(2), vendar le naknadnemu nadzoru (člen 33). Zgornja meja globe je nižja: 7 mio. EUR ali 1,4 % prometa (člen 34(5)). Olajšave za javne subjekte lahko uvede nacionalno pravo — ta modul jih ne pozna.",
    "klasyfikacja.28": "Obveznosti subjektov javne uprave izhajajo iz člena 2(2), točka (f), direktive; njihov natančen obseg, tudi za lokalno raven in izobraževalne ustanove, določa nacionalno pravo (člen 2(5)).",
    "klasyfikacja.29": "Prijavljeno je, da status subjekta izhaja izključno iz združevanja podatkov povezanih ali partnerskih podjetij in da je informacijski sistem subjekta neodvisen. Direktiva tako izključitev dopušča (uvodna izjava 16), vendar o njej odloča nacionalno pravo — modul izključitev sprejme, treba pa jo je preveriti po pravu države članice in dokumentirati.",
    "klasyfikacja.4": "Samo naknadni nadzor — ob dokazih, znakih ali informacijah o kršitvi (člen 33 Direktive (EU) 2022/2555).",
    "klasyfikacja.5": "Zunaj področja uporabe direktive",
    "klasyfikacja.6": "Za navedeno vlogo iz Direktive (EU) 2022/2555 ne izhajajo obveznosti.",
    "klasyfikacja.7": "člen 3(1), točka (a), Direktive (EU) 2022/2555 (subjekt vrste iz Priloge I, ki presega zgornje meje za srednje podjetje)",
    "klasyfikacja.8": "člen 3(2) Direktive (EU) 2022/2555 (subjekt vrste iz Priloge I, ki izpolnjuje merila za srednje podjetje)",
    "klasyfikacja.9": "Mikro in mala podjetja iz naslova te vloge niso zajeta v direktivo (člen 2(1), a contrario).",
    "kreator.10": "Prihodke za prejšnje leto vnesite ročno.",
    "kreator.35": "<span class=\"text-secondary\">Branje računovodskih poročil za to državo ni na voljo.</span>",
    "kreator.37": "Branje računovodskih poročil za to državo ni na voljo — prihodke vnesite ročno.",
    "kreator.56": "Da — uredba EU se neposredno uporablja od 7. novembra 2024 v vseh državah članicah in nima prehodnega obdobja. Njena podlaga je",
    "kreator.57": ", ki je Komisijo pooblastil za določitev tehničnih in metodoloških zahtev za ponudnike iz člena 3(1) uredbe. Rok za prenos direktive je potekel",
    "kreator.58": ", od kdaj lahko nacionalni organ izreka globe, pa določa nacionalno pravo. Tehnične zahteve iz priloge (oddelki 6 in 9–13) so zavezujoče v sedanjem besedilu — ne čakajo na pojasnitev. Odstopiti je mogoče le od zahtev z izrazom „kadar je ustrezno“, in to izključno z dokumentirano utemeljitvijo.",
    "kreator.9": "Računovodska poročila →",
    "kreator.przepisReg2690": "člen 21(5) Direktive (EU) 2022/2555",
    "kreator.terminReg2690": "17. oktobra 2024",
    "punktacja.10": "Javni subjekti",
    "punktacja.4": "Direktiva NIS 2 — člen 21",
    "punktacja.5": "Direktiva NIS 2 — formalne obveznosti",
    "punktacja.8": "Elektronske komunikacije",
    "punktacja.9": "Direktiva NIS 2 — javni subjekti",
    "punktacja.skrotKsc": "NIS 2",
    "punktacja.skrotPke": "telekom",
    "ue.cyt.akapit": ", {p0} pododstavek",
    "ue.cyt.art": "člen {p0}",
    "ue.cyt.drugi": "drugi",
    "ue.cyt.dyr": "{p0} Direktive (EU) 2022/2555",
    "ue.cyt.i": "in",
    "ue.cyt.laczenie": "",
    "ue.cyt.lit": ", točka ({p0})",
    "ue.cyt.litery": "",
    "ue.cyt.pkt": ", točka {p0}",
    "ue.cyt.rozdzielacz": "; ",
    "ue.cyt.rozp": "{p0} Uredbe (EU) 2024/2690",
    "ue.cyt.ust": "({p0})",
    "ue.katalog.1": "Politike za analizo tveganj in varnost informacijskih sistemov",
    "ue.katalog.10": "Obravnavanje incidentov",
    "ue.katalog.11": "Obravnavanje incidentov zajema ukrepe in postopke za preprečevanje, odkrivanje, analizo in omejevanje incidentov, odzivanje nanje in okrevanje po njih (člen 6, točka 8).",
    "ue.katalog.12": "Ali obstaja dokumentiran postopek obravnavanja incidentov, ki zajema odkrivanje, analizo, omejevanje, odziv in okrevanje?",
    "ue.katalog.13": "ISO/IEC 27001 A.5.24–A.5.26",
    "ue.katalog.14": "Ali postopek omogoča upoštevanje rokov za priglasitev pomembnega incidenta: zgodnje opozorilo v 24 urah, priglasitev v 72 urah, končno poročilo v enem mesecu?",
    "ue.katalog.15": "ISO/IEC 27001 A.5.24",
    "ue.katalog.16": "Ali ima subjekt merila za opredelitev incidenta kot pomembnega, skladna s členom 23(3): hude motnje delovanja ali finančne izgube oziroma znatna škoda za druge osebe?",
    "ue.katalog.17": "ISO/IEC 27001 A.5.25",
    "ue.katalog.18": "Ali se incidenti evidentirajo in ali se ugotovitve iz njihovega obravnavanja uporabljajo za izboljšanje ukrepov?",
    "ue.katalog.19": "ISO/IEC 27001 A.5.27",
    "ue.katalog.2": "Ukrepi temeljijo na pristopu, ki upošteva vse nevarnosti (člen 21(2)). Njihova sorazmernost se ocenjuje ob upoštevanju stopnje izpostavljenosti, velikosti subjekta, verjetnosti incidentov in njihove resnosti (člen 21(1), drugi pododstavek).",
    "ue.katalog.20": "Neprekinjeno poslovanje in krizno upravljanje",
    "ue.katalog.21": "Neprekinjeno poslovanje, kot sta upravljanje varnostnih kopij in okrevanje po katastrofi, ter krizno upravljanje.",
    "ue.katalog.22": "Ali obstaja načrt neprekinjenega poslovanja, ki zajema okrevanje po katastrofi?",
    "ue.katalog.23": "ISO/IEC 27001 A.5.29–A.5.30",
    "ue.katalog.24": "Ali se varnostne kopije izdelujejo, ščitijo in preizkušajo glede možnosti obnove?",
    "ue.katalog.25": "ISO/IEC 27001 A.8.13",
    "ue.katalog.26": "Ali ima subjekt postopke kriznega upravljanja z določenimi vlogami in komunikacijskimi kanali?",
    "ue.katalog.27": "ISO/IEC 27001 A.5.29",
    "ue.katalog.28": "Ali se načrti neprekinjenega poslovanja in okrevanja redno preizkušajo, rezultati pa dokumentirajo?",
    "ue.katalog.29": "ISO/IEC 27001 A.5.30",
    "ue.katalog.3": "Ali ima subjekt dokumentirano politiko za analizo tveganj in varnost informacijskih sistemov, ki jo je odobril upravljalni organ?",
    "ue.katalog.30": "Varnost dobavne verige",
    "ue.katalog.31": "Varnost dobavne verige, vključno z varnostnimi vidiki odnosov med subjektom in njegovimi neposrednimi dobavitelji ali ponudniki storitev. Subjekt upošteva ranljivosti, značilne za vsakega dobavitelja, ter splošno kakovost njegovih izdelkov in praks na področju kibernetske varnosti (člen 21(3)).",
    "ue.katalog.32": "Ali subjekt vodi seznam neposrednih dobaviteljev in ponudnikov storitev z oceno njihovega pomena za varnost omrežij in sistemov?",
    "ue.katalog.33": "ISO/IEC 27001 A.5.19",
    "ue.katalog.34": "Ali se pri izbiri ukrepov do dobaviteljev upoštevajo ranljivosti, značilne za vsakega od njih, ter kakovost njihovih praks kibernetske varnosti in varnega razvoja?",
    "ue.katalog.35": "ISO/IEC 27001 A.5.19, A.5.21",
    "ue.katalog.36": "Ali pogodbe z dobavitelji vsebujejo varnostne zahteve in obveznost obveščanja o incidentih in ranljivostih?",
    "ue.katalog.37": "ISO/IEC 27001 A.5.20",
    "ue.katalog.38": "Ali subjekt upošteva rezultate usklajenih ocen varnostnih tveganj kritičnih dobavnih verig iz člena 22?",
    "ue.katalog.39": "ISO/IEC 27001 A.5.21",
    "ue.katalog.4": "ISO/IEC 27001, točki 5.2, 6.1.2",
    "ue.katalog.40": "Varnost pri pridobivanju, razvoju in vzdrževanju sistemov",
    "ue.katalog.41": "Varnost pri pridobivanju, razvoju in vzdrževanju omrežij in informacijskih sistemov, vključno z obravnavanjem in razkrivanjem ranljivosti.",
    "ue.katalog.42": "Ali se varnostne zahteve določijo pred pridobitvijo ali začetkom razvoja sistema in preverijo pred uvedbo?",
    "ue.katalog.43": "ISO/IEC 27001 A.8.25–A.8.29",
    "ue.katalog.44": "Ali obstaja postopek obravnavanja ranljivosti: prepoznavanje, ocena, odprava v določenem času?",
    "ue.katalog.45": "ISO/IEC 27001 A.8.8",
    "ue.katalog.46": "Ali ima subjekt postopek razkrivanja ranljivosti, vključno s kanalom za sprejemanje prijav tretjih oseb?",
    "ue.katalog.47": "Ali spremembe sistemov potekajo prek nadzorovanega procesa upravljanja sprememb z oceno vpliva na varnost?",
    "ue.katalog.48": "ISO/IEC 27001 A.8.32",
    "ue.katalog.49": "Ocenjevanje učinkovitosti ukrepov",
    "ue.katalog.5": "Ali analiza tveganj zajema vse nevarnosti za omrežja in informacijske sisteme ter njihovo fizično okolje, ne le kibernetskih groženj?",
    "ue.katalog.50": "Politike in postopki za ocenjevanje učinkovitosti ukrepov za obvladovanje tveganj za kibernetsko varnost.",
    "ue.katalog.51": "Ali obstaja dokumentirana politika ocenjevanja učinkovitosti ukrepov, ki določa obseg, pogostost in metode?",
    "ue.katalog.52": "ISO/IEC 27001, točka 9.1",
    "ue.katalog.53": "Ali se ocene učinkovitosti izvajajo redno in ali se njihovi rezultati posredujejo upravljalnemu organu?",
    "ue.katalog.54": "ISO/IEC 27001, točki 9.2–9.3",
    "ue.katalog.55": "Ali ugotovljene pomanjkljivosti vodijo do dokumentiranih popravljalnih ukrepov z lastnikom in rokom?",
    "ue.katalog.56": "ISO/IEC 27001, točka 10.1",
    "ue.katalog.57": "Kibernetska higiena in usposabljanje",
    "ue.katalog.58": "Osnovne prakse kibernetske higiene in usposabljanje na področju kibernetske varnosti. Člani upravljalnega organa se redno usposabljajo (člen 20(2)).",
    "ue.katalog.59": "Ali subjekt uporablja osnovne prakse kibernetske higiene: posodobitve, upravljanje gesel, omejevanje pravic, zaščito pred zlonamerno programsko opremo?",
    "ue.katalog.6": "ISO/IEC 27001, točka 6.1.2",
    "ue.katalog.60": "ISO/IEC 27001 A.8.7, A.8.8",
    "ue.katalog.61": "Ali se zaposleni usposabljajo na področju kibernetske varnosti glede na svojo vlogo in ali je udeležba dokumentirana?",
    "ue.katalog.62": "ISO/IEC 27001 A.6.3",
    "ue.katalog.63": "Ali se člani upravljalnega organa redno usposabljajo, da lahko prepoznajo tveganja in ocenijo prakse obvladovanja tveganj?",
    "ue.katalog.64": "ISO/IEC 27001, točka 7.2",
    "ue.katalog.65": "Kriptografija in šifriranje",
    "ue.katalog.66": "Politike in postopki za uporabo kriptografije in, kadar je ustrezno, šifriranja.",
    "ue.katalog.67": "Ali obstaja politika uporabe kriptografije, ki določa, kateri podatki in kanali se šifrirajo in s katerimi algoritmi?",
    "ue.katalog.68": "ISO/IEC 27001 A.8.24",
    "ue.katalog.69": "Ali se kriptografski ključi upravljajo v celotnem življenjskem ciklu: generiranje, distribucija, hramba, rotacija, umik?",
    "ue.katalog.7": "Ali izbira ukrepov upošteva najsodobnejša dognanja, ustrezne evropske in mednarodne standarde ter stroške uvedbe?",
    "ue.katalog.70": "Človeški viri, nadzor dostopa in upravljanje sredstev",
    "ue.katalog.71": "Varnost človeških virov, politike nadzora dostopa in upravljanje sredstev.",
    "ue.katalog.72": "Ali subjekt vodi posodobljen seznam sredstev z dodeljenimi lastniki in klasifikacijo?",
    "ue.katalog.73": "ISO/IEC 27001 A.5.9, A.5.12",
    "ue.katalog.74": "Ali obstaja politika nadzora dostopa, ki temelji na načelu najmanjših pravic, z rednim pregledom pravic?",
    "ue.katalog.75": "ISO/IEC 27001 A.5.15, A.5.18",
    "ue.katalog.76": "Ali se ob zaposlitvi, spremembi delovnega mesta in odhodu zaposlenega uporabljajo varnostni postopki, vključno z odvzemom pravic in vračilom sredstev?",
    "ue.katalog.77": "ISO/IEC 27001 A.6.1–A.6.5",
    "ue.katalog.78": "Ali je privilegirani dostop omejen, beležen in pregledovan?",
    "ue.katalog.79": "ISO/IEC 27001 A.8.2",
    "ue.katalog.8": "ISO/IEC 27001, točka 6.1.3",
    "ue.katalog.80": "Večfaktorska avtentikacija in zavarovana komunikacija",
    "ue.katalog.81": "Kadar je ustrezno — večfaktorska ali neprekinjena avtentikacija, zavarovane glasovne, video in besedilne komunikacije ter zavarovani sistemi komunikacije v sili znotraj subjekta.",
    "ue.katalog.82": "Ali se večfaktorska ali neprekinjena avtentikacija uporablja tam, kjer to utemeljuje analiza tveganj, zlasti za oddaljeni dostop in privilegirane račune?",
    "ue.katalog.83": "ISO/IEC 27001 A.8.5",
    "ue.katalog.84": "Ali so glasovne, video in besedilne povezave, ki se uporabljajo za službene namene, zavarovane?",
    "ue.katalog.85": "ISO/IEC 27001 A.8.20",
    "ue.katalog.86": "Ali ima subjekt zavarovan sistem notranje komunikacije v sili, neodvisen od osnovne infrastrukture?",
    "ue.katalog.9": "Ali je raven varnosti dokumentirana kot ustrezna obstoječemu tveganju, z utemeljitvijo, ki upošteva velikost subjekta ter družbene in gospodarske učinke incidentov?",
    "ue.kierownictwo.1": "Upravljalni organ bistvenega ali pomembnega subjekta — v kapitalski družbi uprava. Direktiva tega pojma ne opredeljuje; njegov obseg v posamezni državi izhaja iz nacionalnega prava.",
    "ue.kierownictwo.10": "Določiti status subjekta in poskrbeti za registracijo",
    "ue.kierownictwo.11": "Določitev, ali je subjekt bistven ali pomemben, in predložitev registracijskih podatkov pristojnemu organu. Postopek in rok določa nacionalno pravo.",
    "ue.kierownictwo.12": "Uvesti analizo tveganj in varnostno politiko",
    "ue.kierownictwo.13": "Ukrepi, ki temeljijo na pristopu, ki upošteva vse nevarnosti, sorazmerni izpostavljenosti, velikosti subjekta in resnosti incidentov.",
    "ue.kierownictwo.14": "Vzpostaviti obravnavanje in priglašanje incidentov",
    "ue.kierownictwo.15": "Postopek obravnavanja incidentov in zmožnost upoštevanja rokov 24 ur, 72 ur in enega meseca.",
    "ue.kierownictwo.16": "24 h / 72 h / mesec od odkritja",
    "ue.kierownictwo.17": "Zagotoviti neprekinjeno poslovanje",
    "ue.kierownictwo.18": "Načrt neprekinjenega poslovanja, varnostne kopije, okrevanje po katastrofi, krizno upravljanje.",
    "ue.kierownictwo.19": "Urediti dobavno verigo",
    "ue.kierownictwo.2": "Odgovornost upravljalnega organa ne posega v nacionalne predpise o odgovornosti javnih institucij in uradnikov (člen 20(1), drugi pododstavek).",
    "ue.kierownictwo.20": "Seznam dobaviteljev, ocena njihovih ranljivosti in praks, varnostne zahteve v pogodbah.",
    "ue.kierownictwo.21": "Uvesti nadzor dostopa in upravljanje sredstev",
    "ue.kierownictwo.22": "Seznam sredstev, načelo najmanjših pravic, pregledi pravic, večfaktorska avtentikacija tam, kjer to utemeljuje tveganje.",
    "ue.kierownictwo.23": "Meriti učinkovitost ukrepov",
    "ue.kierownictwo.24": "Politika in postopki ocenjevanja učinkovitosti, redni pregledi, popravljalni ukrepi.",
    "ue.kierownictwo.25": "Odobriti",
    "ue.kierownictwo.26": "ukrepe za obvladovanje tveganj za kibernetsko varnost (člen 20(1))",
    "ue.kierownictwo.27": "politiko za analizo tveganj in varnost sistemov",
    "ue.kierownictwo.28": "proračun in vloge pri uvedbi",
    "ue.kierownictwo.29": "Nadzorovati",
    "ue.kierownictwo.3": "Ali poveritev obveznosti drugi osebi izključuje odgovornost, odloča nacionalno pravo. Na Poljskem je ne izključuje (člen 8c(3) zakona o nacionalnem sistemu kibernetske varnosti).",
    "ue.kierownictwo.30": "izvajanje odobrenih ukrepov (člen 20(1))",
    "ue.kierownictwo.31": "rezultate ocene učinkovitosti (člen 21(2), točka (f))",
    "ue.kierownictwo.32": "upoštevanje rokov za priglasitev incidentov (člen 23)",
    "ue.kierownictwo.33": "Dokumentirati",
    "ue.kierownictwo.34": "odločitve o odobritvi in preglede",
    "ue.kierownictwo.35": "udeležbo na usposabljanjih (člen 20(2))",
    "ue.kierownictwo.36": "Član upravljalnega organa",
    "ue.kierownictwo.37": "odobritev ukrepov, nadzor, odločitve, proračun",
    "ue.kierownictwo.38": "Vodja projekta",
    "ue.kierownictwo.39": "usklajevanje uvedbe, časovni načrt, stanje in dokazila",
    "ue.kierownictwo.4": "Odobriti ukrepe za obvladovanje tveganj za kibernetsko varnost",
    "ue.kierownictwo.40": "IT / kibernetska varnost",
    "ue.kierownictwo.41": "analiza tveganj, tehnični ukrepi, obravnavanje incidentov",
    "ue.kierownictwo.42": "Pravna služba / skladnost",
    "ue.kierownictwo.5": "Upravljalni organ odobri ukrepe, sprejete za zagotovitev skladnosti s členom 21. To je odločitev organa, ne oddelka IT — brez nje ukrepi nimajo podlage.",
    "ue.kierownictwo.6": "Nadzorovati izvajanje ukrepov",
    "ue.kierownictwo.7": "Nadzor nad izvajanjem je obveznost upravljalnega organa. Izvedbo je mogoče poveriti, nadzora ne.",
    "ue.kierownictwo.8": "Redno se usposabljati",
    "ue.kierownictwo.9": "Člani upravljalnega organa se redno usposabljajo, da pridobijo znanje za prepoznavanje tveganj in oceno praks obvladovanja tveganj ter njihovega vpliva na storitve subjekta.",
    "ue.kierownictwo.daneRejestracyjne": "registracijski podatki in njihovo posodabljanje (člen 3(4) in (5))",
    "ue.meta.1": "Prevlada odstotna različica: {p0} % prometa je več kot {p1} mio. EUR.",
    "ue.meta.10": "Direktiva obveznosti podjetjem ne nalaga neposredno — to stori nacionalni zakon, ki bi ga morala država članica sprejeti do 17. oktobra 2024. Ta modul prikazuje zahteve v besedilu direktive, ker modul nacionalnega prava za izbrano državo še ni pripravljen ali država direktive ni prenesla.",
    "ue.meta.11": "Obveznosti iz direktive",
    "ue.meta.12": "Seznam subjektov — do 17. aprila 2025",
    "ue.meta.13": "Države članice bi morale do 17. aprila 2025 vzpostaviti seznam bistvenih in pomembnih subjektov ter od subjektov zahtevati predložitev registracijskih podatkov.",
    "ue.meta.14": "Uredba (EU) 2024/2690",
    "ue.meta.15": "Neposredno uporabljiva od 7. novembra 2024",
    "ue.meta.16": "Izvedbena uredba se neposredno uporablja v vseh državah članicah, ne glede na stanje prenosa direktive. Zadeva subjekte iz njenega člena 1: DNS, vrhnje domene, oblak, podatkovne centre, omrežja za dostavo vsebin, upravljane storitve in storitve zaupanja.",
    "ue.meta.17": "člen 16 Uredbe (EU) 2024/2690",
    "ue.meta.18": "Najmanj 10 000 000 EUR ali najmanj 2 % skupnega svetovnega letnega prometa podjetja v predhodnem poslovnem letu — uporabi se višji znesek. To je najnižja zgornja meja: nacionalno pravo jo lahko zviša.",
    "ue.meta.19": "Najmanj 7 000 000 EUR ali 1,4 % skupnega svetovnega letnega prometa — uporabi se višji znesek. Najnižja zgornja meja.",
    "ue.meta.2": "Prevlada fiksni znesek: {p0} mio. EUR je več kot {p1} % prometa.",
    "ue.meta.20": "Direktiva ne predvideva ločene globe za kvalificirano kršitev — to je konstrukcija nacionalnega prava nekaterih držav.",
    "ue.meta.21": "Države članice lahko predvidijo periodične denarne kazni za prisilitev k prenehanju kršitve. Višino določa nacionalno pravo.",
    "ue.meta.22": "Upravljalni organ odobri ukrepe za obvladovanje tveganj, nadzoruje njihovo izvajanje in je lahko odgovoren za kršitev člena 21. Pravila in obseg te odgovornosti določa nacionalno pravo.",
    "ue.meta.23": "Upravljalni organ odobri ukrepe za obvladovanje tveganj za kibernetsko varnost (člen 20(1)).",
    "ue.meta.24": "Upravljalni organ nadzoruje izvajanje teh ukrepov (člen 20(1)).",
    "ue.meta.25": "Člani upravljalnega organa se redno usposabljajo (člen 20(2)).",
    "ue.meta.26": "Pri bistvenem subjektu lahko organ zahteva začasno prepoved opravljanja vodstvenih funkcij (člen 32(5), točka (b)).",
    "ue.meta.27": "Najnižjo zgornjo mejo določa direktiva",
    "ue.meta.28": "Primerjata se dve vrednosti: fiksni znesek v evrih in odstotek skupnega svetovnega letnega prometa podjetja v predhodnem poslovnem letu. Višja od njiju je zgornja meja, ki jo mora država članica vsaj predvideti. Nacionalno pravo jo lahko zviša.",
    "ue.meta.29": "Znesek v okviru zgornje meje določi nacionalni organ",
    "ue.meta.3": "Zgornja meja iz direktive presega letni promet subjekta {p0}-krat. Člen 34(1) zahteva, da je globa sorazmerna z okoliščinami posameznega primera — to je zgornja meja, ne pričakovana globa.",
    "ue.meta.30": "Globa mora biti učinkovita, sorazmerna in odvračilna glede na okoliščine posameznega primera. Organ upošteva vsaj merila iz člena 32(7): težo in trajanje kršitve, prejšnje kršitve, škodo, naklep, popravljalne ukrepe in sodelovanje.",
    "ue.meta.31": "Zgornja meja lahko večkratno presega letni promet — to je zgornja meja, ne pričakovani znesek. Nacionalne minimume, periodične kazni in način odmere določa zakon države članice.",
    "ue.meta.32": "Pri odločanju o naložitvi upravne globe in o njeni višini se v vsakem posameznem primeru ustrezno upoštevajo vsaj elementi iz člena 32(7).",
    "ue.meta.33": "teža kršitve in pomen kršenih določb — za hude se v vsakem primeru štejejo: ponavljajoče se kršitve, nepriglasitev ali neodprava pomembnih incidentov, neodprava pomanjkljivosti v nasprotju z zavezujočimi navodili, oviranje revizij ali spremljanja, posredovanje napačnih ali hudo netočnih informacij",
    "ue.meta.34": "bistvene prejšnje kršitve subjekta",
    "ue.meta.35": "povzročena premoženjska in nepremoženjska škoda, vključno s finančnimi izgubami, vplivom na druge storitve in številom prizadetih uporabnikov",
    "ue.meta.36": "naklepna ali malomarna narava dejanja",
    "ue.meta.37": "ukrepi za preprečitev ali omejitev škode",
    "ue.meta.38": "upoštevanje odobrenih kodeksov ravnanja ali mehanizmov certificiranja",
    "ue.meta.39": "stopnja sodelovanja s pristojnimi organi",
    "ue.meta.4": "Direktiva (EU) 2022/2555 Evropskega parlamenta in Sveta (NIS 2)",
    "ue.meta.40": "Direktiva izrecno ne predvideva odstopa od globe — ali in kdaj je to mogoče, odloča nacionalno pravo.",
    "ue.meta.41": "Od tega datuma morajo države članice uporabljati nacionalne predpise za prenos direktive. Konkreten datum, od katerega lahko organ naloži globo, izhaja iz nacionalnega prava.",
    "ue.meta.42": "Začetek veljavnosti Direktive NIS 2",
    "ue.meta.43": "Dvajseti dan po objavi v Uradnem listu.",
    "ue.meta.44": "Rok za prenos direktive",
    "ue.meta.45": "Do tega datuma bi morale države članice sprejeti in objaviti nacionalne predpise.",
    "ue.meta.46": "Uporaba nacionalnih predpisov in razveljavitev NIS 1",
    "ue.meta.47": "Od tega datuma države uporabljajo predpise za prenos; Direktiva (EU) 2016/1148 se razveljavi.",
    "ue.meta.48": "Uporaba Uredbe (EU) 2024/2690",
    "ue.meta.49": "Izvedbena uredba se neposredno uporablja od dvajsetega dne po objavi.",
    "ue.meta.5": "UL EU L 333, 27.12.2022",
    "ue.meta.50": "Seznam bistvenih in pomembnih subjektov",
    "ue.meta.51": "Do tega datuma države članice vzpostavijo seznam; subjekti organom predložijo registracijske podatke.",
    "ue.meta.52": "Prvi pregled direktive s strani Komisije",
    "ue.meta.53": "Komisija pregleda delovanje direktive in predloži poročilo.",
    "ue.meta.54": "Zgodnje opozorilo o pomembnem incidentu",
    "ue.meta.55": "24 ur od seznanitve",
    "ue.meta.56": "Priglasitev pomembnega incidenta",
    "ue.meta.57": "72 ur od seznanitve",
    "ue.meta.58": "Končno poročilo",
    "ue.meta.59": "mesec od priglasitve incidenta",
    "ue.meta.6": "Izvedbena uredba Komisije (EU) 2024/2690",
    "ue.meta.60": "Priglasitev incidenta s strani ponudnika storitev zaupanja",
    "ue.meta.61": "člen 21(5) Direktive (EU) 2022/2555; člena 1 in 2 Uredbe (EU) 2024/2690",
    "ue.meta.62": "Brez podatkov o prometu je zgornja meja fiksni znesek iz direktive.",
    "ue.meta.63": "Zgornje meje iz člena 34(4) in (5) so najnižje („najmanj“) — nacionalno pravo lahko predvidi višje. Zneski v evrih, brez preračuna v nacionalno valuto.",
    "ue.meta.64": "Pristojni organ države članice",
    "ue.meta.65": "Upravljalni organ je lahko odgovoren za kršitev člena 21. Obseg in postopek določa nacionalno pravo — ta modul ju ne pozna.",
    "ue.meta.66": "Obseg osebne odgovornosti vodstva izhaja iz nacionalnega zakona. Za Poljsko je to do 300 % prejemkov (člen 73a(4) zakona o nacionalnem sistemu kibernetske varnosti); druge države to urejajo drugače.",
    "ue.meta.7": "UL EU L, 2024/2690",
    "ue.meta.8": "Direktiva (EU) 2022/2555",
    "ue.meta.9": "Rok za prenos je potekel 17. oktobra 2024",
    "ue.moduly.1": "približno {p0} min",
    "ue.moduly.10": "Deset področij iz člena 21(2), točke (a) do (j): od politike tveganj do večfaktorske avtentikacije. Kršitev je kazniva z globo po členu 34. Ocena na lestvici zrelosti.",
    "ue.moduly.11": "Uredba 2024/2690 — upravljanje in procesi",
    "ue.moduly.12": "Oddelki 1–5 in 7–8 priloge: politike, obvladovanje tveganj, obravnavanje incidentov, neprekinjeno poslovanje, dobavna veriga, ocenjevanje učinkovitosti, kibernetska higiena. Neposredno uporabljiva od 7. novembra 2024.",
    "ue.moduly.13": "Uredba 2024/2690 — tehnične zahteve",
    "ue.moduly.14": "Oddelki 6 in 9–13 priloge: pridobivanje in razvoj sistemov, kriptografija, varnost človeških virov, nadzor dostopa, upravljanje sredstev, fizična in okoljska varnost.",
    "ue.moduly.2": "približno {p0} h {p1} min",
    "ue.moduly.3": "približno {p0} h",
    "ue.moduly.4": "manj kot minuta",
    "ue.moduly.5": "Hitra ocena tveganja",
    "ue.moduly.6": "Nadrejena vprašanja z vseh področij direktive. Vsako odloča o celotni skupini tem. Omogoča oceno obsega zaostankov brez prehoda celotnega vprašalnika.",
    "ue.moduly.7": "Obveznosti iz direktive",
    "ue.moduly.8": "Registracijski podatki, priglasitev incidentov v 24 in 72 urah, obveznosti upravljalnega organa, pripravljenost na nadzor. Preverljivo iz dokumentov, brez tehnične analize.",
    "ue.moduly.9": "Ukrepi za obvladovanje tveganj — člen 21(2)",
    "ue.obowiazki.1": "Registracijski podatki za seznam subjektov",
    "ue.obowiazki.10": "Priglašanje pomembnih incidentov",
    "ue.obowiazki.11": "Subjekt pomembne incidente priglasi skupini CSIRT ali pristojnemu organu v treh korakih: zgodnje opozorilo, priglasitev, končno poročilo. Roki tečejo od seznanitve z incidentom.",
    "ue.obowiazki.12": "Ali je subjekt sposoben v 24 urah od seznanitve s pomembnim incidentom posredovati zgodnje opozorilo z navedbo, ali je incident domnevno povzročen z nezakonitimi dejanji in ali bi lahko imel čezmejni vpliv?",
    "ue.obowiazki.13": "24 ur od seznanitve",
    "ue.obowiazki.14": "Ali je subjekt sposoben v 72 urah posredovati priglasitev incidenta z začetno oceno resnosti in vpliva ter kazalniki ogroženosti?",
    "ue.obowiazki.15": "72 ur od seznanitve",
    "ue.obowiazki.16": "Ali subjekt najpozneje mesec dni po priglasitvi posreduje končno poročilo z opisom incidenta, vrsto grožnje, ukrepi za ublažitev in čezmejnim vplivom?",
    "ue.obowiazki.17": "mesec od priglasitve",
    "ue.obowiazki.18": "Ali subjekt prejemnike svojih storitev obvešča o pomembnih incidentih, ki bi lahko negativno vplivali na opravljanje teh storitev?",
    "ue.obowiazki.19": "Ali subjekt prejemnike storitev obvešča o pomembni kibernetski grožnji in o ukrepih, ki jih lahko prejemniki sprejmejo?",
    "ue.obowiazki.2": "Države članice vzpostavijo seznam bistvenih in pomembnih subjektov ter od subjektov zahtevajo predložitev registracijskih podatkov. Postopek, rok in portal določa nacionalno pravo.",
    "ue.obowiazki.20": "Če je subjekt ponudnik storitev zaupanja — ali pomembne incidente priglasi v 24 urah od seznanitve?",
    "ue.obowiazki.21": "zadeva ponudnike storitev zaupanja",
    "ue.obowiazki.22": "Upravljalni organ",
    "ue.obowiazki.23": "Upravljalni organ odobri ukrepe za obvladovanje tveganj, nadzoruje njihovo izvajanje in je lahko odgovoren. Člani organa se redno usposabljajo.",
    "ue.obowiazki.24": "Ali je upravljalni organ formalno odobril ukrepe za obvladovanje tveganj za kibernetsko varnost, sprejete za zagotovitev skladnosti s členom 21?",
    "ue.obowiazki.25": "Ali upravljalni organ dokumentirano nadzoruje izvajanje teh ukrepov — na primer z rednimi poročili in pregledi?",
    "ue.obowiazki.26": "Ali se člani upravljalnega organa redno usposabljajo, da lahko prepoznajo tveganja in ocenijo prakse obvladovanja tveganj, in ali je udeležba dokumentirana?",
    "ue.obowiazki.27": "Pripravljenost na nadzorne ukrepe",
    "ue.obowiazki.28": "Bistveni subjekt je podrejen predhodnemu in naknadnemu nadzoru, pomembni subjekt — izključno naknadnemu. Organ lahko zahteva informacije, dokazila o izvajanju politik in rezultate revizij.",
    "ue.obowiazki.29": "Ali je subjekt sposoben na zahtevo organa predložiti dokazila o izvajanju politik kibernetske varnosti, vključno z rezultati varnostnih revizij?",
    "ue.obowiazki.3": "Ali je subjekt določil, ali je bistveni ali pomembni subjekt, na podlagi sektorja iz Priloge I ali II in velikosti podjetja?",
    "ue.obowiazki.30": "Ali je subjekt sposoben na zahtevo organa dati na voljo podatke, dokumente in informacije, potrebne za opravljanje nadzornih nalog?",
    "ue.obowiazki.31": "Ali je bistveni subjekt pripravljen na varnostno revizijo, ki jo izvede organ ali neodvisni subjekt, na lastne stroške?",
    "ue.obowiazki.4": "Ali je subjekt pristojnemu organu predložil registracijske podatke: ime, naslov in kontaktne podatke, sektor in podsektor, seznam držav članic, v katerih opravlja storitve?",
    "ue.obowiazki.5": "Kontaktni podatki obsegajo elektronske naslove, obsege naslovov IP in telefonske številke. Nacionalni rok in portal za registracijo določa pravo države članice.",
    "ue.obowiazki.6": "Ali obstaja postopek posodabljanja registracijskih podatkov brez nepotrebnega odlašanja po njihovi spremembi?",
    "ue.obowiazki.7": "Direktiva zahteva posodobitev brez nepotrebnega odlašanja; konkreten rok — na primer 14 dni na Poljskem — izhaja iz nacionalnega prava.",
    "ue.obowiazki.8": "Če je subjekt ponudnik DNS, register vrhnje domene, ponudnik oblaka, podatkovnega centra, CDN, upravljanih storitev, spletna tržnica, iskalnik ali družbeno omrežje — ali je predložil dodatne podatke iz člena 27, vključno z naslovom glavnega sedeža v Uniji?",
    "ue.obowiazki.9": "zadeva subjekte iz člena 26(1)",
    "ue.role.1": "Pristojni organ države članice",
    "ue.role.10": "Storitve podatkovnega centra: kolokacija, gostovanje infrastrukture in povezane storitve.",
    "ue.role.11": "Podatkovni centri",
    "ue.role.12": "Bistveni subjekt nad pragom srednjega podjetja (člen 3(1), točka (a)), pomembni pri srednji velikosti (člen 3(2)). Pod srednjo velikostjo — zunaj področja uporabe, razen če država članica subjekt določi na podlagi člena 2(2), točke (b) do (e). Zajet v Uredbo 2024/2690.",
    "ue.role.13": "Ponudnik stičišča omrežij",
    "ue.role.14": "Infrastruktura, ki omogoča izmenjavo prometa med neodvisnimi omrežji.",
    "ue.role.15": "Stičišča omrežij",
    "ue.role.16": "Klasifikacija po velikosti (člen 3(1), točka (a), in (2)). Uredba 2024/2690 stičišč omrežij ne zajema — člen 1 uredbe vsebuje zaprt seznam naslovnikov.",
    "ue.role.17": "Ponudnik storitev DNS",
    "ue.role.18": "Storitve razreševanja domenskih imen, razen upravljavcev korenskih imenskih strežnikov.",
    "ue.role.19": "Sistem domenskih imen",
    "ue.role.2": "pristojni organ",
    "ue.role.20": "Bistveni subjekt ne glede na velikost (člen 3(1), točka (b)). Zajet v Uredbo 2024/2690.",
    "ue.role.21": "Register vrhnjih domenskih imen",
    "ue.role.22": "Vodenje registra vrhnje domene.",
    "ue.role.23": "Bistveni subjekt ne glede na velikost (člen 3(1), točka (b)). Dodatno obveznosti glede registracijskih podatkov iz člena 28. Zajet v Uredbo 2024/2690.",
    "ue.role.24": "Ponudnik storitev računalništva v oblaku",
    "ue.role.25": "Storitve računalništva v oblaku: infrastruktura, platforma, programska oprema kot storitev.",
    "ue.role.26": "Storitve računalništva v oblaku",
    "ue.role.27": "Klasifikacija po velikosti (člen 3(1), točka (a), in (2)). Zajet v Uredbo 2024/2690.",
    "ue.role.28": "Ponudnik omrežja za dostavo vsebin",
    "ue.role.29": "Omrežje porazdeljenih strežnikov, ki dostavljajo vsebine in storitve končnim uporabnikom.",
    "ue.role.3": "določen z nacionalnim pravom; do uvedbe nacionalnega modula orodje ne navaja konkretne institucije",
    "ue.role.30": "Omrežja za dostavo vsebin",
    "ue.role.31": "Ponudnik storitev zaupanja",
    "ue.role.32": "Storitve zaupanja v smislu Uredbe (EU) št. 910/2014: podpisi, žigi, časovni žigi, potrdila.",
    "ue.role.33": "Storitve zaupanja",
    "ue.role.34": "Zajet v direktivo ne glede na velikost (člen 2(2), točka (a)(ii)). Kvalificirani ponudnik je bistveni subjekt ne glede na velikost (člen 3(1), točka (b)); nekvalificirani je bistven nad pragom srednjega podjetja, sicer pomemben. Zajet v Uredbo 2024/2690.",
    "ue.role.35": "Ponudnik upravljanih storitev",
    "ue.role.36": "Upravljanje infrastrukture IKT stranke: namestitev, vzdrževanje, podpora, administracija sistemov.",
    "ue.role.37": "Upravljanje storitev IKT (B2B)",
    "ue.role.38": "Upravljane storitve",
    "ue.role.39": "Ponudnik upravljanih varnostnih storitev",
    "ue.role.4": "Ponudnik javnih elektronskih komunikacijskih omrežij ali javno dostopnih elektronskih komunikacijskih storitev",
    "ue.role.40": "Upravljane storitve na področju kibernetske varnosti: spremljanje, odzivanje na incidente, preizkusi, svetovanje.",
    "ue.role.41": "Upravljane varnostne storitve",
    "ue.role.42": "Direktiva klasificira po velikosti (člen 3(1), točka (a), in (2)). Države članice lahko prag zaostrijo — Poljska MSSP šteje za bistveni subjekt že od malega podjetja; ta modul uporablja izključno pravilo direktive. Zajet v Uredbo 2024/2690.",
    "ue.role.5": "Zagotavljanje javnih elektronskih komunikacijskih omrežij ali opravljanje javno dostopnih elektronskih komunikacijskih storitev, vključno z dostopom do interneta.",
    "ue.role.6": "Digitalna infrastruktura",
    "ue.role.7": "Elektronske komunikacije",
    "ue.role.8": "Zajet v direktivo ne glede na velikost (člen 2(2), točka (a)(i)). Srednje ali večje podjetje je bistveni subjekt (člen 3(1), točka (c)), mikro in malo — pomembni (člen 3(2)). Nacionalni zakon o elektronskih komunikacijah lahko nalaga dodatne obveznosti — ta modul jih ne vsebuje.",
    "ue.role.9": "Ponudnik storitev podatkovnega centra",
    "ue.role.podstawaArt3b": "člen 3(1), točka (b), Direktive (EU) 2022/2555",
    "ue.zaslepki.1": "Direktiva (EU) 2022/2555 Evropskega parlamenta in Sveta (NIS 2)",
    "ue.zaslepki.10": "Ali se del subjektov vpiše po uradni dolžnosti, odloča nacionalno pravo.",
    "ue.zaslepki.11": "Ugotovite, ali ste zajeti v direktivo",
    "ue.zaslepki.12": "Sektor iz Priloge I ali II in velikost podjetja. Ta del opravi profil subjekta v tem orodju.",
    "ue.zaslepki.13": "Ugotovite pristojni organ v svoji državi",
    "ue.zaslepki.14": "Vsaka država določi pristojni organ (člen 8(1)). Posodobljen seznam vodita ENISA in Komisija.",
    "ue.zaslepki.15": "Predložite registracijske podatke",
    "ue.zaslepki.16": "Ime, naslov in kontaktni podatki, sektor in podsektor, države opravljanja storitev (člen 3(4)). Postopek po nacionalnem pravu.",
    "ue.zaslepki.17": "Podatke posodabljajte brez nepotrebnega odlašanja",
    "ue.zaslepki.18": "Vsaka sprememba registracijskih podatkov zahteva posodobitev (člen 3(5)).",
    "ue.zaslepki.19": "naslov in aktualni kontaktni podatki: elektronski naslovi, obsegi naslovov IP, telefonske številke",
    "ue.zaslepki.2": "UL EU L 333, 27.12.2022, str. 80",
    "ue.zaslepki.20": "sektor in podsektor iz Priloge I ali II",
    "ue.zaslepki.21": "seznam držav članic, v katerih subjekt opravlja storitve",
    "ue.zaslepki.22": "Določa nacionalno pravo.",
    "ue.zaslepki.23": "Direktiva (EU) 2022/2555 — člen 3",
    "ue.zaslepki.24": "ENISA — pristojni organi držav članic",
    "ue.zaslepki.25": "Direktiva (EU) 2022/2555",
    "ue.zaslepki.26": "Modul EU ne vsebuje smernic nacionalnega organa — te bodo prišle z modulom nacionalnega prava.",
    "ue.zaslepki.27": "Samodejno pridobivanje podatkov iz registra deluje le za države z modulom nacionalnega prava. Profil izpolnite ročno.",
    "ue.zaslepki.28": "Branje računovodskega poročila deluje le za države z modulom nacionalnega prava. Prihodke in število zaposlenih vnesite ročno.",
    "ue.zaslepki.3": "Izvedbena uredba Komisije (EU) 2024/2690",
    "ue.zaslepki.4": "UL EU L, 2024/2690, 18.11.2024",
    "ue.zaslepki.5": "Direktiva NIS 2 ne vsebuje ločene plasti elektronskih komunikacij. Nacionalno pravo elektronskih komunikacij lahko nalaga dodatne obveznosti — ta modul jih ne pozna.",
    "ue.zaslepki.6": "Seznam bistvenih in pomembnih subjektov",
    "ue.zaslepki.7": "Pristojni organ države članice.",
    "ue.zaslepki.8": "Direktiva državam članicam nalaga vodenje seznama bistvenih in pomembnih subjektov ter zahtevanje predložitve registracijskih podatkov od subjektov. Portal, postopek in rok določa nacionalno pravo — ta modul jih ne pozna, ker modul nacionalnega prava za izbrano državo še ni pripravljen.",
    "ue.zaslepki.9": "Vsi bistveni in pomembni subjekti. Rok določa nacionalno pravo.",
    "ue.zaslepki.skrotDyrektywy": "Direktiva NIS 2",
    "ue.zaslepki.skrotReg2690": "Uredba 2024/2690",
    "xlsx.1": "{p0} – {p1} EUR",
    "xlsx.25": "Menjalni tečaj",
    "xlsx.4": "POROČILO O SKLADNOSTI Z DIREKTIVO NIS 2 (EU) 2022/2555",
    "xlsx.58": "Dejavnost elektronskih komunikacij: Uredba (EU) 2024/2690 se ne uporablja. Pragove določa nacionalno pravo (člen 23(11) direktive) — skupni modul jih ne pozna.",
    "xlsx.68": "Orodje služi samooceni. Ni revizija niti pravno mnenje.",
    "xlsx.69": "Za subjekte, ki niso zajeti v Uredbo (EU) 2024/2690, pragove pomembnega incidenta določa nacionalno pravo (člen 23(11) direktive).",
    "xlsx.70": "Vloge, navedene v profilu, so izjava. O statusu odloča dejansko opravljana dejavnost (člen 3 Direktive (EU) 2022/2555).",
    "xlsx.etykietaKrs": "Registrska številka",
    "xlsx.etykietaNip": "Identifikacijska številka",
    "xlsx.etykietaRegon": "Statistična številka"
});
