/* Teksty modułu ue — język: sv.
   Te same klucze co w napisy/pl.js (wersja źródłowa); wstawki {p0}, {p1}…
   pozostają bez zmian. Klucze ue.cyt.* to wzorce składania odesłań
   do przepisów w tym języku — patrz kraje/ue/cytaty.js. */
KRAJE.napisy('ue', 'sv', {
    "app.10": "Kontrollera listan över roller nedan — statusen avgörs av den verksamhet som faktiskt bedrivs (artikel 3 i direktiv (EU) 2022/2555), inte av en registerpost.",
    "app.14": "Föregående år: {p0} euro",
    "app.15": "Intäkter för rapportperioden: {p0} euro",
    "app.19": "Frågar register efter nummer {p0}…",
    "app.34": " miljarder euro",
    "app.35": " miljoner euro",
    "app.36": " tusen euro",
    "app.37": "",
    "app.4": "Automatisk hämtning av registeruppgifter är inte tillgänglig för detta land — fyll i profilen manuellt.",
    "app.59": "Bedömning av efterlevnad av NIS 2-direktivet (JSON)",
    "app.68": "För detta land finns inget register som verktyget kan hämta uppgifter från — profilen fylls i manuellt.",
    "app.69": "För detta land finns inget register som verktyget kan hämta uppgifter från. Klicka för att slå på offlineläget.",
    "app.73": " · resultaträkning enligt uppställningsform ",
    "app.74": "<div class=\"mt-2 tekst-uwaga\">Registeruppgifterna visar ingen roll inom sektorn digital infrastruktur. Välj rollerna manuellt nedan.</div>",
    "app.8": "Post i registret över leverantörer av elektronisk kommunikation bekräftad",
    "app.progDostawcy": "",
    "app.przyklad.adres": "Exempelgatan 1, 100 00 Stad",
    "app.przyklad.forma": "Aktiebolag",
    "app.przyklad.nazwa": "Exempeloperatör AB",
    "app.statusVat": " · momsstatus: ",
    "dashboard.1": "Utifrån de deklarerade rollerna och storleken är entiteten varken en väsentlig eller en viktig entitet i den mening som avses i artikel 3 i direktiv (EU) 2022/2555. Kontrollera profilen om resultatet avviker från vad du förväntade dig.",
    "dashboard.113": "Vanliga frågor",
    "dashboard.12": "— {p0}; tidsfristen för införlivande i nationell rätt löpte ut {p2}",
    "dashboard.123": "NIS 2-direktivet",
    "dashboard.30": "Förteckning över väsentliga och viktiga entiteter",
    "dashboard.4": "— direkt tillämplig från {p0} i alla medlemsstater, utan införlivande",
    "dashboard.42": "Variant med fast belopp: {p0}",
    "dashboard.45": "Kriterier enligt artikel 32.7 i direktivet:",
    "dashboard.46": "Totalt",
    "dashboard.49": "Entiteten bedriver elektronisk kommunikationsverksamhet — den ledande personens ansvar bestäms av nationell rätt",
    "dashboard.50": "",
    "dashboard.51": "",
    "dashboard.53": "Löpande vite för dröjsmål med att följa ett beslut: från {p0} euro till {p1} euro per dag ({p2})",
    "dashboard.54": "Kvalificerat fall: upp till {p0} euro ({p1})",
    "dashboard.57": "({p0}). Från när den nationella myndigheten får påföra sanktionsavgifter bestäms av lagen som införlivar direktivet — denna modul känner inte till den. Genomförandeskyldigheterna följer av nationell rätt från dagen den träder i kraft.",
    "dashboard.65": "({p0}). Från när den nationella myndigheten får påföra sanktionsavgifter bestäms av lagen som införlivar direktivet — denna modul känner inte till den. Den ekonomiska risken dateras därför inte här, medan genomförandeskyldigheterna följer av nationell rätt från dagen den träder i kraft.",
    "dashboard.83": "Elektronisk kommunikationsverksamhet — tröskelvärdena bestäms av nationell rätt.",
    "dashboard.84": "Förordning (EU) 2024/2690 gäller inte för tillhandahållare av allmänna elektroniska kommunikationsnät och -tjänster. För dem bestäms tröskelvärdena för en betydande incident av nationell rätt (artikel 23.11 i direktivet) — denna modul känner inte till dem och anger därför inga siffror.",
    "dashboard.terminRejestracji": "Tidsfristen för att lämna registreringsuppgifter bestäms av nationell rätt (artikel 3.4 i direktivet). Leverantörer enligt artikel 27.1 — leverantörer av DNS-tjänster, registreringsenheter för toppdomäner, leverantörer av molntjänster, datacentraltjänster, nätverk för innehållsleverans, hanterade tjänster och hanterade säkerhetstjänster — lämnar sina uppgifter till Enisas register: ursprungligen senast den 17 januari 2025, och varje ändring utan onödigt dröjsmål.",
    "html.1": "ITORO — Bedömning av efterlevnad av NIS 2-direktivet (EU) 2022/2555",
    "html.10": "Bedömning av efterlevnad av NIS 2-direktivet — gemensam modul",
    "html.100": "Inläsning av årsredovisning fungerar endast för länder med modul för nationell rätt. För detta land anger du <strong>intäkterna</strong> för räkenskapsåret manuellt — sanktionsavgiftens nivå beror på dem.",
    "html.102": "Automatisk hämtning av registeruppgifter fungerar endast för länder med modul för nationell rätt. Roller och företagets storlek anger du manuellt.",
    "html.11": "Direktiv (EU) 2022/2555 (NIS 2) kräver införlivande i nationell rätt. Bedömningen omfattar de skyldigheter som följer direkt av direktivet och kommissionens genomförandeförordning (EU) 2024/2690, som gäller direkt — i den mån de berör entiteten.",
    "html.23": "intäkter och storlek anger du manuellt — den gemensamma modulen frågar inte nationella register",
    "html.33": "Europaparlamentets och rådets direktiv (EU) 2022/2555 av den 14 december 2022 (NIS 2)",
    "html.33a": "{p0} — den nationella genomförandeakten; dess krav bedöms ännu inte i denna modul",
    "html.33b": "landet har ännu inte antagit någon genomförandeakt — bedömningen följer unionsrätten",
    "html.35": "ledningsorganets skyldigheter — artikel 20 i direktivet",
    "html.36": "Verktyget är avsett för självbedömning. Det är varken en revision eller juridisk rådgivning.",
    "html.40": "den gemensamma modulen upprättar inga utgående anslutningar alls — den frågar inte register",
    "html.59": "Årsredovisningar",
    "html.60": "Inläsning av årsredovisning är endast tillgänglig för länder med modul för nationell rätt. För detta land anger du intäkter och personalstyrka manuellt.",
    "html.62": "Sökning i register",
    "html.63": "företagsregister är nationella — den gemensamma modulen känner inte till dem",
    "html.64": "roller och företagets storlek anger du manuellt",
    "html.66": "Entitetens identifieringsnummer",
    "html.68": "Automatisk hämtning av registeruppgifter fungerar endast för länder med modul för nationell rätt.",
    "html.76": "Årsintäkter (euro)",
    "html.78": "Intäkter från elektronisk kommunikationsverksamhet (euro)",
    "html.79": "Fältet gäller tillhandahållare av allmänna elektroniska kommunikationsnät eller -tjänster. Nationella tröskelvärden bestäms av medlemsstatens rätt.",
    "html.80": "Chefens månadsersättning (euro)",
    "html.82": "Växelkurs",
    "html.83": "Taken för sanktionsavgifter i direktivet är uttryckta i euro. Omräkning till nationell valuta och kursen bestäms av nationell rätt — här anges beloppen i euro utan omräkning.",
    "html.84": "Statusen följer enbart av sammanläggningen av anknutna företags uppgifter, och entitetens informationssystem är oberoende (skäl 16 i direktivet — nationell rätt avgör tillämpningen)",
    "html.85": "Entiteten är verksam inom nationell säkerhet, allmän säkerhet, försvar eller brottsbekämpning (artikel 2.7 i direktivet)",
    "html.91": "Bedömning av efterlevnad av Europaparlamentets och rådets direktiv (EU) 2022/2555 (NIS 2) och kommissionens genomförandeförordning (EU) 2024/2690 — gemensam modul för länder vars modul för nationell rätt ännu inte är klar.",
    "html.94": "om entiteten är <strong>väsentlig</strong>, <strong>viktig</strong> eller utanför direktivets tillämpningsområde",
    "html.daneZeSprawozdania": "namn, identifieringsnummer, adress för säte",
    "html.rejestrMozliwy": "Registret {p0} är offentligt och avgiftsfritt — inläsning kan läggas till; vi tar gärna emot pull requests (se README).",
    "html.tytulNaglowka": "Bedömning av efterlevnad av NIS 2-direktivet",
    "html.zrodlaRecznie": "Denna modul känner inte till ert lands register — fyll i profilen för hand. Den årliga omsättningen avgör sanktionstaket, så ange den noggrant.",
    "klasyfikacja.10": "artikel 3.1 c i direktiv (EU) 2022/2555 (tillhandahållare av allmänna elektroniska kommunikationsnät eller allmänt tillgängliga elektroniska kommunikationstjänster som är minst ett medelstort företag)",
    "klasyfikacja.11": "artikel 3.2 jämförd med artikel 2.2 a i i direktiv (EU) 2022/2555 (tillhandahållare av allmänna elektroniska kommunikationsnät eller -tjänster som är ett mikroföretag eller litet företag)",
    "klasyfikacja.12": "artikel 3.1 a i direktiv (EU) 2022/2555 (leverantör av hanterade säkerhetstjänster som överskrider taken för ett medelstort företag)",
    "klasyfikacja.13": "Mikroföretag och små företag omfattas inte av direktivet på grund av denna roll (artikel 2.1 a contrario).",
    "klasyfikacja.15": "artikel 3.1 b i direktiv (EU) 2022/2555 (kvalificerad tillhandahållare av betrodda tjänster) — oavsett företagets storlek",
    "klasyfikacja.16": "artikel 3.2 jämförd med artikel 2.2 a ii i direktiv (EU) 2022/2555 (icke-kvalificerad tillhandahållare av betrodda tjänster som är ett mikroföretag, litet eller medelstort företag)",
    "klasyfikacja.18": "artikel 3.2 i direktiv (EU) 2022/2555 (offentlig förvaltningsentitet på regional nivå, om medlemsstaten så föreskriver — artikel 2.2 f ii)",
    "klasyfikacja.19": "artikel 3.1 f i direktiv (EU) 2022/2555 (offentlig förvaltningsentitet på central nivå — artikel 2.2 f i)",
    "klasyfikacja.2": "Förhands- och efterhandstillsyn (artikel 32 i direktiv (EU) 2022/2555).",
    "klasyfikacja.20": "artikel 3.2 i direktiv (EU) 2022/2555 (offentlig förvaltningsentitet på regional nivå — artikel 2.2 f ii)",
    "klasyfikacja.21": "Omfattningen av skyldigheterna för offentliga förvaltningsentiteter på lokal nivå bestäms av nationell rätt (artikel 2.5 a i direktivet).",
    "klasyfikacja.22": "En medlemsstat får undanta entiteter som bedriver verksamhet inom nationell säkerhet, allmän säkerhet, försvar eller brottsbekämpning (artikel 2.7 i direktivet). Undantaget verkar inte av sig självt — kontrollera bedömningens resultat mot nationell rätt.",
    "klasyfikacja.23": "Entiteten uppfyller kriterierna för både en väsentlig och en viktig entitet. Den är en väsentlig entitet (artikel 3.1 i direktivet), och de strängare kraven gäller för all verksamhet som omfattas av direktivet.",
    "klasyfikacja.25": "Entiteten är väsentlig, så hela katalogen av åtgärder enligt artikel 21.2 i direktivet samt förhands- och efterhandstillsyn gäller — bedömningen omfattar hela frågeuppsättningen.",
    "klasyfikacja.26": "Som viktig entitet omfattas ni av samma katalog av åtgärder enligt artikel 21.2, men endast av efterhandstillsyn (artikel 33). Taket för sanktionsavgiften är lägre: 7 miljoner euro eller 1,4 % av omsättningen (artikel 34.5). Lättnader för offentliga entiteter kan införas genom nationell rätt — denna modul känner inte till dem.",
    "klasyfikacja.28": "Skyldigheterna för offentliga förvaltningsentiteter följer av artikel 2.2 f i direktivet; deras exakta omfattning, även för lokal nivå och utbildningsinstitutioner, bestäms av nationell rätt (artikel 2.5).",
    "klasyfikacja.29": "Det har deklarerats att entitetens status enbart följer av sammanläggningen av anknutna företags eller partnerföretags uppgifter och att entitetens informationssystem är oberoende. Direktivet tillåter ett sådant undantag (skäl 16), men nationell rätt avgör — modulen godtar undantaget, som måste kontrolleras mot medlemsstatens rätt och dokumenteras.",
    "klasyfikacja.4": "Endast efterhandstillsyn — vid bevis, indikationer eller information om en överträdelse (artikel 33 i direktiv (EU) 2022/2555).",
    "klasyfikacja.5": "Utanför direktivets tillämpningsområde",
    "klasyfikacja.6": "För den angivna rollen följer inga skyldigheter av direktiv (EU) 2022/2555.",
    "klasyfikacja.7": "artikel 3.1 a i direktiv (EU) 2022/2555 (entitet av en typ som avses i bilaga I som överskrider taken för ett medelstort företag)",
    "klasyfikacja.8": "artikel 3.2 i direktiv (EU) 2022/2555 (entitet av en typ som avses i bilaga I som uppfyller kriterierna för ett medelstort företag)",
    "klasyfikacja.9": "Mikroföretag och små företag omfattas inte av direktivet på grund av denna roll (artikel 2.1 a contrario).",
    "kreator.10": "Ange föregående års intäkter manuellt.",
    "kreator.35": "<span class=\"text-secondary\">Inläsning av årsredovisningar är inte tillgänglig för detta land.</span>",
    "kreator.37": "Inläsning av årsredovisningar är inte tillgänglig för detta land — ange intäkterna manuellt.",
    "kreator.56": "Ja — EU-förordningen gäller direkt från den 7 november 2024 i alla medlemsstater och har ingen övergångsperiod. Dess grund är",
    "kreator.57": ", som gav kommissionen befogenhet att fastställa de tekniska och metodologiska kraven för de leverantörer som avses i artikel 3.1 i förordningen. Tidsfristen för införlivande av direktivet löpte ut",
    "kreator.58": ", och från när den nationella myndigheten får påföra sanktionsavgifter bestäms av nationell rätt. De tekniska kraven i bilagan (avsnitten 6 och 9–13) är bindande i sin nuvarande lydelse — de väntar inte på förtydligande. Avsteg kan endast göras från krav med förbehållet ”när så är lämpligt”, och endast med en dokumenterad motivering.",
    "kreator.9": "Årsredovisningar →",
    "kreator.przepisReg2690": "artikel 21.5 i direktiv (EU) 2022/2555",
    "kreator.terminReg2690": "den 17 oktober 2024",
    "punktacja.10": "Offentliga entiteter",
    "punktacja.4": "NIS 2-direktivet — artikel 21",
    "punktacja.5": "NIS 2-direktivet — formella skyldigheter",
    "punktacja.8": "Elektronisk kommunikation",
    "punktacja.9": "NIS 2-direktivet — offentliga entiteter",
    "punktacja.skrotKsc": "NIS 2",
    "punktacja.skrotPke": "telekom",
    "ue.cyt.akapit": " {p0} stycket",
    "ue.cyt.art": "artikel {p0}",
    "ue.cyt.drugi": "andra",
    "ue.cyt.dyr": "{p0} i direktiv (EU) 2022/2555",
    "ue.cyt.i": "och",
    "ue.cyt.laczenie": "",
    "ue.cyt.lit": " {p0}",
    "ue.cyt.litery": "",
    "ue.cyt.pkt": ".{p0}",
    "ue.cyt.rozdzielacz": "; ",
    "ue.cyt.rozp": "{p0} i förordning (EU) 2024/2690",
    "ue.cyt.ust": ".{p0}",
    "ue.katalog.1": "Strategier för riskanalys och informationssystemens säkerhet",
    "ue.katalog.10": "Incidenthantering",
    "ue.katalog.11": "Incidenthantering omfattar åtgärder och förfaranden som syftar till att förebygga, upptäcka, analysera och begränsa en incident eller att reagera på och återhämta sig från den (artikel 6.8).",
    "ue.katalog.12": "Finns det ett dokumenterat förfarande för incidenthantering som omfattar upptäckt, analys, begränsning, reaktion och återhämtning?",
    "ue.katalog.13": "ISO/IEC 27001 A.5.24–A.5.26",
    "ue.katalog.14": "Gör förfarandet det möjligt att hålla tidsfristerna för rapportering av en betydande incident: tidig varning inom 24 timmar, incidentanmälan inom 72 timmar, slutrapport inom en månad?",
    "ue.katalog.15": "ISO/IEC 27001 A.5.24",
    "ue.katalog.16": "Har entiteten kriterier för att bedöma en incident som betydande i enlighet med artikel 23.3: allvarliga driftstörningar eller ekonomisk förlust, eller betydande skada för andra personer?",
    "ue.katalog.17": "ISO/IEC 27001 A.5.25",
    "ue.katalog.18": "Registreras incidenter och används lärdomarna från hanteringen av dem för att förbättra åtgärderna?",
    "ue.katalog.19": "ISO/IEC 27001 A.5.27",
    "ue.katalog.2": "Åtgärderna bygger på en allriskansats (artikel 21.2). Deras proportionalitet bedöms med beaktande av graden av riskexponering, entitetens storlek, incidenters sannolikhet och deras allvarlighetsgrad (artikel 21.1 andra stycket).",
    "ue.katalog.20": "Driftskontinuitet och krishantering",
    "ue.katalog.21": "Driftskontinuitet, såsom hantering av säkerhetskopior och katastrofåterställning, samt krishantering.",
    "ue.katalog.22": "Finns det en kontinuitetsplan som omfattar återställning efter en katastrof?",
    "ue.katalog.23": "ISO/IEC 27001 A.5.29–A.5.30",
    "ue.katalog.24": "Görs säkerhetskopior, skyddas de och testas de med avseende på återställbarhet?",
    "ue.katalog.25": "ISO/IEC 27001 A.8.13",
    "ue.katalog.26": "Har entiteten krishanteringsförfaranden med fastställda roller och kommunikationskanaler?",
    "ue.katalog.27": "ISO/IEC 27001 A.5.29",
    "ue.katalog.28": "Testas kontinuitets- och återställningsplanerna regelbundet och dokumenteras resultaten?",
    "ue.katalog.29": "ISO/IEC 27001 A.5.30",
    "ue.katalog.3": "Har entiteten en dokumenterad strategi för riskanalys och informationssystemens säkerhet som godkänts av ledningsorganet?",
    "ue.katalog.30": "Säkerhet i leveranskedjan",
    "ue.katalog.31": "Säkerhet i leveranskedjan, inbegripet säkerhetsaspekter som rör förhållandet mellan entiteten och dess direkta leverantörer eller tjänsteleverantörer. Entiteten beaktar de sårbarheter som är specifika för varje leverantör och den övergripande kvaliteten på dess produkter och cybersäkerhetspraxis (artikel 21.3).",
    "ue.katalog.32": "För entiteten en förteckning över direkta leverantörer och tjänsteleverantörer med en bedömning av deras betydelse för nätverkens och systemens säkerhet?",
    "ue.katalog.33": "ISO/IEC 27001 A.5.19",
    "ue.katalog.34": "Beaktas vid valet av åtgärder gentemot leverantörer de sårbarheter som är specifika för var och en av dem samt kvaliteten på deras cybersäkerhetspraxis och praxis för säker utveckling?",
    "ue.katalog.35": "ISO/IEC 27001 A.5.19, A.5.21",
    "ue.katalog.36": "Innehåller avtalen med leverantörer säkerhetskrav och en skyldighet att rapportera incidenter och sårbarheter?",
    "ue.katalog.37": "ISO/IEC 27001 A.5.20",
    "ue.katalog.38": "Beaktar entiteten resultaten av de samordnade säkerhetsriskbedömningarna av kritiska leveranskedjor enligt artikel 22?",
    "ue.katalog.39": "ISO/IEC 27001 A.5.21",
    "ue.katalog.4": "ISO/IEC 27001 punkterna 5.2, 6.1.2",
    "ue.katalog.40": "Säkerhet vid förvärv, utveckling och underhåll av system",
    "ue.katalog.41": "Säkerhet vid förvärv, utveckling och underhåll av nätverks- och informationssystem, inbegripet hantering och offentliggörande av sårbarheter.",
    "ue.katalog.42": "Fastställs säkerhetskraven innan ett system förvärvas eller dess utveckling påbörjas, och verifieras de före driftsättning?",
    "ue.katalog.43": "ISO/IEC 27001 A.8.25–A.8.29",
    "ue.katalog.44": "Finns det en process för hantering av sårbarheter: identifiering, bedömning, åtgärdande inom fastställd tid?",
    "ue.katalog.45": "ISO/IEC 27001 A.8.8",
    "ue.katalog.46": "Har entiteten ett förfarande för offentliggörande av sårbarheter, inbegripet en kanal för att ta emot rapporter från tredje part?",
    "ue.katalog.47": "Går ändringar i systemen genom en kontrollerad ändringshanteringsprocess med bedömning av säkerhetspåverkan?",
    "ue.katalog.48": "ISO/IEC 27001 A.8.32",
    "ue.katalog.49": "Bedömning av åtgärdernas effektivitet",
    "ue.katalog.5": "Omfattar riskanalysen alla risker för nätverks- och informationssystemen och deras fysiska miljö, inte bara cyberhot?",
    "ue.katalog.50": "Strategier och förfaranden för att bedöma effektiviteten hos riskhanteringsåtgärderna för cybersäkerhet.",
    "ue.katalog.51": "Finns det en dokumenterad strategi för bedömning av åtgärdernas effektivitet som fastställer omfattning, frekvens och metoder?",
    "ue.katalog.52": "ISO/IEC 27001 punkt 9.1",
    "ue.katalog.53": "Genomförs effektivitetsbedömningar regelbundet och rapporteras resultaten till ledningsorganet?",
    "ue.katalog.54": "ISO/IEC 27001 punkterna 9.2–9.3",
    "ue.katalog.55": "Leder identifierade brister till dokumenterade korrigerande åtgärder med ansvarig och tidsfrist?",
    "ue.katalog.56": "ISO/IEC 27001 punkt 10.1",
    "ue.katalog.57": "Cyberhygien och utbildning",
    "ue.katalog.58": "Grundläggande praxis för cyberhygien och utbildning i cybersäkerhet. Ledningsorganets ledamöter genomgår regelbundet utbildning (artikel 20.2).",
    "ue.katalog.59": "Tillämpar entiteten grundläggande praxis för cyberhygien: uppdateringar, lösenordshantering, begränsning av behörigheter, skydd mot skadlig programvara?",
    "ue.katalog.6": "ISO/IEC 27001 punkt 6.1.2",
    "ue.katalog.60": "ISO/IEC 27001 A.8.7, A.8.8",
    "ue.katalog.61": "Får de anställda utbildning i cybersäkerhet anpassad till sin roll, och dokumenteras deltagandet?",
    "ue.katalog.62": "ISO/IEC 27001 A.6.3",
    "ue.katalog.63": "Genomgår ledningsorganets ledamöter regelbundet utbildning som gör det möjligt för dem att identifiera risker och bedöma riskhanteringspraxis?",
    "ue.katalog.64": "ISO/IEC 27001 punkt 7.2",
    "ue.katalog.65": "Kryptografi och kryptering",
    "ue.katalog.66": "Strategier och förfaranden för användning av kryptografi och, när så är lämpligt, kryptering.",
    "ue.katalog.67": "Finns det en strategi för kryptografi som fastställer vilka uppgifter och kanaler som krypteras och med vilka algoritmer?",
    "ue.katalog.68": "ISO/IEC 27001 A.8.24",
    "ue.katalog.69": "Hanteras kryptografiska nycklar under hela livscykeln: generering, distribution, lagring, rotation, avveckling?",
    "ue.katalog.7": "Beaktas den senaste utvecklingen, relevanta europeiska och internationella standarder samt genomförandekostnaden vid valet av åtgärder?",
    "ue.katalog.70": "Personalresurser, åtkomstkontroll och tillgångsförvaltning",
    "ue.katalog.71": "Personalsäkerhet, strategier för åtkomstkontroll och tillgångsförvaltning.",
    "ue.katalog.72": "För entiteten en aktuell tillgångsförteckning med tilldelade ägare och klassificering?",
    "ue.katalog.73": "ISO/IEC 27001 A.5.9, A.5.12",
    "ue.katalog.74": "Finns det en strategi för åtkomstkontroll som bygger på principen om minsta behörighet, med regelbunden översyn av behörigheter?",
    "ue.katalog.75": "ISO/IEC 27001 A.5.15, A.5.18",
    "ue.katalog.76": "Tillämpas säkerhetsförfaranden vid anställning, byte av befattning och när en anställd slutar, inbegripet återkallande av behörigheter och återlämnande av tillgångar?",
    "ue.katalog.77": "ISO/IEC 27001 A.6.1–A.6.5",
    "ue.katalog.78": "Är privilegierad åtkomst begränsad, loggad och granskad?",
    "ue.katalog.79": "ISO/IEC 27001 A.8.2",
    "ue.katalog.8": "ISO/IEC 27001 punkt 6.1.3",
    "ue.katalog.80": "Multifaktorautentisering och säkrad kommunikation",
    "ue.katalog.81": "När så är lämpligt — multifaktorautentisering eller kontinuerlig autentisering, säkrad röst-, video- och textkommunikation samt säkrade nödkommunikationssystem inom entiteten.",
    "ue.katalog.82": "Används multifaktorautentisering eller kontinuerlig autentisering där riskanalysen motiverar det, särskilt för fjärråtkomst och privilegierade konton?",
    "ue.katalog.83": "ISO/IEC 27001 A.8.5",
    "ue.katalog.84": "Är den röst-, video- och textkommunikation som används i verksamheten säkrad?",
    "ue.katalog.85": "ISO/IEC 27001 A.8.20",
    "ue.katalog.86": "Har entiteten ett säkrat internt nödkommunikationssystem som är oberoende av den primära infrastrukturen?",
    "ue.katalog.9": "Är säkerhetsnivån dokumenterad som lämplig i förhållande till risken, med en motivering som beaktar entitetens storlek och incidenters samhälleliga och ekonomiska konsekvenser?",
    "ue.kierownictwo.1": "Ledningsorganet för en väsentlig eller viktig entitet — i ett aktiebolag styrelsen. Direktivet definierar inte begreppet; dess omfattning i ett visst land följer av nationell rätt.",
    "ue.kierownictwo.10": "Fastställa entitetens status och se till att den registreras",
    "ue.kierownictwo.11": "Fastställande av om entiteten är väsentlig eller viktig och inlämning av registreringsuppgifter till den behöriga myndigheten. Förfarandet och tidsfristen bestäms av nationell rätt.",
    "ue.kierownictwo.12": "Införa riskanalys och en säkerhetsstrategi",
    "ue.kierownictwo.13": "Åtgärder som bygger på en allriskansats och står i proportion till exponeringen, entitetens storlek och incidenternas allvarlighetsgrad.",
    "ue.kierownictwo.14": "Inrätta incidenthantering och rapportering",
    "ue.kierownictwo.15": "Ett förfarande för incidenthantering och förmågan att hålla tidsfristerna på 24 timmar, 72 timmar och en månad.",
    "ue.kierownictwo.16": "24 h / 72 h / en månad från upptäckt",
    "ue.kierownictwo.17": "Säkerställa driftskontinuitet",
    "ue.kierownictwo.18": "Kontinuitetsplan, säkerhetskopior, katastrofåterställning, krishantering.",
    "ue.kierownictwo.19": "Ordna upp leveranskedjan",
    "ue.kierownictwo.2": "Ledningsorganets ansvar påverkar inte nationella regler om ansvar för offentliga institutioner och tjänstemän (artikel 20.1 andra stycket).",
    "ue.kierownictwo.20": "Förteckning över leverantörer, bedömning av deras sårbarheter och praxis, säkerhetskrav i avtal.",
    "ue.kierownictwo.21": "Införa åtkomstkontroll och tillgångsförvaltning",
    "ue.kierownictwo.22": "Tillgångsförteckning, principen om minsta behörighet, behörighetsöversyner, multifaktorautentisering där risken motiverar det.",
    "ue.kierownictwo.23": "Mäta åtgärdernas effektivitet",
    "ue.kierownictwo.24": "Strategi och förfaranden för effektivitetsbedömning, regelbundna översyner, korrigerande åtgärder.",
    "ue.kierownictwo.25": "Godkänna",
    "ue.kierownictwo.26": "riskhanteringsåtgärderna för cybersäkerhet (artikel 20.1)",
    "ue.kierownictwo.27": "strategin för riskanalys och systemsäkerhet",
    "ue.kierownictwo.28": "budget och roller i genomförandet",
    "ue.kierownictwo.29": "Övervaka",
    "ue.kierownictwo.3": "Om det befriar från ansvar att anförtro skyldigheterna åt en annan person avgörs av nationell rätt. I Polen gör det inte det (artikel 8c.3 i lagen om det nationella cybersäkerhetssystemet).",
    "ue.kierownictwo.30": "genomförandet av de godkända åtgärderna (artikel 20.1)",
    "ue.kierownictwo.31": "resultaten av effektivitetsbedömningen (artikel 21.2 f)",
    "ue.kierownictwo.32": "att tidsfristerna för incidentrapportering hålls (artikel 23)",
    "ue.kierownictwo.33": "Dokumentera",
    "ue.kierownictwo.34": "godkännandebeslut och översyner",
    "ue.kierownictwo.35": "deltagande i utbildning (artikel 20.2)",
    "ue.kierownictwo.36": "Ledamot av ledningsorganet",
    "ue.kierownictwo.37": "godkännande av åtgärder, tillsyn, beslut, budget",
    "ue.kierownictwo.38": "Projektledare",
    "ue.kierownictwo.39": "samordning av genomförandet, tidsplan, status och belägg",
    "ue.kierownictwo.4": "Godkänna riskhanteringsåtgärderna för cybersäkerhet",
    "ue.kierownictwo.40": "IT / cybersäkerhet",
    "ue.kierownictwo.41": "riskanalys, tekniska åtgärder, incidenthantering",
    "ue.kierownictwo.42": "Juridik / regelefterlevnad",
    "ue.kierownictwo.5": "Ledningsorganet godkänner de åtgärder som vidtas för att uppfylla artikel 21. Det är organets beslut, inte IT-avdelningens — utan det saknar åtgärderna mandat.",
    "ue.kierownictwo.6": "Övervaka genomförandet av åtgärderna",
    "ue.kierownictwo.7": "Tillsynen över genomförandet är en skyldighet för ledningsorganet. Utförandet kan delegeras, tillsynen kan det inte.",
    "ue.kierownictwo.8": "Genomgå regelbunden utbildning",
    "ue.kierownictwo.9": "Ledningsorganets ledamöter genomgår regelbundet utbildning för att få tillräckliga kunskaper för att identifiera risker och bedöma riskhanteringspraxis och dess inverkan på entitetens tjänster.",
    "ue.kierownictwo.daneRejestracyjne": "registreringsuppgifter och uppdatering av dem (artikel 3.4 och 3.5)",
    "ue.meta.1": "Procentvarianten gäller: {p0} % av omsättningen är mer än {p1} miljoner euro.",
    "ue.meta.10": "Direktivet ålägger inte företag skyldigheter direkt — det gör den nationella lagen, som medlemsstaten skulle ha antagit senast den 17 oktober 2024. Denna modul visar kraven i direktivets lydelse, eftersom modulen för nationell rätt för det valda landet ännu inte är klar eller landet inte har införlivat direktivet.",
    "ue.meta.11": "Skyldigheter enligt direktivet",
    "ue.meta.12": "Förteckning över entiteter — senast den 17 april 2025",
    "ue.meta.13": "Medlemsstaterna skulle senast den 17 april 2025 upprätta en förteckning över väsentliga och viktiga entiteter och kräva att entiteterna lämnar registreringsuppgifter.",
    "ue.meta.14": "Förordning (EU) 2024/2690",
    "ue.meta.15": "Direkt tillämplig från den 7 november 2024",
    "ue.meta.16": "Genomförandeförordningen gäller direkt i alla medlemsstater, oavsett läget för införlivandet av direktivet. Den berör de entiteter som anges i dess artikel 1: leverantörer av DNS-tjänster, toppdomäner, molntjänster, datacentraltjänster, nätverk för innehållsleverans, hanterade tjänster och betrodda tjänster.",
    "ue.meta.17": "artikel 16 i förordning (EU) 2024/2690",
    "ue.meta.18": "Minst 10 000 000 euro eller minst 2 % av företagets totala globala årsomsättning under föregående räkenskapsår — det högsta beloppet gäller. Detta är ett minimitak: nationell rätt får höja det.",
    "ue.meta.19": "Minst 7 000 000 euro eller 1,4 % av den totala globala årsomsättningen — det högsta beloppet gäller. Minimitak.",
    "ue.meta.2": "Det fasta beloppet gäller: {p0} miljoner euro är mer än {p1} % av omsättningen.",
    "ue.meta.20": "Direktivet föreskriver ingen separat sanktionsavgift för en kvalificerad överträdelse — det är en konstruktion i vissa medlemsstaters nationella rätt.",
    "ue.meta.21": "Medlemsstaterna får föreskriva löpande viten för att tvinga fram att en överträdelse upphör. Beloppet bestäms av nationell rätt.",
    "ue.meta.22": "Ledningsorganet godkänner riskhanteringsåtgärderna, övervakar deras genomförande och kan hållas ansvarigt för överträdelser av artikel 21. Reglerna för och omfattningen av detta ansvar bestäms av nationell rätt.",
    "ue.meta.23": "Ledningsorganet godkänner riskhanteringsåtgärderna för cybersäkerhet (artikel 20.1).",
    "ue.meta.24": "Ledningsorganet övervakar genomförandet av dessa åtgärder (artikel 20.1).",
    "ue.meta.25": "Ledningsorganets ledamöter genomgår regelbundet utbildning (artikel 20.2).",
    "ue.meta.26": "För en väsentlig entitet får myndigheten begära ett tillfälligt förbud mot att utöva ledningsfunktioner (artikel 32.5 b).",
    "ue.meta.27": "Minimitaket bestäms av direktivet",
    "ue.meta.28": "Två värden jämförs: ett fast belopp i euro och en procentandel av företagets totala globala årsomsättning under föregående räkenskapsår. Det högre av dem är den övre gräns som medlemsstaten minst måste föreskriva. Nationell rätt får höja den.",
    "ue.meta.29": "Beloppet inom taket bestäms av den nationella myndigheten",
    "ue.meta.3": "Taket enligt direktivet överstiger entitetens årsomsättning {p0} gånger. Artikel 34.1 kräver att sanktionsavgiften står i proportion till omständigheterna i det enskilda fallet — detta är en övre gräns, inte en förväntad avgift.",
    "ue.meta.30": "Sanktionsavgiften ska vara effektiv, proportionell och avskräckande utifrån omständigheterna i det enskilda fallet. Myndigheten beaktar minst kriterierna i artikel 32.7: överträdelsens allvar och varaktighet, tidigare överträdelser, orsakad skada, uppsåt, korrigerande åtgärder och samarbete.",
    "ue.meta.31": "Taket kan överstiga årsomsättningen flera gånger om — det är en övre gräns, inte ett förväntat belopp. Nationella miniminivåer, löpande viten och förfarandet för att bestämma sanktionsavgifter bestäms av medlemsstatens lag.",
    "ue.meta.32": "Vid beslut om huruvida en administrativ sanktionsavgift ska påföras och om dess storlek tas i varje enskilt fall vederbörlig hänsyn till minst de omständigheter som anges i artikel 32.7.",
    "ue.meta.33": "överträdelsens allvar och vikten av de bestämmelser som överträtts — som allvarliga anses under alla omständigheter: upprepade överträdelser, underlåtenhet att anmäla eller avhjälpa betydande incidenter, underlåtenhet att avhjälpa brister i strid med bindande instruktioner, hindrande av revisioner eller övervakning, lämnande av felaktig eller grovt oriktig information",
    "ue.meta.34": "relevanta tidigare överträdelser av entiteten",
    "ue.meta.35": "materiell eller immateriell skada som orsakats, inbegripet ekonomisk förlust, effekter på andra tjänster och antalet berörda användare",
    "ue.meta.36": "om överträdelsen skett med uppsåt eller av oaktsamhet",
    "ue.meta.37": "åtgärder som vidtagits för att förebygga eller begränsa skadan",
    "ue.meta.38": "efterlevnad av godkända uppförandekoder eller certifieringsmekanismer",
    "ue.meta.39": "graden av samarbete med de behöriga myndigheterna",
    "ue.meta.4": "Europaparlamentets och rådets direktiv (EU) 2022/2555 (NIS 2)",
    "ue.meta.40": "Direktivet föreskriver inte uttryckligen att en sanktionsavgift kan efterges — om och när detta är möjligt avgörs av nationell rätt.",
    "ue.meta.41": "Från detta datum ska medlemsstaterna tillämpa de nationella bestämmelser som införlivar direktivet. Det konkreta datum från vilket myndigheten får påföra en sanktionsavgift följer av nationell rätt.",
    "ue.meta.42": "NIS 2-direktivets ikraftträdande",
    "ue.meta.43": "Den tjugonde dagen efter offentliggörandet i Europeiska unionens officiella tidning.",
    "ue.meta.44": "Tidsfrist för införlivande av direktivet",
    "ue.meta.45": "Senast detta datum skulle medlemsstaterna anta och offentliggöra nationella bestämmelser.",
    "ue.meta.46": "Tillämpning av nationella bestämmelser och upphävande av NIS 1",
    "ue.meta.47": "Från detta datum tillämpar medlemsstaterna införlivandebestämmelserna; direktiv (EU) 2016/1148 upphävs.",
    "ue.meta.48": "Tillämpning av förordning (EU) 2024/2690",
    "ue.meta.49": "Genomförandeförordningen gäller direkt från den tjugonde dagen efter offentliggörandet.",
    "ue.meta.5": "EUT L 333, 27.12.2022",
    "ue.meta.50": "Förteckning över väsentliga och viktiga entiteter",
    "ue.meta.51": "Senast detta datum upprättar medlemsstaterna förteckningen; entiteterna lämnar registreringsuppgifter till myndigheterna.",
    "ue.meta.52": "Kommissionens första översyn av direktivet",
    "ue.meta.53": "Kommissionen ser över hur direktivet fungerar och lägger fram en rapport.",
    "ue.meta.54": "Tidig varning om en betydande incident",
    "ue.meta.55": "24 timmar efter kännedom",
    "ue.meta.56": "Anmälan av en betydande incident",
    "ue.meta.57": "72 timmar efter kännedom",
    "ue.meta.58": "Slutrapport",
    "ue.meta.59": "en månad efter incidentanmälan",
    "ue.meta.6": "Kommissionens genomförandeförordning (EU) 2024/2690",
    "ue.meta.60": "Incidentanmälan av en tillhandahållare av betrodda tjänster",
    "ue.meta.61": "artikel 21.5 i direktiv (EU) 2022/2555; artiklarna 1 och 2 i förordning (EU) 2024/2690",
    "ue.meta.62": "Utan omsättningsuppgifter är taket det fasta beloppet enligt direktivet.",
    "ue.meta.63": "Taken i artikel 34.4 och 34.5 är miniminivåer (”minst”) — nationell rätt får föreskriva högre. Belopp i euro, utan omräkning till nationell valuta.",
    "ue.meta.64": "Medlemsstatens behöriga myndighet",
    "ue.meta.65": "Ledningsorganet kan hållas ansvarigt för överträdelser av artikel 21. Omfattningen och förfarandet bestäms av nationell rätt — denna modul känner inte till dem.",
    "ue.meta.66": "Omfattningen av ledningens personliga ansvar följer av den nationella lagen. För Polen är det upp till 300 % av ersättningen (artikel 73a.4 i lagen om det nationella cybersäkerhetssystemet); andra medlemsstater reglerar det annorlunda.",
    "ue.meta.7": "EUT L, 2024/2690",
    "ue.meta.8": "Direktiv (EU) 2022/2555",
    "ue.meta.9": "Tidsfristen för införlivande löpte ut den 17 oktober 2024",
    "ue.moduly.1": "ca {p0} min",
    "ue.moduly.10": "Tio områden från artikel 21.2 a–j: från riskstrategi till multifaktorautentisering. Överträdelse medför sanktionsavgift enligt artikel 34. Bedömning på mognadsskala.",
    "ue.moduly.11": "Förordning 2024/2690 — styrning och processer",
    "ue.moduly.12": "Avsnitten 1–5 och 7–8 i bilagan: strategier, riskhantering, incidenthantering, driftskontinuitet, leveranskedja, effektivitetsbedömning, cyberhygien. Direkt tillämplig från den 7 november 2024.",
    "ue.moduly.13": "Förordning 2024/2690 — tekniska krav",
    "ue.moduly.14": "Avsnitten 6 och 9–13 i bilagan: förvärv och utveckling av system, kryptografi, personalsäkerhet, åtkomstkontroll, tillgångsförvaltning, fysisk säkerhet och miljösäkerhet.",
    "ue.moduly.2": "ca {p0} h {p1} min",
    "ue.moduly.3": "ca {p0} h",
    "ue.moduly.4": "mindre än en minut",
    "ue.moduly.5": "Snabb riskbedömning",
    "ue.moduly.6": "Övergripande frågor från alla direktivets områden. Var och en avgör en hel grupp av ämnen. Gör det möjligt att bedöma eftersläpningens omfattning utan att gå igenom hela frågeformuläret.",
    "ue.moduly.7": "Skyldigheter enligt direktivet",
    "ue.moduly.8": "Registreringsuppgifter, incidentrapportering inom 24 och 72 timmar, ledningsorganets skyldigheter, beredskap för tillsyn. Kontrollerbart utifrån dokument, utan teknisk analys.",
    "ue.moduly.9": "Riskhanteringsåtgärder — artikel 21.2",
    "ue.obowiazki.1": "Registreringsuppgifter för förteckningen över entiteter",
    "ue.obowiazki.10": "Rapportering av betydande incidenter",
    "ue.obowiazki.11": "Entiteten anmäler betydande incidenter till CSIRT-enheten eller den behöriga myndigheten i tre steg: tidig varning, incidentanmälan, slutrapport. Tidsfristerna löper från kännedom om incidenten.",
    "ue.obowiazki.12": "Kan entiteten inom 24 timmar från kännedom om en betydande incident lämna en tidig varning med uppgift om huruvida incidenten misstänks ha orsakats av olagliga handlingar och om den kan få gränsöverskridande påverkan?",
    "ue.obowiazki.13": "24 timmar efter kännedom",
    "ue.obowiazki.14": "Kan entiteten inom 72 timmar lämna en incidentanmälan med en inledande bedömning av allvarlighetsgrad och påverkan samt angreppsindikatorer?",
    "ue.obowiazki.15": "72 timmar efter kännedom",
    "ue.obowiazki.16": "Lämnar entiteten senast en månad efter anmälan en slutrapport med beskrivning av incidenten, typ av hot, begränsningsåtgärder och gränsöverskridande påverkan?",
    "ue.obowiazki.17": "en månad efter anmälan",
    "ue.obowiazki.18": "Informerar entiteten mottagarna av sina tjänster om betydande incidenter som kan påverka tillhandahållandet av dessa tjänster negativt?",
    "ue.obowiazki.19": "Informerar entiteten tjänstemottagarna om ett betydande cyberhot och om åtgärder som mottagarna kan vidta?",
    "ue.obowiazki.2": "Medlemsstaterna upprättar en förteckning över väsentliga och viktiga entiteter och kräver att entiteterna lämnar registreringsuppgifter. Förfarandet, tidsfristen och portalen bestäms av nationell rätt.",
    "ue.obowiazki.20": "Om entiteten är en tillhandahållare av betrodda tjänster — anmäler den betydande incidenter inom 24 timmar från kännedom?",
    "ue.obowiazki.21": "gäller tillhandahållare av betrodda tjänster",
    "ue.obowiazki.22": "Ledningsorganet",
    "ue.obowiazki.23": "Ledningsorganet godkänner riskhanteringsåtgärderna, övervakar deras genomförande och kan hållas ansvarigt. Organets ledamöter genomgår regelbundet utbildning.",
    "ue.obowiazki.24": "Har ledningsorganet formellt godkänt de riskhanteringsåtgärder för cybersäkerhet som vidtagits för att uppfylla artikel 21?",
    "ue.obowiazki.25": "Övervakar ledningsorganet genomförandet av dessa åtgärder på ett dokumenterat sätt — till exempel genom regelbundna rapporter och översyner?",
    "ue.obowiazki.26": "Genomgår ledningsorganets ledamöter regelbundet utbildning som gör det möjligt att identifiera risker och bedöma riskhanteringspraxis, och dokumenteras deltagandet?",
    "ue.obowiazki.27": "Beredskap för tillsynsåtgärder",
    "ue.obowiazki.28": "En väsentlig entitet omfattas av förhands- och efterhandstillsyn, en viktig entitet — endast av efterhandstillsyn. Myndigheten får begära information, belägg för genomförandet av strategier och revisionsresultat.",
    "ue.obowiazki.29": "Kan entiteten på myndighetens begäran lägga fram belägg för genomförandet av cybersäkerhetsstrategier, inbegripet resultat av säkerhetsrevisioner?",
    "ue.obowiazki.3": "Har entiteten fastställt om den är en väsentlig eller viktig entitet utifrån sektorn i bilaga I eller II och företagets storlek?",
    "ue.obowiazki.30": "Kan entiteten på myndighetens begäran tillhandahålla de uppgifter, dokument och den information som behövs för att utföra tillsynsuppgifterna?",
    "ue.obowiazki.31": "Är den väsentliga entiteten beredd på en säkerhetsrevision utförd av myndigheten eller ett oberoende organ, på egen bekostnad?",
    "ue.obowiazki.4": "Har entiteten lämnat registreringsuppgifter till den behöriga myndigheten: namn, adress och kontaktuppgifter, sektor och delsektor, förteckning över de medlemsstater där den tillhandahåller tjänster?",
    "ue.obowiazki.5": "Kontaktuppgifterna omfattar e-postadresser, IP-adressintervall och telefonnummer. Den nationella tidsfristen och portalen för registrering bestäms av medlemsstatens rätt.",
    "ue.obowiazki.6": "Finns det ett förfarande för att uppdatera registreringsuppgifterna utan onödigt dröjsmål efter att de ändrats?",
    "ue.obowiazki.7": "Direktivet kräver uppdatering utan onödigt dröjsmål; den konkreta tidsfristen — till exempel 14 dagar i Polen — följer av nationell rätt.",
    "ue.obowiazki.8": "Om entiteten är en leverantör av DNS-tjänster, registreringsenhet för toppdomäner, leverantör av molntjänster, datacentraltjänster, CDN, hanterade tjänster, en marknadsplats online, sökmotor eller ett socialt nätverk — har den lämnat de ytterligare uppgifterna enligt artikel 27, inbegripet adressen till det huvudsakliga verksamhetsstället i unionen?",
    "ue.obowiazki.9": "gäller entiteter enligt artikel 26.1",
    "ue.role.1": "Medlemsstatens behöriga myndighet",
    "ue.role.10": "Datacentraltjänster: samlokalisering, infrastrukturhosting och tillhörande tjänster.",
    "ue.role.11": "Datacentraler",
    "ue.role.12": "Väsentlig entitet över tröskeln för ett medelstort företag (artikel 3.1 a), viktig vid medelstor storlek (artikel 3.2). Under medelstor storlek — utanför tillämpningsområdet, såvida inte medlemsstaten utpekar entiteten enligt artikel 2.2 b–e. Omfattas av förordning 2024/2690.",
    "ue.role.13": "Leverantör av internetknutpunkt",
    "ue.role.14": "Infrastruktur som möjliggör trafikutbyte mellan oberoende nät.",
    "ue.role.15": "Internetknutpunkter",
    "ue.role.16": "Klassificering efter storlek (artikel 3.1 a och 3.2). Förordning 2024/2690 omfattar inte internetknutpunkter — artikel 1 i förordningen innehåller en uttömmande förteckning över adressater.",
    "ue.role.17": "Leverantör av DNS-tjänster",
    "ue.role.18": "Domännamnsupplösningstjänster, med undantag för operatörer av rotnamnservrar.",
    "ue.role.19": "Domännamnssystemet",
    "ue.role.2": "behörig myndighet",
    "ue.role.20": "Väsentlig entitet oavsett storlek (artikel 3.1 b). Omfattas av förordning 2024/2690.",
    "ue.role.21": "Registreringsenhet för toppdomäner",
    "ue.role.22": "Förvaltning av registret för en toppdomän.",
    "ue.role.23": "Väsentlig entitet oavsett storlek (artikel 3.1 b). Därutöver skyldigheter enligt artikel 28 avseende registreringsuppgifter. Omfattas av förordning 2024/2690.",
    "ue.role.24": "Leverantör av molntjänster",
    "ue.role.25": "Molntjänster: infrastruktur, plattform, programvara som tjänst.",
    "ue.role.26": "Molntjänster",
    "ue.role.27": "Klassificering efter storlek (artikel 3.1 a och 3.2). Omfattas av förordning 2024/2690.",
    "ue.role.28": "Leverantör av nätverk för innehållsleverans",
    "ue.role.29": "Nätverk av distribuerade servrar som levererar innehåll och tjänster till slutanvändare.",
    "ue.role.3": "utsedd enligt nationell rätt; tills den nationella modulen införs anger verktyget ingen konkret institution",
    "ue.role.30": "Nätverk för innehållsleverans",
    "ue.role.31": "Tillhandahållare av betrodda tjänster",
    "ue.role.32": "Betrodda tjänster i den mening som avses i förordning (EU) nr 910/2014: underskrifter, stämplar, tidsstämplar, certifikat.",
    "ue.role.33": "Betrodda tjänster",
    "ue.role.34": "Omfattas av direktivet oavsett storlek (artikel 2.2 a ii). En kvalificerad tillhandahållare är en väsentlig entitet oavsett storlek (artikel 3.1 b); en icke-kvalificerad är väsentlig över tröskeln för ett medelstort företag, annars viktig. Omfattas av förordning 2024/2690.",
    "ue.role.35": "Leverantör av hanterade tjänster",
    "ue.role.36": "Förvaltning av kundens IKT-infrastruktur: installation, underhåll, support, systemadministration.",
    "ue.role.37": "Förvaltning av IKT-tjänster (B2B)",
    "ue.role.38": "Hanterade tjänster",
    "ue.role.39": "Leverantör av hanterade säkerhetstjänster",
    "ue.role.4": "Tillhandahållare av allmänna elektroniska kommunikationsnät eller allmänt tillgängliga elektroniska kommunikationstjänster",
    "ue.role.40": "Hanterade cybersäkerhetstjänster: övervakning, incidentrespons, tester, rådgivning.",
    "ue.role.41": "Hanterade säkerhetstjänster",
    "ue.role.42": "Direktivet klassificerar efter storlek (artikel 3.1 a och 3.2). Medlemsstaterna får skärpa tröskeln — Polen betraktar MSSP som väsentlig entitet redan från litet företag; denna modul tillämpar enbart direktivets regel. Omfattas av förordning 2024/2690.",
    "ue.role.5": "Tillhandahållande av allmänna elektroniska kommunikationsnät eller allmänt tillgängliga elektroniska kommunikationstjänster, inbegripet internetanslutning.",
    "ue.role.6": "Digital infrastruktur",
    "ue.role.7": "Elektronisk kommunikation",
    "ue.role.8": "Omfattas av direktivet oavsett storlek (artikel 2.2 a i). Ett medelstort eller större företag är en väsentlig entitet (artikel 3.1 c), mikroföretag och små företag — viktig (artikel 3.2). Den nationella lagen om elektronisk kommunikation kan ålägga ytterligare skyldigheter — denna modul innehåller dem inte.",
    "ue.role.9": "Leverantör av datacentraltjänster",
    "ue.role.podstawaArt3b": "artikel 3.1 b i direktiv (EU) 2022/2555",
    "ue.zaslepki.1": "Europaparlamentets och rådets direktiv (EU) 2022/2555 (NIS 2)",
    "ue.zaslepki.10": "Om vissa entiteter förs in ex officio avgörs av nationell rätt.",
    "ue.zaslepki.11": "Fastställ om ni omfattas av direktivet",
    "ue.zaslepki.12": "Sektor enligt bilaga I eller II och företagets storlek. Denna del sköts av entitetens profil i det här verktyget.",
    "ue.zaslepki.13": "Fastställ den behöriga myndigheten i ert land",
    "ue.zaslepki.14": "Varje land utser en behörig myndighet (artikel 8.1). En aktuell förteckning förs av Enisa och kommissionen.",
    "ue.zaslepki.15": "Lämna registreringsuppgifter",
    "ue.zaslepki.16": "Namn, adress och kontaktuppgifter, sektor och delsektor, länder där tjänster tillhandahålls (artikel 3.4). Förfarande enligt nationell rätt.",
    "ue.zaslepki.17": "Uppdatera uppgifterna utan onödigt dröjsmål",
    "ue.zaslepki.18": "Varje ändring av registreringsuppgifterna kräver uppdatering (artikel 3.5).",
    "ue.zaslepki.19": "adress och aktuella kontaktuppgifter: e-postadresser, IP-adressintervall, telefonnummer",
    "ue.zaslepki.2": "EUT L 333, 27.12.2022, s. 80",
    "ue.zaslepki.20": "sektor och delsektor enligt bilaga I eller II",
    "ue.zaslepki.21": "förteckning över de medlemsstater där entiteten tillhandahåller tjänster",
    "ue.zaslepki.22": "Bestäms av nationell rätt.",
    "ue.zaslepki.23": "Direktiv (EU) 2022/2555 — artikel 3",
    "ue.zaslepki.24": "Enisa — medlemsstaternas behöriga myndigheter",
    "ue.zaslepki.25": "Direktiv (EU) 2022/2555",
    "ue.zaslepki.26": "EU-modulen innehåller inga riktlinjer från den nationella myndigheten — de kommer med modulen för nationell rätt.",
    "ue.zaslepki.27": "Automatisk hämtning av registeruppgifter fungerar endast för länder med modul för nationell rätt. Fyll i profilen manuellt.",
    "ue.zaslepki.28": "Inläsning av årsredovisning fungerar endast för länder med modul för nationell rätt. Ange intäkter och personalstyrka manuellt.",
    "ue.zaslepki.3": "Kommissionens genomförandeförordning (EU) 2024/2690",
    "ue.zaslepki.4": "EUT L, 2024/2690, 18.11.2024",
    "ue.zaslepki.5": "NIS 2-direktivet innehåller inget separat lager för elektronisk kommunikation. Nationell rätt om elektronisk kommunikation kan ålägga ytterligare skyldigheter — denna modul känner inte till dem.",
    "ue.zaslepki.6": "Förteckning över väsentliga och viktiga entiteter",
    "ue.zaslepki.7": "Medlemsstatens behöriga myndighet.",
    "ue.zaslepki.8": "Direktivet ålägger medlemsstaterna att föra en förteckning över väsentliga och viktiga entiteter och att kräva att entiteterna lämnar registreringsuppgifter. Portalen, förfarandet och tidsfristen bestäms av nationell rätt — denna modul känner inte till dem, eftersom modulen för nationell rätt för det valda landet ännu inte är klar.",
    "ue.zaslepki.9": "Alla väsentliga och viktiga entiteter. Tidsfristen bestäms av nationell rätt.",
    "ue.zaslepki.skrotDyrektywy": "NIS 2-direktivet",
    "ue.zaslepki.skrotReg2690": "Förordning 2024/2690",
    "xlsx.1": "{p0} – {p1} euro",
    "xlsx.25": "Växelkurs",
    "xlsx.4": "RAPPORT OM EFTERLEVNAD AV NIS 2-DIREKTIVET (EU) 2022/2555",
    "xlsx.58": "Elektronisk kommunikationsverksamhet: förordning (EU) 2024/2690 gäller inte. Tröskelvärdena bestäms av nationell rätt (artikel 23.11 i direktivet) — den gemensamma modulen känner inte till dem.",
    "xlsx.68": "Verktyget är avsett för självbedömning. Det är varken en revision eller juridisk rådgivning.",
    "xlsx.69": "För entiteter som inte omfattas av förordning (EU) 2024/2690 bestäms tröskelvärdena för en betydande incident av nationell rätt (artikel 23.11 i direktivet).",
    "xlsx.70": "Rollerna som anges i profilen är en deklaration. Statusen avgörs av den verksamhet som faktiskt bedrivs (artikel 3 i direktiv (EU) 2022/2555).",
    "xlsx.etykietaKrs": "Registernummer",
    "xlsx.etykietaNip": "Identifieringsnummer",
    "xlsx.etykietaRegon": "Statistiknummer"
});
