/* Teksty interfejsu zależne od prawa polskiego — po polsku.

   Te same klucze co w locale/<jezyk>.js, ale treść nazywa ustawę o KSC,
   jej artykuły, organy, rejestry (NIP, KRS, PKD, RPT), złote i terminy
   krajowe. Ładowarka nakłada je na słownik języka po załadowaniu
   modułu kraju, więc interfejs w innym języku pokazuje te fragmenty
   po polsku — moduł krajowy jest pisany w języku swojego państwa. */
KRAJE.napisy('pl', 'pl', {
    "app.10": "Zweryfikuj listę ról niżej — o statusie decyduje działalność faktycznie wykonywana (art. 5 ustawy o KSC), a nie wpis w rejestrze.",
    "app.14": "Rok wcześniej: {p0} zł",
    "app.15": "Przychód za okres sprawozdawczy: {p0} zł",
    "app.19": "Odpytuję rejestry po numerze NIP {p0}…",
    "app.34": " mld zł",
    "app.35": " mln zł",
    "app.36": " tys. zł",
    "app.37": " · poniżej progu 10 mln zł z art. 67b ust. 1 pkt 2",
    "app.4": "Numer NIP jest niepoprawny — sprawdź cyfrę kontrolną.",
    "app.59": "Ocena zgodności z ustawą o KSC (JSON)",
    "app.68": "Dane po numerze NIP będą pobierane z rejestrów publicznych automatycznie.",
    "app.69": "Narzędzie pobiera dane z rejestrów publicznych po numerze NIP. Kliknij, aby to wyłączyć.",
    "app.73": " · rachunek zysków i strat w wariancie ",
    "app.74": "<div class=\"mt-2 tekst-uwaga\">Z kodów PKD nie wynika żadna rola z sektora infrastruktury cyfrowej. Wskaż role ręcznie niżej.</div>",
    "app.8": "Potwierdzono wpis do rejestru przedsiębiorców telekomunikacyjnych",
    "app.progDostawcy": " · powyżej progu 10 mln zł — termin wycofania sprzętu dostawcy wysokiego ryzyka skraca się z 7 do 4 lat",
    "app.przyklad.adres": "ul. Przykładowa 1, 00-001 Miasto",
    "app.przyklad.forma": "SPÓŁKA Z OGRANICZONĄ ODPOWIEDZIALNOŚCIĄ",
    "app.przyklad.nazwa": "Przykładowy Operator sp. z o.o.",
    "app.statusVat": " · status VAT: ",
    "dashboard.1": "Na podstawie zadeklarowanych ról i wielkości podmiot nie jest podmiotem kluczowym ani ważnym w rozumieniu ustawy o KSC. Zweryfikuj profil, jeżeli wynik jest niezgodny z oczekiwaniem.",
    "dashboard.113": "Częste pytania — stanowisko Ministerstwa Cyfryzacji",
    "dashboard.12": "— {p0}, w brzmieniu nadanym ustawą z 23 stycznia 2026 r. ({p1}), obowiązuje od {p2}",
    "dashboard.123": "Ustawa o KSC",
    "dashboard.30": "Wykaz podmiotów i System S46",
    "dashboard.4": "— stosowane bezpośrednio od {p0}; do prawa polskiego wprowadzone przez art. 8b ustawy o KSC",
    "dashboard.42": "Wariant kwotowy: {p0} (kurs {p1} zł/EUR)",
    "dashboard.45": "Kryteria z art. 53 ust. 12:",
    "dashboard.46": "Łącznie z obu ustaw",
    "dashboard.49": "Podmiot prowadzi działalność telekomunikacyjną, więc osoba zarządzająca odpowiada",
    "dashboard.50": "równolegle na podstawie dwóch ustaw",
    "dashboard.51": "— ustawy o KSC przed organem właściwym oraz Prawa komunikacji elektronicznej przed Prezesem UKE. Są to kary odrębne, niezależne od siebie i od kary nałożonej na przedsiębiorcę.",
    "dashboard.53": "Kara okresowa za zwłokę w wykonaniu decyzji: od {p0} zł do {p1} zł za każdy dzień ({p2})",
    "dashboard.54": "Przypadek kwalifikowany: do {p0} zł ({p1})",
    "dashboard.57": "({p0}). Obowiązki wdrożeniowe biegną jednak już teraz — termin realizacji obowiązków\r\n          rozdziału 3 upływa 3 kwietnia 2027 r.",
    "dashboard.65": "({p0}). Do tego czasu ryzyko finansowe nie jest jeszcze wymagalne, natomiast obowiązki\r\n          wdrożeniowe biegną już teraz — termin realizacji obowiązków rozdziału 3 upływa 3 kwietnia 2027 r.",
    "dashboard.83": "Działalność telekomunikacyjna — stan otwarty.",
    "dashboard.84": "Rozporządzenie (UE) 2024/2690 nie ma zastosowania do\r\n          przedsiębiorców komunikacji elektronicznej, a progi krajowe określi dopiero rozporządzenie Rady Ministrów wydane na\r\n          podstawie art. 11 ust. 4 ustawy o KSC. Do czasu jego wydania obowiązują dotychczasowe przepisy wykonawcze.\r\n          Narzędzie nie podaje tu wartości liczbowych, ponieważ nie zostały jeszcze ustalone.",
    "dashboard.terminRejestracji": "Termin to 6 miesięcy od spełnienia przesłanek — dla podmiotów objętych ustawą od 3 kwietnia 2026 r. upływa 3 października 2026 r. Samorejestracja ruszyła 7 maja 2026 r., więc realne okno jest krótsze niż pół roku.",
    "html.1": "ITORO — Ocena zgodności z ustawą o KSC (wdrożenie NIS 2)",
    "html.10": "Ocena zgodności z ustawą o krajowym systemie cyberbezpieczeństwa (KSC)",
    "html.100": "Jeden plik uzupełnia <strong>komplet danych</strong>: nazwę, NIP, KRS, adres oraz <strong>przychód</strong> za rok obrotowy — a od niego zależy wysokość kary.",
    "html.102": "Szybsze, ale <strong>bez przychodu</strong>. Za to potwierdza wpis do rejestru przedsiębiorców telekomunikacyjnych i podpowiada role na podstawie PKD.",
    "html.11": "Ustawa wdraża dyrektywę (UE) 2022/2555 (NIS 2). Ocena obejmuje także\r\n          rozporządzenie wykonawcze Komisji (UE) 2024/2690 oraz Prawo komunikacji\r\n          elektronicznej (PKE) — w zakresie, w jakim dotyczą podmiotu.",
    "html.23": "sprawozdanie finansowe z KRS albo NIP wypełniają resztę automatycznie",
    "html.33": "ustawa z 5 lipca 2018 r. o krajowym systemie cyberbezpieczeństwa (KSC), w brzmieniu nadanym nowelizacją z 23 stycznia 2026 r.",
    "html.33a": "ustawa z 12 lipca 2024 r. — Prawo komunikacji elektronicznej (PKE)",
    "html.35": "załącznik nr 4 do ustawy o KSC — dla podmiotów publicznych o statusie podmiotu ważnego",
    "html.36": "Narzędzie służy samoocenie. Nie jest audytem w rozumieniu\r\n            art. 15 ustawy o KSC ani opinią prawną.",
    "html.40": "jedyne połączenie wychodzące to odpytanie rejestrów publicznych — wysyłany jest wyłącznie numer NIP",
    "html.59": "Pobierz z RDF",
    "html.60": "Przyjmuje plik XML albo archiwum ZIP pobrane z Repozytorium Dokumentów Finansowych KRS.\r\n                  Sam plik czytany jest wyłącznie w tej przeglądarce. Numer NIP odczytany ze sprawozdania\r\n                  posłuży do automatycznego dobrania reszty danych i ról.",
    "html.62": "Wyszukanie po numerze NIP",
    "html.63": "sugerowane role na podstawie kodów PKD",
    "html.64": "wpis do rejestru przedsiębiorców telekomunikacyjnych",
    "html.66": "NIP podmiotu",
    "html.68": "Odpytuje wykaz podatników VAT, Krajowy Rejestr Sądowy i rejestr Prezesa UKE.\r\n                  Pobieranie uruchamia się automatycznie po wpisaniu poprawnego numeru.",
    "html.76": "Roczny przychód (zł)",
    "html.78": "Przychód z działalności telekomunikacyjnej (zł)",
    "html.79": "Powyżej 10 mln zł skraca termin wycofania sprzętu dostawcy wysokiego ryzyka z 7 do 4 lat (art. 67b ust. 1 pkt 2).",
    "html.80": "Miesięczne wynagrodzenie kierownika (zł)",
    "html.82": "Kurs EUR/PLN",
    "html.83": "Średni kurs NBP z 31 grudnia roku poprzedzającego rok wydania decyzji.",
    "html.84": "Status wynika wyłącznie z agregacji danych przedsiębiorstw powiązanych, a system informacyjny podmiotu jest niezależny (art. 5 ust. 6 i 7)",
    "html.85": "Podmiot podlega Ministrowi Obrony Narodowej lub jest przez niego nadzorowany",
    "html.91": "Ocena zgodności z ustawą z dnia 5 lipca 2018 r. o krajowym systemie cyberbezpieczeństwa (KSC),\r\n        wdrażającą dyrektywę (UE) 2022/2555 (NIS 2), z rozporządzeniem wykonawczym Komisji (UE) 2024/2690\r\n        oraz z ustawą z dnia 12 lipca 2024 r. — Prawo komunikacji elektronicznej (PKE).",
    "html.94": "czy podmiot jest <strong>kluczowy</strong>, <strong>ważny</strong>, czy poza ustawą",
    "html.daneZeSprawozdania": "nazwa, NIP, KRS, adres siedziby",
    "html.tytulNaglowka": "Ocena zgodności z ustawą o KSC",
    "klasyfikacja.10": "art. 5 ust. 1 pkt 2 ustawy o KSC (przedsiębiorca komunikacji elektronicznej co najmniej spełniający wymogi dla średniego przedsiębiorcy)",
    "klasyfikacja.11": "art. 5 ust. 2 pkt 4 ustawy o KSC (przedsiębiorca komunikacji elektronicznej będący mikro- lub małym przedsiębiorcą)",
    "klasyfikacja.12": "art. 5 ust. 1 pkt 3 ustawy o KSC (dostawca usług zarządzanych w zakresie cyberbezpieczeństwa będący co najmniej małym przedsiębiorcą)",
    "klasyfikacja.13": "Mikroprzedsiębiorca nie jest objęty ustawą z tytułu tej roli (art. 5 ust. 1 pkt 3 a contrario).",
    "klasyfikacja.15": "art. 5 ust. 1 pkt 4 lit. b ustawy o KSC (kwalifikowany dostawca usług zaufania) — niezależnie od wielkości przedsiębiorstwa",
    "klasyfikacja.16": "art. 5 ust. 2 pkt 3 ustawy o KSC (niekwalifikowany dostawca usług zaufania będący mikro-, małym lub średnim przedsiębiorcą)",
    "klasyfikacja.18": "art. 5 ust. 2 pkt 8 ustawy o KSC (samorządowy podmiot publiczny realizujący zadanie publiczne z wykorzystaniem systemów informacyjnych)",
    "klasyfikacja.19": "art. 5 ust. 1 pkt 4 lit. d ustawy o KSC w związku z załącznikiem nr 1 (urząd gminy zatrudniający co najmniej 50 osób w przeliczeniu na pełny etat)",
    "klasyfikacja.2": "Nadzór prewencyjny i następczy (art. 53 ust. 3 pkt 1 ustawy o KSC).",
    "klasyfikacja.20": "art. 5 ust. 2 pkt 8 ustawy o KSC (urząd gminy poniżej progu 50 etatów pozostaje samorządową jednostką budżetową z załącznika nr 2)",
    "klasyfikacja.21": "Poniżej progu 50 etatów urząd gminy jest podmiotem ważnym, więc zamiast pełnego art. 8 ust. 1 realizuje węższy katalog z załącznika nr 4 (art. 8 ust. 3).",
    "klasyfikacja.22": "Podmioty podległe Ministrowi Obrony Narodowej lub przez niego nadzorowane są wyłączone ze stosowania ustawy na zasadach ogólnych (art. 5 ust. 10). MON wskazuje własne podmioty decyzją niepodlegającą ogłoszeniu (art. 5 ust. 11). Wynik oceny należy zweryfikować z MON jako organem właściwym (art. 41 pkt 9).",
    "klasyfikacja.23": "Podmiot spełnia kryteria zarówno podmiotu kluczowego, jak i ważnego. Zgodnie z art. 5 ust. 4 ustawy o KSC jest podmiotem kluczowym, a wyższe wymagania stosuje się do całej działalności objętej ustawą.",
    "klasyfikacja.25": "Złagodzony katalog z załącznika nr 4 przysługuje tylko podmiotowi ważnemu (art. 8 ust. 3). Ponieważ podmiot jest kluczowy, obowiązuje go pełny katalog środków z art. 8 ust. 1 — ocena obejmuje szerszy zestaw pytań, niż wynikałoby z samej roli podmiotu publicznego.",
    "klasyfikacja.26": "Jako podmiot ważny będący podmiotem publicznym nie stosujecie art. 8 ust. 1, tylko zamknięty katalog z załącznika nr 4 (art. 8 ust. 3). Odpada wczesne ostrzeżenie w 24 godziny oraz sprawozdania okresowe, z postępu i końcowe — pozostaje zgłoszenie incydentu poważnego (art. 12c). Kara dla kierownika wynosi do 100 %, a nie 300 % wynagrodzenia (art. 73a ust. 5), i nie stosuje się zakazu pełnienia funkcji zarządczych (art. 53 ust. 10). Nie ma też obowiązku audytu z art. 15 — jego odpowiednikiem jest coroczny przegląd systemu.",
    "klasyfikacja.28": "Obowiązki podmiotu publicznego powstają w zakresie, w jakim wykorzystuje on system informacyjny do realizacji zadania publicznego (art. 16d). Kilka jednostek może też wykonywać je wspólnie przy pomocy jednostki wyznaczonej — na przykład centrum usług wspólnych albo urzędu wojewódzkiego (art. 16e i 16f).",
    "klasyfikacja.29": "Zadeklarowano, że status podmiotu wynika wyłącznie z agregacji danych przedsiębiorstw powiązanych lub partnerskich, a system informacyjny podmiotu jest niezależny i nie służy do wspólnego świadczenia usług. W takim przypadku podmiot nie jest podmiotem kluczowym ani ważnym (art. 5 ust. 6 i 7 ustawy o KSC). Przesłankę należy udokumentować.",
    "klasyfikacja.4": "Nadzór wyłącznie następczy, w szczególności w razie uzasadnionego podejrzenia naruszenia (art. 53 ust. 3 pkt 2 ustawy o KSC).",
    "klasyfikacja.5": "Poza zakresem ustawy",
    "klasyfikacja.6": "Brak obowiązków wynikających z ustawy o KSC dla wskazanej roli.",
    "klasyfikacja.7": "art. 5 ust. 1 pkt 1 ustawy o KSC (podmiot z załącznika nr 1 przewyższający wymogi dla średniego przedsiębiorcy)",
    "klasyfikacja.8": "art. 5 ust. 2 pkt 1 ustawy o KSC (podmiot z załącznika nr 1 spełniający kryteria średniego przedsiębiorcy)",
    "klasyfikacja.9": "Mikro- i mali przedsiębiorcy nie są objęci ustawą z tytułu tej roli (art. 5 ust. 1 pkt 1 i ust. 2 pkt 1 a contrario).",
    "kreator.10": "Przychód za poprzedni rok przepiszesz stąd ręcznie — rejestr nie udostępnia go przez API.",
    "kreator.35": "<span class=\"text-secondary\">Podaj numer KRS, aby otworzyć sprawozdania finansowe.</span>",
    "kreator.37": "Wyszukaj podmiot po nazwie, numerze KRS albo NIP, pobierz sprawozdanie i wczytaj je tutaj.",
    "kreator.56": "Tak — rozporządzenie unijne stosuje się bezpośrednio od 7 listopada 2024 r. i nie ma\r\n        okresu przejściowego. W prawie polskim obowiązek jego stosowania wprowadza",
    "kreator.57": ", dodany nowelizacją z 23 stycznia 2026 r.\r\n        Ponieważ art. 8b należy do rozdziału 3 ustawy, termin wdrożenia wynosi 12 miesięcy\r\n        od jej wejścia w życie, czyli upływa",
    "kreator.58": ", a kary mogą\r\n        zostać nałożone najwcześniej 3 kwietnia 2028 r. Wymogi techniczne z załącznika\r\n        (sekcje 6 i 9–13) są wiążące w obecnym brzmieniu — nie czekają na doprecyzowanie.\r\n        Odstąpić można tylko od wymogów opatrzonych formułą „w stosownych przypadkach”,\r\n        i wyłącznie dokumentując uzasadnienie.",
    "kreator.9": "Sprawozdania finansowe w RDF →",
    "kreator.przepisReg2690": "art. 8b ustawy o KSC",
    "kreator.terminReg2690": "3 kwietnia 2027 r.",
    "punktacja.10": "Załącznik 4",
    "punktacja.4": "Ustawa o KSC — art. 8",
    "punktacja.5": "Ustawa o KSC — obowiązki formalne",
    "punktacja.8": "Prawo komunikacji elektronicznej",
    "punktacja.9": "Ustawa o KSC — załącznik nr 4",
    "punktacja.skrotKsc": "KSC",
    "punktacja.skrotPke": "PKE",
    "reg2690.odeslanieKrajowe": "art. 8b ustawy o KSC",
    "reg2690.zaufaniaUwagaKrajowa": " Uwaga na równoległy termin krajowy — art. 11 ust. 1a ustawy o KSC wymaga od dostawcy usług zaufania zgłoszenia incydentu poważnego w ciągu 24 godzin od wykrycia.",
    "xlsx.1": "{p0} – {p1} zł",
    "xlsx.25": "Kurs EUR/PLN",
    "xlsx.4": "RAPORT ZGODNOŚCI Z USTAWĄ O KSC (WDROŻENIE NIS 2)",
    "xlsx.58": "Działalność telekomunikacyjna: rozporządzenie (UE) 2024/2690 nie ma zastosowania. Progi krajowe określi rozporządzenie Rady Ministrów wydane na podstawie art. 11 ust. 4 ustawy o KSC — nie zostały jeszcze ustalone.",
    "xlsx.68": "Narzędzie służy samoocenie. Nie jest audytem w rozumieniu art. 15 ustawy o KSC ani opinią prawną.",
    "xlsx.69": "Progi uznania incydentu za poważny dla podmiotów nieobjętych rozporządzeniem (UE) 2024/2690 nie zostały jeszcze określone — art. 11 ust. 4 ustawy o KSC.",
    "xlsx.70": "Kody PKD pobrane z rejestrów jedynie sugerują role. O statusie decyduje faktycznie wykonywana działalność (art. 5 ustawy o KSC).",
    "xlsx.etykietaKrs": "KRS",
    "xlsx.etykietaNip": "NIP",
    "xlsx.etykietaRegon": "REGON"
});
